### ISSUE TITLE
Problem with timestamp

### ISSUE THREAD

**Issue by sttachoires** [laurenz/oracle_fdw#100]
Hi, and thank you for your work :)

I met a problem with timestamp. There a table (Oracle) with a timestamp.
I need to insert and update it from a PostgreSQL client, so, import server, schema limit to this table, send insert request and then meet:

```
insert into statdb.postgresql_instance_detail (timestamp, hostname, sid, logical_host, rdbms_version, used_data_m, default_character_set, version, port, creation_date, supervision, backup, archivelog_m, xlog_m) values (current_timestamp, '${_hostname}','${_sid}','${_logical_host}','${_rdbms_version}','${_used_data_m}','${_default_character_set}','${_version}','${_port}',to_timestamp('${_creation}', 'YYYYMMDDHH24MISS'), '${_supervision}', '${_backup}', '${_archivelog_m}', '${_xlog_m}')

ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-01856: BC/B.C. or AD/A.D. required
```
The oracle_diag
```
SELECT oracle_diag();
                                             oracle_diag                                             
-----------------------------------------------------------------------------------------------------
 oracle_fdw 1.4.0, PostgreSQL 9.5.3, Oracle client 11.2.0.4.0, ORACLE_HOME=/tech/oracle/client/11204
(1 row)
```

**Comment by legrandlegrand** [comment]
I'm just a user (not the owner of oracle_fdw)
maybe that latest commit is for you too 

 https://github.com/laurenz/oracle_fdw/commit/52865b31013fcd60f33d7ce81a57401794b0b9e5

**Comment by laurenz** [comment]
Yes, I suspect @legrandlegrand is right (unless there are other timestamp bugs lurking; this it turning into a never-ending story).

Coul you try with the latest version from git and see if that solves your problem?

**Comment by houmanb** [comment]
Hi,
First of all thank you for your excellent work with oracle_fdw.
I might have a similar problem with TIMESTAMP  data type. 
I updated my sources to the latest possible version.

```sql
SELECT oracle_diag();
                                                          oracle_diag                                                           
--------------------------------------------------------------------------------------------------------------------------------
 oracle_fdw 1.4.0, PostgreSQL 9.4.4, Oracle client 11.2.0.4.0, ORACLE_HOME=$ORACLE_BASE/instantclient_11_2, TNS_ADMIN=$HOME/etc
(1 row)
```

I tried to find out which type of data are passed to the "checkDataType" function.
It turned out that the TIMESTAMP has been mapped to ORA_TYPE_NUMBER.
I just added a few lines to your code in order to get this information.

My foreign table looks like:
```sql
CREATE FOREIGN TABLE FDW_PARTNO_TIMESTAMP (
	partno INTEGER,
	stamp  TIMESTAMP
) SERVER oradb OPTIONS (schema 'RATEADMIN', table 'BO_ZE_PKV_K_M354');

```
Using sqlplus® directly to the source database I get the following result:

```sql
SQL>  SLECT partno, stamp FROM RATEADMIN.BO_ZE_PKV_K_M354 WHERE rownum=1;
    PARTNO | STAMP
------------------------------------------------
8          | 2005-09-01 00:00:00.000000000 AD

```
But using oracle_fdw ( I just added the second error to oracle_fdw.c at the end of the function checkDataType) in order to get the corresponding actual oraType.

```sql
pal=# select * from FDW_PARTNO_TIMESTAMP limit 1;
ERROR:  column "stamp" of foreign table "fdw_partno_timestamp" cannot be converted to or from Oracle data type
ERROR:  oraType_String="ORA_TYPE_NUMBER"
```

my .oracle_profile file looks like this:
```bash
postgres@pluto:~$ cat .oracle_profile 
export ORACLE_BASE=/opt/oracle
export ORACLE_HOME=$ORACLE_BASE/instantclient_11_2
export PATH=$ORACLE_HOME:$PATH
export TNS_ADMIN=$HOME/etc
export NLS_LANG=AMERICAN_America.UTF8
```

Any kind of help or hint would be very appreciated.
Best regards

**Comment by sttachoires** [comment]
Sorry for the response time :/
So, last master installed, very same problem:
{code}
ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-01856: BC/B.C. or AD/A.D. required
{code}

I've made some tests fooling the driver by changing postgresql foreign table timestamp column to char varying (still a timestamp at Oracle side).
When inserting to_stringed timestamp it works fine.

Hope it'll help :/

**Comment by houmanb** [comment]
Hi,
The error was on my side:
I am not allowed to change the order or the number of columns from the oracle source table in my fdw table. The association of columns is based on nothing less (or more) than the index of the column in the source table.

Thanks

**Comment by laurenz** [comment]
@houmanb: Yes, your problem was unrelated to this thread. Unless you are certain that you are talking about the same issue, I'd recommend opening a new one to avoid confusing problems.

@sttachoires: Could you please tell me the table definitions in Oracle and PostgreSQL and the query that you ran?

**Comment by sttachoires** [comment]
Oracle side:
```
desc statdb.postgresql_instance_detail;
 Name					   Null?    Type
 ----------------------------------------- -------- ----------------------------
 TIMESTAMP					    DATE
```

PostgreSQL side:
```
\des+
                                                                                                    List of foreign servers
  Name  |  Owner   | Foreign-data wrapper | Access privileges | Type | Version |                                                           FDW Opt
ions                                                           | Description 
--------+----------+----------------------+-------------------+------+---------+------------------------------------------------------------------
---------------------------------------------------------------+-------------
 tec04c | postgres | oracle_fdw           |                   |      |         | (dbserver '(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=lh-tec04-db.
france.airfrance.fr)(PORT=1552))(CONNECT_DATA=(SID=TEC04C)))') | 
(1 row)
\deu
List of user mappings
 Server | User name 
--------+-----------
 tec04c | postgres
 tec04c | statdb
(2 rows)
\det+ pgref.*
                                                List of foreign tables
 Schema |           Table            | Server |                       FDW Options                       | Description 
--------+----------------------------+--------+---------------------------------------------------------+-------------
 pgref  | postgresql_backup_jobs     | tec04c | (schema 'STATDB', "table" 'POSTGRESQL_BACKUP_JOBS')     | 
 pgref  | postgresql_instance_detail | tec04c | (schema 'STATDB', "table" 'POSTGRESQL_INSTANCE_DETAIL') | 
 pgref  | postgresql_server_detail   | tec04c | (schema 'STATDB', "table" 'POSTGRESQL_SERVER_DETAIL')   | 
(3 rows)
\d+ pgref.postgresql_instance_detail
                                     Foreign table "pgref.postgresql_instance_detail"
        Column         |              Type              | Modifiers | FDW Options  | Storage  | Stats target | Description 
-----------------------+--------------------------------+-----------+--------------+----------+--------------+-------------
 timestamp             | timestamp(0) without time zone |           |              | plain    |              | 

\dx
                        List of installed extensions
    Name    | Version |   Schema   |              Description               
------------+---------+------------+----------------------------------------
 oracle_fdw | 1.1     | public     | foreign data wrapper for Oracle access

```

```
insert into pgref.postgresql_instance_detail (timestamp) values (current_date);
ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-01856: BC/B.C. or AD/A.D. required
```

**Comment by laurenz** [comment]
Ok, I see where the problem is.
I'll fix it tomorrow.

**Comment by laurenz** [comment]
Could you check if this commit actually fixed your bug?

**Comment by sttachoires** [comment]
I'm on holiday now :/ so I'll try it as soon as possible on monday
Thanks for your work anyway :)

2016-07-06 16:01 GMT+02:00 Laurenz Albe <notifications@github.com>:

> Could you check if this commit actually fixed your bug?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/laurenz/oracle_fdw/issues/100#issuecomment-230780235>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANWTOMRbMEKSxSH_pw61YfxZ2-D4k7Vzks5qS7U_gaJpZM4I8gJB>
> .
>



-- 
"Vous avez cru jusqu’à ce jour qu’il y avait des tyrans ? Et bien ! vous
vous êtes trompés, il n’y a que des esclaves : là où nul n’obéit, personne
ne commande."
  -- Anselme Belleguarrigue

**Comment by sttachoires** [comment]
I check, it works.
Evethings seems fine. Thanks again.
