### ISSUE TITLE
Could not load oracle_fdw.dll

### ISSUE THREAD

**Issue by akinba** [laurenz/oracle_fdw#101]
Hi,

I have a "PostgreSQL 9.5.3, compiled by Visual C++ build 1800, 64-bit" database on windows7.
I have download oracle_fdw-1.4.0-pg95-win64.zip from github and copy each file under C:\Program Files\PostgreSQL\9.5 ...\  same directory in zipfile

I can see oracle_fdw in extension list by using pgAdmin and when i try to create extension occurs error below

```
---------------------------
pgAdmin III
---------------------------
An error has occurred:

ERROR:  could not load library "C:/Program Files/PostgreSQL/9.5/lib/oracle_fdw.dll": unknown error 193
---------------------------
Tamam   
---------------------------

```

Did i miss something?

**Comment by laurenz** [comment]
Could it be that you have a 32-bit Oracle client installed?
Please double-check.

Is `oci.dll` in the `PATH` so that the PostgreSQL server can find it? Maybe restart the PostgreSQL server to be certain.

**Comment by akinba** [comment]
U are right, i have had 32bit ODAC provider :) , so Postgresql find  

> D:\ODAC_ORACLE\product\11.2.0\client_1\oci.dll

![image](https://cloud.githubusercontent.com/assets/10282149/16340483/0b57091e-3a31-11e6-8a33-8bc7e65ffe7f.png)


I m going to install 32bit PostgreSQL 9.5 Server and retry

**Comment by laurenz** [comment]
Why not install a 64-bit Oracle client? That might be simpler.
