### ISSUE TITLE
On the version number issue

### ISSUE THREAD

**Issue by gleu** [laurenz/oracle_fdw#102]
Hi,

I've seen your reply to David and I kinda agree with you. But still, it's hard to know if you run 1.1 or 1.3 or even 1.4 on a specific server. You probably should add a function that gives the release number of the extension's library. Otherwise, it's quite difficult to know if you're using the right release with all the fixes. Or is there already a way?

Thanks.

**Comment by laurenz** [comment]
SELECT oracle_diag();

shoul give you the version of oracle_fdw that is installed.
Is that what you are asking for?

**Comment by gleu** [comment]
That's exactly what I wanted. I should have found that myself. Sorry.

And thanks for the quick answer!
