### ISSUE TITLE
CREATE RULE not working on foreign tables

### ISSUE THREAD

**Issue by fnicollet** [laurenz/oracle_fdw#103]
Hello,

Might be an issue more related to postgres than to this specific FDW but if you have an idea ...
I have a foreign table working well and I need to prevent deletion on this table. Usually, I use this:
>> CREATE or replace RULE esp_del_protect AS ON DELETE TO esi.esi_esp_carto_espace
DO INSTEAD NOTHING;

But in the case of a foreign table, I get the following error:
>> ERREUR:  « esi_esp_carto_espace » n'est pas une table ou une vue

Which is French for:
>> ERROR: « esi_esp_carto_espace » is not a table nor a view

So I guess it could be more of a postgresql issue, or it is driver specific?

Thanks,

**Comment by fnicollet** [comment]
By the way, if anyone is having the same issue, the solution is to prevent deletion via a trigger:
```sql
CREATE or replace FUNCTION prevent_delete() RETURNS TRIGGER AS '
     BEGIN
         RETURN NULL;
     END;
' LANGUAGE 'plpgsql';
create trigger esp_prevent_delete before delete on esi.test for each row EXECUTE PROCEDURE prevent_delete();
```

Still, wondering wether this is a pg limitation or a driver one

**Comment by laurenz** [comment]
That's a limitation of PostgreSQL.

You can define triggers on foreign tables, but no rules.

**Comment by fnicollet** [comment]
Thanks!
Tiny question while you are here, I used oracle_fdw 1.4.0 but realized that PK were not correctly imported, so I looked and noticed https://github.com/laurenz/oracle_fdw/issues/83 which has a fix in 1.5.0.
I downloaded the source files on my linux machine, reran make and make install, restarted postgresql, dropped/create extension oracle_fdw (not sure if necessary) and ran SELECT oracle_diag();. But I still get:
>> "oracle_fdw 1.4.0, PostgreSQL 9.5.3, Oracle client 12.1.0.2.0"
Is the version upgraded just when you do a github release or is there a step I am not doing?

**Comment by laurenz** [comment]
Right, I only change the version number when I make a new release.
Maybe it would be good to use something like `1.5.0devel` to highlight the difference&hellip;

**Comment by fnicollet** [comment]
Yes, that would be nice :). 

So it seems that my primary key is not imported then, even with current master. 
Once IMPORT FOREIGN SCHEMA is already done, is there a way to set a column as primary key? I don't really want to manually CREATE FOREIGN TABLE with the key option, as I would need to give it the names of the 100+ columns

**Comment by laurenz** [comment]
I' be interested to see your case where primary keys are not imported, maybe there is a problem I can fix.
To add a primary key after import, use

    ALTER FOREIGN TABLE tab ALTER col OPTIONS (ADD key 'true');

**Comment by fnicollet** [comment]
I'll add another issue about it, this one is drifting away from the original issue
