### ISSUE TITLE
Define a primary key after import foreign schema

### ISSUE THREAD

**Issue by fnicollet** [laurenz/oracle_fdw#104]
I am using current oracle_fdw master on a PG 9.5 DB / oracle client 12.1
After running IMPORT FOREIGN SCHEMA, the primary key is not recognized, so I can't run any insert / update. Following @laurenz advice, I tried running:
> ALTER FOREIGN TABLE esi."esi_esp_carto_espace" ALTER id_esi_esp_carto_espace OPTIONS (ADD key 'true');

Which gave me an error saying that the option was provided more that once. So instead, I ran SET instead of ADD
> ALTER FOREIGN TABLE esi."esi_esp_carto_espace" ALTER id_esi_esp_carto_espace OPTIONS (SET key 'true');

Which worked, but postgres still doesn't see id_esi_esp_carto_espace as [PK], it is just a bigint with no constraint

**Comment by laurenz** [comment]
Well, if you got the message

    ERROR:  option "key" provided more than once

that means that `IMPORT FOREIGN SCHEMA` successfully imported the primary key definition.
The problem must be with the way that you are displaying the foreign table.

I *guess* that you are using pgAdmin III, which has a bug that keeps it from showing column options in foreign tables.
Try `\d tab`in `psql`, that should work fine.
Or run the following query:

    SELECT c.attname, c.attfdwoptions
    FROM pg_class t
         JOIN pg_attribute c ON c.attrelid = t.oid
    WHERE t.relname = 'esi_esp_carto_espace'
       AND c.attnum > 0 AND NOT c.attisdropped
    ORDER BY c.attnum;

**Comment by fnicollet** [comment]
Ah once again, you are absolutely right! pgAdmin doesn't show [PK] when you do a select, but insert/update indeed work
I guess upgrading to current master actually fixed the PK issue thanks to https://github.com/laurenz/oracle_fdw/issues/83

All good :)
