### ISSUE TITLE
UPDATE with a field not belonging to the foreign Oracle table actually closes the connection

### ISSUE THREAD

**Issue by fnicollet** [laurenz/oracle_fdw#105]
Hello,

I have a table with many columns. If I do:
> UPDATE "l_esi_esp_ctrl_vocation_secnd" = 'voc sec' WHERE ("esi"."esi_esp_carto_espace"."id_esi_esp_carto_espace" IN (130))

No problem, the update is done. It doesn't actually goes to Oracle because I have a trigger on INSERT/UPDATE which stores the modification in another table and doesn't actually update the table (RETURN NULL)
Then, I needed to add another field that didn't belong to the foreign table, to store the user's email which did the modification:
> ALTER FOREIGN TABLE esi."esi_esp_carto_espace" ADD COLUMN email text;

Now if I run:
> UPDATE "esi"."esi_esp_carto_espace" SET "email" = 'fnicollet@ciril.net', "l_esi_esp_ctrl_vocation_secnd" = 'voc sec' WHERE ("esi"."esi_esp_carto_espace"."id_esi_esp_carto_espace" IN (130))

I get in the console:
```
ATTENTION:  column number 136 of foreign table "esi_esp_carto_espace" does not exist in foreign Oracle table, will be replaced by NULL
********** Erreur **********
Connexion interrompue.
```
Last message actually means that the conection has been interrupted. I get the same error in Java, the JDBC connection gets closed when I do that update.

I just need to have the "email" value in my trigger, it won't actually be sent to Oracle, so the warning doesn't bother me (unless I get NULL for it in the trigger :) ).

I think this is an error in oracle_fdw, which somehow closes the postgres connexion.

**Comment by laurenz** [comment]
You cannot add a column to the foreign table that does not already exist on the Oracle table.
But it looks like oracle_fdw causes a crash, which shouldn't happen (check the PostgreSQL server log).
I'll investigate.

**Comment by laurenz** [comment]
Could you check if you get a meaningful error message with the above commit?

**Comment by fnicollet** [comment]
Thanks!
In the meantime, I asked our customer to add the fields in the Oracle Database so I wasn't having any issue anymore, but still, a fix is always good :)

Just tried it, If I only update the absent field, I get this error:
```
ERREUR:  no Oracle column modified by UPDATE
DETAIL:  The UPDATE statement only changes colums that do not exist in the Oracle table.
```
But if I update the absent field and another one that exists, I get:
```
UPDATE "esi"."esi_esp_carto_espace" SET "test_fdw" = 'fnicollet@ciril.net', "l_esi_esp_ctrl_vocation_secnd" = 'voc sec' WHERE ("esi"."esi_esp_carto_espace"."id_esi_esp_carto_espace" IN (130))
```
I don't get any error / warning in the console. Instead, it crashes in my trigger function but might be just an issue with what I am doing. Here is the expression I have in my trigger:
```
... lots of stuff
EXECUTE 'INSERT INTO ' || TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME || '_propositions SELECT ''' || TG_OP || ''', now(), ''' || description_change || ''', ''En attente'', $1.*' USING NEW;
```
Error is
> ERREUR:  la colonne « id_serial_ » est de type integer mais l'expression est de type text
LINE 1: ..._fdw": [] -> [fnicollet@ciril.net]<br/>', 'En attente', $1.*

looks like "NEW.*" still contains the field that doesn't exist in the table. So instead of having id_serial (integer) as the first column of the NEW row, it seems to have the value for "test_fdw", which is text and not integer.

So, this is quite an edge case and I am not even sure if it should be fixed or not !

At least, the connection doesn't crash anymore. But I don't get the warning message displayed in pgAdmin for the case where one of the UPDATE field is not in the foreign table.

Fabien

**Comment by laurenz** [comment]
Yes, I did it like this deliberately:
Any `UPDATE` to such a column is tacitly ignored, and the error message is only thrown if this would result in a no-operation `UPDATE` in Oracle (which I cannot do).
These columns behave just like black holes &ndash; no matter what you put in, `NULL` comes out.

I'm not sure about your trigger since I don't know the definitions involved, but a trigger on the foreign table would definitely see the added `email` column.

**Comment by fnicollet** [comment]
ok, then I think this fix is all good :)

Have you seen the other issue I posted? I seems a bit of a similar issue:
https://github.com/laurenz/oracle_fdw/issues/106

On Mon, Jul 4, 2016 at 4:25 PM, Laurenz Albe <notifications@github.com>
wrote:

> Yes, I did it like this deliberately:
> Any UPDATE to such a column is tacitly ignored, and the error message is
> only thrown if this would result in a no-operation UPDATE in Oracle
> (which I cannot do).
> These columns behave just like black holes – no matter what you put in,
> NULL comes out.
>
> I'm not sure about your trigger since I don't know the definitions
> involved, but a trigger on the foreign table would definitely see the added
> email column.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/laurenz/oracle_fdw/issues/105#issuecomment-230302261>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABLtoXc1KjbMDKVyoNrx-S4E2L6-vWeLks5qSRflgaJpZM4JDGBx>
> .
>



-- 
Fabien Nicollet
Tel : +33 (0)6 60 54 72 20
