### ISSUE TITLE
new version/patch not being sensed after installation

### ISSUE THREAD

**Issue by 3kkani** [laurenz/oracle_fdw#107]
Hi Laurenz,

it happened a couple of times already that when installing a new version/patch of fdw it is not becoming available/not working at all, even when the installation appears to be completed successfully. The previous version keep being used and working fine like as nothing was installed at all.

I am not dealing directly with the sw installation so I do not have further info but I can ask the person dealing with this to get involved in this thread.

Based on your experience do you have any suggestion as to what to check/investigate?

**Comment by laurenz** [comment]
What was the installation procedure (and on which operating system)?
How do you determine the current version? With `SELECT oracle_diag()`?

Normally all you have to do is replace `oracle_fdw.so` (or `oracle_fw.dll` on Windows).
Then any new session will automatically use the new version.
Maybe you didn't start a new database session (or restart your application).

**Comment by 3kkani** [comment]
Hi Laurenz,

oracle_diag() is reporting
oracle_fdw 1.4.0, PostgreSQL 9.5.3, Oracle client 12.1.0.2.0

installation is on Linux x86_64

I could see the new version was not used because a newly added feature (sample_percent or prefetch option for example) was not working (even after opening a new session).

I suspect it is something related with the deployment/substitution of the library but as far as I know there are no build errors.

I have asked the person doing the work to join the discussion.

**Comment by laurenz** [comment]
oracle_fdw is loaded into the backend process when a foreign table is used for the first time (or when `oracle_diag` is called).
So if the `prefetch` option is not working after you start a new database session, that means that the oracle_fdw shared library has not been replaced.

**Comment by 3kkani** [comment]
Hi Laurenz,
it seems the make install was not run properly or not run at all and thus the library was not replaced with the new one.
Thanks.
