### ISSUE TITLE
performance tuning for select

### ISSUE THREAD

**Issue by volkmarbuehringer** [laurenz/oracle_fdw#108]
Hi,

is there something which can be done to improve performance

(I use version 1.4 on postgres 9.6 with oracle instant client 12.1 on oracle 11.2.0.4 database ).

The first select seems to be very slow, also if it is only 1 row with index, after repeating it becomes very much faster.

The execution plan from oracle is fine.

I would like to do something like this:

insert into pgedv.los select * from edv.los where l_id = 32443 on conflict ...

**Comment by volkmarbuehringer** [comment]
I mean:

insert into local.los select * from remote.los where l_id = 32443 on conflict ...

**Comment by laurenz** [comment]
Could it be that the data are not in memory (SGA) on Oracle when the query is run for the first time?

Can you show me the output of `EXPLAIN (ANALYZE, BUFFERS) INSERT ...` for both the slow and the fast case?

**Comment by laurenz** [comment]
I'll close the issue for now, please reopen it if you have more information.
