### ISSUE TITLE
Error creating the extension: "libmql1.so" not found

### ISSUE THREAD

**Issue by julenpardo** [laurenz/oracle_fdw#109]
Hi,

I'm unable to create the extension in postgres, getting the error:

`ERROR:  could not load library "/usr/lib/postgresql/9.3/lib/oracle_fdw.so": libmql1.so: cannot open shared object file: No such file or directory`

I have Oracle installed and set the environmental variables:

```
echo $ORACLE_HOME
/usr/lib/oracle/12.1/client64
echo $LD_LIBRARY_PATH
/usr/lib/oracle/12.1/client64/lib
```

The output of  `ldd`:

```
ldd /usr/lib/postgresql/9.3/lib/oracle_fdw.so
        linux-vdso.so.1 =>  (0x00007ffeb2939000)
        libclntsh.so.12.1 => /usr/lib/oracle/12.1/client64/lib/libclntsh.so.12.1 (0x00007f84f2ca8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f84f28e3000)
        libmql1.so => /usr/lib/oracle/12.1/client64/lib/libmql1.so (0x00007f84f266d000)
        libipc1.so => /usr/lib/oracle/12.1/client64/lib/libipc1.so (0x00007f84f22ef000)
        libnnz12.so => /usr/lib/oracle/12.1/client64/lib/libnnz12.so (0x00007f84f1be5000)
        libons.so => /usr/lib/oracle/12.1/client64/lib/libons.so (0x00007f84f19a0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f84f179c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f84f1496000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f84f1278000)
        libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f84f105e000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f84f0e56000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f84f5e84000)
        libaio.so.1 => /lib/x86_64-linux-gnu/libaio.so.1 (0x00007f84f0c54000)
        libclntshcore.so.12.1 => /usr/lib/oracle/12.1/client64/lib/libclntshcore.so.12.1 (0x00007f84f06e2000)
```

And the files located in Oracle lib dir:

```
 ll $LD_LIBRARY_PATH
total 190208
drwxrwxrwx 2 root root      4096 uzt  7 12:55 ./
drwxr-xr-x 4 root root      4096 uzt  7 12:37 ../
lrwxrwxrwx 1 root root        21 uzt  7 12:55 libclntshcore.so -> libclntshcore.so.12.1*
-rwxrwxrwx 1 root root   6990875 uzt  7  2014 libclntshcore.so.12.1*
lrwxrwxrwx 1 root root        17 uzt  7 12:55 libclntsh.so -> libclntsh.so.12.1*
-rwxrwxrwx 1 root root  58793741 uzt  7  2014 libclntsh.so.12.1*
-rwxrwxrwx 1 root root   1768370 uzt  7  2014 libipc1.so*
-rwxrwxrwx 1 root root    544150 uzt  7  2014 libmql1.so*
-rwxrwxrwx 1 root root   6213011 uzt  7  2014 libnnz12.so*
lrwxrwxrwx 1 root root        15 uzt  7 12:55 libocci.so -> libocci.so.12.1*
-rwxrwxrwx 1 root root   2576030 uzt  7  2014 libocci.so.12.1*
-rwxrwxrwx 1 root root 109549133 uzt  7  2014 libociei.so*
-rwxrwxrwx 1 root root    156353 uzt  7  2014 libocijdbc12.so*
-rwxrwxrwx 1 root root    337137 uzt  7  2014 libons.so*
-rwxrwxrwx 1 root root    118491 uzt  7  2014 liboramysql12.so*
-rwxrwxrwx 1 root root   3670975 uzt  7  2014 ojdbc6.jar*
-rwxrwxrwx 1 root root   3677511 uzt  7  2014 ojdbc7.jar*
-rwxrwxrwx 1 root root    311555 uzt  7  2014 ottclasses.zip*
-rwxrwxrwx 1 root root     35925 uzt  7  2014 xstreams.jar*
```
(Yes, I've given 777 permissions to everything, just in case).

I don't know which is the reason of this. I'd be very grateful if you would help me to figure out the problem.

**Comment by laurenz** [comment]
The funny thing here is that `libclntsh.so.12.1` can be found but `libmql1.so` cannot, even though they are in the same directory and permissions shouldn't be the problem.

Could you check

1. if the environment variables are set in the environment of the PostgreSQL server. Find out the process id of the postmaster (`<pid>`) and run

        cat /proc/<pid>/environ | xargs -n 1 -0 echo | grep -E 'LD_LIBRARY_PATH|ORACLE_HOME'

2. if there is more than one `libclntsh.so.12.1` on the system.

**Comment by julenpardo** [comment]
Hi @laurenz, thanks for your quick response.

Effectively, there is another `libclntsh.so.12.1`. The output of `whereis libclntsh.so.12.1` is  `/lib/libclntsh.so.12.1`. And if I change the name of that library, the error creating the extension is that is not finding it:

`ERROR:  could not load library "/usr/lib/postgresql/9.3/lib/oracle_fdw.so": libclntsh.so.12.1: cannot open shared object file: No such file or directory`

The Oracle environmental variables are not set for Postgres, these are the only ones:

```
PG_GRANDPARENT_PID=15478
PGLOCALEDIR=/usr/share/locale
PGSYSCONFDIR=/etc/postgresql-common
LANG=en_US.UTF-8
PWD=/var/lib/postgresql
PGDATA=/var/lib/postgresql/9.3/main
```

I've added the path to `LD_LIBRARY_PATH` with `ldconfig`, and now the extension is being created without any problem. Many thanks!
