### ISSUE TITLE
Support for Unix

### ISSUE THREAD

**Issue by nirmalnarayanans** [laurenz/oracle_fdw#111]
Hi, 
 
I have downloaded the binary of oracle_fdw-1.4.0-pg95-win64  .  Can the oracle_fdw.dll in lib folder be copied for Unix versions also , or is another binary version available for Unix/Linux platforms. 

Kindly advise on this.

Thanks,
Nirmal.

**Comment by laurenz** [comment]
No, the binaries are for Windows only.

On other platforms you have to build oracle_fdw yourself, which should be quite simple since oracle_fdw uses the PostgreSQL extension system PGXS.

I only provide the Windows binaries since
- It is not so easy to get a Windows build environment installed and configured on Windows
- PGXS does not exist on Windows

Try to follow the instructions in the README and let me know if you run into problems.

**Comment by nirmalnarayanans** [comment]
Hi Laurenz, 

 Thanks I ran into issues after building and installing oracle_fdw. 

 The error was : OCIEnvCreate failed to create environment handle after installing oracle_fdw
 But resolved it following comments given by user jgrocha ( the 4th one in the link )
 below :- 

 http://dba.stackexchange.com/questions/14327/ocienvcreate-failed-to-create-environment-handle-after-installing-oracle-fdw

 Now it is working fine. 

 Had one query regarding connecting to remote Postgres server on Unix from the PgAdmin in my local ( Windows environment )

Below is the listener on Unix box for Postgres :-1: 

cp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1630/postgres

When trying to connect from PgAdmin in Windows i get the below error:-
SSH error :- Authentication by password failed with error code -18

I thought it has to do with some setting in my Postgres unix configuration.  But i am unable to find the pg_hba.conf file itself in remote unix server. 

find . -name "pg_hba.conf"

Postgres works without any issues on this server. 

Thanks,
Nirmal.

**Comment by laurenz** [comment]
The pgAdmin III connection problem is not really related to oracle_fdw&hellip;
It works if you try to connect without SSL, right?

There will be a `pg_hba.conf` on the PostgreSQL server, it is in the data directory.
