### ISSUE TITLE
Date conversion in where clause

### ISSUE THREAD

**Issue by lorenati** [laurenz/oracle_fdw#112]
Hi, I have this oracle table:

```
--------------------------------------------------------
--  DDL for Table MYTABLE
--------------------------------------------------------

  CREATE TABLE "MYSCHEMA"."MYTABLE" 
   (	"COLUMN1" NUMBER, 
	"COLUMN2" NUMBER, 
	"THEDATE" DATE
   ) ;

```

I made my foreign table like this:

```
CREATE FOREIGN TABLE ds_oracle.mytable
   (column1 double precision ,
    column2 double precision ,
    thedate timestamp without time zone)
   SERVER oradb
   OPTIONS (schema 'MYSCHEMA', table 'MYTABLE');

```

When I try to perform this select:

select * from  ds_oracle.mytable where column2='AVALUE' and thedate>=current_timestamp - interval '2 day'

oracle_fdw performs this query (I added a `elog(NOTICE, "%s", fdwState->query);`  right after `createQuery `function in `oracleGetForeignRelSize`):

`NOTICE:  SELECT /*cb927b6e8dae1452f03f03d99760c8ae*/ "COLUMN1", "COLUMN2", "THEDATE"  FROM "MYSCHEMA"."MYTABLE" WHERE ("THEDATE" >= ((CAST (:now AS TIMESTAMP WITH TIME ZONE)) - INTERVAL '2 00:00:00.000000' DAY(9) TO SECOND(6))) AND ("COLUMN2" = 'AVALUE')`

But if I try to cast the column to date, like this:

select * from ds_oracle.mytable where column2='AVALUE' and thedate::date>=(current_timestamp - interval '2 day')::date
`

I get this query:

NOTICE:  SELECT /*3b126d9e4da900a04d70968a54aa4f1b*/ "COLUMN1", "COLUMN2", "THEDATE" FROM "MYSCHEMA"."MYTABLE" WHERE ("COLUMN2" = 'AVALUE')`

The column 'thedate' dissapears in the query

Am I missing something? thank you in advance

**Comment by lorenati** [comment]
Here is more information; these are the EXPLAIN (ANALYZE, VERBOSE, BUFFERS)   of both queries

EXPLAIN (ANALYZE, VERBOSE, BUFFERS) select column2 from ds_oracle.mytable where column2 ='AVALUE' and thedate>=(current_timestamp - interval '2 day')

Foreign Scan on ds_oracle.mytable  (cost=10000.00..20000.00 rows=1000 width=218) (actual time=14.067..91.163 rows=2612 loops=1)
  Output: column2
  Oracle query: SELECT /*6aac8a84b8dd9b5813e8fdfa26e8df2d*/ COLUMN2, THEDATE FROM MYSCHEMA.MYTABLE WHERE (THEDATE >= ((CAST (:now AS TIMESTAMP WITH TIME ZONE)) - INTERVAL '2 00:00:00.000000' DAY(9) TO SECOND(6))) AND (COLUMN2 = 'AVALUE (...)
  Oracle plan: SELECT STATEMENT
  Oracle plan:   TABLE ACCESS FULL MYTABLE  (filter (COLUMN2='AVALUE' AND SYS_EXTRACT_UTC(INTERNAL_FUNCTION(THEDATE))>=SYS_EXTRACT_UTC(CAST(:NOW AS TIMESTAMP WITH TIME ZONE)-INTERVAL'+000000002 00:00:00.000000' DAY(9) TO SECOND(6))))
Planning time: 4.904 ms
Execution time: 91.658 ms

-----------
EXPLAIN (ANALYZE, VERBOSE, BUFFERS) select column2 from ds_oracle.mytable where column2='AVALUE' and thedate::date>=(current_timestamp - interval '2 day')::date

Foreign Scan on ds_oracle.mytable  (cost=10000.00..20000.00 rows=1000 width=218) (actual time=6.719..72.112 rows=2612 loops=1)
  Output: column2
  Filter: ((mytable.thedate)::date >= ((now() - '2 days'::interval))::date)
  Rows Removed by Filter: 1077
  Oracle query: SELECT /*f644fea4fc7085a0cde140e02a5e6583*/ COLUMN2, THEDATE FROM MYSCHEMA.MYTABLE WHERE (COLUMN2 = 'AVALUE')
  Oracle plan: SELECT STATEMENT
  Oracle plan:   TABLE ACCESS FULL MYTABLE  (filter COLUMN2='AVALUE')
Planning time: 4.044 ms
Execution time: 72.492 ms

**Comment by laurenz** [comment]
This is because the query parser converts `thedate::date` to `date(thedate)`, and oracle_fdw does not try to push down the `date()` functions, see [here](https://github.com/laurenz/oracle_fdw/blob/master/oracle_fdw.c#L3404) in the code.

**Comment by laurenz** [comment]
I'll close the issue since I believe that the question is answered.

**Comment by lorenati** [comment]
Hi, I have a question regarding this

I want to get last month's date i.e. in 09/07/2016 (mm/dd/yyyy) I want to get 08/07/2016

I can't do this query according to [this ](https://github.com/laurenz/oracle_fdw/blob/master/oracle_fdw.c#L4626)line:

select * from ds_oracle.mytable t where column2='AVALUE' and 
date_part('year'::text,t.thedate) = date_part('year'::text, now() - interval '1 month') 
AND date_part('month'::text, t.thedate) = date_part('month'::text, now() - interval '1 month') 
AND date_part('day'::text, t.thedate) = date_part('day'::text, now() - interval '1 month')

This gets translated to:

NOTICE:  SELECT /*7ddff13d9747308513ad3c689498bce3*/  * from "MYSCHEMA"."MYTABLE" WHERE ("COLUMN2" = 'AVALUE')

So I have to perform a query like this:

select * from ds_oracle.mytable t where column2='AVALUE' and 
date_part('year'::text,t.thedate) = date_part('year'::text, now() - interval '30 days') 
AND date_part('month'::text, t.thedate) = date_part('month'::text, now() - interval '30 days') 
AND date_part('day'::text, t.thedate) = date_part('day'::text, now() - interval '30 days')

This is translated correctly

NOTICE:  SELECT /*7ddff13d9747308513ad3c689498bce3*/  * from "MYSCHEMA"."MYTABLE" WHERE ("COLUMN2" = 'AVALUE') AND (EXTRACT(year FROM "THEDATE") = EXTRACT(year FROM ((CAST (:now AS TIMESTAMP WITH TIME ZONE)) - INTERVAL '30 00:00:00.000000' DAY(9) TO SECOND(6)))) AND (EXTRACT(month FROM "THEDATE") = EXTRACT(month FROM ((CAST (:now AS TIMESTAMP WITH TIME ZONE)) - INTERVAL '30 00:00:00.000000' DAY(9) TO SECOND(6)))) AND (EXTRACT(day FROM "THEDATE") = EXTRACT(day FROM ((CAST (:now AS TIMESTAMP WITH TIME ZONE)) - INTERVAL '30 00:00:00.000000' DAY(9) TO SECOND(6))))

But in this case I have problems with this query, '30 days' is not necessarily correct in all scenarios

select date_part('day'::text, '08/31/2016'::date - interval '30 days') , date_part('month'::text, '08/31/2016'::date - interval '30 days') , date_part('year'::text, '08/31/2016'::date - interval '30 days') 

This retrieves 1  |  8  | 2016

It should be like this to get the correct date

select date_part('day'::text, '08/31/2016'::date - interval '1 month') , date_part('month'::text, '08/31/2016'::date - interval '1 month') , date_part('year'::text, '08/31/2016'::date - interval '1 month') 

This retrieves 31  |  7  |  2016

**Comment by laurenz** [comment]
Instead of

    ... = date_part('...', now() - interval '1 month')

try

    ... = (SELECT date_part('...', now() - interval '1 month'))

That should work around the problem.

**Comment by lorenati** [comment]
Thank you, it worked
