### ISSUE TITLE
Remote function execute

### ISSUE THREAD

**Issue by VirtUalProtoss** [laurenz/oracle_fdw#113]
Need execute remote function, it need by billing system based on Oracle DB (internal user auth), without this data not return (0 lines always). I trying insert data in custom remote table, and exec auth function by insert trigger. On Oracle DB from SQLDeveloper this tric worked, but from PostgreSQL - no data (maybe session close after insert).

**Comment by laurenz** [comment]
Can you show me SQL statements to create the objects, triggers etc. in Oracle and PostgreSQL and the query you run from PostgreSQL?
And please tell me what you would like to see and how it is different from what you get.

**Comment by VirtUalProtoss** [comment]
At first i trying use the temp table in Oracle:
 CREATE TABLE "AUTH" 
   (	"LOGIN" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   )
and trigger
CREATE OR REPLACE TRIGGER tmp_auth
  AFTER
    INSERT
  ON tmp_auth FOR EACH ROW
declare
    p_res number;
BEGIN
  CASE
    WHEN INSERTING THEN
      begin
          select auth(:NEW.login, :NEW.password) into p_res from dual;
      end;
  END CASE;
END;
and use it:
insert into AUTH (LOGIN, PASSWORD) values ('my_login', 'my_password');
It work in Oracle SQLDeveloper, while DB connected, i can select any data
But from PostgreSQL (PgAdmin3) after insert i try select, and no data return. From any custom tables select returns the data (this tables has no internal auth need).

Then i try another way:
I create view in Oracle:
create view TMP_AUTH as
select
    login
    , auth(trim(login), trim(password)) auth_res
from AUTH
where trim(login) = 'my_login';

and foreign table in Postgres:

CREATE FOREIGN TABLE auth (
   LOGIN character(20),
   auth_res integer
) SERVER oracle OPTIONS (table 'TMP_AUTH');

and it use:
select * from auth where trim(login)='my_login';
then any select from protected tables returns data.

But this is crutch

Betterr way it execute remote SQL, like "select auth(login, password) from dual".

**Comment by laurenz** [comment]
Your example is incomplete.
What is `tmp_auth`? How is the function `auth()` defined?

If you `SET client_min_messages = debug2` you will see the Oracle queries executed.
Do they look like expected?

**Comment by VirtUalProtoss** [comment]
see above ^^^ "create view TMP_AUTH as" - is my view on Oracle DB
function "auth()" is wrapped function from billing system, how they defined - is unknown
SET client_min_messages = debug2 - insufficient privileges...

**Comment by laurenz** [comment]
1. You don't need any privileges for

        SET client_min_messages = debug2;

2. Your example is so confused that I cannot read it. What is that table `AUTH` you create in the beginning?
  Can you provide SQL that I can use to reproduce your problem?
  You have to make it easy for me if you want me to help you.

**Comment by VirtUalProtoss** [comment]
SET client_min_messages = debug2; - line 1: SQLPLUS Command Skipped: set client_min_messages = debug2
It is no longer relevant.
I will look for other means.
