### ISSUE TITLE
Postgres 9.6 and push downs of JOINs

### ISSUE THREAD

**Issue by tsyork** [laurenz/oracle_fdw#115]
Hi Laurenz,

Great work on development of this FDW. I installed it last week for the first time and am finding it extremely useful.

Reading through documentation on the upcoming Postgres 9.6 release it appears support for push down of JOINs will be supported for FDWs in general. However, I assume additional work will be required on each FDW to make pushed down JOINs available. Can you confirm that this is the case? 

I'm in the process of converting Oracle queries to Postgres using your FDW but, depending on the timeline of when push down JOINs will be available, I might hold off on the conversion to take advantage of the new functionality.

Thanks,
Tim

**Comment by laurenz** [comment]
NTT, the Japanese telecommunications company, and in particular @yamatattsu have expressed the wish to contribute in this area.
So yes, it is on the radar, but it is a bigger thing, and I don't expect it to be completed in the next couple of weeks.
I'd start using conventional means in your place (like views in Oracle).

**Comment by tsyork** [comment]
Thanks Laurenz. Unfortunately, we don't have permissions to create objects on the Oracle server so we'll probably just hold off for now. Thanks again for the hard work and great extension.
