### ISSUE TITLE
IMPORT FOREIGN SCHEMA

### ISSUE THREAD

**Issue by davidfetter** [laurenz/oracle_fdw#12]
It's in 9.5-to-be :)

Might it be worthwhile trying to do some kind of type mapping, per

**Comment by laurenz** [comment]
With today's commits b1b5a54959b189acdae146d84913bb568c54f4e9 and cbee53b9259e6ebf9d6dea905ebf6c84fa942467 I have added support for IMPORT FOREIGN TABLE.

There is an option "case" that governs how Oracle names are case-folded.

I ended up querying the Oracle catalog for the relevant data, and that works quite well although the performance of queries on the Oracle catalogs (which are complicated views on internal tables) seriously sucks.

I anybody is willing to play with it, I'd be more than happy.
