### ISSUE TITLE
Is it possible to specify source data columns when defining foreign table?

### ISSUE THREAD

**Issue by mblahay** [laurenz/oracle_fdw#121]
I am asking this as a new user to Postgresql. When I create foreign tables using postgresql_fdw there is a column option "column_name" which is used to identify the source column name. Foreign tables for oracle_fdw do not have this option documented and do not recognize the option when I use it. Is there another way to identify the source columns by name, or is the assignment of source columns to foreign table columns purely positional in nature?

**Comment by laurenz** [comment]
Yes, as the README says, the mapping of columns is purely positional.
