### ISSUE TITLE
best way updating foreign tables

### ISSUE THREAD

**Issue by volkmarbuehringer** [laurenz/oracle_fdw#122]
In postgres I use a trigger for writing into log-table and after commit I do a complicated update on foreign table by joining log-table and data-table

join in update of foreign-table didn't work very well and you translate it into different sql statements anyway.

Would it be better doing all the work in a CTE  and then only doing a simple update out of the
CTE ?

**Comment by laurenz** [comment]
Bulk `UPDATE`s are never efficient with oracle_fdw because of the way a foreign `UPDATE` or `DELETE` works:
In a first step, the foreign table is scanned with a `SELECT ... FOR UPDATE` which contains the `WHERE` conditions that can be pushed down. In a second step, an `UPDATE` or `DELETE` statement is issued for each matching row found in the first step.

(It would be possible, to enhance oracle_fdw so that it does the bulk `UPDATE` or `DELETE` during the first step, but that would not be easy.)

So maybe it won't make much difference which way you update your foreign table, and both ways will be slow. Its hard to say without seeing the statement (and its `EXPLAIN` plan).

**Comment by volkmarbuehringer** [comment]
It is no bulk update but a single row generic update, for replicating data from postgres to oracle,
like in oracle with trigger and queue (= a table for collecting data), every entry (seq) is propagated individually ):


CREATE or replace FUNCTION los_trigger() RETURNS trigger AS $$
BEGIN
if current_user <> 'replikant' then
insert into edv.logger (id,typ,tablename,rower)values(NEW.l_id,substring(tg_op from 1 for 1),TG_TABLE_NAME, row_to_json(NEW) ) ;
  PERFORM pg_notify('watchers' ,'');
end if;
  RETURN new;
END;
$$ LANGUAGE plpgsql;



There seems to be a bug with using FROM in the update, which I avoid by using the  update without FROM. Another possible solution would be  doing the update with values and separate the code in the application:


this works ( update with select ) :

`with x as (  select * from edv.logger x,  json_populate_record(null::imp.los,x.rower ) y where  x.seq = $1 )                update imp.${item.table_name}  set (${item.cols})=(select ${item.cols} from x )  where l.${item.pk} = (select id from x)`

update with from doesn't work ( doesn't propagate the id column into the oracle select ) :

`with x as (  select * from edv.logger x,  json_populate_record(null::imp.los,x.rower ) y where  x.seq = $1 )                update imp.${item.table_name}  set (${item.cols}) from x  where l.${item.pk} = x.id`

**Comment by laurenz** [comment]
I assume that you set the `${...}` from your application code, right?
What exactly do the variables contain?

I am asking because your second `UPDATE` looks like an obvious syntax error; the `SET` clause must look like `<col> = <expr>, ...` or `(<col>, ...) = (<expr>, ...)` or `(<col>, ...) = (SELECT ...) `.

You should be able to use `FROM` in an `UPDATE` without problems, see [the documentation](https://www.postgresql.org/docs/current/static/sql-update.html).

What should your first `UPDATE` do if there is more than one row in `edv.logger`?

Could you describe your problem with more detail and show me the error messages?

**Comment by volkmarbuehringer** [comment]
yes the from clause works, but the select in your wrapper is very slow because the primary key id is not propagated to the oracle select, you do something like "select * from edv.los for update" instead of "select * from edv.los where l_id =  id"

seq is the primary key of logger, so there is only 1 record per update and id is the primary key of the table

**Comment by laurenz** [comment]
Well, without `EXPLAIN` output I cannot say much&hellip;

**Comment by volkmarbuehringer** [comment]
here is the explain plan, the foreign table is completely selected for update, the key not propagated from logger:

mosam=# explain verbose update imp.los l set l_upd_uid='gag' from logger where seq = 27 and l.l_id = id;
                                                                                                                  
                                 QUERY PLAN                                                                       
                                                                             
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------
 Update on imp.los l  (cost=10008.31..20012.07 rows=1 width=510)
   Oracle statement: UPDATE "EDV"."LOS" SET "L_UPD_UID" = :p12 WHERE "L_ID" = :k1
   ->  Hash Join  (cost=10008.31..20012.07 rows=1 width=510)
         Output: l.l_id, l.l_jobid, l.l_packageid, l.l_ticketstatusid, l.l_losnr, l.l_anonym, l.l_marketing, l.l_b
lz, l.l_konto, l.l_cr_uid, l.l_cr_date, 'gag'::character varying(32), l.l_upd_date, l.l_erste_loaid, l.l_bic, l.l_
iban, l.l_losalsgewinn, l.l_id, logger.ctid
         Hash Cond: (l.l_id = logger.id)
         ->  Foreign Scan on imp.los l  (cost=10000.00..20000.00 rows=1000 width=414)
               Output: l.l_id, l.l_jobid, l.l_packageid, l.l_ticketstatusid, l.l_losnr, l.l_anonym, l.l_marketing,
 l.l_blz, l.l_konto, l.l_cr_uid, l.l_cr_date, l.l_upd_uid, l.l_upd_date, l.l_erste_loaid, l.l_bic, l.l_iban, l.l_l
osalsgewinn
               Oracle query: SELECT /*66ebcb1b8d60ec5c59f8a592df3ddf0a*/ "L_ID", "L_JOBID", "L_PACKAGEID", "L_TICK
ETSTATUSID", "L_LOSNR", "L_ANONYM", "L_MARKETING", "L_BLZ", "L_KONTO", "L_CR_UID", "L_CR_DATE", "L_UPD_DATE", "L_E
RSTE_LOAID", "L_BIC", "L_IBAN", "L_LOSALSGEWINN" FROM "EDV"."LOS" FOR UPDATE
               Oracle plan: SELECT STATEMENT
               Oracle plan:   FOR UPDATE
               Oracle plan:     BUFFER SORT
               Oracle plan:       TABLE ACCESS FULL LOS
         ->  Hash  (cost=8.30..8.30 rows=1 width=10)
               Output: logger.ctid, logger.id
               ->  Index Scan using logger_pkey on edv.logger  (cost=0.28..8.30 rows=1 width=10)
                     Output: logger.ctid, logger.id
                     Index Cond: (logger.seq = 27)
(17 Zeilen)

**Comment by laurenz** [comment]
The problem here is that PostgreSQL chooses to use a hash join, which performs a sequential scan.

I see that you have no statistics collected for the foreign table.
Could you run

    ANALYZE logger;

and see if that changes anything?

Can you post the `EXPLAIN` output for the same query after the `ANALYZE` run?

If it still does not use a nested loop join, could you try to set

    SET enable_hashjoin = off;
    SET enable_mergejoin = off;

run `EXPLAIN` again and post that second query plan?

**Comment by volkmarbuehringer** [comment]
it doesn't change anything, it has also the correct number of rows from the foreign table

but it is no problem, because I can use the update-syntax without from-clause

mosam=# set enable_hashjoin=off;
SET
mosam=# set enable_mergejoin=off;
SET
mosam=# explain verbose update los set l_upd_uid = 'ga' from logger where seq = 1;
                                                                                                                                                   QUER
Y PLAN                                                                                                                                                 
   
-------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------
---
 Update on edv.los  (cost=0.28..1357866.86 rows=40579528 width=228)
   ->  Nested Loop  (cost=0.28..1357866.86 rows=40579528 width=228)
         Output: los.l_id, los.l_jobid, los.l_packageid, los.l_ticketstatusid, los.l_losnr, los.l_anonym, los.l_marketing, los.l_blz, los.l_konto, los.
l_cr_uid, los.l_cr_date, 'ga'::character varying(32), los.l_upd_date, los.l_erste_loaid, los.l_bic, los.l_iban, los.l_losalsgewinn, los.ctid, logger.ct
id
         ->  Index Scan using logger_pkey on edv.logger  (cost=0.28..8.30 rows=1 width=6)
               Output: logger.ctid
               Index Cond: (logger.seq = 1)
         ->  Seq Scan on edv.los  (cost=0.00..952063.28 rows=40579528 width=140)
               Output: los.l_id, los.l_jobid, los.l_packageid, los.l_ticketstatusid, los.l_losnr, los.l_anonym, los.l_marketing, los.l_blz, los.l_konto
, los.l_cr_uid, los.l_cr_date, los.l_upd_date, los.l_erste_loaid, los.l_bic, los.l_iban, los.l_losalsgewinn, los.ctid
(8 Zeilen)

**Comment by laurenz** [comment]
I cannot see any foreign scan in the `EXPLAIN` output you just posted.

**Comment by volkmarbuehringer** [comment]
my fault, the statement is:

Update on imp.los  (cost=10000.28..406277830.26 rows=40586196 width=287)
   Oracle statement: UPDATE "EDV"."LOS" SET "L_UPD_UID" = :p12 WHERE "L_ID" = :k1
   ->  Nested Loop  (cost=10000.28..406277830.26 rows=40586196 width=287)
         Output: los.l_id, los.l_jobid, los.l_packageid, los.l_ticketstatusid, los.l_losnr, los.l_anonym, los.l_marketing, los.l_blz, los.l_konto, los.
l_cr_uid, los.l_cr_date, 'ga'::character varying(32), los.l_upd_date, los.l_erste_loaid, los.l_bic, los.l_iban, los.l_losalsgewinn, los.l_id, logger.ct
id
         ->  Index Scan using logger_pkey on edv.logger  (cost=0.28..8.30 rows=1 width=6)
               Output: logger.ctid
               Index Cond: (logger.seq = 1)
         ->  Foreign Scan on imp.los  (cost=10000.00..405871960.00 rows=40586196 width=191)
               Output: los.l_id, los.l_jobid, los.l_packageid, los.l_ticketstatusid, los.l_losnr, los.l_anonym, los.l_marketing, los.l_blz, los.l_konto
, los.l_cr_uid, los.l_cr_date, los.l_upd_uid, los.l_upd_date, los.l_erste_loaid, los.l_bic, los.l_iban, los.l_losalsgewinn
               Oracle query: SELECT /*66ebcb1b8d60ec5c59f8a592df3ddf0a*/ "L_ID", "L_JOBID", "L_PACKAGEID", "L_TICKETSTATUSID", "L_LOSNR", "L_ANONYM", "
L_MARKETING", "L_BLZ", "L_KONTO", "L_CR_UID", "L_CR_DATE", "L_UPD_DATE", "L_ERSTE_LOAID", "L_BIC", "L_IBAN", "L_LOSALSGEWINN" FROM "EDV"."LOS" FOR UPDA
TE
               Oracle plan: SELECT STATEMENT
               Oracle plan:   FOR UPDATE
               Oracle plan:     BUFFER SORT
               Oracle plan:       TABLE ACCESS FULL LOS
(14 Zeilen)

**Comment by volkmarbuehringer** [comment]
the complete statement:

explain verbose update imp.los set l_upd_uid = 'ga' from logger where seq = 1;
                                                                                                                                                   QUER
Y PLAN                                                                                                                                                 
   
-------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------
---
 Update on imp.los  (cost=10000.28..406277830.26 rows=40586196 width=287)
   Oracle statement: UPDATE "EDV"."LOS" SET "L_UPD_UID" = :p12 WHERE "L_ID" = :k1
   ->  Nested Loop  (cost=10000.28..406277830.26 rows=40586196 width=287)
         Output: los.l_id, los.l_jobid, los.l_packageid, los.l_ticketstatusid, los.l_losnr, los.l_anonym, los.l_marketing, los.l_blz, los.l_konto, los.
l_cr_uid, los.l_cr_date, 'ga'::character varying(32), los.l_upd_date, los.l_erste_loaid, los.l_bic, los.l_iban, los.l_losalsgewinn, los.l_id, logger.ct
id
         ->  Index Scan using logger_pkey on edv.logger  (cost=0.28..8.30 rows=1 width=6)
               Output: logger.ctid
               Index Cond: (logger.seq = 1)
         ->  Foreign Scan on imp.los  (cost=10000.00..405871960.00 rows=40586196 width=191)
               Output: los.l_id, los.l_jobid, los.l_packageid, los.l_ticketstatusid, los.l_losnr, los.l_anonym, los.l_marketing, los.l_blz, los.l_konto
, los.l_cr_uid, los.l_cr_date, los.l_upd_uid, los.l_upd_date, los.l_erste_loaid, los.l_bic, los.l_iban, los.l_losalsgewinn
               Oracle query: SELECT /*66ebcb1b8d60ec5c59f8a592df3ddf0a*/ "L_ID", "L_JOBID", "L_PACKAGEID", "L_TICKETSTATUSID", "L_LOSNR", "L_ANONYM", "
L_MARKETING", "L_BLZ", "L_KONTO", "L_CR_UID", "L_CR_DATE", "L_UPD_DATE", "L_ERSTE_LOAID", "L_BIC", "L_IBAN", "L_LOSALSGEWINN" FROM "EDV"."LOS" FOR UPDA
TE
               Oracle plan: SELECT STATEMENT
               Oracle plan:   FOR UPDATE
               Oracle plan:     BUFFER SORT
               Oracle plan:       TABLE ACCESS FULL LOS
(14 Zeilen)

**Comment by volkmarbuehringer** [comment]
I beg your pardon, today is Monday:

here the local update, with the correct plan and after that the remote update:
the update in oracle is with the correct predicate, but in the "select for update" the 
primary key predicate is missing:

mosam=# explain verbose update edv.los l set l_upd_uid = 'ga' from logger where seq = 1 and l.l_id = id;
                                                                                                                                  QUERY PLAN           
                                                                                                                        
-------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
 Update on edv.los l  (cost=0.84..16.89 rows=1 width=228)
   ->  Nested Loop  (cost=0.84..16.89 rows=1 width=228)
         Output: l.l_id, l.l_jobid, l.l_packageid, l.l_ticketstatusid, l.l_losnr, l.l_anonym, l.l_marketing, l.l_blz, l.l_konto, l.l_cr_uid, l.l_cr_dat
e, 'ga'::character varying(32), l.l_upd_date, l.l_erste_loaid, l.l_bic, l.l_iban, l.l_losalsgewinn, l.ctid, logger.ctid
         ->  Index Scan using logger_pkey on edv.logger  (cost=0.28..8.30 rows=1 width=10)
               Output: logger.ctid, logger.id
               Index Cond: (logger.seq = 1)
         ->  Index Scan using pk_los on edv.los l  (cost=0.56..8.58 rows=1 width=140)
               Output: l.l_id, l.l_jobid, l.l_packageid, l.l_ticketstatusid, l.l_losnr, l.l_anonym, l.l_marketing, l.l_blz, l.l_konto, l.l_cr_uid, l.l_
cr_date, l.l_upd_date, l.l_erste_loaid, l.l_bic, l.l_iban, l.l_losalsgewinn, l.ctid
               Index Cond: (l.l_id = logger.id)
(9 Zeilen)

mosam=# explain verbose update imp.los l set l_upd_uid = 'ga' from logger where seq = 1 and l.l_id = id;
                                                                                                                                                   QUER
Y PLAN                                                                                                                                                 
   
-------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------
---
 Update on imp.los l  (cost=10000.28..406379295.75 rows=1 width=287)
   Oracle statement: UPDATE "EDV"."LOS" SET "L_UPD_UID" = :p12 WHERE "L_ID" = :k1
   ->  Nested Loop  (cost=10000.28..406379295.75 rows=1 width=287)
         Output: l.l_id, l.l_jobid, l.l_packageid, l.l_ticketstatusid, l.l_losnr, l.l_anonym, l.l_marketing, l.l_blz, l.l_konto, l.l_cr_uid, l.l_cr_dat
e, 'ga'::character varying(32), l.l_upd_date, l.l_erste_loaid, l.l_bic, l.l_iban, l.l_losalsgewinn, l.l_id, logger.ctid
         Join Filter: (l.l_id = logger.id)
         ->  Index Scan using logger_pkey on edv.logger  (cost=0.28..8.30 rows=1 width=10)
               Output: logger.ctid, logger.id
               Index Cond: (logger.seq = 1)
         ->  Foreign Scan on imp.los l  (cost=10000.00..405871960.00 rows=40586196 width=191)
               Output: l.l_id, l.l_jobid, l.l_packageid, l.l_ticketstatusid, l.l_losnr, l.l_anonym, l.l_marketing, l.l_blz, l.l_konto, l.l_cr_uid, l.l_
cr_date, l.l_upd_uid, l.l_upd_date, l.l_erste_loaid, l.l_bic, l.l_iban, l.l_losalsgewinn
               Oracle query: SELECT /*66ebcb1b8d60ec5c59f8a592df3ddf0a*/ "L_ID", "L_JOBID", "L_PACKAGEID", "L_TICKETSTATUSID", "L_LOSNR", "L_ANONYM", "
L_MARKETING", "L_BLZ", "L_KONTO", "L_CR_UID", "L_CR_DATE", "L_UPD_DATE", "L_ERSTE_LOAID", "L_BIC", "L_IBAN", "L_LOSALSGEWINN" FROM "EDV"."LOS" FOR UPDA
TE
               Oracle plan: SELECT STATEMENT
               Oracle plan:   FOR UPDATE
               Oracle plan:     BUFFER SORT
               Oracle plan:       TABLE ACCESS FULL LOS

**Comment by laurenz** [comment]
I can reproduce the problem.

I'll take a look and tell you what's going on.

**Comment by laurenz** [comment]
The problem is that join clauses are not pushed down to Oracle.
Doing that would require non-trivial additions to the code.
Sorry!
