### ISSUE TITLE
compile oracle_fdw with pg 9.6rc1

### ISSUE THREAD

**Issue by volkmarbuehringer** [laurenz/oracle_fdw#124]
I did git clone of the newest version of Oracle_fdw and then make
and I got an error:

[root@pc-pu22 oracle_fdw]# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -fpic -I/usr/lib/oracle/12.1/client64/sdk/include -I/usr/lib/oracle/12.1/client64/oci/include -I/usr/lib/oracle/12.1/client64/rdbms/public -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-9.6/include/server -I/usr/pgsql-9.6/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_fdw.o oracle_fdw.c
oracle_fdw.c: In Funktion »deparseExpr«:
oracle_fdw.c:2820:2: Fehler: unbekannter Typname: »SQLValueFunction«
  SQLValueFunction *sqlvalfunc;
  ^
oracle_fdw.c:2820:20: Warnung: Variable »sqlvalfunc« wird nicht verwendet [-Wunused-variable]
  SQLValueFunction *sqlvalfunc;
                    ^
make: *** [oracle_fdw.o] Fehler 1

**Comment by laurenz** [comment]
Thanks for the report.
