### ISSUE TITLE
Non English Characters are turned into nulls

### ISSUE THREAD

**Issue by vdedyukhin** [laurenz/oracle_fdw#125]
```
CREATE EXTENSION oracle_fdw;
CREATE FOREIGN DATA WRAPPER oracle_fdw_al32utf8 HANDLER oracle_fdw_handler VALIDATOR oracle_fdw_validator OPTIONS (nls_lang 'ENGLISH_UNITED KINGDOM.AL32UTF8');
CREATE SERVER oradb FOREIGN DATA WRAPPER oracle_fdw_al32utf8 OPTIONS (dbserver '//server.net:1521/orcl.server.net');
GRANT USAGE ON FOREIGN SERVER oradb TO postgres;
CREATE USER MAPPING FOR postgres SERVER oradb OPTIONS (user 'user', password 'password');
```

`SELECT oracle_diag('oradb');`

oracle_fdw 1.5.1devel, PostgreSQL 9.3.9, Oracle client 12.1.0.2.0, Oracle server 12.1.0.2.0

```
CREATE FOREIGN TABLE calldirection (
ncd_id int8,
ncd_name VARCHAR(255),
ncd_price float8,
ncd_rusname VARCHAR(255)
) SERVER oradb OPTIONS (schema 'schema', table 'CALLDIRECTION');
ALTER FOREIGN TABLE calldirection OWNER TO postgres;
```

`SELECT * FROM calldirection ORDER BY ncd_id;`

1	Abkhazia	1	(null)
2	Abkhazia - Mobile	1	(null)
3	Abkhazia - Mobile - A-Mobile	1	(null)
4	Abkhazia - Mobile - Aquafon	1	(null)
5	Afghanistan	1	(null)
6	Afghanistan - Mobile - AWCC	1	(null)
7	Afghanistan - Mobile - At	1	(null)

In SQL Developer:

1	Abkhazia	1	Страна
2	Abkhazia - Mobile	1	Страна
3	Abkhazia - Mobile - A-Mobile	1	Страна
4	Abkhazia - Mobile - Aquafon	1	Страна
5	Afghanistan	1	Страна
6	Afghanistan - Mobile - AWCC	1	Страна
7	Afghanistan - Mobile - At	1	Страна

In a big table with many columns numeric columns like '1' also become to just '0', columns with English characters after the column with Cyrillic characters become to (null). Eliminating the Cyrillic column fixes the issue.

```
select DECODE(parameter, 'NLS_CHARACTERSET', 'CHARACTER SET',
'NLS_LANGUAGE', 'LANGUAGE',
'NLS_TERRITORY', 'TERRITORY') name,
value from v$nls_parameters
WHERE parameter IN ( 'NLS_CHARACTERSET', 'NLS_LANGUAGE', 'NLS_TERRITORY')
```
LANGUAGE	ENGLISH
TERRITORY	UNITED KINGDOM
CHARACTER SET	AL32UTF8

`SHOW server_encoding;`
 UTF8

Wasted all day, couldn't figure it out.

**Comment by laurenz** [comment]
What PostgreSQL client program are you using that displays these `NULL` values?
I tried with `psql`, pgAdmin III and pgAdmin4, and the Cyrillic letters were displayed as they should be.

I'd be curious to know the binary contents of the respective fields.
In Oracle, it looks for me like that:

    SQL> SELECT DUMP(ncd_rusname, 16) FROM calldirection WHERE ncd_id = 1;

    DUMP(NCD_RUSNAME,16)
    --------------------------------------------------------------------------------
    Typ=1 Len=12: d0,a1,d1,82,d1,80,d0,b0,d0,bd,d0,b0

In PostgreSQL I get

    test=> SELECT ncd_rusname::bytea::text FROM calldirection WHERE ncd_id = 1;
    ┌────────────────────────────┐
    │        ncd_rusname         │
    ├────────────────────────────┤
    │ \xd0a1d182d180d0b0d0bdd0b0 │
    └────────────────────────────┘
    (1 row)

Is it different for you?

My configuration is like yours, except I use PostgreSQL 9.6, Oracle client 11.2 and the Oracle database has `NLS_TERRITORY` set to `AMERICA` and `NLS_LANGUAGE` set to `AMERICAN`, but that shouldn't make a difference; all that matters is the encoding.

Do you get the same result if you do not explicitly set the `nls_lang` option on the foreign data wrapper?
