### ISSUE TITLE
ERROR: could not write to hash-join temporary file: No space left on device

### ISSUE THREAD

**Issue by michaeloa** [laurenz/oracle_fdw#126]
Hi,

I'm trying to join two tables from Oracle. Both are quite large (about 40M rows), but I'm joining on a 1-1 basis, and limiting the queries in addition (the result set is around a couple of thousand rows).

Unfortunately I'm ending up with the above error message, although I cannot see on the database server that it is running out of space.

Any thoughts on what might be going wrong?

**Comment by laurenz** [comment]
The tables must be quite large.

oracle_fdw cannot push own the join to Oracle, so it fetches all relevant data to PostgreSQL and performs the join there.
In a hash join, a temporary hash structure is created for the first table (the lower one in the `EXPLAIN` output). This hash structure is so large in your case that it exceeds the available disk space in your PostgreSQL data directory.

The reason why you don't see these files is probably that the whole thing happens rather quickly, and the temporary files are deleted after the query aborts.

**Comment by michaeloa** [comment]
Guessed it might be something like that, though surprised that I can't see the changes (query does take a fair amount of time)

The Oracle db is legacy (of course), and the table structure is anything but conducive to good SQL queries (lots of attributes - not normalized at all). Unfortunately, we have to live with it for some time to come.

Do selections and projections get pushed down; i.e., if I rewrite the query manually with nested SELECT... FROM...WHERE... inside the joins, would that reduce the amount of data retrieved through the FDW interface? The actual data that is needed is actually pretty small, so that would work around pretty well for this case. Also has some implications for some other queries I've written which work - but  should probably be optimized a bit.

Will test this on monday, but presumably you already know the answer.

**Comment by laurenz** [comment]
Yes, oracle_fdw will try to push down conditions wherever it is safe to do so, so your approach should definitely improve matters.

If the optimizer chooses to still do something else, you can force the behaviour with a query like that:

    WITH
       a AS (SELECT ... FROM ext_tbl1 WHERE ...),
       b AS (SELECT ... FROM ext_tbl2 WHERE ...)
    SELECT ... FROM a JOIN b ON ...;

**Comment by michaeloa** [comment]
This seems to have solved the problem.

I found also that the problem was being exacerbated by a faulty conversion from Oracle's Date format to Postgres - although it looked like it was just a Date in Oracle, it was actually a Timestamp, and something went completely wrong in the joins on the Postgres side as a result; i.e.., a join supposed to return 750 rows (and doing so correctly on the Oracle db) suddenly returned 24 times as many on the Postgres side.
