### ISSUE TITLE
Can not access from another user

### ISSUE THREAD

**Issue by todoubaba** [laurenz/oracle_fdw#130]
My database have two schemas (s1, s2) and two users (u1, u2). 

```
CREATE SCHEMA s1 AUTHORIZATION u1;
CREATE SCHEMA s2 AUTHORIZATION u2;
```

u1 created a foreign table e1, and can asscess it without problem.

```
\c test u1
grant select on s1.e1 to u2;
\c test u2
select * from s1.e1;
```

Error:
```
Oracle table "XX"."YY" for foreign table "e1" does not exist or does not allow read access
ORA-00942: table or view does not exist
Oracle table names are case sensitive (normally all uppercase).
```

**Comment by laurenz** [comment]
How do the user mappings for `u1` and `u2` look?  
Do they use the same Oracle user?  
What options were used to create the foreign table?

**Comment by todoubaba** [comment]
They are mapped to different Oracle users:
```
CREATE USER MAPPING FOR u1 SERVER s OPTIONS (user 'u1',password 'p1');
CREATE USER MAPPING FOR u2 SERVER s OPTIONS (user 'u2',password 'p2');
```

```
CREATE FOREIGN TABLE s1.e1 (
    id integer,
    ...
) SERVER zf OPTIONS (schema 'U1', table 'E1', readonly 'true');
```

**Comment by laurenz** [comment]
My guess is that Oracle user `U2` does not have the `SELECT` privilege for table `U1.E1`.

Try the following as user `U1` in Oracle:

    GRANT SELECT ON e1 TO u2;

**Comment by todoubaba** [comment]
‘U1.E1' is a view which access another user's data. After 'GRANT SELECT ON u1.e1 TO u2;', returns the following error:
```
error describing remote table: OCIStmtExecute failed to describe table
ORA-01031: insufficient privileges
```

**Comment by todoubaba** [comment]
Oracle `U2` has privileges on those tables. I need grant privileges to Oracle `U1`  with `WITH GRANT OPTION`, it works now.
But I still confuse about the grant path.

Thanks for your patience and support.
