### ISSUE TITLE
Cannont Connect to foreign server using connect identifier in tnsnames file

### ISSUE THREAD

**Issue by chestercharles** [laurenz/oracle_fdw#131]
Hi laurenz,

My issue is very similiar to https://github.com/laurenz/oracle_fdw/issues/71

I'm able to connect to my oracle database using:

```
sqlplus64 postgres/password@FCSPROD
```

where FCSPROD is specified in my tnsnames file.

To create the foreign server and user mapping:

```
create server fcsprod foreign data wrapper oracle_fdw
options(dbserver 'FCSPROD');

create user mapping for postgres server fcsprod
options (user 'postgres', password 'password');
```

Similiar to #71, when I run

```
 select oracle_diag('fcsprod')
```

I get 

```
ERROR:  cannot connect to foreign Oracle server
DETAIL:  ORA-12154: TNS:could not resolve the connect identifier specified
```

Using:
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit
PostgreSQL v9.3

Any idea what I'm doing wrong?

**Comment by chestercharles** [comment]
U

**Comment by chestercharles** [comment]
UPDATE:

The tnsname I was using before had the connect info for an oracle db with two nodes (one fails over to the other):

    FCSPROD=
     (DESCRIPTION= 
       (LOAD_BALANCE=on) 
       (FAILOVER=on)
       (ADDRESS_LIST= 
         (SOURCE_ROUTE=yes) 
         (ADDRESS=(PROTOCOL=tcp)(HOST=123.456.789.1)(PORT=1630)) 
         (ADDRESS=(PROTOCOL=tcp)(HOST=123.456.789.2)(PORT=1521)))
       (CONNECT_DATA=(SERVICE_NAME=MY_SRVC))

I was able to connect after using the IP and service name for the currently active node:
    
    create server fcsprod foreign data wrapper oracle_fdw
    options(dbserver '123.456.789.1/MY_SRVC');

Is it possible to set up the dbserver option so that it uses the tnsname?

**Comment by laurenz** [comment]
You can certainly use a `tnsnames.ora` file with oracle_fdw.

I suspect that the environment variable `TNS_ADMIN` is not set correctly in the environment of the PostgreSQL server process; if it is set, your `tnsnames.ora` will be found.

What is your operating system? How is your PostgreSQL server started? If you set (and export) `TNS_ADMIN` manually and start PostgreSQL manually with `pg_ctl start`, does it work?

Note, however, that oracle_fdw is not written to support Transparent Application Failover. If a node goes down, you will probably get an error message, but the next request should work again.

**Comment by mixmind** [comment]
Hello, i have the same problem with tnsnames.ora. 

Added to systemctl TNS_ADMIN environment , didnt helped. Tried to run with pg_ctl and TNS_ADMIN before it, still not working.
Can you help with this issue?
File located here:  /usr/lib/oracle/19.10/client64/network/admin/tnsnames.ora 
Version of sqlplus and co used for building extension is 19.10 and postgresql 12. OS Centos 7.

Thanks for help.
