### ISSUE TITLE
 OCIEnvCreate failed to create environment handle.

### ISSUE THREAD

**Issue by i-techsolutions** [laurenz/oracle_fdw#133]
I have installed Oracel FDW on REDHAT.

I am able to create extension as well as Server & foreign table.

When I make command 

`select * from my_f_table;`

I am getting following error.

```
Error : error connecting to oracle : OCIEnvCreate failed to create environment handle.
DETAIL : Error while trying to retrieve text for error ORA-01804
```

I have checked for the path of 
ORACLE_HOME
LD_LIBRARY_PATH
TNS_ADMIN
everything is fine.

My Oracle Client, Postgres 9.3 & Oracle server all are 64-bit.

Please help.

**Comment by laurenz** [comment]
The DETAIL message (which is the Oracle error message) suggests that something is wrong with your setup, and Oracle cannot find the message files.

That error usually means a setup problem: bad environment variables, libraries from different Oracle installations, etc.

- Can you connect with sqlplus as PostgreSQL operating system user?
- Can you see the environment variables in `/proc/xxxx/environ`  (where `xxxx` is the process ID of the PostgreSQL server process)?
- Can you tell me what Oracle software is installed on the PostgreSQL server?

**Comment by i-techsolutions** [comment]
Hi Laurenz,

I am able to connect with sqlplus as PostgreSQL OS user successfully.
I can also see all the environment variables.
Oracle Client from oracle web site is installed on postgresql server.

**Comment by laurenz** [comment]
Which Oracle client are you using? Instant Client or the client installed with Oracle Universal Installer?
Also, is there any other Oracle software on the machine? Sometimes you get that error if libraries from different installations get mixed up.

Other than that, I have no clue. Unfortunately this Oracle error message is very general and does not help us a lot.

Can you post the output of

    SELECT oracle_diag();

and the exact Oracle version?

**Comment by i-techsolutions** [comment]
Hi laurenz,
Output of the given command is
"oracle_fdw 1.5.0, PostgreSQL 9.3.13, Oracle client 11.2.0.3.0"

I do not have any other installation on this mmachine.

It only contains
PostgreSQl 9.3.13
& Oracle client 11.2.0.3.0

**Comment by laurenz** [comment]
Well, I don't know what to suggest.

You could post the output of `set` when you are logged on as PostgreSQL OS user and sqlplus works, and then the contents of the `environ` file of the PostgreSQL server process, and I can compare them and see if I spot any obvious mistakes.

You could also try and run a `strace` on the PostgreSQL backend process and then run the `SELECT` that produces the error. Maybe the `strace` output shows where things go wrong.

Other than that, I have no idea.

**Comment by i-techsolutions** [comment]
Hi laurenz,
Kindly find all attached file.
I have run the command with root user as well as with postgres user.
Also have developed oraserver & created foreign table being root & postgres user but getting same error.
I hope this files will help you to find out the issue which I am facing right now.
[procedure_followed for fdw.txt](https://github.com/laurenz/oracle_fdw/files/558419/procedure_followed.for.fdw.txt)
[env - postgres user.txt](https://github.com/laurenz/oracle_fdw/files/558420/env.-.postgres.user.txt)
[set - root user.txt](https://github.com/laurenz/oracle_fdw/files/558421/set.-.root.user.txt)
[strace - postgres user.txt](https://github.com/laurenz/oracle_fdw/files/558422/strace.-.postgres.user.txt)
[strace - root user.txt](https://github.com/laurenz/oracle_fdw/files/558423/strace.-.root.user.txt)
[set - postgres user.txt](https://github.com/laurenz/oracle_fdw/files/558424/set.-.postgres.user.txt)
[env - root user.txt](https://github.com/laurenz/oracle_fdw/files/558426/env.-.root.user.txt)

**Comment by laurenz** [comment]
It seems like you didn't set the Oracle environment.

You probably need at least:

    ORACLE_HOME=/oracle/OraBase11203/product/11.2.0/client_64
    LD_LIBRARY_PATH=/oracle/OraBase11203/product/11.2.0/client_64/lib

**Comment by i-techsolutions** [comment]
After setting all the variable
ORACLE_HOME
LD_LIBRARY_PATH
TNS_ADMIN
PATH

I am getting the same error.

**Comment by i-techsolutions** [comment]
kindly check these all files
[env-PostgesUser.txt](https://github.com/laurenz/oracle_fdw/files/566060/env-PostgesUser.txt)
[env-RootUser.txt](https://github.com/laurenz/oracle_fdw/files/566065/env-RootUser.txt)
[set-PostgesUser.txt](https://github.com/laurenz/oracle_fdw/files/566061/set-PostgesUser.txt)
[set-RootUser.txt](https://github.com/laurenz/oracle_fdw/files/566062/set-RootUser.txt)
[strace-PostgesUser.txt](https://github.com/laurenz/oracle_fdw/files/566063/strace-PostgesUser.txt)
[strace-RootUser.txt](https://github.com/laurenz/oracle_fdw/files/566064/strace-RootUser.txt)

**Comment by i-techsolutions** [comment]
Hi Laurenz,
The foreign table which am creating as actually a view in Oracle,so is thus the issue?
If yes then how can I develop fdw for view.

**Comment by laurenz** [comment]
Make sure that the environment variables are set in the environment of the PostgreSQL server process. If the process of of the PostgreSQL server process (the &ldquo;postmaster&rdquo;) is 12345, that would look like this:

    cat /proc/19761/environ | xargs -0 -n 1 echo | sort

See if ORACLE_HOME and LD_LIBRARY_PATH are in there.

Finally, your `strace` logs are pretty useless. You seem to run

    strace ls -l *

or something similar which just traces the execution of the `ls` command. What you *should* do is start a PostgreSQL session, find out the process ID with

    SELECT pg_backend_pid();

and, assuming that the result is 11223, run the following in a different shell:

    strace -f -o trace.out -p 11223

Then issue the `SELECT` statement that causes the error.

After that, interrupt `strace` with Ctrl+C and look at the `trace.out` file to see what system calls are issued and how they fail.

**Comment by laurenz** [comment]
And no, a view in Oracle should work just fine.
Your problem happens much earlier, even before oracle_fdw connects to the Oracle database server.
The meaning of the error message is that the Oracle client library cannot find everything it needs on the client machine.

**Comment by i-techsolutions** [comment]
For
cat /proc/19761/environ | xargs -0 -n 1 echo | sort
I am getting
cat /proc/19761/environ : No such file or directory

**Comment by laurenz** [comment]
You have to replace 19761 with the process ID of the postmaster on your system.

**Comment by i-techsolutions** [comment]
Thanks Laurenze.
It got solved.
There was issue in path because of which it was not accessible

**Comment by laurenz** [comment]
Thanks for the feedback, it will help others.

**Comment by chandragie** [comment]
This helped me today! Thanks a lot.
