### ISSUE TITLE
Incorrect import foreign schema for objects with rowid column

### ISSUE THREAD

**Issue by aleksaan** [laurenz/oracle_fdw#134]
There is a column with "rowid" type. After foreign table creation, an error occurs when trying to select that column: "column "row_id" of foreign table "table_name" cannot be converted to or from Oracle data type" HV004

Import foreign schema suggests "text" column type for oracle's "rowid" type.

PostgreSQL 9.6.1 x64 on Windows
Oracle 11.2.0.4 on RHEL x64

**Comment by laurenz** [comment]
No mapping for the Oracle data type `ROWID` has been implemented.

If you want to have such a column in a foreign table, either define a view in Oracle or use a foreign table based on a query, like

    CREATE FOREIGN TABLE r (
      id integer OPTIONS (key 'true') NOT NULL,
      r text
    ) SERVER oracle
       OPTIONS (table '(SELECT id, CAST(r AS VARCHAR2(30)) FROM r)');
