### ISSUE TITLE
 Incorrect date cast while "where" clause pushdown

### ISSUE THREAD

**Issue by aleksaan** [laurenz/oracle_fdw#135]
There is a table in Oracle with column of "date" type. It is successfully imported into foreign table as "date" column type.
Then, while trying to SELECT deal_date, value FROM table_name WHERE deal_date = '01.09.2016' gives an error ORA-01861: literal does not match format string
EXPLAIN clause before that SELECT shows the following:
"Oracle query: SELECT /*5e...8d*/ deal_date, value FROM "ora"."table_name" WHERE (deal_date = (CAST ('2016-09-01 00:00:00.000000 AD' AS TIMESTAMP)))"
Looks like Oracle doesn't recognize that date format. Manipulations with "timestamp" data type didn't help either.

PostgreSQL 9.6.1 x64 on Windows
Oracle 11.2.0.4 on RHEL x64

**Comment by laurenz** [comment]
Please show the output of

    SELECT oracle_diag('servername');

where `servername` should be replaced with the name of your foreign server.

The reason I'm asking is that there have been several bugs with older versions of oracle_fdw and date or timestamp columns.

A reproducible test case would help.

What you describe seems to work fine here.

With this table:

    SQL> DESC datetest
     Name                                      Null?    Type
     ----------------------------------------- -------- ----------------------------
     ID                                        NOT NULL NUMBER(5)
     D                                                  DATE

I can do this:

    test=> \d datetest
           Foreign table "laurenz.datetest"
    ┌────────┬─────────┬───────────┬──────────────┐
    │ Column │  Type   │ Modifiers │ FDW Options  │
    ├────────┼─────────┼───────────┼──────────────┤
    │ id     │ integer │ not null  │ (key 'true') │
    │ d      │ date    │           │              │
    └────────┴─────────┴───────────┴──────────────┘
    Server: oracle
    FDW Options: ("table" 'DATETEST')

    test=> SET DateStyle=German;
    test=> SELECT * FROM datetest WHERE d = '01.09.2016';

    ┌────┬────────────┐
    │ id │     d      │
    ├────┼────────────┤
    │  6 │ 01.09.2016 │
    └────┴────────────┘
    (1 row)

**Comment by aleksaan** [comment]
SELECT oracle_diag('ora');
"oracle_fdw 1.5.0, PostgreSQL 9.6.1, Oracle client 11.2.0.1.0, Oracle server 11.2.0.3.0"

**Comment by laurenz** [comment]
Please provide a test case for me to reproduce the problem.

**Comment by aleksaan** [comment]
CREATE FOREIGN TABLE test_dt (d timestamp) SERVER db options(table '(select to_date(''01.09.2016'') d from dual)');
select d from test_dt where d = '01.09.2016' returns error:
DETAIL: ORA-01843: wrong month

EXPLAIN on that SELECT shows the following:
"Foreign Scan on test_dt  (cost=10000.00..20000.00 rows=1000 width=8)"
"  Oracle query: SELECT /*ebcb3d4bff279c7ef9f02f4b3731f9a5*/ "D" FROM (select to_date('01.09.2016') d from dual) WHERE ("D" = (CAST ('2016-09-01 00:00:00.000000 AD' AS TIMESTAMP)))"

**Comment by laurenz** [comment]
That is as expected.

oracle_fdw sets `NLS_DATE_FORMAT` to `YYYY-MM-DD HH24:MI:SS BC`, and the string you are using does not conform to this format.

To make your test work, include an explicit format like this:

    '(SELECT to_date(''01.09.2016'', ''DD.MM.YYYY'') d FROM dual)'

**Comment by aleksaan** [comment]
The point is that wrong date is being composed during WHERE clause pushdown, so fixing source query doesn't fix the problem. Is it possible to change NLS_DATE_FORMAT to YYYY-MM-DD HH24:MI:SS?

**Comment by laurenz** [comment]
My problem is that I cannot reproduce your problem.

When I run

    SELECT * FROM datetest WHERE d = '01.09.2016';

as I described above, the query run on Oracle is

    SELECT "ID", "D" FROM "DATETEST" WHERE ("D" = (CAST ('2016-09-01 00:00:00 AD' AS DATE)));

which is quite different from what you see.

Moreover, if I try

    ALTER SESSION SET nls_timestamp_format = 'YYYY-MM-DD HH24:MI:SS.FF9 BC';
    SELECT (CAST ('2016-09-01 00:00:00.000000 AD' AS TIMESTAMP)) FROM dual;

to simulate the query you see with oracle_fdw, it works just fine.

I assume that that settings in V$PARAMETER are the same as in #136, is that correct?

So you see, having `CREATE TABLE` and `INSERT` statements on Oracle as well as `CREATE FOREIGN TABLE` and `SELECT` statements in PostgreSQL that let me reproduce at least your query would be very helpful for me.

**Comment by laurenz** [comment]
Can you provide Oracle `CREATE TABLE` and PostgreSQL `CREATE FOREIGN TABLE` statements?

**Comment by laurenz** [comment]
I'll close this because of inactivity, please don't hesitate to reopen it if you have a reproducible test case or new information.

**Comment by laurenz** [comment]
@alirazaidi Don't add your issue to a different issue - start a new one.
