### ISSUE TITLE
Oracle returns comma separated numeric values

### ISSUE THREAD

**Issue by aleksaan** [laurenz/oracle_fdw#136]
Foreign table successfully created. It contains a few numeric columns with floating point delimiter. It is impossible to execute SELECT command because Oracle returns numbers with comma delimited floating point and PostgreSQL cannot recognize it as number. Hence, we have to create foreign table with text columns instead of numeric and then parse and convert numbers on the postgres side. Performance of this approach is unacceptable and no pushdowns are possible anymore.

PostgreSQL 9.6.1 x64 on Windows
Oracle 11.2.0.4 on RHEL x64

**Comment by laurenz** [comment]
Floating point numbers should work just fine, regardless of the settings in Oracle.

oracle_fdw sets `NLS_NUMERIC_CHARACTERS` to `.,` so that floating point numbers should always be sent with a period as decimal separator.

Can you provide a test case for me to reproduce the problem?
What is the setting of `lc_numeric` in PostgreSQL?
What do you get in Oracle for

    SELECT parameter, value
    FROM nls_database_parameters
    WHERE parameter IN ('NLS_LANGUAGE', 'NLS_TERRITORY');

**Comment by aleksaan** [comment]
lc_numeric = 'Russian_Russia.1251'

Oracle config:
NLS_LANGUAGE AMERICAN
NLS_TERRITORY AMERICA

**Comment by laurenz** [comment]
Thanks. Can you provide a test case so I can reproduce the problem?

**Comment by aleksaan** [comment]
CREATE FOREIGN TABLE test1 (t numeric) SERVER db options(table '(select 1.05 t from dual)');
SELECT * FROM test1 fails to execute in my environment.

At the same time,
CREATE FOREIGN TABLE test2 (t text) SERVER db options(table '(select 1.05 t from dual)');
SELECT * FROM test2 returns
t
text
----
1,05

ERROR: wrong syntax for type numeric: "1,05"
CONTEXT: converting column "t" for foreign table scan of "test1", row 1
SQL state: 22P02

**Comment by laurenz** [comment]
Strange.
Could you see that you have SELECT privileges on V$PARAMETER and try the following:

    CREATE FOREIGN TABLE nls_params (name text, value text)
       SERVER db OPTIONS (
          table '(SELECT name, value FROM v$parameter WHERE lower(name) LIKE ''%nls%'')'
       );

and then run

    SELECT * FROM nls_params;

Please show me what you get.

**Comment by aleksaan** [comment]
"nls_language";"RUSSIAN"
"nls_territory";"RUSSIA"
"nls_sort";"BINARY"
"nls_date_language";"AMERICAN"
"nls_date_format";"dd.mm.yyyy"
"nls_currency";"$"
"nls_numeric_characters";".,"
"nls_iso_currency";"AMERICA"
"nls_calendar";"GREGORIAN"
"nls_time_format";"HH.MI.SSXFF AM"
"nls_timestamp_format";"YYYY-MM-DD HH24:MI:SS.FF9 BC"
"nls_time_tz_format";"HH.MI.SSXFF AM TZR"
"nls_timestamp_tz_format";"YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC"
"nls_dual_currency";"$"
"nls_comp";"BINARY"
"nls_length_semantics";"BYTE"
"nls_nchar_conv_excp";"FALSE"

**Comment by laurenz** [comment]
I'll try to get an Oracle client with support for Russian and see if I can reproduce it.

It is quite strange that you see a comma when `nls_numeric_characters` is set to `.,`.

Can you reproduce this with sqlplus:

    ALTER SESSION SET nls_numeric_characters= '.,';
    SELECT 1.05 FROM dual;

and see if you get the comma as well.

**Comment by laurenz** [comment]
I installed an Instant Client with support for Russian, and everything works fine for me.

Can you tell me the table definition in Oracle and the foreign table definition in PostgreSQL?

**Comment by laurenz** [comment]
I'll close this because of inactivity, please reopen it if there is new information.

**Comment by ddelboux** [comment]
Hi,
I´m having the same issue on a postgres 10 on Linux.

The strange thing is that when you create a foreign table like:

CREATE FOREIGN TABLE nls_params (valor numeric) SERVER mega175 OPTIONS (table '(SELECT 1/3 from dual)');

The result is 
                   valor
--------------------------------------------
 0.3333333333333333333333333333333333333333

But when I make a select on a table that contains I number column in Oracle the error ocurs because of the ","

**Comment by laurenz** [comment]
Is this also a Russian Oracle database? What is the character set?

On which operating system are the PostgreSQL and Oracle server?

Can you show me the SQL statements for the definition of the Oracle table and the PostgreSQL foreign table?

Can you create the foreign table `nls_params` I described above and show me what is in it?

**Comment by ddelboux** [comment]
Oracle is in american, the character set is WE8MSWIN1252

The operation system and oracle is in linux

The view in oracle is:

  CREATE OR REPLACE FORCE VIEW "MGCUSTOM"."PREVISAO_RET_CONTSOC" ("ID_MOVIMENTO", "PREVISAO_PIS", "PREVISAO_COFINS", "PREVISAO_CSLL", "PREVISAO_SALDO") AS
  SELECT ID_MOVIMENTO,
       TO_NUMBER(substr(VALORES,
                 instr(VALORES, ':', 1, 1)+1,
                 (instr(VALORES, '#', 1, 1)-
                  (instr(VALORES, ':', 1, 1)+1)))) PREVISAO_PIS,
       TO_NUMBER(substr(VALORES,
                 instr(VALORES, ':', 1, 2)+1,
                 (instr(VALORES, '#', 1, 2)-
                  (instr(VALORES, ':', 1, 2)+1)))) PREVISAO_COFINS,
       TO_NUMBER(substr(VALORES,
                 instr(VALORES, ':', 1, 3)+1,
                 (instr(VALORES, '#', 1, 3)-
                  (instr(VALORES, ':', 1, 3)+1)))) PREVISAO_CSLL,
       TO_NUMBER(substr(VALORES,
                 instr(VALORES, ':', 1, 4)+1,
                 (instr(VALORES, '#', 1, 4)-
                  (instr(VALORES, ':', 1, 4)+1)))) PREVISAO_SALDO
FROM
(
SELECT TO_CHAR(ORG_IN_CODIGO)||'-'||TO_CHAR(MOV_IN_NUMLANCTO) ID_MOVIMENTO,
       (select 'PIS: '   ||TO_CHAR(NVL(PRE_RE_VRPIS, 0))||' # '||
               'COFINS: '||TO_CHAR(NVL(PRE_RE_VRCOFINS, 0))||' # '||
               'CSLL: '  ||TO_CHAR(NVL(PRE_RE_VRCSLL, 0))||' # '||
               'SALDO: ' ||TO_CHAR(NVL(PRE_RE_VRLIQUIDO, 0))||' #'
          from table(MGFIN.FIN_PCK_CONTSOC.F_PrevisaoPCC('<PrevisaoPcc>' ||
                                                            '<AP>'  ||
                                                              '<MOV_IN_NUMLANCTO>'  || MOV_IN_NUMLANCTO ||'</MOV_IN_NUMLANCTO>'   ||
                                                              '<MOV_SEQ_IN_CODIGO>' || MOV_SEQ_IN_CODIGO ||'</MOV_SEQ_IN_CODIGO>' ||
                                                            '</AP>' ||
                                                          '</PrevisaoPcc>',
                                                         'P',
                                                         'B',
                                                         'N'))) VALORES
 FROM (
        SELECT MOV.ORG_IN_CODIGO, MOV.MOV_SEQ_IN_CODIGO, MOV.MOV_IN_NUMLANCTO
          FROM MGFIN.FIN_MOVIMENTO    MOV,
               MGFIN.FIN_CONTASPAGAR  CPA,
               MGGLO.GLO_AGENTES      AGN
         WHERE MOV.ORG_TAB_IN_CODIGO   = CPA.ORG_TAB_IN_CODIGO
           AND MOV.ORG_PAD_IN_CODIGO   = CPA.ORG_PAD_IN_CODIGO
           AND MOV.ORG_IN_CODIGO       = CPA.ORG_IN_CODIGO
           AND MOV.ORG_TAU_ST_CODIGO   = CPA.ORG_TAU_ST_CODIGO
           AND MOV.MOV_TAB_IN_CODIGO   = CPA.MOV_TAB_IN_CODIGO
           AND MOV.MOV_SEQ_IN_CODIGO   = CPA.MOV_SEQ_IN_CODIGO
           AND MOV.MOV_IN_NUMLANCTO    = CPA.MOV_IN_NUMLANCTO
           AND MOV.AGN_TAB_IN_CODIGO   = AGN.AGN_TAB_IN_CODIGO
           AND MOV.AGN_PAD_IN_CODIGO   = AGN.AGN_PAD_IN_CODIGO
           AND MOV.AGN_IN_CODIGO       = AGN.AGN_IN_CODIGO
           AND MOV.MOV_CH_ORIGEM       = 'P'
           AND MOV.MOV_CH_STATUSBXREF  = 'N'
           AND MOV.MOV_CH_SITUACAO     = 'N'
           AND AGN.AGN_CH_TIPOPESSOAFJ = 'J'
           AND MOV.MOV_RE_SALDOCPACRE > 0
       )
)

and the foreign table

 CREATE FOREIGN TABLE PREVISAO_RET_CONTSOC
 (ID_MOVIMENTO      VARCHAR(81)
 ,PREVISAO_PIS      numeric
 ,PREVISAO_COFINS   numeric
 ,PREVISAO_CSLL     numeric
 ,PREVISAO_SALDO    numeric) 
 server mega175 options (schema 'MGCUSTOM', table 'PREVISAO_RET_CONTSOC');

**Comment by laurenz** [comment]
What can you see in the `nls_param` view?

What is the exact error message you get?

Could it be that the `to_number` call in your view fails because you rely on a `NLS_NUMERIC_CHARACTERS` setting that defines `,` as decimal separator?

Then it would be a different problem, and you'd have to fix your view so that it works with `NLS_NUMERIC_CHARACTERS = '.,'`.
