### ISSUE TITLE
Can not install for Postgres 9.6 and Oracle 11.2.0.4

### ISSUE THREAD

**Issue by ardilgulez** [laurenz/oracle_fdw#137]
Hello,

I have been having a difficulty installing oracle fdw for postgresql 9.6 (with postgis 2.3) and oracle instant client 11.2.0.4. When I try "make", it gives me this error:

/usr/bin/ld: cannot find -lclntsh
collect2: error: ld returned 1 exit status
/usr/lib/postgresql/9.6/lib/pgxs/src/makefiles/../../src/Makefile.shlib:310: recipe for target 'oracle_fdw.so' failed
make: *** [oracle_fdw.so] Error 1

I can't figure out why this problem occurs and how I can solve them. Can you help please?

Thanks in advance.

**Comment by laurenz** [comment]
These two causes come to my mind:

1. You didn't set the `ORACLE_HOME`.
  But then you probably wouldn't have found the Oracle header files, and the error message would be different.

2. You don't have a symbolic link `libclntsh.so` in `ORACLE_HOME`.
  Oracle Instant Client, if not installed with RPM, lacks this.
  This is documented in the README in the "Installation" section.
  Change into that directory and run

      ln -s libclntsh.so.11.1 libclntsh.so

**Comment by ardilgulez** [comment]
I had done the first but hadn't done the second. I have done both of them. "make" works now and so does "sudo make install". But when I try to "create extension oracle_fdw;", it says:

ERROR:  could not load library "/usr/lib/postgresql/9.6/lib/oracle_fdw.so": libclntsh.so.11.1: cannot open shared object file: No such file or directory

********** Error **********

ERROR: could not load library "/usr/lib/postgresql/9.6/lib/oracle_fdw.so": libclntsh.so.11.1: cannot open shared object file: No such file or directory
SQL state: XX000

I have my ORACLE_HOME variable in PATH too.

**Comment by laurenz** [comment]
Don't forget to restart the PostgreSQL server after that so that the PostgreSQL server process can pick up the changed environment.

Also make sure that you don't set `LD_LIBRARY_PATH` in your `.bash_profile` or similar, because most PostgreSQL startup scripts will not start a login shell. Using `/etc/ld.so.conf` is usually the better choice, see `man ldconfig`.

**Comment by ardilgulez** [comment]
Thank you so much for all the help. "CREATE EXTENSION oracle_fdw;" now works. Are there any other "gotcha"s or stuff that I need to be aware of?

**Comment by laurenz** [comment]
The next hurdle is to successfully connect to Oracle during a `SELECT` from a foreign table. Try it and see if it works.

**Comment by lupynos** [comment]
Just remark: the symbolic link is to be created to the particular version of the Oracle Client, ie:

`ln -s libclntsh.so.19.1 libclntsh.so`
