### ISSUE TITLE
PGAdmin hangs on selecting data from foreign table

### ISSUE THREAD

**Issue by mbwiese** [laurenz/oracle_fdw#139]
I have defined a foreign table in PostGreSQL, refering to an oracle table at another server.
PGAdmin stops responding whenever I try to view the data, and I have to kill PostgreSQL.exe manually (after 10 at least minutes)
I have this problem both in PGAdmin III version 1.22.0 and in PGAdmin 4 version 1.11, therefore I think problem is not in PGAdmin.
This is the only foreign table I have defined at the moment.  It worked a couple of months ago.

SELECT oracle_diag('servername') never returns.
SELECT oracle_fdw oracle_diag() gives:
**oracle_fdw 1.5.0, PostgreSQL 9.5.0, Oracle client 11.2.0.2.0, TNS_ADMIN=\\path\to\tnsnames.ora**

I can see table data via SQLPlus from the server where PostGreSQL is installed.

/Marianne

**Comment by laurenz** [comment]
If `SELECT oracle_diag('servername')` hangs, you have a problem connecting to the Oracle database.

Could you let the session hang for more than two hours and see if an error is returned eventually? Some network timeouts can take that long.

Can you see the connection attempt from oracle_fdw in `listener.log` on the Oracle server?

The best thing would be to perform an SQL*Net trace on the client side:
In `sqlnet.ora` on the client side (usually located in the same directory as `tnsnames.ora`), you'd add the following lines:

    TRACE_LEVEL_CLIENT = SUPPORT
    TRACE_DIRECTORY_CLIENT = C:\directory\with\write\access
    DIAG_ADR_ENABLED = OFF

Then restart the PostgreSQL server an try again. A trace file should be generated in the trace directory. In that you should be able to find the cause of the problem.

**Comment by mbwiese** [comment]
I let the sesion hang for 40 minutes, then stopped.

I need to talk to the DBA to get access to the listener.log on the Oracle server.

I made a local copy of `tnsnames.ora` / `sqlnet.ora`, where I added the trace lines you suggested.
Then I changed `TNS_ADMIN path parameter` accordingly.

It seems like PostgreSQL is not trying to connect to Oracle. At least, no trace file is being generated when I run `SELECT oracle_diag('server')`.
I updated Oracle InstantClient to the newest version and restarted PostGreSQL server, and the virtual machine on which it resides.

Connecting to Oracle via sqlPlus produces trace logs.

**Comment by laurenz** [comment]
What do you mean by *a local copy* of the configuration files? They have to reside in the directory set by `TNS_ADMIN`.

Could you trace execution with [Process Monitor][1] and see what happens before and during the hang.

It would be interesting to know if you get an error message if you let it hang for more than 2 hours.

[1]: https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx

**Comment by mbwiese** [comment]
By a local copy I mean, that our InstantClients on all servers are set to a common TNS_ADMIN path on the network. Since I wanted to trace only this particular postgres server, I made a local copy for tracing.  

I tried Process Monitor, but honestly it is too detailed for me to understand. I therefore tried Process Explorer, and it turns out, that when SELECT from my foreign table,  a request is sent not to the Oracle server but to some address ending with ldap. And nothing more happens. During my googling yesterday, I remember some old post, where you did recommended to not using LDAP, if I remember correct ?

Thank you for helping me so far. Meanwhile I have done a workaround, and cannot spend much more time on this issue right now.

Cheers, Marianne

**Comment by laurenz** [comment]
Ok, then I leave it closed.

Yes, Process Monitor will produce a lot of data. If you filter out everything except the PostgreSQL backend that accesses Oracle, the interesting operations should be right at the bottom (before it hangs).

But your result with Process Explorer is also interesting.
Do you recognize the address ending in LDAP? Can you tell me the name?

One idea: What is [`NAMES.DIRECTORY_PATH`][1] set to in your `sqlnet.ora`? The default value is `(tnsnames, ldap, ezconnect)`, so if there are problems finding or reading your `tnsnames.ora` file, Oracle client might proceed to try LDAP name resolution. Do you have an `ldap.ora` file where `DIRECTORY_SERVERS` is set?

The problems you mention with LDAP, PostgreSQL and Oracle naming lead to a crash, not a hang, so it must be something else.

[1]: http://docs.oracle.com/cd/E11882_01/network.112/e10835/sqlnet.htm#NETRF192

**Comment by mbwiese** [comment]
Yes, it is OK to leave it closed.

I realized, that in my `FOREIGN SERVER OPTIONS` dbserver string, I had written the connection details host:port/sid instead of the actual TNS name.
Testing with use of TNS name returns within 30 seconds, and never use more than 1 % of CPU (!)

However the result is **ORA-12154: TNS:could not resolve the connect identifier specified**
There is still no trace file from sqlnet.ora, and it seems strange, since oracle_diag() correctly identifies that I have upgraded my InstantClient, and gets the TNS_ADMIN path correct:
**oracle_fdw 1.5.0, PostgreSQL 9.5.0, Oracle client 11.2.0.4.0, TNS_ADMIN=C:\TEMP\TNS**

However, it seems from the Process Monitor information that Postgres requests go to a server named   geusc01.geus.dk:ldap , which must be one of our own servers. I have no idea, if this makes sense, would have to speak to network administrator for this.

The `NAMES.DIRECTORY_PATH` in `sqlnet.ora` is actually set to `(tnsnames, ezconnect)` , so that should be OK.

But, as I said, I have now to do some other work.
When I have more time, I will install a fresh instance of Postgres for test. As I said, I had a foreign table working from this same instance of Postgres in July this year.

**Comment by mbwiese** [comment]
I still cannot define a SERVER with a TNS name.
I think, that when I can connect with :  `sqlplus MBW/password@JUPITEST
`Then I should be able to define a SERVER with 
`CREATE SERVER jupt FOREIGN DATA WRAPPER oracle_fdw OPTIONS(dbserver 'JUPITEST')`
But, oracle_diag(server) in this case returns after 30 seconds with:
**ERROR:  cannot connect to foreign Oracle server
DETAIL:  ORA-12154: TNS:could not resolve the connect identifier specified**

However, my original issue: Postgres thread would use all CPU power in a core forever.
I can replicate on the Windows Server 2008R2  by my bad server definition with double backslashes:
`CREATE SERVER jupt FOREIGN DATA WRAPPER oracle_fdw OPTIONS(dbserver '\\server:port\dbname'); `
Even if the user tends to reverse slashes (As I do),  I think an error message would be appropiate, whereas having to kill processes manually is too much.
Now: This string works perfectly:
`CREATE SERVER jupt FOREIGN DATA WRAPPER oracle_fdw OPTIONS(dbserver 'server:port/dbname');
`
And oracle_diag(servername) returns within 5 seconds:
`oracle_fdw 1.5.0, PostgreSQL 9.5.0, Oracle client 11.2.0.4.0, Oracle server 11.2.0.3.0`

Thank you again for advice.

**Comment by laurenz** [comment]
I tried with a server name with backslashes like you did and got the same result. Oracle connects to the LDAP Server and then hangs in an endless loop.
Congratulations, you have discovered yet another Oracle bug.
It seems to be an unknown one; at least I could not find it in the bug database.
There is nothing I can do about that in oracle_fdw. I don't feel inspired to open a service request for that, as it is easily worked around by entering a proper connection string.

Since you observe that LDAP connections are established, the Oracle client must pick up an `ldap.ora` file with the appropriate definitions somewhere. The search order for that is `%ORACLE_HOME%\ldap\admin`, then `%ORACLE_HOME%\network\admin`, then `%TNS_ADMIN%`.

Using `OPTIONS (dbserver 'JUPITEST')` should work fine if it works with sqlplus.
Are you sure that you can get no trace file if you modify `C:\TEMP\TNS\sqlnet.ora` like I describe above and restart PostgreSQL? That would tell us why you cannot resolve the database. It seems suspicious that the failing connection attempt takes 30 seconds.

**Comment by mbwiese** [comment]
Yes, it is easy to do it right, once aware. But still a nasty error to identify. You might be able to just remove any leading backslashes (which will always be wrong), so that a normal error would be sent back to the user. 
 
Regarding the ORACLE_HOME:  I do not have an ORACLE_HOME environment variable on that server. Nevertheless,  the thread running wild actually had ORACLE_HOME defined in its environment, as far as I remember. I wonder if that could stem from a PostGreSQL configuration, but do not have time to dig into it anymore.
Yes, I am sure that I get no trace from PostGreSQL, but always from SQLPlus, as long as C:\TEMP\TNS is modified according to your advice, and PostGreSQL restarted several times. Probably PostGreSQL never attempts to use TNS names.

**Comment by laurenz** [comment]
It is not PostgreSQL that uses `tnsnames.ora`, but the Oracle client shared library that is used by both sqlplus and oracle_fdw. So there *must* be some difference in the configuration. Does the PostgreSQL server have permissions to change into the directory and read the file?

**Comment by mbwiese** [comment]
How could I check that ? PostGreSQL login role 'postgres' is not a WIndows user.

**Comment by laurenz** [comment]
For example process monitor. You could start the PostgreSQL session, then start Process Monitor and filter away everything but the process ID of the PostgreSQL backend. If you start the problematic query then, there shouldn't be too many events recorded, and you can see what it does and where it fails.
