### ISSUE TITLE
oracle_fdw's version

### ISSUE THREAD

**Issue by Jaime2ndQuadrant** [laurenz/oracle_fdw#140]
while we were trying oracle_fdw, we noted that you haven't updated the default_version in oracle_fdw.control which still shows v1.1.

And when installing it keeps saying v1.1 in pg_extension. why's that?

**Comment by laurenz** [comment]
This is covered in the README:

> Note that the extension version as shown by the psql command `\x` or the
> system catalog `pg_available_extensions` is *not* the installed version
> of oracle_fdw.  To get the oracle_fdw version, use the function `oracle_diag`.

1.1 is the version of the extension, not the version of oracle_fdw.

The extension version only changes if the API changes, e.g. when a new function is introduced.

I know that this discrepancy is unfortunate, and that question gets asked regularly, but if I were to keep the two versions in sync, installing an update would require a `ALTER EXTENSION oracle_fdw UPDATE`, while in reality it is enough to just replace the binary.
