### ISSUE TITLE
pre-exec statement

### ISSUE THREAD

**Issue by legrandlegrand** [laurenz/oracle_fdw#141]
Hello,
and first of all I hope you and the projet an happy new year ;o)

Then I would like to store Oracle DDL into a PostgreSQL database to track the differences between applications releases and differences between environments.

So I was thinking defininng a FOREIGN TABLE with a sub query using **DBMS_METADATA.GET_DDL** 
Something like

    select owner, object_type, object_name, status,
           DBMS_METADATA.GET_DDL(replace(object_type,' ','_'),object_name,owner) ddl
      from dba_objects
      where object_type not like '%PARTITION%'
      and object_type not in ('LOB','PACKAGE BODY','TYPE BODY')
      and generated='N'

but I also would like to use

    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SEGMENT_ATTRIBUTES',false);

and others

Is there a way to execute such statement (or any 'alter session' statement) as a pre-execution step for a Foreign Table ?

Nb: Access to Oracle database is READ ONLY

Thanks in advance
Regards
PAscal

**Comment by laurenz** [comment]
The only idea I have is to use a pipelined function in Oracle like this:

    CREATE OR REPLACE TYPE objdef AS object (
       owner VARCHAR2(128),
       object_type VARCHAR2(23),
       object_name VARCHAR2(128),
       status VARCHAR2(7),
       ddl VARCHAR2(4000)
    )
    /

    CREATE OR REPLACE TYPE objdefs AS TABLE OF objdef
    /

    CREATE OR REPLACE FUNCTION getobjdefs RETURN objdefs PIPELINED IS
       r objdef := objdef(NULL, NULL, NULL, NULL, NULL);
    BEGIN
       DBMS_METADATA.SET_TRANSFORM_PARAM(
          DBMS_METADATA.SESSION_TRANSFORM,
          'SEGMENT_ATTRIBUTES',
          FALSE
       );

       FOR c IN (SELECT owner, object_type, object_name, status,
                       DBMS_METADATA.GET_DDL(
                          replace(object_type,' ','_'),
                          object_name,
                          owner
                       ) ddl
                FROM dba_objects
                WHERE object_type NOT LIKE '%PARTITION%'
                  AND object_type NOT IN ('LOB', 'PACKAGE BODY', 'TYPE BODY')
                  AND generated='N')
       LOOP
          r.owner := c.owner;
          r.object_type := c.object_type;
          r.object_name := c.object_name;
          r.status := c.status;
          r.ddl := c.ddl;

          PIPE ROW (r);
       END LOOP;
       RETURN;
    END;
    /

Then you can define the foreign table like this:

    CREATE FOREIGN TABLE getobjdefs(
       owner text,
       object_type text,
       object_name text,
       status text,
       ddl text
    ) SERVER oracle OPTIONS (
       table '(SELECT * FROM (TABLE(getobjdefs())))'
    );

**Comment by legrandlegrand** [comment]
Thanks,

in the same time I have removed the equivalent text part using
**regexp_replace(ddl,'STORAGE\(.*?\).','')**
