### ISSUE TITLE
oracle_utils.c:22:17: error: oci.h: No such file or directory

### ISSUE THREAD

**Issue by i-techsolutions** [laurenz/oracle_fdw#142]
Hi,

I am getting this issue on fresh installation of ORACLE FDW.

I am able to access my oracle client from the user access.

Here is my bashrc & bash_profile contents

```
PATH=$PATH:$HOME/bin:/usr/lib/oracle/11.2/client64:/usr/lib/oracle/11.2/client64/bin:/opt/PostgreSQL/9.3:/opt/PostgreSQL/9.3/bin
export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib
  export TNS_ADMIN=/usr/lib/oracle/11.2/client64
  export ORACLE_HOME=/usr/lib/oracle/11.2/client64


```

**Comment by laurenz** [comment]
I guess you are trying to build oracle_fdw, right?

Are you building against an Oracle server, an Oracle client installed with Universal Installer or an Instant Client?
Do you have the Oracle header files installed?
Where is `oci.h` in your installation?

**Comment by i-techsolutions** [comment]
I have installed instant client using steps mention on  http://www.xenialab.it/meo/web/white/oracle/HT_IC_RH.htm

my sqlplus is working fine.

I am not aware about the header files.
Can you please help that how I can install the same.

**Comment by laurenz** [comment]
You forgot to install the &ldquo;SDK&rdquo; RPM.

**Comment by i-techsolutions** [comment]
Can you tell me the steps or rpm name

**Comment by laurenz** [comment]
There are no steps - all you need to do is get the RPM with &ldquo;sdk&rdquo; in its name from Oracle (it is available for download on the Instant Client page like the other RPMs).
You install it using `rpm -U`.

**Comment by i-techsolutions** [comment]
Hi,
make & make install works fine.

Now I am getting following error.

```
postgres=# CREATE EXTENSION oracle_fdw;
ERROR:  could not load library "/opt/PostgreSQL/9.3/lib/postgresql/oracle_fdw.so": libclntsh.so.11.1: cannot open shared object file: No such file or directory

```

**Comment by laurenz** [comment]
You didn't set `LD_LIBRARY_PATH` properly in the PostgreSQL server's environment. Did you restart the PostgreSQL server? Look at `/proc/12345/environ` to see the postmaster's environment (replace &ldquo;1234&rdquo; with the postmaster's PID).

**Comment by i-techsolutions** [comment]
I have not restarted it yet. Let me do it. Will get back to you after that.

**Comment by i-techsolutions** [comment]
Hi,

everything worked fine.

Now I am getting following error while fetching details from table.

create table code 

```

CREATE FOREIGN TABLE drcp
(
DD_CODE varchar(100),
DD_DEALER varchar(100),
DD_OL numeric,
DD_DRCP numeric,
DD_SYSDT date
) SERVER oradb OPTIONS (schema 'mis', table 'DRCP');
```



When I make select statement it gives following error.

```
postgres=# select count(*) from drcp;
ERROR:  Oracle table "mis"."DRCP" for foreign table "drcp" does not exist or does not allow read access
DETAIL:  ORA-00942: table or view does not exist
HINT:  Oracle table names are case sensitive (normally all uppercase).

```


Where as I can make select statement from sqlplus and I am getting response

**Comment by laurenz** [comment]
Like the documentation says, uppercase the schema name.

**Comment by i-techsolutions** [comment]
Hi,

I tried with both upper and lower but got the same response.

**Comment by laurenz** [comment]
Well, then either the table `MIS.DRCP` does not exist, or the user has no privileges to select from it.

**Comment by i-techsolutions** [comment]
Using same user on sqlplus I am able to fetch the data

**Comment by laurenz** [comment]
In PostgreSQL, run

   EXPLAIN SELECT * FROM drcp;

You'll get the statement that is executed in Oracle.

Copy and paste that to an sqlplus session *using the same database user*.

**Comment by i-techsolutions** [comment]
Please find response of EXPLAIN

EXPLAIN SELECT * FROM drcp;
ERROR:  Oracle table "MIS"."DRCP" for foreign table "drcp" does not exist or does not allow read access
DETAIL:  ORA-00942: table or view does not exist
HINT:  Oracle table names are case sensitive (normally all uppercase).

**Comment by laurenz** [comment]
Ok, try `SELECT * FROM "MIS"."DRCP"` in Oracle (with the same Oracle user).

**Comment by i-techsolutions** [comment]
It gives me error of table or view does not exists when I tried with

SELECT * FROM "MIS"."DRCP" & SELECT * FROM MIS.DRCP


but it worked when I tried with

SELECT * FROM DRCP

**Comment by laurenz** [comment]
Well, then maybe the schema name is wrong? But if it works without specifying a schema (it might be a global synonym), just don't use a schema:

    ALTER FOREIGN TABLE drcp OPTIONS (DROP schema);

**Comment by i-techsolutions** [comment]
Thanks laurenz for your help.

It works now after dropping the schema.

**Comment by shannithila** [comment]
I am facing same issue
