### ISSUE TITLE
Why always ERROR ORA-08177 

### ISSUE THREAD

**Issue by sangli00** [laurenz/oracle_fdw#143]
hi @laurenz 
How to avoid this ERROR.

I delete and insert  oracle_fdw on transaction.
always  ORA-08177  I don't how to fix this problem.

Thanks.

**Comment by laurenz** [comment]
Can you provide a reproducible test case?

- Table definitions in PostgreSQL and Oracle.
- Oracle `INSERT` statements to populate the table.
- A sequence of statements that causes the error.

**Comment by sangli00** [comment]
yes,Insert used some sequence.
SQL like:
delete from oracle_fdw_tables;

insert into oracle_fdw_tables
select nextval('seq1'),col1,col2 from pg_tables1;

insert into oracle_fdw_tables
select nextval('seq1'),col1,col2 from pg_tables2;
...


postgres tables 4million more  rows

**Comment by sangli00** [comment]
if i insert 100000 rows is success 
I don't what happen.

**Comment by laurenz** [comment]
I don't understand.
Can you describe how exactly to get that error?

You didn't show a `CREATE TABLE` or `CREATE FOREIGN TABLE` statement.

**Comment by sangli00** [comment]
foreign table like this:
create foreign table my_table(
id    bigint OPTIONS (key 'true')  NOT NULL,
cols....

)
service oradb OPTIONS (schema 'test', table 'ORATAB');


create or replace function func_test()
returns void as $$
declare

begin

delete from my_table;

insert into my_table
select nextval('my_sequence'),cols... from table1 ;

insert into my_table
select nextval('my_sequence'),cols... from table2;


end
$$
language  plpgsql;

**Comment by laurenz** [comment]
That works for me.
Here is what I did:

In Oracle:

    CREATE TABLE oratab (
       id NUMBER(10) CONSTRAINT oratab_pkey PRIMARY KEY,
       val VARCHAR2(15 CHAR) CONSTRAINT oratab_val_null NOT NULL
    ) SEGMENT CREATION IMMEDIATE;

In PostgreSQL:

    CREATE FOREIGN TABLE my_table (
       id bigint OPTIONS (key 'true') NOT NULL,
       val varchar(15) NOT NULL
    ) SERVER oracle OPTIONS (schema 'LAURENZ', table 'ORATAB');

    CREATE TABLE table1 (val text NOT NULL);
    CREATE TABLE table2 (val text NOT NULL);
    INSERT INTO table1 VALUES ('one'), ('two');
    INSERT INTO table2 VALUES ('three'), ('four'), ('five');

    CREATE OR REPLACE FUNCTION func_test() RETURNS void AS
    $$DECLARE
    BEGIN
       DELETE FROM my_table;

       INSERT INTO my_table
          SELECT nextval('my_sequence'), val FROM table1 ;

       INSERT INTO my_table
          SELECT nextval('my_sequence'), val FROM table2;
    END;$$
    LANGUAGE plpgsql;

Then I test it:

    SELECT func_test();
    SELECT func_test();
    SELECT * FROM my_table;
    ┌────┬───────┐
    │ id │  val  │
    ├────┼───────┤
    │  6 │ one   │
    │  7 │ two   │
    │  8 │ three │
    │  9 │ four  │
    │ 10 │ five  │
    └────┴───────┘
    (5 rows)

So I cannot reproduce your problem with the information you gave me.

I won't be able to help you unless you can help me to reproduce your problem.

**Comment by sangli00** [comment]
I recreate  oracle table this  problem is fixed

**Comment by laurenz** [comment]
Thanks for keeping me updated.
Now that is plain weird &ndash; but we'll probably never find out what the problem was.

**Comment by sangli00** [comment]
I used PG_AGENT extension  timing sync data .
PG <---> ORACLE

**Comment by laurenz** [comment]
I have no idea what that is &ndash; could you point me to a web page?

**Comment by sangli00** [comment]
I mean,I used oracle_fdw & pg_agent get together work in my system.
diff Database oracle,SQL server ,DB2 ,MYSQL.... I need this data ,I used oracle_fdw sync data to Postgres. This data used procedure join this table and result write ORACLE Database. 

sometimes,is error ora-08173,I think maybe table is lock.

**Comment by laurenz** [comment]
No; unless there is an Oracle bug, it means that you try to modify data in a `SERIALIZABLE` transaction that another database session has modified since your transaction started.

**Comment by laurenz** [comment]
Perhaps this is the same problem as in #200.
