### ISSUE TITLE
DETAIL:  ORA-01858: a non-numeric character was found where a numeric was expected

### ISSUE THREAD

**Issue by i-techsolutions** [laurenz/oracle_fdw#144]
Hi,

I am facing this issue while fetching the data from one of my table where all the data types are characters.

Here is create statement

    create foreign table vw_range_f (
       RTR_CLASS  VARCHAR(10) NOT NULL,
       YYYYMM     VARCHAR(10),
       SYSDT      VARCHAR(9),
       CUST       VARCHAR(20),
       MK2        VARCHAR(9),
       RS         VARCHAR(9),
       SCORE      VARCHAR(10)
    ) SERVER oradb OPTIONS (table 'VW_RANGE');

When I make command 

    select * from vw_range_f

it throws following error

    ERROR:  error executing query: OCIStmtExecute failed to execute remote query
    DETAIL:  ORA-01858: a non-numeric character was found where a numeric was expected

It runs perfectly on sqlplus

**Comment by laurenz** [comment]
Can you show me the table definition of the Oracle table?

What is the result if you run

    EXPLAIN SELECT * FROM vw_range_f;

**Comment by i-techsolutions** [comment]
Response of Explain

```
                                                                                    QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Foreign Scan on vw_range_selling_fr  (cost=10000.00..20000.00 rows=1000 width=280)
   Oracle query: SELECT /*87cc79df508e39d9f6e57e88ce051b82*/ "RTR_CLASS", "YYYYMM", "SYSDT", "CUST", "MK2", "RS", "SCORE" FROM "VW_RANGE"



Oracle View Defination

```
   Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 RTR_CLASS                           NOT NULL VARCHAR2(10)
 YYYYMM                                         VARCHAR2(10)
SYSDT                                           VARCHAR2(9)
 CUST                                        VARCHAR2(20)
 MK2                                             VARCHAR2(9)
 RS                                      VARCHAR2(9)
 SCORE                                              VARCHAR2(10)

```

```

**Comment by laurenz** [comment]
You're saying that the following query runs ok when run with sqlplus as the same Oracle database user as PostgreSQL:

    SELECT "RTR_CLASS", "YYYYMM", "SYSDT", "CUST", "MK2", "RS", "SCORE" FROM "VW_RANGE";

That would be strange indeed.
Can you show me the view definition of the Oracle view?

**Comment by i-techsolutions** [comment]
Hi laurenze,
the query works on SQLPLUS absolutely fine.

I have already shared oracle view defination

 Name                            Null?    Type
 ------------------- ------------ -------- ----------------------------
 RTR_CLASS                       NOT NULL VARCHAR2(10)
 YYYYMM                                   VARCHAR2(10)
 SYSDT                                    VARCHAR2(9)
 CUST                                     VARCHAR2(20)
 MK2                                      VARCHAR2(9)
 RS                                       VARCHAR2(9)
 SCORE                                    VARCHAR2(10)

**Comment by laurenz** [comment]
I don't mean the fields of the view, but the `CREATE VIEW` statement that was used to create it. Plus the column definitions of the tables involved in the view.

I suspect that the problem has to do with that, i.e., incorrect data are found during the execution of the view's SQL statement.

Since it works when you start it from sqlplus, it is very likely that the problem is connected to different session parameters.

Try the following from sqlplus:

    ALTER SESSION SET NLS_DATE_LANGUAGE=AMERICAN;
    ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS BC';
    ALTER SESSION SET 
    ALTER SESSION SET 
    ALTER SESSION SET

**Comment by laurenz** [comment]
I'll close the issue for inactivity, assuming that my comment helped.
Don't hesitate to reopen it if you need more help.
