### ISSUE TITLE
server crash with NULL subquery result in Where condition

### ISSUE THREAD

**Issue by legrandlegrand** [laurenz/oracle_fdw#145]
Hello 

I get a server crash with

```
insert into dbcfg.snap select * from xe.snap
where snap_id > (select max(snap_id) from  dbcfg.snap)
```

**org.postgresql.util.PSQLException: This connection has been closed.**

but works fine when subquery
```
(select max(snap_id) from  dbcfg.snap)
```
is not null

context to reproduce
```
select oracle_diag('xe');
oracle_fdw 1.4.0, PostgreSQL 9.5.1, Oracle client 11.2.0.2.0, Oracle server 11.2.0.2.0

CREATE FOREIGN TABLE xe.snap (
snap_id numeric,
begin_interval_time timestamp(0),
end_interval_time timestamp(0)
) SERVER xe
OPTIONS (table '(
select snap_id,begin_interval_time,end_interval_time from dba_hist_snapshot
)');

CREATE TABLE dbcfg.snap (
snap_id numeric,
begin_interval_time timestamp(0),
end_interval_time timestamp(0));
```

**Comment by laurenz** [comment]
I tried to reproduce it, but it worked for me.

I am using [current HEAD][1] of oracle_fdw; could you try with that or at least with version 1.5.0? Not that I remember any fixes for problems like that, but you never know.

Can you [get a stack trace][2] from the crash?

[1]: https://github.com/laurenz/oracle_fdw/archive/master.zip
[2]: https://wiki.postgresql.org/wiki/Generating_a_stack_trace_of_a_PostgreSQL_backend

**Comment by legrandlegrand** [comment]
The problem is still there after upgrading into oracle_fdw version 1.5.
Sorry, I'm can not install windbg nor Microsoft Visual Studio on my Windows 7 (x64) computer.

But found the following workarround:
``
insert into dbcfg.snap select * from xe.snap
where snap_id > (select **coalesce(max(snap_id),0)** from  dbcfg.snap)
``

**Comment by laurenz** [comment]
Good workaround.

I just could reproduce the problem, but only on Windows :^(

I'll see what I can do.

**Comment by laurenz** [comment]
Fixed binary sent by e-mail, please verify if that fixes the issue.

**Comment by laurenz** [comment]
34eec524bb31df781d569eed0eb8b0aab5f1f7f2 introduced a stupid bug, but aca12d000991cfaaee8e928448cb50747df1bc32 should have fixed it.
