### ISSUE TITLE
ORA-01861: literal does not match format string

### ISSUE THREAD

**Issue by JoseChavez** [laurenz/oracle_fdw#146]
Hi,

I get this error in the next test case:

In oracle

    CREATE TABLE "TABLE1" (
       "COLUMN1" NUMBER(4) NOT NULL,
       "COLUMN2" NUMBER(1) NOT NULL,
       "COLUMN3" NUMBER(4) NOT NULL,
       "COLUMN4" NUMBER(6) NOT NULL,
       "COLUMN5" NUMBER(4) NOT NULL
    ) LOGGING NOCOMPRESS NOCACHE;

    CREATE TABLE "TABLE2" (
       "COLUMN1" NUMBER(4) NOT NULL,
       "COLUMN2" NUMBER(1) NOT NULL,
       "COLUMN3" NUMBER(4) NOT NULL,
       "COLUMN4" NUMBER(6) NOT NULL,
       "COLUMN5" NUMBER(4) NOT NULL,
       "COLUMN6" NUMBER(1) NULL
    ) LOGGING NOCOMPRESS NOCACHE;

    CREATE TABLE "TABLE3" (
       "MONTH" NUMBER(2) NULL ,
       "YEAR" NUMBER(4) NULL ,
       "DATE3" DATE NULL
    ) LOGGING NOCOMPRESS NOCACHE;

    CREATE OR REPLACE TRIGGER TBI_TABLE1 BEFORE INSERT
        ON TABLE1
    REFERENCING NEW AS nvo
    FOR EACH ROW
    begin
        UPDATE TABLE2
            SET COLUMN6 = 1
            where COLUMN2 = :nvo.COLUMN2 and COLUMN3 = :nvo.COLUMN3
               and COLUMN1 = :nvo.COLUMN1 and COLUMN4 = :nvo.COLUMN4
               and COLUMN5 = :nvo.COLUMN5;
    END;
    /

    create or replace trigger TBU_TABLE2 before update on TABLE2
    referencing new as nvo
                old as vjo
    for each row
    declare
      v_date3    date;
      v_date_month  date;
      v_date_month_proc date;
    Begin
      ------------- THIS IS THE CONFLICT QUERY-----------------------------------
      select DATE3 , trunc(DATE3,'mm'), TRUNC(TO_DATE('01/'||MONTH||'/'||YEAR), 'MM')
      into v_date3 , v_date_month, v_date_month_proc
      from TABLE3;
      ------------------------------------------------------------------------------

      v_date_month_proc := to_date(v_date_month_proc, 'DD/MM/YYYY');
    end;
    /

    INSERT INTO "TABLE2" VALUES (1234, 1, 1234, 123456, 1234, 6);
    INSERT INTO "TABLE3" VALUES (11, 2016, TO_DATE('20161205000000', 'YYYYMMDDHH24MISS'));

In postgres

    CREATE FOREIGN TABLE TABLE1 (
       "COLUMN1" int4 NOT NULL,
       "COLUMN2" int4 NOT NULL,
       "COLUMN3" int4 NOT NULL,
       "COLUMN4" int4 NOT NULL,
       "COLUMN5" int4 NOT NULL
    ) SERVER oradb OPTIONS(schema 'TEST', table 'TABLE1');

    CREATE FOREIGN TABLE TABLE2 (
       "COLUMN1" int4 NOT NULL,
       "COLUMN2" int4 NOT NULL,
       "COLUMN3" int4 NOT NULL,
       "COLUMN4" int4 NOT NULL,
       "COLUMN5" int4 NOT NULL,
       "COLUMN6" int4 NULL
    ) SERVER oradb OPTIONS(schema 'TEST', table 'TABLE2');

    CREATE FOREIGN TABLE TABLE3 (
       "MONTH" NUMERIC(2) NULL ,
       "YEAR" NUMERIC(4) NULL ,
       "DATE3" DATE NULL
    ) SERVER oradb OPTIONS(schema 'TEST', table 'TABLE3');

And now try this query from postgres

    INSERT INTO TABLE1 VALUES (1234, 1, 1234, 123456, 1234);

**Comment by laurenz** [comment]
Thank you for the complete test case!
I wish that everybody reported problems as thoroughly.

The problem with the failing query is that it assumes that the parameter `NLS_DATE_FORMAT` is set to `DD/MM/YYYY`, but oracle_fdw sets it to `YYYY-MM-DD HH24:MI:SS BC` so that date values that come from Oracle are in a format that PostgreSQL understands.

You should fix your query not to make such assumptions. Use

    TO_DATE('01/'||MONTH||'/'||YEAR, 'DD/MM/YYYY')

instead of

    TO_DATE('01/'||MONTH||'/'||YEAR)

**Comment by JoseChavez** [comment]
That is. Now every it's Ok. 

Thank you Laurenz

**Comment by shatestest** [comment]
I am working with spark which uses ojdbc6.jar , which is also resulting same error....  how to debug it 
 ?  https://stackoverflow.com/questions/56020103/how-to-pass-date-timestamp-as-lowerbound-upperbound-in-spark-sql-2-4-1v
