### ISSUE TITLE
Datestyle automatically changes after an insert within a session

### ISSUE THREAD

**Issue by JoseChavez** [laurenz/oracle_fdw#147]
Hi Laurenz,

#146 
After resolving the issue quoted, the following occurs:

- Execute 'SHOW DATESTYLE' from django

Return (u'ISO, DMY',)

- Save model (And the triggers shown in #146 are executed)

- Execute 'SHOW DATESTYLE' from django

Return (u'SQL, DMY',)

And query's not working anymore

Why might this happen?

**Comment by chrullrich** [comment]
Neither oracle_fdw nor Django change that option anywhere. psycopg2 does, but only *to* ISO, not away from it. Is it possible that you have added something to Django that changes the date style? A third-party date/time field, perhaps?

If you have superuser rights on your PostgreSQL, you can `set session log_statement='all'` (from Django) to log all queries, and try to figure out from context where the change is coming from.

**Comment by JoseChavez** [comment]
Hi chrullrich,

Thanks for answering.

The strange thing is that if the trigger is not executed everything ends well and nothing strange happens. But not only that. We have another oracle server (development, in theory with the same production configuration). If the foreign tables are from this server everything works fine (even with triggers), but on the production server it happens as discussed above.

**Comment by JoseChavez** [comment]
Excuse me guys. My fault. Within a trigger the datestyle was set since oracle uses another date format. This issue has been fixed.

Thank you anyway
