### ISSUE TITLE
ORA-03135 connection lost contact

### ISSUE THREAD

**Issue by swvanlinge** [laurenz/oracle_fdw#148]
Every so often trying to run SELECT statements against an Oracle 11gR2 instance (11.2.0.4.0) using PostgreSQL 9.5, I get errors:

    ERROR:  error fetching result: OCIStmtFetch2 failed to fetch next result row
    DETAIL:  ORA-03135: connection lost contact

These happen while querying large amounts of data, so it may be related to some sort of timeout, but it ends up losing me large amounts of time/work everytime it happens.  Are there ways to reduce the possibility of this happening?  How can I search for the cause?

**Comment by laurenz** [comment]
This error message means that the Oracle client unexpectedly lost the network connection to the Oracle server while waiting for a query result.

This points towards a network problem.
Could there be a firewall that randomly decides to terminate TCP connections after a certain time?

**Comment by swvanlinge** [comment]
There could be.  I'll ask our sysadmins to investigate.  Thank you for the suggestion!

In the meantime, for anyone else having the same issue, I have broken up the work into batches by looping over queries like this to chunk it up into pieces (example from http://engineering.tilt.com/7-postgresql-data-migration-hacks/):

DECLARE batched_count INTEGER = 1;
BEGIN
    WITH selected_users AS (
        SELECT id
        FROM users
        WHERE role = 'moderator'
        AND registration_date < CURRENT_DATE - INTERVAL '4' YEAR
        LIMIT 1000
        FOR UPDATE NOWAIT
    ),
    updated_users AS (
        UPDATE users
        SET role = 'admin'
        FROM selected_users
        WHERE selected_users.id = users.id
        RETURNING users.id
    ) SELECT COUNT(1) INTO batched_count FROM updated_users;
END$$;

I have the loop at the batch/shell level since PostgreSQL doesn't allow me to commit mid-loop.
