### ISSUE TITLE
How to fix ORA-08177: can't serialize access for this transaction

### ISSUE THREAD

**Issue by sangli00** [laurenz/oracle_fdw#149]
I don't what happen.

1 ``` delete from oracle_fdw_t1 ;```
2 ```insert into oracle_fdw_t2;```
3 ```insert into oracle_fdw_t1;```

Table is very big,
![111](https://cloud.githubusercontent.com/assets/3765918/23394964/eb77122e-fdc6-11e6-927a-e13dfc866227.png)

![2222](https://cloud.githubusercontent.com/assets/3765918/23395081/b463fb3e-fdc7-11e6-99bb-c12d1e3af303.png)

**Comment by sangli00** [comment]
This is  error log:
![333](https://cloud.githubusercontent.com/assets/3765918/23395341/0182d7c2-fdc9-11e6-8e27-4f4bd0b92f96.png)

**Comment by laurenz** [comment]
On your images I see a lot of errors and a lot of different statements affecting different tables, so it is hard for me to understand, let alone reproduce, what is going on.

Can you tell me the output of

    SELECT oracle_diag('your_foreign_server');

Can you give me a `CREATE TABLE` statement for the Oracle table, a `CREATE FOREIGN TABLE` statement for the PostgreSQL foreign table, and an SQL statement that causes the error?

Are there any concurrent transactions on the Oracle database that modify data in the same table? That would explain the serialization errors. It is normal for such errors to be thrown if data are modified concurrently.

**Comment by sangli00** [comment]
@laurenz 
oracle table:
```
create table tb_cert_update
(cert_no varchar2(100),
 type number,
 update_time timestamp);
 
 ALTER TABLE tb_cert_update ADD PRIMARY KEY (cert_no);
```

oracle_fdw table
```
create Foreign table cloudbridge_tb_cert_update
 ( 
 cert_no text options(key 'true'),
 type numeric,
 update_time timestamp
)
Server oradb_cloudbridge
Options (schema 'CLOUDBRIDGE', table 'TB_CERT_UPDATE');
```

**Comment by sangli00** [comment]
```insert into cloudbridge_tb_cert_update  
select distinct cert_no ,1, now() from db2_rjwods_cnc_sapsr3db_du_ccc_zsxx where ZERSDA>max_time and ZERSDA is not null;
```
table ```db2_rjwods_cnc_sapsr3db_du_ccc_zsxx``` is odbc_fdw  connect to db2 database .

**Comment by sangli00** [comment]
![333](https://cloud.githubusercontent.com/assets/3765918/23443226/46d1944a-fe68-11e6-953a-a97a467b76c7.png)

**Comment by laurenz** [comment]
But that `SELECT` statement does not access the Oracle foreign table at all!
Is there a mistake?

I see that you are using oracle_fdw version 1.3.0.
I don't remember fixing any problems that look like they are related to what you see, but it might be a good idea to use 1.5.0 and see if that improves matters.

**Comment by laurenz** [comment]
I cluse this because of inactivity &ndash; please reopen it if you have new information.

**Comment by laurenz** [comment]
Perhaps this is the same problem as #200.

**Comment by daconglee** [comment]
ABP zero
Configuration.UnitOfWork.IsolationLevel = System.Transactions.IsolationLevel.ReadCommitted;//ORA-08177

**Comment by laurenz** [comment]
Huh?
If that is supposed to be a comment on this issue, please explain.
If you have a problem with oracle_fdw, please open a new issue with a somewhat more extensive description.
