### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by onemojofilter** [laurenz/oracle_fdw#152]
Hi: I'm running postgres 9.4 and I've installed Oracle instant client 11.1 on Redhat 6.7 (Santiago)

I'm getting these errors and I'm not certain what component is missing other than these 
oracle_fdw.c:22:34: error: catalog/pg_collation.h: No such file or directory
oracle_fdw.c:25:38: error: catalog/pg_foreign_table.h: No such file or directory
oracle_fdw.c:33:28: error: foreign/fdwapi.h: No such file or directory

...followed by many errors that I think that are related to these initial ones...

Any help would be appreciated...

**Comment by laurenz** [comment]
What is the directory you get with

    pg_config --includedir-server

Does it contain the header files you quote above?

If not, then something seems to be wrong with your PostgreSQL installation.

**Comment by onemojofilter** [comment]
This returns /usr/pgsql-9.4/include/server.

The directory /usr/pgsql-9.4 exists on my server but the sub-directories include/server do not...

I have bin, doc, lib and share and that's it.

Sounds like I need to install the postgresql-devel package?

**Comment by laurenz** [comment]
Exactly.
What is strange is that you have `pg_config` installed, but not the header files.
Normally `pg_config` is in the development package, so I didn't even suspect that.

From the man page of `pg_config`:

> The pg_config utility prints configuration parameters of the currently installed version of PostgreSQL. It is
> intended, for example, to be used by software packages that want to interface to PostgreSQL to facilitate
> finding the required header files and libraries.

**Comment by onemojofilter** [comment]
I figured it out, I think. I successfully installed the devel package and set it up. Thanks for your help!

**Comment by onemojofilter** [comment]
Now I have a new problem... Even though I have Oracle Instant Client installed and all the appropriate libraries present
export ORACLE_HOME=/usr/lib/oracle/11.1/client64
export LD_LIBRARY_PATH=$ORACLE_HOME/lib

I log onto postgres (as postgres) and try the following:
CREATE EXTENSION oracle_fdw;

I get the following error:
ERROR:  could not load library "/usr/pgsql-9.4/lib/oracle_fdw.so": libclntsh.so.11.1: cannot open shared object file: No such file or directory

**Comment by laurenz** [comment]
That means that `LD_LIBRARY_PATH` is not set for the PostgreSQL server process.

Add `/usr/lib/oracle/11.1/client64/lib` to `/etc/ld.so.conf` and run `ldconfig` as user `root`.

Then restart the PostgreSQL server.

**Comment by onemojofilter** [comment]
I'll do that, thanks!!

**Comment by onemojofilter** [comment]
Your advise solved my problem, thank you! All I had to do was install one more missing library (libaio.so.1) via yum ( yum -y install libaio-devel) and I was off to the races...
