### ISSUE TITLE
FEHLER:  ungültige Byte-Sequenz für Kodierung »UTF8«: 0xdf 0x74

### ISSUE THREAD

**Issue by mpatzwah** [laurenz/oracle_fdw#155]
Hi Laurenz,
i have a similar Problem (Oracle 12.2 (Yes, very new :-) ) on Windows with Postgres 9.6
The Database is a new fresh Default Installation without any garbage :-)
I took the default Tables that oracle used the last 30 years. Long times before Unicode was insight:-)

```
ps >SELECT oracle_diag('oradb122');
                                      oracle_diag
----------------------------------------------------------------------------------------
 oracle_fdw 1.5.0, PostgreSQL 9.6.2, Oracle client 12.2.0.1.0, Oracle server 12.2.0.1.0
(1 Zeile)

> ps >select * from dept;
> FEHLER:  ungültige Byte-Sequenz für Kodierung »UTF8«: 0xdf 0x74
> ps >SHOW server_encoding;
>  server_encoding
> -----------------
>  UTF8
> (1 Zeile)

```
This is the Table:

 ```
   DEPTNO DNAME          LOC          
---------- -------------- -------------
        10 ACCOUNTING     NEW YORK     
        20 RESEARCH       DALLAS       
        30 SALES          CHICAGO      
        40 OPERATIONS     BOSTON      

```
On Oracle:

```
SELECT value FROM nls_database_parameters WHERE parameter = 'NLS_CHARACTERSET';
AL32UTF8
```

What can i do? Is there any trace/log ?

Thanks
Marco

**Comment by laurenz** [comment]
0xDF74 is not valid UTF-8, so you must have some garbage in your Oracle database.
In ISO 8859-1 that byte sequence would be &ldquo;&szlig;t&rdquo;, so it might be incorrectly encoded German text from before the spelling reform.

Once you know which row and column contains the problematic bytes, you can verify that in Oracle with

    SELECT dump(colname, 16) FROM dept WHERE deptno = 42;

**Comment by mpatzwah** [comment]
select 1 from dept2  where deptno=10;
FEHLER:  ungültige Byte-Sequenz für Kodierung »UTF8«: 0xdf 0x74

**Comment by laurenz** [comment]
Really `SELECT 1`? What do you get for

    EXPLAIN select 1 from dept2 where deptno=10;

**Comment by mpatzwah** [comment]
ps >EXPLAIN select 1 from dept2 where deptno=10;
                          QUERY PLAN
--------------------------------------------------------------
 Foreign Scan on dept2  (cost=100.00..153.00 rows=17 width=4)
(1 Zeile)

**Comment by laurenz** [comment]
Sorry, I meant `EXPLAIN (VERBOSE) SELECT ...`.

**Comment by mpatzwah** [comment]
ps >EXPLAIN verbose select 1 from dept2 where deptno=10;
                             QUERY PLAN
---------------------------------------------------------------------
 Foreign Scan on public.dept2  (cost=100.00..153.00 rows=17 width=4)
   Output: 1
   Remote SQL: SELECT NULL FROM "SCOTT"."DEPT" WHERE ((deptno = 10))
(3 Zeilen)

**Comment by mpatzwah** [comment]
I have 25 years experiennce with Oracle but only two weeks with Potsgres, so mayby the error is somerwhere else .. i did:
CREATE EXTENSION postgres_fdw;

CREATE SERVER oradb122
FOREIGN DATA WRAPPER postgres_fdw
OPTIONS (host '127.0.0.1', port '1521', dbname 'o12c');
CREATE FOREIGN TABLE scott.dept2 (deptno integer,dname varchar(10), loc varchar(10)) ;

**Comment by laurenz** [comment]
I don't think that this query can cause that error message.
Also, that `EXPLAIN` doesn't look right; it should have `"DEPTNO" = 10.
Are there any triggers involved?

Please post the `CREATE TABLE` statement from Oracle and the `CREATE FOREIGN TABLE` statement in PostgreSQL.

If possible, provide an `INSERT` statement for Oracle that produces the problematic row.

**Comment by mpatzwah** [comment]
REM Oracle ################
create table pg_test (id int, text varchar2(10));
insert into pg_test values (1,'ABCDEFG');
commit;
###########################

## Pstgres ###
CREATE FOREIGN TABLE pg_test (
id int NOT NULL,
data varchar(10))
SERVER oradb122
OPTIONS (schema_name 'scott', table_name 'pg_test');

ps >select * from pg_test;
FEHLER:  ungültige Byte-Sequenz für Kodierung »UTF8«: 0xdf 0x74

**Comment by laurenz** [comment]
I don't think that these are the real statements you used.
I need real data (copy & paste) if I'm to help you.

    CREATE FOREIGN TABLE pg_test (
       id int NOT NULL,
       data varchar(10)
    ) SERVER oracle OPTIONS (table_name 'pg_test');

    ERROR:  invalid option "table_name"
    HINT:  Valid options in this context are: schema, table, plan_costs, max_long, readonly, sample_percent, prefetch

Even if I use `table` instead of `table_name`, you write `'pg_test'` in lower case, which would reference the Oracle table `"pg_test"` instead of the table `PG_TEST` you just created (remember that Oracle converts names to upper case, while PostgreSQL converts them to lower case).

Could it be that there is another table called `"pg_test"` in Oracle that causes the problem?

You make it hard to help you.

If I use `OPTIONS (table 'PG_TEST')`, your test works for me:

    test=> SELECT * FROM pg_test;
    ┌────┬─────────┐
    │ id │  data   │
    ├────┼─────────┤
    │  1 │ ABCDEFG │
    └────┴─────────┘
    (1 row)

I repeat my question: Is there a trigger on the foreign table?

Does the real query fail for all rows (`WHERE deptno = ...`) or only for a certain row?
Could you show me the *real* query and the *real* `EXPLAIN` output?

**Comment by mpatzwah** [comment]
Sorry, i don´t want to make it hard for you and thanks for you help !
It is a new fresh Database Installation, and it was a copy and paste example (i swear) 
No Triggers (by the way: In Oracle there is NO SELECT Trigger )

Now the same in Uppercase:

CREATE FOREIGN TABLE pg_test (
id int NOT NULL,
data varchar(10))
SERVER oradb122
OPTIONS (schema_name 'SCOTT', table_name 'PG_TEST');

ps >select * from pg_test;
FEHLER:  ungültige Byte-Sequenz für Kodierung »UTF8«: 0xdf 0x74

At the moment all Queries fail with the same error. Why is my examaple not real?

In Oracle:
desc pg_test
Name Null? Typ          
---- ----- ------------ 
ID         NUMBER(38)   
TEXT       VARCHAR2(10) 

select * from USER_DEPENDENCIES; => empty
select * from USER_triggers; => empty
select object_name,object_type from USER_objects;
DEPT	TABLE
PK_DEPT	INDEX
EMP	        TABLE
PK_EMP	INDEX
BONUS	TABLE
SALGRADE TABLE
PG_TEST	TABLE

Is there any way to debug the extension? The error does not make sense for me
Thanks
Marco

**Comment by mpatzwah** [comment]
oh could it be a problem of Oracle 12.2 ? Which Version did you use for your tests?

**Comment by laurenz** [comment]
Sorry about the triggers, that was nonsense by me (they are not used with `SELECT`).

You must be using a different foreign data wrapper.

The above `CREATE FOREIGN TABLE` statement won't work with oracle_fdw.

**Comment by mpatzwah** [comment]
ok, how can i check which Version i use ? Like this?
ps >SELECT name, default_version, installed_version, left( comment, 30) As comment
postgres-# FROM pg_available_extensions
postgres-# WHERE installed_version IS NOT NULL;
      name       | default_version | installed_version |            comment
-----------------+-----------------+-------------------+--------------------------------
 adminpack       | 1.0             | 1.0               | administrative functions for P
 dblink          | 1.2             | 1.2               | connect to other PostgreSQL da
 file_fdw        | 1.0             | 1.0               | foreign-data wrapper for flat
 oracle_fdw      | 1.1             | 1.1               | foreign data wrapper for Oracl
 orafce          | 3.3             | 3.3               | Functions and operators that e
 pgcrypto        | 1.3             | 1.3               | cryptographic functions
 pg_freespacemap | 1.1             | 1.1               | examine the free space map (FS
 plpgsql         | 1.0             | 1.0               | PL/pgSQL procedural language
 postgres_fdw    | 1.0             | 1.0               | foreign-data wrapper for remot

**Comment by laurenz** [comment]
That output looks good!

My problem is that the `CREATE FOREIGN TABLE` statement you quoted above cannot work with oracle_fdw.
Since you swore that you used copy & paste, the only explanation how you got this to work is that it is a different, modified version of oracle_fdw. My software wouldn't accept that statement.

Also, my oracle_fdw could not throw this error message with `SELECT 1 FROM ...`.

**Comment by mpatzwah** [comment]
So i did a complete new fresh Installation of Postgres 9.6.2-3 on Windows.
I used the included version of postgres_fdw (mayby this is not the right version?, or it is developed by somebody else ?)
But i get the same error
Do i have to install additional software from you gitgub Page ?

**Comment by laurenz** [comment]
This is getting more and more confusing.

Are you using postgres_fdw or oracle_fdw?
They have nothing to do with each other.

If you continue to feed me little bits of information, all of which contradict each other or themselves, I'll lose my patience.

Write up a complete test case, beginning with Oracle SQL to create and fill the table, and PostgreSQL statements from `CREATE SERVER` on, then a `SELECT` that exhibits the problem, plus an `EXPLAIN SELECT` for the same query.
Also, I need to know what the value of `NLS_LANG` was when you ran `sqlplus` and the results of:

    SHOW server_encoding;  -- in PostgreSQL

and

    SELECT value FROM nls_database_parameters WHERE parameter = 'NLS_CHARACTERSET';  -- in Oracle

Lastly, I want to know the output for

    SELECT dump(colname, 16) FROM oratable WHERE pkey = ...;

for a row and column where the problem occurs.

All of this copied from the actual screen, please.

I know it is painful to write all that down, but how am I supposed to help without that information?

**Comment by mpatzwah** [comment]
Thanks for patience but i´m giving up also. 
All Information you requested are still inside this Post (most of them in the first comment)
Thanks anyway, i will look for other resources to find the problem.

**Comment by laurenz** [comment]
Good luck!
