### ISSUE TITLE
OCIEnvCreate error revisited

### ISSUE THREAD

**Issue by MichaelDBA** [laurenz/oracle_fdw#158]
Ha, I think I googled all the OCIEnvCreate errors:
`ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
`
This happens when I try to import the HR schema from Oracle:
`IMPORT FOREIGN SCHEMA HR FROM SERVER oradb INTO hr OPTIONS (CASE 'lower');`
Here are my diagnostics:
```
SELECT oracle_diag();
                         oracle_diag
--------------------------------------------------------------
 oracle_fdw 1.5.0, PostgreSQL 9.6.2, Oracle client 11.2.0.2.0

SELECT pg_backend_pid();
--> 26083

In a second session in the shell:
ps -p26083 -oppid=
--> 18119

As root or PostgreSQL OS user:
cat /proc/18119/environ | xargs -0 -n 1 echo | sort
-->
LANG=en_US.UTF-8
PGDATA=/4TBHDD/var/lib/postgresql/9.6/main
PG_GRANDPARENT_PID=26799
PGLOCALEDIR=/usr/share/locale
PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj
PGSYSCONFDIR=/etc/postgresql-common
PWD=/home/postgres
```
Obviously, ORACLE_HOME and LIBRARY_PATH are not there.  But why?  I start and stop PG using postgres user and pg_ctlcluster (ubuntu 14.04 LTS, trusty), not the services.  As Postgres User, my env vars are:
```
HOME=/home/postgres
LANG=en_US.UTF-8
LD_LIBRARY_PATH=/usr/lib/postgresql/9.6/bin:/u01/app/oracle/product/11.2.0/xe/lib:/u01/app/oracle/product/11.2.0/xe
LOGNAME=postgres
NLS_LANG=AMERICAN_AMERICA.AL32UTF8
ORACLE_BASE=/u01/app/oracle
ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
ORACLE_SID=XE
PATH=/usr/sbin:/usr/lib/postgresql/9.6/bin:/u01/app/oracle/product/11.2.0/xe/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PGBASE=/var/lib/postgresql/9.6
PGCONF=/etc/postgresql/9.6/main
PGDATA=/4TBHDD/var/lib/postgresql/9.6/main
PGDATABASE=postgres
PGLIB=/usr/lib/postgresql/9.6/lib
PGPORT=5439
PGROOT=/usr/lib/postgresql/9.6
PGSYSCONFDIR=/etc/postgresql-common
PGUSER=postgres
PWD=/home/postgres
SHELL=/bin/bash
TNS_ADMIN=/u01/app/oracle/product/11.2.0/xe/network/admin
USER=postgres
VERSION=9.6
```
I can connect in same postgres shell to sqlplus successfully:
sqlplus dbman/mypassword@xe

What am I missing here?

**Comment by laurenz** [comment]
I don't know, everything looks fine to me.

Unfortunately this is not a meaningful error, it means "something went wrong while initializing Oracle" andd is usually a configuration problem.

What *I* would do as a last-ditch effort is run an SQL Net Trace.

In `sqlnet.ora` add the lines:

    # so that TRACE_DIRECTORY_CLIENT is respected
    DIAG_ADR_ENABLED = OFF
    TRACE_DIRECTORY_CLIENT = /directory/with/write/permission
    TRACE_LEVEL_CLIENT = SUPPORT

Then restart the server and try again. Hopefully a trace file will be written that can help.

Are there more than one Oracle installations in your `PATH` or `LD_LIBRARY_PATH`? I guess not.

**Comment by MichaelDBA** [comment]
Did the trace and nothing unusual shows up in the .trc file.  Interesting that it doesn't capture sql, just a bunch of session stuff.

Yes, no conflicts with other oracle installation.  But I did point to another oracle client installation, and got a different error instead:
```
example=# select * from hr.regions;
ERROR:  connection for foreign table "regions" cannot be established
DETAIL:  ORA-12154: TNS:could not resolve the connect identifier specified
```
Question: does this error assume that I got past my previous error (OCIEnvCreate error )?  If so, then I'm only dealing with a TNS configuration problem it appears.

Also from my orginal post, what else did you expect to see in the environment output for the postgres backend pid?

**Comment by laurenz** [comment]
Everything in your original post looked like there should be no problem.

So you have more than one Oracle installations on the machine. That often causes this problem, usually because one installation tries to use something from the other installation and fails.

The error you enounter now with the other installation is more encouraging, it means you are past the `OCIEnvCreate`. It is a simple configuration issue, the SQL Net Trace will help you debug that quite nicely.

It should not be a problem to have PostgreSQL and Oracle server on the same machine. If you know what you are doing, you could use BEQUEATH connections for added performance.

**Comment by MichaelDBA** [comment]
Got past my last problem with the TNS error,  ORA-12154.  Had used SID for server create, not host:port.

On a side note, with sqlnet.ora suggestions to generate trace files, it did generate trace files, but the SQL statements executed were not in them, even after I did tkprof on them.  What's up with that?

**Comment by laurenz** [comment]
If `OCIEnvCreate` fails, you are far from being connected to the database, let alone send SQL statements. So it is hardly surprising that you see none in the trace file. Unfortunately, this error happens so early that you often don't get meaningful traces at all.
It is a hard error to debug.

I am glad you got the problem solve with the other client though.

**Comment by MichaelDBA** [comment]
Thanks for all your help, Laurenz.  Those "OCIEnvCreate" problems are frustrating since no easy way to figure out the problem initially.  But at least I'm back in the water again.

**Comment by Igor506** [comment]
Michael,

for ubuntu try to put the settings to  /etc/...
e.g.
 /etc/postgresql/9.6/main/environment
...
ORACLE_HOME='/u01/app/oracle/product/12/dbhome_1'
LD_LIBRARY_PATH='/u01/app/oracle/product/12/dbhome_1/lib:/lib:/usr/lib:/usr/lib64'
TNS_ADMIN='/var/lib/postgres'
...
do not forget to mention the service in tnsnames.ora

restart postgres

credentials to oracle have to be in upper case for username, but pwd is case sensitive
as usually
