### ISSUE TITLE
DDL migratrion using "IMPORT FOREIGN SCHEMA"?

### ISSUE THREAD

**Issue by MichaelDBA** [laurenz/oracle_fdw#159]
"IMPORT FOREIGN SCHEMA" is really cool.  I'm wondering if there can be a feature to convert foreign tables to real local tables as part of a migration purpose?  In other words, bypass something like Ora2pg and use oracle_fdw for creating real tables during a DDL migration.

**Comment by laurenz** [comment]
That's beyond the scope of a foreign data wrapper.

But it should be fairly straightforward:

    DO
    $$DECLARE
       tabname text;
    BEGIN
       FOR tabname IN
          SELECT table_name
             FROM information_schema.tables
             WHERE table_schema = 'import_schema'
                AND table_type = 'FOREIGN TABLE'
       LOOP
          EXECUTE 'ALTER FOREIGN TABLE ' || quote_ident(tabname)
             || ' RENAME TO ' || quote_ident(tabname || '_f');
          /* to preserve NOT NULL qualifiers */
          EXECUTE 'CREATE TABLE ' || quote_ident(tabname)
             || ' (LIKE ' || quote_ident(tabname || '_f') || ' INCLUDING ALL);
          EXECUTE 'INSERT INTO ' || quote_ident(tabname)
             || ' SELECT * FROM ' || quote_ident(tabname || '_f');
          EXECUTE 'DROP FOREIGN TABLE ' || quote_ident(tabname || '_f');
       END LOOP;
    END;$$;

I did not test it.
It shouldn't be too hard to create the primary key as well, but I'm too lazy to do it right now.

**Comment by MichaelDBA** [comment]
Thanks for your response, Laurenz, and also for the code snippet.
