### ISSUE TITLE
\setenv TNS_ADMIN ignored

### ISSUE THREAD

**Issue by ccherr** [laurenz/oracle_fdw#16]
I am using an Oracle wallet.  In ~postgres/.bashrc I have:

   export TNS_ADMIN=/path/to/wallet/dir

In psql:

   select * from remote_table;

works and returns rows.

If I remove "export TNS_ADMIN" from .bashrc, then pg_ctl restart, then psql:

   select * from remote_table;

returns:

   ERROR:  session for foreign table "remote_table" cannot be authenticated
   DETAIL:  ORA-01017: invalid username/password; logon denied

which is to be expected.

However, I would expect in psql:

   \setenv TNS_ADMIN /path/to/wallet/dir

to fix the error.  It appears oracle_fdw is not affected by the psql client using \setenv.  Is this by design?  Can it be changed?

psql=> select oracle_diag('dvlp');
 oracle_fdw 1.1.0, PostgreSQL 9.3.5, Oracle client 12.1.0.2.0, Oracle server 11.2.0.3.0
(1 row)

psql=> select oracle_diag();
 oracle_fdw 1.1.0, PostgreSQL 9.3.5, Oracle client 12.1.0.2.0, ORACLE_HOME=/apps/local/instantclient, TNS_ADMIN=/wrong/path
(1 row)

psql=> \setenv TNS_ADMIN /path/to/wallet/dir

psql=> select oracle_diag();
 oracle_fdw 1.1.0, PostgreSQL 9.3.5, Oracle client 12.1.0.2.0, ORACLE_HOME=/apps/local/instantclient, TNS_ADMIN=/wrong/path
(1 row)

**Comment by laurenz** [comment]
If you use \setenv in psql, you will change the environment of the psql client process, but not of the backend server process.
oracle_fdw is loaded into the server process, so it will run with the enviroonment of the backend server process.
