### ISSUE TITLE
ERROR:  could not load library "/opt/PostgreSQL/9.4/lib/postgresql/oracle_fdw.so": libclntsh.so.12.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by imHDoshi** [laurenz/oracle_fdw#161]
Hi,

I have installed Postgresql-9.4 and Oracle client 12.2 on CentOS 7

**.bashrc**

    # .bashrc

    # User specific aliases and functions

    alias rm='rm -i'
    alias cp='cp -i'
    alias mv='mv -i'
    
    # Source global definitions
    if [ -f /etc/bashrc ]; then
            . /etc/bashrc
    fi
 
    export LD_LIBRARY_PATH=/usr/lib/oracle/12.2/client64/lib/
      export TNS_ADMIN=/usr/lib/oracle/12.2/client64
      export ORACLE_HOME=/usr/lib/oracle/12.2/client64
 
    PATH=$PATH:$HOME/bin:/opt/PostgreSQL/9.4:/opt/PostgreSQL/9.4/bin:/usr/lib/oracle/12.2/client64/bin:/usr/lib/oracle/12.2/client64/lib:/usr/lib/oracle/12.2/client64:/usr/lib/oracle/12.2/client64/sdk
    export PATH

**.bash_profile**

    # .bash_profile
 
    # Get the aliases and functions
    if [ -f ~/.bashrc ]; then
            . ~/.bashrc
    fi
 
    # User specific environment and startup programs
 
    PATH=$PATH:$HOME/bin:/opt/PostgreSQL/9.4:/opt/PostgreSQL/9.4/bin:/usr/lib/oracle/12.2/client64/lib:/usr/lib/oracle/12.2/client64:/usr/lib/oracle/12.2/client64/sdk:/usr/lib/oracle/12.2/client64/bin
 
    export LD_LIBRARY_PATH=/usr/lib/oracle/12.2/client64/lib/
      export TNS_ADMIN=/usr/lib/oracle/12.2/client64
      export ORACLE_HOME=/usr/lib/oracle/12.2/client64
    export PATH

**ld.so.conf**

    include ld.so.conf.d/*.conf
    /usr/lib/oracle/12.2/client64:/usr/lib/oracle/12.2/client64/bin:/usr/lib/oracle/12.2/client64/lib:/usr/lib/oracle/12.2/client64/sdk:/opt/PostgreSQL/9.4:/opt/PostgreSQL/9.4/bin:/opt/PostgreSQL/9.4/lib:/opt/PostgreSQL/9.4/lib/postgresql:/opt/PostgreSQL/9.4/data

While creating new Extension I got following error

    ERROR:  could not load library "/opt/PostgreSQL/9.4/lib/postgresql/oracle_fdw.so": libclntsh.so.12.1: cannot open shared object file: No such file or directory

**Comment by laurenz** [comment]
Your `ld.so.conf` file looks wrong.

An entry is a single directory name, not a colin separated path string.

Moreover, it should only contain the directories that contain shared objects (`*.so` files) that you need to load, not the binaries or header files.

So the entry should probably look like this:

    /usr/lib/oracle/12.2/client64/lib

Don't forget to run `ldconfig` as user `root` after you edit the file.

**Comment by imHDoshi** [comment]
Thanks Laurenz, now I am able to create extension.
