### ISSUE TITLE
could not load library "C:/POSTGR~1/pg96/../pg96/lib/postgresql/oracle_fdw.dll": %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by HiyamB** [laurenz/oracle_fdw#163]
Hello Sir, 

When i execute the query 
**Create extension oracle_fdw**
 i got the following error:

**could not load library "C:/POSTGR~1/pg96/../pg96/lib/postgresql/oracle_fdw.dll": %1 is not a valid Win32 application**

I have  copied ( oracle_fdw.dll) to  C:\PostgreSQL\pg96\lib\postgresql

and the files :   
- oracle_fdw.control 
- oracle_fdw--1.0--1.1.sql
- oracle_fdw--1.1.sql

 to  C:\PostgreSQL\pg96\share\postgresql\extension

systems specifications 

windows 10 64 bit

oracle 11g 64 bit (   i have installed the server and client and made sure that they are connected successfully ) 
postgresql 96 64 bit

I appreciate your help :)

Kind regards,
Hiyam

**Comment by laurenz** [comment]
Your PostgreSQL server is 32-bit, not 64-bit as you think.
