### ISSUE TITLE
I am having issue in windows while executing "make" command in cygwin ? 

### ISSUE THREAD

**Issue by awesomehimanshu** [laurenz/oracle_fdw#164]
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lclntsh
collect2: error: ld returned 1 exit status
make: *** [/usr/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.shlib:367: oracle_fdw.dll] Error 1

I have set all the path

13  echo $PATH;
   14  echo $PGHOME;
   15  export PGHOME=/cygdrive/c/PostgreSQL
   16  echo $PGHOME;
   17  export PGLIB=$PGHOME/lib
   18* echo
   19  export LD_LIBRARY_PATH=$PGLIB:/cygdrive/c/oracle/instantclient_12_2
   20  export ORACLE_HOME=/cygdrive/c/oracle/instantclient_12_2

**Comment by laurenz** [comment]
This is unsurprising &ndash; `ld` is looking for `libclntsh.dll`, but the Oracle Client library on Windows is `oci.dll`.

I have fixed the `Makefile` with commit 6d311aa666e6eb94ce0ee66deb0e451365881a53.

Could you check if it fixes the problem?
I admit that I never tested on cygwin; I'd be interested to get feedback from you if you get it to run.

**Comment by awesomehimanshu** [comment]
By the way thanks @laurenz for wonderful extension . I have used your compiled source code it work fine for me . I will work on cygwin by this commit and will tell .
Thanks

**Comment by awesomehimanshu** [comment]
I have taken your commit 6d311aa makefile and paste in my makefile same issue .

**Comment by laurenz** [comment]
It is still looking for `clntsh`, not for `oci`?

**Comment by laurenz** [comment]
I'll close this issue for lack of feedback.
I'm still interested if the linker is looking for `oci` now or still for `clntsh`.
