### ISSUE TITLE
/usr/bin/ld: cannot find -lclntsh error in make

### ISSUE THREAD

**Issue by awesomehimanshu** [laurenz/oracle_fdw#166]
Not working in ubuntu

    /usr/bin/ld: cannot find -lclntsh
    collect2: error: ld returned 1 exit status
    make: *** [oracle_fdw.so] Error 1
    /usr/lib/postgresql/9.6/lib/pgxs/src/makefiles/../../src/Makefile.shlib:310: recipe for target 'oracle_fdw.so' failed
    The command '/bin/sh -c make' returned a non-zero code: 2

Can you tell me which parameter should be set before make command?

I have set `ORACLE_HOME` and `LD_LIBRARY_PATH`:

    ORACLE_HOME=/instantclient_12_2 
    LD_LIBRARY_PATH=/instantclient_12_2::/instantclient_12_2/sdk/include/

**Comment by laurenz** [comment]
Where is your `libclntsh.so`? It should be in `$ORACLE_HOME`, `$ORACLE_HOME/bin` or `$ORACLE_HOME/lib`.

**Comment by Keleir** [comment]
I met the same question:
```
# github.com/mattn/go-oci8
/bin/ld: cannot find -lclntsh
```
Here is the details mattn/go-oci8#168

**Comment by laurenz** [comment]
Please don't hijack a foreign thread, particularly if your problem is not with oracle_fdw.

This error means that the library is not in on the library path during compilation.
