### ISSUE TITLE
ERROR:  could not load library "/opt/postgresql/9.6/lib/postgresql/oracle_fdw.so": libclntsh.so.12.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sumshu** [laurenz/oracle_fdw#167]
I have below environment variables set:
export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib:$LD_LIBRARY_PATH
export ORACLE_HOME=/usr/lib/oracle/12.1/client64
PATH=$PATH:/usr/lib/oracle/12.1/client64/bin:/usr/lib/oracle/12.1/client64/lib:/usr/lib/oracle/12.1/client64:/usr/lib/oracle/12.1/client64/sdk
export PATH

The file /opt/postgresql/9.6/lib/postgresql/oracle_fdw.so is also available. 

I have also added "include /usr/lib/oracle/12.1/client64/lib" in /etc/ld.so.conf 

I still see below error when I perform "create extension oracle_fdw;"

ERROR:  could not load library "/opt/postgresql/9.6/lib/postgresql/oracle_fdw.so": libclntsh.so.12.1: cannot open shared object file: No such file or directory

**Comment by laurenz** [comment]
See my [answer on the mailing list][1].

Essentially, the environment variable is probably not set in the PostgreSQL server's environment.

 [1]: https://www.postgresql.org/message-id/A737B7A37273E048B164557ADEF4A58B53A4D8A3%40ntex2010i.host.magwien.gv.at

**Comment by sumshu** [comment]
This has been resolved.  In my case the issue was with the service script. Thanks

**Comment by parekhjeet** [comment]
cvfopd=# CREATE EXTENSION oracle_fdw;
ERROR:  incompatible library "/usr/pgsql-9.6/lib/oracle_fdw.so": version mismatch
DETAIL:  Server is version 9.6, library is version 9.5.

**Comment by parekhjeet** [comment]
how to resolve the issue, i am upgrading the database from 9.5 to 9.6 and i am facing this issue

**Comment by laurenz** [comment]
You need to rebuild oracle_fdw with PostgreSQL 9.6

You cannot use a shared library from 9.5 with 9.6
