### ISSUE TITLE
Upgrade from oracle_fdw 1.3 to oracle_fdw 1.5

### ISSUE THREAD

**Issue by sumshu** [laurenz/oracle_fdw#169]
Hi Laurenz,

Could  you please let me know on how to upgrade foracle_fdw from version 1.3 to 1.5

Thanks
Sumeet

**Comment by laurenz** [comment]
Just run `make install` like you did to build version 1.3.

There is nothing you have to change in the database, just replace the shared library.

Database sessions have to be restarted for the upgrade to take effect.

If you are using the Windows binaries, just unpack the ZIP file an replace the files already present.
