### ISSUE TITLE
Is it mandatory to select all columns of Oracle table while using Oracle_fdw to migrate in Postgres. How can we select columns which we prefer?

### ISSUE THREAD

**Issue by AnandNicky** [laurenz/oracle_fdw#173]
Example In oracle, Table test has following columns with datatype:

    art_id              NUMBER(38) not null,
    short_art_title     VARCHAR2(250 CHAR) not null,
    short_art_text      VARCHAR2(4000 CHAR),
    art_ts                TIMESTAMP(9),

How can we create a foreign table in postgres, when we just want `short_art_title` , `art_ts` these two columns only?

Thanks!

**Comment by laurenz** [comment]
Several ideas:

1. Only select the columns you want.

2. Define a foreign table on all four columns, then define a view that selects only the two desired columns from the foreign table.

3. Define the foreign table like this

       CREATE FOREIGN TABLE (art_id bigint, art_ts timestamp without time zone)
          ...
          OPTIONS (table '(SELECT art_id, art_ts FROM ...)')

**Comment by AnandNicky** [comment]
Thanks For the response!
Tried with option 3. Its working.
