### ISSUE TITLE
Converting XML Value to JSON

### ISSUE THREAD

**Issue by AnandNicky** [laurenz/oracle_fdw#174]
Hi Laurenz,
With reference to #172

I used getClobVal() to fetch the value of xml and stored in test datatype in foreign table, now I am able to fetch the values from the foreign table but my project requirement is to convert this fetched xml value in text datatype to JSON format.

Eg: how I used to create, fetch and store xml data form Oracle to Postgres.
CREATE FOREIGN TABLE test_xml_clob(user_id INTEGER OPTIONS (key 'true') NOT NULL, uth_token VARCHAR(100), device_id VARCHAR(50)  not null,user_info CLOB) SERVER oradb1 OPTIONS (table '(SELECT a.user_id, a.auth_token, a.device_id, a.user_info.getClobVal() FROM TEST.USER_DEATAILS a)');

Please help to figure out this issue.

**Comment by laurenz** [comment]
The task to convert XML to JSON is outside the scope of oracle_fdw.

I guess you'll either have to do this in application code or write a function in Oracle or PostgreSQL for it.
