### ISSUE TITLE
Conversion of oracle timestamp to postgres timestamp?

### ISSUE THREAD

**Issue by AnandNicky** [laurenz/oracle_fdw#175]
Hi Laurenz, While trying to migrate Oracle time stamp in PostgreSQL time stamp, its working great but I have one doubt for the same. 

In Oracle we have a time stamp in hh12 format:
i.e. for example:
18-APR-17 05.15.44.201587 AM
05-MAY-17 02.07.27.453601 PM
We get it in the form of AM and PM.

But in PostgreSQL foreign table we get its output as:
2017-04-18 05.15.44.201587
2017-05-05 14:07:27.453601

Could you please help me to migrate time stamp column in PostgreSQL in the same format of Oracle.

Regards,

**Comment by laurenz** [comment]
A timestamp does not have a certain format in Oracle, it is the value of the `NLS_TIMESTAMP_FORMAT` parameter (or environment variable) that etermines the format when a timestamp is converted to a string (e.g., to display it with sqlplus).

In PostgreSQL, there is the `DateStyle` parameter that serves a similar purpose, but it only can take the values `ISO`, `Postgres`, `SQL` and `German`, none of which looks like you want.

You will have to use `to_char` to format timestamps the way you want:

    SELECT to_char(localtimestamp, 'DD-MON-YY HH12:MI:SS.US AM');
    ┌──────────────────────────────┐
    │           to_char            │
    ├──────────────────────────────┤
    │ 09-JUN-17 02:11:24.541811 PM │
    └──────────────────────────────┘
    (1 row)

**Comment by AnandNicky** [comment]
Thanks for the response Laurenz!
But still my issue exists as at the time of migrating data from Oracle to PostgreSQL, time stamp values are not fetched in the desired format.

For Example: Created table in Oracle, inserted systimestam in it.

![oracle table timestamp](https://user-images.githubusercontent.com/29143372/26976792-020a6e16-4d43-11e7-9ae5-5e4f2805070a.PNG)

For the same, I have tried migrating in Psql with the syntax as:

CREATE FOREIGN TABLE mobile.test_Psql ( mob_ts timestamp) SERVER oradb1 OPTIONS (table '(SELECT mob_ts FROM MOBILE.test_Oracle)');

![postgresql table timestamp](https://user-images.githubusercontent.com/29143372/26976876-6dc19fc6-4d43-11e7-8c10-1f2a22aaa16e.PNG)

But the desired out, I wish to have in PostgreSQL foreign table is -
2017-06-09 08:58:18.413714 AM
2017-06-08 08:58:18.413714 PM

**Comment by laurenz** [comment]
As I told you, you should

    SELECT to_char(mob_ts, 'DD-MON-YY HH12:MI:SS.US AM')
    FROM mobile.test_psql;
