### ISSUE TITLE
SDO_GEOMETRY - Equivalent in PostgreSQL 

### ISSUE THREAD

**Issue by ferozbasha** [laurenz/oracle_fdw#176]
Hi Laurenz,

Am trying to migrate Oracle DB to PostgreSQL DB. Am stuck up in one of the spatial data type. I tried installing Postgis extension but am not getting it. Kindly help me.

My Oracle insert command something has like below:
SDO_GEOMETRY(2001, NULL, SDO_POINT_TYPE(NULL, NULL, NULL), NULL, NULL)
For the above, what would be the equivalent data type and inserting values for PostgreSQL.

Please help!.

**Comment by laurenz** [comment]
If you want oracle_fdw to translate `SDO_GEOMETRY` to `geometry`, you'll have to install PostGIS.

The point that you quote above will not work though &ndash; it will raise the error

    ERROR:  error converting SDO_GEOMETRY to geometry: null point coordinates not supported

There is no way to represent such a point in PostGIS. Use a NULL value instead to indicate that the point's coordinates are unknown.

**Comment by ferozbasha** [comment]
Hi Laurenz,

Thanks a lot for responding. :).  Yes, I faced the same error message. I have already installed PostGIS and am new to PostGIS and Spatial stuffs actually. Is there any easy way where i can translate SDO_GEOMETRY to geometry using oracle_fdw. Kindly please me in this.

**Comment by laurenz** [comment]
Yes. But not this one.
