### ISSUE TITLE
Conversion of XML containing CADTA/HTML to JSON 

### ISSUE THREAD

**Issue by AnandNicky** [laurenz/oracle_fdw#177]
Hi Laurenz,

Referring issue #172 .

My work involved fetching all the details available in XML format in Oracle  to converting it into JSON.

For the same where ever I had XML, I had converted it into JSON using function at oracle side and then had included it in foreign table  (eg. : select mypkg.xml2json(t.USER_INFO).to_char() from info_table t; ).

& this i am sucessully able to capture translated XML to JSON in text datatype in PoastgreSQL.

But the problem arises where XML has CDATA in it.

neither I am able to use XMLTYPE.GETCLOBVAL() to save xml content as it is in Postgre; nor I am able to convert in into xml2json.

My desire resultant should be XML should be converted to JSON but wherever it has CDATA or HTML embedded in it, that should come as it is. 

Kindly help to find the proper solution for it.

**Comment by laurenz** [comment]
I am not sure if I understand the question.

Are you trying to get the contents of a CDATA expression?
Where is the problem?

    CREATE TABLE xml (id number(5) CONSTRAINT xml_pkey PRIMARY KEY, x XMLType);

    INSERT INTO xml
       VALUES (
          1,
           '<doc><content att="mama"><![CDATA[Something with < and > in it]]></content></doc>'
       );

    COMMIT;

Then I can get the text in the `<content>` tag with:

    SELECT id,
           xmlquery('/doc/content/text()' PASSING x RETURNING CONTENT) AS content
    FROM xml;

    ID CONTENT
    -- ----------------------------------------
     1 <![CDATA[Something with < and > in it]]>

Now if I want to get rid of the CDATA, I can do something like

    SELECT id,
           regexp_substr(
              xmlquery('/doc/content/text()' PASSING x RETURNING CONTENT),
              '^<!\[CDATA\[(.*)\]\]>$',
              1,
              1,
              NULL,
              1
           ) AS content
    FROM xml;

    ID CONTENT
    -- ----------------------------------------
     1 Something with < and > in it

Anyway, all that doesn't seem to have much to do with oracle_fdw...

**Comment by AnandNicky** [comment]
thanks for the response Laurenz!

I will try to explain myself in more descriptive way. 

when the value of x in table xml is "<user-info>
  <device-name>My iPad2</device-name>
  <locale-language>en</locale-language>
  <device-uname>iPad2,2</device-uname>
  <current-dttm>2012-03-12 16:23:58</current-dttm>
  <device-version>5.1</device-version>
  <device-system>iPhone OS</device-system>
  <app-version>1.1.1</app-version>
  <device-model>iPad</device-model>
</user-info>" ==> XMLTYPE.

I am able to process its data and convert it in JSON using -
select mypkg.xml2json(t.x).to_char() from xml t; 

but in case, if we talk about the data which you had inserted, I am not able to parse the given XML to JSON.

I must admit, initially it is not related to Oracle_fdw but after processing i need it in PotgreSQL using oracle_fdw

**Comment by AnandNicky** [comment]
<user-info>
  <device-name>My iPad2</device-name>
  <locale-language>en</locale-language>
  <device-uname>iPad2,2</device-uname>
  <current-dttm>2012-03-12 16:23:58</current-dttm>
  <device-version>5.1</device-version>
  <device-system>iPhone OS</device-system>
  <app-version>1.1.1</app-version>
  <device-model>iPad</device-model>
</user-info>

**Comment by laurenz** [comment]
Then why don't you modify `mypkg.xml2json` so that it handles `<![CDATA[]]>` correctly?

**Comment by AnandNicky** [comment]
That's the last option which we might use, as of now we are mainly focusing to keep Oracle objects as it is!
No alteration in available packages or procedures in Oracle.

Hence trying to figure out the other way.

**Comment by laurenz** [comment]
I understand, though I would argue that it is a bug in the Oracle function if it doesn't handle CDATA correctly.

You can of course also write a function in PostgreSQL that modigies JSON data by &ldquo;unpacking&rdquo; CDATA sections in all string attributes.

Then you can define a view on the foreign table that applies the function to all JSON data, and you are set. Is this a solution for you?

**Comment by AnandNicky** [comment]
Thanks for the response, Laurenz!
Yes, m trying to check at Oracle end.
