### ISSUE TITLE
Create extension in PostgreSQL

### ISSUE THREAD

**Issue by navinkumarmishra** [laurenz/oracle_fdw#178]
Hello friends,

I want to know the steps for creating extension for 'pltclu' in PostgreSQL. 
Can anybody elaborate the steps as i am getting following error while creating extension:
ERROR:  could not load library "C:/Program
Files/PostgreSQL/9.4/lib/pltcl.dll": The specified module could not be
found.

**Comment by laurenz** [comment]
Sorry, this has nothing to do with oracle_fwd.
Make sure you have TCL installed.

**Comment by navinkumarmishra** [comment]
I have TCL installed on my system
