### ISSUE TITLE
PostgreSQL 9.2.3 to Oracle 12.2

### ISSUE THREAD

**Issue by robersonjfa** [laurenz/oracle_fdw#179]
Hi Laurenz,

Congratulations for your job with this extension for PostgreSQL. 
We starting a project where we need to send data from PG to Oracle. Is possible to enable commands like INSERT, UPDATE and DELETE to send this data from PostgreSQL 9.2.3 to Oracle 12.2?

Thanks.

**Comment by laurenz** [comment]
Support for DML with foreign data wrappers was added in PostgreSQL 9.3, so it cannot be used in earlier versions. There is no substitute for it either.

But if you start a new project, you shouldn't be using a PostgreSQL version that will be going out of support in a few months. Even if this you are working with a pre-existing PostgreSQL database, it might be wise to upgrade the database before you start developing something new with it.
