### ISSUE TITLE
Access violation - code c0000005 occurred on postgres.exe when throw specific SQL.

### ISSUE THREAD

**Issue by YoichiroGoda** [laurenz/oracle_fdw#182]
Hello, Mr.
We have serious issues.
Do you know workaround?
Maybe you can reproduce this issue easily.

[Problem:]
postgres.exe was crash with c0000005 when throw specific SQL.
from pg_log
2017-07-13 12:15:38 JST LOG:  server process (PID 3596) was terminated by exception 0xC0000005
2017-07-13 12:15:38 JST DETAIL:  Failed process was running: select a.col_a,b.col_b,(select ora.col_ora_c1 from table_ora_c ora where ora.col_ora_c = b.col_b2) from table_a1 a left outer join table_b1 b on a.col_a = b.col_b;

[The problemable SQL is below:]
select a.col_a,b.col_b,(select ora.col_ora_c1 from table_ora_c ora where ora.col_ora_c = b.col_b2) from table_a1 a left outer join table_b1 b on a.col_a = b.col_b;

table_a1    --- postgre side table.
table_b1    --- postgre side table.
table_ora_c --- oracle side table. (via oracle_fdw)

[Used version is:]
oracle_fdw 1.5.0
postgres 9.5.5.16298 64bit on Windows8.1
Oracle Databese 11g Express Edition Release 11.2.0.2.0 - 64bit on Windows8.1
*postgres and oracle in the same machine.

[How to reproduce]
--Oracle Side-------------------------
1.Use Scott user. create table.

  create table "scott"."table_ora_c" 
   (	"col_ora_c1" number, 
	"col_ora_c" number(*,0)
   ) segment creation immediate 
  pctfree 10 pctused 40 initrans 1 maxtrans 255 nocompress logging
  storage(initial 65536 next 1048576 minextents 1 maxextents 2147483645
  pctincrease 0 freelists 1 freelist groups 1 buffer_pool default flash_cache default cell_flash_cache default)
  tablespace "system" ;

2.Login as Scott user. create data.
insert into table_ora_c values('100','100');
insert into table_ora_c values('200','200');

--Postgres Side-------------------------
1.create schema
CREATE SCHEMA bob;
create role bob with password 'password';
alter role bob login;
GRANT ALL PRIVILEGES ON schema bob TO bob;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA bob TO bob;

2.create table
-- Table: bob.table_a1
CREATE TABLE bob.table_a1(  col_a bigint);
-- Table: bob.table_b1
CREATE TABLE bob.table_b1( col_b bigint,  col_b2 bigint)

3.create data
insert into table_a1 values('100');
insert into table_b1 values('100');
*if you exec insert into table_b1 values('100','100'); , not crash.

4.create oracle_fdw
create EXTENSION oracle_fdw;
CREATE SERVER oraclexe FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '//172.16.1.91/xe');
CREATE USER MAPPING FOR public SERVER oraclexe options (user 'scott', password 'tiger');
IMPORT FOREIGN SCHEMA "SCOTT" FROM SERVER oraclexe INTO public;
GRANT USAGE ON FOREIGN SERVER oraclexe TO bob;

5.login as bob and exec sql
select a.col_a,b.col_b,(select ora.col_ora_c1 from table_ora_c ora where ora.col_ora_c = b.col_b2) from table_a1 a left outer join table_b1 b on a.col_a = b.col_b;

postgres.exe proccess is crash!

**Comment by laurenz** [comment]
This is the same error as #145.

The problem happens on Windows when a NULL value is passed as parameter to a foreign scan; in your case, it is `b.col_b2`.

You need a version of oracle_fdw that contains at least patch aca12d000991cfaaee8e928448cb50747df1bc32.

If you cannot build oracle_fdw yourself, I could build it and send it to you, but I'd need an e-mail address.

**Comment by YoichiroGoda** [comment]
I will try to modify and build it.
Your excellent product  and support will help us.
Thank you very much. Mr. laurenz.

**Comment by YoichiroGoda** [comment]
I confirmed that crash problem was gone.
Thanks again, Mr.laurenz.
Please close this issue.
