### ISSUE TITLE
Issues when using oracle_fdw extension in windows

### ISSUE THREAD

**Issue by Leandrompl** [laurenz/oracle_fdw#183]
I'm trying to install and use oracle_fdw in postgresql 9.6, however I keep receiving the same issue every time that I run the following command:

create extension oracle_fdw;
ERROR:  could not load library "D:/PostgreSQL/pg96/../pg96/lib/postgresql/oracle_fdw.dll": 
    The specified module could not be found.
Two things are very strange here:

1- the folder that it's looking for the dll, has a ".." in the middle, so it seems it should look into D:\PostgreSQL\pg96\lib only, but I do have the folder D:\PostgreSQL\pg96\lib\postgresql as well.

2- I set the following variables in the system, but it seems not to reflect in the command:
Path: D:\PostgreSQL\pg96\lib\;C:\Program Files\Oracle Instant Client\instantclient_12_2; 
    D:\PostgreSQL\pg96\lib\postgresql

PS: check my Environment Variables:
ORACLE_HOME: C:\Program Files\Oracle Instant Client\instantclient_12_2

PATH: C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\idmu\common;C:\coreutil\SfPkgInstall;c:\coreutil\sfreskit;C:\coreutil\sysinternals;c:\coreutil\ntreskit;C:\usr\OV\lib;C:\usr\OV\bin;C:\usr\OV\bin\win64;C:\usr\OV\bin\win64\OpC;D:\coreutil\OmniBack\bin\;C:\Program Files\Oracle Instant Client\instantclient_12_2;D:\PostgreSQL\pg96\lib\postgresql;c:\orcale_odbc

**Comment by YoichiroGoda** [comment]
I faced same issues on Windows.

In my case,
I did not have msvcr120.dll,msvcr140.dll,msvcp120.dll,msvcp140.dll etc on system32 folder.
oracle_fdw need these files.

Visual C++ Redistributable for Visual Studio 2015
https://www.microsoft.com/en-us/download/details.aspx?id=48145

Visual C++ Redistributable Packages for Visual Studio 2013
https://www.microsoft.com/en-us/download/details.aspx?id=40784

After install these, problem was gone.

**Comment by Leandrompl** [comment]
Unfortunately it didn't work. I already have it installed. Any other idea?

**Comment by YoichiroGoda** [comment]
I heard oracle_fdw.dll need the below module.

VC runtime(VCRUNTIME140.DLL etc)
oci.dll(Provided by Oracle Instant Client）

Your Postgres,oracle_fdw,Oracle Instant Client,VCruntime is all 64bit?
64bit application cannot load 32 bit application and vice versa.

**Comment by Leandrompl** [comment]
It's all 64 bit. I already reinstalled everything as well and nothing works =/

**Comment by YoichiroGoda** [comment]
Sorry, I don't have any other idea.
Please wait owner's reply.

**Comment by laurenz** [comment]
The problem is probably that `oci.dll` is not on the shared library search path of the PostgreSQL server.

Are you sure that the PostgreSQL service has got the `PATH` setting you show? Did you restart PostgreSQL after you changed the `PATH` environment variable?

You could use [process monitor][1] to see where the PostgreSQL backend process looks for `oci.dll` and why it cannot find it.

[1]: https://technet.microsoft.com/en-US/sysinternals/processmonitor.aspx

**Comment by chrullrich** [comment]
Your installation path ("pg96") looks similar to the one from bug #160. Could you see if perhaps the suggestions and solution there also apply in your case?
