### ISSUE TITLE
Issue While creating function in PostgreSQL “ERROR: syntax error at or near ”ROWTYPE“”

### ISSUE THREAD

**Issue by AnandNicky** [laurenz/oracle_fdw#184]
Hi Laurenz,

While trying to migrate Procedures and functions to PostgreSQL, in one of of the function of PL/SQL I am facing an issue for %ROWTYPE.

Below is a simple procedure in PL/SQL

    PROCEDURE emp_get_rec (emp_rec IN OUT NOCOPY emp_content%ROWTYPE)
    IS
        v_cnt   NUMBER;
    BEGIN
        SELECT COUNT(*)
           INTO v_cnt
           FROM emp_content
           WHERE emp_id = emp_rec.emp_id;
        IF v_cnt = 1
        THEN
           SELECT * INTO emp_rec
           FROM emp_content
           WHERE emp_id = emp_rec.emp_id;
        END IF;
     END emp_get_rec;

Which I am trying to convert in PostgreSQL,

    Create or replace function emp_get_rec (emp_rec IN OUT emp_content%ROWTYPE)
    AS $BODY$
    DECLARE
       v_cnt   NUMBER;
    BEGIN
       SELECT COUNT(*)
          INTO v_cnt
          FROM emp_content
          WHERE emp_id = emp_rec.emp_id;
       IF v_cnt = 1
       THEN
           SELECT * INTO emp_rec
           FROM emp_content
           WHERE emp_id = emp_rec.emp_id;
        END IF;
    END;
    $BODY$ LANGUAGE 'plpgsql';

I am facing following error:

    ERROR: syntax error at or near "ROWTYPE"

Kindly let me know, where am I going wrong? Or what syntax i should use?

Regards,

**Comment by laurenz** [comment]
Just omit the `%ROWTYPE` and use the type `emp_content`.

I would appreciate if you didn't use oracle_fdw issues for problems with PL/pgSQL syntax...
