### ISSUE TITLE
/usr/bin/ld: BFD version 2.20.51.0.2-5.47.el6_9.1 20100205 internal error

### ISSUE THREAD

**Issue by gugo-95** [laurenz/oracle_fdw#185]
Hello Laurenz
When I do 'make' I'm getting such error

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -fpic -shared -o oracle_fdw.so oracle_fdw.o oracle_utils.o oracle_gis.o -L/usr/pgsql-9.6/lib -Wl,--as-needed  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-9.6/lib',--enable-new-dtags  -L/usr/lib/oracle/12.2/client64 -L/usr/lib/oracle/12.2/client64/bin -L/usr/lib/oracle/12.2/client64/lib -lclntsh -L/usr/lib/oracle/12.2/client/lib -L/usr/lib/oracle/12.2/client64/lib -L/usr/lib/oracle/12.1/client/lib -L/usr/lib/oracle/12.1/client64/lib -L/usr/lib/oracle/11.2/client/lib -L/usr/lib/oracle/11.2/client64/lib -L/usr/lib/oracle/11.1/client/lib -L/usr/lib/oracle/11.1/client64/lib -L/usr/lib/oracle/10.2.0.5/client/lib -L/usr/lib/oracle/10.2.0.5/client64/lib -L/usr/lib/oracle/10.2.0.4/client/lib -L/usr/lib/oracle/10.2.0.4/client64/lib -L/usr/lib/oracle/10.2.0.3/client/lib -L/usr/lib/oracle/10.2.0.3/client64/lib 
> /usr/bin/ld: BFD version 2.20.51.0.2-5.47.el6_9.1 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size
> 
> /usr/bin/ld: Please report this bug.
> 
> collect2: ld returned 1 exit status
> make: *** [oracle_fdw.so] Error 1
> 
>  

I set $ORACLE_HOME variable 
and in /etc/ld.so.conf I have 
```
include ld.so.conf.d/*.conf
/usr/lib/oracle/12.2/client64/lib

```
PostgreSQL version: 9.6.3

**Comment by laurenz** [comment]
A web search suggests that this is a bug in `ld`.

Try installing a later version of the &ldquo;binutils&rdquo; package or try `make -j 1`.

**Comment by gugo-95** [comment]
`make -j 1` didn't help.
about binutils, it says I already have latest version
`Package binutils-2.20.51.0.2-5.47.el6_9.1.x86_64 already installed and latest version`

**Comment by laurenz** [comment]
I have exactly the same version on my system and never had this problem.

Unfortunately I cannot help you with that one...

**Comment by shsong** [comment]
@gugo-95 
please try to use a newer version of `ld`

e.g.) install devtoolset-6
```
$ /opt/rh/devtoolset-6/root/usr/bin/ld --version
GNU ld version 2.27-8.el6
```
