### ISSUE TITLE
Cannot connect to Oracle

### ISSUE THREAD

**Issue by MichaelHolzman** [laurenz/oracle_fdw#186]
I've installed the latest version built from sources on EDB Advanced Server 9.6 (RHEL 7.3)
CREATE SERVER, CREATE USER, CREATE FOREIGN TABLE commands succeeded. Unfortunately, the 'select * 'from the foreign table fails with the message 
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
DETAIL:

The PATH and LD_LIBRARY_PATH are correct. 'ldd /opt/edb/as9.6/lib/oracle_fdw.so' passes.
Please assist

**Comment by laurenz** [comment]
People who had tried out oracle_fdw with EDB's PostgreSQL fork have reported errors.

Did you have no problem building oracle_fdw?

The error means that oracle_fdw can be loaded, but there is a problem initializing the Oracle client.

This error message unfortunately is very general.
Often it means that something is wrong with the environment.

See if you can connect qith sqlplus as PostgreSQL operating system user.

Sometimes this error is thrown if there is more than one Oracle installation on the machine.

**Comment by MichaelHolzman** [comment]
There were four warnings about incompatible pointer type at compilation.
sqlplus connects smoothly
I searched for this string in the sources and found it in one place only; oracle_utils.c, line 151

**Comment by laurenz** [comment]
Did you check that the PostgreSQL server has the same Oracle environment as your postmaster process? Look at `/proc/xxxxx/environ`, where `xxxxx` is the postmaster PID.

Other than that, I cannot help you since that Oracle error message is too general.

**Comment by MichaelHolzman** [comment]
Yes, it has the same environment

**Comment by laurenz** [comment]
You could try running `strace` on the PostgreSQL backend an see if it has a problem finding files...

But I'm clutching at straws here.

**Comment by MichaelHolzman** [comment]
I ran strace (I found here a similar issue yesterday and tried everything that was there). I found nothing.
