### ISSUE TITLE
Call Oracle Procedure

### ISSUE THREAD

**Issue by fabiozesge** [laurenz/oracle_fdw#187]
Hello, I'm trying to call a oracle procedure using oracle_fdw, but I'm not getting any positive results.
In SQLDeveloper I call `Execute oracleprocedure (1,2,3)`

How can I make this call using oracle_fdw?

**Comment by laurenz** [comment]
There is no direct way to do that.

You could define an Oracle table with a trigger that calls the procedure when table value are updated and run an `UPDATE ... RETURNING` statement in PostgreSQL that triggers the procedure.

There might be other similar tricks to achieve that.

**Comment by laurenz** [comment]
Just for reference, because somebody asked:

[Here](https://stackoverflow.com/a/46360383/6464308) is an example how that could be done for a function (but you can also call a procdedure in the trigger).
