### ISSUE TITLE
How can i insert dynamic value in the foreign table created by query?Is it possible?

### ISSUE THREAD

**Issue by awesomehimanshu** [laurenz/oracle_fdw#189]
Hi laurenz ,
I am using ORACLE_FDW for postgres to oracle migration. So i have procedure with multiple join and it is take time if i excute it from postgres .  
So can be the approach for doing so .

I have seen the docs , it says create a table with that select query and the whole query will execute in oracle only and this will give be fast output.

I have procedure 

```
CREATE foreign TABLE webowner.content
(  blurb_id integer
server oradb1 options(TABLE
 '(SELECT l.blurb_id FROM sometable l
        INNER JOIN sometable1 b ON b.blurb_id = l.target_blurb_id
        INNER JOIN sometable2  bap ON bap.blurb_id = b.blurb_id
        INNER JOIN (SELECT agfa.ap_id FROM  sometable3 agfa WHERE agfa.group_id!='INTRA')tt ON tt.ap_id=bap.ap_id
        WHERE l.blurb_id=a_blurb_id AND l.external_yn = 'Y'
        UNION ALL
        SELECT l.blurb_id FROM  sometable l
        INNER JOIN sometable1 b ON b.article_id=l.article_id
        INNER JOINsometable2 bap ON bap.blurb_id = b.blurb_id
        INNER JOIN (SELECT agfa.ap_id FROM sometable3 agfa WHERE agfa.group_id!='INTRA')tt ON tt.ap_id=bap.ap_id
        WHERE l.blurb_id=a_blurb_id AND l.external_yn = 'Y')')  
```

**What i want in this code , i have to insert a_blurb_id  dynamically at query time which is inside the query . I can i do so.**

**Comment by laurenz** [comment]
Your query is kind of weird, because you only select `l.blurb_id`, which must be equal to `a_blurb_id`.

So the result could only be zero or more copies of `a_blurb_id`. Is that what you want?

What you could do is omit the condition(s)

    WHERE l.blurb_id=a_blurb_id

from your query and query the foreign table like this:

    SELECT blurb_id
    FROM webowner.content
    WHERE blurb_id = a_blurb_id;

Then the condition will be pushed down and appended to the Oracle query, and with some luck the Oracle optimizer will be smart enough to process it efficiently.

**Comment by awesomehimanshu** [comment]
Yes i want that only . Thanks i have applied same approach for current.  But if i need some query.

select * from  student where rollno = 34 union all select * from college name ="xyz"

and this 34 and xyz should be dynamic what you will perfer

**Comment by laurenz** [comment]
Some ideas:

1. You could define the remote table with

       SELECT * FROM student UNION SELECT * FROM college

   and try if Oracle is smart enough to push a `WHERE` clause down into the `UNION`.

2. You could define two foreign tables, one on `student` and one on `college`.
   Then run your `UNION` query in PostgreSQL, and things should work well.

**Comment by awesomehimanshu** [comment]
I don't think this is good practice , can we not make it like , give them variable while calling time .

means while i call foreign table i could be able to able to pass dynamic value , by this way i will we able to execute exact query i want. I will look to your code at week end .

**Comment by laurenz** [comment]
The way to supply a parameter in an SQL statement is a `WHERE` clause; I cannot see what should be bad practice about that.

Contrariwise, I cannot imagine how else you could supply a parameter to a table in SQL.
