### ISSUE TITLE
Modifying Existing PostgreSQL Table?

### ISSUE THREAD

**Issue by bsislow** [laurenz/oracle_fdw#196]
We are attempting to write rows which are INSERTed into a partitioned Postgres table **into** Oracle using oracle_fdw. We only need to "wrap" one partition in the table - not the entire table.

The table (partition) was already created and I assume it should've been created as a FOREIGN table? It is just a partitioned table by a key value. Can we convert the existing table? It (the partition in question) already contains millions of rows.

Let me know if this makes sense...

**Comment by laurenz** [comment]
From PostgreSQL 9.5 on a foreign table can be an inhertiance child of another table (`ALTER FOREIGN TABLE ... INHERIT ...`), so you can have a foreign table as a partition.

You'd have to create a foreign table with the same data as the current local partition, either with `INSERT INTO ... SELECT ...` or with `COPY` and [SQL*Loader](docs.oracle.com/cd/E11882_01/server.112/e22490/part_ldr.htm).

Then remove the local partition and replace it with the foreign table.

**Comment by bsislow** [comment]
Excellent, we thought of this as well since we posted using INHERIT. We will test this and then request an issue close. Thanks.

**Comment by bsislow** [comment]
This can be closed. This was the correct solution. Thank you.
