### ISSUE TITLE
How do I use oracle query hints in oracle_fdw? 

### ISSUE THREAD

**Issue by peixubin** [laurenz/oracle_fdw#197]
Oracle_fdw  automatically delete the query hint.such as /*+ full(alias )*/

**Comment by laurenz** [comment]
Yes. PostgreSQL does not know query hints like Oracle does, so the PostgreSQL parser will remove any such commenty even before oracle_fdw becomes involved.

If you *really* want hints with your Oracle query, you could define a foreign table on a `SELECT` statement:

    CREATE FOREIGN TABLE ... OPTIONS (table '(SELECT /* your hint */ ...)');

**Comment by peixubin** [comment]
OK,thanks.
