### ISSUE TITLE
PostgreSQL 10 support

### ISSUE THREAD

**Issue by kimjand** [laurenz/oracle_fdw#198]
Do you currently have any plans for supporting PG10? 
I have attempted to build oracle_fdw against PG10 beta3, but there seems to be a number of breaking changes: libpq/md5.h moved to common/md5.h and apparently ExecEvalExpr changed its footprint:
`oracle_fdw.c: In function ‘setSelectParameters’:
oracle_fdw.c:5038:12: error: too many arguments to function ‘ExecEvalExpr’
    datum = ExecEvalExpr((ExprState *)(param->node), econtext, &is_null, NULL);`

I did not try to go any further than that.

**Comment by laurenz** [comment]
You'll have to use the latest development version (get it with git or download [here](https://github.com/laurenz/oracle_fdw/archive/master.zip)) to build against PostgreSQL v10.

**Comment by kimjand** [comment]
Great, thanks! Works perfectly against PG10-Beta3 so far.

Fra: Laurenz Albe [mailto:notifications@github.com]
Sendt: 6. september 2017 12:06
Til: laurenz/oracle_fdw <oracle_fdw@noreply.github.com>
Cc: Kim Johan Andersson <kian@uddata.dk>; Author <author@noreply.github.com>
Emne: Re: [laurenz/oracle_fdw] PostgreSQL 10 support (#198)


You'll have to use the latest development version (get it with git or download here<https://github.com/laurenz/oracle_fdw/archive/master.zip>) to build against PostgreSQL v10.
