### ISSUE TITLE
ORA-08177: can't serialize access for this transaction

### ISSUE THREAD

**Issue by bsislow** [laurenz/oracle_fdw#200]
Hello,

I saw some closed cases that refer to this issue but our scenario seems to be different.

PG - 9.6.3
oracle_fdw - 1.5.0
Oracle - 12.2.0.1.0

The target Oracle database table is not accessed by *anything* except my testing which involves the INSERT below. Why would it only work occasionally as shown below? The behavior is very sporadic.

```
modelpgp=> select count(*) from model_data_test_data;
 count
--------
 135247
(1 row)
modelpgp=> insert into model.test2 select * from model_data_test_data limit 1000;
ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-08177: can't serialize access for this transaction
modelpgp=> insert into model.test2 select * from model_data_test_data limit 1000;
ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-08177: can't serialize access for this transaction
modelpgp=> insert into model.test2 select * from model_data_test_data limit 1000;
ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-08177: can't serialize access for this transaction
modelpgp=> insert into model.test2 select * from model_data_test_data limit 1000;
INSERT 0 1000
modelpgp=> insert into model.test2 select * from model_data_test_data limit 1000;
INSERT 0 1000
modelpgp=> insert into model.test2 select * from model_data_test_data limit 1000;
ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-08177: can't serialize access for this transaction
modelpgp=> insert into model.test2 select * from model_data_test_data limit 1000;
ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-08177: can't serialize access for this transaction
modelpgp=> insert into model.test2 select * from model_data_test_data limit 1000;
INSERT 0 1000
modelpgp=> insert into model.test2 select * from model_data_test_data limit 1000;
ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-08177: can't serialize access for this transaction

```

More info:

```
modelpgp=> \d model_data_test_data
            Table "model.model_data_test_data"
      Column       |           Type           | Modifiers
-------------------+--------------------------+-----------
 id                | bigint                   | not null
 uuid              | uuid                     |
 virtual_table_id  | bigint                   | not null
 model_id          | character varying(50)    | not null
 model_version     | smallint                 | not null
 model_type        | character varying(10)    | not null
 transaction_id    | character varying(128)   | not null
 data_header_id    | bigint                   |
 execution_ts      | timestamp with time zone | not null
 value_fetch_time  | bigint                   |
 xform_time        | bigint                   |
 execution_time    | bigint                   |
 model_probability | double precision         | not null
 model_score       | double precision         |
 raw_inputs        | jsonb                    |
 model_xforms      | jsonb                    |
 reason_codes      | jsonb                    |
 error_code        | character varying(50)    |
 error             | character varying(750)   |
 host              | character varying(50)    |

modelpgp=> \d test2
                      Foreign table "model.test2"
      Column       |           Type           | Modifiers | FDW Options
-------------------+--------------------------+-----------+-------------
 data_header_id    | bigint                   |           |
 error             | character varying        |           |
 error_code        | character varying        |           |
 execution_time    | character varying        |           |
 execution_ts      | smallint                 | not null  |
 host              | character varying        |           |
 id                | character varying        | not null  |
 model_id          | character varying        | not null  |
 model_probability | timestamp with time zone | not null  |
 model_score       | double precision         |           |
 model_type        | character varying        | not null  |
 model_version     | smallint                 | not null  |
 model_xforms      | text                     |           |
 raw_inputs        | text                     |           |
 reason_codes      | text                     |           |
 transaction_id    | character varying        | not null  |
 uuid              | character varying        |           |
 value_fetch_time  | character varying        |           |
 virtual_table_id  | character varying        | not null  |
 xform_time        | character varying        |           |
Server: dwdb01
FDW Options: (schema 'DDOWNER', "table" 'MODEL_DATA')
```

**Comment by bsislow** [comment]
This seems to be resolved by using:
SEGMENT CREATION IMMEDIATE
in the Oracle table DDL.

**Comment by laurenz** [comment]
If you have a new Oracle table defined *without* `SEGMENT CREATION IMMEDIATE`, the *first* `INSERT` will cause this error, as described in the README.

But subsequent `INSERT`s should work fine, so the behaviour you show above is not explained by this.

Is there anything unusual about the Oracle table that would require new segments to be created repeatedly?

**Comment by bsislow** [comment]
I do not understand your prior question about "Is there anything unusual about the Oracle table that would require new segments to be created repeatedly?"... can you explain exactly what you mean?

Again, the only component that acts against this Oracle table is inserts from the FOREIGN TABLE from PostgreSQL.

We have now been running batches of inserts using oracle_fdw and the FOREIGN TABLE for a couple of days - batching about 10000 rows every 15 minutes via cronjob.

The job failed today with the ORA-08177 error. The job has executed well over 50 times and we all of a sudden hit this error.

Again, the Oracle table was created with SEGMENT CREATION IMMEDIATE. This *seemed* to to help but alas, we still hit the error *randomly* on a later execution.

Is the only workaround to build in retry logic? Is there a better way to circumvent this issue?

Thanks.

**Comment by bsislow** [comment]
Can't you modify the behavior of the oracle_fdw tool or at least offer an option to isolate the transaction level differently?

https://stackoverflow.com/questions/785765/ora-08177-cant-serialize-access-for-this-transaction

**Comment by bsislow** [comment]
We have retried the same batch that failed 10 times and - 10 times we have gotten the ORA-08177 error. We cannot proceed. Please advise based on my recent posts... what else do you need to diagnose this?

**Comment by bsislow** [comment]
The amount of rows we're trying to insert at this point: 80349.

If we try to insert only 25 rows (subset of the batch), it works! WHY?!?!?!

modelpgp=# insert into ..... where id > XXX and id <= YYY;
INSERT 0 25

Why does the quantity matter?

**Comment by laurenz** [comment]
When I ask if there is anything unusual about the Oracle table that would require new segments to be created repeatedly, I'm only fishing for clues. It's just that the only circumstance where I have seen that behaviour is when a table is created that has no segment yet.

oracle_fdw needs `SERIALIZABLE` transactions because it is possible that it has to issue several Oracle queries to satisfy a single PostgreSQL query (e.g. if a foreign table is scanned in the inner loop of a nested loop join). All these queries have to see the same snapshot of the database. So nothing short of `SERIALIZABLE` will do.

I just searched the Oracle knowledge base, and I've seen a few cases where this or a similar behaviour is called &ldquo;working as expected&rdquo; (see for example document 160593.1 and &ldquo;not a&rdquo; bug 2495132):
If the table has an index and several concurrent serializable transactions insert rows, it can happen that an index page is split, and if one of the transactions tries to re-read the values, a serialization error will happen.

Could this be what happens in your case? Are there several sessions inserting at the same time? Is there an index (probably yes)?

If that is indeed your problem, you are hitting an Oracle &ndash; er &ndash; feature.

For clarification it would be the best to ask Oracle. They can tell you if your problem is the one described above or something else. It does not look like oracle_fdw is doing something wrong here, does it?

**Comment by bsislow** [comment]
Good call on the indexes being an issue - we will keep an eye on this. We believe that is the cause.

You can close this out - we will follow up with an Oracle case on how to handle this.

Thank you for your detailed explanation and help.
