### ISSUE TITLE
build error with fedora 

### ISSUE THREAD

**Issue by volkmarbuehringer** [laurenz/oracle_fdw#203]
this required library does not exists with fedora 

gcc: Fehler: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
make: *** [<eingebaut>: oracle_fdw.o] Fehler 1

**Comment by laurenz** [comment]
A web search suggests that installing the `redhat-rpm-config` RPM should get rid of that error.

**Comment by laurenz** [comment]
Funny, I just had the same error on Fedora 25, and verified that this is the solution.
I'll close the issue.
