### ISSUE TITLE
Tuning oracle_fdw

### ISSUE THREAD

**Issue by bsislow** [laurenz/oracle_fdw#204]
Hello,

Can you explain if it is possible to make oracle_fdw perform with minimal impact and if it batches operations?

We attempted to deploy it in production to INSERT PostgreSQL (9.6.2) values into Oracle (11.2) and it created latency on the PostgreSQL side. The INSERT being done into the FOREIGN TABLE is via trigger. We are sure the trigger is causing the latency.

The trigger appears as such:

```
CREATE TRIGGER trig
    AFTER INSERT
    ON table
    FOR EACH ROW
    EXECUTE PROCEDURE func();
```

The underlying function is as such:

```
CREATE FUNCTION func()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF 
    ROWS 0
AS $BODY$

BEGIN 
INSERT INTO foreign_table (col1,col2,col3.......) 
VALUES (NEW.abc, NEW.xyz, ......); 

RETURN NEW; 
END; 

$BODY$;
```

**Comment by laurenz** [comment]
I think there is no better way to do it with a trigger `FOR EACH ROW`.
In PL/pgSQL the statement plan will be cached, so you'll have as little overhead as possible.
Still, there is always a round trip between PostgreSQL and Oracle for each row, no way around that.

You should try to measure where the time is spent.
If it is on the network, there's not much you can do.
If it is on the Oracle side (unlikely), then batching several PostgreSQL `INSERT`s into a transaction might help (then it will also be a single transaction in Oracle).

If there is no way you can make the performance acceptable with a trigger, you could also have a regular batch job that `INSERT`s all new rows in the foreign table. That way you can at least speed up the PostgreSQL `INSERT`s.

Of course then the Oracle data would not be updated immediately.

**Comment by bsislow** [comment]
Thanks, we were planning on a batch job which inserts into the FT on a regular basis.

You can close this case, thank you again.
