### ISSUE TITLE
Getting TNS error 12514

### ISSUE THREAD

**Issue by gchaika** [laurenz/oracle_fdw#207]
Hello,

I've setup a test of the Oracle_FDW for postgres.  I've installed postgres 9.6 server and Oracle 12.2.0 database on the same Redhat6 server(vm).

I've configured your extension, compiled it and followed your instructions but when I go to run:

SELECT * from public.oratab I get the ORA-12514 error.  I'm guessing I have some error in the configuration of the foreign table but I'm pulling my hair out.  

Any thoughts?

**Comment by gchaika** [comment]
My foreign database (oracle) is configured as follows:

![image](https://user-images.githubusercontent.com/17831663/31353156-6ed6a926-acff-11e7-9e35-d8c98fe5dfe4.png)

**Comment by laurenz** [comment]
You should use `OPTIONS (dbserver 'TESTDB')` for the foreign server.

Or if you want a local connection bypassing the listener, set `ORACLE_SID=TESTDB` in the environment of your PostgreSQL server process (that needs a server restart) and use `OPTIONS (dbserver '')`.

**Comment by gchaika** [comment]
It worked!  Thanks for getting back to me so quickly and double thanks for writing this extension.

We're looking to move our databases off of Oracle to Postgres and this will help.
