### ISSUE TITLE
How to set ORACLE_HOME for postgres?

### ISSUE THREAD

**Issue by sarfarazm** [laurenz/oracle_fdw#208]
I have installed the plugin and have reached a point where I could create a foriegn table. But when I try to query this table, I get the following error: 
`ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle`

I went through the following issue where this exact issue is discussed:
**OCIEnvCreate failed to create environment handle. #133**

The thing is that I am not able to set the env variable for ORACLE_HOME. Below is the command to check the env and the corresponding output:

```
:$ sudo cat /proc/4885/environ | xargs -0 -n 1 echo | sort
LANG=en_IN
PGDATA=/var/lib/postgresql/9.6/main
PG_GRANDPARENT_PID=4880
PGLOCALEDIR=/usr/share/locale
PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj
PGSYSCONFDIR=/etc/postgresql-common
PWD=/
```
I have tried to export this variable in all possible places but to no avail. I refered the following threads:

https://unix.stackexchange.com/questions/117467/how-to-permanently-set-environmental-variables/117470

http://www.linuxtopia.org/online_books/database_guides/Practical_PostgreSQL_database/PostgreSQL_x486_007.htm

Thus I have added env variables in the following files:
(after loging in as postgres using **sudo su postgres**)
~/.bashrc
~/.bash_profile
~/.bash_login
~/.login
~/.profile
/etc/profile

In all of these files I have the following line:
`export ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe/
`

Am I missing something here?

PS: I am on Ubuntu 17.10 using Postgres 9.6

**Comment by sarfarazm** [comment]
Solved here: 
https://stackoverflow.com/questions/46972168/postgressql-set-environment-variables/46973364#46973364

**Comment by laurenz** [comment]
Your environment variables only get set in shells.

The solution is to either set the environment variable in the startup script or to start PostgreSQL from the shell with `pg_ctl start`.
