### ISSUE TITLE
error ORA-00904: invalid column name during import schema with Oracle 8.1.7 version

### ISSUE THREAD

**Issue by legrandlegrand** [laurenz/oracle_fdw#209]
Hello,
I get error

```
IMPORT FOREIGN SCHEMA "XXXX" LIMIT TO(tttttt) FROM SERVER sssssss INTO sssssss

org.postgresql.util.PSQLException: ERREUR: error importing foreign schema: OCIStmtExecute failed to execute column query
  Détail : ORA-00904: invalid column name
```

Is there a work arround ?

Thanks in advance
Regards
PAscal

**Comment by laurenz** [comment]
What is the output of

    SELECT oracle_diag('name_of_foreign_server');

What do you get if you run the following with sqlplus:

    SELECT col.table_name, col.column_name, col.data_type, col.data_type_owner,
            col.char_length, col.data_precision, col.data_scale, col.nullable,
            CASE WHEN primkey_col.position IS NOT NULL THEN 1 ELSE 0 END AS primary_key
     FROM all_tab_columns col,
          (SELECT con.table_name, cons_col.column_name, cons_col.position
           FROM all_constraints con, all_cons_columns cons_col
           WHERE con.owner = cons_col.owner AND con.table_name = cons_col.table_name
             AND con.constraint_name = cons_col.constraint_name
             AND con.constraint_type = 'P' AND con.owner = 'schema_name') primkey_col
     WHERE col.table_name = primkey_col.table_name(+) AND col.column_name = primkey_col.column_name(+)
       AND col.owner = 'schema_name'
     ORDER BY col.table_name, col.column_id;

This is the Oracle query that oracle_fdw runs, you'll have to replace `schema_name` with the actual schema name.

**Comment by legrandlegrand** [comment]
A quick search in oracle 8i documentation at https://docs.oracle.com/cd/A87860_01/doc/index.htm
tells that **char_length** isn't in **all_tab_columns**
in fact syntax **varchar2(n char)** wasn't supported in that version ;o(

In this case **char_length** should be replaced by **data_length** or **char_col_decl_length**.

I'll have access to that Oracle system into 2 days and will try to create a custom view **all_tab_columns** with the missing column.

Thanks for your help
Regards
PAscal

**Comment by laurenz** [comment]
So this is 8i.

I have documented the problem, but I think that it is not trivial to fix; I would have to write a different query for Oracle 8i.

I'm reluctant to fix a problem with such an old release if it is complicated.

Your workaround should be fine in you create ALL_TAB_COLUMNS in the current schema. That is a smart idea!

**Comment by Kitzi** [comment]
Hi Laurenz, 

I get the same oracle error code when trying to select from a foreign table I just created:

ERROR:  error describing remote table: OCIStmtExecute failed to describe table
DETAIL:  ORA-00904: "foo_bar_foo": invalid identifier
SQL state: HV00M

Some days ago the query just returned the desired results.

**Comment by laurenz** [comment]
That is quite a different problem, even if it is the same oracle error number.

Please open a new issue for that and include the following information:

- Result of `SELECT oracle_diag('your foreign_server');`

- `CREATE TABLE` statement for the Oracle table.

- ` CREATE FOREIGN TABLE` statement for the PostgreSQL foreign table.

**Comment by legrandlegrand** [comment]
to prevent 
ORA-01731: circular view definition encountered

I had to create the view with an other name with a synonym like

```
create view my_all_tab_columns
as
SELECT
    tc.OWNER,
    tc.TABLE_NAME,
    tc.COLUMN_NAME,
    tc.COLUMN_ID,
    tc.NULLABLE,
    tc.DATA_TYPE,
    tc.DATA_TYPE_OWNER,
    tc.DATA_LENGTH as CHAR_LENGTH,
    tc.DATA_PRECISION,
    tc.DATA_SCALE
FROM    DBA_TAB_COLUMNS tc
;

create synonym all_tab_columns for my_all_tab_columns
;
```
