### ISSUE TITLE
Geometries with SDO_ETYPE = 0

### ISSUE THREAD

**Issue by laurenz** [laurenz/oracle_fdw#21]
@vmora, I just got a problem report by somebody who uses this Oracle geometry:

    MDSYS.SDO_GEOMETRY(
       2001,2193,NULL,
       MDSYS.SDO_ELEM_INFO_ARRAY(1,0,6000,4,1,1),
       MDSYS.SDO_ORDINATE_ARRAY(1,0,0,1803127,5801479)
    )
This causes the following error message:

    ERROR:  error converting SDO_GEOMETRY to geometry: unsupported etype 0 with interpretation 6000 in elem_info
That is fundamentally OK because according to [the documentation](http://docs.oracle.com/cd/E11882_01/appdev.112/e11830/sdo_objrelschema.htm#BGHDGCCE "Values and Semantics in SDO_ELEM_INFO") a value of 0 means
> Type 0 (zero) element. Used to model geometry types not supported by Oracle Spatial.*

But [later on](http://docs.oracle.com/cd/E11882_01/appdev.112/e11830/sdo_objrelschema.htm#SPATL537 "Type 0 (Zero) Element") I read:
> Geometries with type 0 elements must contain at least one nonzero element, that is, an element with an SDO_ETYPE value that is not 0. The nonzero element should be an approximation of the unsupported geometry, and therefore it must have both:
> 
> * An SDO_ETYPE value associated with a geometry type supported by Spatial
> * An SDO_INTERPRETATION value that is valid for the SDO_ETYPE value (see Table 2-2)

Wouldn't the correct thing be to skip the part with ETYPE = 0 and use the approximation instead?
In this case it would be a point.

**Comment by vmora** [comment]
Hi @laurenz,

This looks more like a corner case than a major issue, I'll try and fix that as soon as I can, but I'm under some strain at the moment, so it may have to wait until summer unless something bumps the priority.

**Comment by laurenz** [comment]
Thanks, that's good enough; as you said, it is a corner case.
I'll let you know if it gets urgent; alternatively I can try and have a go at it.

**Comment by laurenz** [comment]
I have created pull request #32 that should implement this.

Could you have a look at it and tell me if it looks sane to you?
I tried to mess with your code as little as possible.

My first idea was to preprocess the collections in the SDO_GEOMETRY object itself, but (like everything else) this is rather difficult in OCI, so I had the idea of extracting the collections, preprocessing them and storing the result in some cache fields in `struct ora_geometry`.

**Comment by laurenz** [comment]
Thanks for your feedback, I have merged the commit.
