### ISSUE TITLE
Query : oracle_fdw support on Redhat Software Collection Libraries

### ISSUE THREAD

**Issue by venkatsusarla** [laurenz/oracle_fdw#213]
Hi Laurenz,
Firstly,I would like to thankyou for the wonderful tool with great efforts!!!

I have a query:

We have RHSCL license and if i use oracle_fdw to connect to oracle database from postgres,will Redhat support this?

-Venkat

**Comment by laurenz** [comment]
I searched for a RHSCL license, but couldn't find it.

oracle_fdw, which has a liberal license, imposes no legal burden on its users.

I cannot speak for RHEL, so you'd have to ask them.
