### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by ymucahit** [laurenz/oracle_fdw#214]
I am doing some experiments on foreign data wrappers for my company. We are just before the decision on using wrappers or not. I have a big question about joins on the foreign server. When monitoring Postgres server CPU usage, while executing the query like 
```
select * from a 
inner join b on a.x = b.x
```
it becomes %90-%100. As far as i assume, it pulls the data into Postgres server and then joins it. However, both a and b foreign tables are located in the same Oracle server. Is there a way to run this join operation on the remote database? By the way, defining this join as a separate table and then to the Postgres as foreign server doesn't work for my requirement. 

Again count queries on a single table is also a problem. 
`
select count(*) from a
`
It increases the CPU usage to %80s. 

I am looking for a configuration or some optimization to run such queries on remote server.

**Comment by laurenz** [comment]
You should use the latest release 2.0.0 which has pushdown for inner joins.

There is no pushdown for aggregates (yet), so the `count(*)` case will have to pull the whole table to PostgreSQL.

If you have problems pushing down joins, please post the output of `EXPLAIN (ANALYZE) SELECT ...`.

**Comment by HipDragon** [comment]
Is there a reason why inner joins push downs are limited to the first 3 tables? Any chance to increase that number?

**Comment by laurenz** [comment]
Currently only two-way joins (joins between two tables) can be pushed down to Oracle. This is not limited to the first three tables in the query though.

Enabling push down of joins of more than two tables will require substantial additions to oracle_fdw, but it is on the radar.

**Comment by HipDragon** [comment]
Thanks, i thought it was limited to three inner joins due to the documentation "Joins between three or more tables won't be pushed down."

**Comment by laurenz** [comment]
I'll close this issue, feel free to reopen it if things remain unclear.
