### ISSUE TITLE
parallel query in 9.6.6 + oracle_fdw -> ERROR: invalid cache ID: 41

### ISSUE THREAD

**Issue by chris-mair** [laurenz/oracle_fdw#215]
Hi,

I've found a problem in either PostgreSQL 9.6.6 or oracle_fdw 2.0.0. I've posted the details
on the Postgres general mailing list and a link here:

https://www.postgresql.org/message-id/96420364a3d055172776752a1de80714%40smtp.hushmail.com

Let me know if there's any additional tests I can do...

Thanks :) 
Chris.

**Comment by chris-mair** [comment]
Replying to myself:

apparently the problem is in oracle_fdw.c, where _PG_init() calls SearchSysCacheList() - see
Tom Lane's reply:

https://www.postgresql.org/message-id/11960.1511116873%40sss.pgh.pa.us

Thanks :)
Chris.

**Comment by laurenz** [comment]
Thanks for the report; as usual, Tom's analysis was correct.

Could you test if commit 4accfebb33c316d71da73d341dac796df813638c fixes the problem for you?

**Comment by chris-mair** [comment]
Great!

I'll be able to test this only later today and will report back...

Thanks :)
Chris.

**Comment by chris-mair** [comment]
Hi,

here I am!

I've compiled the Github master, redone my tests and can confirm that
commit 4accfeb fixes  the reported bug.

Thanks :)
Chris.

**Comment by laurenz** [comment]
Thanks for testing.
