### ISSUE TITLE
Symfoware connection Oracle error

### ISSUE THREAD

**Issue by scqlmm** [laurenz/oracle_fdw#216]
errorMessage:do you want to attempt to reconnect to the datebase?

**Comment by laurenz** [comment]
I have never heard of Symfoware.

You'll have to give me way more detail, particularly the error messages from PostgreSQL and how the setup is.

**Comment by yamatattsu** [comment]
Hi, scqlmm,

Symfoware is made by Fujitsu Corp. So, firstly, you might better to ask it
to Fujitsu Corp.

Regards,
Tatsuro Yamada


2017-11-20 17:14 GMT+09:00 Laurenz Albe <notifications@github.com>:

**Comment by laurenz** [comment]
Reopen the issue if any questions remain.
