### ISSUE TITLE
problem with  translation of "where" condition to oracle query

### ISSUE THREAD

**Issue by andrey73594** [laurenz/oracle_fdw#217]
Hello!
I created a foreign table using oracle_fdw and try to get rows from this table with some filters in WHERE section. But I always get all rows from the table (no difference with condtition) and EXPLAIN shows that Oracle query does not contain any conditions.
Example:

    create foreign table req_lot (
       id_req bigint options (key 'true') not null,
       id_lot bigint
    ) server ora_test1 options (schema 'CGT_REQUEST', table 'REQ_LOT');

    insert into req_lot (id_lot,id_req) values (1,2);
    insert into req_lot (id_lot,id_req) values (3,4);

`SELECT * from req_lot WHERE id_req=4 ORDER BY id_req` returns:

    id_req;id_lot
    2;1
    4;3

and `explain (select * from req_lot where id_req=4 order by id_req)` returns:

    Foreign Scan on req_lot  (cost=10000.00..20000.00 rows=1000 width=16)
      Oracle query: SELECT /*0bc601372dc3506bfe5bd9b5cb3dc491*/ r1."ID_REQ", r1."ID_LOT" FROM "CGT_REQUEST"."REQ_LOT" r1

So Oracle Query does not contain WHERE clause and ORDER BY clause!

`SELECT public.oracle_diag('ora_test1')` returns:

    oracle_fdw 2.0.0devel, PostgreSQL 9.6.5, Oracle client 11.2.0.3.0, Oracle server 11.2.0.3.0

Could you give advice what could be wrong?

**Comment by laurenz** [comment]
To answer the question, I'd need to know the definition of the Oracle table.

**Comment by andrey73594** [comment]
CREATE TABLE "CGT_REQUEST"."REQ_LOT" 
   (	"ID_REQ" NUMBER, 
	"ID_LOT" NUMBER, 
	 CONSTRAINT "REQ_PK" PRIMARY KEY ("ID_REQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

**Comment by laurenz** [comment]
It works here!

Oracle:

    CREATE TABLE req_lot (
       id_req number CONSTRAINT req_lot_pkey PRIMARY KEY,
       id_lot number)
    SEGMENT CREATION IMMEDIATE;

PostgreSQL:

    CREATE FOREIGN TABLE req_lot(
       id_req bigint OPTIONS (key 'true') NOT NULL,
       id_lot bigint
    ) SERVER oracle OPTIONS (table 'REQ_LOT');

    INSERT INTO req_lot (id_lot,id_req) VALUES (1,2);
    INSERT INTO req_lot (id_lot,id_req) VALUES (3,4);

    EXPLAIN (COSTS off) SELECT * FROM req_lot WHERE id_req=4 ORDER BY id_req;

                                          QUERY PLAN                                                           
    --------------------------------------------------------------------------------------
     Foreign Scan on req_lot
       Oracle query: SELECT /*16b991a9af57b0f1fe7e6717ffa37c81*/ r1."ID_REQ", r1."ID_LOT"
                     FROM "REQ_LOT" r1 WHERE (r1."ID_REQ" = 4)
    (2 rows)

There is no `ORDER BY` in the Oracle query because the PostgreSQL optimizer removes it &ndash; it is useless with this `WHERE` condition.

Reading your question again, I am surprised why your query returns two rows. It should only return the second row.

Please double check that everything is in order.

**Comment by andrey73594** [comment]
I checked more than double times!
And I have this problem not with only one table, but with all tables that I try to create as foreign tables. And clause WHERE doesn't applied in all type of queries, not only in SELECT, in my example:
 update req_lot set id_lot=44 WHERE id_req=4 
give message "Query returned successfully: 2 rows affected, 15 msec execution time."
and then^
SELECT * from req_lot
returns 
2;44
4;44

**Comment by laurenz** [comment]
That would be really bad.

Can I have the output of

    EXPLAIN UPDATE req_lot SET id_lot=44 WHERE id_req=4;

I notice that your version of oracle_fdw is 2.0.0devel.
Still, I have never seen behaviour like the one you describe. What is the latest commit in the version you are using?
Does anything change if you use the latest version (git HEAD)?

**Comment by andrey73594** [comment]
I get the latest version from this site (with date 13.09.2017), file: oracle_fdw-2.0.0-pg96-win64.zip

EXPLAIN update req_lot set id_lot=45 WHERE id_req=4 
returns:
"Update on req_lot(cost=10000.00..20000.00 rows=1000 width=24)"
"  Oracle statement: UPDATE "CGT_REQUEST"."REQ_LOT" SET "ID_LOT" = :p2 WHERE "ID_REQ" = :k1"
"  ->  Foreign Scan on req_lot (cost=10000.00..20000.00 rows=1000 width=24)"
"        Oracle query: SELECT /*caf9f9fc9e03bf9b0f3f3b4e4f8273f7*/ r1."ID_REQ" FROM "CGT_REQUEST"."REQ_LOT" r1 FOR UPDATE"

**Comment by laurenz** [comment]
You didn't tell me that you were using Windows.

Unfortunately I don't have Windows any more, so I cannot try it.

Strange that the version reported for oracle_fdw is 2.0.0devel, that is wrong.
I must have made a mistake building that binary...

Sorry, but I don't know what to do about it.

**Comment by chrullrich** [comment]
The ORACLE_FDW_2_0_0 tag [builds without "devel"](https://github.com/laurenz/oracle_fdw/files/1491926/oracle_fdw-2.0.0-pgsql-9.6.x64.zip). This one is from Visual Studio 2017, so to test, you'll need the [2017 runtime libraries](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) ("Visual C++ Redistributable") installed.

**Comment by laurenz** [comment]
Thanks. You don't think it is a problem to load a DLL build with Visual Studio 2017 into an executable build with Visual Studio 2013?

**Comment by chrullrich** [comment]
As I wrote in the other bug, this is specifically meant to work, both in Windows in general and PostgreSQL in particular.

**Comment by andrey73594** [comment]
Thank you for advice but Installation of Visual Studio 2017 didn't help.

**Comment by laurenz** [comment]
Even when you used the DLL @chrullrich provided above?

**Comment by andrey73594** [comment]
Yes, version of dll changed ,
select oracle_diag('ora_test') 
returns 
"oracle_fdw 2.0.0, PostgreSQL 9.6.5, Oracle client 11.2.0.3.0, Oracle server 11.2.0.3.0"
but WHERE clause still doesn't work

**Comment by andrey73594** [comment]
The only way I can use this table is using additional VIEW (req_lot is foreign table):
`create view cgt_request.req_lot as with a as (select * from req_lot) select * from a`

After that select from view 
`select *from cgt_request.req_lot where id_req=4`
returns only one row when 
`select *from req_lot where id_req=4` 
still returns all rows from the table.

Main problem in this way is that all data fetched into postgres and then filtered. so if somebody can give advice how to use this foreign tables in normal way it would be very useful for me.

**Comment by laurenz** [comment]
Something must be quite wrong here, and I suspect that it is not oracle_fdw.

What is the output of

    EXPLAIN SELECT * FROM cgt_request.req_lot WHERE id_req=4;

in PostgreSQL?

**Comment by andrey73594** [comment]
`EXPLAIN SELECT * FROM cgt_request.req_lot WHERE id_req=4;`
returns:

"CTE Scan on a  (cost=20000.00..20022.50 rows=5 width=16)"
"  Filter: (id_req = 4)"
"  CTE a"
"    ->  Foreign Scan on req_lot  (cost=10000.00..20000.00 rows=1000 width=16)"
"          Oracle query: SELECT /*0bc601372dc3506bfe5bd9b5cb3dc491*/ r1."ID_REQ", r1."ID_LOT" FROM "CGT_REQUEST"."REQ_LOT" r1"

**Comment by laurenz** [comment]
I give up since I cannot reproduce the problem.

Could you try with a different Oracle table and see if the behaviour is the same?

**Comment by andrey73594** [comment]
I tried with different tables and even different Oracle instances. result is totally the same.

**Comment by chrullrich** [comment]
Where are your PostgreSQL binaries from?

**Comment by andrey73594** [comment]
I use Postgres pro
https://postgrespro.com/products/postgrespro/download/latest

**Comment by laurenz** [comment]
This is a fork of PostgreSQL. If it is not binary compatible with PostgreSQL (which it probably isn't), then it won't work with an oracle_fdw build for standard PostgreSQL.

That would explain the problem.

You could try building oracle_fdw against PostgresPro, but I don't know if that will work.

**Comment by chrullrich** [comment]
[Building works.](https://github.com/laurenz/oracle_fdw/files/1503278/oracle_fdw-2.0.0-postgrespro-9.6-x64.zip) Whether the result is any good as far as WHERE clauses go remains to be seen.

**Comment by chrullrich** [comment]
GitHub doesn't send notifications when comments are edited. This is annoying. Anyway, see edited comment above, please.

**Comment by laurenz** [comment]
Thanks for clarifying this and for providing a binary for @andrey73594!

**Comment by andrey73594** [comment]
Now everything works fine, thank you for help! I didn't think that extension can depend on fork. Can you explain reasons why it works so? PostgresPro overwrite some PostgreSQL libraries that used in extension?

**Comment by chrullrich** [comment]
PostgresPro extend some internal data structures that PostgreSQL uses to represent the parsed query. Since oracle_fdw is compiled using the original, unmodified versions of the structures, it looks in the wrong place when extracting data to assemble the query to be sent to Oracle.

For example:

    --- PostgreSQL\\relation.h	2017-11-21 16:09:33.270934900 +0100
    +++ PostgresPro\\relation.h	2017-11-14 14:27:14.000000000 +0100
    @@ -433,6 +433,19 @@
      *		fdwroutine - function hooks for FDW, if foreign table (else NULL)
      *		fdw_private - private state for FDW, if foreign table (else NULL)
      *
    + * Two fields are used to cache knowledge acquired during the join search
    + * about whether this rel is provably unique when being joined to given other
    + * relation(s), ie, it can have at most one row matching any given row from
    + * that join relation.  Currently we only attempt such proofs, and thus only
    + * populate these fields, for base rels; but someday they might be used for
    + * join rels too:
    + *
    + *		unique_for_rels - list of Relid sets, each one being a set of other
    + *					rels for which this one has been proven unique
    + *		non_unique_for_rels - list of Relid sets, each one being a set of
    + *					other rels for which we have tried and failed to prove
    + *					this one unique
    + *
      * The presence of the remaining fields depends on the restrictions
      * and joins that the relation participates in:
      *
    @@ -533,6 +546,10 @@
        struct FdwRoutine *fdwroutine;
        void	   *fdw_private;
     
    +	/* cache space for remembering if we have proven this relation unique */
    +	List	   *unique_for_rels;	/* known unique for these other relid set(s) */
    +	List	   *non_unique_for_rels;	/* known not unique for these set(s) */
    +
        /* used by various scans and joins: */
        List	   *baserestrictinfo;		/* RestrictInfo structures (if base
                                             * rel) */

I don't have a clue about the inner workings of PostgreSQL's planner/executor, but my guess is that the `baserestrictinfo` contains essentially the WHERE clause. Here, it is shifted back and in its place, the `unique_for_rels` field appears, so oracle_fdw tries to use *it* instead. In your queries, it apparently was always NULL, because otherwise oracle_fdw, in the attempt to read data from an entirely different structure, would most likely have crashed the backend. It would be interesting to see if a schema and query can be constructed that makes this new field non-NULL, just to see the fireworks.

**Comment by laurenz** [comment]
Yes, `baserestrictinfo` contains the `WHERE` conditions for a base table, so your analysis is certainly correct.

Good to know that oracle_fdw works with PostgresPro.

I don't understand why they did not add the new fields at the end of the struct, thus maintaining binary compatibility in this place.
