### ISSUE TITLE
problem with oracle_fwd windows server 2016

### ISSUE THREAD

**Issue by filipposisti** [laurenz/oracle_fdw#218]
Hi laurenz,

i' m trying to use oracle_fdw with Postgresql 9.6 and Windows Server 2016 Essentials.

I experience an error in loading the oracle_fdw.dll while creating the extension. This error has ben widely documented on many posts. Following the procedure documented on git and at https://www.openscg.com/2016/04/how-to-install-and-configure-the-oracle-foreign-data-wrapper/ i can run oracle_fdw on windows 7 /server 2008R2. I found out that using dependencywalker on oracle_fdw some windows\system32\api-ms-*.dll libraries are missing. I cannot find a way to install those dependencies. It seems that i should re-install VC++ 2015 redist. I did it but nothing changes.

Can you help me in finding out how to complete these dependencies?

Thank  you.

**Comment by chrullrich** [comment]
The api-* DLLs are false positives; if they weren‘t there you‘d be having bigger problems. If you‘re using a binary download of oracle_fdw (i.e. have not built it yourself) you need the Visual C++ 2013 redist, not the 2015. 2013 is msvcr120, 2015 is msvcr140.

**Comment by filipposisti** [comment]
removing VC++ 2015 does not resolve . I using process monitor [https://docs.microsoft.com/it-it/sysinternals/downloads/procmon](url) i found out that postgresql.exe is not looking for oci.ddl in one of Oralce paths (Path, TNS_ADMIN,ORACLE_HOME). I did copy oci.dll in c:\windows\system32 and i can register the extension.

Then if i create the oracle server (on pgsql woth oracle_fdw) and query for data on one table i get 

> ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
> DETAIL:  
> 
> ********** Error **********
> 
> ERROR: error connecting to Oracle: OCIEnvCreate failed to create environment handle
> SQL state: HV00N

How can i force postgresql to use the correct paths for oracle?

**Comment by laurenz** [comment]
That won't work.

Remove the copy of `oci.dll` that you made and set the `PATH` environment variable for the PostgreSQL server process so that the directory with the original `oci.dll` is on it.

Also, unless you are using Instant Client, set the `ORACLE_HOME` environment variable for the PostgreSQL server process correctly.

Then restart the PostgreSQL server so that it can pick up the settings.

Then try again.

**Comment by filipposisti** [comment]
Thank you.  How can i 

> set the PATH environment variable for the PostgreSQL server process so that the directory with the original oci.dll is on it.

**Comment by laurenz** [comment]
PostgreSQL, like every other process in Windows, looks for DLLs on the PATH.

Setting environment variables on Windows is a [well-known procedure](http://lmgtfy.com/?q=Windows+%22set+environment+variable%22).

If PostgreSQL is running as service, restart the service. That should do the trick.

**Comment by filipposisti** [comment]
ok, sorry for the dumb question, but i prefer to be sure. I did it before, this is the list of entries in PATH variable for my windows config
![image](https://user-images.githubusercontent.com/28946912/33131146-f0b67436-cf95-11e7-8987-784734f0276b.png)

and the content of instantclient_11_2

![image](https://user-images.githubusercontent.com/28946912/33131224-2c8764fc-cf96-11e7-85b5-ef3f64535222.png)

**Comment by chrullrich** [comment]
Oh, looks like it's another one of the "pg96"s. Check the last post on bug #160, please; it may well apply to you.

**Comment by laurenz** [comment]
I found a number of interesting ideas with a web search for "windows environment variable service".

Setting the "system" environment variables and rebooting the machine should do the trick in any event.

**Comment by laurenz** [comment]
@chrullrich: we don't even get to initialize Oracle here, so while that problem may wait in the future, we have to solve the PATH problem first.

**Comment by chrullrich** [comment]
#160 _was_ a PATH problem. Better yet, the page @filipposisti linked to about installing oracle_fdw has a link to another article about installing the exact PostgreSQL distribution ("Postgres by BigSQL") that had the service startup script overriding the PATH that #160 was about. It's a guess on my part that they're using that distribution, but I'm sticking to it for now :-).

**Comment by filipposisti** [comment]
i can confirm PostgreSQL by BIGSQL. The strange thing is that on Windows 7 /2008R2 everything works without editing .bat file.

**Comment by laurenz** [comment]
@chrullrich you were right of course. As usual :^)
