### ISSUE TITLE
centos 7 systemd environment variables

### ISSUE THREAD

**Issue by tsykes** [laurenz/oracle_fdw#22]
I am having trouble with the environment variables running postgres 9.3 on CentOS 7. When I start the database with pg_ctl, the Oracle environment variables are set appropriately and the foreign data wrapper works. When I start the database from systemctl then I get the following error: 

ERROR:  could not load library "/usr/pgsql-9.3/lib/oracle_fdw.so": libclntsh.so.11.1: cannot open shared object file: No such file or directory

I may not have the best solution, but I was able to resolve the issue by removing the environment variable references from new environment variables... 

So,  I changed the following 
Environment=PGDATA=/var/lib/pgsql/9.3/data/
Environment=ORACLE_VERSION=11.2
Environment=ORACLE_HOME=/usr/lib/oracle/${ORACLE_VERSION}/client64
Environment=PATH=$PATH:${ORACLE_HOME}/bin
Environment=LD_LIBRARY_PATH=${ORACLE_HOME}/lib
Environment=TNS_ADMIN=${ORACLE_HOME}/network/admin

To 
Environment=PGDATA=/var/lib/pgsql/9.3/data/
Environment=ORACLE_VERSION=11.2
Environment=ORACLE_HOME=/usr/lib/oracle/11.2/client64
Environment=PATH=$PATH:/usr/lib/oracle/11.2/client64/bin
Environment=LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib
Environment=TNS_ADMIN=/usr/lib/oracle/11.2/client64/network/admin

Hope this helps someone.

**Comment by laurenz** [comment]
This is normal behaviour in UNIX.
Environment variables are taken as they are and not subjected to shell expansion.

**Comment by tsykes** [comment]
Hi - Do you know is this is an issue with the pgxn client which did the install? I'd love to be able to install on future servers without having to manually modify the systemd config.

**Comment by laurenz** [comment]
I don't think that the pgxn client will set any Oracle environment variables.
How did you install Oracle client? Maybe the bad settings originate from there.

How are the environment variables set?
It would be quite OK to e.g. have the following in /etc/profile:

    export ORACLE_VERSION=11.2
    export ORACLE_HOME=/usr/lib/oracle/${ORACLE_VERSION}/client64
That would in fact set `ORACLE_HOME` to `/usr/lib/oracle/11.2/client64`.

But it is a problem if you get this:

    $ echo $ORACLE_HOME
    /usr/lib/oracle/${ORACLE_VERSION}/client64

**Comment by jgoux** [comment]
Hello,
I have this issue too.
My installation of the instant client is fine (I can run sqlplus without issues).
My main issue is that I don't know how to launch the postgresql server to keep the environment variables ($ORACLE_HOME, $LD_LIBRARY_PATH).
Launching postgresql as the `postgres` user with the `pg_ctlcluster 9.5 main start` doesn't work, I have the error : 
`ERROR:  could not load library "/usr/lib/postgresql/9.5/lib/oracle_fdw.so": libclntsh.so.11.1: cannot open shared object file: No such file or directory`
No success with the `sudo service postgresql start` either.

**Comment by laurenz** [comment]
``.bash_profile`` and friends won't help you as they only set the environment of interactive shells.

I don't know how Debian's startup scripts work, but you'd probably have to modify the PostgreSQL startup script if you want ``LD_LIBRARY_PATH`` or other environment variables set for PostgreSQL.

As for the shared library path, the preferred option on Linux is to edit ``/etc/ld.so.conf`` and run ``ldconfig`` to change the system-wide library load path to include the Oracle library directories.

**Comment by jgoux** [comment]
@laurenz The `/etc/ld.so.conf` did the trick ! :+1: 
Thanks *a lot* !!!
I read a lot of installation steps for the instant client, and it's the first time that someone mention `ldconfig`, so I search again with this instruction, and I found this link which is more or less everything I did for Debian/Ubuntu : http://webikon.com/cases/installing-oracle-sql-plus-client-on-ubuntu
Maybe we could include it in the wiki ?

**Comment by laurenz** [comment]
Done!
