### ISSUE TITLE
views are not imported at all

### ISSUE THREAD

**Issue by tarkhil** [laurenz/oracle_fdw#220]
oracle=> SELECT oracle_diag();
                                                            oracle_diag
    ---------------------------------------------------------------------------------------------------------------------------
     oracle_fdw 2.1.0devel, PostgreSQL 9.6.6, Oracle client 11.2.0.4.0, ORACLE_HOME=/u01/oracle/product/11.2.4, ORACLE_SID=inf
    (1 row)

IMPORT SCHEMA loads all tables OK, but no views/material views

**Comment by laurenz** [comment]
The README says

>- IMPORT FOREIGN SCHEMA will create foreign tables for all objects found in  ALL_TAB_COLUMNS.  That includes tables, views and materialized views,  but not synonyms.

I just tested it on a view, and it worked as expected.

Does the Oracle user specified in the PostgreSQL user mapping have permissions on the views?

Can you create a reproducible test case, i.e. a list of SQL statements in Oracle and PostgreSQL that demonstrates the problem?

**Comment by tarkhil** [comment]
I've got more interesting effect. All views and material views got 
exported as tables. They are complex, use ROWID and spaghettied very 
much. One day, I'll try to narrow this case, but I won't risk messing 
with production database...


27.11.2017 20:47, Laurenz Albe пишет:

**Comment by laurenz** [comment]
Can you be a little more precise, please?

Do you mean that after IMPORT FOREIGN SCHEMA, the Oracle views show up as foreign tables in your PostgreSQL database?

If yes, than that's working as expected. IMPORT FOREIGN SCHEMA does not export or load the data from Oracle to PostgreSQL, it just creates foreign tables, which &ldquo;forward&rdquo; SQL statements to Oracle and return results to PostgreSQL. The word &ldquo;IMPORT&rdquo; in &ldquo;IMPORT FOREIGN SCHEMA&rdquo; is maybe misleading.

If I misunderstood you, please clarify, perhaps with some examples.

**Comment by tarkhil** [comment]
So even if I see _it_ as a table, it's a view? How releiving! I guess it 
should be stated clear in docs.


27.11.2017 22:22, Laurenz Albe пишет:

**Comment by laurenz** [comment]
The README supposes that you have read the PostgreSQL documentation on foreign data and understand what a foreign table is, so it doesn't explain the concept.

It must be the client you are using that shows foreign tables as tables. `psql` doesn't:

    test=> \det log
     List of foreign tables
     Schema | Table | Server 
    --------+-------+--------
     lau    | log   | ora2
    (1 row)

    test=> \dt log
    Did not find any relation named "log".

    test=> \d log
                                    Foreign table "lau.log"
     Column  |            Type             | Collation | Nullable | Default | FDW options  
    ---------+-----------------------------+-----------+----------+---------+--------------
     logdate | timestamp without time zone |           | not null |         | (key 'true')
     message | character varying(4000)     |           | not null |         | 
    Server: ora2
    FDW options: ("table" 'LOG')
