### ISSUE TITLE
centos7 - pgsql10 - oracle_fdw2.1 - error

### ISSUE THREAD

**Issue by barisand** [laurenz/oracle_fdw#221]
Hi Laurenz!

I tried to install your datawrapper to my system: CentOS7 - PostgreSQL10
I used the latest (oracle_fdw-master.zip) version from your Git.

install oracle stuff (12.1)  done.
make, make install - done, no errors:
/usr/bin/mkdir -p '/usr/lib64/pgsql'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/doc/pgsql/extension'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 755  oracle_fdw.so '/usr/lib64/pgsql/oracle_fdw.so'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw.control '/usr/share/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw--1.1.sql ./oracle_fdw--1.0--1.1.sql  '/usr/share/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./README.oracle_fdw '/usr/share/doc/pgsql/extension/'

I put the env_variable to the postgres system unit, the cat /proc/{pid}/environ | xargs -0 -n 1 command gave the values back right. Cool..

PGadmin 4.2 start , connect to the server.
query tool: CREATE EXTENSION oracle_fdw; Run: aaaand error cannot find the oracle_fdw.control.  .. :(
I have found that the pgsql10 extension directory is the /usr/pgsql-10/share/extension not the /usr/share/pgsql/extension/ (as in the installer). I copied the control file and the sql-s to the new place.
Run the  CREATE EXTENSION  command aaaaaand error again: cannot load the oracle_fdw.so.
Wrong directory again: I copied the file to /usr/pgsql-10/lib.
Run the  CREATE EXTENSION  command aaaaaand error again: ERROR:  could not load library "/usr/pgsql-10/lib/oracle_fdw.so": /usr/pgsql-10/lib/oracle_fdw.so: undefined symbol: errcontext
SQL state: XX000
Pfffff  i have no more idea... please help.
thanks
barisand

**Comment by laurenz** [comment]
Thanks for describing your problem so clearly.

You need to build oracle_fdw against the correct PostgreSQL version.

As the README says:

> Make sure that `pg_config` is in the PATH (test with `pg_config --pgxs`).

So you should build with

    PATH=/usr/pgsql-10/bin:$PATH make

to build against your PostgreSQL v10 installation.

**Comment by barisand** [comment]
Hi L!

pg_config --pgxs
/usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk

 echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/lib/oracle/12.1/client64/bin:/usr/pgsql-10/bin:/root/bin

I think these are OK. or NOT?
thx
ba

**Comment by laurenz** [comment]
It is not ok if there is a `pg_config` earlier on the `PATH`.

Try `which pg_config` to find out.

Did you try my advice?

**Comment by barisand** [comment]
I ran your command, but didn't help.

The pg_config command said:
PKGLIBDIR = /usr/lib64/pgsql
LIBDIR = /usr/lib64
PGXS = /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk
VERSION = PostgreSQL 9.2.23
Wrong directories, wrong version???? What? This was a new pgsql installation, the rpm-s from the postgres website....

Now? Any advice?
thx
B

**Comment by chrullrich** [comment]
See if there is a `/usr/pgsql-10/bin/pg_config`, and try that one instead. Otherwise, do what Laurenz suggested and run `which pg_config` to find the one you're actually using, and `rpm -qf (that file)` to find out which package installed it. Most likely you have a `/usr/bin/pg_config` that was installed by your distribution's PostgreSQL 9.2 package.

**Comment by barisand** [comment]
HOOOHOOO  you are awsome Laurenz!!!!!
I try your advice
PATH=/usr/pgsql-10/bin:$PATH make
and after try this
PATH=/usr/pgsql-10/bin:$PATH make install
AND:
usr/bin/mkdir -p '/usr/pgsql-10/lib'
/usr/bin/mkdir -p '/usr/pgsql-10/share/extension'
/usr/bin/mkdir -p '/usr/pgsql-10/share/extension'
/usr/bin/mkdir -p '/usr/pgsql-10/doc/extension'
/usr/bin/install -c -m 755  oracle_fdw.so '/usr/pgsql-10/lib/oracle_fdw.so'
/usr/bin/install -c -m 644 .//oracle_fdw.control '/usr/pgsql-10/share/extension/'
/usr/bin/install -c -m 644 .//oracle_fdw--1.1.sql .//oracle_fdw--1.0--1.1.sql  '/usr/pgsql-10/share/extension/'
/usr/bin/install -c -m 644 .//README.oracle_fdw '/usr/pgsql-10/doc/extension/'
Cool!! Create extension oracle_fdw;  Query returned successfully in 221 msec.   

thanks man!!!!!!
