### ISSUE TITLE
oracle_fdw 2.1.0

### ISSUE THREAD

**Issue by guzik** [laurenz/oracle_fdw#223]
There is 2.1.0 version in changelog, but i can't find it.

-- 
guzik

**Comment by laurenz** [comment]
You will notice that this version does not have a release day yet.
That is because it is not yet released.

To use the latest code, check out HEAD from the `master` branch in the git repository or download https://github.com/laurenz/oracle_fdw/archive/master.zip

**Comment by laurenz** [comment]
2.1.0 has just been released.
