### ISSUE TITLE
connection for foreign table cannot be authenticated (ORA-01017: invalid username/password; logon denied)

### ISSUE THREAD

**Issue by tnaresh43** [laurenz/oracle_fdw#224]
Hello Team,

would you please help us to fix the issue.
masked the data for security issues
The steps followed 
1.  created the extension 

            Name    | Version |   Schema   |              Description
        ------------+---------+------------+----------------------------------------
         oracle_fdw | 1.1     | public     | foreign data wrapper for Oracle access

2. created server

          name    |      owner       |  wrapper   |               options
       -----------+------------------+------------+-------------------------------------
        gspprs    | postgres         | oracle_fdw | {dbserver=xxxxxxxx:1524/yyyy}
        gsprvlprs | postgres         | oracle_fdw | {dbserver=xxxxxxx:1524/yyyy}

`xxx` represents above host name with domain
`yyyy`  represend the ORACLE_SID

3. user mapped

        umid  | srvid |  srvname  | umuser |    usename     |          umoptions
       -------+-------+-----------+--------+----------------+-----------------------------
        20580 | 20578 | gspprs    |  16388 | xxxxxxxx       | {user=xxxxxx,password=xxxxxx}
        20581 | 20579 | gsprvlprs |  16891 | xxxxxxx        | {user=xxxxxx,password=xxxxxxx}

first `xxxx` - postgres username
second `xxxx` - oracle username

4. created foreign table

            Schema     |       Name       |     Type      |     Owner      |  Size   | Description
       ----------------+------------------+---------------+----------------+---------+-------------
        test           | v_instrument_bdr | foreign table | test           | 0 bytes |

but when we do select getting below error

> ERROR:  HV00N: connection for foreign table "v_instrument_bdr" cannot be authenticated
> DETAIL:  ORA-01017: invalid username/password; logon denied

version of postgres

    --------------------------------------------------------------------------------------------------------------
     PostgreSQL 9.5.9 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit
    (1 row)

in oracle database the below parameter has already set

    NAME                                 TYPE        VALUE
    ------------------------------------ ----------- ------------------------------
    os_authent_prefix                    string      ops$
    remote_os_authent                    boolean     TRUE

**Comment by laurenz** [comment]
This is really an Oracle problem and has nothing much to do with oracle_fdw.

You'll have to debug on the Oracle side why the connection fails.

Some notes:

- Are you aware that `remote_os_authent` is deprecated and rather unsafe?

- Do you have an Oracle database user named `ops$postgres` (if PostgreSQL runs as user `postgres`)?

- Is the Oracle user defined as `IDENTIFIED EXTERNALLY`?

- Did you try setting the option `user` in the user mapping to an empty string (so that external authentication is used)?

**Comment by tnaresh43** [comment]
Thanks for the reply

Do you have an Oracle database user named ops$postgres (if PostgreSQL runs as user postgres)?
NO
Is the Oracle user defined as IDENTIFIED EXTERNALLY?
NO
Did you try setting the option user in the user mapping to an empty string (so that external authentication is used)?
NO

**Comment by tnaresh43** [comment]
I fixed the issue its with case sensitive of username and password on user mapping .

now I have one more issue
(postgres@ # select count(*) from V_INSTRUMENT_BDR;
ERROR:  HV00R: Oracle table "PRSNETGSP"."V_INSTRUMENT_BDR" for foreign table "v_instrument_bdr" does not exist or does not allow read access
DETAIL:  ORA-00942: table or view does not exist
HINT:  Oracle table names are case sensitive (normally all uppercase).
LOCATION:  oracleError_ssdh, oracle_fdw.c:5491
Time: 5.793 ms


In oracle Database:

SQL> show user;
USER is "PRSNETGSP"
SQL> select count(*) from V_INSTRUMENT_BDR;

  COUNT(*)
----------
    225589

so the user has select privilege and it is getting data. but the actual owner of the table is different is this giving me the above error?

Note: the table name is in capitals in foreign table creation step

**Comment by laurenz** [comment]
Then it is not surprising if the connection fails, is it?

**Comment by laurenz** [comment]
Maybe the table is in a different Oracle schema?

Try in Oracle:

    SELECT count(*) FROM "PRSNETGSP"."V_INSTRUMENT_BDR";

**Comment by tnaresh43** [comment]
Thanks for your help

looks like permission issue only, I created dummy table in schema PRSNETGSP as select * from base table 
its working fine, need to check why its not working for PRSNETGSP even though its has select privileges on other schema with grant option

**Comment by tnaresh43** [comment]
Hello Team,

all of a sudden I am not able to get the data from foreign table and getting below error.

# select count(*) from v_instrument_bdr;
ERROR:  XX000: could not load library "/opt/rh/rh-postgresql95/root/usr/lib64/pgsql/oracle_fdw.so": libclntsh.so.11.1: cannot open shared object file: No such file or directory
LOCATION:  internal_load_library, dfmgr.c:235
Time: 1.031 ms


\dX
    Name    | Version |   Schema   |              Description
------------+---------+------------+----------------------------------------
 oracle_fdw | 1.1     | public     | foreign data wrapper for Oracle access
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

\dE
     Schema     |        Name        |     Type      |     Owner
----------------+--------------------+---------------+----------------
 xxxxxxxx | v_instrument_bdr   | foreign table | xxxxxxxx

server
   name    |      owner       |  wrapper   |                      options
-----------+------------------+------------+---------------------------------------------------
 gsprvlprs | "xxxxxx" | oracle_fdw | {dbserver=xxxxx:1xx/Pxxx}

user mapping
 umid  | srvid |  srvname  | umuser |    usename     |              umoptions
-------+-------+-----------+--------+----------------+-------------------------------------
 22121 | 22120 | gsprvlprs |  16891 | xxxxx | [null]

# select count(*) from v_instrument_bdr;
ERROR:  XX000: could not load library "/opt/rh/rh-postgresql95/root/usr/lib64/pgsql/oracle_fdw.so": libclntsh.so.11.1: cannot open shared object file: No such file or directory
LOCATION:  internal_load_library, dfmgr.c:235
Time: 1.031 ms

dont know what happened .



evn
cat /proc/7906/environ | xargs -n 1 -0 echo
MANPATH=/opt/rh/rh-postgresql95/root/usr/share/man
PGENV_ASK=NO
HOSTNAME=xxxxxxxxxxxxxxxxxxx
TERM=xterm
SHELL=/bin/ksh
HISTSIZE=1000
LIBRARY_PATH=/opt/rh/rh-postgresql95/root/usr/lib64
PG_GRANDPARENT_PID=31691
CDC_PREW2KHOST=xxxxxxxxxxxxxxxxxx
PG_HOME=/opt/rh/rh-postgresql95/root/usr
CLUSTER_NAME=yyyyyyyyyyyyyyyyyy
COM=/home/postgres/COM
_AST_FEATURES=UNIVERSE - ucb
USER=postgres
PGPORT=5433
LD_LIBRARY_PATH=/opt/rh/rh-postgresql95/root/usr/lib64
CPATH=/opt/rh/rh-postgresql95/root/usr/include
ORD=/home/postgres/ORD
DA_SESSION_ID_AUTH=d06643e4-3f25-8640-bb96-95ff01129f6f
COLUMNS=134
A__z=! PS1="*SHLVL
PATH=/opt/rh/rh-postgresql95/root/usr/bin:/bin:/usr/bin:/usr/local/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/home/postgres/COM
MAIL=/var/spool/mail/postgres
_=*31691*/opt/rh/rh-postgresql95/root/usr/bin/pg_ctl
PWD=/xxxxxxxxxxxxx/postgres/yyyyyyyyyyyyyy/pg_xlog
PGLOCALEDIR=/opt/rh/rh-postgresql95/root/usr/share/locale
FIC=/home/postgres/FIC
SQL=/home/postgres/SQL
LANG=C
USER_PRINCIPAL_NAME=s_fr_postgres@xxxxxxxxxxxxxxxxxxxxx
PGSYSCONFDIR=/etc/opt/rh/rh-postgresql95
PSQLRC=/home/postgres/COM/psqlrc.master
HISTCONTROL=ignoredups
CDC_JOINED_DC=srvpardc0016.eur.msd.world.socgen
SHLVL=1

please help to reslove this

**Comment by tnaresh43** [comment]
ls -lrt /opt/rh/rh-postgresql95/root/usr/lib64/pgsql/oracle_fdw.so
-rwxr-xr-x 1 root root 491633 Nov 30 13:12 /opt/rh/rh-postgresql95/root/usr/lib64/pgsql/oracle_fdw.so

**Comment by laurenz** [comment]
I assume that process 7906 is your PostgreSQL server process.

It looks like `libclntsh.so.11.1` can neither be found in the standard library path nor in `/opt/rh/rh-postgresql95/root/usr/lib64`.

Does &ldquo;all of a sudden&rdquo; mean that there might have been a reboot of the machine?

**Comment by tnaresh43** [comment]
Thanks for the reply, there was a corruption on os due to which the module is not working. unix re-installed it and now its working fine.

**Comment by tnaresh43** [comment]
Thanks for the reply, there was a corruption on os due to which the module is not working. unix re-installed it and now its working fine.
