### ISSUE TITLE
always...   ORA-08177: can't serialize access for this transaction

### ISSUE THREAD

**Issue by jeffery9** [laurenz/oracle_fdw#226]
If we do more quick to insert oracle table, oracle raise  ORA-08177

we run  fdw ... "oracle_fdw 2.0.0, PostgreSQL 9.6.6, Oracle client 12.2.0.1.0, Oracle server 11.2.0.4.0"

**Comment by yamatattsu** [comment]
Hi Jeffery,

As far as I know, oracle_fdw's transaction isolation level is serializable.
So it occurred when your transactions accessed same table at the same time,
maybe.

Regards,
Tatsuro Yamada
2017/12/25 15:30 "Jeffery CHEN Fan" <notifications@github.com>:

**Comment by laurenz** [comment]
The description isn't very clear.

There are two things that come to mind:

1. Concurrent `INSERT`s via oracle_fdw can lead to this error, see [#200](https://github.com/laurenz/oracle_fdw/issues/200#issuecomment-334391025).

2. The first `INSERT` on a newly created table can lead to this error unless you created the table with `SEGMENT CREATION IMMEDIATE`. This is described in the README.

Could you check if either of these might be your problem?
