### ISSUE TITLE
data type definition needed on create foreign table?

### ISSUE THREAD

**Issue by hollladiewaldfee** [laurenz/oracle_fdw#227]
I'm building a PG DB which connects to a lot of oracle DBs and reads out users, segments... for charging.
Therefore I created an oracle user on each DB which has select grants on `V_$*` and `DBA_*` views.

I successfully set up the oracle_fdw, created a foreign server, user mapping...

oracle_diag:

    oracle_fdw 2.0.0, PostgreSQL 10.1, Oracle client 12.2.0.1.0,
    ORACLE_HOME=/oracle/product/12.2.0/client_1/

After creating the foreign table with

    ilv=> create foreign table oraxxx_users ()
          server oradb_xxx options (schema 'SYS', table 'DBA_USERS'); 

I can query it but no data is retuned.

    ilv=> select * from oraxxx_users ;
    (403 rows)

The table definition look like:

    ilv=> \d oraxxx_users
                Foreign table "public.oraxxx_users"
     Column | Type | Collation | Nullable | Default | FDW options 
    --------+------+-----------+----------+---------+-------------
    Server: oradb_xxx
    FDW options: (schema 'SYS', "table" 'DBA_USERS')

Do I have to specify all columns in the create foreign table statement?
I thought the FDW converts the data types.

I tried it with a simpler table.

Without column definition:

    ilv=> create foreign table orarxxx_test ()
          server oradb_xxx options (schema 'CMDB', table 'TEST');
    CREATE FOREIGN TABLE
    ilv=> \d oraxxx_test 
                 Foreign table "public.oraxxx_test"
     Column | Type | Collation | Nullable | Default | FDW options 
    --------+------+-----------+----------+---------+-------------
    Server: oradb_xxx
    FDW options: (schema 'CMDB', "table" 'TEST')

With column definition:

    ilv=> create foreign table oraxxx_test (a numeric)
          server oradb_xxx options (schema 'CMDB', table 'TEST');
    CREATE FOREIGN TABLE
    ilv=> \d oraxxx_test 
                  Foreign table "public.oraxxx_test"
     Column |  Type   | Collation | Nullable | Default | FDW options 
    --------+---------+-----------+----------+---------+-------------
     a      | numeric |           |          |         | 
    Server: oradb_xxx
    FDW options: (schema 'CMDB', "table" 'TEST')

cheers 
Daniel

PS: I still think that the oracle port should be mentioned in the README, it is only working without port if the default port 1521 is used.

    pgdb=# CREATE SERVER oradb FOREIGN DATA WRAPPER oracle_fdw
           OPTIONS (dbserver '//dbserver.mydomain.com:ORAPORT/ORADB');

**Comment by laurenz** [comment]
The foreign tables you define have no columns, so you get one empty result set per Oracle table row.

You either have to define the columns during `CREATE FOREIGN TABLE` or you can add them later with `ALTER FOREIGN TABLE`. Keep in mind that the columns are not mapped to the Oracle columns by name, but rather by position &ndash; the first foreign table column will be mapped to the first Oracle column and so on.

Thank you for the suggestion to mention the Oracle port in the connection string samples. I have modified the README accordingly.
