### ISSUE TITLE
ORA-12541: TNS:no listener

### ISSUE THREAD

**Issue by htecmac** [laurenz/oracle_fdw#229]
Hi Laurenz,

See my SELECT oracle_diag('oraprod');

ERROR:  ERRO:  cannot connect to foreign Oracle server
DETAIL:  ORA-12541: TNS:no listener

**Comment by laurenz** [comment]
This is an Oracle configuration problem: No Oracle listener (the networking component) was found where the Oracle client tried to reach it.

Please show the result of:

    SELECT srvoptions FROM pg_foreign_server WHERE srvname = 'oraprod';

Either something is wrong with the connect string or its resolution, or the Oracle listener at the destination is really not started.

**Comment by laurenz** [comment]
No, the listener is just on the Oracle server, no listener configuration on the client is needed.

Does that connection string work from other machines? Try

    sqlplus user/password@//10.28.96.24/BSC

Does it work if you try to connect from the PostgreSQL server to the Oracle port with `telnet`?

    telnet 10.28.96.24 1521

**Comment by htecmac** [comment]
Ok, result of sqlplus user/password@//10.28.96.24/BSC 
ERROR:
ORA-12541: TNS:no listener

Result  of telnet 10.28.96.24 1521
telnet: connect to address 10.28.96.24: Connection refused

Is it because of the firewall (Windows Server)?

Thank's

**Comment by laurenz** [comment]
That sounds like a good explanation.

You have to be able to reach the Oracle port on the Oracle machine.
