### ISSUE TITLE
What does this error indicate?

### ISSUE THREAD

**Issue by Kitzi** [laurenz/oracle_fdw#237]
I am receiving this error on executing a select on a foreign table. I double-check the definition of the foreign table, everything alright. 
I have several views on that oracle database which I am accessing, only one returns this error. Any ideas why? 

ERROR:  error describing remote table: OCIStmtExecute failed to describe table
DETAIL:  ORA-02070: database DB2X does not support set transaction in this context
ORA-02063: preceding line from FOOBAR
SQL state: HV00M

-- postgres version: 9.5.9

select oracle_diag():
oracle_fdw 1.5.0, PostgreSQL 9.5.9, Oracle client 12.1.0.2.0, ORACLE_HOME=/lfs/oracle/ora12102c, TNS_ADMIN=/lfs/oracle/ora12102c/network/admin

**Comment by laurenz** [comment]
It seems that your Oracle database has a problem serializable transactions.

Is there anything special about this database or the table that you are trying to access? Is it a normal Oracle table?

Aside: with all the problems I see in the context of serializable transaction, I get the feeling that Oracle's support for that isn't all that great.

**Comment by Kitzi** [comment]
It´s a View which contains lots of data (and columns, 77 in total), that´s all I know until now.
I have 5 views on the Oracle Database, the other 4 work just fine.

**Comment by Kitzi** [comment]
I suppose that some part of the view ddl is causing this error. Will continue investigating on Monday.

**Comment by Kitzi** [comment]
It´s very likely! I can tell on Monday. Will follow up here.

**Comment by Kitzi** [comment]
Sorry for getting back to you so late. The problem was that the view was changed and then included a database link to a DB" Database. Works on Oracle, but not on the Postgres with oracle_fdw :)

**Comment by laurenz** [comment]
Yes, this is a known shortcoming of Oracle. Serializable transactions across database links are not supported.

Unfortunately oracle_fdw needs serializable transactions, since it is possible that a foreign scan is executed repeatedly in a single query (e.g. if the foreign scan is on the inner side of a nested loop join), and all these scans have to see the same state of the Oracle database.
