### ISSUE TITLE
oracle_fdw version

### ISSUE THREAD

**Issue by nicodimi** [laurenz/oracle_fdw#238]
Hi Laurenz,

I don't know if you are aware of that, that if you install the oracle_fdw in postgres, you see via "select * from pg_available_extensions" that there is oracle_fdw version 1.1 is installed, though the newest repository was downloaded from github. 
But fortunately it is the 2.0.0 version. It only shows the 1.1 Version.
Is this a mistake in the control file?

**Comment by laurenz** [comment]
See issue #140.

1.1 is the extension version, the version of oracle_fdw can be seen with the `oracle_diag` function.
