### ISSUE TITLE
Oracle FDW issue on amazon aws

### ISSUE THREAD

**Issue by friendarora** [laurenz/oracle_fdw#239]
Script : SELECT oracle_diag();

output is
 "oracle_fdw 2.0.0devel, PostgreSQL 9.6.6, Oracle client 11.2.0.3.0, TNS_ADMIN=C:\app\Administrator\product\11.2.0\client_64\network\admin, TWO_TASK=ORCL"

we are experiencing an adhoc issue on amazon aws cloud environment when executing batch insert from the postgres to oracle using postgres_oracle FDW.

the error is
 Error: error executing query: OCIStmtExecute failed to execute remote queryerror executing query: OCIStmtExecute failed to execute remote queryORA-08177: can't serialize access for this transaction" 
 
After following the forum we have added SEGMENT CREATION IMMEDIATE in the oracle table create
but then also we experience it sometimes and not always

is there anyway to remove this issue completely from our envoronment

**Comment by laurenz** [comment]
This must be the same problem as #200.

> If the table has an index and several concurrent serializable transactions insert rows, it can happen that an index page is split, and if one of the transactions tries to re-read the values, a serialization error will happen.

Simply retry the failed transactions.

**Comment by friendarora** [comment]
we can surely try the failed transaction if we encounter the error

but this process is scheduled to execute after every 12 hrs 
and we cannot have a person check the execution log and re-execute it in case of error

is there a way to completely avoid this error

**Comment by laurenz** [comment]
You'd have to ask Oracle to fix their implementation of serializable isolation level.
oracle_fdw needs `REPEATABLE READ`, which is called `SERIALIZABLE` in Oracle.

I do not suggest that you check manually, but programmatically.
Whenever your `INSERT` gets a serialization error, catch it and retry the transaction.
