### ISSUE TITLE
getting SQL state: 42704 error creating foreign table

### ISSUE THREAD

**Issue by enricofer** [laurenz/oracle_fdw#240]
Hi Laurenz, I'm running postgresql under ubuntu and i'm trying migration with oracle_fdw but I stopped facing an issue creating a foreign table. Could You help me?
I compiled oracle_fwd 1.5 (2.0 was giving me dependencies issues) and succesfully installed extension on my ubuntu. 
Following instructions I create the foreign server:
`CREATE SERVER oradb FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '//10.10.20.100:1521/GDBT');`
I granted user postgres:
`GRANT USAGE ON FOREIGN SERVER oradb TO postgres;`
then I created user mapping:
`CREATE USER MAPPING FOR postgres SERVER oradb OPTIONS (user 'UTENTE', password 'pwd');`
now I'm trying to create a foreing table:
```
CREATE FOREIGN TABLE test 
  (oid integer NOT NULL,id varchar(80),lon numeric,lat numeric,h numeric,descr varchar(80),job varchar(80),shape geometry(Point,3003))
SERVER oradb OPTIONS (table 'TEST');
```
but i'm getting the following error:
```
ERROR: server "oradb" does not exist
SQL state: 42704
```
What am I doing wrong?

note1: I can retrieve foreign server by;
`SELECT srvname,srvoptions FROM pg_foreign_server;`
getting:
`oradb {dbserver=//10.10.20.100:1521/GDBT}`
and foreign connection detail:
`SELECT oracle_diag('oradb')`
getting:
`oracle_fdw 1.5.0, PostgreSQL 9.3.4, Oracle client 12.2.0.1.0, Oracle server 11.2.0.4.0`

note2: I can succefully connect to oracle by sqlplus:
`sqlplus UTENTE/pwd@//10.10.20.100:1521/GDBT`
having access to TEST table:
```
SQL> desc TEST
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 OBJECTID                                  NOT NULL NUMBER(38)
 ID                                                 NVARCHAR2(80)
 LON                                                NUMBER(38,8)
 LAT                                                NUMBER(38,8)
 H                                                  NUMBER(38,8)
 DESC_                                              NVARCHAR2(80)
 JOB                                                NVARCHAR2(80)
 SHAPE                                              SDE.ST_GEOMETRY

```
note3: I'm currently using other foreign tables with postgres_fdw extension

**Comment by laurenz** [comment]
Your `CREATE FOREIGN TABLE` statement uses the foreign server `oradb3`, but the error messages talks about `oradb`, so they don't go together.

Could you post a complete psql session where you run all required SQL statements to reproduce the error? Then I should be able to see what's going on.

**Comment by enricofer** [comment]
I'm feeling stupid, I was working on two consoles on different dbs. Now I can create foreign tables.
Thanks anyway, putting all the queries together I realized the problem....
```
CREATE SERVER oradb FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '//10.10.20.100:1521/GDBT');
GRANT USAGE ON FOREIGN SERVER oradb TO postgres;
CREATE USER MAPPING FOR postgres SERVER oradb OPTIONS (user 'UTENTE', password 'pwd');
CREATE FOREIGN TABLE test(
	oid integer NOT NULL,
	id varchar(80),
	lon numeric,
	lat numeric,
	h numeric,
	descr varchar(80),
	job varchar(80),
	shape geometry(Point,3003)
)
SERVER oradb OPTIONS (table 'TEST');
```
