### ISSUE TITLE
Problems with installation on CentOS 7

### ISSUE THREAD

**Issue by aaitimov** [laurenz/oracle_fdw#242]
Hi, I'm trying to compile Oracle FDW, but I get the following compilation errors:

gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_fdw.o oracle_fdw.c
oracle_fdw.c: In function ‘acquireSampleRowsFunc’:
oracle_fdw.c:3142:9: error: ‘ALLOCSET_SMALL_SIZES’ undeclared (first use in this function)
         ALLOCSET_SMALL_SIZES);
         ^
oracle_fdw.c:3142:9: note: each undeclared identifier is reported only once for each function it appears in
oracle_fdw.c:3142:9: error: too few arguments to function ‘AllocSetContextCreat ’
In file included from oracle_fdw.c:70:0:
/usr/include/pgsql/server/utils/memutils.h:122:22: note: declared here
 extern MemoryContext AllocSetContextCreate(MemoryContext parent,
                      ^
make: *** [oracle_fdw.o] Error 1

---------------

I installed oracle instant client and oracle instant client sdk using rpms from oracle website. 

My PATH env variable:
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/devel/.local/bin:/home/devel/bin:/usr/pgsql-9.5/bin

LD_LIBRARY_PATH:
/usr/lib/oracle/12.1/client64/lib:

And I have the following postgre sql packages installed:

yum list installed | grep postgresql
postgresql.x86_64                     9.2.23-3.el7_4             @updates
postgresql-contrib.x86_64             9.2.23-3.el7_4             @updates
postgresql-devel.x86_64               9.2.23-3.el7_4             @updates
postgresql-libs.x86_64                9.2.23-3.el7_4             @updates
postgresql95.x86_64                   9.5.12-1PGDG.rhel7         @pgdg95
postgresql95-contrib.x86_64           9.5.12-1PGDG.rhel7         @pgdg95
postgresql95-devel.x86_64             9.5.12-1PGDG.rhel7         @pgdg95
postgresql95-libs.x86_64              9.5.12-1PGDG.rhel7         @pgdg95
postgresql95-server.x86_64            9.5.12-1PGDG.rhel7         @pgdg95

---------

I've never compiled and installed postgresql extensions before, so apologies if asking dumb questions

**Comment by aaitimov** [comment]
Nevermind, I cloned master branch and it does not compile. After checking out ORACLE_FDW_2_0_0, everything compiles.

However, I have another problem. I have two PostgreSQL installations 9.2 and 9.5 (and I'm not sure if I can remove 9.2). When I run make install, it installs everything into /usr/lib64/ and /usr/share/pgsql/extension directories. My 9.5 installation uses /usr/pgsql-9.5/ directory, which has bin/, doc/, include/, lib/ and share/ folders. I tried copying files from 9.2 folders to 9.5 folders and run create extension. I get the following error:

ERROR:  could not load library "/usr/pgsql-9.5/lib/oracle_fdw.so": libclntsh.so.12.1: cannot open shared object file: No such file or directory

Can I configure make install to install into 9.5 installation directory?

**Comment by laurenz** [comment]
Concerning your first message: you discovered a bug in the current development version, which should be fixed now.

About the second problem: You cannot use a build made with PostgreSQL 9.2 with a 9.5 installation.
Like the README says:

> Make sure that `pg_config` is in the PATH

So you should run something like

    PATH=/path/to/9.5/installation/bin:$PATH make

**Comment by aaitimov** [comment]
Thanks a lot! I successfully installed the extension.

Had to temporarily move 9.2 installation pg_config to other folder to build the files. Also needed to run "ldconfig" and everything worked.

Thanks again for your help.

**Comment by laurenz** [comment]
Thanks for reporting a bug!
