### ISSUE TITLE
oracle_fdw installation issue: 

### ISSUE THREAD

**Issue by harshitsoni19** [laurenz/oracle_fdw#246]
Hi, 

We are setting up oracle_fdw on psql (9.2.23, server 9.4.13)

ERROR:  could not load library "/opt/sas/viya/home/lib64/postgresql/oracle_fdw.so": /opt/sas/viya/home/lib64/postgresql/oracle_fdw.so: undefined symbol: errcontext

Our postgresql is not installed in default location, we followed the installation instruction step by step as shown below

Upload oracle_fdw-2.0.0 to /opt/sas/viya/home directory

[myuser@myserver bin]$ cd
[myuser@myserver ~]$ cd oracle_fdw-2.0.0/

[myuser@myserver oracle_fdw-2.0.0]$ make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I/opt/oracle/product/12.1.0/client_1/sdk/include -I/opt/oracle/product/12.1.0/client_1/oci/include -I/opt/oracle/product/12.1.0/client_1/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_fdw.o oracle_fdw.c
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I/opt/oracle/product/12.1.0/client_1/sdk/include -I/opt/oracle/product/12.1.0/client_1/oci/include -I/opt/oracle/product/12.1.0/client_1/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_utils.o oracle_utils.c
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I/opt/oracle/product/12.1.0/client_1/sdk/include -I/opt/oracle/product/12.1.0/client_1/oci/include -I/opt/oracle/product/12.1.0/client_1/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_gis.o oracle_gis.c
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -shared -o oracle_fdw.so oracle_fdw.o oracle_utils.o oracle_gis.o -L/usr/lib64 -Wl,-z,relro   -Wl,--as-needed  -L/opt/oracle/product/12.1.0/client_1 -L/opt/oracle/product/12.1.0/client_1/bin -L/opt/oracle/product/12.1.0/client_1/lib -lclntsh -L/usr/lib/oracle/12.2/client/lib -L/usr/lib/oracle/12.2/client64/lib -L/usr/lib/oracle/12.1/client/lib -L/usr/lib/oracle/12.1/client64/lib -L/usr/lib/oracle/11.2/client/lib -L/usr/lib/oracle/11.2/client64/lib -L/usr/lib/oracle/11.1/client/lib -L/usr/lib/oracle/11.1/client64/lib -L/usr/lib/oracle/10.2.0.5/client/lib -L/usr/lib/oracle/10.2.0.5/client64/lib -L/usr/lib/oracle/10.2.0.4/client/lib -L/usr/lib/oracle/10.2.0.4/client64/lib -L/usr/lib/oracle/10.2.0.3/client/lib -L/usr/lib/oracle/10.2.0.3/client64/lib

[myuser@myserver oracle_fdw-2.0.0]$ make install
/usr/bin/mkdir -p '/usr/lib64/pgsql'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/doc/pgsql/extension'
/usr/bin/mkdir: cannot create directory ‘/usr/share/doc/pgsql’: Permission denied
make: *** [installdirs] Error 1

[myuser@myserver oracle_fdw-2.0.0]$ sudo make install
/usr/bin/mkdir -p '/usr/lib64/pgsql'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/opt/sas/viya/home/share/doc/pgsql/extension'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 755  oracle_fdw.so '/usr/lib64/pgsql/oracle_fdw.so'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw.control '/usr/share/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw--1.1.sql ./oracle_fdw--1.0--1.1.sql  '/usr/share/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./README.oracle_fdw '/usr/share/doc/pgsql/extension/'

**I had to run following since postgresql is not installed on assumed location**

[myuser@myserver oracle_fdw-2.0.0]$

sudo /usr/bin/mkdir -p '/opt/sas/viya/home/share/doc/pgsql/extension'
sudo /bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 755  oracle_fdw.so '/opt/sas/viya/home/lib64/postgresql/oracle_fdw.so'
sudo /bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw.control '/opt/sas/viya/home/share/postgresql/extension/'
sudo /bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw--1.1.sql ./oracle_fdw--1.0--1.1.sql  '/opt/sas/viya/home/share/postgresql/extension/'
sudo /bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./README.oracle_fdw '/opt/sas/viya/home/share/doc/pgsql/extension/'

[myuser@myserver oracle_fdw-2.0.0]$ psql SharedServices -U dbmsowner
Password for user dbmsowner:
psql (9.2.23, server 9.4.13)
WARNING: psql version 9.2, server version 9.4.
         Some psql features might not work.
Type "help" for help.

SharedServices=# CREATE EXTENSION oracle_fdw;
_

> ERROR:  could not load library "/opt/sas/viya/home/lib64/postgresql/oracle_fdw.so": /opt/sas/viya/home/lib64/postgresql/oracle_fdw.so: undefined symbol: errcontext

_
SharedServices=#

I would be glad if someone can help me resolve above issue.

Regards,
HS

**Comment by laurenz** [comment]
The problem is that you are using oracle_fdw with a different PostgreSQL (major) version than the one you built it with.

You don't really tell, but it looks like you built oracle_fdw with PostgreSQL 9.2 and tried to run it with PostgreSQL 9.4. That won't work.

The particular symptom that you notice is that in PostgreSQL 9.2, `errcontext` was a function, but in 9.4 it has been changed to a macro.

You'll have to build oracle_fdw with 9.4. For that, you have to make sure that `pg_config` from the 9.4 installation is on the `PATH` before the one from 9.2.
So you should be doing something like this (I am guessing the path):

    make clean
    PATH=/opt/sas/viya/home/bin:$PATH make

**Comment by laurenz** [comment]
Then the path I guessed is probably wrong.

You'll have to find out where the `pg_config` executable from your 9.4 installation is and use that path.

On UNIX systems, you can probably use the following to find all `pg_config`s on your machine:

    locate pg_config

**Comment by harshitsoni19** [comment]
Sorry I didn’t mention that in my comment. I do have correct PATH set and the I confirmed it that pg_config is under /opt/sas/viya/home/bin is from 9.4 install.

Not sure what else to try.

**Comment by laurenz** [comment]
Then it should work. Just run

    make clean
    make

and as user with the correct permissions (root?)

    make install

Please show the output from these commands, as well as the SQL command you typed and the message you got.

**Comment by harshitsoni19** [comment]
Strange, now I started getting a new error: see below

[myuser@myserver oracle_fdw-2.0.0]$ sudo make clean
rm -f oracle_fdw.so   liboracle_fdw.a
rm -f oracle_fdw.o oracle_utils.o oracle_gis.o
rm -rf results/ regression.diffs regression.out tmp_check/ log/
[myuser@myserver oracle_fdw-2.0.0]$ sudo make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_fdw.o oracle_fdw.c
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_utils.o oracle_utils.c
oracle_utils.c:22:17: fatal error: oci.h: No such file or directory
 #include <oci.h>
                 ^
compilation terminated.
make: *** [oracle_utils.o] Error 1

**Comment by laurenz** [comment]
You shouldn't be using `sudo` for `make clean` or `make`, because that will run the commands as user root. Only use it for `make install`, and only if your current user does not have write permissions on the installation directory.

But that's not your problem here.

It is obvious that you did **not** change your `PATH` to contain `/opt/sas/viya/home/bin`, because the build process is still picking up the `pg_config` from your 9.2 installation (`-I/usr/include/pgsql/server -I/usr/include/pgsql/internal`).

Before you had `ORACLE_HOME` set to `/opt/oracle/product/12.1.0/client_1`, but now you didn't set it, which is why the build process complains that it cannot find the Oracle headers.

To spell it out in minute detail for you:

    export PATH=/opt/sas/viya/home/bin:$PATH
    export ORACLE_HOME=/opt/oracle/product/12.1.0/client_1
    make clean
    make
    sudo make install

**Comment by harshitsoni19** [comment]
It worked. Thank you so much for your help with this setup issue. 
I had to set above variable in user's .bash_profile and source the file to make it work.  I did set them up in /etc/profile.d/vars.sh too but probably that wasn't necessary.

Much appreciated.
