### ISSUE TITLE
make doesn't work with postgresql 11 beta

### ISSUE THREAD

**Issue by volkmarbuehringer** [laurenz/oracle_fdw#255]
I tried to compile with postgresql 11 beta and have problems with
the makefile

with postgresql 10 make worked:

[postgres@localhost oracle_fdw]$ make
/usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o oracle_fdw.bc oracle_fdw.c
make: /usr/lib64/ccache/clang: Kommando nicht gefunden
make: *** [/usr/pgsql-11/lib/pgxs/src/makefiles/../../src/Makefile.global:1009: oracle_fdw.bc] Fehler 127

**Comment by laurenz** [comment]
That means that your PostgreSQL is configured `--with-llvm`, but the `clang` compiler that was present during PostgreSQL build is not found.

Did you build PostgreSQL from source?

**Comment by laurenz** [comment]
You can ignore those errors, but it means you have to install the extension files by hand.

**Comment by laurenz** [comment]
I experimented, and the following works for me:

    with_llvm=no make -e

**Comment by volkmarbuehringer** [comment]
Thank you.
where do I put this ?

**Comment by laurenz** [comment]
On the command line. I suggest that you call `make` like that.

**Comment by laurenz** [comment]
Did you get it to work? Can we close the issue?

**Comment by volkmarbuehringer** [comment]
Yes thank you



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Laurenz Albe <notifications@github.com>
Datum: 07.06.18 21:41 (GMT+01:00)
An: laurenz/oracle_fdw <oracle_fdw@noreply.github.com>
Cc: Volkmar Bühringer <Volkmar.Buehringer@prounix.de>, Author <author@noreply.github.com>
Betreff: Re: [laurenz/oracle_fdw] make doesn't work with postgresql 11 beta (#255)


Did you get it to work? Can we close the issue?
