### ISSUE TITLE
oracle_fdw.c:8:22: fatal error: postgres.h:

### ISSUE THREAD

**Issue by rnicolae69** [laurenz/oracle_fdw#256]
Hello.
Thank you for your job and support.
I found some days ago this wrapper and tried to install, but somethgin went wrong.
I'm stucked in this error:
"oracle_fdw.c:8:22: fatal error: postgres.h: File o directory non esistente"
Anyone can help?
Should I open another thread?
Thank you very much for helping.

**Comment by laurenz** [comment]
Please tell us the steps how you built oracle_fdw.

How did you install PostgreSQL?
Is `pg_config` on the `PATH`?
If you installed PostgreSQL with binary packages, did you install the "devel" or "dev" package?

**Comment by rnicolae69** [comment]
Hello.
I didnt install it, I just found it on the server, and now I have to manage it.
So I'm quiet new. May you help me? 
![image](https://user-images.githubusercontent.com/40034608/41152674-ae8fb7f0-6b14-11e8-97aa-0cda4576de04.png)

**Comment by laurenz** [comment]
I like &ldquo;quiet new&rdquo;.

I think all you need is the command

    yum install postgresql10-devel

**Comment by rnicolae69** [comment]
LOL I'm quiet new to PG, I mean.
Installed devel.
![image](https://user-images.githubusercontent.com/40034608/41167132-56711cd4-6b42-11e8-8c3f-fa453e04ff5c.png)
Now try to create the extension? 
Thank you

**Comment by laurenz** [comment]
Yes, now it should work (unless there is some other problem).

**Comment by rnicolae69** [comment]
Hi. Still not working ... 
![image](https://user-images.githubusercontent.com/40034608/41223190-66931aee-6d69-11e8-9e71-19c02932777a.png)

**Comment by laurenz** [comment]
You must build oracle_fdw against the same version of PostgreSQL as you are running it.

See #246.

**Comment by rnicolae69** [comment]
there is just one version of Postgres on that server

**Comment by laurenz** [comment]
Still you built oracle_fdw against a different version.

If you share more of what you are doing than some screen shots, maybe I can spot where you are going wrong.

Please tell me all you are doing to configure, build and install oracle_fdw.

The screen shots clearly show that there is PostgreSQL 9.2 and PostgreSQL v10 installed on the machine. If you build against PostgreSQL 9.2, you'd get exactly this error.

My bet is that `pg_config` from 9.2 is on the `PATH` before the one from v10.

**Comment by rnicolae69** [comment]
I Downloaded file oracle_fdw-ORACLE_FDW_2_0_0.zip from https://github.com/laurenz/oracle_fdw/releases/tag/ORACLE_FDW_2_0_0 and:
	a. unzip oracle_fdw-ORACLE_FDW_2_0_0.zip
	b. make && make install
	c. cp oracle_fdw--1.1.sql oracle_fdw--1.0--1.1.sql oracle_fdw.control /usr/pgsql-10/share/extension
	d. cp oracle_fdw.so /usr/pgsql-10/lib
What other screenshots can I share you? 

Postgres process running:
![image](https://user-images.githubusercontent.com/40034608/41236808-5081b372-6d92-11e8-9faa-22024c372bd6.png)

**Comment by laurenz** [comment]
Text is better than a screenshot, because you can copy and paste it.

Your problem is probably the `make`, because it will call `pg_config` from your 9.2 installation.

Try the following to verify that:

    pg_config --version

You probably have to do the following to build and install oracle_fdw into your PostgreSQL v10 installation:

    PATH=/usr/pgsql-10/bin:$PATH make clean
    PATH=/usr/pgsql-10/bin:$PATH make
    sudo make install

**Comment by rnicolae69** [comment]
[root@HeroDB ~]# pg_config --version
PostgreSQL 9.2.23

[root@HeroDB oracle_fdw-ORACLE_FDW_2_0_0]# PATH=/usr/pgsql-10/bin:$PATH make cle                                                                                           an
rm -f oracle_fdw.so   liboracle_fdw.a  liboracle_fdw.pc
rm -f oracle_fdw.o oracle_utils.o oracle_gis.o
rm -rf results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/ o                                                                                             utput_iso/

[root@HeroDB oracle_fdw-ORACLE_FDW_2_0_0]# PATH=/usr/pgsql-10/bin:$PATH make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexces                                                                s-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fP                                                                IC -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracl                                                                e/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/or                                                                acle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/cli                                                                ent -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -                                                                c -o oracle_fdw.o oracle_fdw.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexces                                                                s-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fP                                                                IC -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracl                                                                e/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/or                                                                acle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/cli                                                                ent -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -                                                                c -o oracle_utils.o oracle_utils.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexces                                                                s-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fP                                                                IC -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracl                                                                e/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/or                                                                acle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/cli                                                                ent -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -                                                                c -o oracle_gis.o oracle_gis.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexces                                                                s-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fP                                                                IC -shared -o oracle_fdw.so oracle_fdw.o oracle_utils.o oracle_gis.o -L/usr/pgsql-10/lib -Wl,--as-needed  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-10/lib',--enabl                                                                e-new-dtags  -L -L/bin -L/lib -lclntsh -L/usr/lib/oracle/12.2/client/lib -L/usr/lib/oracle/12.2/client64/lib -L/usr/lib/oracle/12.1/client/lib -L/usr/lib/oracle/12.1/client6                                                                4/lib -L/usr/lib/oracle/11.2/client/lib -L/usr/lib/oracle/11.2/client64/lib -L/usr/lib/oracle/11.1/client/lib -L/usr/lib/oracle/11.1/client64/lib -L/usr/lib/oracle/10.2.0.5/                                                                client/lib -L/usr/lib/oracle/10.2.0.5/client64/lib -L/usr/lib/oracle/10.2.0.4/client/lib -L/usr/lib/oracle/10.2.0.4/client64/lib -L/usr/lib/oracle/10.2.0.3/client/lib -L/usr                                                                /lib/oracle/10.2.0.3/client64/lib
[root@HeroDB oracle_fdw-ORACLE_FDW_2_0_0]# make install
/usr/bin/mkdir -p '/usr/lib64/pgsql'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/doc/pgsql/extension'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 755  oracle_fdw.so '/usr/lib64/pgsql/oracle_fdw.so'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw.control '/usr/share/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw--1.1.sql ./oracle_fdw--1.0--1.1.sql  '/usr/share/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./README.oracle_fdw '/usr/share/doc/pgsql/extension/'

then I copied **oracle_fdw.control**, **oracle_fdw--1.1.sql** and **README.oracle_fdw** in /usr/pgsql-10/share/extension and **oracle_fdw.so** in /usr/pgsql-10/lib

and then **FINALLY**:
postgres=# create extension oracle_fdw;
**CREATE EXTENSION**

**Thank you very much for helping.**

**Comment by rnicolae69** [comment]
Now trying to:
CREATE SERVER oracle_assistiti FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver'//x.x.x.x:1521/SID');
gets me this error:
11:57:49 Kernel error: ERRORE:  il wrapper di dati esterni "oracle_fdw" non esiste

The oracle_fdw extension was created with postgres user, this is another user owning a database.

**Comment by laurenz** [comment]
You should not create the extension in the `postgres` database, but in the database from which you need to access Oracle.

**Comment by rnicolae69** [comment]
ok I finally did it. Now on the Oracle DB I have some views and synonyms. How can I read them ? do I hace to import ito postgresql, or may I read them remotely? Ty.

**Comment by laurenz** [comment]
You can either define foreign tables for the Oracle objects you want to use with the `CREATE FOREIGN TABLE` statement, or you can use `IMPORT FOREIGN SCHEMA` to automatically create the foreign tables for you.

Like the README says:

> `IMPORT FOREIGN SCHEMA` will create foreign tables for all objects found in
>  `ALL_TAB_COLUMNS`.  That includes tables, views and materialized views,
>  but not synonyms.

**Comment by laurenz** [comment]
&ast;sigh&ast; I don't want to be rude, but did you read the documentation?

> - The Oracle schema name must be written exactly as it is in Oracle, so
>   normally in upper case.  Since PostgreSQL translates names to lower case
>   before processing, you must protect the schema name with double quotes
>   (for example `"SCOTT"`).

**Comment by rnicolae69** [comment]
Well you have to be rude, because I read the doc, very quickly and I didn't see that part. :)
I can see now in my foreign tables, all the tables from Oracle user. We can now close this long thread.
Thank you very much for your help and patience. 
I owe you a beer ! :D
