### ISSUE TITLE
How can I create a foreign table with only specific columns? Also how can you specify a schema."table name" with double quotes?

### ISSUE THREAD

**Issue by Bpapman** [laurenz/oracle_fdw#257]
Hi laurenz,
I am using postgres for fdw's to pull in multiple databases as resources.
The original problem is when importing tables as a foreign schema eg
`CREATE SCHEMA DW`
`IMPORT FOREIGN SCHEMA "BRIDGES" LIMIT TO ("Table 1") FROM SERVER DATAWAREHOUSE INTO DW `

When the foreign schema.table changes I no longer get any results (0 rows no error) in postgres until the we drop and re-run the above commands. Our warehouse is still in the early phases and occasionally adds new columns which creates this issue.

From here we create material views for translation and speed reasons. But we use material view refreshes to keep the data up to date.

One of my stabs at fixing this problem was to try to import specific columns from the oracle table as opposed to our bandage solution above. This is because the warehouse rarely removes columns but most frequently adds additional and/or re-orders the columns.
`CREATE FOREIGN TABLE DW."Table 1" (
    id INT,
    status VARCHAR(8)
) SERVER DATAWAREHOUSE
OPTIONS (
    table '(SELECT "Employee ID", "Effective Status" FROM BRIDGES."Table 1")',
    readonly
);`

I assume this would work but the documentation on foreign table options doesn't specify how you would double quote when necessary. Describing the full table with options schema 'BRIDGES'  and table 'Table 1' works but the column order could still change.

If I'm going in the wrong direction let me know. I hope I gave enough information to avoid the XY problem.

**Comment by laurenz** [comment]
Yes, `IMPORT FOREIGN SCHEMA` will only work if the foreign table is not already defined.

Defining a foreign table with a `SELECT` that contains only certain columns seems like a good solution in the face of changing Oracle tables.

The `SELECT` statement that you use in the `table` option is a plain Oracle `SELECT` statement, so identifiers must be quoted in the Oracle fashion: Only names that are not all upper case have to be quoted.

Your foreign table definition looks like it should work. Are you experiencing a problem?

**Comment by Bpapman** [comment]
The one thing I forgot. I'm using DataGrip as my console if that matters at all.

`[HV024] ERROR: invalid value for option "table" Hint: Double quotes are not allowed in names.`

From postgres docs: HV024 | fdw_invalid_attribute_value

**Comment by laurenz** [comment]
That looks like you wrote

    CREATE FOREIGN TABLE ... OPTIONS ("table" ...);

instead of what you said above.
The client shouldn't matter as long as it doesn't mess with your statements.

No errors and no data means that the Oracle query returned no data.

You'll have to give me more details if I am to help you:
- The `CREATE TABLE` statement in Oracle.
- The `CREATE FOREIGN TABLE` statement in PostgreSQL.

Please copy and paste them literally from your screen.

**Comment by Bpapman** [comment]
In oracle
> CREATE TABLE "Instructor / Advisor"
> (
>   EMPLID                     VARCHAR2(11) NOT NULL,
>   "Employee ID"              NUMBER,
>   "Academic Organization ID" NUMBER,
>   "Instructor Type ID"       NUMBER,
>   ACAD_ORG                   VARCHAR2(10) NOT NULL,
>   ADVISOR                    VARCHAR2(1)  NOT NULL,
>   INSTR_TYPE                 VARCHAR2(4)  NOT NULL,
>   INSTR_AVAILABLE            VARCHAR2(2)  NOT NULL,
>   "Effective Status"         VARCHAR2(8),
>   "Start Date"               DATE,
>   "End Date"                 DATE,
>   "Current Row Indicator"    VARCHAR2(7)
> )

In postgres.
> CREATE FOREIGN TABLE DW."Instructor / Advisor" (
>     emplid VARCHAR(11) NOT NULL,
>     employeeid INT,
>     status VARCHAR(8)
> ) SERVER DW
> OPTIONS (
>     table '(SELECT "EMPLID", "Employee ID", "Effective Status" FROM BRIDGES."Instructor / Advisor")');

Specifically if OPTIONS becomes `(schema 'BRIDGES', table 'Instructor / Advisor')` everything queries correctly but this is just one table that I'm moving away from import schema.

**Comment by laurenz** [comment]
Oh, I see. This is a bug left behind from the time when subqueries were not allowed as `table` option.

Should be fixed with commit b96f9d9ed13a8a1bec681b07096dd9f5b7918bd6.
