### ISSUE TITLE
To Install for a Oracle docker Container

### ISSUE THREAD

**Issue by kaushikjnayak** [laurenz/oracle_fdw#258]
May I know how and where could I Install the FDW If I have PostgreSQL(App) installed on my local ( Mac  OsX ) while I'm running  Oracle  for GNU Linux on a docker container ?
When I simply tried to run `make` on my local, it gives the error:

> oracle_utils.c:22:10: fatal error: 'oci.h' file not found
> #include <oci.h>
>          ^~~~~~~
> 1 error generated.
> make: *** [oracle_utils.o] Error 1

I have an Oracle instant client  as well on my Mac if it helps in anyway.

**Comment by laurenz** [comment]
I have no idea about docker specific problems.

But he error message you show suggests that you didn't install the Oracle client header files. For Instant Client that is the &ldquo;SDK&rdquo; package.

**Comment by kaushikjnayak** [comment]
That issue is resolved after I downloaded SDK package.
But when i run this from psql
`CREATE EXTENSION oracle_fdw;
`, 
it causes this error:
> ERROR:  could not load library "/Applications/Postgres.app/Contents/Versions/10/lib/postgresql/oracle_fdw.so": dlopen(/Applications/Postgres.app/Contents/Versions/10/lib/postgresql/oracle_fdw.so, 10): Library not loaded: @rpath/libclntsh.dylib.12.1
>   Referenced from: /Applications/Postgres.app/Contents/Versions/10/lib/postgresql/oracle_fdw.so
>   Reason: image not found

I tried searching to try and  fix this, but could not find a solution anywhere.

**Comment by laurenz** [comment]
Looks like the operating system cannot find the Oracle 12.1 client shared library.

I don't know anything about Mac OS, but a web search told me that it might be the right thing to set the environment variable `DYLD_FALLBACK_LIBRARY_PATH` to include the path where your Oracle client shared library is found.

This environment variable should not be set in your shell, but in the environment of the PostgreSQL server process. How this is done will depend on how PostgreSQL is started.
