### ISSUE TITLE
Mailin list still active?  (re:  [Oracle-fdw-general] Error creating extension)

### ISSUE THREAD

**Issue by cloojure** [laurenz/oracle_fdw#26]
Hi - I had the same problem (& solution!) described in this post:
------------------------------------------
On Tue, Nov 20, 2012 at 10:40 AM, Albe Laurenz <laurenz.albe at wien.gv.at> wrote:
> So /usr/lib/oracle/11.2/client64/lib is in
> /etc/ld.so.conf and you ran ldconfig, right?
> That should be good enough (better than the dreaded
> LD_LIBRARY_PATH, actually).
> Did you restart the PostgreSQL server after you did that?

ok, i think i put it wrong on ld.so.conf... anyway i create a new
oracle.conf file on ld.so.conf.d/ run ldconfig again with -v option
and now i see oracle libs.

i restarted postgresql and tried again... and it works.
thanks a lot
Jaime Casanova       
-------------------------------------------
(http://lists.pgfoundry.org/pipermail/oracle-fdw-general/2014q3/000138.html)

I wanted to update the mailing list with some additional info but when I try to access the mailing list I get an error:
-------------------------------------------
Forbidden
You don't have permission to access /mailman/listinfo/oracle-fdw-general on this server.
-------------------------------------------

Is the mailing list still active?  Has it moved?

Thanks,
Alan Thompson

**Comment by cloojure** [comment]
PS Apologies for the strange font sizes seen above....I do not see any way of correcting that.
Alan

**Comment by laurenz** [comment]
I have sent an e-mail to Marc Fournier to look into the mailing list problem.
Glad you got oracle_fdw to work!

**Comment by laurenz** [comment]
The mailing list problem should be fixed now.
Thanks for the report!
