### ISSUE TITLE
Delete takes an excessive amount of time

### ISSUE THREAD

**Issue by asr1901** [laurenz/oracle_fdw#260]
I have an oracle_fdw table pointing to an Oracle 11g machine.  
In Postgres, I'm running the statement "DELETE FROM table where transaction_date > current_date -6)"

There are 255,736 rows to be deleted.

This statement runs for > 10 minutes without returning anything.

In contrast, when I run in Oracle directly "delete from table where transaction_date > trunc(sysdate)-6" it completes in < 3 seconds.

The primary key for the table is a composite key of (transaction_date, transaction_id)

Explain plan in Postgres:

```
                                                                                                           QUERY PLAN                                                                                                             
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Delete on TABLE  (cost=10000.00..20000.00 rows=1000 width=12)
   Oracle statement: DELETE FROM "ORACLE_SCHEMA"."TABLE" WHERE "TRANSACTION_DATE" = CAST (:k1 AS DATE) AND "TRANSACTION_ID" = :k2
   ->  Foreign Scan on TABLE  (cost=10000.00..20000.00 rows=1000 width=12)
         Oracle query: SELECT /*3ef36beac2704cf3e3463225eb234157*/ r1."TRANSACTION_DATE", r1."TRANSACTION_ID" FROM "ORACLE_SCHEMA"."TABLE" r1 WHERE (r1."TRANSACTION_DATE" > (CAST ('2018-07-01 00:00:00 AD' AS DATE))) FOR UPDATE
(4 rows)
```

Is this a limitation of oracle_fdw or is there anything I can do to speed this up?

**Comment by asr1901** [comment]
Here's the Oracle side EXPLAIN plan from sqlplus (the query that takes < 3 seconds):

```
SQL> delete from ORACLE_SCHEMA.TABLE where TRANSACTION_DATE > trunc(sysdate)-6;

255736 rows deleted.


Execution Plan
----------------------------------------------------------
Plan hash value: 3554545475

------------------------------------------------------------------------------------------------------------------------

| Id  | Operation		  | Name		       | Rows  | Bytes |
 Cost (%CPU)| Time     | Pstart| Pstop |

------------------------------------------------------------------------------------------------------------------------

|   0 | DELETE STATEMENT	 		 |			        |   247K|  3377K| 32212	(94)| 00:01:09 |       |       |
|   1 |  DELETE 		  | TABLE    |       		    |       |	    |	      	|       |	       |
|   2 |   PARTITION RANGE ITERATOR	 |			        |   247K|  3377K| 32212	(94)| 00:01:09 |   KEY |    93 |
|*  3 |    INDEX RANGE SCAN	  		 | PK_TABLE |   247K|  3377K| 32212	(94)| 00:01:09 |   KEY |    93 |

------------------------------------------------------------------------------------------------------------------------


Predicate Information (identified by operation id):
---------------------------------------------------

   3 - access("TRANSACTION_DATE">TRUNC(SYSDATE@!)-6)


Statistics
----------------------------------------------------------
	 49  recursive calls
    1040758  db block gets
       2327  consistent gets
	  0  physical reads
  125367516  redo size
	840  bytes sent via SQL*Net to client
	842  bytes received via SQL*Net from client
	  3  SQL*Net roundtrips to/from client
	  1  sorts (memory)
	  0  sorts (disk)
     255736  rows processed
```

**Comment by asr1901** [comment]
I did a full timing test.  It took 1 hour and 55 minutes to delete 255k rows from Oracle via oracle_fdw.  The same delete statement on the Oracle side takes < 15 seconds.

**Comment by laurenz** [comment]
Is your table really called `TABLE`? Obfuscation can mask problems.

The primary key should be `(TRANSACTION_ID, TRANSACTION_DATE)` (or the other way round). At least that's what you told oracle_fdw in your `CREATE FOREIGN TABLE` statement.

So the `DELETE` statement

    DELETE FROM "ORACLE_SCHEMA"."TABLE"
    WHERE "TRANSACTION_DATE" = CAST (:k1 AS DATE)
      AND "TRANSACTION_ID" = :k2;

should be efficient. Can you confirm that?

The first query should also be fast, right? Here it is:

    SELECT r1."TRANSACTION_DATE", r1."TRANSACTION_ID"
    FROM "ORACLE_SCHEMA"."TABLE" r1
    WHERE (r1."TRANSACTION_DATE" > (CAST ('2018-07-01 00:00:00 AD' AS DATE)))
    FOR UPDATE;

If both queries are fast, the time is probably spend in the 255736 client-server round trips used to delete the rows.

Of course this is not a very efficient way to go about deleting so many rows. The README states that clearly:

> While modifying foreign data works, the performance is not particularly
> good, specifically when many rows are affected, because (owing to the way
> foreign data wrappers work) each row has to be treated individually.

This could potentially be optimized, but it would be complicated. I'd say that oracle_fdw is not good for efficient bulk updates or deletes.
