### ISSUE TITLE
oracle_fdw parameters or transaction options possible?

### ISSUE THREAD

**Issue by pauldzy** [laurenz/oracle_fdw#262]
Hi Laurenz,

I have not entirely forgotten about #245.  However overall it seems that geometry translation is rather slow and adding additional logic to check the orientation of polygon rings will just make it slower.  Ideally it would be swell to have this be optional behavior.  However I do not exactly see how oracle_fdw could or should accept logic conditions per transaction.

What I mean is perhaps I have 3 million polygons in my system which I know are oriented correctly and I do not wish to have their orientations checked.  Or perhaps I have 3 millions polygons from unknown source which may or may not be oriented correctly and I want to verify the orientation perhaps on the first load into my system (and thereafter is not needed).  Is oracle_fdw really setup for this kind of conditional processing?  I just don't see any other functionality doing this.

Paul

**Comment by laurenz** [comment]
Hmm, it should be quite fast to read Oracle geometries via oracle_fdw. Updating or inserting many Oracle geometries is slow, but that's a general problem of oracle_fdw which updates or inserts each row individually. Are you reading or writing?

I am not certain what you mean by making such a check optional. Currently there is no such check, right? So are you wondering how to write a patch that optionally checks polygon orientation?

In that case the answer would be to make this a FDW option, probably on the table, like `max_long` or `prefetch`. This can be set and reset at will. Of course you could also add a new GUC `oracle_fdw.check_polygon_orientation`. Hard to say which is better.

**Comment by laurenz** [comment]
What is the state on this?

**Comment by pauldzy** [comment]
hello,
well its still under consideration.  :)
but do close the ticket for now if its cluttering up the list.

**Comment by laurenz** [comment]
Let's leave it open. This was just a keepalive packet.

**Comment by laurenz** [comment]
Four years later: shall we still keep this open?

**Comment by J3throSanidad** [comment]
Hi Laurenz,

Can you provide download link for oracle_fdw which has compatibility with psql (PostgreSQL) 9.4.24? Thanks!
