### ISSUE TITLE
OCIEnvCreate failed to create environment handle  new Situation not like before

### ISSUE THREAD

**Issue by martinko2009** [laurenz/oracle_fdw#263]
I query a foreign table like that
```
select * from AAA;
```
but I get these errors like below:
```
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle

SQL state: HV00N
Detail: 
```

I have modify /etc/profile, and add ORACLE_HOME, LD_LIBRARY_PATH, then source /etc/profile
I use printenv, it display ORACLE_HOME, LD_LIBRARY_PATH , these two variables do work.
But when I use cat /proc/302/environ | xargs -0 -n 1 echo | sort
I found there has not the value of ORACLE_HOME in the LD_LIBRARY_PATH, it is the content of that like below:
```
LD_LIBRARY_PATH=/opt/PostgreSQL/10/lib::
LESSOPEN=|/usr/bin/lesspipe.sh %s
LOADEDMODULES=
LOGNAME=postgres
MAIL=/var/spool/mail/postgres
MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
MODULESHOME=/usr/share/Modules
_=/opt/PostgreSQL/10/bin/pg_ctl
ORACLE_HOME=/opt/instantclient_11_2
PATH=/opt/PostgreSQL/10/bin::/sbin:/usr/sbin:/bin:/usr/bin
PGDATA=/opt/PostgreSQL/10/data
```
```
SELECT oracle_diag();
oracle_fdw 2.0.0, PostgreSQL 10.4, Oracle client 11.2.0.4.0, ORACLE_HOME=/opt/instantclient_11_2, TNS_ADMIN=/opt/instantclient_11_2/network/admin
```
here is the trace.out

[trace.out.log](https://github.com/laurenz/oracle_fdw/files/2205066/trace.out.log)

I can't solve the problem.
Can you tell me how to solve it.
Thank you.

**Comment by laurenz** [comment]
It is much better to add `/opt/instantclient_11_2` to `/etc/ld.so.conf` and run `ldconfig`.

That does not require any environment variables.

But I don't believe that that is the problem. If PostgreSQL fails to load the Oracle library, it won't get as far.

The trace doesn't contain any information. It is best to start a new connection, attach `strace` to the backend and run the `SELECT` on the foreign table. That should capture the interesting part.

It would be interesting to know the foreign server definition.

**Comment by martinko2009** [comment]
I try again, when I query the foreign table,like below 
```
postgres=# select * from AAA limit 10;
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
DETAIL:  
```
here is the trace.out  
[trace.out.log](https://github.com/laurenz/oracle_fdw/files/2230694/trace.out.log)

but just one record in the log file.

**Comment by laurenz** [comment]
You have attached to the wrong process. You have to attach to the backend process of the session where you run the command. You can get the process number with

    SELECT pg_backend_pid();

**Comment by martinko2009** [comment]
Oh, thank you.
here is the log 
[trace.out.log](https://github.com/laurenz/oracle_fdw/files/2230724/trace.out.log)

**Comment by laurenz** [comment]
You need to close the PostgreSQL session, start a new one, attach to that backend and run the query.

**Comment by martinko2009** [comment]
I use "service postgresql-10 stop"  to close the PostgreSQL session.
after that I type ps -ef|grep postgres then 
```
postgres  1990     1  0 Jul18 ?        00:02:20 /opt/PgBouncer/bin/pgbouncer -d /opt/PgBouncer/share/pgbouncer.ini
root     52296 52269  0 15:24 pts/1    00:00:00 grep postgres
```
then I use "service postgresql-10 start"  to start the PostgreSQL
then 
```
[root@dev02 ~]# su - postgres
-bash-4.1$ psql
psql.bin (10.4)
Type "help" for help.

postgres=# SELECT pg_backend_pid();
 pg_backend_pid 
----------------
          52444
(1 row)

postgres=# select * from VW_SNAPSHOT_FLIGHT_INFO limit 10;
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
DETAIL:  
postgres=#  
```
here is the log 
[trace.out.log](https://github.com/laurenz/oracle_fdw/files/2230901/trace.out.log)

**Comment by laurenz** [comment]
To quote from your trace:

    open("/opt/PostgreSQL/10/lib/postgresql/oracle_fdw.so", O_RDONLY|O_CLOEXEC) = 41

Ok, oracle_fdw was found.

    open("/opt/PostgreSQL/10/lib/libclntsh.so.11.1", O_RDONLY|O_CLOEXEC) = 41
    open("/opt/PostgreSQL/10/lib/libnnz11.so", O_RDONLY|O_CLOEXEC) = 41

What is the Oracle client shared library doing in your PostgreSQL software directory?
It looks like you copied part of the instant client there, but not all of it.

It would have been better not to do that.

    open("/opt/PostgreSQL/10/lib/libociei.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    open("/opt/PostgreSQL/10/lib/libociicus.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

Now Oracle is looking for the Instant Client library in the same directory where it found the client shared library. It cannot find the library because you forgot to copy it and so thinks that this is a regular Oracle installation (not an Instant Client).

    open("/opt/instantclient_11_2/nls/data/lx1boot.nlb", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/opt/instantclient_11_2/rdbms/mesg/diaus.msb", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/opt/instantclient_11_2/rdbms/mesg/ocius.msb", O_RDONLY) = -1 ENOENT (No such file or directory)

Since Oracle thinks it is a normal client, it tries to read message files and other files (which in Instant Client are in the Instant Client library). That fails.

Oracle deduces that something is seriously wrong and reports the error message you observe.

There are two solutions:

- Remove all Oracle files from the PostgreSQL software directory. Since the Instant Client installation directory is on your library path, that should work and is the best solution.
- Copy the Instant Client library `libociei.so` or `libociicus.so` (depending on whether you installed &ldquo;basic&rdquo; or &ldquo;basic light&rdquo;) to the PostgreSQL library directory where the other files are.

**Comment by laurenz** [comment]
Sorry, let me be more precise:

The library path is the list of directories where the dynamic loader `ld-linux.so` searches for dynamic libraries.

See this part of `man ld-linux.so`:

> When resolving shared object dependencies, the dynamic linker first inspects each dependency string to see if it contains a slash (this can occur  if  a  shared  object  pathname  containing slashes was specified at link time).  If a slash is found, then the dependency string is interpreted as a (relative or absolute) pathname, and the shared object is loaded using that pathname.
>
> If a shared object dependency does not contain a slash, then it is searched for in the following order:
>
> - Using the directories specified in the `DT_RPATH` dynamic section attribute of the binary if present and `DT_RUNPATH` attribute  does  not exist.  Use of `DT_RPATH` is deprecated.
>
> - Using  the environment variable `LD_LIBRARY_PATH` (unless the executable is being run in secure-execution mode; see below).  in which case it is ignored.
>
> - Using the directories specified in the `DT_RUNPATH` dynamic section attribute of the binary if present.   Such  directories  are  searched only  to  find those objects required by `DT_NEEDED` (direct dependencies) entries and do not apply to those objects' children, which must themselves have their own `DT_RUNPATH` entries.  This is unlike `DT_RPATH`, which is applied to searches for all children in the  dependency tree.
>
> - From  the  cache  file  `/etc/ld.so.cache`,  which  contains a compiled list of candidate shared objects previously found in the augmented library path.  If, however, the binary was linked with the `-z nodeflib` linker option, shared objects in the default paths  are  skipped. Shared objects installed in hardware capability directories (see below) are preferred to other shared objects.
>
> - In the default path `/lib`, and then `/usr/lib`.  (On some 64-bit architectures, the default paths for 64-bit shared objects are `/lib64`, and then `/usr/lib64`.)  If the binary was linked with the `-z nodeflib` linker option, this step is skipped.

I advocate the fourth option.
