### ISSUE TITLE
Oracle pkg_rls.set_context(...) 

### ISSUE THREAD

**Issue by cloojure** [laurenz/oracle_fdw#27]
Hi - We are trying to use oracle_fdw to access a legacy Oracle DB in the pharmaceutical industry. I got the oracle_fdw installed & working last night on an AWS instance using postgres 9.4.1 on Ubuntu.

An unexpected problem is that Oracle requires a function call "pkg_rls.set_context ('admin', '1', 'username', 'password') to be the very first thing performed by each connection to the DB.  This is used to control "multi-tenancy" (the name derives from the Package "Row Level Security" and the "Enterprise Context").  Are you familiar with this at all?  If one fails to issue this function call, all select statements return zero rows (with no warning).

If accessing the ODB with a GUI like Squirrel, sqlplus, or SQL Developer, this is merely an annoyance.  However, since this is a non-standard Oracle-only requirement, tools like oracle_fdw, Teiid, etc are not expecting it and they either fail or require awkward workarounds.  Accessing the ODB via JDBC is possible, but pkg_rls.set_context(...) must be called as the first operation for each connection or no table rows are visible.  This complicates even simple programs since the connection must be cached and the function must be called again in the event a connection is dropped & new one established.

For the time-being, I'm going to use Clojure & JDBC to export the data from the ODB for testing in a local pg instance.  In the long term, it would be nicer if we could extend the oracle_fdw extension to accommodate the pkg_rls.set_context(...) weirdness.

Have you ever encountered pkg_rls.set_context(...) before?  Do you have any suggestions on the best way to extend oracle_fdw to accomodate a "prelude" of sorts?  

Thanks for a great extension,
Alan Thompson

**Comment by laurenz** [comment]
I have no experience with Row Level Security in Oracle, but I have an idea.

In Oracle you can define triggers on database events, and one of these is "logon".
So my solution would be a logon trigger that calls the function whenever a new connection is established by a certain user.

**Comment by cloojure** [comment]
Great idea!  I will look into it.
Alan

**Comment by cloojure** [comment]
Failed:

```sql
sqlplus> CREATE OR REPLACE TRIGGER hr_logon_trigger
  2  AFTER LOGON ON DATABASE
  3  INSERT INTO hr_users_log (user_name, activity, event_date)
  4  VALUES (USER, 'LOGON', SYSDATE);
  5  end hr_logon_trigger;
  6  /
AFTER LOGON ON DATABASE
               *
ERROR at line 2:
ORA-01031: insufficient privileges
```

**Comment by laurenz** [comment]
Well, that's what you got a DBA for, right?
