### ISSUE TITLE
When release the new version of oracle fdw for windows and linux

### ISSUE THREAD

**Issue by martinko2009** [laurenz/oracle_fdw#271]
Dear laurenz:
When release the new version of oracle fdw for windows and linux?
Thank you. :)

**Comment by laurenz** [comment]
There is no precise date, but the answer is "soon".
We are about to pull a patch for outer join push down, and I want to get that in before I make a new release.

I am aware that it has been a last time since the last release.

You can always use the current master branch, I try to keep that in release quality.

**Comment by martinko2009** [comment]
When I download the current master branch, how to compile it for windows.

**Comment by laurenz** [comment]
This is what I used to build for PostgreSQL v10:

    REM needs Visual Studio 2013

    set ORACLE_HOME=C:\MinGW\msys\1.0\home\lanadvall\instantclient64_10_2
    set CODE_DIR=C:\MinGW\msys\1.0\home\lanadvall\oracle_fdw
    set PGSQL_DIR=C:\MinGW\msys\1.0\home\lanadvall\pg64_10

    cl /Ox /GL /Zi /LD /MD /W4 /wd4200 /wd4244 /wd4267 /wd4389 /wd4018 /wd4996 /wd4100 /wd4127 /D_CRT_SECURE_NO_WARNINGS /I %ORACLE_HOME%\sdk\include /I %CODE_DIR% /I %PGSQL_DIR%\include\server\port\win32_msvc /I %PGSQL_DIR%\include\server\port\win32 /I %PGSQL_DIR%\include /I %PGSQL_DIR%\include\server /I %PGSQL_DIR%\include\internal %CODE_DIR%\oracle_fdw.c %CODE_DIR%\oracle_utils.c %CODE_DIR%\oracle_gis.c %PGSQL_DIR%\lib\postgres.lib %ORACLE_HOME%\sdk\lib\msvc\oci.lib

By the way, we are all set for a new release.

I just have to find the time to do those Windows builds.

**Comment by laurenz** [comment]
Version 2.1.0 has just been released.
