### ISSUE TITLE
64/32 bit

### ISSUE THREAD

**Issue by mbwiese** [laurenz/oracle_fdw#273]
This is more of a question:
On a Windows 64 bit server, we have a PostgreSQL 9.4 32bit instance (Probably because Mapserver on same Server is 32 bit) 
I have tried installing the oracle_fdw extension.
I dropped the relevant files in postgres lib and share/extensions.
I tried both -win64 (first) and -win32 distributions.
On CREATE EXTENSION oracle_fdw I get ERROR: could not load library "C:/Program Files (x86)/PostgreSQL/9.4/lib/oracle_fdw.dll": %1 is not a valid Win32 application. 
I assume, this error is due to the not matching bitsize of Server and Postgres, and it is perfectly OK if so.
But I would like to know if my assumption is correct ?
Best
Marianne B. Wiese

**Comment by laurenz** [comment]
If you are running 32-bit PostgreSQL, you need 32-bit oracle_fdw binaries and a 32-bit Oracle client.

Otherwise you will see an error like you observe.

I'd recommend to use 64-bit PostgreSQL on a 64-bit machine.

**Comment by mbwiese** [comment]
Ok, thanks.
Actually there is only a 64bit Oracle client on that server, I was not aware that creating extension would already look at the existing Oracle client.

Thank you, I will put up the 32 bit Oracle client then.

Yes, of course, but someone else installed postgres in this case.

Marianne

**Comment by laurenz** [comment]
The reason is that `oracle_fdw.dll` is linked with `oci.dll`, so it cannot be loaded unless the latter is present.

**Comment by laurenz** [comment]
Is this resolved?

**Comment by mbwiese** [comment]
Hi

I think so, although I can’t confirm it.

It turned out, that on that specific production server,  another person is running scheduled tasks with the 64bit version of oracle_client.
I don’t dare to put the path to 32bit version first in the path, because I may obstruct some of his tasks.

I am now moving to another server (Linux 64 bit/postgres 64 bit).

Best
Marianne

**Comment by mbwiese** [comment]
Comment:
As I now just saw on the documentation on GitHub:
PostgreSQL and Oracle need to have the same architecture, for example you cannot have 32-bit software for the one and 64-bit software for the other.

Therefore I could have never worked on that server, so that was my ignorance.

/Marianne


From: Marianne B. Wiese
Sent: 01. oktober 2018 12:54
To: 'laurenz/oracle_fdw' <reply@reply.github.com>
Subject: RE: [laurenz/oracle_fdw] 64/32 bit (#273)

Hi

I think so, although I can’t confirm it.

It turned out, that on that specific production server,  another person is running scheduled tasks with the 64bit version of oracle_client.
I don’t dare to put the path to 32bit version first in the path, because I may obstruct some of his tasks.
I am now moving to another server (Linux 64 bit/postgres 64 bit).

Best
Marianne
