### ISSUE TITLE
Suggestion: EXPLAIN using dbms_xplan

### ISSUE THREAD

**Issue by devtomk** [laurenz/oracle_fdw#275]
To get the execution plan in Oracle, creating a PLAN_TABLE has not been necessary since Oracle 10 as such a table is available as a global synonym pointing to a temporary table. 

Using V$SQL and V$SQL_PLAN is only necessary to get the equivalent of Postgres' `explain (analyze)`. 

The "usual"  way to get an execution plan is to use 

    EXPLAIN PLAN FOR
    SELECT .... ;
    SELECT plan_table_output 
    FROM TABLE(dbms_xplan.display());

`dbms_xplan.display()` displays the most recently generated plan from PLAN_TABLE. If needed it can be passed a statement_id, but it's usually not necessary.

I think it would make more sense to use that, if a simple `EXPLAIN` was used on the Postgres side. 

The approach using V$SQL and V$SQL_PLAN makes sense if  `EXPLAIN (ANALYZE) ...` is used: add the comment with the unique id, run the statement, then retrieve the plan using V$SQL_PLAN.

**Comment by laurenz** [comment]
Thanks for the idea! I didn't know of that package.

I have read through the documentation any played with it, and it would definitely make the code simpler.

The only consideration I have is that with `DBMD_XPLAN` I have little control over the formatting of the output, and I think that the Oracle output with the access predicates in footnotes is not very readable.
It also wouldn't fit in very well with the rest of PostgreSQL's `EXPLAIN` output.

Can you think of a way to get at the information in a way similar to `PLAN_TABLE` or `V$SQL_PLAN`, so that I can format the output in a more readable fashion?

**Comment by laurenz** [comment]
I have seen that.

Still, the output looks like this:

SQL> SELECT * FROM TABLE(dbms_xplan.display(format => 'ALL,-PROJECTION,-ALIAS'));

    Plan hash value: 523216113

    ----------------------------------------------------------------------------------------------
    | Id  | Operation		    | Name	     | Rows  | Bytes | Cost (%CPU)| Time     |
    ----------------------------------------------------------------------------------------------
    |   0 | SELECT STATEMENT	    |		     |	   1 |	  20 |	   2   (0)| 00:00:01 |
    |   1 |  TABLE ACCESS BY INDEX ROWID| TYPETEST1      |	   1 |	  20 |	   2   (0)| 00:00:01 |
    |*  2 |   INDEX UNIQUE SCAN	    | TYPETEST1_PKEY |	   1 |	     |	   1   (0)| 00:00:01 |
    ----------------------------------------------------------------------------------------------

    Predicate Information (identified by operation id):
    ---------------------------------------------------

       2 - access("ID"=4)

rather than the more readable

    SELECT STATEMENT
      TABLE ACCESS BY INDEX ROWID TYPETEST1
        INDEX UNIQUE SCAN TYPETEST1_PKEY (condition "R1"."ID"=4)

Parsing the result strings seems difficult and fragile.

**Comment by laurenz** [comment]
I guess I'll decline this one.
But thanks for the inspiration!

**Comment by laurenz** [comment]
Also, isn't that package new as of Oracle 11?
That would mean that I'd have to drop support for older Oracle server versions.
Given that oracle_fdw is a tool to migrate data from (possibly old) Oracle servers, that seems unattractive.
