### ISSUE TITLE
support oracle 18.3

### ISSUE THREAD

**Issue by volkmarbuehringer** [laurenz/oracle_fdw#276]
Hi,

could you support linking with the oracle 18.3 instant client  ?

**Comment by laurenz** [comment]
You mean, add the paths from the Instant Client RPM to the `Makefile`?

Sure! Could you tell me where the headers and where the shared libraries are for the 32-bit and 64-bit Instant Client?

**Comment by volkmarbuehringer** [comment]
18.3 supports the new glibc on fedora 28, without symbolic links needed


I think you need to replace 12.2  with 18.3 that is all:

/usr/lib/oracle/18.3/client64
[prounix@localhost client64]$ ls
bin  lib

root@localhost client64]# pwd
/usr/include/oracle/18.3/client64
[root@localhost client64]# ls
ldap.h     occiCommon.h   occiObjects.h  ociapr.h  ociextp.h  ocixmldb.h    orid.h  ort.h
nzerror.h  occiControl.h  oci1.h         ocidef.h  oci.h      ocixstream.h  ori.h   xa.h
nzt.h      occiData.h     oci8dp.h       ocidem.h  ocikpr.h   odci.h        orl.h
occiAQ.h   occi.h         ociap.h        ocidfn.h  ociver.h   oratypes.h    oro.h

**Comment by laurenz** [comment]
It should work now.
