### ISSUE TITLE
Issue in installing oracle_fdw 2.0.1 on PG 9.6

### ISSUE THREAD

**Issue by venkatsusarla** [laurenz/oracle_fdw#277]
Hi Laurenz,
Firstly,Thanks for this great piece of work.
I am trying to install oracle_fdw 2.0.0 on PG 9.6 with Oracle 11.2 client with no success.
As per your installation requirement,It says 

"Due to an API break in a PostgreSQL minor release, the following PostgreSQL versions cannot be used: 9.6.0 to 9.6.8 and 10.0 to 10.3"
This means to use oracle_fdw i need to be less than 9.6?

**Comment by laurenz** [comment]
No, that means that you have to upgrade to 9.6.9 or better.

You should do that anyway. As the [web site](https://www.postgresql.org/support/versioning/) says:

> the community considers not upgrading to be riskier than upgrading

It is simple too: stop the server, install the latest update, restart the server.
