### ISSUE TITLE
Oracle's ROWID Type Not Supported

### ISSUE THREAD

**Issue by dreckard** [laurenz/oracle_fdw#28]
This is more of a feature request than issue.  The Oracle ROWID type (SQLT_RDD in the OCI constants) is not currently supported, so any columns that come after a ROWID typed column cannot be accessed with oracle_fdw.

>ERROR: column "rowid" of foreign table "some_foreign_table" cannot be converted to or from Oracle data type
>SQL state: HV004

**Comment by laurenz** [comment]
Supporting ROWID is an option, but even without that it is possible to use columns after the ROWID column.

In Oracle:

    SQL> CREATE TABLE testrowid(
       id NUMBER(5) CONSTRAINT testrowid_pkey PRIMARY KEY,
       arowid ROWID,
       string VARCHAR2(20 CHAR)
    ) SEGMENT CREATION IMMEDIATE;
    
    Table created.
    
    SQL> INSERT INTO testrowid VALUES (1, 'AAAWuQAAEAAAADkAAE', 'one');

    1 row created.

    SQL> INSERT INTO testrowid VALUES (2, 'AAAWuQAAEAAAADkAAB', 'two');

    1 row created.

    SQL> COMMIT;

    Commit complete.

In PostgreSQL:

    test=> CREATE FOREIGN TABLE testrowid (
       id integer NOT NULL,
       arowid bytea,
       string varchar(20)
    ) SERVER oradb OPTIONS (table 'TESTROWID');
    
    test=> SELECT id, string FROM testrowid;
     id | string
    ----+--------
      1 | one
      2 | two
    (2 rows)

You only have to make sure that the ROWID column is not in the select list.

INSERT or UPDATE for such a table will not work, but you can work around that by using a view that does not contain the ROWID column.

**Comment by dreckard** [comment]
Ah, thanks!
