### ISSUE TITLE
Can't load oracle_fdw on windows server 2016 Standard Edition x64

### ISSUE THREAD

**Issue by LaetitiaAvrot** [laurenz/oracle_fdw#285]
Hi,

I'm sure I did a mistake somewhere because I can't make Postgres load oracle_fdw, I got an error "unknwon error 126".

Here is what I did :

- PostgreSQL installed with EDB installer (version 10.5)
- Oracle Instant Client installed (version 11.2)
- Microsoft  Visual C++ redistrobutable package 2013 installed (file C:\Windows\System32\msvcr120.dll exists)
- oracle_fdw.dll added to C:\PostgreSQL\pg10\lib\postgresql and SQL and CONTROL files added to C:\PostgreSQL\pg10\share\postgresql\extension.

I set ORACLE_HOME and TNS_ADMIN in the environment variables. PostgreSQL binaries are added to the PATH.

I can connect to my database with sqlplus (but I think this is irrelevant as I can't load the library).

Any thoughts?

Cheers,

Lætitia

**Comment by laurenz** [comment]
Can you copy and paste the complete error message?
Is everything 64-bit or 32-bit, no mixes?
Is `oci.dll` on the `PATH`? Has PostgreSQL been restarted since you changed the `PATH` (if you did)?

**Comment by LaetitiaAvrot** [comment]
First a big thank you for your quick answer.
The complete message was 
> ERROR: could not load library "C:/PostgreSQL/pg10/lib/postgresql/oracle_fdw.dll" : unknown error 126

I double-checked there was no mixes between 32-bit and 64-bit. `oci.dll` is in the `PATH`. And I tried to restart PostgreSQL (but couldn't start because of the error).

Anyway, I'll close the issue because that solution was only one we wanted to explore and my customer decided to go without Postgres for that project (not because of oracle_fdw, but because they weren't ready to move to Postgres yet and that project will always be linked to Oracle because of the software's editor).

Thank you so much for your time.

Merry Christmas and happy new year!
