### ISSUE TITLE
Problem installing on PG 10 and oracle-instantclient18.3

### ISSUE THREAD

**Issue by jpintodacosta** [laurenz/oracle_fdw#286]
Hi
Nice 2019!

I've installed on CentOS PostgreSQL 10.6, oracle-instantclient18.3 and downloaded oracle_fdw-2.1.0.zip

When I try to build I get the error below I've checked:
pg_config --pgxs output
/usr/pgsql-10/lib/pgxs/src/makefiles/pgxs.mk

echo $PATH output
/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/lib/oracle/18.3/client64/bin:/root/bin

find /usr/include/oracle -name oci.h output
/usr/include/oracle/18.3/client64/oci.h

Can you give me some advice?
Regards
Joaquim

make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I/usr/lib/oracle/18.3/client64/sdk/include -I/usr/lib/oracle/18.3/client64/oci/include -I/usr/lib/oracle/18.3/client64/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_utils.o oracle_utils.c
oracle_utils.c:22:17: fatal error: oci.h: No such file or directory

**Comment by jpintodacosta** [comment]
Solved with sym link to
creating /usr/lib/oracle/18.3/client64/sdk and
ln -s /usr/include/oracle/18.3/client64 include

Thanks

**Comment by laurenz** [comment]
That works fine.

You could also use the latest development version of oracle_fdw, since support for 18.3 has been added in commit b2fc87691ee6f35ebe24c6faa1148837f0995101.

Thanks for sharing your findings!
