### ISSUE TITLE
ORA-01856: aC/a.C. o dC/d.C. DATE field

### ISSUE THREAD

**Issue by codificandola** [laurenz/oracle_fdw#287]
Hi  laurenz I am having this error between two DATE fields. 
My environment is: 

- PostgreSQL11 
- Oracle Client 10.2.0.5 - client64
- Oracle Database 10g Enterprise Edition Release 10.2.0.4.0  

In Oracle I have this table column definition:
..
FECHA date
..
In PostgreSQL I have this foreign table column definition:
...
fecha date
...

When I ran this query:

    select * 
    from movimientos 
    where fecha = '20190109'; 

I get the error: 

    ERROR:  error executing query: OCIStmtExecute failed to execute remote query
    DETAIL:  ORA-01856: aC/a.C. o dC/d.C. necesario
    SQL state: HV00L

Thank you in advance

**Comment by laurenz** [comment]
That is unexpected.

What do you get for

    EXPLAIN SELECT * FROM movimientos
    WHERE fecha = '20190109';

What is the result of

    SELECT oracle_diag('foreign_server');

(please substitute your actual foreign server name.)

**Comment by codificandola** [comment]
Yes, sure. 
Explain:

```
"Foreign Scan on movimientos  (cost=10000.00..7902880.00 rows=789288 width=8)"
"  Oracle query: SELECT /*ea3ab963226f14c7ff44afe1a016dcbd*/ r1."NUMERO_MOV", r1."FECHA" FROM "SCHEMA"."MOVIMIENTOS" r1 WHERE (r1."FECHA" = (CAST ('2019-01-09 00:00:00 AD' AS DATE)))"
```
oracle_diag:

`"oracle_fdw 2.1.0, PostgreSQL 11.1, Oracle client 10.2.0.5.0, Oracle server 10.2.0.4.0"
`
Thank you!!

**Comment by laurenz** [comment]
I guess your PostgreSQL database has `lc_messages` set to Spanish, so oracle_fdw sets `NLS_LANGUAGE` and `NLS_TERRITORY` to `SPANISH`, hence the Spanish Oracle messages.

But oracle_fdw makes sure to set `NLS_DATE_LANGUAGE` to `AMERICAN`, and that is the parameter that influences how date literals are interpreted. I tried with a Spanish `lc_messages`, and it worked fine.

Could you run the following in your PostgreSQL database and show what you get:

    CREATE FOREIGN TABLE nls_session_parameters (
       parameter text NOT NULL,
       value text
    ) SERVER oracle OPTIONS (table 'NLS_SESSION_PARAMETERS');

Change the name of the `SERVER` as appropriate!

    SELECT * FROM nls_session_parameters;

This should show us how the parameters are actually set.

Also, it would be good to know your PostgreSQL settings:

    SELECT name, setting FROM pg_settings WHERE name LIKE 'lc_%';

**Comment by codificandola** [comment]
Ok I understand, here is the data 

NLS_SESSION_PARAMETERS

```
"NLS_LANGUAGE"	"SPANISH"
"NLS_TERRITORY"	"AMERICA"
"NLS_CURRENCY"	"$"
"NLS_ISO_CURRENCY"	"AMERICA"
"NLS_NUMERIC_CHARACTERS"	".,"
"NLS_CALENDAR"	"GREGORIAN"
"NLS_DATE_FORMAT"	"YYYY-MM-DD HH24:MI:SS BC"
"NLS_DATE_LANGUAGE"	"SPANISH"
"NLS_SORT"	"SPANISH"
"NLS_TIME_FORMAT"	"HH.MI.SSXFF AM"
"NLS_TIMESTAMP_FORMAT"	"YYYY-MM-DD HH24:MI:SS.FF9 BC"
"NLS_TIME_TZ_FORMAT"	"HH.MI.SSXFF AM TZR"
"NLS_TIMESTAMP_TZ_FORMAT"	"YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC"
"NLS_DUAL_CURRENCY"	"$"
"NLS_COMP"	"BINARY"
"NLS_LENGTH_SEMANTICS"	"BYTE"
"NLS_NCHAR_CONV_EXCP"	"FALSE"
```
PG_SETTINGS

```
"lc_collate"	"en_US.UTF-8"
"lc_ctype"	"en_US.UTF-8"
"lc_messages"	"en_US.UTF-8"
"lc_monetary"	"en_US.UTF-8"
"lc_numeric"	"en_US.UTF-8"
"lc_time"	"en_US.UTF-8"

```

**Comment by laurenz** [comment]
Mysterious.

Do you have anything (login trigger, ...) that would change the parameters to Spanish *after* oracle_fdw has established the Oracle connection?

**Comment by codificandola** [comment]
No, nothing.  
I have installed everything as the doc says. I also tried with a newer Oracle client but didn't work.

**Comment by laurenz** [comment]
Are the settings the same when you connect with sqlplus from the PostgreSQL machine as user `postgres`?

Are there any Oracle environment variables set in the PostgreSQL environment?

Can you check <code>/proc/*&lt;pid&gt;*/environ</code> for a PostgreSQL backend that has used oracle_fdw and see what environment variables are set there?

**Comment by codificandola** [comment]
Yes, they are the same
The environment variables I set are: ORACLE_HOME, LD_LIBRARY_PATH, TNS_ADMIN and PATH.

/proc/<pid>/environ:
```
LANG=en_US.UTF-8
PATH=$PATH:/usr/pgsql-11/bin
NOTIFY_SOCKET=/run/systemd/notify
HOME=/var/lib/pgsql
LOGNAME=postgres
USER=postgres
SHELL=/bin/bash
PGDATA=/var/lib/pgsql/11/data/
PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj
PG_OOM_ADJUST_VALUE=0
ORACLE_HOME=/usr/lib/oracle/10.2.0.5/client64
LD_LIBRARY_PATH=/usr/lib/oracle/10.2.0.5/client64/lib
TNS_ADMIN=/usr/lib/oracle/10.2.0.5/client64/network/admin
```

Env variables for user postgres:

```
export ORACLE_HOME=/usr/lib/oracle/10.2.0.5/client64
export PATH=$PATH:$ORACLE_HOME/bin
export LD_LIBRARY_PATH=$ORACLE_HOME/lib
export TNS_ADMIN=$ORACLE_HOME/network/admin
export PATH=$PATH:/usr/pgsql-11/bin


```

**Comment by laurenz** [comment]
I forgot that `/proc/.../environ` only contains the startup environment...

Anyway, if you experience the same with sqlplus, and you have no `NLS_LANG` or `NLS_DATE_LANGUAGE` set in your environment, but it is still set to `SPANISH` in `NLS_SESSION_PARAMETERS`, that would quite clearly indicate that there is something going on on the Oracle server that sets the value.

Maybe your Oracle DBA knows more about that?

**Comment by laurenz** [comment]
That is unsurprising. But the query that oracle_fdw runs fails, right?

    select * from movimientos where fecha = '2019-01-09 00:00:00 AD';

oracle_fdw uses a certain format for dates and sets `NLS_DATE_FORMAT` and `NLS_DATE_LANGUAGE` so that Oracle understands the format.

**Comment by codificandola** [comment]
Yes it fails. 

Another test I did was changing fecha to varchar and casting it in PostgreSQL. But in this case, indexes are not used and I am getting a full scan in the Oracle table.

**Comment by laurenz** [comment]
There is clearly something fishy going on.
If nothing in your environment is set so Spanish, why should the Oracle session be?
I'd suspect the Oracle server, but I don't know where to point.

**Comment by codificandola** [comment]
Yes sure there is. 
But, I have a question, isn't the session already in Spanish as the NLS_LANG in Oracle is Spanish ?

**Comment by laurenz** [comment]
If your `lc_messages` setting is English, oracle_fdw will set `NLS_LANG` to English.

`NLS_LANG` determines `NLS_DATE_LANGUAGE` unless the latter is set explicitly, and oracle_fdw does that, so it should always be AMERICAN.

Where do you find a Spanish `NLS_LANG`? You didn't list it among the set environment variables.

**Comment by codificandola** [comment]
Ok I understand. I was taking about NLS_LANGUAGE in SPANISH. 
Look, I have these differences: 
In the PostgreSQL Server via SQLPLUS I get these parameters. 

```
PARAMETER		       VALUE
------------------------------ ----------------------------------------
NLS_LANGUAGE		       SPANISH
NLS_TERRITORY		       AMERICA
NLS_CURRENCY		       $
NLS_ISO_CURRENCY	       AMERICA
NLS_NUMERIC_CHARACTERS	       .,
NLS_CALENDAR		       GREGORIAN
NLS_DATE_FORMAT 	       DD-MON-RR
NLS_DATE_LANGUAGE	       SPANISH
NLS_SORT		       SPANISH
NLS_TIME_FORMAT 	       HH.MI.SSXFF AM
NLS_TIMESTAMP_FORMAT	       DD-MON-RR HH.MI.SSXFF AM
```
While in psql, selecting the foreign table I get these:
```
       parameter        |                value                
-------------------------+-------------------------------------
 NLS_LANGUAGE            | SPANISH
 NLS_TERRITORY           | AMERICA
 NLS_CURRENCY            | $
 NLS_ISO_CURRENCY        | AMERICA
 NLS_NUMERIC_CHARACTERS  | .,
 NLS_CALENDAR            | GREGORIAN
 NLS_DATE_FORMAT         | YYYY-MM-DD HH24:MI:SS BC
 NLS_DATE_LANGUAGE       | SPANISH
 NLS_SORT                | SPANISH
 NLS_TIME_FORMAT         | HH.MI.SSXFF AM
 NLS_TIMESTAMP_FORMAT    | YYYY-MM-DD HH24:MI:SS.FF9 BC
 NLS_TIME_TZ_FORMAT      | HH.MI.SSXFF AM TZR
 NLS_TIMESTAMP_TZ_FORMAT | YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC
```

One of the differences I can notice is the NLS_DATE_FORMAT, what if I change from NLS_DATE_FORMAT from "YYYY-MM-DD HH24:MI:SS BC" to "DD-MON-RR" in Oracle_FDW. 
Is it possible?

**Comment by laurenz** [comment]
That's not the problem.

I need the AD so oracle_fdw can handle dates before Christ.

To find the solution to your problem you have to figure out what sets `NLS_DATE_LANGUAGE` (and `NLS_LANGUAGE`) when you are using sqlplus.

Fix that, and everything, will work.

**Comment by codificandola** [comment]
Hi, I have just forced the format 'DD-Mon-RR' to the oracle user session with a trigger. So now, my nls_session_parameters in PostgreSQL are like these:
o3_dw=# select * from nls_session_parameters ; 

```
        parameter        |                value                
-------------------------+-------------------------------------
 NLS_LANGUAGE            | SPANISH
 NLS_TERRITORY           | AMERICA
 NLS_CURRENCY            | $
 NLS_ISO_CURRENCY        | AMERICA
 NLS_NUMERIC_CHARACTERS  | .,
 NLS_CALENDAR            | GREGORIAN
 NLS_DATE_FORMAT         | DD-MON-RR
 NLS_DATE_LANGUAGE       | SPANISH
 NLS_SORT                | SPANISH
 NLS_TIME_FORMAT         | HH.MI.SSXFF AM
 NLS_TIMESTAMP_FORMAT    | YYYY-MM-DD HH24:MI:SS.FF9 BC
 NLS_TIME_TZ_FORMAT      | HH.MI.SSXFF AM TZR
 NLS_TIMESTAMP_TZ_FORMAT | YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC
 NLS_DUAL_CURRENCY       | $
 NLS_COMP                | BINARY
 NLS_LENGTH_SEMANTICS    | BYTE
 NLS_NCHAR_CONV_EXCP     | FALSE
```
But, now I have this problem. If I query with the "Mon" in Spanish Postgres give me an error: 

> ERROR:  invalid input syntax for type date: "01ene2019"

And if I query is in english Oracle give me an error:

> DETALLE:  ORA-01861: el literal no coincide con la cadena de formato

if I try with February ('Feb') it works perfect, because "feb" in english and in spanish are the same. 
I think is a simple thing, but I can't find a solution. I change lc_time in Postgres but it doesn't work either.

**Comment by laurenz** [comment]
What you should force with a login trigger is:

    NLS_DATE_LANGUAGE=AMERICAN
    NLS_DATE_FORMAT=YYYY-MM-DD HH24:MI:SS BC
    NLS_TIMESTAMP_FORMAT=YYYY-MM-DD HH24:MI:SS.FF9 BC
    NLS_TIMESTAMP_TZ_FORMAT=YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC
    NLS_NUMERIC_CHARACTERS=.,

These are the settings that oracle_fdw needs for proper operation.

The thing I cannot understand is that they are set differently in your case, although oracle_fdw sets these values via environment variables.

But if you can force the correct values with a trigger, it should work all the same.

**Comment by codificandola** [comment]
Well, I change the date format to MM instead of MON because the NLS_DATE_LANGUAGE was still in Spanish, even though the trigger set AMERICAN. 
Now It work ok. If I a have any strage problem in the future, I will set these parameters before asking anything to you. 
Thank you very much, now It is working ok.

**Comment by laurenz** [comment]
If you ever find out why the settings were different from the ones that oracle_fdw sets, pray tell me!
