### ISSUE TITLE
Performance issue with count(*)

### ISSUE THREAD

**Issue by gaodi16366** [laurenz/oracle_fdw#288]
Postgres 11.1
Oracle 10.2.0.5.0
Oracle_fdw 2.1.0

I have a performance issue when execute a `count( * )` query like

    select count( * ) from a;

The table a has about 40,000 rows. And it takes 15s to get the result while 0.1s on oracle client.
Explain analyse  just give result like below
It seems that `count(*)` can't be pushed down to oracle. Is there any solution for this issue?

    postgres=# explain analyse  select count(*) from a;
                                                                   QUERY PLAN                                                            
    
    --------------------------------------------------------------------------------------------------------------------------
     Aggregate  (cost=20002.50..20002.51 rows=1 width=8) (actual time=15282.440..15282.441 rows=1 loops=1)
       ->  Foreign Scan on a  (cost=10000.00..20000.00 rows=1000 width=0) (actual time=7.130..15022.004 rows=415793 loops =1)
             Oracle query: SELECT /*7b29be0c10f94a41f044d5c3825ea347*/ '1' FROM "***"."a" r4
     Planning Time: 14.613 ms
     Execution Time: 15282.532 ms
    (5 rows)`

**Comment by laurenz** [comment]
You are right, aggregates are not pushed down to Oracle, so the whole table it pulled to PostgreSQL just for counting.

There is no pretty solution, but you could create a foreign table specifically for that:

    CREATE FOREIGN TABLE a_count (count bigint NOT NULL)
       SERVER oracle OPTIONS (table '(SELECT count(*) FROM schema_name.s)');

**Comment by gaodi16366** [comment]
OK, I understand now. Thank you so much.
