### ISSUE TITLE
Harcoded Oracle EPSG equivalents

### ISSUE THREAD

**Issue by pauldzy** [laurenz/oracle_fdw#29]
Hello,

I think this would be directed to Vincent.  I am a little perplexed by the built in equivalents in the epsgFromOracle and epsgToOracle functions.  I am not sure if this some kind of continental difference or what.  But 4269 as far as I know is a truly North American coordinate system based on NAD83.  
http://spatialreference.org/ref/epsg/4269/
It should always equate to 8265 in Oracle.  What is this 8267 primed onto Paris?  

Similarly WGS84 is the ubiquitous global system at 4326 
http://spatialreference.org/ref/epsg/4326/  
which I have always equated to 8307.  Looking at 8307 and 8192 I suppose they are equivalent.  So this does seem like a valid disagreement.  

I am wondering if you should do this at all, perhaps it would be better to just equate PostGIS 4269 to Oracle 4269 and if the user is using 9i or 10gR1 (less and less likely), then they need to edit the srid file to match an older Oracle srid to the PostGIS srid.

Cheers,
Paul

switch (srid)
    {
    	case 8192:  return 4326;  /* WGS84 */
    	case 8306:  return 4322;  /* WGS72 */
    	case 8267:  return 4269;  /* NAD83 */
    	case 8274:  return 4277;  /* OSGB 36 */
    	case 81989: return 27700; /* UK National Grid */
		default: return srid;
    }

**Comment by pauldzy** [comment]
Opps, apologies I see this was removed in the December update. Feel free to just remove the issue.
Thanks,
Paul

**Comment by laurenz** [comment]
Yes, the hard coded translation proved to be a bad choice.

Lacking deeper GIS knowledge, I was not aware that SRIDs are not standardized, but interpreted differently by different vendors and organizations.

So it seemed the best choice to let everybody configure this as they need.

**Comment by laurenz** [comment]
Duplicate of #14.
