### ISSUE TITLE
ERROR:  column "dealer_user_id" of foreign table "ora_ap_dealer" cannot be converted to or from Oracle data type

### ISSUE THREAD

**Issue by sheenzxx** [laurenz/oracle_fdw#290]
hi 
  my problem is  oracle table ap_dealer column dealer_user_id data type is  NUMBER,foreign table ora_ap_dealer column dealer_user_id  data type is numeric 。when I create foreign table with full columns of oracle's table .it was no problem.but when I create it with only four colums of it .it reported a ERROR：ERROR:  column "dealer_user_id" of foreign table "ora_ap_dealer" cannot be converted to or from Oracle data type
foreign table :
create foreign table ora_AP_DEALER
(
  id      numeric, 
  name varchar(100),
  short_name varchar(100),
  dealer_user_id      numeric
) SERVER ORA_AUTOPRICE options (table 'AP_DEALER');
oracle table
create table AP_DEALER
(
  id                  NUMBER not null,
  name                VARCHAR2(100),
  short_name          VARCHAR2(100),
  logo                VARCHAR2(255),
  agent_qualification NUMBER default 1,
  agent_qualfcn       VARCHAR2(255),
  home_url            VARCHAR2(255),
  recommend_value     NUMBER,
  recommend_value2    NUMBER,
  seq                 NUMBER default 99999 not null,
  agent_service       VARCHAR2(255),
  business_cars       VARCHAR2(255),
  business_brand      VARCHAR2(255),
  region_id           NUMBER,
  city                VARCHAR2(50),
  address             VARCHAR2(255),
  postcode            VARCHAR2(10),
  mobile              VARCHAR2(100),
  phone               VARCHAR2(100),
  as_phone            VARCHAR2(30),
  fax                 VARCHAR2(30),
  sos_phone           VARCHAR2(30),
  poc_1_phone         VARCHAR2(30),
  poc_400_phone       VARCHAR2(30),
  is_400_phone        NUMBER(1) default 0,
  contact             VARCHAR2(100),
  email               VARCHAR2(100),
  qq                  VARCHAR2(100),
  status              NUMBER(1) default 0 not null,
  deleted             NUMBER(1) default 0 not null,
  source              NUMBER(1) default 0,
  vip                 NUMBER(1) default -1,
  is_ad_dealer        NUMBER(1) default 0,
  is_agreement_dealer NUMBER(1) default 0,
  dealer_allot_id     NUMBER,
  pv_counter_id       NUMBER,
  show_counter_id     NUMBER,
  dealer_map_id       NUMBER,
  dealer_template_id  NUMBER,
  dealer_introduce_id NUMBER,
  dealer_business_id  NUMBER,
  dealer_user_id      NUMBER,
  dealer_counter_id   NUMBER,
  contract_id         NUMBER,
  join_date           DATE,
  create_user_id      NUMBER,
  create_user_name    VARCHAR2(50),
  create_time         DATE default sysdate not null,
  update_user_id      NUMBER,
  update_user_name    VARCHAR2(50),
  update_time         DATE,
  version             NUMBER,
  seo_title           VARCHAR2(255),
  support             NUMBER,
  against             NUMBER,
  send_time           DATE default sysdate,
  sendnews_num        VARCHAR2(32) default '2012-03-06=1',
  area_id             NUMBER default 0,
  special_service     VARCHAR2(255),
  namelist_range      NUMBER default 0,
  contact_no          VARCHAR2(30),
  dealer_group_id     NUMBER,
  shop_birthday       DATE,
  is_trial            NUMBER(1) default 0,
  is_delay            NUMBER(1)
)
when foreign table 
create foreign table ora_AP_DEALER
(
  id                  numeric,
  name                varchar(100),
  short_name          varchar(100),
  logo                varchar(255),
  agent_qualification numeric,
  agent_qualfcn       varchar(255),
  home_url            varchar(255),
  recommend_value     numeric,
  recommend_value2    numeric,
  seq                 numeric,
  agent_service       varchar(255),
  business_cars       varchar(255),
  business_brand      varchar(255),
  region_id           numeric,
  city                varchar(50),
  address             varchar(255),
  postcode            varchar(10),
  mobile              varchar(100),
  phone               varchar(100),
  as_phone            varchar(30),
  fax                 varchar(30),
  sos_phone           varchar(30),
  poc_1_phone         varchar(30),
  poc_400_phone       varchar(30),
  is_400_phone        numeric(1),
  contact             varchar(100),
  email               varchar(100),
  qq                  varchar(100),
  status              numeric(1),
  deleted             numeric(1),
  source              numeric(1),
  vip                 numeric(1),
  is_ad_dealer        numeric(1),
  is_agreement_dealer numeric(1),
  dealer_allot_id     numeric,
  pv_counter_id       numeric,
  show_counter_id     numeric,
  dealer_map_id       numeric,
  dealer_template_id  numeric,
  dealer_introduce_id numeric,
  dealer_business_id  numeric,
  dealer_user_id      numeric,
  dealer_counter_id   numeric,
  contract_id         numeric,
  join_date           timestamp without time zone,
  create_user_id      numeric,
  create_user_name    varchar(50),
  create_time         timestamp without time zone,
  update_user_id      numeric,
  update_user_name    varchar(50),
  update_time         timestamp without time zone,
  version             numeric,
  seo_title           varchar(255),
  support             numeric,
  against             numeric,
  send_time           timestamp without time zone,
  sendnews_num        varchar(32),
  area_id             numeric,
  special_service     varchar(255),
  namelist_range      numeric,
  contact_no          varchar(30),
  dealer_group_id     numeric,
  shop_birthday       timestamp without time zone,
  is_trial            numeric(1),
  is_delay            numeric(1)
) SERVER ORA_AUTOPRICE options (table 'AP_DEALER');
have no problem

**Comment by sheenzxx** [comment]
I found that ,oracle_fdw fetch column data with the order of oracle tables .when I used data type text for dealer_user_id  。it get data with oracle table column logo .so when designed foreign table for oracle table .used full columns and column order will be good

**Comment by laurenz** [comment]
This is a duplicate of #210.

Thanks for the feedback that you found the problem! It might help others.

**Comment by sheenzxx** [comment]
> This is a duplicate of #210.
> 
> Thanks for the feedback that you found the problem! It might help others.

thanks a lot！
