### ISSUE TITLE
Is not a valid Win32 application

### ISSUE THREAD

**Issue by nigun** [laurenz/oracle_fdw#294]
Hello Sir,

I download oracle_fdw-2.1.0-pg96-win64.zip, unzip, and copy to foldes.

When i execute the query
Create extension oracle_fdw
i got the following error:
**could not load library "C:/POSTGR~1/pg96/../pg96/lib/postgresql/oracle_fdw.dll": %1 is not a valid Win32 application**

systems specifications

windows 10 64 bit
oracle client 18.3.0.0.0 64 bit (home1)
oracle client 18.3.0.0.0 32 bit (home2)
postgresql 9.6 64 bit

our help :)

Kind regards,
Nigun

**Comment by laurenz** [comment]
I assume that oracle_fdw finds the 32-bit `oci.dll` first.

Could you try to take the 32-bit Oracle client out of the `PATH` and restart PostgreSQL?
If you cannot get that to work, uninstall the 32-bit Oracle client.

**Comment by nigun** [comment]
First thing I deleted from  32-bit PATH and restart PostgreSQL.
In the evening, remove the client, and inform for you.

**Comment by laurenz** [comment]
I find [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to be a valuable tool when dealing with such problems.

**Comment by nigun** [comment]
hi.
I reinstall 64-bit client in custom  mode. Select all components.
It`s work.
Probably, for the first time I put the 32-bit version of the last, later 64-bit
