### ISSUE TITLE
SDO_GEOMETRY. how create FOREIGN TABLE

### ISSUE THREAD

**Issue by nigun** [laurenz/oracle_fdw#298]
Hi. Laurenz,
I have a table with the field "geoloc"  MDSYS.SDO_GEOMETRY type.
I create foreign table:
```
CREATE FOREIGN TABLE atd
   (
  geoloc geometry(MultiPolygon,4326)
  name character varying(80)
      )
   SERVER server_ora
   OPTIONS (schema 'GIS', table 'ATD');
```
run:
`SELECT * FROM  atd`
I receive:
`ERROR: column "geoloc" of foreign table "atd" cannot be converted to or from Oracle data type`
How as it is correct to create  FOREIGN TABLE?

------------------
"oracle_fdw 2.1.0, PostgreSQL 9.6.10, Oracle client 18.1.0.0.0"
"POSTGIS="2.5.1'

Thanks.

**Comment by nigun** [comment]
Sory. 
I solved a problem. FOREIGN TABLE has to correspond completely ORA Table

**Comment by laurenz** [comment]
Yes, it is a duplicate of #201 and #1.
