### ISSUE TITLE
oracle_fdw.so: undefined symbol: AllocSetContextCreate when using pg_upgrade for postgresql 11

### ISSUE THREAD

**Issue by postgresnc** [laurenz/oracle_fdw#303]
I'm testing the upgrade of postgresql 10 to 11 using pg_upgrade and I'm getting an oracle_fdw library error. Oracle_fdw is working fine with my postgresql 10.5 installation.
 
Here's what I did.
1. Installed postgresql11, postgresql-11-server, postgresql11-libs, postgresql11-devel-11, postgresql11-contrib-11 packages. 
2. I initialized the database with /usr/pgsql-11/bin/postgresql-11-setup initdb.
3. I then set up oracle_fdw (version 2.1.0) with my new postgresql 11 installation. It was a little tricky as I had to search and install some extra packages (llvm5.0, llvm-toolset-7-clang, devtoolset-7). After that the oracle_fdw install went ok.

[root@ oracle_fdw-ORACLE_FDW_2_1_0]# make
/opt/rh/llvm-toolset-7/root/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/lib/oracle/11.2/client64/sdk/include -I/usr/lib/oracle/11.2/client64/oci/include -I/usr/lib/oracle/11.2/client64/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o oracle_fdw.bc oracle_fdw.c
/opt/rh/llvm-toolset-7/root/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/lib/oracle/11.2/client64/sdk/include -I/usr/lib/oracle/11.2/client64/oci/include -I/usr/lib/oracle/11.2/client64/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o oracle_utils.bc oracle_utils.c
/opt/rh/llvm-toolset-7/root/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/lib/oracle/11.2/client64/sdk/include -I/usr/lib/oracle/11.2/client64/oci/include -I/usr/lib/oracle/11.2/client64/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o oracle_gis.bc oracle_gis.c
[root@oracle_fdw-ORACLE_FDW_2_1_0]# make install
/usr/bin/mkdir -p '/usr/pgsql-11/lib'
/usr/bin/mkdir -p '/usr/pgsql-11/share/extension'
/usr/bin/mkdir -p '/usr/pgsql-11/share/extension'
/usr/bin/mkdir -p '/usr/pgsql-11/doc/extension'
/usr/bin/install -c -m 755  oracle_fdw.so '/usr/pgsql-11/lib/oracle_fdw.so'
/usr/bin/install -c -m 644 .//oracle_fdw.control '/usr/pgsql-11/share/extension/'
/usr/bin/install -c -m 644 .//oracle_fdw--1.1.sql .//oracle_fdw--1.0--1.1.sql  '/usr/pgsql-11/share/extension/'
/usr/bin/install -c -m 644 .//README.oracle_fdw '/usr/pgsql-11/doc/extension/'
/usr/bin/mkdir -p '/usr/pgsql-11/lib/bitcode/oracle_fdw'
/usr/bin/mkdir -p '/usr/pgsql-11/lib/bitcode'/oracle_fdw/
/usr/bin/install -c -m 644 oracle_fdw.bc '/usr/pgsql-11/lib/bitcode'/oracle_fdw/./
/usr/bin/install -c -m 644 oracle_utils.bc '/usr/pgsql-11/lib/bitcode'/oracle_fdw/./
/usr/bin/install -c -m 644 oracle_gis.bc '/usr/pgsql-11/lib/bitcode'/oracle_fdw/./
cd '/usr/pgsql-11/lib/bitcode' && /usr/lib64/llvm5.0/bin/llvm-lto -thinlto -thinlto-action=thinlink -o oracle_fdw.index.bc oracle_fdw/oracle_fdw.bc oracle_fdw/oracle_utils.bc oracle_fdw/oracle_gis.bc

4. Then I ran pg_upgrade with --check parameter.
-bash-4.2$ /usr/pgsql-11/bin/pg_upgrade -b /usr/pgsql-10/bin -B /usr/pgsql-11/bin -d /var/lib/pgsql/10/data -D /var/lib/pgsql/11/data –-check
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Creating dump of global objects                             ok
Creating dump of database schemas
                                                            ok
Checking for presence of required libraries                 fatal

Your installation references loadable libraries that are missing from the
new installation.  You can add these libraries to the new installation,
or remove the functions using them from the old installation.  A list of
problem libraries is in the file:
    loadable_libraries.txt

The file loadable_libraries.txt contains this error message: 
could not load library "$libdir/oracle_fdw": ERROR:  could not load library "/usr/pgsql-11/lib/oracle_fdw.so": /usr/pgsql-11/lib/oracle_fdw.so: undefined symbol: AllocSetContextCreate

I searched all the oracle-fdw issues but I haven't found a similar problem. Any ideas what's wrong or what needs to be done to correct the problem.

Thanks in advance for your help.

**Comment by laurenz** [comment]
That error means that oracle_fdw wasn't build with PostgreSQL v11, but with an earlier version.

The output from your `make` command looks like you forgot to run

    make clean

before building oracle_fdw. That way you probably reused object files built against v10.

**Comment by postgresnc** [comment]
Thank you very much, that appears to have been the problem.
I needed to execute "make clean" to do a clean up before rebuilding in postgresql 11.
After that, make and make install ran fine and pg_upgrade ran without errors or warnings. 

Thanks again.
