### ISSUE TITLE
Need rowid to disambiguate rows in a keyless ODS.

### ISSUE THREAD

**Issue by lembark** [laurenz/oracle_fdw#304]
I am pulling data from an table used to store events. The table lacks a surrogate key, the original intent was to use timestamps to disambiguate events. 

Catch: There are multiple otherwise-identical events per time unit.

Using timestap+rowid would allow me to at least select distinct rows from the table. 

Given the issue with describe not showing "rowid" and the special case of "rowid" being an intrinsic column, would it be reasonable to just include it as a special case and fake the describe output: It will be identical for all describe's of all tables, just pretend it's there...

**Comment by laurenz** [comment]
This is similar to #28.

Would the workarounds shown in that ticket solve your problem?

**Comment by laurenz** [comment]
I'm closing the ticket for inactivity.
Feel free to reopen it if you need more help with this issue.
