### ISSUE TITLE
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle

### ISSUE THREAD

**Issue by alexeyshishkin01** [laurenz/oracle_fdw#307]
hello, all!

I have the following issue:
```
psql --dbname=mmdb --username=mmuser -c "create server remote_server foreign data wrapper oracle_fdw options (dbserver '//localhost:1521/XE')"

[postgres@test-03 ~]$ psql --dbname=mmdb --username=mmuser -c "\des+ remote_server"
                                                       List of foreign servers
     Name      | Owner  | Foreign-data wrapper | Access privileges | Type | Version |           FDW options            | Description
---------------+--------+----------------------+-------------------+------+---------+----------------------------------+-------------
 remote_server | mmuser | oracle_fdw           |                   |      |         | (dbserver '//localhost:1521/XE') |
(1 row)

psql --dbname=mmdb --username=mmuser -c "create user mapping for mmuser server remote_server options (user 'system', password 'oraclepassword')"

[postgres@test-03 ~]$ psql --dbname=mmdb --username=mmuser -c "\deu+"
                          List of user mappings
    Server     | User name |                 FDW options
---------------+-----------+----------------------------------------------
 remote_server | mmuser    | ("user" 'system', password 'oraclepassword')
(1 row)

psql --dbname=mmdb --username=mmuser -c "create foreign table mm_table_01(id integer, title text) server remote_server options (schema 'system', table 'mm_table_02')"

[postgres@test-03 ~]$ psql --dbname=mmdb --username=mmuser -c "\d mm_table_01"
               Foreign table "public.mm_table_01"
 Column |  Type   | Collation | Nullable | Default | FDW options
--------+---------+-----------+----------+---------+-------------
 id     | integer |           |          |         |
 title  | text    |           |          |         |
Server: remote_server
FDW options: (schema 'system', "table" 'mm_table_02')

[postgres@test-03 ~]$ psql --dbname=mmdb --username=mmuser -c "select * from mm_table_01"
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
DETAIL:
[postgres@test-03 ~]$
```
why does it throw the error?

**Comment by alexeyshishkin01** [comment]
[postgres@test-03 ~]$ psql --dbname=mmdb --username=mmuser -c "select oracle_diag('remote_server');"
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
DETAIL:
[postgres@test-03 ~]$ psql --dbname=mmdb --username=mmuser -c "select oracle_diag();"
                         oracle_diag
-------------------------------------------------------------
 oracle_fdw 2.1.0, PostgreSQL 10.6, Oracle client 18.4.0.0.0
(1 row)

**Comment by laurenz** [comment]
There are many possible causes for this problem; it is an Oracle configuration problem.

My guess is that you have the same problem as #305. Read [this comment](/laurenz/oracle_fdw/issues/305#issuecomment-474488009) in particular. From your `oracle_diag()` output I see that `ORACLE_HOME` is missing in the PostgreSQL server's environment. This environment variable is needed for all Oracle access except with Instant Client. From your connect string it looks like you are using Oracle Express as a client (and server).

How you set the environment variable properly depends on you system startup procedure (`systemd`?). A restart of the PostgreSQL server is also required. You know you have succeeded when `ORACLE_HOME` shows up in the `oracle_diag()` output.

Other missing or wrongly set environment variables can also cause this error.

It can also be caused by a mixed up Oracle installations, e.g. when you copy or link Oracle libraries around (see #263).

See also #208, #254 (like #305), #218 (oracle_fdw binaries used with an incompatibly modified PostgreSQL server), #186 (perhaps like #218) and #133 (lack of file system permissions on the Oracle installation).

**Comment by alexeyshishkin01** [comment]
ORACLE_HOME is present during 'make' and in Postgres env.

I use Oracle Express 18c - is it supported?

**Comment by alexeyshishkin01** [comment]
do you find these warnings during 'make' critical?

[root@test-06 oracle_fdw-ORACLE_FDW_2_1_0]# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -I/usr/include/et -fPIC -I/opt/oracle/product/18c/dbhomeXE/sdk/include -I/opt/oracle/product/18c/dbhomeXE/oci/include -I/opt/oracle/product/18c/dbhomeXE/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/opt/pgpro/ent-10/include/server -I/opt/pgpro/ent-10/include/internal  -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_fdw.o oracle_fdw.c
oracle_fdw.c: In function ‘transactionCallback’:
oracle_fdw.c:5769:2: warning: enumeration value ‘XACT_EVENT_START’ not handled in switch [-Wswitch]
  switch(event)
  ^
oracle_fdw.c:5769:2: warning: enumeration value ‘XACT_EVENT_POST_PREPARE’ not handled in switch [-Wswitch]
oracle_fdw.c:5769:2: warning: enumeration value ‘XACT_EVENT_PRE_COMMIT_PREPARED’ not handled in switch [-Wswitch]
oracle_fdw.c:5769:2: warning: enumeration value ‘XACT_EVENT_COMMIT_PREPARED’ not handled in switch [-Wswitch]
oracle_fdw.c:5769:2: warning: enumeration value ‘XACT_EVENT_ABORT_PREPARED’ not handled in switch [-Wswitch]
oracle_fdw.c:5769:2: warning: enumeration value ‘XACT_EVENT_COMMIT_COMMAND’ not handled in switch [-Wswitch]
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -I/usr/include/et -fPIC -I/opt/oracle/product/18c/dbhomeXE/sdk/include -I/opt/oracle/product/18c/dbhomeXE/oci/include -I/opt/oracle/product/18c/dbhomeXE/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/opt/pgpro/ent-10/include/server -I/opt/pgpro/ent-10/include/internal  -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_utils.o oracle_utils.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -I/usr/include/et -fPIC -I/opt/oracle/product/18c/dbhomeXE/sdk/include -I/opt/oracle/product/18c/dbhomeXE/oci/include -I/opt/oracle/product/18c/dbhomeXE/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/opt/pgpro/ent-10/include/server -I/opt/pgpro/ent-10/include/internal  -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_gis.o oracle_gis.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -I/usr/include/et -fPIC -shared -o oracle_fdw.so oracle_fdw.o oracle_utils.o oracle_gis.o -L/opt/pgpro/ent-10/lib  -Wl,-rpath,\$ORIGIN/../lib  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/opt/pgpro/ent-10/lib',--enable-new-dtags  -L/opt/oracle/product/18c/dbhomeXE -L/opt/oracle/product/18c/dbhomeXE/bin -L/opt/oracle/product/18c/dbhomeXE/lib -lclntsh -L/usr/lib/oracle/12.2/client/lib -L/usr/lib/oracle/12.2/client64/lib -L/usr/lib/oracle/12.1/client/lib -L/usr/lib/oracle/12.1/client64/lib -L/usr/lib/oracle/11.2/client/lib -L/usr/lib/oracle/11.2/client64/lib -L/usr/lib/oracle/11.1/client/lib -L/usr/lib/oracle/11.1/client64/lib -L/usr/lib/oracle/10.2.0.5/client/lib -L/usr/lib/oracle/10.2.0.5/client64/lib -L/usr/lib/oracle/10.2.0.4/client/lib -L/usr/lib/oracle/10.2.0.4/client64/lib -L/usr/lib/oracle/10.2.0.3/client/lib -L/usr/lib/oracle/10.2.0.3/client64/lib
[root@test-06 oracle_fdw-ORACLE_FDW_2_1_0]#

**Comment by alexeyshishkin01** [comment]
this is 'make install' output:

[root@test-06 oracle_fdw-ORACLE_FDW_2_1_0]# make install
/bin/mkdir -p '/opt/pgpro/ent-10/lib'
/bin/mkdir -p '/opt/pgpro/ent-10/share/extension'
/bin/mkdir -p '/opt/pgpro/ent-10/share/extension'
/bin/mkdir -p '/opt/pgpro/ent-10/doc/extension'
/bin/install -c -m 755  oracle_fdw.so '/opt/pgpro/ent-10/lib/oracle_fdw.so'
/bin/install -c -m 644 .//oracle_fdw.control '/opt/pgpro/ent-10/share/extension/'
/bin/install -c -m 644 .//oracle_fdw--1.1.sql .//oracle_fdw--1.0--1.1.sql  '/opt/pgpro/ent-10/share/extension/'
/bin/install -c -m 644 .//README.oracle_fdw '/opt/pgpro/ent-10/doc/extension/'
[root@test-06 oracle_fdw-ORACLE_FDW_2_1_0]#

**Comment by alexeyshishkin01** [comment]
this is 'ldconfig' output:

[root@test-06 ~]# ldconfig
ldconfig: /opt/oracle/product/18c/dbhomeXE/lib/libexpat.so.1 is not a symbolic link

[root@test-06 ~]#

**Comment by alexeyshishkin01** [comment]
I also tested Oracle XE 11.2 with PostgreSQL 10.7 - the same error:
[postgres@test-07 ~]$ psql --dbname=mmdb --username=mmuser -c "select * from mm_table_01"
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
DETAIL:

at the same time:
[postgres@test-07 ~]$ sqlplus system/oraclepassword@//localhost:1521/XE

SQL*Plus: Release 11.2.0.2.0 Production on Fri Apr 12 23:04:45 2019

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL>

**Comment by alexeyshishkin01** [comment]
so, my current question if Oracle XE is supported?

**Comment by laurenz** [comment]
Yes, Oracle XE is supported and works fine (I use it for developing oracle_fdw).

You set `ORACLE_HOME` in the environment **of the shell**, so sqlplus and building oracle_fdw work.
However, you didn't set it in the environment **of the PostgreSQL server process**, and that is your problem.

You will have to configure the startup process for PostgreSQL. If you need help doing that, you'll have to tell me which operating system you are using and how your PostgreSQL startup procedure works.

The compiler warnings are unexpected and might well point to a problem. Most of all, they indicate that you are **not** using regular PostgreSQL, but some modified fork of it (the macro names in the warning do not occur in the PostgreSQL source code).

Judging from the names of the macros, I'd guess that these are just additional callback points that allow to hook extra functionality into PostgreSQL, and ignoring them is OK, but if you want certainty, you'll have to ask the authors of this PostgreSQL fork whether they support oracle_fdw or not.

**Comment by alexeyshishkin01** [comment]
ok, thanks, after setting up ORACLE_HOME in the environment of the Postgres server process it starts working!
