### ISSUE TITLE
impossible create extansion oracle_fdw

### ISSUE THREAD

**Issue by sabineCa** [laurenz/oracle_fdw#308]
Hello,
i'm trying to instal oracle_fdw on RHEL7 and i have some problem :

when i do:

    PATH=/usr/pgsql-10/bin:$PATH make

I have : 

```text
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_utils.o oracle_utils.c
oracle_utils.c:22:17: fatal error: oci.h: No such file or directory
 #include <oci.h>
                 ^
compilation terminated.
make: *** [oracle_utils.o] Error 1

so when i do make install i have : 

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_utils.o oracle_utils.c
oracle_utils.c:22:17: fatal error: oci.h: No such file or directory
 #include <oci.h>
                 ^
compilation terminated.
make: *** [oracle_utils.o] Error 1
```

and i can't create extension because i have this error : 

    create extension oracle_fdw;
    ERROR:  could not access file "$libdir/oracle_fdw": No such file or directory

can you help me please ?

**Comment by jkldv** [comment]
# here is what I did
# find oracle home
[oracle_fdw]$ locate oci.h
/export/home/oracle/product/12.1.0.2/db_1/precomp/public/sql2oci.h
/export/home/oracle/product/12.1.0.2/db_1/rdbms/public/oci.h   <-- home is everything before /rdbms
...

# build library
export ORACLE_HOME='/export/home/oracle/product/12.1.0.2/db_1'
make

# also, you'll probably want that oracle home added to your bashrc file (assuming linux here, but there is a windows equivalent

**Comment by laurenz** [comment]
oracle_fdw's `Makefile` includes `-I$(ORACLE_HOME)/rdbms/public` in `PG_CPPFLAGS`, so if you set `ORACLE_HOME` like you did in the environment of `make`, the build should work.

This is documented in the README:

> Set the environment variable ORACLE_HOME to the location of the Oracle
> installation.

Do I read that right that your problem is solved?

**Comment by sabineCa** [comment]
Hello, 
I don't have oracle installed on my server. i just installler instant client so when i do a locate, i have :
`locate oci.h
/opt/oracle/instantclient_11_2/sdk/include/oci.h
` 

i don't have rdms folder. how can i build library ?

**Comment by sabineCa** [comment]
hi ,
it's ok, i found it !
i did 
`export ORACLE_HOME=/opt/oracle/instantclient_11_2`
and
`ln -s /opt/oracle/instantclient_11_2 $ORACLE_HOME/sdk/include`

and it works !
thank you !
