### ISSUE TITLE
 Function to convert column type or include St_Geometry in oracle_fdw type conversion

### ISSUE THREAD

**Issue by naub1n** [laurenz/oracle_fdw#311]
Hi laurenz,

I try to convert an Oracle database to PostgreSQL database.
I want to import specific table in specific schema. It's easy for 'basic' table, I use `IMPORT FOREIGN SCHEMA "ORASCHEMA" LIMIT TO (mytable) FROM SERVER oradb INTO local_schema`.

But for ST_GEOMETRY type (ESRI ArcSDE), I must declare each column and specify a SQL request in table option like that:
```
CREATE FOREIGN TABLE local_schema.local_table (
    ID text,
    SHAPE geometry
) SERVER oradb OPTIONS (table '(SELECT ID, SDO_GEOMETRY(SDE.ST_asText(SHAPE)) AS SHAPE FROM oraschema.mytable)')
```
I don't know how oracle_fdw check columns type but is it possible to auto convert ST_GEOMETRY to GEOMETRY implementing SDO_GEOMETRY(SDE.ST_asText()) in Oracle query ?

**Comment by laurenz** [comment]
There is no support for ESRI in oracle_fdw.

Your solution looks like the correct one (except there is `')` missing in the end).

Sorry if this is a bit cumbersome, but you have to do it only once per table with a geometry. Of course the performance might not be great.

**Comment by naub1n** [comment]
> our solution looks like the correct one (except there is ') missing in the end).

I edit it

> Sorry if this is a bit cumbersome, but you have to do it only once per table with a geometry.

Ok. No possible to implement it in futur upgrade?
actually, I create a fonction to choose good postgreSQL type : 
```
CREATE OR REPLACE FUNCTION convertTypeOraTopsql(typeData text) RETURNS text AS $$
	DECLARE
		psqlType text;	
	BEGIN
		CASE typeData
			WHEN 'DATE' THEN psqlType='TIMESTAMP';
			WHEN 'NUMBER' THEN psqlType='NUMERIC';
			WHEN 'NVARCHAR2' THEN psqlType='VARCHAR';
			WHEN 'ST_GEOMETRY' THEN psqlType='GEOMETRY';
		END CASE;
		RETURN psqlType;
	END;
$$ LANGUAGE plpgsql;
```
Then I import table all_tab_columns, I read colmuns and data type by table and i add it in loop (sorry for french comments) : 
```
query := 'CREATE FOREIGN TABLE ' || schemasitousig || '.' || arow.table_name || '(';
-- Incrémentation de chaque déclaration de colonne avec le bon Type compatible PostgreSQL
for col in 
	SELECT "column_name", "data_type", "owner" FROM public.all_tab_columns WHERE table_name=arow.table_name
loop
	query := query || col.column_name || ' ' || aesn_pgis_interne.convertTypeOraTopsql(col.data_type) || ',';
end loop;
-- Suppression de la virgule en trop
query := substring(query from 1 for length(query)-1);
-- Pas de schéma à déclarer car l'option 'table' sera une requête SQL
query := query || ') SERVER oradb OPTIONS (table ''(SELECT ';
-- Incrémentation de chaque déclaration de colonne dans la requête Oracle
for col in 
	SELECT "column_name", "data_type", "owner" FROM public.all_tab_columns WHERE table_name=arow.table_name
loop
	-- Prise en compte du cas particulier des colonnes de type ST_GEOMETRY
	if (col.data_type = 'ST_GEOMETRY') then
		-- Le champ doit être converti en Type lisible par oracle_fdw, c'est à dire SDO_GEOMETRY
		query := query || 'SDO_GEOMETRY(SDE.ST_asText(' || col.column_name || ')) AS ' || col.column_name || ',';
	else
		query := query || col.column_name || ',';
	end if;
end loop;
-- Suppression de la virgule en trop
query := substring(query from 1 for length(query)-1);
-- Fin de déclaration de la requête SQL d'Oracle en spécifiant le schéma et la table
query := query || ' FROM ' || col.owner || '.' || arow.table_name || ')'');';
```

**Comment by laurenz** [comment]
It looks like you are re-implementing [ora_migrator](../../../cybertec-postgresql/ora_migrator).

You can either try it out or use it as inspiration for your solution.

**Comment by naub1n** [comment]
thank you, I do not know this extension!
I keep my solution for now, but I'll follow all this.
Thanks for your work and your time!
