### ISSUE TITLE
Issue when building oracle_dfw in windows using Visual Studio 2019

### ISSUE THREAD

**Issue by Johnsonxiong** [laurenz/oracle_fdw#314]
Hi, there. I am pretty new about the dataBase. But was assigned a project need to migrate Oracle database to PostGres. And I found this potential tool oracle_fdw. But was stuck in even building the tool... 
The information that I know so far. 
For the Oracle headers and libraries.  -- installed basic, sdk and sqlplus 18.5 in "C:\Oracle\instantclient_18_5"
Microsoft Visual Studio -- community 2019
For the PostGres database. -- Because it comes with the application that I am going to use. So I am not sure what version it is using. The location is "C:\Program Files\ModelCenterServer\pgsql"
Here is the screenshot of what's in the folder. 
![image](https://user-images.githubusercontent.com/28211299/56684493-e0449380-669d-11e9-929a-b65045853371.png)

Then I download the oracle_fdw-2.1.0.zip and unzip it under the same folder of the PostGres dataBase. "C:\Program Files\ModelCenterServer\pgsql".

Before build the Oracle_fdw, I tried to run >sqlplus Rome/root@//10.10.14.133:1521/XE
![image](https://user-images.githubusercontent.com/28211299/56685219-6ad9c280-669f-11e9-85b9-dc76fc519e2c.png)
And I can connect to the remote Oracle dataBase. So I assume that the environment for Oracle is set up correctly.

In the end, open "C:\Program Files\ModelCenterServer\pgsql\oracle_fdw-2.1.0\oracle_fdw\msvc\oracle_fdw.sln" in Visual Studio and build the project. Then it shows error as below:
 
1>oracle_fdw.c
1>C:\Program Files\Phoenix Integration\ModelCenterServer\pgsql\oracle_fdw-2.1.0\oracle_fdw.c(8): fatal error C1083: Cannot open include file: 'postgres.h': No such file or directory
1>oracle_gis.c
1>C:\Program Files\Phoenix Integration\ModelCenterServer\pgsql\oracle_fdw-2.1.0\oracle_gis.c(15): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory
1>oracle_utils.c
1>C:\Program Files\Phoenix Integration\ModelCenterServer\pgsql\oracle_fdw-2.1.0\oracle_utils.c(12): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
1>oracle_msvc.c
1>C:\Program Files\Phoenix Integration\ModelCenterServer\pgsql\oracle_fdw-2.1.0\oracle_fdw.h(13): fatal error C1083: Cannot open include file: 'postgres_ext.h': No such file or directory
1>Generating Code...
1>Done building project "oracle_fdw.vcxproj" -- FAILED.

Any help would be appreciated.

**Comment by laurenz** [comment]
I have little knowledge of Visual Studio.

I use the command line to build oracle_fdw with the following script:

    REM needs Visual Studio 2013

    set ORACLE_HOME=C:\MinGW\msys\1.0\home\lanadvall\instantclient64_10_2
    set CODE_DIR=C:\MinGW\msys\1.0\home\lanadvall\oracle_fdw
    set PGSQL_DIR=C:\MinGW\msys\1.0\home\lanadvall\pg64_10

    cl /Ox /GL /Zi /LD /MD /W4 /wd4200 /wd4244 /wd4267 /wd4389 /wd4018 /wd4996 /wd4100 /wd4127 /D_CRT_SECURE_NO_WARNINGS /I %ORACLE_HOME%\sdk\include /I %CODE_DIR% /I %PGSQL_DIR%\include\server\port\win32_msvc /I %PGSQL_DIR%\include\server\port\win32 /I %PGSQL_DIR%\include /I %PGSQL_DIR%\include\server /I %PGSQL_DIR%\include\internal %CODE_DIR%\oracle_fdw.c %CODE_DIR%\oracle_utils.c %CODE_DIR%\oracle_gis.c %PGSQL_DIR%\lib\postgres.lib %ORACLE_HOME%\sdk\lib\msvc\oci.lib

If you use the EDB PostgreSQL binaries, why don't you use the ready made Windows binaries I offer for download rather than building it yourself?

**Comment by Johnsonxiong** [comment]
Hi, Laurenz. Thanks for your quick reply. When you mentioned  "ready made Windows binaries", do you mean the zip files in "https://github.com/laurenz/oracle_fdw/releases/tag/ORACLE_FDW_2_1_0"? Like "oracle_fdw-2.1.0-pg10-win64.zip"? If so, then I guess what I need to do is figure out what pg version is been used and then follow the instructions by "installing the oracle_fdw" step by step?

**Comment by laurenz** [comment]
Yes, I mean exactly those files.

You can find your PostgreSQL version with

    SHOW server_version;

If you use the binaries, you don't have to build the software. Just follow the instructions in [Installing the extension](/laurenz/oracle_fdw#installing-the-extension). The files must be placed in the existing subdirectories of your PostgreSQL installation, `oracle_fdw.dll` into `lib` and so on.

Don't forget to add the Oracle libraries to the `PATH` and restart PostgreSQL so that it has the new setting in its environment.

**Comment by Johnsonxiong** [comment]
Hi, laurenz. Thanks for your reply. I have placed the oracle_fdw files into the PostreSQL installation folder. And tried to "create extension oracle_fdw" , but get error like this:

********** Error **********

ERROR: PostgreSQL version "9.6.3" not supported by oracle_fdw
SQL state: 39000
Hint: You'll have to update PostgreSQL to a later minor release.

But I did not add the Oracle libraries to the Path yet. Because I dont know how in Windows. Could you explain a little bit more so that I can finish adding Oracle to the path and try again.

**Comment by laurenz** [comment]
First, you'll have to upgrade to 9.6.9 or later, because there was a bugfix that introduced an incompatible change.

How to change environment variables on Windows: start the &ldquo;Control Center&rdquo; and then (I think) select &ldquo;System&rdquo; / &ldquo;Advanced Settings&rdquo; / &ldquo;Environment&rdquo; or similar ( I don't have Windows, so I cannot check). The edit the `PATH` **System** environment variable and add the directory that contains `oci.dll`.

A web search will easily give you better instructions than mine.

**Comment by Johnsonxiong** [comment]
Hi, I get it. I just dont sure add what path to the PATH. Because I was little confused by the ORACLE_HOME setting or so for Linux. I will upgrade and try again. Thanks again. 
So if I am only been allowed to use Postgres 9.6.3. Is it impossible to use oracle_fdw?

**Comment by laurenz** [comment]
Yes, it is impossible to use oracle_fdw with 9.6.3.
It is *always* commendable to use the latest minor release, in this case 9.6.12.

The `PATH` has to contain the directory where `oci.dll` is.
With Oracle Instant Client you don't need `ORACLE_HOME`.

**Comment by Johnsonxiong** [comment]
Hi, Laurenz. Thanks for your patience and quick replies. I should come here and write a issue report instead of figuring out nothing by myself! 
I really appreciate your help. I hope once I finished the upgrade, I could use oracle_fdw in the end. 
Thanks again.

**Comment by laurenz** [comment]
You are welcome. I don't mind answering clear questions.

In a way, every question answered in public saves me a lot of work - that way others can find the issue and solve their problem without asking me.

**Comment by Johnsonxiong** [comment]
Hi, laurenz. Just let you know that I installed the oracle_dfw successfully finally after upgrading my Postgres database! Thanks for your help and creating this great tool. Below is what I have done to upgrade Postgres 9.6.3 -> 9.6.12. Hope it might help someone like me.

**Minor upgrade Postgres 9.6.3 -> 9.6.12(latest release).** [refer](https://www.postgresql.org/docs/current/upgrading.html)
    

- StopPostgres server by running `>pg_ctl stop` in a cmd window.(if shows "pg_ctl: no database directory specified and environment variable PGDATA unset", it means that need to specify data_directory of the server) Then in query tool(I use pgAdmin 4), run `SHOW data_directory;` to get the data directory location. In the end I run `pg_ctl stop -D "C:\ProgramData\ModelCenterServer\repository\metadata"` in a cmd window and it shun down the server. 

- Go to [download](https://www.enterprisedb.com/download-postgresql-binaries) the 9.6.12 binary files. Unzip the zip file and go to location like this "_postgresql-9.6.12-2-windows-x64-binaries\pgsql\bin_". Copy all the files and replace the files in the old 
postgresql version folder. 

- Start the server again by running `pg_ctl start -D "C:\ProgramData\ModelCenterServer\repository\metadata"` in a cmd window. (If shows "LOG:  could not create file "postmaster.opts": Permission denied" error, it means that you dont have full control on the data directory, need to go to that folder and give full control of the user you are using)

- Restart query tool, I used pgAdmin 4 and run `SHOW server_version;` it will show 9.6.12, then it is been upgraded successfully. 

Then you can just follow the instruction to use the tool oracle_fdw. Enjoy! And laurenz is really helpful if you are stuck on anything using this too. Post an issue if you are stuck and it will save you and others a lot of time. Thanks agian, laurenz.
