### ISSUE TITLE
invalid byte sequence for encoding "UTF8": 0xd1 0x4f

### ISSUE THREAD

**Issue by gonxalo2000** [laurenz/oracle_fdw#317]
```
#  select wtrnomfun  from wtrrecli where WTRCEDULAI = 9912519 and wtrmanro=797;
ERROR:  invalid byte sequence for encoding "UTF8": 0xd1 0x4f
CONTEXT:  converting column "wtrnomfun" for foreign table scan of "wtrrecli", row 1
```

Configuration:

POSTGRES:

```
#  SELECT oracle_diag('sefi');
                                       oracle_diag
-----------------------------------------------------------------------------------------
 oracle_fdw 2.1.0, PostgreSQL 9.6.11, Oracle client 10.2.0.5.0, Oracle server 11.2.0.4.0
(1 row)

#  SHOW server_encoding;
 server_encoding
-----------------
 UTF8
(1 row)
```

ORACLE:

```
SQL> SELECT value FROM nls_database_parameters WHERE parameter = 'NLS_CHARACTERSET';
VALUE
----------------------------------------
WE8ISO8859P1

SQL> 


SQL> select wtrnomfun  from wtrrecli where WTRCEDULAI = 9912519 and wtrmanro=797   ;    
WTRNOMFUN
------------------------
RAÑO CALVELO MARIA ELENA

SQL>
```

The problem is the Ñ character, but now i think the character is in the oracle characterset.

**Comment by laurenz** [comment]
That should work just fine. What is the result you get in PostgreSQL for

    SHOW server_encoding;

It looks like no conversion is done for the &ldquo;&Ntilde;&rdquo;.

Did you set the `nls_lang` option on the FDW? What do you get for

    \dew+

in `psql`?

**Comment by gonxalo2000** [comment]
# SHOW server_encoding;
 server_encoding
-----------------
 UTF8
(1 row)
#

# \dew+
                                                                  List of foreign-data wrappers
    Name    |  Owner   |      Handler       |      Validator       | Access privileges |                FDW Options
          |         Description
------------+----------+--------------------+----------------------+-------------------+----------------------------------
----------+-----------------------------
 oracle_fdw | postgres | oracle_fdw_handler | oracle_fdw_validator |                   | (nls_lang 'AMERICAN_AMERICA.WE8IS
O8859P1') | Oracle foreign data wrapper
(1 row)

grp=#

**Comment by laurenz** [comment]
There is your problem, you set the Oracle client encoding to a wrong value.

You can reset it with

    ALTER FOREIGN DATA WRAPPER oracle_fdw OPTIONS (DROP nls_lang);

**Comment by gonxalo2000** [comment]
Tks a lot! It work. Originally i didn't set nls_lang, but i had the chr(0) problem.... i read other issues and fix the problem but change the nls_lang and didn't change it back.

Tks again.
