### ISSUE TITLE
Oracle table "schema"."table" for foreign table "table_name" does not exist or does not allow read access

### ISSUE THREAD

**Issue by odijh** [laurenz/oracle_fdw#318]
hello, 

i'have some trouble with this error, while i create foreign table, it's work in postgres, but not for oracle side, table didn't show up.. 
im already install extension, foreign data wrapper, data mapping

how can i solve this?
thanks

**Comment by laurenz** [comment]
All I know after reading your report is that you have some kind of problem, which is not enough to help you.

Can you copy and paste the steps you perform (ideally a small, simple example that exhibits the problem well), including the error messages you get, and tell me how the observed behaviour diverges fro the desired behaviour?

**Comment by laurenz** [comment]
I'll close this for inactivity. Please don't hesitate to reopen it if you have more details to your question.
