### ISSUE TITLE
oracle_fdw 2.1.0 - ora-00972 Identifier is too long

### ISSUE THREAD

**Issue by XavierUrbain** [laurenz/oracle_fdw#319]
Hello,

I'm trying to create a foreign table in a PostgresQL Server 9.6 using the oracle_fdw.

Here the details of oracle_diag : "oracle_fdw 2.1.0, PostgreSQL 9.6.12, Oracle client 12.2.0.1.0, Oracle server 11.2.0.3.0"

The installation was ok, the foreign server is created, the user mapping ok, the foreign table is created without errors. 
When I try to do a select on the foreign table, I receive the following error
"ERROR: error describing remote table: OCIStmtExecute failed to describe table DETAIL: ORA-00972: identifier is too long SQL state: HV00M"

In another Postgresql Server version 9.2, we use the oracle_fdw version 1.1. Here the detail of the oracle_diag function : "oracle_fdw 2.1.0, PostgreSQL 9.2.24, Oracle client 12.2.0.1.0, Oracle server 11.2.0.3.0"

Do I need to install the version 1.1 of the oracle_fdw ?

Thank you,
Xavier

**Comment by laurenz** [comment]
If you have extension version 1.0 somewhere, you should definitely run

    ALTER EXTENSION oracle_fdw UPDATE;

but that is unrelated to your problem.

To say more, I'd need to see your foreign table definition, but my guess is that it looks somewhat like this:

    CREATE FOREIGN TABLE xxx (...) SERVER s
       OPTIONS (table '(SELECT complicated_expression FROM tab ...)');

Then Oracle automatically chooses a long and complicated alias for the column that it cannot digest itself.

The solution would be to explicitly specify a short alias:

    CREATE FOREIGN TABLE xxx (...) SERVER s
       OPTIONS (table '(SELECT complicated_expression AS short_alias FROM tab ...)');

**Comment by XavierUrbain** [comment]
Hi Laurent,

It was exactly the case. One column has an identifier too long (31 characters), I remove it and it was working. 
I will rename the column by a short alias.

Thank you for your answer.
You can close this ticket.
Xavier
