### ISSUE TITLE
Cannot create user mapping

### ISSUE THREAD

**Issue by lee-gravity** [laurenz/oracle_fdw#321]
I'm using the following versions:

```
postgres=# SELECT oracle_diag('oradb');
                                       oracle_diag
-----------------------------------------------------------------------------------------
 oracle_fdw 2.0.0, PostgreSQL 9.6.13, Oracle client 12.2.0.1.0, Oracle server 11.2.0.2.0
```

I have also tried version 2.10 and the behaviour is the same.

I have run the following steps:

Compiled and installed oracle_fdw

Connect to PG as super user - postgres

    create server ORADB foreign data wrapper oracle_fdw options (dbserver '//server:port/sid');

    GRANT USAGE ON FOREIGN SERVER oradb to orauser;

Connect as to PG as user orauser

    CREATE USER MAPPING FOR orauser server ORADB options (user 'user', password 'pwd');

    ERROR:  server "oradb" does not exist

I do not understand this when I have created the server and granted access to the user orauser. I would therefore assume this is a bug.

I can create a mapping for the postgres super user and create a foreign table to my Oracle database that works as expected.

Kind Regards

**Comment by lee-gravity** [comment]
I've tried multiple versions on oracle_fdw and the Oracle client and I still get the same issue. Is there something I'm missing here i.e. a grant for the user?

**Comment by laurenz** [comment]
That is strange, and I cannot explain it right away.

What do you get when you run `\des+ oradb` in `psql`?

**Comment by lee-gravity** [comment]
postgres=# \des+ oradb
                                                         List of foreign servers
 Name  |  Owner  | Foreign-data wrapper | Access privileges | Type | Version |                 FDW Options                 | Description
-------+---------+----------------------+-------------------+------+---------+---------------------------------------------+-------------
 oradb | orauser | oracle_fdw           | orauser=U/orauser |      |         | (dbserver '//centos7.internal.lan:1521/XE') |
(1 row)

I tried changing the ownership of the server with:

ALTER SERVER ora db OWNER TO eraser; 

Which it did as you can see but it makes no difference.

**Comment by lee-gravity** [comment]
I've also tried this on the following versions:

SELECT oracle_diag();
                                                               oracle_diag
------------------------------------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.1.0, PostgreSQL 11.3, Oracle client 12.2.0.1.0, ORACLE_HOME=/usr/lib/oracle/12.2/client64/, TNS_ADMIN=/var/lib/pgsql/oracle

and I still get the same problem.

I assume I'm missing a step. 

Does the user 'orauser' need any specific privileges for this to work?

User has the following:

\du orauser
           List of roles
 Role name | Attributes | Member of
-----------+------------+-----------
 orauser   |            | {}

I've also granted usage on the server from the postgres superuser.

postgres=# GRANT USAGE ON FOREIGN SERVER oradb to orauser;
GRANT

**Comment by laurenz** [comment]
I am absolutely clueless; this should work just as you intend.
Can user `orauser` call `SELECT oracle_diag('oradb')` successfully?

It doesn't matter which version of oracle_fdw you use, this seems to be a generic permission problem.

Just checking: are you using plain open source PostgreSQL or some fork?

**Comment by lee-gravity** [comment]
postgres=# SELECT oracle_diag('oradb');
                                      oracle_diag
---------------------------------------------------------------------------------------
 oracle_fdw 2.1.0, PostgreSQL 11.3, Oracle client 12.2.0.1.0, Oracle server 11.2.0.2.0
(1 row)

Yes using standard PostgreSQL from via links from PostgreSQL site. Running on CentOS 6.10 if that matters.

If I run from the orauser which I want to create the mapper for I get:

orauser=>  SELECT oracle_diag('oradb');
ERROR:  function oracle_diag(unknown) does not exist
LINE 1: SELECT oracle_diag('oradb');
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by lee-gravity** [comment]
The user 'orauser' can't seem to see the oracle_fdw extension. Not sure if this is relevant:

orauser-> \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description
---------+---------+------------+------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(1 row)

Sorry also upgraded to PG 11 which made no difference.

Used following 

yum install postgresql11
yum install postgresql11-server
yum install postgresql11-devel.x86_64

Again these are from standard PostgreSQL repository
i.e.
https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-$releasever-$basearch

**Comment by laurenz** [comment]
Ah, we are getting closer.

It seems that the extension is installed in a schema that is not on `orauder`'s search path, or there are permissions lacking.

What do you get in `psql` for the following commands:

    \dx oracle_fdw

    \dn+

**Comment by lee-gravity** [comment]
From the user: orauser

orauser=> \dx oracle_fdw
     List of installed extensions
 Name | Version | Schema | Description
------+---------+--------+-------------
(0 rows)

orauser=> \dn+
                          List of schemas
  Name  |  Owner   |  Access privileges   |      Description
--------+----------+----------------------+------------------------
 public | postgres | postgres=UC/postgres+| standard public schema
        |          | =UC/postgres         |
(1 row)

SHOW search_path;
   search_path
-----------------
 "$user", public

**Comment by laurenz** [comment]
The only explanation is that the connection with `orauser` are made to a different database...

Verify with `\set` in `psql`.

**Comment by lee-gravity** [comment]
The output from \set as below:

orauser=> \set
AUTOCOMMIT = 'on'
COMP_KEYWORD_CASE = 'preserve-upper'
DBNAME = 'orauser'
ECHO = 'none'
ECHO_HIDDEN = 'off'
ENCODING = 'UTF8'
FETCH_COUNT = '0'
HISTCONTROL = 'none'
HISTSIZE = '500'
HOST = '/var/run/postgresql'
IGNOREEOF = '0'
LAST_ERROR_MESSAGE = ''
LAST_ERROR_SQLSTATE = '00000'
ON_ERROR_ROLLBACK = 'off'
ON_ERROR_STOP = 'off'
PORT = '5432'
PROMPT1 = '%/%R%# '
PROMPT2 = '%/%R%# '
PROMPT3 = '>> '
QUIET = 'off'
SERVER_VERSION_NAME = '11.3'
SERVER_VERSION_NUM = '110003'
SHOW_CONTEXT = 'errors'
SINGLELINE = 'off'
SINGLESTEP = 'off'
USER = 'orauser'
VERBOSITY = 'default'
VERSION = 'PostgreSQL 11.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23), 64-bit'
VERSION_NAME = '11.3'
VERSION_NUM = '110003'

**Comment by laurenz** [comment]
Yes, and I think that either `HOST` or `PORT` or `DBNAME` must be different than when you ran `CREATE EXTENSION` as superuser.

`DBNAME = 'orauser'` looks particularly suspicious.
Don't forget that if you connect with `psql`, the default database name is the same as the user name.
Perhaps the extension was created in database `postgres`, and now you are looking for it in database `orauser`.

**Comment by lee-gravity** [comment]
Ok great it's working now. I'm a bit new to PostgreSQL so my understanding may be lacking.

I connected to the database orauser as the postgres superuser then added the extension, created the server and granted usage on the server to orauser. From there added the mapping while connected as the user orauser.

Thanks for your help.
