### ISSUE TITLE
Cannot find issue related to: Error connecting to Oracle: OCIEnvCreate

### ISSUE THREAD

**Issue by MarvinDBA** [laurenz/oracle_fdw#323]
Hi,

I have an installed oracle_fdw.
I have set the ORACLE_HOME and LD_LIBRARY_PATH, the same way it is required for the installation of this contribution.
I created a foreign table but I get an error:

```
dboracle=> \d oratab_demo_applications
                         Foreign table "public.oratab_demo_applications"
         Column          |          Type          | Collation | Nullable | Default | FDW options
-------------------------+------------------------+-----------+----------+---------+--------------
 application_id          | integer                |           | not null |         | (key 'true')
 application_name        | character varying(20)  |           |          |         |
 application_description | character varying(200) |           |          |         |
Server: oradb
FDW options: (schema 'topaz', "table" 'DEMO_APPLICATIONS')

dboracle=> select * from oratab_demo_applications;
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
DETAIL:
dboracle=>
```

Can someone tell what is wrong?

Thanks by advance.

**Comment by laurenz** [comment]
This is a generic error that means that you set up Oracle client wrongly.

See for example #307 and the many other issues linked from there for things to try.

Often the problem are bad or missing environment variables.

**Comment by MarvinDBA** [comment]
The issue was a difficult to find, but it now solved.
There was a wrong entry in the config file for running ldconfig.
I just defined the vaiables ORACLE_HOME and LD_LIBRARY_PATH, and ran ldconfig just after.
These variables must always be defined for the user owner owning the PostgreSQL server (at least, as long as the extension is used).

**Comment by laurenz** [comment]
Then it is an exact duplicate of #161.
Thanks for the feedback!
