### ISSUE TITLE
PANIC:  ERRORDATA_STACK_SIZE exceeded

### ISSUE THREAD

**Issue by kimjand** [laurenz/oracle_fdw#328]
I have been using oracle_fdw for a while now, and I have run into a few problems, that when triggered cause a database crash.

The first scenario happens when cancelling a query, then I get a message sequence like this:

WARNING:  AbortSubTransaction while in ABORT state
WARNING:  did not find subXID 202809 in MyProc
ERROR:  canceling statement due to user request
ERROR:  error rolling back to savepoint: OCIStmtExecute failed to set savepoint
DETAIL:  ORA-12152: TNS:unable to send break message

Then issuing a rollback causes the following (ultimately resulting in a database crash):

WARNING:  AbortSubTransaction while in ABORT state
WARNING:  did not find subXID 202808 in MyProc
WARNING:  AbortSubTransaction while in ABORT state
WARNING:  did not find subXID 202807 in MyProc
WARNING:  AbortSubTransaction while in ABORT state
WARNING:  did not find subXID 202806 in MyProc
WARNING:  AbortSubTransaction while in ABORT state
WARNING:  did not find subXID 202805 in MyProc
ERROR:  error rolling back to savepoint: OCIStmtExecute failed to set savepoint
DETAIL:  ORA-03114: not connected to ORACLE
ERROR:  error rolling back to savepoint: OCIStmtExecute failed to set savepoint
DETAIL:  ORA-03114: not connected to ORACLE
ERROR:  error rolling back to savepoint: OCIStmtExecute failed to set savepoint
DETAIL:  ORA-03114: not connected to ORACLE
ERROR:  error rolling back to savepoint: OCIStmtExecute failed to set savepoint
DETAIL:  ORA-03114: not connected to ORACLE
ERROR:  error rolling back to savepoint: OCIStmtExecute failed to set savepoint
DETAIL:  ORA-03114: not connected to ORACLE
PANIC:  ERRORDATA_STACK_SIZE exceeded

The second scenario occurs in long running sessions, usually if the Oracle snapshot have expired. Do a rollback or commit results in the following:

WARNING:  AbortSubTransaction while in ABORT state
WARNING:  AbortSubTransaction while in ABORT state
WARNING:  AbortSubTransaction while in ABORT state
WARNING:  AbortSubTransaction while in ABORT state
ERROR:  failed to re-find shared lock object
ERROR:  failed to re-find shared lock object
ERROR:  failed to re-find shared lock object
ERROR:  failed to re-find shared lock object
ERROR:  failed to re-find shared lock object
PANIC:  ERRORDATA_STACK_SIZE exceeded

Interestingly enough the crash can usually be dodged by rollback to a save point, and then issuing a new query before attempting a commit or full rollback.
That is:
1. run query with failure.
2. rollback to savepoint
3. run succesful query on the same foreign server as in 1.
4. rollback or commit

I have experienced these problems on Postgres 11.0-11.3 the messages listed above are from 11.3
Unfortunatly I do not recall if the second scenario was a problem on Postgres 10, but the first was, but then it didn't cause a database crash.
We are running oracle_fdw against different releases of Oracle 12c.
I have tried using different versions of the Oracle client, from 12.1 to 18.5.
oracle_diag() output:
oracle_fdw 2.2.0devel, PostgreSQL 11.3 (Debian 11.3-1.pgdg90+1), Oracle client 18.5.0.0.0
I believe the source was at commit 6c544da74449c1eba4600f90716436ff254b37de, when we did the latest build. But the problem has been present for a while.

Is there anything I can do to help solving this?

**Comment by kimjand** [comment]
I forgot to add that I ran the above with max_parallel_workers = 0, since parallel workers also cause problems.

**Comment by laurenz** [comment]
A crash should definitely not happen, and the warning suggests that something is going wrong.

Can you come up with a reproducible test case?

**Comment by laurenz** [comment]
I don't think commit 6c544da has changed anything here.

**Comment by kimjand** [comment]
> 
> 
> A crash should definitely not happen, and the warning suggests that something is going wrong.
> 
> Can you come up with a reproducible test case?

I will try to work out a test case.

**Comment by laurenz** [comment]
Any news on this?

**Comment by kimjand** [comment]
> 
> 
> Any news on this?

Unfortunately, no. I have so far not been able to work out a simple test case. I only seem to hit this in a long running session.

**Comment by laurenz** [comment]
Shall I leave the issue open?

**Comment by laurenz** [comment]
I'll close this as "inactive".
Please don't hesitate to reopen it if you can think of a way how I can reproduce this.

**Comment by kimjand** [comment]
I have not been able to reproduce this after upgrading to PostgreSQL 11.4. 
After updating oracle_fdw, I get the correct error messages for the savepoint failure, and the current situation is that database no longer crashes.

    Thanks,
        Kim Johan Andersson

**Comment by laurenz** [comment]
Thanks for the clarification!
