### ISSUE TITLE
Oracle to Postgres Sync

### ISSUE THREAD

**Issue by venkatsusarla** [laurenz/oracle_fdw#331]
Hello Laurenz,

I have a requirement to daily refresh data in Postgres tables from Oracle tables, this will result in n-1 day data in Postgres.

There are around 1200 tables ( 30 tables more than 1gb, max size of the table right now is 12gb).

Do you think that using oracle_fdw to connect to oracle to get data and create materialized views on postgres db would be right approach?, where every day we just refresh the mview and we get n-1 data.

Your inputs would be very valuable.

Regards,
Venkat

**Comment by laurenz** [comment]
Yes, I think that this is a good architecture, and I expect it to work well.

It is trivial if you always want to refresh the whole data, then you can user a materialized view.

If you want &ldquo;incremental refresh&rdquo;, you'd have to implement the logic yourself my using a PostgreSQL table and running `INSERT INTO ... SELECT FROM foreign table WHERE ...` on it.
The difficult thing would be to come up with the correct `WHERE` clause.

**Comment by venkatsusarla** [comment]
Thanks Laurenz , for your reply , and yes as you said the incremental loading becomes complex for implementation as well as maintenance.

Regards,
Venkat
