### ISSUE TITLE
Performance Impact of oracle_fdw

### ISSUE THREAD

**Issue by venkatsusarla** [laurenz/oracle_fdw#333]
Hi Laurenz,

Referencing my old conversation, just wanted to know if there will be significant impact on the oracle database , if there is heavy access of data from oracle to postgres using oracle_fdw.

Regards,
Venkat

Thanks Laurenz , for your reply , and yes as you said the incremental loading becomes complex for implementation as well as maintenance.

Regards,
Venkat

_Originally posted by @venkatsusarla in https://github.com/laurenz/oracle_fdw/issues/331#issuecomment-507179135_

**Comment by laurenz** [comment]
Sorry; I wouldn't have closed the other issue if I had known that you have more questions.

If you refresh a materialized query based on an Oracle foreign table, you will run part of the query on the Oracle database. For example, if it is a regular Oracle table and the materialized view is defined on `SELECT * FROM foreign_table`, that will be a sequential scan on Oracle.
If you have `WHERE` conditions or such, oracle_fdw will try to push them down.

You can run

    EXPLAIN (VERBOSE) SELECT ...;

on the query that defines the materialized view, then you will see the Oracle statement and its execution plan, which can give you an idea of the required impact.

**Comment by venkatsusarla** [comment]
Thanks a lot  Laurenz, let me analyze this and come back to you.Could you please keep this thread open for couple of days ?

Regards,
Venkat

**Comment by laurenz** [comment]
Sure, I won't repeat my mistake.

**Comment by venkatsusarla** [comment]
Hi Laurenz,

Thanks for keeping this question open, appreciate it.

We have tested the above approach and it is working as per our expectations. Now, the challenge we have faced is, when a structural changes happen on oracle table (like adding or dropping a column) for which we have defined foreign tables, it doesn't get cascaded to foreign tables on PostgreSQL (Which i think is correct). 

My question is, do we have a way to automate this, did you face this kind of issue anytime in your experience?

Approach I am thinking of :
------------------------------
- Create a trigger on Oracle for the tables so that it triggers when there is a ddl on table (not sure if it works for column alter or drop or add)
- Then this trigger alters the foreign table too. 

Please let me know your valuable inputs.

Regards,
Venkat

**Comment by laurenz** [comment]
I cannot think of a way to do that automatically.

That would have to be run by a trigger in Oracle, and I cannot see how you can issue PostgreSQL DDL commands from an Oracle trigger.

Alternatively, you could define PostgreSQL foreign tables on the Oracle metadata and poll them for changes regularly so you can redefine a foreign table (any the materialized view based on it), but that is complicated and cannot run automatically whenever the Oracle table changes.

I'd try to establish a policy that DDL statements on that Oracle table are not to be performed without also adapting the PostgreSQL foreign table definition.

**Comment by laurenz** [comment]
Is there anything more I can help you with? I don't want to close this issue too quickly again :^)

**Comment by venkatsusarla** [comment]
Hi Laurenz,

Thanks a lot for your help, that's it for now:), you can close it.
