### ISSUE TITLE
Character set problem - AL32UTF8

### ISSUE THREAD

**Issue by ejcrotty** [laurenz/oracle_fdw#334]
I have read the Issues and failed at how to solve this problem - 

I got this error :

BEGIN
insert into LTC.F_LTC_SERV_DTL
SELECT * FROM LTC_orcl.F_LTC_SERV_DTL ;
psql:tab_mig.sql:11: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x2f
CONTEXT:  converting column "sd_ok_reasn_text" for foreign table scan of "f_ltc_serv_dtl", row 92199

( The text is Cafe' - with a little accent on the e )

Oracle is AL32UTF8,  So I change the wrapper to match it. 
    OPTIONS (nls_lang 'AMERICAN_AMERICA.AL32UTF8'); 

-- and still get  the same  error

BEGIN
insert into LTC.F_LTC_SERV_DTL
SELECT * FROM LTC_orcl.F_LTC_SERV_DTL ;
psql:tab_mig.sql:11: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x2f
CONTEXT:  converting column "sd_ok_reasn_text" for foreign table scan of "f_ltc_serv_dtl", row 92199

so I change wrapper to UTF8

    OPTIONS (nls_lang 'AMERICAN_AMERICA.UTF8'); 

and get a new error.

BEGIN
insert into LTC.F_LTC_SERV_DTL
SELECT * FROM LTC_orcl.F_LTC_SERV_DTL ;
psql:tab_mig.sql:11: ERROR:  error fetching result: OCIStmtFetch2 failed to fetch next result row
DETAIL:  ORA-29275: partial multibyte character

Should I be changing the characterset on Postgres?  How can I make this work?

**Comment by laurenz** [comment]
Normally you should *not* set `nls_lang` on the foreign data wrapper.

PostgreSQL will set this to the PostgreSQL server encoding automatically, which is the right thing unless Oracle contains corrupted data.

What do you get for this in PostgreSQL:

    SHOW server_encoding;

And for this in Oracle:

    SELECT value FROM nls_database_parameters WHERE parameter='NLS_CHARACTERSET';

Also, what are the values you are inserting (in PostgreSQL):

    SELECT 'café'::bytea;

**Comment by ejcrotty** [comment]
Postgres server encoding is UTF8

Oracle is AL32UTF8

Dumping the value of the problem row in oracle  - the e9, 20, 2f is there. 

SQL Statement which produced this data:
  select * from (
  select a.sd_ok_reasn_text, dump(sd_ok_reasn_text,16), rownum as row_num from ltc.f_ltc_serv_dtl a
  )
   where row_num = 92199;

SD_OK_REASN_TEXT	DUMP(SD_OK_REASN_TEXT,16)	ROW_NUM
Caf? Barber Beauty shop not covered	Typ=1 Len=37: 43,61,66,e9,20,2f,20,42,61,72,62,65,72,20,42,65,61,75,74,79,20,73,68,6f,70,20,6e,6f,74,20,63,6f,76,65,72,65,64	92199

So I am not sure if this is a data problem ( and I need to scrub it ) or a configuration problem.  Thanks for your help.

**Comment by laurenz** [comment]
Oh, I thought you were inserting.

Anyway, the case is clear: You have corrupt data in your Oracle database.

Bytes 43,61,66,e9,20 do not form valid UTF-8.
Rather, it is &ldquo;Caf&eacute; &rdquo; in ISO 8859-1 or Windows-1252 encoding.

So PostgreSQL complains correctly.

You have two options:

1. Fix the data in the Oracle database.

2. If you are certain that all data in the Oracle database are in Windows-1252, you can:

   - Create the PostgreSQL database with `ENCODING "WIN1252"`.
   - Set `nls_lang` on the foreign data wrapper to `AMERICAN_AMERICA.AL32UTF8`.

   Then Oracle will not convert the data, and they will arrive in the correct encoding in PostgreSQL.

**Comment by ejcrotty** [comment]
Wonderful - now I have a plan.  Thanks so much for your help.

**Comment by ejcrotty** [comment]
I have come to the realization that I need to clean up the data.

also - AL32UTF8 is just oracle laziness. 

Oracle convert function will swap the unprintable bad character for a compliant character

update
bad_table
set bad_columm = 
convert(bad_column,'AL32UTF8','UTF8');


thanks for your help!

**Comment by laurenz** [comment]
That will get rid of the problem, and there won't be invalid characters left, but Oracle will use a &ldquo;replacement character&rdquo; which is garbage.

So you'll end up with garbage that does not create errors. Maybe that's the best that can be done.

Have you considered:

    convert(bad_column, 'AL32UTF8', 'WE8MSWIN1252')

**Comment by ejcrotty** [comment]
THANK YOU!! -  some of the  convert(bad_column,'AL32UTF8','UTF8')  failed with "ORA-12703: this character set conversion is not supported"  and some failed because the columns are defined as BYTE and not CHAR. Technical debt inherited.  Also the columns are defined as byte -  varchar2 ( 1000 bytes )  instead of CHAR for unicode,  A non trivial amount of remediation will be needed before migration.

What should the nls_lang on the wrapper be set to ?  I am guessing nothing?

**Comment by laurenz** [comment]
Once you have fixed the characters on the Oracle side, do *not* set `nls_lang` on the foreign data wrapper.

That is only if you follow the alternative procedure described [here](#issuecomment-507673665), which only makes sense if *all* the data in Oracle are in a consistent encoding.

**Comment by laurenz** [comment]
Is is ok if I close this issue?

**Comment by ejcrotty** [comment]
Yes of course!  To sum up, the issue was win1252 characters stored in
Oracle AL32UTF8 ( also with BYTE limits instead of CHAR - that's why they
call it technical debt ).   Solution is to "clean your house" on Oracle
before moving forward.   Thanks so much for your help.
