### ISSUE TITLE
OCIEnvCreate failed to create environment handle

### ISSUE THREAD

**Issue by RHundertmark** [laurenz/oracle_fdw#335]
Hello,

i´ve the following environment (oracle and postgresql on the same server):
oracle_fdw 2.1.0, PostgreSQL 11.4, Oracle client 11.2.0.1.0
An i´m getting the following error:

    org.jkiss.dbeaver.model.sql.DBSQLException: SQL-Fehler [HV00N]: ERROR: error connecting to Oracle: OCIEnvCreate failed to create environment handle
  
 when i execute the following statement:

    IMPORT FOREIGN SCHEMA rrt
        FROM SERVER oracle
        INTO migrate;

my strace of the backend-process:

```
strace: Process 15167 attached
epoll_wait(3, [{EPOLLIN, {u32=44578224, u64=44578224}}], 1, -1) = 1
recvfrom(11, "P\0\0\0I\0IMPORT FOREIGN SCHEMA rrt\n"..., 8192, 0, NULL, NULL) = 109
getrlimit(RLIMIT_STACK, {rlim_cur=32768*1024, rlim_max=RLIM64_INFINITY}) = 0
setrlimit(RLIMIT_STACK, {rlim_cur=32768*1024, rlim_max=RLIM64_INFINITY}) = 0
brk(NULL)                               = 0x2ddb000
brk(0x2e17000)                          = 0x2e17000
times({tms_utime=2, tms_stime=1, tms_cutime=0, tms_cstime=0}) = 4064963978
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
write(2, "\0\0\36\1?;\0\0t2019-07-02 15:56:27.357"..., 295) = 295
sendto(11, "1\0\0\0\0042\0\0\0\4n\0\0\0\4E\0\0\0\215SERROR\0VERRO"..., 157, 0, NULL, 0) = 157
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
sendto(10, "\2\0\0\0(\0\0\0\0@\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 40, 0, NULL, 0) = 40
sendto(11, "Z\0\0\0\5I", 6, 0, NULL, 0) = 6
recvfrom(11, 0xcfe8c0, 8192, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(3,
```

Can anyone help me or need more informations?
Thanks
/rene

**Comment by laurenz** [comment]
This is a generic error that means that something is wrong in your Oracle setup.

Look at #307 and the many issues linked from there.

**Comment by RHundertmark** [comment]
Thank. I solved the problem. The ORACLE_HOME was missing in the postgresql-11.service File.
