### ISSUE TITLE
oracle_utils.c:22:10: fatal error: oci.h: No such file or directory  #include <oci.h>

### ISSUE THREAD

**Issue by keating178** [laurenz/oracle_fdw#338]
@laurenz 

I have been racking my brain for 2 days trying to figure out what is going on and why this error message is happening. You have helped me with this exact error in the past but I am unable to find that post. Can you point me in the right direction here?

Could it be that I am using a version of the instant client that is not fully supported yet?
I am installing 19.3

Error: "oracle_utils.c:22:10: fatal error: oci.h: No such file or directory
 #include <oci.h>"
![fdw error](https://user-images.githubusercontent.com/45406216/61726650-d6770e80-ad26-11e9-9305-d6087107995f.JPG)

Thanks in advance,

**Comment by laurenz** [comment]
I guess you are referring to #95.
Does this reference solve your problem?

**Comment by keating178** [comment]
This is the post I was looking form, 

Thanks for getting back to me

**Comment by laurenz** [comment]
Should I close the issue or are there still uncertainties?
