### ISSUE TITLE
Read PG_CONFIG variable in Makefile

### ISSUE THREAD

**Issue by abiuan** [laurenz/oracle_fdw#339]
It would be useful to permit to define in command line the PG_CONFIG environment variable, when do you have multiple version of PostgreSQL installed.
I modified my Makefile:
@@ -15,7 +15,9 @@
 include $(top_builddir)/src/Makefile.global
 include $(top_srcdir)/contrib/contrib-global.mk
 else
+ifndef PG_CONFIG
 PG_CONFIG = pg_config
+endif
 PGXS := $(shell $(PG_CONFIG) --pgxs)
 include $(PGXS)
 endif

therefore you can specify PG_CONFIG variable on command line

**Comment by laurenz** [comment]
I understand the wish, but I don't know if that is necessary.
You can always override the setting:

    make PG_CONFIG=/whatever/you/want

Excerpts from `info make`:

> An argument that contains `=` specifies the value of a variable: `V=X`
> sets the value of the variable `V` to `X`.  If you specify a value in this
> way, all ordinary assignments of the same variable in the makefile are
> ignored; we say they have been "overridden" by the command line
> argument.
>
> The most common way to use this facility is to pass extra flags to
> compilers.  For example, in a properly written makefile, the variable
> `CFLAGS` is included in each recipe that runs the C compiler, so a file
> `foo.c` would be compiled something like this:
>
>     cc -c $(CFLAGS) foo.c
>
> Thus, whatever value you set for `CFLAGS` affects each compilation
> that occurs.  The makefile probably specifies the usual value for
> `CFLAGS`, like this:
>
>     CFLAGS=-g
>
> Each time you run `make`, you can override this value if you wish.
> For example, if you say `make CFLAGS='-g -O'`, each C compilation will
> be done with `cc -c -g -O`.  (This also illustrates how you can use
> quoting in the shell to enclose spaces and other special characters in
> the value of a variable when you override it.)

Does that solve the problem for you?
