### ISSUE TITLE
FDW Performance

### ISSUE THREAD

**Issue by kkwhite** [laurenz/oracle_fdw#34]
I have implemented your FDW on our Postgres 9.3 server. We are connecting to an Oracle 11g R2 instance. The problem we are running into is that it is taking around 3 to 4 minutes to pull back approximately 2000 to 3000 records. We have checked the connection between the two servers by pinging them. The return time  is .34ms, so the connection speed is good. That leads us to believe there is an issue with the performance of the FDW. Therefore, we would like to know if there is any way to tweak the performance of the FDW? 

Thanks,

Kris

**Comment by vmora** [comment]
Hi Kris, what is the size of the data in your 2000-3000 record ? Nothing big ?

**Comment by kkwhite** [comment]
Right. There are only 10 columns each containing a numeric value or a line of text. Nothing big. The servers are also running on Linux machines. Running the queries from both the command line (psql) or through our web application both take the same amount of time. So, we know it is something to do with the FDW

**Comment by laurenz** [comment]
Can you ``EXPLAIN (ANALYZE)`` the query in question and post the query plan?
I'd be curious to know the query issued to Oracle.

**Comment by kkwhite** [comment]
We've done the EXPLAIN ANALYZE select statement as well.The basic select statement is looking for records with a date / timestamp that is less than the past 6 hours. The total runtime was 222943.881ms. Granted, there are hundreds of thousands of records in the table we are searching. However, when we run this same query directly on the oracle DB server, it returns results almost immediately.

**Comment by laurenz** [comment]
Would you please copy and paste the ``EXPLAIN ANALYZE`` output so I can have a look at it?

**Comment by kkwhite** [comment]
Oracle query: SELECT /*334d303034e35670230a0a37b3cbc1d7*/ "TRACK_ID", "TRACK_NAME", "TRACK_GUID", "AVRAGE_SPEED", "DETECT_LATITUDE", "DETECT_LONGITUDE", "DETECT_TIMESTAMP", "FADE_LATITUDE", "FADE_LONGITUDE", "TRACK_SORT", "TRACK_SOURCE", "TRACK_TYPE" FROM <SERVER>.<VIEW> WHERE ("DETECT_TIMESTAMP">(:now - INTERVAL '006:00:00.000000' DAY(9) TO SECOND(6))) Total runtime: 222943.881 ms

**Comment by laurenz** [comment]
Can you run ``EXPLAIN VERBOSE`` to see the execution plan used in Oracle?
Is it the same plan that you get when you run the query with sqlplus?
Also, what is the **complete** output of ``EXPLAIN ANALYZE``?

**Comment by kkwhite** [comment]
That was the complete output. I will see if I can get our DBA to run the query again using explain verbose.

**Comment by laurenz** [comment]
The complete plan should look somewhat like that:

                                                            QUERY PLAN
    ---------------------------------------------------------------------------------------------------------------------------
     Foreign Scan on laurenz.typetest1  (cost=10000.00..10000.00 rows=1000 width=48) (actual time=3.848..3.868 rows=1 loops=1)
       Output: id, c
       Oracle query: SELECT /*040533fc5ff58b5862de0228e9677df8*/ "ID", "C", "B" FROM "SCOTT"."TYPETEST1" WHERE ("B" > 0)
       Oracle plan: SELECT STATEMENT
       Oracle plan:   TABLE ACCESS FULL TYPETEST1  (filter "B">0)
     Planning time: 1.376 ms
     Execution time: 3.939 ms
(7 rows)

**Comment by kkwhite** [comment]
here is the output we get when running EXPLAIN VERBOSE

ERROR: error describing query query: OCIStmtExecute failed to describe remote query
DETAIL: ORA-30081: invalid data type for datetime/interval arithmetic

The normal select statement we are running looks like this:
select * from <schema>.<table> where detect_timestamp > now() - interval '6 hours';

The select statement works fine but takes 2 to 3 minutes to return records.

**Comment by laurenz** [comment]
Hmm, ok, that error is a separate problem; I'll address that at some point.

To analyze your problem, can you tell me the Oracle table definition involved, together with all indexes defined on it?
My suspicion is that the Oracle query just takes a very long time, maybe because of a missing index.

Could you run something like the following in sqlplus and see if it is fast or slow:

    DECLARE
       now TIMESTAMP WITH TIME ZONE := to_timestamp('2015-06-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS');
       x PLS_INTEGER;
    BEGIN
       SELECT 1 INTO x FROM <your table> WHERE detect_timestamp > (now - INTERVAL '0 06:00:00.000000' DAY(9) TO SECOND(6));
    END;
    /
I see that the statement you quoted above is missing a table name. Is that a typo?

**Comment by laurenz** [comment]
I realized that the code I wrote above will probably cause an error.
Please try ``SELECT count(*)`` instead of ``SELECT 1``.
If that PL/SQL code is too hard to try, you could simply run the SELECT statement from the client of your choice and substitute the timestamp instead of ``now``. It is not 100% the same, but if that is also slow, you know that you have to look for the problem outside oracle_fdw.

Starting with tomorrow, I will be on vacation for about three weeks, so don't be alarmed if I cannot respond during that time.

**Comment by laurenz** [comment]
I just pushed a fix for the error message in ``EXPLAIN (VERBOSE)``.
Could you try that again with the latest version from git?
I'd really like to see the Oracle execution plan; it might explain what is going on here.

**Comment by laurenz** [comment]
Well, the only explanation that I have is that the Oracle table contains many rows and there is no index on "detect_timestamp".

I'll close the issue due to inactivity; reopen it if you are still interested.

**Comment by Adolfho** [comment]
Hi there,
I was looking for a solution related to a problem quite similar to this one. In my case my query in oracle (10gR2) takes 0.043s to return 17 columns. But in my postgres 9.3 bringing (with oracle_fdw)  all columns takes 170s for the same query in oracle. If I bring one column with the same condition it takes 0.769s. And as long I add more columns the result takes longer and longer. Is there any option or configuration to make the execution better?
Thanks.

**Comment by laurenz** [comment]
Run ``EXPLAIN ANALYZE`` and ``EXPLAIN VERBOSE`` on the query.
Then you see
- what Oracle does
- how much time is spent where

That should help to understant the problem.

**Comment by Adolfho** [comment]
It is solved after an upgrade to a newer master version.
Thanks!!!

**Comment by laurenz** [comment]
Cool --- a new master version of what?

**Comment by Adolfho** [comment]
oracle_fdw

**Comment by Adolfho** [comment]
I was a little bit confused about the oracle_fdw version that I have to
use. I saw 1.2 but it seems older than the version 1.1 I downloaded from
your git. I'm mean older in terms of more recent files.
The one I was using before was from january and the file_name is
oracle_fdw_master.zip.

Thx.

A.
