### ISSUE TITLE
Makefile needs to be updated for Solaris 11 builds

### ISSUE THREAD

**Issue by edechaux** [laurenz/oracle_fdw#340]
Hello,

Starting Solaris 11.3, Oracle has incorporated instantclient in a package. When installed it is located in `/usr/oracle/instantclient/<versions>/`.

```
$ ls /usr/oracle/instantclient/12.1/
bin  lib  man  sdk
```
On 64 bits systems shared libs are located in `/usr/oracle/instantclient/<versions>/lib/amd64/` which is not searched by oracle_fdw. It would be nice if the Makefile be updated to take it into account. An updated Makefile is attached as reference.

[oraclefdw-fixpath.txt](https://github.com/laurenz/oracle_fdw/files/3502025/oraclefdw-fixpath.txt)

**Comment by laurenz** [comment]
Thanks for the report!
