### ISSUE TITLE
Oracle fdw  ‘RelOptInfo’ has no member named ‘lateral_relids’ Error

### ISSUE THREAD

**Issue by emretuna01** [laurenz/oracle_fdw#341]
I am trying to set up the latest version Oracle_fdw extension on Postgresql. My Postgresql is working on Centos. I get an error like;

"oracle_fdw.c: In function ‘oracleGetForeignPaths’:
oracle_fdw.c:1003:13: error: ‘RelOptInfo’ has no member named ‘lateral_relids’
baserel->lateral_relids,"

When i try to "make" command  on oracle_fdw folder get an error like this:

gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I/usr/lib/oracle/19.3/client64/lib/sdk/include -I/usr/lib/oracle/19.3/client64/lib/oci/include -I/usr/lib/oracle/19.3/client64/lib/rdbms/public -I/usr/include/oracle/19.3/client -I/usr/include/oracle/19.3/client64 -I/usr/include/oracle/18.5/client -I/usr/include/oracle/18.5/client64 -I/usr/include/oracle/18.3/client -I/usr/include/oracle/18.3/client64 -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_fdw.o oracle_fdw.c
oracle_fdw.c: In function ‘oracleGetForeignPaths’:
oracle_fdw.c:1003:13: error: ‘RelOptInfo’ has no member named ‘lateral_relids’
      baserel->lateral_relids,
             ^
oracle_fdw.c: At top level:
oracle_fdw.c:385:13: warning: ‘hasTrigger’ used but never defined [enabled by default]
 static bool hasTrigger(Relation rel, CmdType cmdtype);
             ^
oracle_fdw.c:386:13: warning: ‘buildInsertQuery’ declared ‘static’ but never defined [-Wunused-function]
 static void buildInsertQuery(StringInfo sql, struct OracleFdwState *fdwState);
             ^
oracle_fdw.c:387:13: warning: ‘buildUpdateQuery’ declared ‘static’ but never defined [-Wunused-function]
 static void buildUpdateQuery(StringInfo sql, struct OracleFdwState *fdwState, List *targetAttrs);
             ^
oracle_fdw.c:388:13: warning: ‘appendReturningClause’ declared ‘static’ but never defined [-Wunused-function]
 static void appendReturningClause(StringInfo sql, struct OracleFdwState *fdwState);

![image](https://user-images.githubusercontent.com/42046428/63706972-6f72db00-c839-11e9-86bd-cb5c4d21af9e.png)

Can you help me about that?

Thanks

**Comment by laurenz** [comment]
What is your PostgreSQL version?

What is your oracle_fdw version?

**Comment by emretuna01** [comment]
Postgresql version "PostgreSQL 10.10 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit"

oracle_fdw version 2.1.0

**Comment by laurenz** [comment]
`RelOptInfo` has had member `lateral_relids` ever since [commit 9ff79b9d4e71822a875c0f5e38f5ec86c7fb079f](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=9ff79b9d4e71822a875c0f5e38f5ec86c7fb079f), so it has been present in every PostgreSQL release since 9.3, when `LATERAL` was introduced.

You must be building against a really old version of PostgreSQL.
Check `pg_config --version` for the exact version.

You should build against v10 explicitly:

    PATH=/usr/pgsql-10/bin:$PATH make clean
    PATH=/usr/pgsql-10/bin:$PATH make

**Comment by emretuna01** [comment]
thank you for your help. I have just passed the error but i get another one 
it's about "oracle_utils.c:22:17: fatal error: oci.h: No such file or directory"

the path of ORACLE_HOME and LD_LIBRARY_PATH is same
![image](https://user-images.githubusercontent.com/42046428/63776980-06e43680-c8eb-11e9-8409-abaaf29214b1.png)


how can i solve it

**Comment by laurenz** [comment]
Two possibilities:

- you didn't install the Oracle SDK as the README says.

- your `ORACLE_HOME` points to a wrong directory.

Where are your Oracle header files installed?

**Comment by emretuna01** [comment]
you're right. Path of Oracle oci files was in the wrong directory. I move it to the right place

I have one more question, when i try to create extension i get an error like this 

/usr/pgsql-10/lib/oracle_fdw.so: undefined symbol: errcontext

do you have any clue about that

**Comment by emretuna01** [comment]
i tried 

```
PATH=/usr/pgsql-10/bin:$PATH make
PATH=/usr/pgsql-10/bin:$PATH make install 
```
command  according to this issue [](https://github.com/laurenz/oracle_fdw/issues/221)

but the status of error didn't change

**Comment by emretuna01** [comment]
PATH was not properly set . my bad
now everything is fine 
thank you laurenz

**Comment by laurenz** [comment]
Thanks for the feedback, it will help others. I just add a reference to #312 for completeness' sake.
