### ISSUE TITLE
Problem with trigger

### ISSUE THREAD

**Issue by gsiz007** [laurenz/oracle_fdw#342]
Hello,

I'm not sure, if my expectation is correct. I'm using  oracle_fdw 2.2.0devel, PostgreSQL 11.4, Oracle client 12.1.0.2.0, ORACLE_HOME=/usr/lib/oracle/12.1/client64, TNS_ADMIN=/usr/lib/oracle/12.1/client64/network/admin

I have table in Oracle, used R/W trought FDW in Postgresql. On this table I have trigger:

```sql
create or replace function ei2.testei_trigger()
returns trigger AS $$
declare

begin
  if TG_OP = 'INSERT' then
    insert into ei2.test(operace, popis, data) select 3, 'INSERT', jsonb_build_object('new', to_jsonb(NEW.*), 'old', to_jsonb(OLD.*)) on conflict do nothing;
    return NEW;
  elsif TG_OP = 'UPDATE' then
    insert into ei2.test(operace, popis, data) select 4, 'UPDATE', jsonb_build_object('new', to_jsonb(NEW.*), 'old', to_jsonb(OLD.*)) on conflict do nothing;
    return NEW;
  end if;
end;
$$ language plpgsql;

create trigger testei_trigger before insert or update on ei_work.testei
for each row execute procedure ei2.testei_trigger();
```
1. When I insert data to external table from PostgreSQL , everything work and trigger is fired 
```
=> insert into ei_work.testei(id, value) values (2,'Test from FDW');
INSERT 0 1

=> select * from ei2.test;
 id |             cas              | operace | popis  |                           data                            
----+------------------------------+---------+--------+-----------------------------------------------------------
  7 | 2019-09-01 19:13:50.91348+02 |       3 | INSERT | {"new": {"id": 2, "value": "Test from FDW"}, "old": null}
(1 řádka)
```
2. When I insert data from Oracle SQLPlus, trigger is not fired
```
SQL*Plus: Release 12.1.0.2.0 Production on Sun Sep 1 19:11:49 2019

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

SQL> insert into work.testei(id,value) values (3, 'Test from SQLPlus');

1 row created.

SQL> commit;

Commit complete.

In PostgreSQL I see:

=> select * from ei2.test;
 id |             cas              | operace | popis  |                           data                            
----+------------------------------+---------+--------+-----------------------------------------------------------
  7 | 2019-09-01 19:13:50.91348+02 |       3 | INSERT | {"new": {"id": 2, "value": "Test from FDW"}, "old": null}
(1 řádka)

=> select * from ei_work.testei;
 id |       value       
----+-------------------
  1 | Test VK
  3 | Test from SQLPlus
  2 | Test from FDW

```

Is possible fire trigger on external table, when data are inserted in Oracle ?

Thank you very much for help

Best regards

Vitek

**Comment by laurenz** [comment]
The trigger is triggered by DML statements in PostgreSQL.

It is not possible to fire a PostgreSQL trigger for data changes that happen in Oracle.
How should the PostgreSQL server know that you modified the data in Oracle?

You'd have to create a trigger in Oracle for that (but then you cannot insert into a PostgreSQL table).

What are you trying to achieve?

**Comment by gsiz007** [comment]
Thank you very much for response.

I have application in APEX, that modify some Oracle tables and I need sync modification this tables to PostgreSQL table using fdw. Working scenarios are:

1. perodically run script for transfer Oracle tabel to PostgreSQL table using pg_cron
2. call PG function from REST API for sync changes. REST API will be call from APEX app.

Disadvantages are: 
1. delay between changes and sync
2. extra integration in APEX application and adding REST API

Question is, if exists any other simply way, using DB level only?

**Comment by laurenz** [comment]
No, there is no automatic way to keep a PostgreSQL table synchronized with an Oracle table using PostgreSQL techniques.
That would somehow have to be triggered by Oracle.

I believe that Oracle has some product called "Golden Gate" that does things like that.

**Comment by gsiz007** [comment]
Thank you very much for response.
