### ISSUE TITLE
Oracle DB blocks me because PROGRAM sent value always change

### ISSUE THREAD

**Issue by sezaru** [laurenz/oracle_fdw#344]
Hello, In my project, we are trying to connect into a client Oracle database via oracle_fdw. For their security, they block access by OSUSER, USERNAME, PROGRAM and MACHINE values.
That means that I need to send always that same information so they can allow access to me that way.

The issue is that somehow the PROGRAM registered in their logs when I try to do any operation is changing, you can see in the image bellow:
![image](https://user-images.githubusercontent.com/279828/64566583-af06f000-d32c-11e9-9dab-b5a0172d9e79.png)
I blurred some confidential information, but you can see in the PROGRAM tab that my requests using postgres via oracle_fdw always change a number after the local ip address.

At the same time, you can see another program (jamdb) which always send only "jamdb" as PROGRAM value.

Is this something that I can configure in oracle_fdw?

Thanks!

**Comment by laurenz** [comment]
Interesting question. I cannot find a way to set this in a C program (although it seems to be possible from a Java program).
I have opened [a Stackoverflow question](https://stackoverflow.com/q/57868513/6464308), maybe somebody knows a way.

Provided that I cannot find a way to change this, here is some ammunition why it is pointless for your security people to check this information:

The `PROGRAM` column is taken from the process title of the client process. This can be changed by means as simple as renaming the executable and is under control of the client (the reason why I cannot do it is that PostgreSQL uses this, and you would have to modify the server to change that).

So it is completely worthless to check for the program name as a security check. Any attacker would just rename his program to `sqlplus` and bypass the test.

**Comment by sezaru** [comment]
I'm with you that it is very dumb of them to try to limit access by the `PROGRAM` column since it is so easily bypassed.
Unfortunately, they are a big client so I don't think I have any saying in their DB security measures hehe.
I saw your StackOverflow question, very nice!
If there is something that I can help feel free to ask!
Thanks!

**Comment by laurenz** [comment]
I have experimented with this, but changing the process title varies do much between the various operating systems. I'd have to copy most of [`set_ps_display`](https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/utils/misc/ps_status.c;h=67ba95c5f7dbdcae043784abbcfe08ca604c5331;hb=8a0deae8d9b6861265cf4ebf25a9e4385f4c7672#l331) into oracle_fdw.

That seems over the top for an essentially unnecessary exercise like this, sorry.

You'll have to tell your security people that they either have to relax or learn to use pattern matching.

**Comment by laurenz** [comment]
Another idea: you could set the `cluster_name` parameter in `postgresql.conf` to some long string.
Since `PROGRAM` is a `VARCHAR2(48)`, Oracle must cut off the process name at some point, so you could get away with that.

**Comment by sezaru** [comment]
Just an update, your solution worked like a charm! Thanks a lot for the help :)
