### ISSUE TITLE
ORA-20903: Logon rejected as os user POSTGRES is not authorised to connect to

### ISSUE THREAD

**Issue by RobW101** [laurenz/oracle_fdw#345]
Hi,

Apologies if this is a simple oversight on my part. 

I am attempting to connect to our enterprise ORACLE server from postgreSQL on a CentOS host.  The connection works via SQLPlus, but when attempting through fdw am receiving the following error:
ORA-20903: Logon rejected as **os user POSTGRES** is not authorised to connect to MyOracleServer

The issue is our ORACLE server is protected so that only specified users can log on (also useful for auditing).  When I specify the connection in SQLPlus, the user "myusername" is used to logon.  I don't understand why fdw is using the user "POSTGRES" instead, especially as I've specified the user mapping as below:

`CREATE SERVER oradb FOREIGN DATA WRAPPER oracle_fdw
              OPTIONS (dbserver 'MYSERVERNAME');`
`GRANT USAGE ON FOREIGN SERVER oradb TO myusername;`
`CREATE USER MAPPING FOR pguser SERVER oradb
              OPTIONS (user 'myusername', password 'mypassword');`

Here is the diagnostic output:

SELECT oracle_diag();
oracle_diag
oracle_fdw 2.1.0, PostgreSQL 9.2.24, Oracle client 11.2.0.4.0, ORACLE_HOME=/usr/lib/oracle/11.2/client64/lib

SELECT oracle_diag('oradb'); 

ERROR:  cannot authenticate connection to foreign Oracle server
DETAIL:  ORA-04088: error during execution of trigger 'OurServer.USER_MGMT_LOGON_AUDIT_TRIG'
ORA-00604: error occurred at recursive SQL level 1
ORA-20903: Logon rejected as os user POSTGRES is not authorised to connect to Exadata
ORA-06512: at line 12

I know an answer would be to create a user "POSTGRES" on the ORACLE database, but I do not think our security team would permit this.

Any help greatly appreciated,
Rob

**Comment by RobW101** [comment]
Commenting on my own post (how uncool!!)

A penny has dropped that when I'm running SQLPlus I'm logged in as "myusername", and OSUSER will be "myusername" so it passes our security checks.  When using postgreSQL, it must be running as OSUSER "POSTGRES", despite my logging into the database as "myusername".  Not sure of the solution here at all :-/

**Comment by laurenz** [comment]
I think that your diagnosis is spot on, and the important factor is the operating system user that is running the `sqlplus` or `postgres` command that is the deciding factor.

Some benighted Oracle administrator must have thought that it improves security to allow or deny connections based on what the client says is the operating system user name on the client system.

I cannot find anything on that Oracle error with a web search &mdash; you may have to open a service request with Oracle to get an explanation for the error message.

Or you simply cheat and rename the user `postgres` to `myusername` in `/etc/passwd` (but make sure there is no other user of that name).

**Comment by RobW101** [comment]
Thanks laurenz - I will badger the Oracle admins and see if they can let POSTGRES connect. We still have the username/password protection after all.  I think the extra OSUSER check is used to police users using other user's database credentials to connect. More of an accountability thing...
I'll close this because it is our beef and not yours :-)
