### ISSUE TITLE
count(*) is translated to select '1' What am I doing wrong?

### ISSUE THREAD

**Issue by JamesInform** [laurenz/oracle_fdw#347]
Hi Laurenz

I am experiencing strange performance issues when using oracle_fdw to connect to Oracle 12.2.

I want to run a simple count(*) on a table, but the FDW seems to translate count(*) to '1' which whill fetch a lot of records. I have tables in Oracle containing some million records at that count(*) runs like forever.

FDW Version 2.1.0 / PostgreSQL 11.5 on Mac.
`oracle_fdw 2.1.0, PostgreSQL 11.5, Oracle client 12.2.0.1.0, Oracle server 12.2.0.1.0
`
Example:
```
explain analyze
select count(*) from ora.ec_ucum;
```

```
Aggregate  (cost=20002.50..20002.51 rows=1 width=8) (actual time=93.780..93.780 rows=1 loops=1)
  ->  Foreign Scan on ec_ucum  (cost=10000.00..20000.00 rows=1000 width=0) (actual time=21.391..93.597 rows=911 loops=1)
        Oracle query: SELECT /*571c7dd7f0a480de56984e77d163595b*/ '1' FROM "MYORA"."EC_UCUM" r1
Planning Time: 28.651 ms
Execution Time: 93.843 ms
```

Is there something that I am doing wrong? Or can't I use "select count(*)" on foreign tables in a way that Oracle is doing the count for me?

Regards
James

**Comment by laurenz** [comment]
There are provisions in the foreign data wrapper API to push down aggregate functions to the remote database, but oracle_fdw hasn't implemented that so far. It is on the radar.

Lacking aggregate pushdown, the only option for PostgreSQL is to fetch all rows to PostgreSQL and count it there. That is what you see and what takes so much time.

**Comment by JamesInform** [comment]
Thanks for your respose to my already closed issue ;)

It's good to hear that this is on the radar. The question that follows is about the timeframe. Is this something that can be exspected within the next 6 - 12  months? 

Would be nice to have that aggregate push down anytime soon, because currently it is not possible to use oracle_fdw for any data warehouse querying. I have seens your trick with defining a foreign table on a "select count(*)" query. This is quite nice but far away from an approach one could use in a production environment.

If we had aggregate push down this would be a strong exclamation mark to anyone that is planing a migration from Oracle to PostgreSQL. 

Because then we can tell them: "For the start leave your data in Oracle ... bring your application to PostgreSQL and access your warehouses in Oracle ... finally completely switch to PostgreSQL!"

**Comment by laurenz** [comment]
We have no time frame, we kind of do it as we find time and motivation.

But your expressed interest and motivation is valuable information!
