### ISSUE TITLE
ORA-pseudocolumn in oracle_fdw?

### ISSUE THREAD

**Issue by GitHubTestBln** [laurenz/oracle_fdw#349]
Is there any way to get a pseudocolumn like ORA_ROWSCN in the oracle_fdw? For details see https://docs.oracle.com/cd/B19306_01/server.102/b14200/pseudocolumns007.htm
I would like to install an incremental update on postgres side. In lack of an id-column i think about a database-internal status id.
Thanks in advance!

**Comment by laurenz** [comment]
You can do that if you define teh foreign table on a query:

    CREATE FOREIGN TABLE mytab (
       id bigint NOT NULL,
       ora_rowscn text NOT NULL
    ) SERVER oracle OPTIONS (
       table '(SELECT id, ora_rowscn FROM mytab)'
    );

If the column is not a `VARCHAR2`, you may want to add a type cast to the query.
