### ISSUE TITLE
Problems when installing on PostgreSQL 12. Module not found

### ISSUE THREAD

**Issue by AndreyLisichenko** [laurenz/oracle_fdw#352]
I've read carefully the similar issues #119, #160 but can't find any new ideas to make oracle_fdw 2.2.0 work on my new PostgreSQL 12 instance

I have a  Windows Server 2016 Standard (64-bit) with PostgreSQL 11.5 (64-bit) and oracle_fdw 2.1.0 successfully installed.
PSQL installation path:  C:\Program Files\PostgreSQL\11
Oracle Instant Client 12.1.0.2 64-bit: C:\Program Files\Oracle Instant Client\instantclient_12_1

Lately I've installed ver 12.0 (64-bit) PostgreSQL in parallel to 11.5 PSQL (C:\Program Files\PostgreSQL\12) and made an attempt to use oracle_fdw 2.2.0 (oracle_fdw-2.2.0-pg12-win64.zip)  - all files from archive were placed in correct folders in PostgreSQL\12 .   
Also I made several preparations:
1. In addition to ver 12.1.0.2 new Oracle Instant Client 19.3.0.0 (64-bit) was installed: C:\Program Files\Oracle Instant Client\instantclient_19_3
2. Modified  WIndows System PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\PostgreSQL\12;C:\Program Files\PostgreSQL\12\bin;C:\Program Files\Oracle Instant Client\instantclient_19_3;C:\Program Files\PostgreSQL\11;C:\Program Files\PostgreSQL\11\bin;C:\Program Files\Oracle Instant Client\instantclient_12_1;
3. Modified Windows System ORACLE_HOME=C:\Program Files\Oracle Instant Client\instantclient_19_3

After modifying system paths I've made a server reboot and run command **CREATE EXTENSION oracle_fdw;**. It returns "ERROR:  unable to load library "C:/Program Files/PostgreSQL/12/lib/oracle_fdw.dll": The specified module could not be found".

I've made all checks from https://github.com/laurenz/oracle_fdw/issues/160#issuecomment-291769719 (many thanks to @chrullrich):
1. msvcr120.dll exists and no sysnative folder
2. Dependency Walker shows that oracle_fdw.dll has all necessary dependencies 
![DW](https://user-images.githubusercontent.com/56431465/66641733-fa5e3800-ec23-11e9-8f3a-cf32fdae0ff6.jpg)
3. regsvr32 oracle_fdw.dll shows "DllRegisterServer not found" error
4. postgres processes in Sysinternals Process Explorer get the correct system paths
5. Visual C++ 2008, 2013, 2015-19, 2017 redistributable packages installed
 
I've run out of ideas what I'm doing wrong, especially after successful installation oracle_fdw 2.1.0 version on 11 PostgreSQL. 

Thank you for your help!

**Comment by chrullrich** [comment]
The error message from regsvr32 proves that the DLL can be loaded correctly; it really should work based on your information (very thorough research, thank you!).

Two questions:

- Do you have any version of Visual Studio installed?
- Are the dependencies of oci.dll also correct in Dependency Walker?

**Comment by laurenz** [comment]
My Windows skills are limited, so this is more a question to @chrullrich:

- The previous binaries were build using my &ldquo;traditional&rdquo; method with `cl` and without `oracle_msvc.c`. Could that make a difference?

- I built the latest binaries with Instant Client 11.2 (this is where `OCI_ATTR_DRIVER_NAME` was introduced). Previous binaries were built with 10.2. Could that make a difference?

**Comment by chrullrich** [comment]
If anything, using the msbuild solution makes things more likely to work because it delay-loads OCI and can provide diagnostics where otherwise it would just fail to load. My test build was also with 11.2, so this does not immediately indicate trouble.

**Comment by AndreyLisichenko** [comment]
@chrullrich , @laurenz , many thanks for fast answer
According to your questions:
1. On the server there is no VS installed, only visual studio tools for applications 2015/2017
2. At first look oci.dll dependencies are ok 
![DW2](https://user-images.githubusercontent.com/56431465/66648039-2d5bf800-ec33-11e9-9e24-ef766c24c936.jpg)
 
3. Got no idea. I've also mentioned this new dependency while comparing the results of Dependency walker analysis of  oracle_fdw 2.2.0 vs. 2.1.0. Since there was no ucrtbased.dll on server, I added it manually from another my computer with Visual Studio installed. It didn't help either

**Comment by chrullrich** [comment]
Try adding `C:\Program Files\PostgreSQL\12\lib` to the system PATH variable, or put `ucrtbased.dll` into the `Windows\system32` directory.

When you successfully ran regsvr32 against oracle_fdw.dll, your current directory was PostgreSQL\12\lib, I bet, and that is why it worked.

When @laurenz publishes the updated binaries (release builds) on Monday, be sure to replace your oracle_fdw.dll even if the above works for you, to avoid further trouble.

**Comment by AndreyLisichenko** [comment]
@chrullrich, many thanks for your help! 
Adding C:\Program Files\PostgreSQL\12\lib to the system PATH resolve the installation problem

**Comment by laurenz** [comment]
I have uploaded new binaries what should link with the regular C runtime libraries.

**Comment by AndreyLisichenko** [comment]
@laurenz, thank you very much! Escpecially for such a useful extention for PSQL
