### ISSUE TITLE
Binary packages of oracle_fdw 2.2.0 include DLLs built in debug mode

### ISSUE THREAD

**Issue by chrullrich** [laurenz/oracle_fdw#353]
Hello,

in the screenshot of Dependency Walker from bug #352 it can be seen that the tested DLL depends on ucrtbased.dll and vcruntime140d.dll, which are the debug builds. This usually happens if a module is itself compiled in debug mode.

I just checked the 2.2.0 assets, and this applies to all of them. In addition, the 64-bit pg11 and pg12 builds used a different compiler version from the others (VS 2015 vs. VS 2013).

To use the msbuild solution file to build for release, add `/p:Configuration=Release` to the command line.

**Comment by laurenz** [comment]
Thanks for the pointer.

I saw that the binaries were built into the `Debug` subdirectory, but I didn't think that was a problem.

I can rebuild the binaries as soon as I get near the Windows machine again, but I wonder: what is the down side of using debug builds?

**Comment by chrullrich** [comment]
That they depend on the debug builds of the CRTs and only work where these are present, which is the reason for my question in #352 whether the reporter had VS installed. Since the debug CRTs are not part of the redistributable packages, they should not otherwise be present.

**Comment by laurenz** [comment]
Ugh. Then I will fix that on Monday. I'll remove the binaries from the release in the meantime.

**Comment by chrullrich** [comment]
Thanks. Sorry I didn't catch it earlier. I actually looked at one of the DLLs out of curiosity to see which build method you used, but I didn't notice the 'd's on the CRT.

**Comment by laurenz** [comment]
Is there any way to make `/p:Configuration=Release` the default?

**Comment by laurenz** [comment]
I have build and uploaded the new binaries.
Thanks again.
