### ISSUE TITLE
Access to tables available through a dblink

### ISSUE THREAD

**Issue by nboullis** [laurenz/oracle_fdw#356]
I’ve been given access to an Oracle server where some tables are available through a dblink. I’d like to access those tables from my PostgreSQL server.

This issue is somewhat the same as #78.

I know very little about Oracle but, as far as I can tell, I have no permission to create a synonym, as suggested by @laurenz in that other issue. Moreover, even if I could, I am using a (read-only) account that is shared with other users; I guess it would be terribly messy if each user created their own synonyms (or views or tables or whatever)…

Would it be possible to add an option for oracle_fdw’s foreign tables to access a table through a dblink?

**Comment by laurenz** [comment]
The issue you mention had database links to Microsoft SQL Server. Do you have such database links too or are your database links to other Oracle databases?

Can you give me the exact error message?

Also, like in the other issue, what do you get if you try the following in sqlplus:

    SQL> SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    SQL> SELECT * FROM atable@adblink;

(Of course you have to replace `atable` and `adblink` with the actual names.)

**Comment by nboullis** [comment]
Thanks for your answer.

I just tried your suggested
```
SQL> SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SQL> SELECT * FROM atable@adblink;
```
and it works fine.

I just looked at the ALL_DB_LINKS system view for the dblink I am using and, as I understand it (the content of the HOST column looks like a dsn for an Oracle database), it confirms that the link points to another Oracle database.

What I tried was:
```
CREATE FOREIGN TABLE atable (
    …
)
SERVER aserver
OPTIONS (
    "table" 'ATABLE@ADBLINK'
);
```
But when I try to use it, it (understandably) fails with:
```
ERROR:  Oracle table "ATABLE@ADBLINK" for foreign table "atable" does not exist or does not allow read access
DETAIL:  ORA-00942: table or view does not exist
HINT:  Oracle table names are case sensitive (normally all uppercase).
```

I wish I could create the foreign table with something like:
```
CREATE FOREIGN TABLE atable (
    …
)
SERVER aserver
OPTIONS (
    "table" 'ATABLE',
    "dblink" 'ADBLINK'
);
```

Note that I just figured out I can create is with:
```
CREATE FOREIGN TABLE atable (
    …
)
SERVER aserver
OPTIONS (
    "table" '(SELECT * FROM ATABLE@ADBLINK)'
);
```
which works fine as a workaround but I find less clean (and I don’t know whether it would work for INSERT, DELETE or UPDATE, but that’s not a problem for me since I have no such permission).

**Comment by laurenz** [comment]
Yes, I was about to suggest this last workaround.

Adding a new `dblink` option is an interesting suggestion for an enhancement.

Your immediate problem is solved, right?

**Comment by nboullis** [comment]
Yes, my immediate problem is solved, I think you can remove the “problem” label, and keep the issue open as a request for an enhancement.

Thinking a little further, I think a `dblink` option would also be great for the `IMPORT FOREIGN SCHEMA` command to be able to conveniently create (doubly-)remote foreign tables.

BTW, thanks a lot for oracle_fdw; that’s a realy nice tool for a happy PostgreSQL user who **has** to use an Oracle database.
