### ISSUE TITLE
OCIEnvCreate error: /opt/oracle/instantclient/oracore/zoneinfo No such file or directory

### ISSUE THREAD

**Issue by goopand** [laurenz/oracle_fdw#358]
hello sir,

Error while trying to query data from remote oracle database to PostgreSQL 12.0:   

    ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle

i got strace log as below:

```
epoll_wait(3, [{EPOLLIN, {u32=38785800, u64=38785800}}], 1, -1) = 1
recvfrom(9, "Q\0\0\0001select * from icsys.cmn_chi"..., 8192, 0, NULL, NULL) = 50
openat(AT_FDCWD, "/opt/oracle/instantclient/oracore/zoneinfo", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/oracle/instantclient/oracore/zoneinfo", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
brk(NULL)                               = 0x2696000
brk(0x26c3000)                          = 0x26c3000
get_mempolicy(NULL, NULL, 0, NULL, 0)   = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
open("/proc/sys/kernel/shmmax", O_RDONLY) = 16
fstat(16, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fded1a13000
read(16, "500000000\n", 1024)           = 10
close(16)                               = 0
munmap(0x7fded1a13000, 4096)            = 0
get_mempolicy(NULL, NULL, 0, NULL, 0)   = 0
open("/proc/meminfo", O_RDONLY)         = 16
fstat(16, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fded1a13000
read(16, "MemTotal:       65756788 kB\nMemF"..., 1024) = 1024
read(16, "Total:       0\nHugePages_Free:  "..., 1024) = 202
close(16)                               = 0
munmap(0x7fded1a13000, 4096)            = 0
open("/opt/oracle/instantclient/rdbms/mesg/ocius.msb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/oracle/instantclient/rdbms/mesg/ocius.msb", O_RDONLY) = -1 ENOENT (No such file or directory)
mmap(NULL, 176128, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fded18ba000
times(NULL)                             = 849260037
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
write(2, "2019-10-18 15:03:17.595 CST [150"..., 260) = 260
sendto(9, "E\0\0\0\215SERROR\0VERROR\0CHV00N\0Merror"..., 142, 0, NULL, 0) = 142
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
sendto(8, "\2\0\0\0(\0\0\0\1@\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 40, 0, NULL, 0) = 40
sendto(9, "Z\0\0\0\5I", 6, 0, NULL, 0)  = 6
recvfrom(9, 0xd209c0, 8192, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(3,  <detached ...>
```

Apparently it indicates that '/opt/oracle/instantclient/oracore/zoneinfo' and '/opt/oracle/instantclient/rdbms/mesg/ocius.msb' don't exist. However, i downloaded and unzipped the client package files from official Oracle site. Client files are as follows: 

> instantclient-basic-linux.x64-12.2.0.1.0.zip
> instantclient-sdk-linux.x64-12.2.0.1.0.zip
> instantclient-sqlplus-linux.x64-12.2.0.1.0.zip

Following environment is configured for both root and postgres user:

    export PGDATA=/data/pgsql/data
    export PGPORT=5432
    export PATH=/usr/local/pgsql/bin:${PATH}
    export ORACLE_HOME=/opt/oracle/instantclient
    export OCI_LIB_DIR=$ORACLE_HOME
    export OCI_INC_DIR=$ORACLE_HOME/sdk/include
    export LD_LIBRARY_PATH=/lib64:/usr/lib64:/usr/local/lib64:/lib:/usr/lib:/usr/local/lib:$ORACLE_HOME:$LD_LIBRARY_PATH
    export PATH=${ORACLE_HOME}:${PATH}

Could you please help to give some suggestions? Thanks in advance.

**Comment by laurenz** [comment]
The problem must be with the setup of Oracle client.

You say you are using Instant Client, yet your process is not loading the Instant Client shared library (`libociei.so` or `libociicus.so`), but it thinks that this is a client installation made with Oracle Universal installer. Consequently, it sets out to find time zone resource files and message files (`/opt/oracle/instantclient/rdbms/mesg/ocius.msb`). It should find all these in the Instant Client shared library.

Either there is something wrong with your installation or with your environment variables.

For clarification, could you show me the environment variables set in the postmaster's environment?

    cat /proc/32288/environ | xargs -n 1 -0 | egrep '(ORA|NLS|LD_|TNS)'

(Replace 32288 with your postmaster process ID.)

Also, could you start the `strace` earlier, right after you connect to PostgreSQL and before you access oracle_fdw? That way I can see how and from where the Oracle client shared library is loaded.

**Comment by goopand** [comment]
environ and shared lib are as follows:
> # cat /proc/15802/environ ; echo
LC_PAPER=en_US.UTF-8LC_MONETARY=en_US.UTF-8SHELL=/bin/bashPG_GRANDPARENT_PID=1LC_NUMERIC=en_US.UTF-8USER=postgresPGPORT=5432PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/binPWD=/PGLOCALEDIR=/usr/local/pgsql-12.0/share/localeLANG=en_US.UTF-8LC_MEASUREMENT=en_US.UTF-8PGSYSCONFDIR=/usr/local/pgsql-12.0/etcSHLVL=0HOME=/data/user/postgresLOGNAME=postgresPGDATA=/data/pgsql/dataLC_TIME=en_US.UTF-8

# find /opt/oracle/instantclient -name "*.so" -print | grep liboci
/opt/oracle/instantclient/libociei.so
/opt/oracle/instantclient/libocijdbc12.so


complete strace log as bellow:

> select(6, [3 4 5], NULL, NULL, {46, 290122}) = 1 (in [4], left {41, 128825})
rt_sigprocmask(SIG_SETMASK, ~[ILL TRAP ABRT BUS FPE SEGV CONT SYS RTMIN RT_1], NULL, 8) = 0
accept(4, {sa_family=AF_INET6, sin6_port=htons(56038), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 9
getsockname(9, {sa_family=AF_INET6, sin6_port=htons(5432), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 0
setsockopt(9, SOL_TCP, TCP_NODELAY, [1], 4) = 0
setsockopt(9, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f45423a6b90) = 29836
close(9)                                = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
select(6, [3 4 5], NULL, NULL, {60, 0}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGUSR1 {si_signo=SIGUSR1, si_code=SI_USER, si_pid=15807, si_uid=1002} ---
rt_sigprocmask(SIG_SETMASK, ~[ILL TRAP ABRT BUS FPE SEGV CONT SYS RTMIN RT_1], NULL, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f45423a6b90) = 29916
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
rt_sigprocmask(SIG_SETMASK, ~[ILL TRAP ABRT BUS FPE SEGV CONT SYS RTMIN RT_1], NULL, 8) = 0
open("postmaster.pid", O_RDWR)          = 9
read(9, "15802\n/data/pgsql/data\n157138352"..., 8191) = 75
close(9)                                = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
select(6, [3 4 5], NULL, NULL, {60, 0}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29916, si_uid=1002, si_status=0, si_utime=0, si_stime=0} ---
rt_sigprocmask(SIG_SETMASK, ~[ILL TRAP ABRT BUS FPE SEGV CONT SYS RTMIN RT_1], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 29916
wait4(-1, 0x7ffd58131a7c, WNOHANG, NULL) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
rt_sigprocmask(SIG_SETMASK, ~[ILL TRAP ABRT BUS FPE SEGV CONT SYS RTMIN RT_1], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
select(6, [3 4 5], NULL, NULL, {60, 0}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29836, si_uid=1002, si_status=0, si_utime=1, si_stime=0} ---
rt_sigprocmask(SIG_SETMASK, ~[ILL TRAP ABRT BUS FPE SEGV CONT SYS RTMIN RT_1], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 29836
wait4(-1, 0x7ffd58131a7c, WNOHANG, NULL) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
rt_sigprocmask(SIG_SETMASK, ~[ILL TRAP ABRT BUS FPE SEGV CONT SYS RTMIN RT_1], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
select(6, [3 4 5], NULL, NULL, {60, 0} <detached ...>

**Comment by laurenz** [comment]
That looks like an `strace` of the postmaster, not of the backend using oracle_fdw as above.

To identify the proper backend process:

- start a new `psql` session
- run `SELECT pg_backend_pid();
- in another shell, attach with `strace -o tracefile -p <pid from above>
- in the `psql` session, use oracle_fdw to get the error.

Your `libociei.so` seems to be in the proper location.
I am curious what the `strace` will show.

**Comment by goopand** [comment]
new strace log is as below:


> =# SELECT pg_backend_pid();
 pg_backend_pid 
----------------
          18900
(1 row)

[root@localhost ~]# strace -o 18900.out -p 18900
strace: Process 18900 attached

[root@localhost ~]# cat 18900.out 
epoll_wait(3, [{EPOLLIN, {u32=21584120, u64=21584120}}], 1, -1) = 1
recvfrom(9, "Q\0\0\0001select * from icsys.cmn_chi"..., 8192, 0, NULL, NULL) = 50
mmap(NULL, 143360, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb4eb562000
open("/lib64/libociei.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/libociicus.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("oraaccess.xml", O_RDONLY)         = -1 ENOENT (No such file or directory)
access("oraaccess.xml", F_OK)           = -1 ENOENT (No such file or directory)
open("oraaccess.xml", O_RDONLY)         = -1 ENOENT (No such file or directory)
getcwd("/data/pgsql/data", 256)         = 17
socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 28
bind(28, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
close(28)                               = 0
access("sqlnet.ora", F_OK)              = -1 ENOENT (No such file or directory)
access("/data/user/postgres/.sqlnet.ora", F_OK) = -1 ENOENT (No such file or directory)
stat("/data/user/postgres", {st_mode=S_IFDIR|0700, st_size=156, ...}) = 0
geteuid()                               = 1002
getuid()                                = 1002
socket(AF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 28
connect(28, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(28)                               = 0
socket(AF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 28
connect(28, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(28)                               = 0
open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 28
fstat(28, {st_mode=S_IFREG|0644, st_size=3085, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb4eb614000
read(28, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 3085
close(28)                               = 0
munmap(0x7fb4eb614000, 4096)            = 0
uname({sysname="Linux", nodename="master02", ...}) = 0
getuid()                                = 1002
open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 28
fstat(28, {st_mode=S_IFREG|0644, st_size=3085, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb4eb614000
read(28, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 3085
close(28)                               = 0
munmap(0x7fb4eb614000, 4096)            = 0
times(NULL)                             = 882177821
brk(NULL)                               = 0x1587000
brk(0x15a9000)                          = 0x15a9000
stat("/data/user/postgres/oradiag_postgres/diag/clients/user_postgres/host_1961587888_107", 0x7ffe1c2caad0) = -1 ENOENT (No such file or directory)
gettid()                                = 18900
getrlimit(RLIMIT_NOFILE, {rlim_cur=1024, rlim_max=4*1024}) = 0
openat(AT_FDCWD, "/proc/self/fd/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 28
getrlimit(RLIMIT_FSIZE, {rlim_cur=RLIM64_INFINITY, rlim_max=RLIM64_INFINITY}) = 0
open("/usr/lib64/libndctl.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/data/user/postgres", {st_mode=S_IFDIR|0700, st_size=156, ...}) = 0
geteuid()                               = 1002
getuid()                                = 1002
open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 29
fstat(29, {st_mode=S_IFREG|0644, st_size=3085, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb4eb614000
read(29, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 3085
close(29)                               = 0
munmap(0x7fb4eb614000, 4096)            = 0
uname({sysname="Linux", nodename="master02", ...}) = 0
getuid()                                = 1002
open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 29
fstat(29, {st_mode=S_IFREG|0644, st_size=3085, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb4eb614000
read(29, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 3085
close(29)                               = 0
munmap(0x7fb4eb614000, 4096)            = 0
access("sqlnet.ora", F_OK)              = -1 ENOENT (No such file or directory)
access("/etc/intchg.ora", F_OK)         = -1 ENOENT (No such file or directory)
access("intchg.ora", F_OK)              = -1 ENOENT (No such file or directory)
access("/etc/tnsnav.ora", F_OK)         = -1 ENOENT (No such file or directory)
access("tnsnav.ora", F_OK)              = -1 ENOENT (No such file or directory)
rt_sigaction(SIGQUIT, NULL, NULL, 8)    = 0
rt_sigaction(SIGQUIT, NULL, {0x74a1b0, [], SA_RESTORER|SA_RESTART, 0x7fb4eb1f26d0}, 8) = 0
rt_sigaction(SIGILL, NULL, NULL, 8)     = 0
rt_sigaction(SIGILL, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGILL, {0x7fb4d1f3c7b0, [], SA_RESTORER|SA_SIGINFO, 0x7fb4eb1f26d0}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGABRT, NULL, NULL, 8)    = 0
rt_sigaction(SIGABRT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGABRT, {0x7fb4d1f3c7b0, [], SA_RESTORER|SA_SIGINFO, 0x7fb4eb1f26d0}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGFPE, NULL, NULL, 8)     = 0
rt_sigaction(SIGFPE, NULL, {0x74a280, [], SA_RESTORER|SA_RESTART, 0x7fb4eb1f26d0}, 8) = 0
rt_sigaction(SIGSEGV, NULL, NULL, 8)    = 0
rt_sigaction(SIGSEGV, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGSEGV, {0x7fb4d1f3c7b0, [], SA_RESTORER|SA_SIGINFO, 0x7fb4eb1f26d0}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGBUS, NULL, NULL, 8)     = 0
rt_sigaction(SIGBUS, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGBUS, {0x7fb4d1f3c7b0, [], SA_RESTORER|SA_SIGINFO, 0x7fb4eb1f26d0}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGSYS, NULL, NULL, 8)     = 0
rt_sigaction(SIGSYS, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGSYS, {0x7fb4d1f3c7b0, [], SA_RESTORER|SA_SIGINFO, 0x7fb4eb1f26d0}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTRAP, NULL, NULL, 8)    = 0
rt_sigaction(SIGTRAP, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTRAP, {0x7fb4d1f3c7b0, [], SA_RESTORER|SA_SIGINFO, 0x7fb4eb1f26d0}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGXCPU, NULL, NULL, 8)    = 0
rt_sigaction(SIGXCPU, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGXCPU, {0x7fb4d1f3c7b0, [], SA_RESTORER|SA_SIGINFO, 0x7fb4eb1f26d0}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGXFSZ, NULL, NULL, 8)    = 0
rt_sigaction(SIGXFSZ, NULL, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x7fb4eb1f26d0}, 8) = 0
brk(NULL)                               = 0x15a9000
brk(0x15d4000)                          = 0x15d4000
open("/usr/lib64/libnuma.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib64/libnuma.so.1", O_RDONLY|O_CLOEXEC) = 29
read(29, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@4\0\0\0\0\0\0"..., 832) = 832
fstat(29, {st_mode=S_IFREG|0755, st_size=50752, ...}) = 0
mmap(NULL, 2144488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 29, 0) = 0x7fb4cdf3d000
mprotect(0x7fb4cdf47000, 2097152, PROT_NONE) = 0
mmap(0x7fb4ce147000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 29, 0xa000) = 0x7fb4ce147000
close(29)                               = 0
mprotect(0x7fb4ce147000, 4096, PROT_READ) = 0
open("/proc/self/status", O_RDONLY)     = 29
fstat(29, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb4eb614000
read(29, "Name:\tpostgres\nState:\tR (running"..., 1024) = 1024
close(29)                               = 0
munmap(0x7fb4eb614000, 4096)            = 0
openat(AT_FDCWD, "/sys/devices/system/node", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 29
getdents(29, /* 10 entries */, 32768)   = 312
open("/sys/devices/system/node/node0/meminfo", O_RDONLY) = 30
fstat(30, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb4eb614000
read(30, "Node 0 MemTotal:       67055316 "..., 4096) = 1000
stat("/etc/sysconfig/64bit_strstr_via_64bit_strstr_sse2_unaligned", 0x7ffe1c2ccc70) = -1 ENOENT (No such file or directory)
stat("/etc/sysconfig/64bit_strstr_via_64bit_strstr_sse2_unaligned", 0x7ffe1c2ccc70) = -1 ENOENT (No such file or directory)
read(30, "", 4096)                      = 0
close(30)                               = 0
munmap(0x7fb4eb614000, 4096)            = 0
getdents(29, /* 0 entries */, 32768)    = 0
close(29)                               = 0
sched_getaffinity(0, 512, [0 1 2 3 4 5 6 7 8 9 10 11 ...]) = 512
openat(AT_FDCWD, "/sys/devices/system/cpu", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 29
getdents(29, /* 27 entries */, 32768)   = 768
getdents(29, /* 0 entries */, 32768)    = 0
close(29)                               = 0
open("/proc/self/status", O_RDONLY)     = 29
fstat(29, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb4eb614000
read(29, "Name:\tpostgres\nState:\tR (running"..., 1024) = 1024
read(29, ":\t0\nvoluntary_ctxt_switches:\t665"..., 1024) = 63
read(29, "", 1024)                      = 0
close(29)                               = 0
munmap(0x7fb4eb614000, 4096)            = 0
get_mempolicy(NULL, NULL, 0, NULL, 0)   = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
open("/proc/sys/kernel/shmmax", O_RDONLY) = 29
fstat(29, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb4eb614000
read(29, "500000000\n", 1024)           = 10
close(29)                               = 0
munmap(0x7fb4eb614000, 4096)            = 0
get_mempolicy(NULL, NULL, 0, NULL, 0)   = 0
open("/proc/meminfo", O_RDONLY)         = 29
fstat(29, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb4eb614000
read(29, "MemTotal:       65756788 kB\nMemF"..., 1024) = 1024
read(29, "Total:       0\nHugePages_Free:  "..., 1024) = 202
close(29)                               = 0
munmap(0x7fb4eb614000, 4096)            = 0
open("/etc/localtime", O_RDONLY|O_CLOEXEC) = 29
fstat(29, {st_mode=S_IFREG|0644, st_size=528, ...}) = 0
fstat(29, {st_mode=S_IFREG|0644, st_size=528, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb4eb614000
read(29, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\2\0\0\0\0"..., 4096) = 528
lseek(29, -330, SEEK_CUR)               = 198
read(29, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\3\0\0\0\3\0\0\0\0"..., 4096) = 330
close(29)                               = 0
munmap(0x7fb4eb614000, 4096)            = 0
mmap(NULL, 176128, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb4eb537000
times(NULL)                             = 882177821
brk(NULL)                               = 0x15d4000
brk(0x15f5000)                          = 0x15f5000
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
write(2, "2019-10-22 10:29:35.440 CST [189"..., 260) = 260
sendto(9, "E\0\0\0\215SERROR\0VERROR\0CHV00N\0Merror"..., 142, 0, NULL, 0) = 142
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
sendto(8, "\2\0\0\0X\2\0\0\1@\0\0\5\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 600, 0, NULL, 0) = 600
sendto(8, "\2\0\0\0\10\1\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 264, 0, NULL, 0) = 264
sendto(9, "Z\0\0\0\5I", 6, 0, NULL, 0)  = 6
recvfrom(9, 0xd209c0, 8192, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(3,  <detached ...>

**Comment by laurenz** [comment]
Looks like you set `ORACLE_HOME` in the environment of the PostgreSQL server, but forgot to set `LD_LIBRARY_PATH` to the directory containing the client shared libraries.

So the Oracle client looks for `libociei.so` in the default library path, doesn't find it there and assumes that this is not an instant client installation.

The solution is to set `LD_LIBRARY_PATH` in the environment of the PostgreSQL server and restart it.

**Comment by goopand** [comment]
That's awesome! Originally i started the PostgreSQL service using 'systemctl start postgresql.service' command with root user, so the error appeared repeatedly. Now all goes well after i started postgresql service using 'pg_ctl -D $PGDATA start' command using postgres user. Thank you very much for your time and patience, Laurenz. Great!

**Comment by laurenz** [comment]
Good that the root of the problem is found, but that is not a robust solution: the next reboot will cause the problem to re-appear.

Create a new service file `/etc/systemd/system/postgresql-12.service` that makes sure that the environment variable is set:

```
.include /usr/lib/systemd/system/postgresql-12.service

[Service]
Environment='LD_LIBRARY_PATH=/opt/oracle/instantclient'
```

**Comment by goopand** [comment]
Thanks a lot. It works.
