### ISSUE TITLE
ERROR: oracleQueryPlan internal error: statement handle is not NULL

### ISSUE THREAD

**Issue by Jaisus** [laurenz/oracle_fdw#359]
Hello,

I will not be able to give you the very sample of data and statements that I am using but I will try to be as most precised that I can.

- I have a view on the Oracle side (Oracle 11g)
- It is running fine on the oracle side. 
- It is a very large statement that is pivoting in almost 200 columns. It takes a while to process

- I have a PostgreSQL database (PostgreSQL 11.5)
- On this database a foreign schema is connecting on the Oracle mentionned before
- For common and 'small' tables : it works fine.
- On views (even smaller) : it doesn't work.

- oracle_fdw 1.1

Issue : 
- for evry views : it is launching to me this error 'ERROR: oracleQueryPlan internal error: statement handle is not NULL'

I found this error in the oracle_utils.c file. I checked the V$SESSION and there is no session than the one that is running my statement.

Have you any idea of what is going on?

**Comment by Jaisus** [comment]
Okay. It seems to be a DBeaver issue. I just tried on psql and it works like a charm. Sorry for this useless ticket.

**Comment by laurenz** [comment]
It would be interesting to know the exact SQL statements that DBeaver sends to the database to cause this.

**Comment by Jaisus** [comment]
I agree. My guess is a aborted attempt to parallelize the statement on DBeaver side. But I am in a huge rush at work so I sadly do not have the time to investigate properly... I will open a ticket on their side this noon and see what appends after that ;)

**Comment by laurenz** [comment]
Thanks. No hurry.
My point is that this error should never occur, so it looks like there is an oracle_fdw bug involved.

**Comment by Jaisus** [comment]
So I asked and they respond that : https://dbeaver.com/ticket/29593/.

So for them it more likely the oracle_fdw that is reponsible for this error. If I have some time at the end of this mission, I will try to reproduce the bug with a from scratch installation.

**Comment by laurenz** [comment]
I cannot read the ticket as I don't have (and want) an account there.

It would be valuable if you could reproduce the error with `log_min_messages = debug1`. Then the log would contain the sequence of oracle_fdw calls.

**Comment by Jaisus** [comment]
I will try to redo it. I am very short on time for now. So if I can (before the end of next week because I will not have access to the servers after that ... :P ), I will.

**Comment by laurenz** [comment]
There is absolutely no rush from my end.
I will reopen the ticket.

**Comment by laurenz** [comment]
I'll close this for inactivity, but I'd still be interested in understanding the problem.

**Comment by SebastienCaunes** [comment]
I got the same problem !

My test until now are these :
insert into my_schema.the_table (select * from oracle_tables.the_table limit xxxx);

With a small limit (under 100k) it works fine.
With limit to 1M I have this error (it's dbeaver):
SQL Error [HV000]: ERROR: oracleQueryPlan internal error: statement handle is not null

With limit over 2M I have this error :
SQL Error [HV00L]: ERROR: no SELECT privilege on V$SQL in the remote database
  Detail : ORA-00942: table or view does not exist

(The foreign table point to a view in Oracle)

I will set  loging to debug1 and post the results

**Comment by SebastienCaunes** [comment]
I did a bit more test. I narrowed down the imported data, if I import by small batches (one day of data for example) it always work. So it is not related to corrupted data in one particular row.

If I do bigger batches the larger the timespan, the more chances of bug.

If I ask one month of data the query stops with error after 4s, for two months 8s, for 3 months after 12s and so on. So it looks like all data is transfered before the bug appear.

**Comment by laurenz** [comment]
The point is to get this to reproduce. This error is thrown in a function that is only called when you use `EXPLAIN`, so it cannot be caused by an `INSERT`. So DBeaver must call `EXPLAIN` behind the scenes. The best way to figure out what DBeaver is doing is to log *all* statements on the PostgreSQL server side (`log_statements = all`). Extra debugging output is good, since it shows what exactly oracle_fdw is doing and in which order. Perhaps a cursor is involved...

**Comment by SebastienCaunes** [comment]
Thank you for caring Laurenz. Wich error is due to an explain ?
The error I care for is : HV00L: no SELECT privilege on V$SQL in the remote database
It append in my migration script that does not have any explain statement.

I do think a cursor is involved.

**Comment by laurenz** [comment]
*Both* errors can only be caused by an `EXPLAIN` statement.
I believe when you say that you don't run any of these. My suspicion is that DBeaver might.
That's what I was curious about: I didn't expect them to know why oracle_fdw throws this error (which is indeed almost certainly a bug), but when and how they run `EXPLAIN` without being asked to do that.
I have to be able to reproduce it or understand exactly what is going on, otherwise I cannot fix it.

**Comment by SebastienCaunes** [comment]
I understand you need to reproduce.

I did test in DBeaver but the original error was in my own migration tool. I made it with C# and I'm sure it does not have any EXPLAIN statement (unless npgsql do it under the hood).

**Comment by SebastienCaunes** [comment]
I took some time to troubleshoot this problem now.
The autoexplain option was activated on the server
2023-03-09 10:22:56.291 UTC [2956320] postgres@template1DEBUG:  loaded library "auto_explain"

we removed it, it's working fine now.

Thank you Laurenz.

Maybe we should write somewhere a more explicit message. Why not suggest to disable the auto_explain feature in your error message ?

**Comment by SebastienCaunes** [comment]
Yet I still have a problem on that server. When I use `pg_terminate_backend ` to cancel a long running data migration query
`INSERT INTO PostgresTable (SELECT * FROM OracleTable);` The process hangs and never die.

**Comment by laurenz** [comment]
auto_explain is a good clue. Perhaps I can reproduce the problem.
The other problem is unrelated to this issue. You should open a new issue for that.

**Comment by laurenz** [comment]
I am currently doing a major rewrite of parts of oracle_fdw. I can investigate your lead once the dust has settled on that.

**Comment by SebastienCaunes** [comment]
You rules, thank you

**Comment by SebastienCaunes** [comment]
@laurenz thank you for coming back. I must have agreement from DBAs but I'll try and tell you what.

**Comment by laurenz** [comment]
Thanks. I just tried using `auto_explain` with my latest code, and I could not trigger any errors.

**Comment by laurenz** [comment]
I have found the bug and fixed it in ebc8f4afab.
Can you verify that it works now?
