### ISSUE TITLE
Error: "Connection for the foreign table "XXXXX" cannot be established

### ISSUE THREAD

**Issue by vnaveed** [laurenz/oracle_fdw#360]
Hi,

We had configured Oracle_fdw and create a connection and user in postgresql server.We also created foreign table with the same name in the oracle database.

When we try to SELECT ,COUNT from the foreign table it's throwing an error below,

Error : connection for foreign table "XXXXXXXXX" cannot be established
Details : ORA-12514 :TNS:Listener does not currently know of service requested in connect description

Please help on this

**Comment by laurenz** [comment]
That error means that you either specified the wrong service name or that the database is currently down.

Check with sqlplus from the PostgreSQL machine as operating system user `postgres` and using the same connect string as you used to define the foreign server.
If the error is the same, ask your database administrator to start the database.

**Comment by laurenz** [comment]
Anything new? Can I close the ticket?
