### ISSUE TITLE
Wrong result for count(*) when using filter not in local table

### ISSUE THREAD

**Issue by srakazmus** [laurenz/oracle_fdw#364]
Hello Laurenz,

when I select rows from foreign table oracle_mig.iniposhdr and use * or pohtseq and filter them with "not in" local table filter I get correct number of rows.

```
select pohtseq
	from oracle_mig.iniposhdr ih
	 where ih.pohsite = 805 
	 and ih.pohtseq
	   not in 
		  (select h.pohtseq 
		    from magpos_mig.xxx_jd_s_poshdr_805 h
		    where h.pohsite=805);	
```
```
Foreign Scan on iniposhdr ih  (cost=10000.00..20000.00 rows=1000 width=8) (actual time=69.510..134.990 rows=3714 loops=1)
  Filter: (NOT (hashed SubPlan 1))
  Rows Removed by Filter: 9122
  Oracle query: SELECT /*e3261ee95c51da57f6d0e557faef9a1d*/ r1."POHSITE", r1."POHTSEQ" FROM "INIPOS"."INIPOSHDR" r1 WHERE (r1."POHSITE" = 805)
  SubPlan 1
    ->  Seq Scan on xxx_jd_s_poshdr_805 h  (cost=0.00..340.02 rows=9122 width=8) (actual time=0.025..6.825 rows=9122 loops=1)
          Filter: (pohsite = 805)
Planning Time: 1.993 ms
Execution Time: 135.577 ms
```   
But if I don't include pohtseq field I get 0 rows.
Also when I try to count those rows with the same filter I get zero rows instead of 3714.
```
select count(*)
	from oracle_mig.iniposhdr ih
	 where ih.pohsite = 805 
	 and ih.pohtseq
	   not in 
		  (select h.pohtseq 
		    from magpos_mig.xxx_jd_s_poshdr_805 h
		    where h.pohsite=805);
```
```
Aggregate  (cost=20002.50..20002.51 rows=1 width=8) (actual time=540.603..540.604 rows=1 loops=1)
  ->  Foreign Scan on iniposhdr ih  (cost=10000.00..20000.00 rows=1000 width=0) (actual time=540.598..540.598 rows=0 loops=1)
        Filter: (NOT (hashed SubPlan 1))
        Rows Removed by Filter: 12836
        Oracle query: SELECT /*29d56f2bcaecea66c0baf134f5a9cee8*/ r1."POHSITE" FROM "INIPOS"."INIPOSHDR" r1 WHERE (r1."POHSITE" = 805)
        SubPlan 1
          ->  Seq Scan on xxx_jd_s_poshdr_805 h  (cost=0.00..340.02 rows=9122 width=8) (actual time=0.024..7.625 rows=9122 loops=1)
                Filter: (pohsite = 805)
Planning Time: 2.085 ms
Execution Time: 540.733 ms
```
it looks like too many rows are filtered out.
If I use filter IN (instead NOT IN) I get correct count.
If I call select count(pohsite) instead of count(*) and NOT IN filter I get correct result.
I also get wrong result if use left join and select null rows on joined (local) table.
If I create a local table form foreign table and repeat count(*) NOT IN statement with local instead of foreign table I get correct result. 

What's the problem? It looks like push-down optimization ruins result.

I use: oracle_fdw 2.2.0, PostgreSQL 12.1, Oracle client 19.3.0.0.0, Oracle server 11.2.0.4.0

**Comment by laurenz** [comment]
The problem is clearly that oracle_fdw doesn't select the `pohtseq` column from Oracle.
This is a bug :^(

**Comment by laurenz** [comment]
Can be reproduced with the regression test database with

    SELECT id
    FROM typetest1
    WHERE vc NOT IN (SELECT *
                     FROM (VALUES ('short'), ('other')) AS q);

**Comment by laurenz** [comment]
Could you check if that fixes your problem?

**Comment by srakazmus** [comment]
Perfect. It works now. Sorry for late response.
