### ISSUE TITLE
OCIStmtPrepare failed to prepare query, ORA-01741: illegal zero-length identifier

### ISSUE THREAD

**Issue by theahmadkhan** [laurenz/oracle_fdw#365]
Respected Mr. Laurenz
I have successfully installed oracle_fdw and created foreign tables.
but i am facing some kind of issue that in oracle database column contain text like "Gauze Sponge with x - ray detectable non sterile 2" x 2" 8 ply"
it is an example there are so many other special characters in the string
table is created but when we execute select query following error occurs.

    ERROR:  error describing remote table: OCIStmtPrepare failed to prepare query
    DETAIL:  ORA-01741: illegal zero-length identifier
    SQL state: HV00M  

I also tried following  with $$ delimiter.

    CREATE FOREIGN TABLE mm_item (
       item_no varchar(16) NOT NULL,
       ud_item_no varchar(30) NOT NULL,
       "$sc$item_name$sc$" text,
       "$sc$description$sc$" text
    ) SERVER oradb OPTIONS (schema 'INVENTORY', table 'ITEMS');

your help in this regard is highly appreciated!!

**Comment by laurenz** [comment]
Interesting.

Can you tell me the exact query and the `CREATE TABLE` statement for the Oracle table?

I doubt that this can be connected to the data in the database, but who knows.

Can you also give me the output of

    SELECT oracle_diag('oradb');

Can you use oracle_fdw with other tables?

**Comment by theahmadkhan** [comment]
Yes, i am able to query another table which is foreign table.
Here is the output. 

hmisdb=# SELECT oracle_diag('oradb');
                                      oracle_diag                                      
---------------------------------------------------------------------------------------
 oracle_fdw 2.2.0, PostgreSQL 12.1, Oracle client 12.2.0.1.0, Oracle server 11.2.0.4.0
(1 row)

Create table command.
CREATE FOREIGN TABLE mm_item (
	item_no varchar(16) NOT NULL,
	ud_item_no varchar(30) NOT NULL,
	item_name text,
	description text,
	parent_item_no varchar(16),
	reorder_level integer,
	minimum_level integer,
	maximum_level integer,
	expireable varchar(1),
	identify_type varchar(1),
	uom_no varchar(16),
	dimension varchar(20),
	specs varchar(2000),
	max_req_verify_level smallint,
	max_po_verify_level smallint,
	method_no varchar(16),
	generic_no varchar(16),
	strength bigint,
	strength_unit_no varchar(16),
	product_type_no varchar(16),
	reorder_days integer,
	lead_days integer,
	replaceable_flag char(1),
	shelf_life integer,
	carring_method varchar(300),
	group_no varchar(16) NOT NULL,
	manufacturer_no varchar(16),
	origin varchar(13),
	entered_by varchar(16),
	entry_timestamp timestamp,
	updated_by varchar(16),
	update_timestamp timestamp,
	item_flag char(1),
	active_status char(1),
	price double precision,
	curr_no varchar(20),
	autho_id varchar(16),
	item_type varchar(1),
	approved_by varchar(16),
	minimumuom_no varchar(16),
	total_calorie bigint,
	alert_expdays bigint,
	cat_no varchar(30),
	old_item varchar(30),
	new_item char(1),
	company_no varchar(10) DEFAULT '1',
	item_shape varchar(1000),
	storage_condition varchar(2000),
	poduct_nature varchar(200),
	warning_status varchar(1000),
	nls_item_name varchar(200),
	mnemonic_code varchar(30),
	auto_ac_no varchar(16),
	auto_ac_no_rtn varchar(16),
	strength_per_qty bigint,
	strength_per_qty_unit varchar(16),
	genc_str_pct varchar(1),
	no_of_vaccinedose bigint,
	m_strength varchar(1),
	batch_required varchar(1),
	model_no varchar(16),
	volume bigint,
	volume_unit_no varchar(16),
	strength_unit varchar(5),
	brand_no varchar(16),
	exp_daychk bigint
) SERVER oradb OPTIONS (schema 'INVENTORY', MMITEM '');

**Comment by laurenz** [comment]
Now I am confused.

This `CREATE FOREIGN TABLE` statement is quite different from the original one, and it will not run (there is no option `mmitem`).

I need not only the correct `CREATE FOREIGN TABLE` statement, but also the `CREATE TABLE` statement that was used to create the Oracle table. If it is hard to get that, the result of `DESCRIBE` on that table would be good enough.

**Comment by theahmadkhan** [comment]
SERVER oradb OPTIONS (schema 'INVENTORY', MMITEM '');
that was typo sorry for that correct one is 
SERVER oradb OPTIONS (schema 'INVENTORY', 'MMITEM');

Describe oracle table is below.
SQL> describe mm_item;
Name                  Type           Nullable Default Comments 
--------------------- -------------- -------- ------- -------- 
ITEM_NO               VARCHAR2(16)                             
UD_ITEM_NO            VARCHAR2(30)                             
ITEM_NAME             VARCHAR2(200)  Y                         
DESCRIPTION           VARCHAR2(1000) Y                         
PARENT_ITEM_NO        VARCHAR2(16)   Y                         
REORDER_LEVEL         NUMBER(5)      Y                         
MINIMUM_LEVEL         NUMBER(5)      Y                         
MAXIMUM_LEVEL         NUMBER(5)      Y                         
EXPIREABLE            VARCHAR2(1)    Y                         
IDENTIFY_TYPE         VARCHAR2(1)    Y                         
UOM_NO                VARCHAR2(16)   Y                         
DIMENSION             VARCHAR2(20)   Y                         
SPECS                 VARCHAR2(2000) Y                         
MAX_REQ_VERIFY_LEVEL  NUMBER(2)      Y                         
MAX_PO_VERIFY_LEVEL   NUMBER(2)      Y                         
METHOD_NO             VARCHAR2(16)   Y                         
GENERIC_NO            VARCHAR2(16)   Y                         
STRENGTH              NUMBER         Y                         
STRENGTH_UNIT_NO      VARCHAR2(16)   Y                         
PRODUCT_TYPE_NO       VARCHAR2(16)   Y                         
REORDER_DAYS          NUMBER(5)      Y                         
LEAD_DAYS             NUMBER(5)      Y                         
REPLACEABLE_FLAG      CHAR(1)        Y                         
SHELF_LIFE            NUMBER(5)      Y                         
CARRING_METHOD        VARCHAR2(300)  Y                         
GROUP_NO              VARCHAR2(16)                             
MANUFACTURER_NO       VARCHAR2(16)   Y                         
ORIGIN                VARCHAR2(13)   Y                         
ENTERED_BY            VARCHAR2(16)   Y                         
ENTRY_TIMESTAMP       DATE           Y                         
UPDATED_BY            VARCHAR2(16)   Y                         
UPDATE_TIMESTAMP      DATE           Y                         
ITEM_FLAG             CHAR(1)        Y                         
ACTIVE_STATUS         CHAR(1)        Y                         
PRICE                 NUMBER(12,2)   Y                         
CURR_NO               VARCHAR2(20)   Y                         
AUTHO_ID              VARCHAR2(16)   Y                         
ITEM_TYPE             VARCHAR2(1)    Y                         
APPROVED_BY           VARCHAR2(16)   Y                         
MINIMUMUOM_NO         VARCHAR2(16)   Y                         
TOTAL_CALORIE         NUMBER         Y                         
ALERT_EXPDAYS         NUMBER         Y                         
CAT_NO                VARCHAR2(30)   Y                         
OLD_ITEM              VARCHAR2(30)   Y                         
NEW_ITEM              CHAR(1)        Y                         
COMPANY_NO            VARCHAR2(10)   Y        '1'              
ITEM_SHAPE            VARCHAR2(1000) Y                         
STORAGE_CONDITION     VARCHAR2(2000) Y                         
PODUCT_NATURE         VARCHAR2(200)  Y                         
WARNING_STATUS        VARCHAR2(1000) Y                         
NLS_ITEM_NAME         VARCHAR2(200)  Y                         
MNEMONIC_CODE         VARCHAR2(30)   Y                         
AUTO_AC_NO            VARCHAR2(16)   Y                         
AUTO_AC_NO_RTN        VARCHAR2(16)   Y                         
STRENGTH_PER_QTY      NUMBER         Y                         
STRENGTH_PER_QTY_UNIT VARCHAR2(16)   Y                         
GENC_STR_PCT          VARCHAR2(1)    Y                         
NO_OF_VACCINEDOSE     NUMBER         Y                         
M_STRENGTH            VARCHAR2(1)    Y                         
BATCH_REQUIRED        VARCHAR2(1)    Y                         
MODEL_NO              VARCHAR2(16)   Y                         
VOLUME                NUMBER         Y                         
VOLUME_UNIT_NO        VARCHAR2(16)   Y                         
STRENGTH_UNIT         VARCHAR2(5)    Y                         
BRAND_NO              VARCHAR2(16)   Y                         
EXP_DAYCHK            NUMBER         Y

**Comment by laurenz** [comment]
That is still bad syntax:

```
ERROR:  syntax error at or near "'MMITEM'"
LINE 1: ...teger) SERVER oradb OPTIONS (schema 'INVENTORY', 'MMITEM');
```

**Comment by theahmadkhan** [comment]
I got it !!
that was syntax error. I was doing wrong. my mistake was 
SERVER oradb OPTIONS (schema 'INVENTORY', table '');  "passed table name null"

this is right one.
SERVER oradb OPTIONS (schema 'INVENTORY', table 'MMITEM');


thanks for your time. and i am sorry for this kind of silly mistake.

**Comment by laurenz** [comment]
No problem.
I am glad you could figure it out!
