### ISSUE TITLE
postgresql-13devel issue with heap_open heap_close

### ISSUE THREAD

**Issue by legrandlegrand** [laurenz/oracle_fdw#368]
Hello,
I get errors like :
oracle_fdw.o:oracle_fdw.c:(.text+0x2ffb): undefined reference to `heap_open'
oracle_fdw.o:oracle_fdw.c:(.text+0x312b): undefined reference to `heap_close'
oracle_fdw.o:oracle_fdw.c:(.text+0x8db0): undefined reference to `heap_open'
oracle_fdw.o:oracle_fdw.c:(.text+0x8e1d): undefined reference to `heap_close'
oracle_fdw.o:oracle_fdw.c:(.text+0x8e84): undefined reference to `heap_close'
oracle_fdw.o:oracle_fdw.c:(.text+0x9116): undefined reference to `heap_close'
oracle_fdw.o:oracle_fdw.c:(.text+0x91f1): undefined reference to `heap_close'
oracle_fdw.o:oracle_fdw.c:(.text+0xa112): undefined reference to `heap_open'
oracle_fdw.o:oracle_fdw.c:(.text+0xa12c): undefined reference to `heap_close'
oracle_fdw.o:oracle_fdw.c:(.text+0xa558): undefined reference to `heap_close'
oracle_fdw.o:oracle_fdw.c:(.text+0xb2bf): undefined reference to `heap_open'
oracle_fdw.o:oracle_fdw.c:(.text+0xb2ff): undefined reference to `heap_close'

when building on windows with msys.
changing heap_open and heap_close in table_open and table_close
seems to fix this compilation error (don't know if it works because of an other problem with initDB)

Any idea ?

Regards
Pascal

**Comment by laurenz** [comment]
To work with Git HEAD in PostgreSQL, you should also use Git HEAD in oracle_fdw.

This specific problem should have been fixed with commits [19a9ea163d](../commit/19a9ea163d602bb6ca22b6969aa5db88a1980569) and [7cf56cd03b](..//commit/7cf56cd03be617fc5eed2b02803a867003b911b1).

**Comment by legrandlegrand** [comment]
yes it is fixed in head,
thank you
