### ISSUE TITLE
oracle_execute() support for PL/SQL procedure execution

### ISSUE THREAD

**Issue by legrandlegrand** [laurenz/oracle_fdw#369]
Hello,
I tried this new feature `oracle_execute`,
because I would like to store Oracle DDL in a postgres database.

I'm able to define the `DBMS_METADATA.GET_DDL` in a Foreign table definition,
but was not able to execute procedure like
`dbms_metadata.set_transform_param(dbms_metadata.session_transform,'storage',false);`

a simple test case is

    select oracle_execute('xe','dbms_lock.sleep(10)');

that fails with

    ERROR: error executing statement: OCIStmtExecute failed to execute query
    Détail : ORA-00900: invalid SQL statement

Is that syntax supported ?

Thanks in advance
Regards
PAscal

**Comment by laurenz** [comment]
No, that syntax is not supported... by Oracle.

Try it in sqlplus, and it will fail just the same.

You need to write an &ldquo;anonymous PL/SQL block&rdquo;, which is a valid SQL statement:

    SELECT oracle_execute('xe', 'BEGIN dbms_lock.sleep(10); END;');

**Comment by legrandlegrand** [comment]
Hi,
my syntax isn't supported, but the feature is !
and that's the more important.
Thank you for this great tool (and support)
Regards
PAscal
