### ISSUE TITLE
PostgreSQL 9.5 Alpha1/2 make issue

### ISSUE THREAD

**Issue by danielwestermann** [laurenz/oracle_fdw#37]
<pre>
postgres@oel7:/home/postgres/oracle_fdw-1.2.0/ [PG6] make clean
rm -f oracle_fdw.so   liboracle_fdw.a  liboracle_fdw.pc
rm -f oracle_fdw.o oracle_utils.o oracle_gis.o
rm -rf results/ regression.diffs regression.out tmp_check/ log/
postgres@oel7:/home/postgres/oracle_fdw-1.2.0/ [PG6] make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/u01/app/postgres/product/95/db_2/include/server -I/u01/app/postgres/product/95/db_2/include/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_fdw.o oracle_fdw.c
oracle_fdw.c: In function ‘oracleGetForeignPlan’:
oracle_fdw.c:839:2: error: too few arguments to function ‘make_foreignscan’
  return make_foreignscan(tlist, keep_clauses, baserel->relid, fdwState->params, fdw_private);
  ^
In file included from oracle_fdw.c:42:0:
/u01/app/postgres/product/95/db_2/include/server/optimizer/planmain.h:46:21: note: declared here
 extern ForeignScan *make_foreignscan(List *qptlist, List *qpqual,
                     ^
oracle_fdw.c: In function ‘oraclePlanForeignModify’:
oracle_fdw.c:1226:25: error: ‘RangeTblEntry’ has no member named ‘modifiedCols’
    tmpset = bms_copy(rte->modifiedCols);
                         ^
In file included from oracle_fdw.c:10:0:
oracle_fdw.c: In function ‘getOracleWhereClause’:
/u01/app/postgres/product/95/db_2/include/server/fmgr.h:197:27: error: too few arguments to function ‘array_create_iterator’
  pg_detoast_datum((struct varlena *) DatumGetPointer(datum))
                           ^
/u01/app/postgres/product/95/db_2/include/server/utils/array.h:242:49: note: in expansion of macro ‘PG_DETOAST_DATUM’
 #define DatumGetArrayTypeP(X)    ((ArrayType *) PG_DETOAST_DATUM(X))
                                                 ^
oracle_fdw.c:2610:37: note: in expansion of macro ‘DatumGetArrayTypeP’
    iterator = array_create_iterator(DatumGetArrayTypeP(constant->constvalue), 0);
                                     ^
In file included from /u01/app/postgres/product/95/db_2/include/server/utils/acl.h:29:0,
                 from /u01/app/postgres/product/95/db_2/include/server/catalog/objectaddress.h:18,
                 from /u01/app/postgres/product/95/db_2/include/server/catalog/pg_operator.h:26,
                 from oracle_fdw.c:26:
/u01/app/postgres/product/95/db_2/include/server/utils/array.h:448:22: note: declared here
 extern ArrayIterator array_create_iterator(ArrayType *arr, int slice_ndim, ArrayMetaState *mstate);
                      ^
oracle_fdw.c: In function ‘transactionCallback’:
oracle_fdw.c:4263:2: warning: enumeration value ‘XACT_EVENT_PARALLEL_COMMIT’ not handled in switch [-Wswitch]
  switch(event)
  ^
oracle_fdw.c:4263:2: warning: enumeration value ‘XACT_EVENT_PARALLEL_ABORT’ not handled in switch [-Wswitch]
oracle_fdw.c:4263:2: warning: enumeration value ‘XACT_EVENT_PARALLEL_PRE_COMMIT’ not handled in switch [-Wswitch]
oracle_fdw.c: In function ‘oracleGetForeignPlan’:
oracle_fdw.c:840:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [oracle_fdw.o] Error 1
</pre>

Oracle Linux 7.1
<pre>cat /etc/oracle-release 
Oracle Linux Server release 7.1
</pre>

PostgreSQL 9.5 alpha2 compiled from source. The same issue occurs with alpha1. On the same machine with PostgreSQL 9.4.4 there are no issues. Any idea?

Thanks in advance
Daniel

**Comment by laurenz** [comment]
Since oracle_fdw depends on some internal PostgreSQL functions, it has to be adapted to new PostgreSQL versions since the internal server side API changes more frequently than the documented client APIs.

Try to pull the latest version from GitHub (or [download a ZIP archive](https://github.com/laurenz/oracle_fdw/archive/master.zip)) an try to build with that.

If you still have a problem, please tell me.

**Comment by danielwestermann** [comment]
Thanks, works like a charme

<pre>postgres@oel7:/home/postgres/ [PG6] unzip oracle_fdw-master.zip
Archive:  oracle_fdw-master.zip
7d8dc82c55c2c32795318dc69060c9d756d9265e
   creating: oracle_fdw-master/
  inflating: oracle_fdw-master/.gitignore  
  inflating: oracle_fdw-master/CHANGELOG  
  inflating: oracle_fdw-master/LICENSE  
  inflating: oracle_fdw-master/Makefile  
    linking: oracle_fdw-master/README  -> README.oracle_fdw 
  inflating: oracle_fdw-master/README.oracle_fdw  
  inflating: oracle_fdw-master/TODO  
   creating: oracle_fdw-master/expected/
  inflating: oracle_fdw-master/expected/oracle_fdw.out  
  inflating: oracle_fdw-master/expected/oracle_gis.out  
  inflating: oracle_fdw-master/expected/oracle_import.out  
  inflating: oracle_fdw-master/oracle_fdw--1.0--1.1.sql  
  inflating: oracle_fdw-master/oracle_fdw--1.1.sql  
  inflating: oracle_fdw-master/oracle_fdw.c  
  inflating: oracle_fdw-master/oracle_fdw.control  
  inflating: oracle_fdw-master/oracle_fdw.h  
  inflating: oracle_fdw-master/oracle_gis.c  
  inflating: oracle_fdw-master/oracle_utils.c  
   creating: oracle_fdw-master/sql/
  inflating: oracle_fdw-master/sql/oracle_fdw.sql  
  inflating: oracle_fdw-master/sql/oracle_gis.sql  
  inflating: oracle_fdw-master/sql/oracle_import.sql  
finishing deferred symbolic links:
  oracle_fdw-master/README -> README.oracle_fdw
postgres@oel7:/home/postgres/ [PG6] cd oracle_fdw-master
postgres@oel7:/home/postgres/oracle_fdw-master/ [PG6] which pg_config
/u01/app/postgres/product/95/db_2/bin/pg_config
postgres@oel7:/home/postgres/oracle_fdw-master/ [PG6] make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/u01/app/postgres/product/95/db_2/include/server -I/u01/app/postgres/product/95/db_2/include/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_fdw.o oracle_fdw.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/u01/app/postgres/product/95/db_2/include/server -I/u01/app/postgres/product/95/db_2/include/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_utils.o oracle_utils.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/u01/app/postgres/product/95/db_2/include/server -I/u01/app/postgres/product/95/db_2/include/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_gis.o oracle_gis.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -shared -o oracle_fdw.so oracle_fdw.o oracle_utils.o oracle_gis.o -L/u01/app/postgres/product/95/db_2/lib -Wl,--as-needed -Wl,-rpath,'/u01/app/postgres/product/95/db_2/lib',--enable-new-dtags  -L -L/bin -L/lib -lclntsh -L/usr/lib/oracle/12.1/client/lib -L/usr/lib/oracle/12.1/client64/lib -L/usr/lib/oracle/11.2/client/lib -L/usr/lib/oracle/11.2/client64/lib -L/usr/lib/oracle/11.1/client/lib -L/usr/lib/oracle/11.1/client64/lib -L/usr/lib/oracle/10.2.0.5/client/lib -L/usr/lib/oracle/10.2.0.5/client64/lib -L/usr/lib/oracle/10.2.0.4/client/lib -L/usr/lib/oracle/10.2.0.4/client64/lib -L/usr/lib/oracle/10.2.0.3/client/lib -L/usr/lib/oracle/10.2.0.3/client64/lib 
/usr/bin/ld: skipping incompatible /lib/libc.so when searching for -lc
postgres@oel7:/home/postgres/oracle_fdw-master/ [PG6] make install
/usr/bin/mkdir -p '/u01/app/postgres/product/95/db_2/lib'
/usr/bin/mkdir -p '/u01/app/postgres/product/95/db_2/share/extension'
/usr/bin/mkdir -p '/u01/app/postgres/product/95/db_2/share/extension'
/usr/bin/mkdir -p '/u01/app/postgres/product/95/db_2/share/doc/extension'
/usr/bin/install -c -m 755  oracle_fdw.so '/u01/app/postgres/product/95/db_2/lib/oracle_fdw.so'
/usr/bin/install -c -m 644 .//oracle_fdw.control '/u01/app/postgres/product/95/db_2/share/extension/'
/usr/bin/install -c -m 644 .//oracle_fdw--1.1.sql .//oracle_fdw--1.0--1.1.sql  '/u01/app/postgres/product/95/db_2/share/extension/'
/usr/bin/install -c -m 644 .//README.oracle_fdw '/u01/app/postgres/product/95/db_2/share/doc/extension/'
</pre>

**Comment by danielwestermann** [comment]
Is this a known issue? 

<pre>postgres=# import foreign schema SCOTT from server oracle into scott;
ERROR:  error importing foreign schema: OCIStmtExecute failed to execute column query
DETAIL:  ORA-00100: no data found
postgres=# 
</pre>

Oracle rdbms 12.1.0.2 with the SCOTT sample schema.

Explicitly defining the foreign table works:
<pre>postgres=# create foreign table scott.emp (empno int not null, ename varchar(10), job varchar(9), mgr int, hiredate date, sal numeric, comm numeric, deptno int ) server oracle options (schema 'SCOTT', table 'EMP');
CREATE FOREIGN TABLE
postgres=# select count(*) from scott.emp;
 count 
-------
    14
(1 row)
</pre>

Thanks in advance,
Daniel

**Comment by laurenz** [comment]
There shouldn't be an error message, that is a bug that I will fix.

But it is ok that no data are found, because you didn't quote the Oracle schema with double quotes.
The README says:

>- The Oracle schema name must be written exactly as it is in Oracle, so
>  normally in upper case.  Since PostgreSQL translates names to lower case
>  before processing, you must protect the schema name with double quotes
>  (for example "SCOTT").

**Comment by danielwestermann** [comment]
Thanks a lot. Should have read the readme in more detail (which I thought I had).

**Comment by laurenz** [comment]
Ok, I fixed the bug in commit cd9e5908f3915f5e0fd871c39829f61c1c9291f8.
Does it work for you now?

**Comment by danielwestermann** [comment]
Thanks a lot. Yes it works. 



One more question: Do you have any idea if there are plans to support foreign keys on foreign tables? 


Cheers, 
Daniel 

----- Original Message -----

**Comment by laurenz** [comment]
You mean a foreign key relationship between a foreign table and a local table?

I don't think that will ever be supported, because PostgreSQL has no way to prevent the foreign server from violating the constraint.

**Comment by danielwestermann** [comment]
No. If the foreign key is defined on the table it would be nice if this key gets imported to the local table, too. 
It's clear that this is somehow redundant but it would be nice to see the foreign key in the local table 




----- Original Message -----

**Comment by laurenz** [comment]
That wouldn't work at all.
That foreign key might point to an Oracle table for which no foreign table exists.
Besides, what good would a foreign key definition on a foreign table do?
It could not guarantee integrity, and that's the reason for a constraint.

**Comment by danielwestermann** [comment]
ok, thanks
