### ISSUE TITLE
CREATE EXTENSION oracle_fdw; ERROR:  

### ISSUE THREAD

**Issue by anzoyem** [laurenz/oracle_fdw#370]
postgres=# CREATE EXTENSION oracle_fdw;
ERROR:  could not open extension control file "/usr/pgsql-10/share/extension/oracle_fdw.control": No such file or directory
postgres=# 

ORACLE_HOME=/usr/lib/oracle/12.1/client64/
LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib:$LD_LIBRARY_PATH

**Comment by laurenz** [comment]
You have to build oracle_fdw by running

    make

and install it with

    make install

before you can create the extension. The software must be installed before you can use it.

Please read the "Installation" section from the README carefully.

**Comment by jhgoodwin** [comment]
I can confirm this is resolved. I will ask work if they will let me post the docker build file which lets me add oracle_fdw to a postgres docker image, if you would like it.
