### ISSUE TITLE
Null Byte Error Fix

### ISSUE THREAD

**Issue by Sascha8a** [laurenz/oracle_fdw#371]
Null-Bytes are not allowed in Postgres, however many customers use null bytes as empty strings in Oracle. I'd wish for a column in pgsql_stage.columns to apply a fix, that allows conversion of null bytes

**Comment by laurenz** [comment]
I have added a column option `strip_zeros`.

To make use of that with ora_migrator, I'll have to change the code there...

**Comment by laurenz** [comment]
I have just adapted ora_migrator and db_migrator.

There is now a new column `options` in the `columns` table of the Postgres stage where you can set such options.
