### ISSUE TITLE
How to rename a column during foreign table creation?

### ISSUE THREAD

**Issue by jhgoodwin** [laurenz/oracle_fdw#375]
Hi,

When importing the tables from an oracle database using:
```sql
IMPORT FOREIGN SCHEMA "MYUSER"
  FROM SERVER testoracleserver
  INTO testoracleserver
     OPTIONS (readonly 'true');
```

I will get an error about xmin/xmax as reserved system columns, like this:  https://www.postgresql.org/message-id/4030CB90.6070204@cromwell.co.uk

I was able to temporarily work around this by renaming the column, then importing. This gives me nearly all the foreign tables correctly, but this one table needs to have the original name for the old system. Do you have any suggestions on how I can use create foreign table but with the column prefixed with say `position_` on the postgres side, but leave it as the original column name on the oracle side?

Thanks, John

**Comment by laurenz** [comment]
oracle_fdw`s implementation of `IMPORT FOREIGN SCHEMA` has no provisions to automatically rename (or prefix) columns. I think this is too much of a corner case to spend much effort on it.

I suggest that you use the `EXCEPT` clause:

    IMPORT FOREIGN SCHEMA "ORAUSER"
       EXCEPT (table_with_xmin_col)
       FROM SERVER oraserver INTO local_schema;

That will get the work done for all tables except for the bad one.

Then use `CREATE FOREIGN TABLE` to create the one table &ldquo;on foot&rdquo; and use innocuous column names.

**Comment by jhgoodwin** [comment]
Thanks for your advice. I think your suggestion of using the EXCEPT clause is quite helpful.

I still have one question related to your response.

Do you happen to know where I can see an example of the syntax for CREATE FOREIGN TABLE which lets me rewrite the column name? I tried 
```
create foreign table mytable_in_oracle
(
	position_xmin integer not null options (column xmin),
	position_xmax integer not null options (column xmax),
	difference numeric(12,6)
)
server myserver
options (schema 'MYORACLESCHEMA', table 'MYTABLE_IN_ORACLE');
```
But, when I did this, I got a message that `key` was the only valid option. When I looked at the code for the oracle_fdw.c, I wasn't able to figure out if there was another way.

Thanks again for making this fdw, it's quite helpful.

**Comment by laurenz** [comment]
It is actually much easier in oracle_fdw.

For historical reasons (orache_fdw was written before there were column options and before postgres_fdw) oracle_fdw maps columns by position, not by name. I would do that different if I started from scratch today, but <strike>I was too lazy</strike> I didn't want to break compatibility.

So names are irrelevant: The first oracle column will always be mapped to the first foreign table column and so on, regardless of the name. So all you need to do is choose different names and omit the column option clause.

**Comment by jhgoodwin** [comment]
Thank you so much! I'll try this out. I'll close this ticket and reopen or make a new one if I have more questions.
