### ISSUE TITLE
Refresh materialized views

### ISSUE THREAD

**Issue by Muhammad112233** [laurenz/oracle_fdw#377]
Hello laurenz,

I have a requirement to refresh materialized views on oracle using oracle_fdw. Is this thing possible? or we have to refresh them manually from oracle?Thanks

Regards,
Muhammad Ali.

**Comment by laurenz** [comment]
That is outside the scope of a foreign data wrapper.

But I have recently added a function `oracle_execute` that can execute arbitrary SQL statements on an Oracle database as long as there are no results. So you could make it work with [the latest development version][1].

 [1]: https://github.com/laurenz/oracle_fdw/archive/master.zip

**Comment by Muhammad112233** [comment]
Great! Thank you laurenz
