### ISSUE TITLE
New to Postgres and need access to Oracle

### ISSUE THREAD

**Issue by mettemusen** [laurenz/oracle_fdw#380]
Testinstall of Postgres12 in Windows 10 in c.\postgres - works fine :-)
My oracle is 11.2.0.4 - and 12.2 - and 18.3 (the 18.3 is first in Path)

I have downloaded the Oracle fdw Postgres 12 zip for 64 bit ....

I have unzipped it into C:\PostgreSQL\12 and flipped the service.

I get this message after connect to postges and issuing the command:

`create extension oracle_fdw;`

ERROR:  could not open extension control file "C:/Program Files/PostgreSQL/12/share/extension/oracle_fdw.control": No such file or directory
SQL state: 58P01

This seems to be pointing to the first place I installed Postgres12 into ??

Where do I unzip the files info ?

Best regards
Mette

**Comment by laurenz** [comment]
Yes, you will have to unzip the files into `C:/Program Files/PostgreSQL/12`.
That is the place where your PostgreSQL will look for extension control files.

Like the README says:
> Make sure that the oracle_fdw shared library is installed in the PostgreSQL
> library directory and that oracle_fdw.control and the SQL files are in
> the PostgreSQL extension directory.

Please also read the rest of the installation instructions, it will save you some time and trouble.

**Comment by mettemusen** [comment]
But my Postgres is installed in c:\postgres ??

The other was an old installation which I removed ??


________________________________
Fra: Laurenz Albe <notifications@github.com>
Sendt: 27. februar 2020 16:20
Til: laurenz/oracle_fdw <oracle_fdw@noreply.github.com>
Cc: Mette Stephansen <meste@miracle42.dk>; Author <author@noreply.github.com>
Emne: Re: [laurenz/oracle_fdw] New to Postgres and need access to Oracle (#380)


Yes, you will have to unzip the files into C:/Program Files/PostgreSQL/12.
That is the place where your PostgreSQL will look for extension control files.

Like the README says:

Make sure that the oracle_fdw shared library is installed in the PostgreSQL
library directory and that oracle_fdw.control and the SQL files are in
the PostgreSQL extension directory.

Please also read the rest of the installation instructions, it will save you some time and trouble.

**Comment by mettemusen** [comment]
Now It works !!!  Thanks !

**Comment by laurenz** [comment]
Could you share what was wrong?
It might be interesting to other users with a similar problem.

**Comment by mettemusen** [comment]
Yeps - I unzipped in C:\\Program Files\PostgreSQL\12  even though it was an old installation - so I guess that conthing is still pointing that way .

I will try on a clean machine next week.

I have tested it with:

```
create extension oracle_fdw;

create schema MST;
 /*
drop server oracle cascade;;
drop user mapping for postgres server oracle;
*/

create server oracle foreign data wrapper oracle_fdw options (dbserver '//10.42.42.xxx/noname.miracle.local' );
create user mapping for postgres server oracle options (user 'xxx', password 'xxx');
--import foreign schema "MST" from server oracle into MST; --- ikke alle tabeller kan læses - der fåes fx ora-03113

IMPORT FOREIGN SCHEMA "MST" LIMIT TO (SCOTT_EMP, SCOTT_DEPT) from server oracle into MST

update mst.scott_emp set ename = 'Mette' where empno = 7521; --- her updates den rigtige Oracle tabel !
select * from mst.scott_emp;
```
