### ISSUE TITLE
strange (unhelpful) error message on oracle trigger fail

### ISSUE THREAD

**Issue by radist-nt** [laurenz/oracle_fdw#381]
PostgreSQL 9.6.17 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
oracle_fdw 2.1.0devel, PostgreSQL 9.6.17, Oracle client 11.2.0.4.0

Query
```
update fdw_table d
   set kd_status = 1,
       nn_column = fud.nn_column,
       dt_change = fud.dt_change
  from local_table fud
 where d.id_index = 123
   and d.nm_index = fud.nm_index;
```
Causes error:
```
ERROR: UPDATE on Oracle table changed 0 rows instead of one in iteration 1
HINT: This probably means that you did not set the "key" option on all primary key columns.
********** Error **********

ERROR: UPDATE on Oracle table changed 0 rows instead of one in iteration 1
SQL state: HV00L
Hint: This probably means that you did not set the "key" option on all primary key columns.
```

All oracle key columns has key option in postgres. The table structure is identical. But the oracle table has trigger which caused no_data_found error in pl/sql, which is a not error in sql context, but looks like it leads to reverting the update.

In my case it was an error in data used by trigger, so after fixing the data, I managed to avoid this error, but the hint is really confusing.

Actually, the trigger which denies an update is a valid situation, however since this situation seems not supported in oracle_fdw, I suggest to extend the hint message with the hint about trigger.

The trigger ddl example is follows:
```
create or replace trigger fdw_table_trg
  after update of kd_status on fdw_table_trg
begin
  case
    when UPDATING ('kd_status') then
      raise no_data_found;
    else
      null;
  end case;
end fdw_table_trg;
/
```

**Comment by laurenz** [comment]
Thanks for the report!

Could you confirm that my commit fixes the problem?
