### ISSUE TITLE
oracle_fdw  segworker groups is not supported

### ISSUE THREAD

**Issue by Rumyuqiang** [laurenz/oracle_fdw#385]
Dear sir,
When I CREATE EXTENSION oracle_fdw, I got the error:

postgres=# create extension oracle_fdw;
ERROR: query plan with multiple segworker groups is not supported
HINT: likely caused by a function that reads or modifies data in a distributed table

I need your help, thank you!

**Comment by laurenz** [comment]
That is not a PostgreSQL error message. You seem to be using a different database (Greenplum?) that is not API compatible with PostgreSQL, which is not supported.
