### ISSUE TITLE
ERROR:  could not load library "/pgsql/lib/oracle_fdw.so": libnsl.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bomuva** [laurenz/oracle_fdw#386]
Hi!
Linux 4.18.0-147.5.1.el8_1.x86_64 , Oracle Instant Client 11.2.0.4, PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4), 64-bit
Installation of oracle_fwd was succesful. But when I try issue "create extension oracle_fwd" I got an error:
ERROR:  could not load library "/pgsql/lib/oracle_fdw.so": libnsl.so.1: cannot open shared object file: No such file or directory.

I have found only /usr/lib64/libnsl.so.2  in file system...
Can you help me, please?

**Comment by bomuva** [comment]
RESOLVED:
yum install libnsl

**Comment by laurenz** [comment]
Thanks for sharing the answer.
