### ISSUE TITLE
FEHLER:  Oracle table "orauser"."sym_cache" for foreign table "sym_cache" does not exist or does not allow read access

### ISSUE THREAD

**Issue by svenkirsten** [laurenz/oracle_fdw#389]
I run into this issue : FEHLER:  Oracle table "orauser"."sym_cache" for foreign table "sym_cache" does not exist or does not allow read access

**On Oracle I have this table:** 

```
SQL> desc orauser.sym_cache
 Name					   Null?    Type
 ----------------------------------------- -------- ----------------------------
 ID						    NUMBER
 EVENTID					    NUMBER
 DATA						    CLOB
 NAME						    VARCHAR2(255)
 STATUS 					    VARCHAR2(255)
 TS						    TIMESTAMP(6)

SQL> 
```

**I have created the foreign table in postgresql :** 

```
AS User postgres : 
CREATE FOREIGN TABLE sym_cache (
id SERIAL, eventid integer, name varchar(255), status varchar(255), data text, ts timestamp)
server oranus options (schema 'orauser', table 'sym_cache');

CREATE SERVER oranus FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '//192.168.71.98:1521/p01');

GRANT USAGE ON FOREIGN SERVER oranus TO ndmuser;

As User ndmuser:
CREATE USER MAPPING FOR ndmuser SERVER oranus
OPTIONS (user 'orauser', password 'orauser');

CREATE FOREIGN TABLE sym_cache (
id SERIAL, eventid integer, name varchar(255), status varchar(255), data text, ts timestamp) server oranus options (schema 'orauser', table 'sym_cache');

```

So the Oracle Table within the Schema should be found.... but - did not 

And I installed the sqlplus client on the Linux where the PostgreSQL database runs and setup tis command : 
```
 sven@canosa  ~ sqlplus orauser/orauser@//192.168.71.98:1521/p01

SQL*Plus: Release 19.0.0.0.0 - Production on Thu Apr 30 14:00:39 2020
Version 19.5.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Last Successful login time: Thu Apr 30 2020 15:53:19 +00:00

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0

SQL> 
```

**Comment by svenkirsten** [comment]
I need to change in upper case: 

`CREATE FOREIGN TABLE sym_cache (
id SERIAL, eventid integer, name varchar(255), status varchar(255), data text, 
ts timestamp) server oranus options (schema 'ORAUSER', table 'SCWH_CACHE');
`

**Comment by laurenz** [comment]
Great! You found the solution.
This is covered in the documentation:

> This name must be written exactly as it occurs in Oracle's system catalog, so normally consist of uppercase letters only.

The reason for this oddity is that Oracle (in accordance with the SQL standard) folds all unquotes identifiers to uppercase, while [PostgreSQL doesn't](https://www.postgresql.org/docs/11/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS):

> The folding of unquoted names to lower case in PostgreSQL is incompatible with the SQL standard, which says that unquoted names should be folded to upper case.
