### ISSUE TITLE
Unable to install oracle_fdw: Makefile:23: /usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk:

### ISSUE THREAD

**Issue by aahamed-star** [laurenz/oracle_fdw#390]
Hi, While running make command, I am getting below error. 
@slcnpawsxxx:/opt/oracle_fdw-master>make
Makefile:23: /usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

Below list of postgres/oracle RPM's available:
-----------------------------------------
percona-postgresql-client-common-214-2.el7.noarch
percona-postgresql11-libs-11.7-2.el7.x86_64
percona-postgresql11-contrib-11.7-2.el7.x86_64
percona-postgresql-server-dev-all-214-2.el7.noarch
percona-postgresql11-11.7-2.el7.x86_64
percona-postgresql11-server-11.7-2.el7.x86_64
percona-postgresql-common-214-2.el7.noarch
oracle-instantclient18.3-basic-18.3.0.0.0-3.x86_64
oracle-instantclient18.3-devel-18.3.0.0.0-3.x86_64

Any Idea what I am missing here. Many Thanks.

**Comment by laurenz** [comment]
You should install proper PostgreSQL, not some modified version. I make no guarantees that the extension works with anything but regular PostgreSQL.

Anyway, the obvious problem seems to be that you didn't install the `*-devel` RPM, which contains headers and the PostgreSQL extension building infrastructure.

This is explained in the README:

> You will need PostgreSQL headers and PGXS installed (if your PostgreSQL was
> installed with packages, install the development package).

 If in doubt, ask your provider where to find that.

**Comment by aahamed-star** [comment]
Hello Laurenz, Thanks for the help. The issue is resolved after I installed *-devel RPM.
