### ISSUE TITLE
Failure to create SERVER with option isolation_level

### ISSUE THREAD

**Issue by meyerink** [laurenz/oracle_fdw#391]
I am attempting to solve the problem of reading tables to populate my reporting database using Oracle FDW. When the contents of that table are being modified it errors with a serialization error. While we could set all the source tables to "segment immediate" on the Oracle side, it would work for us to change our connection to perform as "read committed". However when we attempt to do so the SERVER creation fails. Example as follows:

<code SQL>
select oracle_diag();

oracle_fdw 2.2.0, PostgreSQL 10.12, Oracle client 12.1.0.2.0;

CREATE SERVER test
                FOREIGN DATA WRAPPER oracle_fdw
                OPTIONS
                    (dbserver 'lsdsscant:1521/crit', isolation_level 'READ_COMMITTED');

...

SQL Error [HV00D]: ERROR: invalid option "isolation_level"
  Hint: Valid options in this context are: dbserver
</code>

Am I doing something wrong or have I misread the documentation on Foreign server options?

**Comment by laurenz** [comment]
No, you have done everything right, except you didn't use the [latest development version](https://github.com/laurenz/oracle_fdw/archive/master.zip).

**Comment by meyerink** [comment]
That was the problem! After upgrading to 2.3 development version I was able to ALTER the existing SERVER successfully. Thanks!
