### ISSUE TITLE
connection for foreign table "" cannot be established  TNS:no listener

### ISSUE THREAD

**Issue by aahamed-star** [laurenz/oracle_fdw#393]
I am getting an error while accessing Foreign table from postgres using oracle_fdw. Could you please help to fix it.

Actually I followed below steps to implement Oracle_FDW:

Oracle client installed:

```bash
sudo yum install oracle-instantclient18.3-basic
sudo yum install oracle-instantclient18.3-devel
sudo yum install oracle-instantclient18.3-sqlplus
```

Added TNS entry and can able to connect using sqlplus:

able to connect from sqlplus of postgres server

```none
sqlplus system/Tr1t3l3#@FTST

SQL*Plus: Release 18.0.0.0.0 - Production on Tue May 5 16:29:02 2020
Version 18.3.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Data Mining
and Real Application Testing options

SQL>
```

ORACLE_FDW installed

    $ make
    $ make install

In postgres:

```
postgres=# create server oracle foreign data wrapper oracle_fdw options (dbserver '//10.36.207.6/FTST');
postgres# GRANT USAGE ON FOREIGN SERVER oracle TO postgres;
postgres=# create user mapping for postgres server oracle options (user 'SYSTEM', password 'xxxx');
```

In oracle:

```
SQL> create table system.test3(ID NUMBER(38), NAME VARCHAR2(50));
SQL> insert into system.test3(ID,NAME) values (1,'TOM');
SQL> commit;
```

In postgres:

```
postgres=# create foreign table datawrap_test31 (id int, name varchar(50)) server oracle options (schema 'SYSTEM', table 'test3');

postgres=# select * from datawrap_test3;
ERROR:  connection for foreign table "datawrap_test3" cannot be established
DETAIL:  ORA-12541: TNS:no listener


postgres=# SELECT oracle_diag();
                                                oracle_diag
------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.2.0, PostgreSQL 11.7, Oracle client 18.3.0.0.0, ORACLE_HOME=/usr/lib/oracle/18.3/client64/lib
```

**Comment by laurenz** [comment]
Can you describe how exactly you "added the TNS entry"?
Are you using local naming with a `tnsnames.ora` file?

What environment variables did you set to make sqlplus work (I'd expect `TNS_ADMIN`, perhaps `ORACLE_HOME`)?
Did you make sure that these variables are set in the environment of the PostgreSQL server?
On Linux, you can check the environment in the `/proc/12345/environ` file, where `12345` is the process ID of the postmaster process (PostgreSQL parent process).

**Comment by aahamed-star** [comment]
Can you describe how exactly you "added the TNS entry"?
----------------------------------------------------------------
cd /usr/lib/oracle/18.3/client64
mkdir -p network/admin
vi tnsnames.ora

Are you using local naming with a tnsnames.ora file?
-----------------------------------------------------------
Yes

What environment variables did you set to make sqlplus work (I'd expect TNS_ADMIN, perhaps ORACLE_HOME)?
--------------------------------------------------------------------------------------------------------
export ORACLE_HOME=/usr/include/oracle/18.3/client64
export SQLPLUS=/usr/lib/oracle/18.3/client64
export TNS_ADMIN=/usr/lib/oracle/18.3/client64/network/admin


Did you make sure that these variables are set in the environment of the PostgreSQL server?
---------------------------------------------------------------------------------------------------------
Yes, I did. 

On Linux, you can check the environment in the /proc/12345/environ file, where 12345 is the process ID of the postmaster process (PostgreSQL parent process).
-------------------------------------------------------------------------------------------------------
@aaanpaws111:/home/postgres>cat /proc/9111/environ | xargs -0 -n 1
LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
NOTIFY_SOCKET=/run/systemd/notify
HOME=/home/postgres
LOGNAME=postgres
USER=postgres
SHELL=/bin/bash
PGDATA=/pgsqldata
PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj
PG_OOM_ADJUST_VALUE=0
PGPORT=5432

**Comment by laurenz** [comment]
Then you didn't set the environment variables in the environment of the PostgreSQL server.

Look at related issues like #22 or #64.

Are you using Linux? If yes, which distribution?

**Comment by aahamed-star** [comment]
Hi Laurenz, I did small change in server creation syntax below (added oracle db's port number next to hostname) and TNS issue resolved. Now Oracle_FDW is working fine.

New Syntax:- 
---------------
create server <server_name> foreign data wrapper oracle_fdw options (dbserver '//<oracle_servefr_IP>:<port>/<sid>' );

Old Syntax:- 
---------------
create server <server_name> foreign data wrapper oracle_fdw options (dbserver '//<oracle_servefr_IP>/<sid>' );


Technically it makes sense, but I didn't find it (new syntax) in any online reference. Please correct me, if I miss something. Many Thanks,

**Comment by aahamed-star** [comment]
Sorry, I couldn't paste entire syntax in previous chat

create server oracle foreign data wrapper oracle_fdw options (dbserver '//10.30.20.60:1522/sid');

**Comment by laurenz** [comment]
Thanks for the feedback!

That makes sense in connection with the error message `ORA-12541: TNS:no listener`, since the default Oracle port is 1521.

Good that you could solve the problem.
