### ISSUE TITLE
ERROR:  Oracle table  for foreign table does not exist or does not allow read access

### ISSUE THREAD

**Issue by brajncst123** [laurenz/oracle_fdw#395]
Hi,

I am able to establish connection to Oracle but getting following error while trying to get the foreign relation size using "SELECT * from \"schemaname\".\"tablename\"".

ERROR:  Oracle table "schemanme"."tablename" for foreign table "tablename" does not exist or does not allow read access.

Thanks
Braj

**Comment by laurenz** [comment]
I need to know the actual names, because these are probably the problem.

- What is the schema name and table name as it appears in `DBA_TABLES`?

- Which Oracle user are you using to connect? WHat permissions does that user have on the table?

- What exactly is the `CREATE FOREIGN TABLE` statement in PostgreSQL?

My first suspicion: you used a lower case name in the PostgreSQL definition.

**Comment by brajncst123** [comment]
I had created foreign table with small letter name, But when i dropped this table and recreated with capital latter table name, I am getting different error now

test2=# select * from T1 ;
2020-05-07 20:53:37.496 IST [15880] ERROR:  relation "braj.T1" does not exist at character 42
2020-05-07 20:53:37.496 IST [15880] STATEMENT:  DECLARE c1 CURSOR FOR
        SELECT c1, c2 FROM braj."T1"
2020-05-07 20:53:37.499 IST [11624] ERROR:  relation "braj.T1" does not exist
2020-05-07 20:53:37.499 IST [11624] CONTEXT:  remote SQL command: SELECT c1, c2 FROM braj."T1"
2020-05-07 20:53:37.499 IST [11624] STATEMENT:  select * from T1 ;
ERROR:  relation "braj.T1" does not exist
CONTEXT:  remote SQL command: SELECT c1, c2 FROM braj."T1"

**Comment by brajncst123** [comment]
Hey Laurenz,

The problem is resolved.
The reason for this error was in following statement i gave oracle schema name in small later.
CREATE FOREIGN TABLE T1(c1 int,c2 int) SERVER oradb OPTIONS (schema 'myschema',table 'TEST');

Thanks Laurenz

Braj

**Comment by laurenz** [comment]
Thanks for the feedback.
