### ISSUE TITLE
Encrypted connection with oracle_fdw

### ISSUE THREAD

**Issue by tommisan** [laurenz/oracle_fdw#398]
I would like to use an encrypted connection to Oracle.
I set up a file `sqlnet.ora` with:

    SQLNET.ENCRYPTION_CLIENT = REQUIRED
    SQLNET.ENCRYPTION_TYPES_CLIENT = (AES256)
    SQLNET.CRYPTO_CHECKSUM_CLIENT = REQUIRED
    SQLNET.CRYPTO_CHECKSUM_TYPES_CLIENT = (SHA256)

Using sqlplus, encryption is easily verified with sql query

    select NETWORK_SERVICE_BANNER from v$session_connect_info
       where SID = sys_context('USERENV','SID');

I wanted to be sure that postgres too through oracle_fdw is using encryption.
I made a typo in the file `sqlnet.ora`, sqlplus stop working with Internal Error (`ERROR: ORA-12699: Native service internal error`), while connection from PostgreSQL is working as usual which seems it is not using that file. I also restarted postgresql, same result.

---
```
SELECT oracle_diag('server_name');
oracle_fdw 2.0.0, PostgreSQL 10.12 (Debian 10.12-2.pgdg90+1), Oracle client 12.2.0.1.0, Oracle server 12.1.0.2.0

SELECT oracle_diag();
oracle_fdw 2.0.0, PostgreSQL 10.12 (Debian 10.12-2.pgdg90+1), Oracle client 12.2.0.1.0, ORACLE_HOME=/usr/local/lib/instantclient
```
---

Is there any way to check it?
Thank you in advance

**Comment by laurenz** [comment]
Well, that would indicate that your `sqlnet.ora` is not used.

It is searched in `$ORACLE_HOME/network/admin/` or `$TNS_ADMIN`, so the suspicion is that these are not set in the environment of your PostgreSQL server. Find out the postmaster process ID from `postmaster.pid` and try (replacing 12345 with the process ID):

    cat /proc/12345/environ | xargs -0 -n 1 echo

You might have to modify the startup script.

To test on the server side, I think you can look at

SELECT network_service_banner FROM v$session_connect_info;

for the session in question.

**Comment by tommisan** [comment]
$ORACLE_HOME and $TNS_ADMIN were already set in /etc/environment (also available to user postgres) but they were not present in PostgreSQL server environment as you command showed.
Once added, the behaviour is the same of the sqlplus (Error if a typo is added in sqlnet.ora). 
It seems the file is now read by PostgreSQL.
Unfortunately I don't have much control on server side, but when I launch SELECT network_service_banner FROM v$session_connect_info; I get hundreds of connections (it's a really big vm).
Is it possible to traslate to PostgreSQL the query select NETWORK_SERVICE_BANNER from v$session_connect_info where SID = sys_context('USERENV','SID'); to get info about the current session?

Thank you very much!

**Comment by laurenz** [comment]
CREATE FOREIGN TABLE oracle_banner(banner text NOT NULL)
    SERVER server_name OPTIONS (table '(SELECT network_service_banner FROM v$session_connect_info WHERE sid = sys_context(''USERENV'', ''SID''))');

**Comment by tommisan** [comment]
I confirm that now is working fine.
Thank you again
