### ISSUE TITLE
FDW Dockerfile

### ISSUE THREAD

**Issue by SrdanD** [laurenz/oracle_fdw#399]
Hi, I am trying to build postgres 10.12 with oracle FDW and getting the following error 
oracle_fdw.c:8:22: fatal error: postgres.h: No such file or directory
 #include "postgres.h"
                      ^
compilation terminated.
<builtin>: recipe for target 'oracle_fdw.o' failed

I've attached my dockerfile for reference. 

[Dockerfile_PG10.txt](https://github.com/laurenz/oracle_fdw/files/4684517/Dockerfile_PG10.txt)

**Comment by laurenz** [comment]
That error means that the C header files for the PostgreSQL server are not there, or that the compiler invocation is lacking the appropriate `-I` directive.

I am no Docker specialist, but the file looks like you did install `postgresql-server-dev-10`, which should contain the headers.

If you want me to help you, please show me that compiler command line that gets executed to build `oracle_fdw.o`.

By the way, I recommend that you don't use an old version of oracle_fdw. Use Git HEAD.

**Comment by SrdanD** [comment]
Found the issue,  postgis isn't specifying a version when being installed so defaulting to the highest version (12) it would seem that package has a dependency for the postgres 12 client. When the client gets installed after the base image is pulled it sets the PG_CONFIG parameters to postgres 12 thus causing issues with the extensions because the make files derive a lot of their information from PG_CONFIG. Specified the version of postgis, now it looks like the make commands for oracle FDW and pgsql-http are working as expected.

**Comment by laurenz** [comment]
Thanks for the feedback, that will help others.

**Comment by vlizanae** [comment]
I'm having the exact same problem, did you specify the postgis version on the Dockerfile? how is this done?

**Comment by SrdanD** [comment]
RUN apt-get update \
    && apt-get install -y postgresql-10-python-multicorn \
                          postgresql-10-pgtap \
                          **postgresql-10-postgis-2.4 \**
                          postgresql-plpython-10 \
                          postgresql-server-dev-10 \
                          postgresql-10-cron \
                          libaio1 \
                          libcurl4-openssl-dev \
                          alien \
    && rm -rf /var/lib/apt/lists/*

**Comment by Santhi510** [comment]
Hi, I am trying to install oracale FWD in my local machine, getting below issues,  Please help me here.

oracle_fdw.c:8:22: fatal error: postgres.h: No such file or directory
 #include "postgres.h"
                      ^

[root@localhost ~]# pg_config
BINDIR = /usr/edb/as12/bin
DOCDIR = /usr/share/doc
HTMLDIR = /usr/share/doc
INCLUDEDIR = /usr/edb/as12/include
PKGINCLUDEDIR = /usr/edb/as12/include
INCLUDEDIR-SERVER = /usr/edb/as12/include/server
LIBDIR = /usr/edb/as12/lib
PKGLIBDIR = /usr/edb/as12/lib
LOCALEDIR = /usr/edb/as12/share/locale
MANDIR = /usr/edb/as12/share/man
SHAREDIR = /usr/edb/as12/share
SYSCONFDIR = /etc/sysconfig/edb/as12
PGXS = /usr/edb/as12/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/usr/edb/as12' '--includedir=/usr/edb/as12/include' '--mandir=/usr/edb/as12/share/man' '--datadir=/usr/edb/as12/share' '--libdir=/usr/edb/as12/lib' '--with-llvm' '--with-perl' '--with-python' '--with-tcl' '--with-tclconfig=/usr/lib64' '--with-openssl' '--with-pam' '--with-krb5' '--with-gssapi' '--with-includes=/usr/include' '--with-libraries=/usr/lib64' '--enable-nls' '--with-ossp-uuid' '--with-libxml' '--with-libxslt' '--with-ldap' '--with-systemd' '--with-libcurl' '--with-icu' '--with-oci=/usr/include/oracle/10.2.0.5/client64' '--with-system-tzdata=/usr/share/zoneinfo' '--sysconfdir=/etc/sysconfig/edb/as12' '--docdir=/usr/share/doc' '--with-pgport=5444' 'CFLAGS=-I/usr/libexec/edb-as12-icu53.1/include/ -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -I/usr/include/et' 'LDFLAGS=-L/usr/libexec/edb-as12-icu53.1/lib/ ' 'CPPFLAGS= -I/usr/include/et' 'CXXFLAGS= -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LLVM_CONFIG=/usr/lib64/llvm5.0/bin/llvm-config' 'CLANG=/opt/rh/llvm-toolset-7/root/usr/bin/clang' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig' 'ICU_CFLAGS=-I/usr/libexec/edb-as12-icu53.1/include/' 'ICU_LIBS=-Wl,-rpath,/usr/libexec/edb-as12-icu53.1/lib -L/usr/libexec/edb-as12-icu53.1/lib -licui18n -licuuc -licudata' 'PYTHON=/usr/bin/python2'
CC = gcc -std=gnu99
CPPFLAGS = -I/usr/libexec/edb-as12-icu53.1/include/ -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -I/usr/libexec/edb-as12-icu53.1/include/ -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -I/usr/include/et
CFLAGS_SL = -fPIC
LDFLAGS = -L/usr/libexec/edb-as12-icu53.1/lib/ -L/usr/lib64/llvm5.0/lib -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/edb/as12/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lrt -lcrypt -ldl -lxml2 -lm
VERSION = EnterpriseDB 12.4.5
