### ISSUE TITLE
Cannot create user mapping

### ISSUE THREAD

**Issue by svenkirsten** [laurenz/oracle_fdw#400]
Hi, 

I hit the same issue as already mentioned here: #321.

I don't understand the final solution to fix it.

**Comment by laurenz** [comment]
In that other ticket, the plaintiff connected to a database (let's call it `a`) and ran `CREATE SERVER` there.

Then he or she connected to a second database (`b`) and ran `CREATE USER MAPPING` there.

Naturally, that caused an error, because the referenced server did not exist in `b`.

**Comment by laurenz** [comment]
Is that case clear? Can I close the issue?
