### ISSUE TITLE
Incorrect date in select statment

### ISSUE THREAD

**Issue by entazy** [laurenz/oracle_fdw#402]
Hi, I have table in Oracle:

```
create table G_TAB (todate date);

SQL>  select todate from g_tab p;
TODATE
----------------------
4712-12-31 00:00:00 AD
```

On PostgreSql server with Oracle Database Client

```
select todate from g_tab p;
TODATE
----------------------
4712-12-31 00:00:00 AD
```

On PostgreSQL

```
=> CREATE FOREIGN TABLE ttt(
>               todate date
>            ) SERVER snap1 OPTIONS (schema 'DW', table 'G_TAB');


show datestyle
--------------------
ISO, DMY


select todate from ttt;
 todate
--------------------
 2012-12-31    ------PROBLEM


=> SELECT oracle_diag();
--------------------
oracle_fdw 2.2.0, PostgreSQL 11.5.12, Oracle client 12.1.0.2.0, ORACLE_HOME=/usr/lib/oracle/12.1/client64/lib
```

If

    SET datestyle = "ISO, YMD";

Then 

```
select todate from ttt;
 todate
--------------------
2031-12-12 00:00:00  ----Very Incorrect
```

I found look like problem: #284
But there is no result

Thanks

**Comment by entazy** [comment]
I noticed an interesting phenomenon. If run in psql
dwh=> select now();
               now
----------------------------------
 10-JUN-20 15:50:40.312358 +06:00

Then I don't see YYYY.

**Comment by laurenz** [comment]
I tried to reproduce it and failed again.

There is the faint possibility that there is an Oracle logon trigger that messes with the `NLS_DATE_FORMAT` that oracle_fdw sets. Could you investigate that?

Try setting

    export NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS BC'

Then connect with sqlplus and run

    SELECT value FROM nls_session_parameters WHERE parameter = 'NLS_DATE_FORMAT';

**Comment by entazy** [comment]
Hello.

I executed:
# export NLS_LANG=AMERICAN_AMERICA.AL32UTF8
# export NLS_DATE_FORMAT="YYYY-MM-DD HH24:MI:SS"
# env | grep -i nls
NLS_LANG=AMERICAN_AMERICA.AL32UTF8
NLS_DATE_FORMAT=YYYY-MM-DD HH24:MI:SS

SQLPLUS
SELECT value FROM nls_session_parameters WHERE parameter = 'NLS_DATE_FORMAT ;

VALUE
--------------------------------------------------------------------------------
DD.MM.RR

Another database returned the correct response.



I found trigger in the Oracle:

create or replace trigger C_CONNECT
  AFTER LOGON ON DATABASE
begin
    dbms_session.Set_NLS ('nls_territory','CIS');
    dbms_session.Set_NLS ('nls_numeric_characters','''.,''');
    dbms_session.Set_NLS ('nls_date_format','''DD.MM.RR''');
    dbms_session.Set_NLS ('nls_sort','BINARY');
end C_CONNECT;


What should I do?
Please give me your advice.

**Comment by laurenz** [comment]
Bingo!

Make sure that that silly trigger is removed. It breaks oracle_fdw and perhaps other well-behaved applications that set their own parameters.

If you cannot, use the development version of oracle_fdw and run this first:

    SELECT oracle_execute('ALTER SESSION SET NLS_DATE_FORMAT = ''YYYY-MM-DD HH24:MI:SS BC''');

**Comment by entazy** [comment]
I can’t delete this silly trigger because it is a external system, is denied to change. Administrative environments do not allow this.

Thanks for your advice, it worked.

If several selects run step by step, then
oracle_execute to execute before each select or execute once at start?

begin
  oracle_execute;
  select;
  oracle_execute;
  select;
  oracle_execute;
  select;
end;

or

begin
  oracle_execute;
  select;
  select;
  select;
end;

Thanks

**Comment by laurenz** [comment]
It is enough to call it once, like in your second example, because oracle_fdw caches Oracle connections for the duration of the database session.

**Comment by entazy** [comment]
Thank you!
