### ISSUE TITLE
Trigger on postgresql didn't recognize changes on oracle site

### ISSUE THREAD

**Issue by LutzSteinborn** [laurenz/oracle_fdw#404]
Hi,

I will monitor INSERTs on foreign tables.
For this I've created a simple table, a function and a trigger on the postgresql site. The trigger fires on "AFTER INSERT ON".
It works fine, then I INSERT a row on the foreign table at the postgresql site but the trigger didn't fire on INSERTs from the oracle site.
So what I'm doing wrong or is this the normal behavior?
Greetings
Lutz

`test=# SELECT oracle_diag();
                                                   oracle_diag
-----------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.3.0devel, PostgreSQL 12.3, Oracle client 19.6.0.0.0, ORACLE_HOME=/usr/lib/oracle/19.6/client64/lib`

**Comment by laurenz** [comment]
This is a duplicate of #342.

PostgreSQL has no way of knowing that data were modified on the Oracle side.

A trigger on a foreign table will only fire if you run DML statements **on the foreign table**, not on the remote Oracle table.

**Comment by LutzSteinborn** [comment]
Thank you for the fast response and sorry for the duplicate. This is a little bit of bad news. So we have the choice between polling and check for changes or buying golden gate from Oracle.

Regards!
