### ISSUE TITLE
Oracle wrong format

### ISSUE THREAD

**Issue by anes-madiyarov** [laurenz/oracle_fdw#406]
Can't run successfully make command. Has exception oracle_fdw.o could not read symbols: File in wrong format. collect2 run command finished with return code 1. Trying install oracle fdw on Centos 6

**Comment by laurenz** [comment]
Can you tell me the following:

1. Is all software involved (PostgreSQL, Oracle client) either 32-bit or 64-bit?
2. What is the installation path of Oracle client and PostgreSQL server?
3. Can you quote the complete `make` run, preserving the formatting?

**Comment by anes-madiyarov** [comment]
1. Yeah postgresql-10 installed, oracle sqlplus installed, 64 bit.
2. Paths are default. But haven't oracle instant client.
3. Can, share tomorrow. 
Can you tell me? Is it possible install oracle fdw to Centos 6 with i686 architecture?

**Comment by laurenz** [comment]
There are no default paths, sorry. The paths depend on how you installed the software.
You'll have to be more precise and tell me the actual paths.
If you install both PostgreSQL and Oracle as 32-bit binaries, then yes, you can build oracle_fdw that way. But who would want to do that in 2020?

**Comment by anes-madiyarov** [comment]
It's a hard life of developer in Kazakhstan)) Is it important architecture of OS? I am trying install on Centos 6 i 686? And you said that if have 32 bits binaries i can install. So x64 is not supportable?

**Comment by anes-madiyarov** [comment]
Do you have telegram account? Can i write to you if i have some questions?

**Comment by laurenz** [comment]
You can create an issue or buy professional support from my employer.
You cannot run 64-bit binaries on 32-bit Linux.
So get 32-bit builds of Oracle and PostgreSQL, and it should work.

**Comment by anes-madiyarov** [comment]
Ok thanks, will try it.
