### ISSUE TITLE
isolation_level

### ISSUE THREAD

**Issue by threenotrump** [laurenz/oracle_fdw#408]
Hello

I tried to create a foreign server with isolation level read committed but i am getting the error below

ERROR:  invalid option "isolation_level"

my command is:

CREATE SERVER someserver FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '10.1.1.1:1521/orcl',isolation_level  'read_committed');

what is the correct syntax for this command? I tried without single quotes. I can create server without isolation_level option.

oracle_fdw version :

 SELECT oracle_diag();
                         oracle_diag
-------------------------------------------------------------
 oracle_fdw 2.2.0, PostgreSQL 12.3, Oracle client 19.5.0.0.0

Best Regards 

Burak Yurdakul

**Comment by laurenz** [comment]
For that you need [the latest development version](https://github.com/laurenz/oracle_fdw/archive/master.zip), which should be stable.

**Comment by threenotrump** [comment]
Thank you very much for the quick response.

I have read the documents but couldnt find about upgrading the oracle_fdw.

Would reinstalling and recreating the extension or executing ALTER EXTENSION oracle_fdw UPDATE; command do the job?

**Comment by laurenz** [comment]
You have to build and install the software, overwriting the old files.

Then connect to each database where oracle_fdw is installed and run the SQL statement you suggested.

**Comment by threenotrump** [comment]
Thanks again for the response. Closing the issue.
