### ISSUE TITLE
Error ORA-12546 when trying to access to a remote Oracle database

### ISSUE THREAD

**Issue by plu9in** [laurenz/oracle_fdw#409]
Hi Laurenz,

I know that this error is common but I did not find any solution.

My distribution is a CentOS 8 - 64bits and my database is a postgresql 10.6.

I have installed the oracle client and I have no problem to connect via sqlplus with the following command
```
$ sqlplus user/password@ORCL_PRD
```
or with
```
$ sqlplus user/password@\\192.168.x.x:53000\ORCL
```

Both connections work fine. Mind that the Oracle database is not listing on the regular port but on 53000.

Then, I have compiled and installed your foreign data wrapper.
```
select oracle_diag();
=> oracle_fdw 2.2.0, PostgreSQL 10.6, Oracle, ORACLE_HOME=/usr/lib/oracle/19.6/client64
set client_min_messages=debug1;
=> SET
select oracle_diag('oracle');
=> DEBUG: oracle_fdw: set NLS_LANG=FRENCH_FRANCE.AL32UTF8
     ERROR: ERREUR: cannot connect to foreign Oracle server
     DETAIL: ORA-12546: TNS : permission denied.
```
Maybe the problem is that the Oracle database is on a Windows system and the Postgresql database is on a CentOS.
Any idea of what can go wrong ?

**Comment by laurenz** [comment]
Interesting, that's an error I haven't seen yet.

It sounds like the `postgres` operating system user doesn't have all the required permissions to use the Oracle client.

Did you run the successful connection attempt with sqlplus as operating system user `postgres`?

It would be interesting to establish a connection to PostgreSQL, then attach to the PostgreSQL backend process with `strace` and provoke the error. Then you should see in the trace exactly which permission is denied.

Also, what was your `CREATE SERVER` statement?

**Comment by plu9in** [comment]
Sorry Laurenz for the late reply.

*Did you run the successful connection attempt with sqlplus as operating
system user postgres?*
Yes. I thought about it. With sqlplus, I have no problem connecting to
Oracle DB with postgres system user.

I have noticed something weird in sqlplus logs. Apparently, when I send an
order 'select oracle_diag();', I find a log saying that I am trying to
connect with my Linux user. To be clear, I connect
to the server with my Linux user, then to the database with (for example)
postgres user (through psql) and I try an oracle_diag. The sqlnet.log shows
a log with a connection attempt with my user linux.

My create server statement was :
create server oracle foreign data wrapper oracle_fdw options (dbserver:
'//<address>:<port>/<DB_NAME>')

and I tried
create server oracle foreign data wrapper oracle_fdw options (dbserver:
'<SID>') with <SID> like in : sqlplus user/password@SID


I will do what you have suggested in your previous email concerning strace
when I am back at the office on Friday.

Thank you for your advice.

Le ven. 10 juil. 2020 à 16:56, Laurenz Albe <notifications@github.com> a
écrit :

**Comment by plu9in** [comment]
Sorry Laurenz for the late reply.

*Did you run the successful connection attempt with sqlplus as operating
system user postgres?*
Yes. I thought about it. With sqlplus, I have no problem connecting to
Oracle DB with postgres system user.

I have noticed something weird in sqlplus logs. Apparently, when I send an
order 'select oracle_diag();', I find a log saying that I am trying to
connect with my Linux user. To be clear, I connect
to the server with my Linux user, then to the database with (for example)
postgres user (through psql) and I try an oracle_diag. The sqlnet.log shows
a log with a connection attempt with my user linux.

My create server statement was :
```
create server oracle foreign data wrapper oracle_fdw options (dbserver:
'//<address>:<port>/<DB_NAME>')
```
and I tried
create server oracle foreign data wrapper oracle_fdw options (dbserver:
'<SID>') with <SID> like in : 
```
sqlplus user/password@SID
```

I will do what you have suggested in your previous email concerning strace
when I am back at the office on Friday.

Thank you for your advice.

**Comment by plu9in** [comment]
Hi Laurenz,
I am progressing. 

I stopped the DB (launched with systemctl) and started it by hand with postgres user. I was able to import the schema of my Oracle DB. So, I stopped again the database and restarted it with systemctl ... And then, I could not connect or select on imported schema.
```
ERROR:  ERROR:  connection for foreign table "test_connector" cannot be established
DETAIL:  ORA-12546: TNS : access denied
```
So, I need to fix permissions for systemd. However, I don't know to what I have to grant access to systemd ...
I will try to start postgres db at boot time with postgres user.

Thank you for your help.

**Comment by plu9in** [comment]
How do I disable it ?

**Comment by plu9in** [comment]
Yes. After disabling SELinux, I am able to connect to my Oracle DB.
Thank you Laurenz. Now it works.
Have you an idea on what I have to do to please SELinux ?

**Comment by laurenz** [comment]
I know nothing about SELinux except that it is a pain in the butt.

It probably has its uses when you are dealing with military level security, but other than that it is best disabled.

**Comment by plu9in** [comment]
You are right. I have disabled SELinux.

Thank you very much for your help and for your wrapper. It will help us a lot on migrating our corporate databases from Oracle to Postgres.
