### ISSUE TITLE
Error compilation

### ISSUE THREAD

**Issue by DavidMeteoFrance** [laurenz/oracle_fdw#41]
Hye Laurenz.
I get an error at compilation with PostgreSQL 9.5b1 and Oracle client 11g.
See below. 
However I've dowloaded the fdw_master.zip 
Thanks for your help.
Regards.

[yep@postgres-oracle_fdw-master]$ which pg_config
/usr/pgsql/bin/pg_config

[yep@postgres-oracle_fdw-master]$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -fpic -I/home/oracle/11g/client/sdk/include -I/home/oracle/11g/client/oci/include -I/home/oracle/11g/client/rdbms/public -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-9.5/include/server -I/usr/pgsql-9.5/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_fdw.o oracle_fdw.c
oracle_fdw.c: In function 'oracleGetForeignPlan':
oracle_fdw.c:876:8: error: too many arguments to function 'make_foreignscan'
        );
        ^
In file included from oracle_fdw.c:43:0:
/usr/pgsql-9.5/include/server/optimizer/planmain.h:46:21: note: declared here
 extern ForeignScan *make_foreignscan(List *qptlist, List *qpqual,
                     ^
make: *** [oracle_fdw.o] Error 1

**Comment by laurenz** [comment]
This is because of a PostgreSQL commit made after Beta 1.
See #40.

**Comment by DavidMeteoFrance** [comment]
Thanks Laurenz. 
This works fine. 
Regards 


Dav id PEYRIERES 
Direction des Systèmes d'Information 
Division Etudes et Développements 
Administration et Support Bases de Données 





Tel : +33 (0)5.61.07.83.36 
Fax : +33 (0)5.61.07.81.09 
david.peyrieres@meteo.fr 


METEO FRANCE 
www.meteo.fr 
42 avenue Gustave Coriolis 
31057 TOULOUSE Cédex 





----- Mail original -----

De: "Laurenz Albe" <notifications@github.com> 
À: "laurenz/oracle_fdw" <oracle_fdw@noreply.github.com> 
Cc: "David" <david.peyrieres@meteo.fr> 
Envoyé: Vendredi 6 Novembre 2015 08:50:21 
Objet: Re: [oracle_fdw] Error compilation (#41) 



This is because of a PostgreSQL commit made after Beta 1. 
See #40 .
