### ISSUE TITLE
ERROR:  no SELECT privilege on V$SQL in the remote database with simple query

### ISSUE THREAD

**Issue by MikhailVolosevitch** [laurenz/oracle_fdw#410]
I 'm trying to execute simple query "select * from sch1.scoring;" and error appears.

```
kobi=> IMPORT FOREIGN SCHEMA "INS" FROM SERVER oracle_kia INTO sch1;
IMPORT FOREIGN SCHEMA
kobi=> select * from sch1.scoring;
ERROR:  no SELECT privilege on V$SQL in the remote database
DETAIL:  ORA-00942: table or view does not exist
kobi=> SELECT oracle_diag('oracle_kia');
                                        oracle_diag
--------------------------------------------------------------------------------------------
 oracle_fdw 2.3.0devel, PostgreSQL 12.2, Oracle client 12.2.0.1.0, Oracle server 19.0.0.0.0
(1 row)
```

scoring - it is View in oracle database.
But if I do query to table in oracle database 0- there is no errors.

```
kobi=> select count(*) from sch1.sqln_explain_plan;
 count
-------
     0
(1 row)
```

**Comment by laurenz** [comment]
Does the Oracle view select from `V$SQL`?

If not, the only explanation for that error is that you actually don't perform a `SELECT`, but `EXPLAIN (VERBOSE) SELECT`.

**Comment by MikhailVolosevitch** [comment]
View doesn't select from v$sql. Only from user tables. But in view is directive "BEQUEATH DEFINER".
In details:
1. all the tables owns user1 and  owner of view also user1
2. I connect as user2 and select from view with definers rights from user1.view
3. I can do simple query as "select count(*) from view" on oracle database client on server with sqlplus
4. when I do the same query with foreign table error appears "ERROR:  no SELECT privilege on V$SQL in the remote database"

**Comment by laurenz** [comment]
That error message is from oracle_fdw, and the code path where that error message can happen is only taken if you run `EXPLAIN (VERBOSE)` in PostgreSQL. If you don't do that, something in your stack must do it for you.

You'll find that you don't get the error if you run the query with `psql`.

If you cannot figure out what does that, why don't you simply give the user `SELECT` privileges on `V$SQL`?

**Comment by MikhailVolosevitch** [comment]
We are integrating with our customer. And it doesn't want to grant select privilege on V$SQL for sequrity reason.
I not use any explain expression.

kobi_prod=> select count(*) from sch1.scoringagreement;
ERROR:  no SELECT privilege on V$SQL in the remote database
DETAIL:  ORA-00942: table or view does not exist

**Comment by laurenz** [comment]
I double checks, and I think that's impossible. But then, why should you lie?
Let's explore that mystery.

Can you please provide the following:

1. The `CREATE FOREIGN TABLE` statement for `sch1.scoringagreement`.

2. The output that you get when you set `client_min_messages = debug3`.

**Comment by MichaelDBA** [comment]
Deception, mystery ...

This sounds exciting im watching

**Comment by MikhailVolosevitch** [comment]
Hi.
I found the problem. When I set client_min_messages = debug3 

[postgres@srv-db prod]$ psql
DEBUG:  find_in_dynamic_libpath: trying "/opt/postgres/12/lib/auto_explain"
DEBUG:  find_in_dynamic_libpath: trying "/opt/postgres/12/lib/auto_explain.so"
DEBUG:  loaded library "auto_explain"
psql (12.2)

That is why. After I disabled extension, all the queries return results without error.
Thank you.

**Comment by laurenz** [comment]
Ah, that explains it. Thanks for the resolution.
