### ISSUE TITLE
ERROR:  could not load library "/usr/pgsql-9.6/lib/oracle_fdw.so": libmql1.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by asdarunasd** [laurenz/oracle_fdw#411]
i am facing this error while trying to create oracle_fdw extension 

ERROR:  could not load library "/usr/pgsql-9.6/lib/oracle_fdw.so": libmql1.so: cannot open shared object file: No such file or directory

i have exported all the required path 

$LD_LIBRARY_PATH =/usr/lib/oracle/18.5/client64/lib
$ORACLE_HOME = /usr/lib/oracle/18.5/client64/lib

pg_config path /usr/pgsql-9.6/bin

I am using postgres 9.6.18

**Comment by asdarunasd** [comment]
It worked when i added the path in /usr/lib/systemd/system/postgresql-9.6.service

**Comment by laurenz** [comment]
Thanks for sharing the solution, it will help others.
