### ISSUE TITLE
ORA-01722: invalid number

### ISSUE THREAD

**Issue by svenkirsten** [laurenz/oracle_fdw#414]
I run into this error when I try a select statement from the local created foreign PostgreSQL table. 
But not always. When I limit the output by a where clause then I get all lines as expected. 
But when I execute a select statement that involves all oracle rows , then I get this "invalid statement". 

    ERROR:  error executing query: OCIStmtExecute failed to execute remote query
    DETAIL:  ORA-01722: invalid number

In the oracle table there a two columns from type NUMBER. I tried to translated this into postgresql datatype (NUMERIC(10,2), VARCHAR(20), float4) but no success. 

The NUMBER column in the oracle table has max 10 digits before the decimal point and 2 digits after.  

Any idea ? 

```
postdb=> SELECT oracle_diag('remote_server');
                                        oracle_diag
--------------------------------------------------------------------------------------------
 oracle_fdw 2.3.0devel, PostgreSQL 12.2, Oracle client 19.5.0.0.0, Oracle server 12.1.0.2.0
(1 row)

postdb=>  SELECT oracle_diag();
                                                   oracle_diag
-----------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.3.0devel, PostgreSQL 12.2, Oracle client 19.5.0.0.0, ORACLE_HOME=/usr/lib/oracle/19.5/client64/lib
(1 row)
```

**Comment by laurenz** [comment]
Try to find out which row contains the problematic `NUMBER`.
How does the value look in Oracle?

**Comment by svenkirsten** [comment]
Hello, 
yes it seems to be that I found the affected rows. 
This column is from oracle type: VARCHAR2(20)
And I translated this to PostgreSQL type:   character varying(20)

To get this "invalid number" message the column contains for example this values : 100 101 102 103 ... or 1,001 1,002 1,003 1,004 and so on. 

But I dont understand this error because the datatype VARCHAR is a clear instruction to oracle to handle this as STRING not as NUMBERS.

**Comment by laurenz** [comment]
Please share the Oracle `CREATE TABLE` statement and the PostgreSQL `CREATE FOREIGN TABLE` statement.
And tell me which column causes the problem.

**Comment by laurenz** [comment]
Did you figure out the problem?
Shall I close the issue?

**Comment by svenkirsten** [comment]
Hi Laurenz, 

Ich schreib jetzt mal in Deutsch. 

Mein Kollege betreibt die Oracle Seite und ich die PostgreSQL Seite. 
Und mein Kollege ist noch ein paar Tage im Urlaub. 

Und nur er kann mir/uns sagen wie er den Oracle View angelegt hat. 

Sobald er wieder zurück ist - schreib ich ihn nochmal an. 

Danke 

Gruß 
Sven

**Comment by laurenz** [comment]
Ok, I'll wait for feedback. Just wanted to know if you are still on it.

**Comment by laurenz** [comment]
Any news on the problem?

**Comment by svenkirsten** [comment]
Hallo Laurenz, 

Ich muss den Kollegen nochmal anschreiben. 
>> Der rührt sich net ! 

Danke für den Reminder 

Gruß
Sven

**Comment by laurenz** [comment]
Please reopen the issue if you have new information.
