### ISSUE TITLE
Insert into nvarchar2 column

### ISSUE THREAD

**Issue by srakazmus** [laurenz/oracle_fdw#416]
Hello Laurenz,
I tried to insert  text with some special characters into fdw_table column with nvarchar2 type.
Unfortunately some data get lost during insert or select to fdw_table.

For instance if I insert 'èà' into fdw_table column type varchar(2000) which is a representation of NVARCHAR2(2000) Oracle column I get '??' on Oracle side. If I insert 'èà' directly into oracle table and select it with fdw_table I get again '??'.

Is there any solution for this? If not, do you know any workaround for this? Maybe to convert data to some other format, insert it into oracle BLOB column and on Oracle side convert it back to NVARCHAR2?

Jan

POSTGRES:
select version();
PostgreSQL 12.1 on x86_64-pc-linux-gnu, compiled by gcc (SUSE Linux) 7.4.1 20190424 [gcc-7-branch revision 270538], 64-bit
show client_encoding;UTF8
show server_encoding;UTF8

ORACLE: 
NLS_NCHAR_CHARACTERSET	AL16UTF16
NLS_CHARACTERSET	EE8ISO8859P2
Oracle version: 11.2.0.4.0

ORACLE_FDW: oracle_fdw 2.2.1devel, PostgreSQL 12.1, Oracle client 19.3.0.0.0, Oracle server 11.2.0.4.0

**Comment by laurenz** [comment]
I tested it, and it works fine on my system.

To investigate, try the following on Oracle to see what is stored there:

    SELECT dump(nvarchar_col, 16) FROM atable WHERE ...;

That should gibe us the binary values. The result at my system is:

```
SQL> SELECT id, dump(n, 16) FROM nvc;

	ID DUMP(N,16)
---------- ----------------------------------------
	 1 Typ=1 Len=4: 0,e8,0,e0
	 2 Typ=1 Len=4: 0,e8,0,e0
```

Then it would be interesting to see the actual value in PostgreSQL.

This can be done by casting the values to `bytea`. In my example:

```
SELECT id, n::bytea FROM nvc;

 id |     n      
----+------------
  1 | \xc3a8c3a0
  2 | \xc3a8c3a0
(2 rows)
```

Also, the result to the following would be interesting in PostgreSQL:

```
SHOW client_encoding;
```

A potential problem could be the configuration of your terminal. What looks like <code>&egrave;</code> when you type it might actually be something else.

**Comment by srakazmus** [comment]
I don't know what am I doing wrong. Here are my tests:

**ORACLE:**
```
create table CHARTEST_ORA
(
  nchar1 NVARCHAR2(100)
);
insert into CHARTEST_ORA (nchar1) values (n'èà');
select nchar1, dump(nchar1, 16) from CHARTEST_ORA;

NCHAR1	DUMP(NCHAR1,16)
èà	Typ=1 Len=4: 0,e8,0,e0
```

**POSTGRES:**

```
show client_encoding;
 UTF8
show server_encoding;
 UTF8

import foreign schema "MAGONLINE_TEST" limit to (
chartest_ora
) from server magtexn into vopi_ora;

magpostest=> select nchar1::bytea, nchar1 from vopi_ora.chartest_ora;
 nchar1 | nchar1
--------+--------
 \x3f3f | ??
(1 row)

create table vopi_ora.CHARTEST_PG
(
  char1 VARCHAR(100)
);
insert into vopi_ora.CHARTEST_PG (char1) values ('èà');

magpostest=> select char1::bytea, char1 from vopi_ora.CHARTEST_PG;
   char1    | char1
------------+-------
 \xc3a8c3a0 | èà
(1 row)
```

**ORACLE:**
`delete from CHARTEST_ORA`;
**POSTGRES:**
`insert into vopi_ora.chartest_ora select char1 from vopi_ora.CHARTEST_PG;`
**ORACLE:**
```
select nchar1, dump(nchar1, 16) from CHARTEST_ORA;
NCHAR1	DUMP(NCHAR1,16)
??	Typ=1 Len=4: 0,3f,0,3f
```
As an alternative I was trying to insert UTF8 text in some kind of encoded format that I would be able to decode and insert into nvarchar2 column on Oracle side but without success.

Jan

**Comment by srakazmus** [comment]
After a lot of testing I found a workable workaround:

**POSTGRES:**
```
magpostest=> SELECT ENCODE(CONVERT_TO('èà', 'UTF-8'), 'base64');
  encode
----------
 w6jDoA==
(1 row)
```

**ORACLE:**
```
select UTL_RAW.CAST_TO_NVARCHAR2(UTL_RAW.CONVERT(UTL_ENCODE.BASE64_DECODE(UTL_RAW.CAST_TO_RAW ('w6jDoA==')),'SLOVENIAN_SLOVENIA.AL16UTF16','SLOVENIAN_SLOVENIA.AL32UTF8')) as label from dual;

LABEL
èà
```
I have an alternative solution for now but I would be very thankful if you would find out what am I doing wrong with oracle_fdw.

Jan

**Comment by laurenz** [comment]
I have an idea. Perhaps you are using the "Basic Lite" Oracle Instant Client, which does not support all character sets.
If yes, try with "Basic".

**Comment by srakazmus** [comment]
I think I already have Oracle basic client installed.
```
postgres@magpos-test:/> rpm -qa | grep oracle
oracle-instantclient19.3-jdbc-19.3.0.0.0-1.x86_64
oracle-instantclient19.3-sqlplus-19.3.0.0.0-1.x86_64
oracle-instantclient19.3-basic-19.3.0.0.0-1.x86_64
oracle-instantclient19.3-devel-19.3.0.0.0-1.x86_64
```

**Comment by laurenz** [comment]
Do things look OK if you use sqlplus from the PostgreSQL machine after setting

    export NLS_LANG=AMERICAN_AMERICA.AL32UTF8

**Comment by srakazmus** [comment]
I can select properly inserted characters from database but I can not insert them. Only if I use unistr. So you think there is something wrong with my Oracle instant client? 

```
SQL> insert into CHARTEST_ORA (nchar1) values ('èà');
insert into CHARTEST_ORA (nchar1) values (n'èà');
insert into CHARTEST_ORA values(unistr('\00E8\00E0'));
1 row created.
SQL>
1 row created.
SQL>
1 row created.
SQL> select nchar1, dump(nchar1, 16) from CHARTEST_ORA;

NCHAR1
--------------------------------------------------------------------------------
DUMP(NCHAR1,16)
--------------------------------------------------------------------------------
??
Typ=1 Len=4: 0,3f,0,3f

??
Typ=1 Len=4: 0,3f,0,3f

èà
Typ=1 Len=4: 0,e8,0,e0
```

**Comment by laurenz** [comment]
Perhaps something is wrong with your terminal settings.
Try the following from the shell:

```bash
$ echo -n 'èà' | od -t x1
0000000 c3 a8 c3 a0
0000004
```

Do you get the same output?

**Comment by srakazmus** [comment]
yes
```
postgres@magpos-test:/> echo -n 'èà' | od -t x1
0000000 c3 a8 c3 a0
0000004
```

**Comment by laurenz** [comment]
Hm. There goes that theory.

Well, since you have the same problem with sqlplus, it must be something with the client setup.
If the `NLS_LANG` environment variable is set correctly, Oracle should correctly convert the characters...
oracle_fdw sets `NLS_LANG` correctly before connecting to Oracle.

There are no such problems with a normal `VARCHAR2`, right?

Sorry, but I don't know what the problem is...

**Comment by srakazmus** [comment]
No problems with varchar2. 
Thanks a lot. Do you recomend reinstalation of instant client?

**Comment by laurenz** [comment]
I don't think that's going to make a lot of difference.

Perhaps you can ask Oracle for help with that character conversion problem, since it can be reproduced with Oracle tools alone.
I don't have the resources to set up an Oracle database with a single byte character set and analyse the problem, and I don't have access to Oracle's support.

**Comment by chrullrich** [comment]
Pardon me for intruding, and I'm aware I'm probably talking nonsense, so if I do, just tell me to shut up.

I just read up a bit on Oracle's N... datatypes and how they're used, and ISTM that oracle_fdw is getting something wrong. In particular, Oracle says that to bind an NCHAR-type parameter an attribute named OCI_ATTR_CHARSET_FORM should be set to SQLCS_NCHAR so the incoming data is converted directly from the client character set to the "national character set" (NLS_NCHAR_CHARACTERSET?), and not via the database character set. oracle_fdw does not do that as far as I can tell.

ISO-8859-2 does not contain the characters in question. It has the versions with acute accent (éá), but not the ones with grave accent (èà), so if they get converted through EE8ISO8859P2, it is reasonable that they are lost.

@srakazmus, do the acute-accent characters work?

**Comment by srakazmus** [comment]
Thank you both for helping me solve this problem. I made some additional research and managed to persuade local SQLPLUS client to send special characters to nvarchar2 field.
I had to set following environment variables:
```
export NLS_LANG=AMERICAN_AMERICA.AL32UTF8
export LC_CTYPE="en_US.UTF-8"
export ORA_NCHAR_LITERAL_REPLACE=true

SQL> insert into CHARTEST_ORA (nchar1) values (n'èà');

1 row created.
SQL> select nchar1, dump(nchar1, 16) from CHARTEST_ORA;
NCHAR1
--------------------------------------------------------------------------------
DUMP(NCHAR1,16)
--------------------------------------------------------------------------------
èà
Typ=1 Len=4: 0,e8,0,e0
```
source: https://stackoverflow.com/questions/6509751/inserting-national-characters-into-an-oracle-nchar-or-nvarchar-column-does-not-w
I also checked https://docs.oracle.com/cd/B28359_01/server.111/b28298/ch7progrunicode.htm (NCHAR String Literal Replacement)

Laurenz, do you think we can do something like this with oracle_fdw?

**Comment by srakazmus** [comment]
Chapter from https://docs.oracle.com/cd/B28359_01/server.111/b28298/ch7progrunicode.htm seems like it might work in my situation 

> **Handling SQL NCHAR String Literals in OCI**
> By default, the NCHAR literal replacement is not performed in OCI. (Refer to "NCHAR String Literal Replacement".)
> 
> You can switch it on by setting the environment variable ORA_NCHAR_LITERAL_REPLACE to TRUE. You can also achieve this behavior programmatically by using the OCI_NCHAR_LITERAL_REPLACE_ON and OCI_NCHAR_LITERAL_REPLACE_OFF modes in OCIEnvCreate() and OCIEnvNlsCreate(). So, for example, OCIEnvCreate(OCI_NCHAR_LITERAL_REPLACE_ON) turns on NCHAR literal replacement, while OCIEnvCreate(OCI_NCHAR_LITERAL_REPLACE_OFF) turns it off.

```
OCIEnvCreate((OCIEnv **) &envhp,
   (ub4)OCI_THREADED|OCI_NCHAR_LITERAL_REPLACE_ON,
   (dvoid *)0, (dvoid * (*)(dvoid *, size_t)) 0,
   (dvoid * (*)(dvoid *, dvoid *, size_t))0,
   (void (*)(dvoid *, dvoid *)) 0,
   (size_t) 0, (dvoid **) 0)
```

**Comment by laurenz** [comment]
Oh, good research, thanks.

The handling of `NCHAR` and `NVARCHAR2` is complicated and messy, and I don't claim that I truly understand it.
I remember that Oracle's documentation claims that character set conversion does *not* work for `NCLOB` at all, which is why I don't support it in oracle_fdw (besides, the data type seems useless, since `CLOB` is stored in Unicode anyway).

I wrote a potential fix that sets `OCI_NCHAR_LITERAL_REPLACE_ON` in `OCIEnvCreate`; could you try [this patched version](https://github.com/laurenz/oracle_fdw/archive/fix-nchar.zip)?

@chrullrich I am not sure. Look at [this](https://docs.oracle.com/en/database/oracle/oracle-database/18/lnoci/handle-and-descriptor-attributes.html#GUID-01C53C14-CD15-4A8B-9EFF-86996282F3BD):

> `OCI_ATTR_CHARSET_FORM`
>
> Character set form of the bind handle. The default form is `SQLCS_IMPLICIT`. Setting this attribute causes the bind handle to use the database or national character set on the client side. Set this attribute to `SQLCS_NCHAR` for the national character set or `SQLCS_IMPLICIT` for the database character set.

That sounds like the characters will show up in UCS-2 (which is used for `CLOB`s internally) on the client side if `SQLCS_NCHAR` is set, and that would not be useful.

If @srakazmus reports back that my patch doesn't work, I'll give it a try.

**Comment by chrullrich** [comment]
My source was https://docs.oracle.com/cd/B28359_01/server.111/b28298/ch7progrunicode.htm#CACGCEAI, and I admit I had not seen the reference to UTF-16 there. I wonder if using OCIEnvNlsCreate() and setting the NCHAR charset to UTF-8 might help. https://docs.oracle.com/cd/B28359_01/server.111/b28298/ch10oci.htm#i1005942 says that this specifies the encoding of NCHAR data, see also https://docs.oracle.com/cd/B28359_01/appdev.111/b28395/oci02bas.htm#LNOCI87644 which self-contradictorily states that only UTF-16 and any character set other than UTF-16 can be used.

Also, is NVARCHAR the same as NCLOB, or something else? You seem to say they are the same.

Finally, I'd really like to know the answer to my question to @srakazmus about the behavior of characters present in ISO-8859-2. If they are converted to question marks as well, the problem probably has nothing to do with charsets at all. In that case, a network trace (or strace or equivalent, or Oracle's logging equivalent for raw socket data, if there is one) might help to determine where the question marks first appear.

**Comment by srakazmus** [comment]
Unfortunately setting OCI_NCHAR_LITERAL_REPLACE_ON in OCIEnvCreate doesn't seem to help. It works the same as before. What bothers me is that even select from nvarchar2 column doesn't show 'èà' properly. It selects ?? from fdw_table.

@chrullrich, there are no problems with 'éá' characters (not 'èà') which are included in ascii character set. Insert and select works well from sqlplus and from oracle_fdw. Even if I don't prefix literal with **n**('éá').

@laurenz As I understand CLOB in single-byte character set database doesn't include unicode characters. Only NCLOB does.

**Comment by chrullrich** [comment]
Thank you for confirming that. “ASCII” is 7-bit and does not contain any accented characters. You are probably referring to ISO-8859-2, aka Oracle EE8ISO8859P2, which contains éá but not èà. The acute-accent characters work under all circumstances because they are in the single-byte database character set.

My guess, as I think it was @laurenz's before, is that the grave-accent characters do not because they are converted first into the single-byte database character set, which fails because they do not exist in it and turns them into question marks, then the _question marks_ are converted to the NCHAR character set and stored in the table.

**Comment by srakazmus** [comment]
You are right. I was refering to EE8ISO8859P2 (latin2) character set.

**Comment by srakazmus** [comment]
If I insert values 'èà that I select from the same foreign table, information is lost in this transaction:

Postgres:
`insert into vopi_ora.chartest_ora select nchar1 from vopi_ora.CHARTEST_ORA;`


Oracle:
```
SQL> select * from chartest_ora;
NCHAR1
--------------------------------------------------------------------------------
èà
??
```

OCI_NCHAR_LITERAL_REPLACE_ON only tels client to use **n** prefix literlas as unicode.
So, if I use oracle_execute and insert literals directly into oracle tables it works fine. It also works if I select values from remote table using execute.
```
SELECT extensions.oracle_execute('magtexn', 'insert into magonline_test.CHARTEST_ORA (nchar1) values (n''èà'')');
SELECT extensions.oracle_execute('magtexn', 'insert into magonline_test.CHARTEST_ORA select nchar1 from magonline_test.CHARTEST_ORA');
```
Another workaround would be creating dynamic DML SQL-s and execute them with oracle_execute.

**Comment by srakazmus** [comment]
I also changed OCIEnvCreate function to
```
OCIEnvNlsCreate((OCIEnv **) &envhp,
				(ub4)OCI_OBJECT | OCI_NCHAR_LITERAL_REPLACE_ON,
				(dvoid *) 0, (dvoid * (*)(dvoid *,size_t)) 0,
				(dvoid * (*)(dvoid *, dvoid *, size_t)) 0,
				(void (*)(dvoid *, dvoid *)) 0, (size_t) 0, (dvoid **) 0, (ub2)OCI_UTF16ID, (ub2)OCI_UTF16ID)
```
But I would probably have to change more things (I'm no C programer). It doesn't work.

**Comment by laurenz** [comment]
Bummer.
I have followed up on @chrullrich's idea and set `OCI_ATTR_CHARSET_FORM` to `SQLCS_NCHAR` in all bind and define handles.

Could you try [the latest snapshot](https://github.com/laurenz/oracle_fdw/archive/fix-nchar.zip) and see if that improves things?

**Comment by srakazmus** [comment]
Brilliant!
Everything works!

```
insert into vopi_ora.chartest_ora select char1 from vopi_ora.CHARTEST_PG; 
insert into vopi_ora.chartest_ora select nchar1 from vopi_ora.CHARTEST_ORA;
insert into vopi_ora.chartest_ora values ('èà');
select nchar1::bytea, nchar1 from vopi_ora.CHARTEST_ORA;
nchar1  |nchar1|
--------|------|
Ã¨Ã     |èà    |
Ã¨Ã Ã©Ã¡|èàéá  |
Ã¨Ã Ã©Ã¡|èàéá  |
```


Thank you both!

**Comment by laurenz** [comment]
Thanks everybody for your help!

**Comment by laurenz** [comment]
A heads up:
Several people had problems with that patch.
Some complained about the performance impact (see #435 and #434), and it causes ORA-01461 errors if an `UPDATE` sets a string over 2000 bytes (#453).

The first was partly mitigated with commit 5fd556f60274c6c287104f0a2aa90b8075e663cb, but I couldn't find a workaround for the error.

So I have committed 5fd556f60274c6c287104f0a2aa90b8075e663cb.
That introduces a foreign server option `nchar` that you have set to `on` or `true` to get the correct, but problematic character conversion.
You will have to use that option as soon as you upgrade to a version of oracle_fdw that includes that change.
