### ISSUE TITLE
Getting error whole running create server command

### ISSUE THREAD

**Issue by Saurabh-704** [laurenz/oracle_fdw#421]
Hello!
I am getting error when I am trying to create server -
<img width="663" alt="f" src="https://user-images.githubusercontent.com/47383623/91939635-cf854280-ed13-11ea-911d-cce46c15b527.png">

Note-
1)I have checked for the env path of oracle n postgres home n lib path and its there in ~/.bash_profile.
2)libclntsh.so.12.1 file is there in "/usr/lib/oracle/19.8/client64/lib" location
3) I have file named "postgresql-12.service" in "/etc/systemd/system" location with content -

.include /usr/lib/systemd/system/postgresql-12.service
[Service]
Environment=LD_LIBRARY_PATH=/usr/lib/oracle/19.8/client64/lib

I have all this thing configured in my linux env but still I have facing that issue.
Can you please help me with this ?

**Comment by laurenz** [comment]
Look at issue #64 and try the command mentioned there:

    cat /proc/<pid>/environ | xargs -0 -n 1

where `<pid>` is the process ID of the PostgreSQL server process (postmaster).

Did you run this:

    sudo systemctl daemon-reload
    sudo systemctl restart postgresql-12

**Comment by Saurabh-704** [comment]
Hey @laurenz ! Thank you for your response. 
I have ran that cat command n this is the output -
<img width="368" alt="f1" src="https://user-images.githubusercontent.com/47383623/91955073-46c0d380-ed20-11ea-935a-6394ab6d7426.png">

And in /etc/ld.so.conf there was no oracle home path so i have given home path like this -
<img width="239" alt="f2" src="https://user-images.githubusercontent.com/47383623/91955207-78399f00-ed20-11ea-8df0-92bc3c5b8a18.png">

And after that I reloaded and restarted the postgres but still getting that issue.

**Comment by laurenz** [comment]
Ah, I see. You linked against Oracle 12, but try to run with Oracle client 19.8.

Your `/etc/ld.so.conf` is wrong, there should be one directory per line. Putting `/lib` there is unnecessary too.
Also, what is that Oracle 12 path in the last line? That shouldn't be there.
For simplicity, don't install more than one version of Oracle client at the same time.

What do you get for

    ls -l /usr/lib/oracle/19.8/client64/lib/libclntsh.*
    file /usr/lib/oracle/19.8/client64/lib/libclntsh.so.12.1

**Comment by Saurabh-704** [comment]
Hello!
I am attaching ss of the output which I got -
For - ls -l /usr/lib/oracle/19.8/client64/lib/libclntsh.*
<img width="923" alt="f3" src="https://user-images.githubusercontent.com/47383623/91967528-fbfb8780-ed30-11ea-9678-3d29678cc172.png">

And for file /usr/lib/oracle/19.8/client64/lib/libclntsh.so.12.1 -
<img width="557" alt="f4" src="https://user-images.githubusercontent.com/47383623/91967606-13d30b80-ed31-11ea-827d-0d12ef875c94.png">

**Comment by laurenz** [comment]
You somehow messed up your Oracle installation.

`libclntsh.so.12.1` points to `libclntsh.so.12.1.XX`, and `libclntsh.so.12.1.XX` points to `libclntsh.so.12.1` in a different directory.
When loading the dependencies of `libclntsh.so.12.1`, the loader will look in `/usr/lib/oracle/19.8/client64/lib` and find libraries that don't match.

You should fix it as follows:

- Remove the Oracle 12 installation.

- Fix the symbolic links as follows:

      rm -f  /usr/lib/oracle/19.8/client64/lib/libclntsh.so.12.1
      rm -f  /usr/lib/oracle/19.8/client64/lib/libclntsh.so.12.1.XX
      ln -s libclntsh.so.19.1 /usr/lib/oracle/19.8/client64/lib/libclntsh.so.12.1

That should do the trick.

**Comment by Saurabh-704** [comment]
Thank you @laurenz for your response. I will try this one time. But for a doubt can I simply just run that two rm command  without removing oracle 12 and create that symoblic link ?!
Will it cause any trouble If i do like this?

**Comment by laurenz** [comment]
Yes, that won't do any harm to your Oracle 12 installation.

But it were best if you remove Oracle 12.
If not, make sure that the Oracle 12 library directory is **not** in `LD_LINRARY_PATH` and is **not** in `/etc/ld.so.conf`.

**Comment by Saurabh-704** [comment]
Hey @laurenz thank you for your help. It is working now. Thanks for your help.
