### ISSUE TITLE
Open Source Alternatives to OCI

### ISSUE THREAD

**Issue by timnlupo** [laurenz/oracle_fdw#422]
Hi all, I wanted to inquire to see if it was possible to use this library without Oracle Instant Client, preferably some open-source alternative. Thanks so much.

**Comment by laurenz** [comment]
There is no open source implementation for Oracle database. If you want to speak to an Oracle database, you need proprietary Oracle software.

It doesn't have to be Instant Client, it can be the client installed with Oracle Universal Installer, or it could be the client software that is part of the Oracle server installation. But it has to be Oracle.

**Comment by timnlupo** [comment]
Understood, thank you for the help.
