### ISSUE TITLE
ERROR:  could not load library

### ISSUE THREAD

**Issue by Argha-2890** [laurenz/oracle_fdw#424]
Hi Team,

I am getting the below error while trying to create the extension.

```
postgres=# create extension oracle_fdw;
ERROR:  could not load library "/usr/lib/postgresql/11/lib/oracle_fdw.so": libclntsh.so.18.1: cannot open shared object file: No such file or directory
```

**PostgreSQL Version : 11
OS Version : Ubuntu 18.04**

Path Details : 

```

ubuntu@xxxxxxx:/usr/lib/oracle/18.5/client64/lib$ echo $ORACLE_HOME
/usr/lib/oracle/18.5/client64
ubuntu@xxxxxxx:/usr/lib/oracle/18.5/client64/lib$
ubuntu@xxxxxxx:/usr/lib/oracle/18.5/client64/lib$ echo $LD_LIBRARY_PATH
/usr/lib/oracle/18.5/client64/lib/

ubuntu@xxxxxxx:/usr/lib/oracle/18.5/client64/lib$ ls -larth libc*
-rwxr-xr-x 1 root root 8.0M Feb 26  2019 libclntshcore.so.18.1
-rwxr-xr-x 1 root root  75M Feb 26  2019 libclntsh.so.18.1
lrwxrwxrwx 1 root root   17 Sep 21 05:37 libclntsh.so -> libclntsh.so.18.1

ubuntu@xxxxxxx:/usr/lib/oracle/18.5/client64/lib$ sudo cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf
include /usr/lib/oracle/18.5/client64/lib
include /usr/lib/oracle/18.5/client64

ubuntu@xxxxxxx:/usr/lib/oracle/18.5/client64/lib$ ls -larth /usr/share/postgresql/11/extension/oracle*
-rw-r--r-- 1 root root  133 Sep 21 07:19 /usr/share/postgresql/11/extension/oracle_fdw.control
-rw-r--r-- 1 root root 1003 Sep 21 07:19 /usr/share/postgresql/11/extension/oracle_fdw--1.1.sql
-rw-r--r-- 1 root root  231 Sep 21 07:19 /usr/share/postgresql/11/extension/oracle_fdw--1.0--1.1.sql
```

Could you please confirm what I am doing wrong.

**Comment by laurenz** [comment]
You didn't set `LD_LIBRARY_PATH` (and perhaps `ORACLE_HOME`) in the environment of the PostgreSQL server process.

See #64, #161 and #322 for more.

Setting it in `.bash_profile` of the `postgres` user isn't enough, you have to adapt the PostgreSQL startup process.
With the Ubuntu binaries, there is a file somewhere in `/etc` where you can set the environment of the PostgreSQL server.

**Comment by Argha-2890** [comment]
@laurenz - The issue is resolved. I added the environment variables in /etc/environment and also added the library path in /etc/ld.so.conf file. Post making these changes I am able to use oracle_fdw against my Oracle DB. 

Really appreciate  your help.

I want to do a round of load testing for measuring the performance. Just wanted to know what could be a good tool etc for the same.

**Comment by laurenz** [comment]
Thanks for the feedback.

Perhaps you can use `pgbench` for a load test; you can use it with custom SQL statements.
