### ISSUE TITLE
OCIStmtFetch2 failed to fetch next result row: ORA-01406

### ISSUE THREAD

**Issue by kvaikla** [laurenz/oracle_fdw#425]
hi,
how to set max_long for db_migrator

**Comment by laurenz** [comment]
That is actually an [`ora_migrator`][1] issue.

You can use the `max_long` option of `db_migrate_prepare`, `db_migrate_mkforeign` and `db_migrate`.

An example:

    SELECT db_migrate_prepare(..., options => '{ "max_long": 1000000 }');

I had forgotten to document that, fixed with https://github.com/cybertec-postgresql/ora_migrator/commit/b02b00ef1e773dbb7866022aef853c733e33f21c.


 [1]: https://github.com/cybertec-postgresql/ora_migrator

**Comment by kvaikla** [comment]
thnx, works. But a few notes.
`pg=> SELECT oracle_diag();
                                                oracle_diag
------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.3.0, PostgreSQL 12.1, Oracle client 19.8.0.0.0, ORACLE_HOME=/usr/lib/oracle/19.8/client64/lib
(1 row)
`
Errors like:
`
WARNING:  Error loading table data for schema.table
DETAIL:  invalid XML content: line 645: Premature end of data in tag Period line 643
line 645: Premature end of data in tag AvailableCapacity line 502
line 645: Premature end of data in tag Unit line 494
`
`
WARNING:  Error loading table data for schema.table
DETAIL:  invalid XML content: line 735: Couldn't find end of Start Tag UnavailableC line 735
line 735: Premature end of data in tag EventTimePeriod line 734
line 735: Premature end of data in tag TimePeriods line 565
`
indicates to too small max_long as well. oracle_fdw 2.2.0 error is ORA-01406, but not with oracle_fdw 2.3.0

**Comment by laurenz** [comment]
So, what happens with oracle_fdw 2.3.0?

**Comment by kvaikla** [comment]
Errors above are with 2.3.0

**Comment by laurenz** [comment]
Looks like the XML is not correct. Try mapping it to `text` and see how it looks.

**Comment by kvaikla** [comment]
No, my point is, errors above can fix when increasing  max_long

**Comment by laurenz** [comment]
Ah, so your problem is fixed?

**Comment by kvaikla** [comment]
jep. closed.
