### ISSUE TITLE
error connecting to Oracle: OCIEnvCreate failed to create environment handle

### ISSUE THREAD

**Issue by kirandba-hub** [laurenz/oracle_fdw#426]
Hi,

I have installed the oracle_fdw and created the extension also i have create the foreign server,user mapping and foreign table.
When i am doing select * from table;

Getting below error

ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
DETAIL:

Below is the configuation

export ORACLE_HOME=/u01/app/oracle/product/12.1.0.2/dbhome_1
export TNS_ADMIN=$ORACLE_HOME/network/admin
export PATH=$ORACLE_HOME/bin:/usr/pgsql-11/bin/:$PATH
export LD_LIBRARY_PATH=/u01/app/oracle/product/12.1.0.2/dbhome_1/lib

can you please help to sort out this.

Thanks,
Kiran

**Comment by laurenz** [comment]
If sqlplus works, then there is probably a problem in the environment of your PostgreSQL server.

Look at #307 and the many issues linked from there.

What do you get for the postmaster's environment (see for example https://github.com/laurenz/oracle_fdw/issues/305#issuecomment-474340877)?

**Comment by kirandba-hub** [comment]
Hi Laurenz,

Operating system - Red Hat Enterprise Linux Server release 7.5 (Maipo)

XDG_SESSION_ID=c217
HOSTNAME=xxxxxx
TERM=xterm
SHELL=/bin/bash
HISTSIZE=1000
PG_GRANDPARENT_PID=62674
QTDIR=/usr/lib64/qt-3.3
QTINC=/usr/lib64/qt-3.3/include
QT_GRAPHICSSYSTEM_CHECKED=1
USER=postgres
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
PATH=/usr/pgsql-11/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin
MAIL=/var/spool/mail/postgres
_=./pg_ctl
PWD=/usr/pgsql-11/bin
PGLOCALEDIR=/usr/pgsql-11/share/locale
LANG=en_US.UTF-8
PGSYSCONFDIR=/etc/sysconfig/pgsql
HISTCONTROL=ignoredups
HOME=/u001/pgcluster
SHLVL=1
LOGNAME=postgres
QTLIB=/usr/lib64/qt-3.3/lib
LESSOPEN=||/usr/bin/lesspipe.sh %s
PGDATA=/u001/pgcluster/11
PROMPT_COMMAND=logger -p local6.debug "$(whoami) ${SHELL}[$$]: $(history 1 | sed "s/^[ ]*[0-9]\+[ ]*//" )"
PG_LOG=/u001/pgcluster/11/pg_log
HISTTIMEFORMAT=%d/%m/%y %T

Thanks,
Kiran

**Comment by kirandba-hub** [comment]
also i observer, when i list the extension oracle_fdw version is 1.2 and when i do select oracle_diag(); the extension is 2.3.0

gdsrm_sdm=> select oracle_diag();
                         oracle_diag
-------------------------------------------------------------
 oracle_fdw 2.3.0, PostgreSQL 11.7, Oracle client 12.1.0.2.0
(1 row)

**Comment by kirandba-hub** [comment]
Hi Laurenz,

Can you please help i am not able to replicate the problem.

Thanks,
Kiran

**Comment by laurenz** [comment]
The extension version and the orcle_fdw version are different, I think I mentioned that in the documentation.

You'll have to configure the startup process for PostgreSQL so that it gets the requires Oracle environment variables; see the many other issues I linked to.

**Comment by kirandba-hub** [comment]
Okay Laurenz.

Below is the postgresql-11.service

[Unit]
Description=PostgreSQL 11 database server
Documentation=https://www.postgresql.org/docs/11/static/
After=syslog.target
After=network.target

[Service]
Type=notify

User=postgres
Group=postgres

# Note: avoid inserting whitespace in these Environment= lines, or you may
# break postgresql-setup.

# Location of database directory
Environment=PGDATA=/var/lib/pgsql/11/data/

# Where to send early-startup messages from the server (before the logging
# options of postgresql.conf take effect)
# This is normally controlled by the global default set by systemd
# StandardOutput=syslog

# Disable OOM kill on the postmaster
OOMScoreAdjust=-1000
Environment=PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj
Environment=PG_OOM_ADJUST_VALUE=0

ExecStartPre=/usr/pgsql-11/bin/postgresql-11-check-db-dir ${PGDATA}
ExecStart=/usr/pgsql-11/bin/postmaster -D ${PGDATA}
ExecReload=/bin/kill -HUP $MAINPID
KillMode=mixed
KillSignal=SIGINT


# Do not set any timeout value, so that systemd will not kill postmaster
# during crash recovery.
TimeoutSec=0

[Install]
WantedBy=multi-user.target


Where i need configure the Oracle environment variables

**Comment by kirandba-hub** [comment]
Issue solved

**Comment by laurenz** [comment]
Great.

For the record: it would be a line in the `[Service]` section that looks like

```none
Environment=VARIABLENAME=value
```

It is best not to modify the original service file, as subsequent updates via the package manager will obliterate your changes. Create a plug-in or replacement service file in `/etc`.
