### ISSUE TITLE
Incorrect PGXN package for oracle_fdn 2.3.0

### ISSUE THREAD

**Issue by nboullis** [laurenz/oracle_fdw#428]
Hi,

The PGXN package for oracle_fdw 2.3.0 lacks the README.oracle_fdw file, referenced from the Makefile (while it exists as README.md):
    [https://api.pgxn.org/src/oracle_fdw/oracle_fdw-2.3.0/](https://api.pgxn.org/src/oracle_fdw/oracle_fdw-2.3.0/)

As far as I understand it, there was the same problem when oracle_fdw 2.2.0 was released (see issue #374).

Can you fix the PGXN release?

Cheers,

Nicolas

**Comment by laurenz** [comment]
Sorry about that. I have uploaded 2.3.1 to PGXN.
That is not really a new version, I just fixed the package.
