### ISSUE TITLE
Oracle timestamp(0) not imported

### ISSUE THREAD

**Issue by abiuan** [laurenz/oracle_fdw#43]
Mapping an oracle timestamp(0) field as timestamp(0) or date gives the following error:

> ERROR: invalid input syntax for type timestamp: "1977-06-09 18:00:00."

It seems that oracle answers appending a point, even if the field is defined *timestamp(0)*, and oracle_fdw is unable to handle that.

Follow the output of **oracle_diag()**:
> oracle_fdw 1.2.0, PostgreSQL 9.4.5, Oracle client 11.2.0.4.0, Oracle server 11.2.0.4.0

P.S.
Temporary I solved mapping the field as varchar.

**Comment by laurenz** [comment]
Yes, that's a bug. Will fix.

**Comment by laurenz** [comment]
I have committed a fix at 17c16074543992812ff55d7035904a3a5978183c
Could you check if that fixes the problem for you?

**Comment by abiuan** [comment]
It works fine.

Many thanks!

Alberto

**Comment by laurenz** [comment]
Thanks for the report!
