### ISSUE TITLE
Setting NLS parameters by default

### ISSUE THREAD

**Issue by AdrianoS22** [laurenz/oracle_fdw#430]
Hello, laurenz.

Before anything, thanks for your contribution to PG community with this module.

My issue is the following... (sorry my bad English)

I have a PG 12.3 64 bit instance (with admin privs) running on a CentoOS 7, and a FDW thats point to an Oracle EE 11g 64bit,  which I can run only SQL SELECTs (read only tables/views).

Output of SELECT oracle_diag();
"oracle_fdw 2.3.0devel, PostgreSQL 12.3, Oracle client 19.6.0.0.0, ORACLE_HOME=/usr/lib/oracle/19.6/client64".

Table lay-out on the Oracle side (running "describe ORASCHEMA.ORATABLE;" by SQL Plus):
	COLNUM1                          NUMBER(2)
	COLNUM2                          NUMBER(6)
	COLDATE1                          DATE
	COLDATE2                          DATE

On PG side:

	CREATE FOREIGN TABLE pgschema.pgtable(
		colnum1 smallint NULL,
		colnum2 integer NULL,
		coldate1 timestamp(0) without time zone NULL,
		coldate2 timestamp(0) without time zone  NULL
	)
		SERVER oraserver
		OPTIONS (schema 'ORASCHEMA', table 'ORATABLE');

The foreign table was created without erros, but when I try to run a query like:
	SELECT * FROM pgschema.pgtable;

I get the error:
	"ORA-01861: literal does not match format string"

On the PG side, when connected with Oracle client SQL*Plus (Version 19.6.0.0.0) and run the query on ORASCHEMA.ORATABLE, the error doesn't happen.

I run in the SQL*Plus client on the PG server: "SELECT * FROM NLS_SESSION_PARAMETERS;". The result is:

	PARAMETER                      VALUE
	------------------------------ ----------------------------------------
	NLS_LANGUAGE                   BRAZILIAN PORTUGUESE
	NLS_TERRITORY                  BRAZIL
	NLS_CURRENCY                   R$
	NLS_ISO_CURRENCY               BRAZIL
	NLS_NUMERIC_CHARACTERS         ,.
	NLS_CALENDAR                   GREGORIAN
	NLS_DATE_FORMAT                DD/MM/RR
	NLS_DATE_LANGUAGE              BRAZILIAN PORTUGUESE
	NLS_SORT                       WEST_EUROPEAN
	NLS_TIME_FORMAT                HH24:MI:SSXFF
	NLS_TIMESTAMP_FORMAT           DD/MM/RR HH24:MI:SSXFF
	NLS_TIME_TZ_FORMAT             HH24:MI:SSXFF TZR
	NLS_TIMESTAMP_TZ_FORMAT        DD/MM/RR HH24:MI:SSXFF TZR

When I run a query on a PG foreign table mapped to "SYS.NLS_SESSION_PARAMETERS" Oracle's view, I get the result (only diff rows listed):

			PARAMETER        |                VALUE
	-------------------------+-------------------------------------
	 NLS_NUMERIC_CHARACTERS  | .,
	 NLS_DATE_FORMAT         | YYYY-MM-DD HH24:MI:SS BC
	 NLS_DATE_LANGUAGE       | AMERICAN
	 NLS_TIMESTAMP_FORMAT    | YYYY-MM-DD HH24:MI:SS.FF9 BC
	 NLS_TIMESTAMP_TZ_FORMAT | YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC

Some settings from 'postgresql.conf' file:
	datestyle = 'iso, dmy'
	timezone = 'America/Sao_Paulo'
	lc_messages = 'pt_BR.utf8'
	lc_monetary = 'pt_BR.utf8'
	lc_numeric = 'pt_BR.utf8'
	lc_time = 'pt_BR.utf8'

PG (CentOS 7) server system env var:
LANG=pt_BR.utf8

I had a look on issue #402, and I ran "SELECT oracle_execute('oraserver', 'ALTER SESSION SET NLS_DATE_FORMAT = ''DD/MM/RR''');" to change the session of FDW connection, and than the query on pgschema.pgtable started to run without errors.

My question is: Is that the best solution? And if it is, there is a way to change the NLS settings in the FDW to values that I can choose by default?

Like I saw in another issues in this forum, and through the source code (file "oracle_utils.c", function "setOracleEnvironment"), the NLS settings is "hard coded", (NLS_DATE_LANGUAGE, NLS_DATE_FORMAT, etc).
I changed the code, disabling the NLS's settings, leaving only the NLS_LANG (already setted), rebuilded e reinstalled the FDW library, and restarded PG. That solved my problem too.

After disabling the NLS settings in the source code, I could set then by environment variables, like explained here: https://docs.oracle.com/cd/B28359_01/server.111/b28298/ch3globenv.htm#i1005949

I don't know if it has been tried, or even if it is a good suggestion, but what if the NLS parameters were configured in the code only if they were not configured by environment variables? I apologize if I am suggesting something that has already been tried, but if it was not, I can make changes and send a pull request ...

**Comment by laurenz** [comment]
Thanks for that well-researched report. I wish they all were like this!

Your analysis is helpful, but I don't think that your suggestion goes in the right direction.
The idea behind type conversion in oracle_fdw is to force all the Oracle `NLS_*_FORMAT` to a value so that PostgreSQL can interpret the string representation correctly, regardless of its settings.
For example, if the dates showed up in the format `DD/MM/RR`, PostgreSQL will understand them with the settings you have, but it would fail if `datestyle` were set differently. Moreover, that format makes you lose the time part of the Oracle `DATE`.

We must get to the bottom of why Oracle has a problem with

    NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS BC'

Could you try that in sqlplus:

    ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS BC';
    SELECT * FROM oraschema.oratable WHERE ???;

Try without `WHERE` clause first and verify that you get the same error.
If yes, try narrowing it down with a `WHERE` condition and try to identify a `DATE` value for which the format fails.
I'd be interested in knowing that value.

**Comment by AdrianoS22** [comment]
Ok, I got your point. Thanks for clarifying me.

In sqlplus, after I changed the session with "ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS BC'", any SELECT returns with "ORA-01861" error, with or without WHERE clause, either with "*" or cols names.

About the values in the oraschema.oratable, that's a small table with only 24 rows. The columns COLNUM1 and COLNUM2 have some random numbers, and the columns COLDATE1 and COLDATE2 have some random date values, as follow:

   COLNUM1    COLNUM2 COLDATE1 COLDATE2
---------- ---------- -------- --------
         2      55890 06/06/19 03/07/22
         3     289922 06/06/19 26/04/22
         4     252552 06/06/19 05/10/22
         5     295921 06/06/19 31/10/22
         6     226170 06/06/19 25/08/22
         7     284198 06/06/19 02/10/22
         8     285085 06/06/19 31/07/21
         9     288716 06/06/19 03/09/21
        10     267300 06/06/19 12/11/22
        11     265841 06/06/19 25/06/22
        17     308621 12/07/19 11/07/23
        18     255159 06/06/19 22/05/22
        19     260066 04/05/20 03/05/24
        21     294410 06/06/19 19/01/23
        22     113178 06/06/19 18/05/21
        23     213320 06/06/19 17/05/22
        26     289119 05/10/19 04/10/23
        28     304074 10/07/19 09/07/23
        29     289423 06/06/19 22/04/23
        34     293386 06/06/19 13/03/23
        36     298284 06/06/19 17/04/21
        37     309635 06/06/19 05/01/23
        38      71936 06/06/19 10/11/22
        39     299283 19/08/20 18/08/24

If you have some idea or advise, I will be very grateful.

**Comment by laurenz** [comment]
I still cannot reproduce it, but it is a good step in the right direction that you can reproduce it with Oracle means alone.
If all fails, that means you can ask Oracle for an explanation.

Could you try to use `ALTER SESSION` to set `NLS_DATE_LANGUAGE` to `AMERICAN` and see if that fixes the problem?

Basically, sice I cannot reproduce it, I'm asking you to come up with a combination of parameters that produces a result in the form

```none
2020-10-06 04:08:04 AD
```

so that it can be understood by PostgreSQL. Then I can adapt oracle_fdw's parameter settings so that things work for you.

**Comment by AdrianoS22** [comment]
Hi, Laurenz!

I did `ALTER SESSION SET NLS_DATE_LANGUAGE = 'AMERICAN'` in SQL Plus, and it also didn't solve the problem. I still get "ORA-01861" error when I ran any query.

Either in sqlplus or through oracle_fdw, the queries only run if I change the NLS_DATE_FORMAT session parameter value to the same of server, 'DD/MM/RR' in case.

I am trying an alternative approach, running a "`oracle_execute('oraserver', 'ALTER SESSION SET NLS_DATE_FORMAT = ''DD/MM/RR''')`" just after PG startup.

By now, thank you for your time.
God bless you!

**Comment by laurenz** [comment]
I am unhappy that we cannot find settings that make your case work.

Do you get the same error for

    SELECT to_char(current_date, 'YYYY-MM-DD HH24:MI:SS BC') FROM dual;

**Comment by AdrianoS22** [comment]
`SELECT to_char(current_date, 'YYYY-MM-DD HH24:MI:SS BC') as curr_date FROM dual;` runs fine in the SQL Plus:

	CURR_DATE
	------------------------
	2020-10-09 13:43:26 D.C.

I believe that there is some issue between server-client comunication, or some misconfiguration on date columns in the "oratable" (that is a view, in fact). 

For a test exemple, in sqlplus, if I change the session with `ALTER SESSION SET NLS_DATE_FORMAT='RR/MM/DD';` and then run `select current_date as curr_dt from dual`', I get the result:

	CURR_DT
	--------
	20/10/09

But if in the same session I run `select coldate1 from oraschema.oratable;`, I get: "ORA-01830: date format picture ends before converting entire input string"

SQLPlus describes that 'coldate1' is a date type column: 'DESC oraschema.oratable;':

	 Name                                      Null?    Type
	 ----------------------------------------- -------- ----------------------------
	 COLNUM1                                            NUMBER(2)
	 COLNUM2                                            NUMBER(6)
	 COLDATE1                                  NOT NULL DATE
	 COLDATE2                                           DATE


But what kind of 'date' is it, who knows!? (laughs)

To solve my problem, I made this work around solution (which in clear Brazilian Portuguese is called "gambiarra"): I created a view 'pgview' as follows:

	CREATE OR REPLACE VIEW pgschema.pgview AS
	SELECT * FROM pgschema.pgtable
	WHERE (
		SELECT count(*) from (SELECT oracle_execute('oraserver', 'ALTER SESSION SET NLS_DATE_FORMAT = ''DD/MM/RR''')) as T
	) > 0;
	
I know, I know, that's not "clever", but... It works! 

I believe that you were right. The problem was never in the Oracle FDW.

Feel yourself free to close this issue.

Thank you your appreciation again.

**Comment by laurenz** [comment]
Ah, it is a view. That is crucial information.
I bet the problem is in the view definition.
Could you show me the view definition?

**Comment by AdrianoS22** [comment]
```
CREATE VIEW ORASCHEMA.ORATABLE
AS SELECT 
	CAST(SUBSTR(BT2.COLNUM1, 1, 2) AS NUMBER(2)) AS COLNUM1,
    CAST(BT1.COLNUM2 AS NUMBER(6)) AS COLNUM2,
    BT1.DATINI AS COLDATE1,
    BT1.DATFIM AS COLDATE2
FROM ORASCHEMA2.BASETABLE1 BT1,
     ORASCHEMA2.BASETABLE2 BT2
WHERE ...
```

By the definition of `ORASCHEMA.ORATABLE` that I could access, I found nothing suspicious. I am trying to contact the `oraserver` administrator, to figure out the `ORASCHEMA2.BASETABLE1` definition.

**Comment by laurenz** [comment]
Can you post the complete view definition with the `WHERE` clause?
I'd also need the definitions of the underlying tables.

My suspicion is that there is a conversion from `VARCHAR2` to `DATE` in there somewhere which depends on the `NLS_DATE_FORMAT` setting, which is a bug in the view definition.

**Comment by AdrianoS22** [comment]
```
CREATE VIEW ORASCHEMA.ORATABLE
AS SELECT 
	CAST(SUBSTR(BT2.COLNUM1, 1, 2) AS NUMBER(2)) AS COLNUM1,
    CAST(BT1.COLNUM2 AS NUMBER(6)) AS COLNUM2,
    BT1.COLDATE1 AS COLDATE1,
    BT1.COLDATE2 AS COLDATE2
 FROM ORASCHEMA2.BASETABLE1 BT1,
     ORASCHEMA2.BASETABLE2 BT2
 WHERE BT1.COLX = BT2.COLX
...
  AND BT1.COLDATE1 <= SYSDATE
  AND (BT1.COLDATE2 >= SYSDATE OR BT1.COLDATE2 = '31/12/1900')
ORDER BY 2, 3
```

Some details I had to hide, some others I had to obfuscate, because it contains some business rules.

**Comment by laurenz** [comment]
There we have the problem.

    BT1.COLDATE2 = '31/12/1900'

will perform an implicit type cast from `VARCHAR2` to `DATE`, and that cast depends on the current setting of `NLS_DATE_FORMAT`.

So the proper solution is to fix the view to not depend on a setting that everybody can change in their session:

    BT1.COLDATE2 = to_date('31/12/1900', 'DD/MM/YYYY')

You'd have to do something similar in all other places in the view where such implicit type conversions to `DATE` happen.

Messing with oracle_fdw's settings is not the proper way to deal with that.

**Comment by AdrianoS22** [comment]
Got it!

I will contact the oracle's side admin and ask him to change the view's definition.

Thank you again!
