### ISSUE TITLE
 slowness to insert 

### ISSUE THREAD

**Issue by lucponelle** [laurenz/oracle_fdw#431]
Hi,
I tried to insert some data in Oracle table froma  postgres database 
I encount slowness insert

Here is the oracle_diag() result :
oracle_fdw 2.2.0, PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1), Oracle client 12.1.0.2.0, Oracle server 11.2.0.4.0

Here are the duration of my inserting tests : 
100 lines
INSERT canope_prod.e_vanne INTO {schema=REG_SUD,table=E_VANNE,prefetch=10000,max_long=50}
Insertion en 2.490s

1000 lignes
INSERT canope_prod.e_vanne INTO {schema=REG_SUD,table=E_VANNE,prefetch=10000,max_long=50}
Insertion en 21.350s

10000 lignes
INSERT canope_prod.e_vanne INTO {schema=REG_SUD,table=E_VANNE,prefetch=10000,max_long=50}
Insertion en 204.312s

20000 lignes
INSERT canope_prod.e_vanne INTO {schema=REG_SUD,table=E_VANNE,prefetch=10000,max_long=50}
After 4185s, the process is still running while data have been inserted in database Oracle since more 3600s

Have you some ideas about this behaviour ?
Is it a configuration problem ?

Thanks
Regards
Luc Ponelle

**Comment by laurenz** [comment]
I think that the slow bulk inserts you observe are caused by the way the FDW API is designed in PostgreSQL.

Basically, each row is treated separately and causes a round trip between PostgreSQL and the Oracle server.
I don't think there is a simple way to overcome that.

The documentation mentions that:

> While modifying foreign data works, the performance is not particularly  
> good, specifically when many rows are affected, because (owing to the way  
> foreign data wrappers work) each row has to be treated individually.

Sorry.
