### ISSUE TITLE
Loss of performance after upgrade from 2.2.0 to 2.3.0 ?

### ISSUE THREAD

**Issue by philflorent** [laurenz/oracle_fdw#434]
Hi,

We use oracle_fdw to migrate data of public hospitals from Oracle Databases to PostgreSQL.
I packaged latest version 2.3.0 to build the next version of our Debian-based distribution and I noticed a loss of performance in two tests after the upgrade. 
Using very old hardware a 1Gb table is loaded by CTAS from the foreign table after an "import foreign schema". Duration was about 5 minutes with 2.1 or 2.2.0, about 9 minutes with 2.3.0. Results are reproductible. 
Complete migration test now runs in 79 minutes, it was 52 minutes with 2.1 and 2.2. Difference is proportionnaly less important but the complete test includes operations that only run on target like index creations. Compiling with or without LLVM does not make any difference. 
I don't use any option (prefetch etc.), the only element that change in the various runs is oracle_fdw version. Did you notice such a difference in your tests ?

Best regards
Phil

Here is my test :

```
-- test vith 2.3.0

dddd=> select oracle_diag('oradb');
                                                  oracle_diag
---------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.3.0, PostgreSQL 11.9 (Debian 11.9-0+deb10u1), Oracle client 19.8.0.0.0, Oracle server 11.2.0.4.0
(1 ligne)

dddd=> IMPORT FOREIGN SCHEMA "XXXXX" FROM SERVER oradb INTO orcl;
IMPORT FOREIGN SCHEMA

dddd=> create table xx_xxx as select * from orcl.xx_xxx;
SELECT 2771791
Durée : 530816,690 ms (08:50,817)
dddd=> truncate table xx_xxx;
TRUNCATE TABLE

dddd=> insert into xx_xxx select * from orcl.xx_xxx;
INSERT 0 2771791
Durée : 527305,543 ms (08:47,306)
dddd=> truncate table xx_xxx;
TRUNCATE TABLE

dddd=> insert into xx_xxx select * from orcl.xx_xxx;
INSERT 0 2771791
Durée : 546937,484 ms (09:06,937)

dddd=> \d+
                      Liste des relations
 Schéma |  Nom   | Type  | Propriétaire | Taille | Description
--------+--------+-------+--------------+--------+-------------
 nnnn   | xx_xxx | table | nnnn         | 991 MB |
(1 ligne)

dddd=> drop table xx_xxx;
DROP TABLE

dddd=> commit;
COMMIT


-- root
apt reinstall ./postgresql-11-oracle-fdw-19.2.deb
...
dpkg: avertissement: dégradation (« downgrade ») de postgresql-11-oracle-fdw depuis 19.19 vers 19.2

-- same test after downgrade to 2.2

dddd=# drop extension oracle_fdw cascade;

dddd=# create extension oracle_fdw schema extensions;
CREATE EXTENSION

...

dddd=> select oracle_diag('oradb');
                                                  oracle_diag
---------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.2.0, PostgreSQL 11.9 (Debian 11.9-0+deb10u1), Oracle client 19.8.0.0.0, Oracle server 11.2.0.4.0
(1 ligne)

dddd=> IMPORT FOREIGN SCHEMA "XXXXX" FROM SERVER oradb INTO orcl;
IMPORT FOREIGN SCHEMA

dddd=> create table xx_xxx as select * from orcl.xx_xxx;
SELECT 2771791
Durée : 282446,589 ms (04:42,447)
dddd=> truncate table xx_xxx ;
TRUNCATE TABLE

dddd=> insert into xx_xxx select * from orcl.xx_xxx;
INSERT 0 2771791
Durée : 316711,142 ms (05:16,711)
dddd=> truncate table xx_xxx;
TRUNCATE TABLE

dddd=> insert into xx_xxx select * from orcl.xx_xxx;
INSERT 0 2771791
Durée : 296482,296 ms (04:56,482)

dddd=> \d+
                      Liste des relations
 Schéma |  Nom   | Type  | Propriétaire | Taille | Description
--------+--------+-------+--------------+--------+-------------
 nnnn   | xx_xxx | table | nnnn         | 991 MB |
(1 ligne)

dddd=> drop table xx_xxx;
DROP TABLE

dddd=> commit;
COMMIT

-- root -- reupgrade to 2.3
apt-get install --only-upgrade ./postgresql-11-oracle-fdw-19.19.deb
...
Dépaquetage de postgresql-11-oracle-fdw (19.19) sur (19.2) ...

pg_ctlcluster 11 pilotage_p restart

-- same test after reupgrade to 2.3

dddd=# drop extension oracle_fdw cascade;

dddd=# create extension oracle_fdw schema extensions;
CREATE EXTENSION

dddd=# select oracle_diag('oradb');
                                                  oracle_diag
---------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.3.0, PostgreSQL 11.9 (Debian 11.9-0+deb10u1), Oracle client 19.8.0.0.0, Oracle server 11.2.0.4.0
(1 ligne)

dddd=> IMPORT FOREIGN SCHEMA "XXXXX" FROM SERVER oradb INTO orcl;
IMPORT FOREIGN SCHEMA

dddd=> create table xx_xxx as select * from orcl.xx_xxx;
SELECT 2771791
Durée : 515891,581 ms (08:35,892)

dddd=> truncate table xx_xxx ;
TRUNCATE TABLE

dddd=> insert into xx_xxx select * from orcl.xx_xxx;
INSERT 0 2771791
Durée : 532858,582 ms (08:52,859)

dddd=> truncate table xx_xxx ;
TRUNCATE TABLE

dddd=> insert into xx_xxx select * from orcl.xx_xxx;
INSERT 0 2771791
Durée : 526876,635 ms (08:46,877)

dddd=> \d+
                      Liste des relations
 Schéma |  Nom   | Type  | Propriétaire | Taille | Description
--------+--------+-------+--------------+--------+-------------
 nnnn   | xx_xxx | table | nnnn         | 991 MB |
(1 ligne)

dddd=> drop table xx_xxx;
DROP TABLE

dddd=> commit;
COMMIT

-- root -- downgrade to 2.1

apt reinstall ./postgresql-11-oracle-fdw-19.0.deb
...
dpkg: avertissement: dégradation (« downgrade ») de postgresql-11-oracle-fdw depuis 19.19 vers 19.0

-- same test after downgrade to 2.1

dddd=# drop extension oracle_fdw cascade;

dddd=# create extension oracle_fdw schema extensions;
CREATE EXTENSION

dddd=> \d orcl.xx_xxx
                                         Table distante « orcl.xx_xxx »
       Colonne        |              Type              | Collationnement | NULL-able | Par défaut | Options FDW
----------------------+--------------------------------+-----------------+-----------+------------+--------------
 ccc_ccc              | character varying(12)          |                 | not null  |            | (key 'true')
...
 cccc_ccc_ccc_ccc     | character varying(1)           |                 |           |            |
Serveur : oradb
Options FDW : (schema 'XXXXX', "table" 'XX_XXX')

dddd=#  select oracle_diag('oradb');
                                                  oracle_diag
---------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.1.0, PostgreSQL 11.9 (Debian 11.9-0+deb10u1), Oracle client 19.8.0.0.0, Oracle server 11.2.0.4.0
(1 ligne)

dddd=> IMPORT FOREIGN SCHEMA "XXXXX" FROM SERVER oradb INTO orcl;
IMPORT FOREIGN SCHEMA

dddd=>  create table xx_xxx as select * from orcl.xx_xxx;
SELECT 2771791
Durée : 281328,324 ms (04:41,328)

dddd=> truncate table xx_xxx ;
TRUNCATE TABLE

dddd=> insert into xx_xxx select * from orcl.xx_xxx;
INSERT 0 2771791
Durée : 286855,877 ms (04:46,856)

dddd=> truncate table xx_xxx ;
TRUNCATE TABLE

dddd=> insert into xx_xxx select * from orcl.xx_xxx;
INSERT 0 2771791
Durée : 296835,433 ms (04:56,835)

dddd=> \d+
                      Liste des relations
 Schéma |  Nom   | Type  | Propriétaire | Taille | Description
--------+--------+-------+--------------+--------+-------------
 nnnn   | xx_xxx | table | nnnn         | 991 MB |
(1 ligne)

```

**Comment by laurenz** [comment]
Interesting. I just reviewed all the modifications between 2.2.0 and 2.3.0 and couldn't find anything to explain that.

Could you check if the foreign table definitions are the same in all cases? They should be.

I see two things that could be done to shed light on this problem:

- Install the debugging symbols for PostgreSQL and oracle_fdw.
  Then run `perf` while you perform both tests and see which functions take up the time.

- Run a `git bisect` on oracle_fdw to find out which commit is responsible for the problem.
  That is a lot of work, but would narrow down the problem considerably.

**Comment by philflorent** [comment]
Hi,

_Could you check if the foreign table definitions are the same in all cases? They should be._

I checked 2.2 and 2.3 (I won't use 2.1 anymore) 
The foreign table definitions are the same. 
They are the result of an "import foreign schema" in both cases : 188 columns, same order, names and types (character varying(NN) and timestamp(0)). 

I will use your suggestions to investigate and update the issue.

Best regards
Phil

**Comment by philflorent** [comment]
Hi,

I ran perf top in 2.2 and 2.3.
Typical OK profile is 
```
  13,72%  libclntsh.so.19.1          [.] ttccfpg
  12,04%  libclntsh.so.19.1          [.] ttcfour
   6,65%  libclntsh.so.19.1          [.] ttcaGetCol
   4,87%  libclntsh.so.19.1          [.] ttcfopr
   4,52%  oracle_fdw.so              [.] convertTuple
   3,55%  libclntsh.so.19.1          [.] kpccs2c
   2,92%  libclntsh.so.19.1          [.] __intel_ssse3_rep_memcpy
   2,55%  libclntshcore.so.19.1      [.] lxgcnvb
   2,36%  libclntshcore.so.19.1      [.] ldxdtsint
   1,87%  libclntshcore.so.19.1      [.] lxsCnvLongToNumStr
   1,79%  libclntsh.so.19.1          [.] kpccc2u
   1,56%  postgres                   [.] heap_fill_tuple
   1,22%  postgres                   [.] pg_verify_mbstr_len
   1,01%  postgres                   [.] SearchCatCache1
```

Typical KO profile is 
```
  6,49%  libclntshcore.so.19.1  [.] lxgcnvb
   6,40%  libclntsh.so.19.1      [.] ttccfpg
   5,67%  libclntsh.so.19.1      [.] ttcfour
   5,36%  libclntshcore.so.19.1  [.] ldxmfn
   3,70%  libclntshcore.so.19.1  [.] lxpcget
   3,65%  libclntsh.so.19.1      [.] ttcaGetCol
   3,57%  libclntsh.so.19.1      [.] __intel_ssse3_rep_memcpy
   3,51%  libclntshcore.so.19.1  [.] lxgu2t
   3,24%  libclntshcore.so.19.1  [.] ldxsnf
   2,56%  oracle_fdw.so          [.] convertTuple
   2,35%  libclntsh.so.19.1      [.] ttcfopr
   1,83%  libclntshcore.so.19.1  [.] ldxsti
   1,54%  libclntsh.so.19.1      [.] kpccs2c
   1,29%  libclntshcore.so.19.1  [.] lxptset
   1,26%  libclntshcore.so.19.1  [.] ldxdtsint
   1,18%  libclntshcore.so.19.1  [.] lxmfwdx
```

ldxmfn & lxgcnvb are typically used in Oracle nls and to_char functions.

First time I obtain the KO profile is with this commit :

77242d1fef780e3f1b77561c81542889a83fb334 is the first bad commit
commit 77242d1fef780e3f1b77561c81542889a83fb334
Author: Laurenz Albe <laurenz.albe@cybertec.at>
Date:   Fri Aug 14 11:17:02 2020 +0200

    Fix NCHAR and NVARCHAR2 handling

    By default, Oracle converts NCHAR and NVARCHAR2 columns
    (which are stored in a UNICODE encoding) to the database
    encoding before converting them to the client encoding.

    If the database encoding is not AL32UTF8 (which is the
    main use case for the now obsolete NCHAR and NVARCHAR2
    data types), converting to the database encoding will
    substitute characters that cannot be represented with
    "replacement characters", which results in data loss.

    Reported by "srakazmus", who also found that you need
    to use OCI_NCHAR_LITERAL_REPLACE_ON in OCIEnvCreate.

    Special thanks to Christian Ullrich, who suspected that
    OCI_ATTR_CHARSET_FORM needs to be set to SQLCS_NCHAR in
    the bind and define handles to make this work.

    Unfortunately the Oracle documentation is unclear and
    contradictory on this point, so we had to use trial and
    error.

    This closes #416.

Since I worked with the load profiles and not the complete durations notice I cannot be 100% sure loss of performance occurred with this commit. 

Best regards
Phil

**Comment by laurenz** [comment]
Great work.
That all fits together, because this commit affects how `NCHAR` and `NVARCHAR2` are handled, which matches your observed profile.

Could you remove `OCI_NCHAR_LITERAL_REPLACE_ON` from the `OCIEnvCreate` call and see if that is the problem? If not, then it is probably the `OCI_ATTR_CHARSET_FORM` on the define and bind handle.

Once we have found which of the two changes causes the performance regression, perhaps @srakazmus can test if `OCI_NCHAR_LITERAL_REPLACE_ON` is really needed to fix the bug he observed in #416.

If not, then perhaps we can find a solution that is both fast and correct. Otherwise, I am afraid that the performance regression is necessary to have oracle_fdw work correctly with national character set columns...

In the worst case, you can fork oracle_fdw and revert the patch in your copy; if you don't use national characters sets, you could live without that patch.

**Comment by philflorent** [comment]
Removing the OCI_NCHAR_LITERAL_REPLACE_ON : no effect 
Removing the OCI_ATTR_CHARSET_FORM blocks : perf top profile and DDL duration of 2.2.0

We don't use nchar / nvarchar columns and 2.2.0 is OK for our Oracle 11.2 =>Debian 10/PostgreSQL 11 migrations. 
2.3.0 is very interesting though. This version will allow developers to work with a unique source (oracle_execute function). They sometimes need to create/replace views in Oracle databases for performance reasons. Filters are pushed but an Oracle-side view can be useful in some cases. 
2.3.0 will be mandatory with Debian 11 anyway since it will include PostgreSQL 13. I will have to find a solution for the 21 version of our Debian iso.
Perhaps my PostgreSQL support will be able to help ? oracle_fdw is listed in the products they will have to support. First public tender failed cause only one company answered but I hope the second one will be successful.

**Comment by laurenz** [comment]
Thanks for the research.

Could you check if 5a3ce2da85cc722e44ca25028467fe6cd0133749 fixes your problem?

**Comment by philflorent** [comment]
Hi. Thanks a lot I confirm it fixes the problem : load profile and duration are good with a single table. I am running the complete test on the whole schema but there is no doubt it is OK.

**Comment by laurenz** [comment]
Thanks for the feedback, I will pull the patch into the master branch, which closes this issue.

Thanks again for the effort you invested in diagnosing and testing this!

**Comment by laurenz** [comment]
Other users also had problems with that feature, so I have added a server option `nchar` in commit 5fd556f60274c6c287104f0a2aa90b8075e663cb.
Unless that option is set, you get the old behavior from 2.2.0.
It shouldn't affect you, but I wanted to let you know.

**Comment by philflorent** [comment]
Hi,
Thank you, it's noticed. We use PostgreSQL for our DSS databases but oracle_fdw is not currenty used in daily production, only in the migration process.
It could change but it's currently under development and it's an option among others. I will use 2.4.0 in the development process and I will report issues, directly on github or via our Cybertec support.
Best regards,
Phil

________________________________
De : Laurenz Albe <notifications@github.com>
Envoyé : lundi 8 février 2021 16:00
À : laurenz/oracle_fdw <oracle_fdw@noreply.github.com>
Cc : philflorent <philflorent@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [laurenz/oracle_fdw] Loss of performance after upgrade from 2.2.0 to 2.3.0 ? (#434)


Other users also had problems with that feature, so I have added a server option nchar in commit 5fd556f<https://github.com/laurenz/oracle_fdw/commit/5fd556f60274c6c287104f0a2aa90b8075e663cb>.
Unless that option is set, you get the old behavior from 2.2.0.
It shouldn't affect you, but I wanted to let you know.
