### ISSUE TITLE
oracle fdw does not push down an uuid field

### ISSUE THREAD

**Issue by GaddipatiAsish** [laurenz/oracle_fdw#439]
Hi,

I have a 

Oracle Set up: (11g)
```
CREATE TABLE sample ( id RAW(16) DEFAULT sys_guid() NOT NULL ENABLE,
text VARCHAR2(75) NOT NULL ENABLE,
CONSTRAINT "PK_SAMPLE" PRIMARY KEY (id));
        
INSERT INTO sample (text) VALUES ('T1');
INSERT INTO sample (text) VALUES ('T2');
```

Postgres Set up: (v13.1)
```
CREATE foreign TABLE pg_sample (	
        id uuid NOT NULL, 
	text VARCHAR(75) NOT NULL) 
OPTIONS (schema 'RANDOM', table 'sample'); 
```
ORACLE_FDW : 2.3.0

So, When I query like below from postgres

`explain verbose select * from pg_sample vs where vs.id = 'b556ac0b-d4c8-35c8-e050-12ac020072df';`
I see the below as Oracle-query

`SELECT /*a2420a704def355a5cad7d948337e507*/ r1."id", r1."text" FROM "RANDOM"."sample" r1`

which means its not sending over the where clause to oracle in case of UUID's. So, when there are million records in such a table(oracle), search from PG is very slow. is there any thing can we do to improve this?

My observation is it is pulling all the data from the oracle table to postgres and executing the where clause on postgres side (which is not a good idea).

Thank you.

**Comment by laurenz** [comment]
Thanks for the initiative. So far, I didn't bother to support this, but it turns out to be simple.

Could you see if the latest development version does the trick for you?

**Comment by GaddipatiAsish** [comment]
Yes, it worked. Thank you so much for your quick response.
