### ISSUE TITLE
Question: is the newest compiled version exepected to run with postgres 9.5 beta

### ISSUE THREAD

**Issue by pbel78** [laurenz/oracle_fdw#44]
Hi. thank you for this nice project. I was able to get oracle_fdw running with a postgres 9.4 server. But on the same machine I doesn't work with 9.5. 

Is it possible that the code already supports 9.5 but the compiled version not?

I'm running postgres on windows.

**Comment by laurenz** [comment]
Yes, exactly. You'd have to checkout the latest code and build oracle_fdw yourself.

I plan a new release (with binaries) when a release candidate for PostgreSQL 9.5 is out.
