### ISSUE TITLE
Issue with importing Nested Table

### ISSUE THREAD

**Issue by Argha-2890** [laurenz/oracle_fdw#442]
Hi Team,

Env: 

```
Oracle_fdw Ver: 2.3
PostgreSQL Ver: 11
Oracle Ver:  12.1.0.2.0 

```
I am trying to import a table which has a nested table datatype, but getting the below error while querying.

ERROR:  column "header" of foreign table "pr" cannot be converted to or from Oracle data type

Oracle DDL:

```
CREATE TABLE "SCHEMA"."TBL" 
   (	 
	"HEADER" "SCHEMA"."HEADER_TAB"  DEFAULT "SCHEMA"."HEADER_TAB"()
);
	
create or replace TYPE "HEADER_T" as object (
    field varchar2(64),
    value varchar2(998)
);

create or replace TYPE "HEADER_TAB" as table of header_t;
```

PostgreSQL DDL:

```
CREATE FOREIGN TABLE gnats.tbl(
    header gnats.header_tab NULL
);

```

I have used the `IMPORT FOREIGN SCHEMA` option for this. Please suggest on how to map nested tables via oracle_fdw.

Please let me know in case any further information is required from my end.

**Comment by laurenz** [comment]
Sorry, oracle_fdw does not support nested tables.

You could work around that by defining your foreign table as

```
CREATE FOREIGN TABLE tbl (
   header_field varchar(64),
   header_value varchar(998)
) SERVER srvname
OPTIONS (table '(SELECT (tbl.header).field AS header_field, (tbl.header).value AS header_value) FROM tab)');
```

**Comment by Argha-2890** [comment]
@laurenz - Thank you for your response. Could you please elaborate on your solution.

In my Oracle environment the **TBL** table has got multiple fields out of which the **header** field is a  **HEADER_TAB** custom nested table datatype. 

I have tried the below implementing the below DDL, but getting the same error.

```
CREATE FOREIGN TABLE header_tab (
   header_tab_field varchar(64),
   header_tab_value varchar(998)
) SERVER gnatsdb
OPTIONS (table '(SELECT (header_tab.header_tab).field AS header_tab_field, (header_tab.header_tab).value AS header_tab_value FROM "HEADER_TAB")');

CREATE FOREIGN TABLE tbl(
    field1 bigint OPTIONS (key 'true') NOT NULL,
    header header_tab,
    field2 character varying(128) NULL COLLATE pg_catalog."default",
    field3 character varying(512) NULL COLLATE pg_catalog."default",
    field4 varying(32) NULL COLLATE pg_catalog."default"
   ---------,
   ---------)
SERVER gnatsdb
    OPTIONS (schema 'SCHEMA', table 'TBL');
```

**Comment by laurenz** [comment]
What I posted was already the foreign table definition, and it shouldn't cause an error. Essentially, it is using an Oracle query rather than a table as source for the data.

An alternative is to create a view in Oracle that presents the nested table columns as normal columns and youe that as the source of a foreign table.

**Comment by laurenz** [comment]
Have you been able to find a solution?
Can I close the issue?

**Comment by Argha-2890** [comment]
@laurenz - Apologies. I have followed your suggestion and testing is in progress. The ticket can be closed for now, in case we need any further help will raise a new incident. Thank you!!
