### ISSUE TITLE
Poor performance on CLOB column to JSON

### ISSUE THREAD

**Issue by jordiromera** [laurenz/oracle_fdw#444]
Hi,

First, thanks for this great project.

I am facing on performance issue on CLOB column. Indeed, with oracle_fdw, SQL request takes 3 times longer. My tests were done on a table with 230 records. A SELECT statement with a direct connection on Oracle takes 7 seconds while with oracle_fdw it takes 35 seconds.

Are there some settings or tips to improve performance on CLOB to JSON cast ?
I already check "prefetch" option, multiple versions on oracle_fdw and oracle client.

**Explain results**

Request on column ID (simple case, good performance) :

```
Foreign Scan on dflexnet.dtfxl2_pdt  (cost=10000.00..10010.00 rows=1 width=32) (actual time=29.219..29.784 rows=230 loops=1)
   Output: id
   Oracle query: SELECT /*bd4261a017a0f53719288890692b8830*/ r1."ID" FROM "FLXPMR"."DTFXL2_PDT" r1
   Oracle plan: SELECT STATEMENT
   Oracle plan:   TABLE ACCESS FULL DTFXL2_PDT
 Planning Time: 480.724 ms
 Execution Time: 29.904 ms
```

Request on column PROPERTIES which has CLOB type (poor performance) :

```
**Foreign Scan on dflexnet.dtfxl2_pdt  (cost=10000.00..10010.00 rows=1 width=32) (actual time=113.583..35181.414 rows=230 loops=1)
   Output: properties
   Oracle query: SELECT /*85a5c6d95789e88a79cb57956b45301e*/ r1."PROPERTIES" FROM "FLXPMR"."DTFXL2_PDT" r1
   Oracle plan: SELECT STATEMENT
   Oracle plan:   TABLE ACCESS FULL DTFXL2_PDT
 Planning Time: 437.723 ms
 Execution Time: 35181.731 ms**
```

**Versions**
```
SELECT oracle_diag();
oracle_fdw 2.4.0devel, PostgreSQL 11.9 (Debian 11.9-0+deb10u1), Oracle client 21.1.0.0.0
```
Also test on :
```
SELECT oracle_diag();
oracle_fdw 2.3.0, PostgreSQL 11.9 (Debian 11.9-0+deb10u1), Oracle client 12.2.0.1.0
```

**Oracle table**
```
CREATE TABLE "FLXPMR"."DTFXL2_PDT" 
   (	
        "ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100002071 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MACHINE" NVARCHAR2(40) NOT NULL ENABLE, 
	"PROPERTIES" CLOB, 
	"TRANSACTIONID" NUMBER(*,0), 
	"CREATIONUTCDATE" DATE NOT NULL ENABLE, 
	"TRANSFERFLAG" NUMBER(1,0) NOT NULL ENABLE, 
	"TRANSFERLOCALDATE" DATE, 
	"REFID" NUMBER(*,0), 
	"CONTENTTYPE" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLEXNET" 
 LOB ("PROPERTIES") STORE AS SECUREFILE (
  TABLESPACE "FLEXNET" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
```

**PostgreSQL table**
```
CREATE FOREIGN TABLE dflexnet.dtfxl2_pdt(
    id numeric OPTIONS (key 'true') NOT NULL,
    machine character varying(40) NOT NULL COLLATE pg_catalog."default",
    properties json NULL,
    transactionid numeric NULL,
    creationutcdate timestamp(0) without time zone NOT NULL,
    transferflag smallint NOT NULL,
    transferlocaldate timestamp(0) without time zone NULL,
    refid numeric NULL,
    contenttype character varying(20) NULL COLLATE pg_catalog."default"
)
    SERVER dflexnet
    OPTIONS (schema 'FLXPMR', table 'DTFXL2_PDT', prefetch '1000', sample_percent '20');
```

Thanks

**Comment by laurenz** [comment]
This is a known problem, see #68, #326 and #429.

This is a limitation of the prefetch functionality in the Oracle C API.
Aboiding that would require substantial rewriting.
I have added it to the TODO list.

There is nothing much you can do about that.

**Comment by jordiromera** [comment]
Thank you for the quick answer and sorry for the duplicate.

You say substantial rewriting... too bad.
If you give me some key points, I will give a try for a push request on this.

I try some dirty hack quickly but OCILobRead2() seems still weird to me

**Comment by laurenz** [comment]
The idea would be to do away with [prefetching][1] and instead call [`OCIStmtFetch2()`][2] [here][3] with `iters` set to a value greater than 1. But then you have to define array variables to receive the results. `oracleFetchNext` would have to become slightly more complicated, but the main problem is not forgetting any special cases like `MDSYS.DSO_GEOMETRY` columns and LOBs.

Not impossible, but not trivial. I certainly welcome any help in this area, since this is a shortcoming that has come up repeatedly.


 [1]: https://github.com/laurenz/oracle_fdw/blob/8d955e1e864bef7f36beae5453df9fbb2fe978d4/oracle_utils.c#L1438
 [2]: https://docs.oracle.com/en/database/oracle/oracle-database/18/lnoci/statement-functions.html#GUID-7C0AF073-7870-4866-BBC9-D2BF3D8E5CCE
 [3]: https://github.com/laurenz/oracle_fdw/blob/8d955e1e864bef7f36beae5453df9fbb2fe978d4/oracle_utils.c#L2152

**Comment by laurenz** [comment]
This has been improved with commit d679a73d02057fd674fc78fe5f25183e5c9a172b.
You are welcome to test if the current development version works better for you.
