### ISSUE TITLE
Ora2pg vs oracle_fdw

### ISSUE THREAD

**Issue by naveenjul29** [laurenz/oracle_fdw#445]
how oracle_fdw is different from ora2pg

**Comment by laurenz** [comment]
ora2pg is a Perl script for exporting data and metadata from Oracle and importing them into PostgreSQL.

oracle_fdw is a PostgreSQL extension that runs inside the database and allows you to access tables that really are in an Oracle database from PostgreSQL.

These tools don't have much in common, except that both deal with Oracle databases and can be used to move data from Oracle to PostgreSQL.
