### ISSUE TITLE
Oracle_fdw upgrade from 2.2 to 2.3 issue

### ISSUE THREAD

**Issue by threenotrump** [laurenz/oracle_fdw#446]
Hi Laurenz

While upgrading oracle_fdw to 2.3.0 I get the error "ERROR:  could not find function "oracle_execute" in file "/usr/pgsql-12/lib/oracle_fdw.so" when  executing ALTER EXTENSION oracle_fdw UPDATE;

OS : Centos 7

Postgres Version : 12.3

Oracle_fdw version : 2.2.0

Oracle Client version : 19.5.0

How Can I fix this error?

Best Regards

Burak Yurdakul

**Comment by laurenz** [comment]
I am on vacation until Jan 7, so sorry for delays.

The error means that you didn't install the new version of oracle_fdw, or you installed in another directory.
At any rate, `/usr/pgsql-12/lib/oracle_fdw.so` is not from version 2.3.0.

**Comment by Chunters** [comment]
@threenotrump try this manual. https://github.com/laurenz/oracle_fdw/issues/436#issuecomment-730298337

**Comment by threenotrump** [comment]
Hi Laurenz 

Thank you very much for great software and for response even you are on holiday.

Hi Chunters thank you for the pointers.

I did everything the same except I executed make command with root.

This time I could upgrade the extension.

Probably I made a typo last time.

Happy holidays everyone.

Best Regards

Burak Yurdakul
