### ISSUE TITLE
oracle_utils.c:22:10: fatal error: oci.h: No such file or directory

### ISSUE THREAD

**Issue by engineer4235** [laurenz/oracle_fdw#447]
Hi,
@laurenz  

I know #95 issue inclued solution but I applied #95 solution, there was no solution for me.

My operating sistem is oracle linux 8;
Red Hat Enterprise Linux release 8.3 (Ootpa)

and I export below parameter;

export ORACLE_HOME=/usr/lib/oracle/19.5/client64/lib/
export LD_LIBRARY_PATH=/usr/lib/oracle/19.5/client64/lib/

Also;
cd /tmp/oracle_fdw-master after that execute make command and I gave below error.

[root@192 oracle_fdw-master]# echo $ORACLE_HOME 
/usr/lib/oracle/19.5/client64/lib/
[root@192 oracle_fdw-master]# echo $LD_LIBRARY_PATH 
/usr/lib/oracle/19.5/client64/lib/
[root@192 oracle_fdw-master]# 
[root@192 oracle_fdw-master]# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I/usr/lib/oracle/19.5/client64/lib//sdk/include -I/usr/lib/oracle/19.5/client64/lib//oci/include -I/usr/lib/oracle/19.5/client64/lib//rdbms/public -I/usr/lib/oracle/19.5/client64/lib/ -I/usr/include/oracle/19.9/client -I/usr/include/oracle/19.9/client64 -I/usr/include/oracle/19.8/client -I/usr/include/oracle/19.8/client64 -I/usr/include/oracle/19.6/client -I/usr/include/oracle/19.6/client64 -I/usr/include/oracle/19.3/client -I/usr/include/oracle/19.3/client64 -I/usr/include/oracle/18.5/client -I/usr/include/oracle/18.5/client64 -I/usr/include/oracle/18.3/client -I/usr/include/oracle/18.3/client64 -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-12/include/server -I/usr/pgsql-12/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_utils.o oracle_utils.c
oracle_utils.c:22:10: fatal error: oci.h: No such file or directory
 #include <oci.h>
          ^~~~~~~
compilation terminated.
make: *** [<builtin>: oracle_utils.o] Error 1

Also;

I execute all command as root.

please help me..

Best Regards,
Engin.

**Comment by engineer4235** [comment]
hi Again,
I solved my problem, My workaround solution is;

Firstly I find oci.h file in my server;
find / -name oci.h

above command result is;
/usr/include/oracle/19.5/client64

After that create oci file directory my oracle home diractory;

cd /usr/lib/oracle/19.5/client64/lib/
mkdir oci

Fastly, I create link ;
ln -s /usr/include/oracle/19.5/client64 /usr/lib/oracle/19.5/client64/lib/oci/include

After that my problem solved.

NOTE:
I installed Oracle client with below command.

yum install https://download.oracle.com/otn_software/linux/instantclient/195000/oracle-instantclient19.5-basic-19.5.0.0.0-1.x86_64.rpm -y
yum install https://download.oracle.com/otn_software/linux/instantclient/195000/oracle-instantclient19.5-sqlplus-19.5.0.0.0-1.x86_64.rpm -y
yum install https://download.oracle.com/otn_software/linux/instantclient/195000/oracle-instantclient19.5-devel-19.5.0.0.0-1.x86_64.rpm -y

Probably Oracle linux was creating the oci.h file in "/usr/include/oracle/19.5/client64" directory(by default)

Best Regards
Engin.

**Comment by laurenz** [comment]
I am on vacations until Jan 7, so sorry for the lack of response.

I guess it would have worked out of the box if you had set

    export ORACLE_HOME=/usr/lib/oracle/19.5/client64
