### ISSUE TITLE
Option for Query

### ISSUE THREAD

**Issue by tsykes** [laurenz/oracle_fdw#45]
Wondering if it makes sense to add an option when creating a foreign table to base it off a query. The MySQL FDW can have 
... OPTIONS (table 'hr.employees');
or 
... OPTIONS (query 'SELECT * FROM overtime WHERE year = 2010;');

Is this a possibility for the Oracle FDW to do this as well?

**Comment by laurenz** [comment]
It could be done, but I think that it is not needed in most cases:
- You can define a foreign table on `OVERTIME` and have oracle_fdw push down the WHERE clause.
- If the WHERE clause cannot be pushed down from PostgreSQL or you don't want to give the user access to the whole table, you can define a view on the Oracle side.

**Comment by tsykes** [comment]
The specific use case in my head was a join plus filter and/or aggregation on the Oracle side. I haven't been able to test yet (still running some analyze statements) but I believe joining a couple Oracle tables will execute the join in Postgres requiring pulling the entire table to Postgres that didn't have the where clause. When the table is very big, this is causing a problem.  

I've got a query that returns in a couple minutes in Oracle, but I can't get it to return at all running from Postgres. 

So for example,

SELECT ....
FROM oratable a
     JOIN orahugetable b on a.id = b.aid
WHERE a.somecol = 'testval' 

In this case, does the orahugetable need to be returned to postgres in its entirety and then run through a Merge Join in postgres?

**Comment by laurenz** [comment]
You are right, a join of two Oracle foreign tables will cause all necessary rows from both tables to be pulled to PostgreSQL, which can easily lead to intolerably bad performance.

There are plans to improve this, though: in PostgreSQL 9.5 there is support for [custom scan](http://www.postgresql.org/docs/9.5/static/custom-scan.html) which can be used to push down joins in foreign data wrappers. An implementation for postgres_fdw is in the pipeline right now, and oracle_fdw might implement that too at some point.

How about an Oracle view, that would solve your problem, right?

**Comment by tsykes** [comment]
Thanks for the update. I will do this part in my ETL layer for now. Looking forward to pushing joins down in foreign data wrappers. That would be pretty magical. 

As for the Oracle view, technically that's pretty easy but organizationally not so much.

**Comment by cirix81** [comment]
Another use case for creating a query is when you doesn't have privileges to create a view in oracle.

**Comment by laurenz** [comment]
It is strange how often I hear from users who claim that they cannot create a view in Oracle.
I guess it must be a power struggle between the Oracle DBAs and the PostgreSQL developers.
I'd expect every company to have some kind of process to modify an Oracle schema...

**Comment by cirix81** [comment]
I'm working for a multinational, and all oracle server is centralized in general quarter. To modified or create a view, it's need to be justified, validated, tested and put in production. It's more easy to make the query in the fdw side. I really think it's a very nice enhancement for oracle_fdw.

**Comment by jgoux** [comment]
This feature would be very useful. :+1: 
I'm also in the case that I can't touch anything on the Oracle side as the databases aren't from my company, I can just read the data.
I'll need to make complex queries with a lot of joins (and comments hints) on big tables, so I'd prefer that Postgres doesn't import the whole world and let Oracle does the work.

Thank you for this awesome extension !
