### ISSUE TITLE
FOREIGN TABLES Performance Issues 

### ISSUE THREAD

**Issue by nraju-c** [laurenz/oracle_fdw#451]
I have created foreign tables which are having data size more than 200 Millions of records in Oracle.
While i am  using foreign tables in Postgresql, the queries are running forever.

Can you please advise how to improve the performance on foreign tables which are having huge data size in source.

Note: Source Oracle Database is running on Exadata.

**Comment by luss** [comment]
In my general FDW experience, this is a matter of understanding what
queries predicates "the WHERE clause" get pushed down from the Postgres
query the the query that runs on Oracle.  Then you must consider how many
rows are returned back to Postgres.   You will get comparable query
resi\ults to Oracle when a summary query is fully pushed down to oracle and
only a small result set is retuned back thru postgres.

I am, of course, interested to hear laurenz's expert thoughts specific to
his oracle_fdw.

--Luss

**Comment by laurenz** [comment]
That sounds like the query is performing a sequential scan on the Oracle table.

Denis' comment is correct; it depends on the query and its `WHERE` and join conditions what query will be sent to Oracle.

For a more detailed answer, I need to see the output of `EXPLAIN (VERBOSE) SELECT ...` and the table definitions in Oracle and PostgreSQL.

**Comment by nraju-c** [comment]
its a simple select statement & running forever.

select * from abc.ft_MASK_INFORMATION ; 

**output of EXPLAIN (VERBOSE) SELECT**

"Foreign Scan on abc.ft_MASK_INFORMATION  (cost=10000.00..20000.00 rows=1000 width=4576)"
"  Output: MASK_INFORMATION_id, agreement_number, agreement_term, name, cancel_date, completed_date, ckr, owner, interaction_activity, forecast_close_date, non_recurring_revenue, is_primary, contact_name, ocn, due_date, foc_date, entity_type, pon, priority, platform_id, probability, product_name, status, status_date, quote_package_id, subject, recurring_revenue, type, version, won_date, create_user, created_date, last_update_user, last_update_date, created_system_user, created_system_date, last_update_system_user, last_update_system_date, global_account_id, MASK_INFORMATION_number, agreement_sign_date, is_coordinated, is_expedited, is_adv_config, is_adv_config_user_maintained, provisioning_plan_name, submitted_date, provisioning_plan_type, customer_desired_due_date, psr_coordinator, cust_desired_due_date_is_req, coordinator, activity, origin_bus_system_id, parent_MASK_INFORMATION_id, MASK_INFORMATION_ref, ticket_number, admin_state_lkup_id, billing_account_no, object_state, is_support_ticket, supplement_type, is_fast_track, object_state_date, admin_state, admin_state_date, is_proof_of_concept, distribution_channel"
"  Oracle query: SELECT /*ee872d07d1ece9f78045ee5ac1e5f502*/ r1.""MASK_INFORMATION_ID"", r1.""AGREEMENT_NUMBER"", r1.""AGREEMENT_TERM"", r1.""NAME"", r1.""CANCEL_DATE"", r1.""COMPLETED_DATE"", r1.""CKR"", r1.""OWNER"", r1.""INTERACTION_ACTIVITY"", r1.""FORECAST_CLOSE_DATE"", r1.""NON_RECURRING_REVENUE"", r1.""IS_PRIMARY"", r1.""CONTACT_NAME"", r1.""OCN"", r1.""DUE_DATE"", r1.""FOC_DATE"", r1.""ENTITY_TYPE"", r1.""PON"", r1.""PRIORITY"", r1.""PLATFORM_ID"", r1.""PROBABILITY"", r1.""PRODUCT_NAME"", r1.""STATUS"", r1.""STATUS_DATE"", r1.""QUOTE_PACKAGE_ID"", r1.""SUBJECT"", r1.""RECURRING_REVENUE"", r1.""TYPE"", r1.""VERSION"", r1.""WON_DATE"", r1.""CREATE_USER"", r1.""CREATED_DATE"", r1.""LAST_UPDATE_USER"", r1.""LAST_UPDATE_DATE"", r1.""CREATED_SYSTEM_USER"", r1.""CREATED_SYSTEM_DATE"", r1.""LAST_UPDATE_SYSTEM_USER"", r1.""LAST_UPDATE_SYSTEM_DATE"", r1.""GLOBAL_ACCOUNT_ID"", r1.""MASK_INFORMATION_NUMBER"", r1.""AGREEMENT_SIGN_DATE"", r1.""IS_COORDINATED"", r1.""IS_EXPEDITED"", r1.""IS_ADV_CONFIG"", r1.""IS_ADV_CONFIG_USER_MAINTAINED"", r1.""PROVISIONING_PLAN_NAME"", r1.""SUBMITTED_DATE"", r1.""PROVISIONING_PLAN_TYPE"", r1.""CUSTOMER_DESIRED_DUE_DATE"", r1.""PSR_COORDINATOR"", r1.""CUST_DESIRED_DUE_DATE_IS_REQ"", r1.""COORDINATOR"", r1.""ACTIVITY"", r1.""ORIGIN_BUS_SYSTEM_ID"", r1.""PARENT_MASK_INFORMATION_ID"", r1.""MASK_INFORMATION_REF"", r1.""TICKET_NUMBER"", r1.""ADMIN_STATE_LKUP_ID"", r1.""BILLING_ACCOUNT_NO"", r1.""OBJECT_STATE"", r1.""IS_SUPPORT_TICKET"", r1.""SUPPLEMENT_TYPE"", r1.""IS_FAST_TRACK"", r1.""OBJECT_STATE_DATE"", r1.""ADMIN_STATE"", r1.""ADMIN_STATE_DATE"", r1.""IS_PROOF_OF_CONCEPT"", r1.""DISTRIBUTION_CHANNEL"" FROM ""MASK_INFORMATION"" r1"
"  Oracle plan: SELECT STATEMENT"
"  Oracle plan:   PARTITION LIST ALL"
"  Oracle plan:     TABLE ACCESS STORAGE FULL MASK_INFORMATION"

**Comment by laurenz** [comment]
There is the `prefetch` option on the foreign table that determines how many rows are fetched per client-server round trip. It defaults to 200, but you could experiment with different values.

Note that this prefetching does not work with `BLOB`, `CLOB` and `BFILE` columns. So if you have any columns of this type in your Oracle table, each row will require a client-server round trip, which definitely impacts performance.

Other than that, you could try installing `sqlplus` on the PostgreSQL server and running the query from there. If that takes just as long, the problem must be elsewhere, for example in a slow network connection.

**Comment by nraju-c** [comment]
can you please advise any best OPTIONS setup on foreign tables.

**Comment by nraju-c** [comment]
Getting below error for long running query.

**ERROR:  error fetching result: OCIStmtFetch2 failed to fetch next result row**
**DETAIL:  ORA-03135: connection lost contact**
Process ID: 172606
Session ID: 1010 Serial number: 24958
SQL state: HV00L

**Comment by luss** [comment]
I definitely agree that a great & necessary way to debug a long running fdw
query, that sometimes errors out, is to install sqlplus using the same
oracle client as what your oracle_fdw is configured to use.   Then you will
learn what's the best case for running that query for the Postgres server,
across whatever network your running across, to the oracle server.

Assuming you get the performance you want with the same sqlplus query
above, then you could consider to start tweaking oracle_fdw parms..
Your error above is a network timeout...   Are you running the query over
an unreliable network or one without enough bandwidth the retrieve all the
data to the client without timing out?

**Comment by nraju-c** [comment]
I am running on VPN from  pgAdmin tool.

**Comment by luss** [comment]
You are likely then running into network speed and reliability issues.

The instructions are pretty technical for trying to debug your problem.
 Sqlplus is oracle's command line sql tool that if you can run it from the
postgresql server box, will run the query over the same network as
oracle_fdw does.

**Comment by laurenz** [comment]
The best options to use for a foreign table are `TABLE` (because that is required) and maybe `SCHEMA` (if it is in a different schema). Use other options only if you need them.

As to your error, please describe what exactly you did to get it.
The error means that something closed the connection: either the Oracle server or the network (ill-configured firewall).
Look into the Oracle logs for a corresponding message. That will tell you if the server closed the connection or if it is as surprised as the client, and something in between terminated the connection.

oracle_fdw caches Oracle connections for the duration of the PostgreSQL database session, so it is possible that such connections stay open and idle for a long time. When activity is resumed, oracle_fdw checks if the connection is still alive and will automatically re-establish it if it got lost (commit c269639be5e7e3e126efcedfbb5d18cfd177f7af).
So this error is somewhat surprising. Could it be that you started a transaction and left it open for a long time?

**Comment by VieilleDame** [comment]
Hope it helps : we've been using oracle foreign data wrapper for quite a while, and it was very fast on big tables with CLOB, _until the previous last download_ (unzipped files from March 16th, 2020). Then we downloaded a newer one, and for one table (190 millions record with CLOBs, 80GB) we passed from **25 minutes to 2 hours** (!!!) 

After having checked OS, SAN, postgres versions, we finally switched back to the "previous" release, and it works fine again, on postgres 11.9 and 11.10, and on OEL 7 and OEL 8.

**Comment by laurenz** [comment]
@VieilleDame that may or may not be @nraju-c 's problem.
What you experience was probably #434, a performance regression introduced by a bugfix.
Do you still see the problem if you use the latest development version, which includes 73086bf1fc65b89821c82172a559ef05f26d9854?

**Comment by VieilleDame** [comment]
we tried with two later zip downloads, one with files of September 24th, and one with files of October 7th (which both seem to include 73086bf, as far as I understand). Those ones were both veeeery slow, taking 2 hours. The fast one (for us) is the one of March 16th

**Comment by laurenz** [comment]
@VieilleDame , you are perhaps experiencing something like #435, and you could open your own issue about that, since we never got to a conclusion there. But let's not discuss that in this issue, unless @nraju-c can confirm that he has that problem, and version 2.2.0 is fast.

**Comment by nraju-c** [comment]
Found the root cause & fixed on the same.

**Root Cause** : Joining more than 2 Foreign  tables in SQL's
**Solution**: Joins created while Foreign tables creation.
