### ISSUE TITLE
Support for Oracle 21.1 and 19.10

### ISSUE THREAD

**Issue by ivanlonel** [laurenz/oracle_fdw#455]
Any chance of these versions being supported in next release?

**Comment by laurenz** [comment]
They are already supported. Just set `ORACLE_HOME` to point to the right directory before building.

If you want the default installation paths in the `Makefile` so that you don't need to set `ORACLE_HOME`, please provide a patch. I have no license to run anything but Oracle XE.

**Comment by ivanlonel** [comment]
Oh, I didn't realize setting ORACLE_HOME was enough to avoid having to explicitly "support" each specific version. Please disregard this then.
Thanks!

**Comment by laurenz** [comment]
I still would add the paths to the `Makefile` if you tell me where the headers and libraries are located (ideally for the 64- and 32-bit builds).

**Comment by ivanlonel** [comment]
Sure!
I just created PR #456 that adds the paths to the makefile.
There don't seem to be 32-bit builds for these versions tho.
