### ISSUE TITLE
Odd performance issues.

### ISSUE THREAD

**Issue by alexitheodore** [laurenz/oracle_fdw#458]
I am experiencing performance issues which are easiest to demonstrate with the following examples:

If I execute this simple query directly on Oracle, it responds back in a normal time frame

(note: I am selecting "1" just to eliminate the data load from the columns as a concern)

`SELECT 1 FROM ORDERS`
> [2021-03-15 19:00:33] 500 rows retrieved starting from 1 in 1 s 137 ms (execution: 210 ms, fetching: 927 ms)

If I execute the same (in theory?) exact query from postgres through the oracle FDW, it also performs nominally:

`SELECT 1 FROM foreign_tables.orders`
> [2021-03-15 19:01:05] 500 rows retrieved starting from 1 in 641 ms (execution: 632 ms, fetching: 9 ms)

So far, this makes sense. But... if I do this:

(again directly on Oracle)
`SELECT 1 FROM ORDERS WHERE CLIENT = '336'`
> [2021-03-15 19:04:08] 500 rows retrieved starting from 1 in 1 s 108 ms (execution: 188 ms, fetching: 920 ms)

(and then remotely from Postgres)

`SELECT 1 FROM foreign_tables.orders WHERE client = '336'`

then the query times out after 15 minutes...

I have tried ANALYZE on the remote table (that times out too).

These are the foreign table options:

`options (table 'ORDERS', sample_percent '0.01', prefetch '100', readonly 'TRUE');`

and I've tried various different prefetch options from 100 to 10000.

Also:

> oracle_fdw 2.2.0, PostgreSQL 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1), Oracle client 19.3.0.0.0, Oracle server 11.2.0.4.0

**Comment by laurenz** [comment]
`ANALYZE` is definitely a good idea. Use a client that doesn't &ldquo;time out&rdquo;.

But to answer the rest of the question, I would like to see

1. The `CREATE TABLE` statement in Oracle.
2. The output of `EXPLAIN (VERBOSE) SELECT 1 FROM foreign_tables.orders WHERE client = '336'`.

**Comment by alexitheodore** [comment]
```
create foreign table orders
(
	columns...
)
server fds_oracle
options (table 'ORDERS', sample_percent '0.01', prefetch '100', readonly 'TRUE');

alter foreign table orders owner to postgres;

grant select on orders to dbbackup;

grant select, references on orders to sync_daemon;

grant insert, select, update, delete, truncate, references, trigger on orders to db_architect;
```

I removed the column names to protect the identity of my high profile client. Hopefully you don't really need that info, I think it should be arbitrary.

As for the explain, I have limited permissions and VERBOSE was not allowed - so this is the best I can get.

```
Foreign Scan on orders  (cost=10000.00..35330347430.00 rows=3533033743 width=4)
  Oracle query: SELECT /*a981096faf87d79c709d39a56210506c*/ r1."CLIENT" FROM "ORDERS" r1 WHERE (r1."CLIENT" = '336')
```

All that being said... something has somehow changed in the mean time. The query above works identically on Oracle as on Postgres. I believe that maybe the ANALYZE completed even though the client timed out.

BUT... just to make things more confusing. If I add another WHERE constraint, we're back to the same problem again: a query that performs instantly on Oracle will hang on Postgres.

I am not sure whether this is anything to do with oracle_fdw. If you think it is not, then we can close the issue.

**Comment by laurenz** [comment]
You will need to request the permissions to get the Oracle query plan.
Otherwise, how can we know what access path Oracle chooses?
If you run that same query directly with sqlplus, does it use the index?

"Something changed" - what is the effect? Is the query faster now?

I recommend that you get the Oracle DBAs involved. If they don't give you the permissions, tell them to do their job and figure the problem out themselves.

**Comment by alexitheodore** [comment]
I have been working within the limitations that are given to me. If I had more options, I would take them. I agree, more permissions and leverage on the Oracle side would certainly help. 

> If you run that same query directly with sqlplus, does it use the index?

I agree, but I've spent way too long trying to get sqlplus to work on Ubuntu and I cannot get past:

```
Error 6 initializing SQL*Plus
SP2-0667: Message file sp1<lang>.msb not found
SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory
```

> "Something changed" - what is the effect? Is the query faster now?
"The query above (now) works identically on Oracle as on Postgres. I believe that maybe the ANALYZE completed even though the client timed out."

I understand that this is equally out of your arms length to make heads or tails of. If you think it is unrelated to oracle_fdw, you're welcome to close the issue.

**Comment by laurenz** [comment]
I don't know if it is related to oracle_fdw or not, because we don't have the required information.

But the generated Oracle query looks extremely simple, and I cannot see how Oracle would not be able to use an index there.
Perhaps there was something wrong with the table statistics in Oracle? I have no way to tell.

I'll close the ticket, because it looks like we won't get to the bottom of that with the information we have.
