### ISSUE TITLE
compilation problem 

### ISSUE THREAD

**Issue by kid1968** [laurenz/oracle_fdw#459]
I try to compile oracle_fdw at oracle linux 7, Oracle 19 and postgres 13 and got
bash-4.2$ make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I/home/oracle/inst_19/sdk/include -I/home/oracle/inst_19/oci/include -I/home/oracle/inst_19/rdbms/public -I/home/oracle/inst_19 -I/usr/include/oracle/19.8/client -I/usr/include/oracle/19.8/client64 -I/usr/include/oracle/19.6/client -I/usr/include/oracle/19.6/client64 -I/usr/include/oracle/19.3/client -I/usr/include/oracle/19.3/client64 -I/usr/include/oracle/18.5/client -I/usr/include/oracle/18.5/client64 -I/usr/include/oracle/18.3/client -I/usr/include/oracle/18.3/client64 -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_fdw.o oracle_fdw.c
oracle_fdw.c:11:33: schwerwiegender Fehler: access/htup_details.h: Datei oder Verzeichnis nicht gefunden
My environment:
bash-4.2$ echo $PATH
/home/oracle/inst_19/bin:/usr/sbin:/usr/local/bin:/home/oracle/inst_19/bin:/usr/sbin:/usr/local/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/pgsql-13/bin
bash-4.2$ echo $LD_LIBRARY_PATH
/home/oracle/inst_19/lib:/lib:/usr/lib
 What I do wrong?

**Comment by laurenz** [comment]
Follow the documentation:

> You will need PostgreSQL headers and PGXS installed (if your PostgreSQL was
> installed with packages, install the development package).
