### ISSUE TITLE
Can't convert CHAR(1 BYTE) column from oracle to postgresql

### ISSUE THREAD

**Issue by dszczyt** [laurenz/oracle_fdw#46]
I have a field in a table declared in Oracle like this :
```
"COF_FLAG_REFERENCEUR" CHAR(1 BYTE)
```

I tried to create a foreign table with :
```
elg_mod_ou_art "char"
```

I tried various typings, the only one working is character varying(19), but it is displayed as... timestamp !?

**Comment by laurenz** [comment]
I am quite certain that the columns in your PostgreSQL foreign table do not correspond to the columns in the Oracle table.

oracle_fdw matches columns by position, not by name, so the n-th column of the Oracle table will correspond to the n-th column of the PostgreSQL foreign table.

It sounds like your PostgreSQL `char(1)` column coresponds to an Oracle `TIMESTAMP` column.

**Comment by dszczyt** [comment]
OK you're right, I had bad column ordering. Thank you for your answer.
