### ISSUE TITLE
modifying create foreign table (..) statement leads to  

### ISSUE THREAD

**Issue by elsbiet** [laurenz/oracle_fdw#460]
unsure if this is a postgres, oracle or oracle_fdw_problem.

i created a foreign table using the statement

create foreign table t2 (
    name                varchar,
    id                      varchar
) server SERVER_NAME options (schema 'MAPPING', table 'UPPERCASE_TABLE_NAME);

this worked fine. i then dropped the table using

drop foreign table t2;

and modified the create statement:

create foreign table t2 (
    name                    varchar,
    emp_group           numeric,   -- oracle datatype = number
    id                           varchar
) server SERVER_NAME options (schema 'MAPPING', 'UPPERCASE_TABLE_NAME');

the create statement was processed fine but when i try to select from t2:

select emp_group from t2;

i get

ERROR:  column "emp_group" of foreign table "t2" cannot be converted to or from Oracle data type.

i restarted the postgres server, recreated user mapping and foreign data wrapper and recreated the extension oracle_fdw but these actions did not fix my issue.

SELECT oracle_diag();

outputs

                                                       oracle_diag                                                   --------------------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.4.0devel, PostgreSQL 11.10 (Debian 11.10-0+deb10u1), Oracle client 11.2.0.2.0, ORACLE_HOME=/opt/oracle/11R2

what did i miss?

thanks for your reply.

**Comment by laurenz** [comment]
This is the same as #210, #290 and #361.

Different from other foreign data wrappers, oracle_fdw maps the PostgreSQL columns to the Oracle columns *not* by name, but by position. So the second Oracle column is mapped to the second PostgreSQL column, regardless of the name. This has largely historical reasons.

**Comment by elsbiet** [comment]
thanks for your answer.
