### ISSUE TITLE
Compilation problem: RedOS 7.2, PostgresPro13, Oracle 21 client

### ISSUE THREAD

**Issue by plotn** [laurenz/oracle_fdw#461]
Hi! I am compiled oracle_fdw in such environment (as written above) and got following problem:
static declaration follows non-static declaration 

Then I modified those line (oracle_fdw.c, 354):
static Expr *find_em_expr_for_rel(EquivalenceClass *ec, RelOptInfo *rel);
to
Expr *find_em_expr_for_rel(EquivalenceClass *ec, RelOptInfo *rel);

And it seems to work normally (tested with 'select * from dual')

Is it okay or did I do something wrong?

**Comment by plotn** [comment]
nb: and I slightly modified makefile - added oracle 21 (64 bit) paths

**Comment by laurenz** [comment]
I noticed that `find_em_expr_for_rel` is exported from v13 on, so I changed the code to use the PostgreSQL version.

Since you are not using regular PostgreSQL, I am not sure if that fixes your problem. Could you test?

What are the paths for Oracle instant client 21?

**Comment by plotn** [comment]
I compared optimizer/paths.h from PGPro and PG, they are almost the same.
Okay, I will test, I have another one server.
You can see the path from makefile added

**Comment by laurenz** [comment]
Thanks for testing.
About the `Makefile`, it looks as if you were using and old version.
The `Makefile` from the current development version already has that path, see commit cd39b3c54eb91691e56b1ccbcd28a04006e01b17.

I guess we can close this issue, right?

**Comment by plotn** [comment]
sure!
