### ISSUE TITLE
ORA-01858: a non-numeric character was found where a numeric was expected

### ISSUE THREAD

**Issue by jkhasanov** [laurenz/oracle_fdw#462]
Hi Laurenz, While trying to migrate the Oracle timestamp in PostgreSQL timestamp I got the following error:

ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-01858: a non-numeric character was found where a numeric was expected

dsdb=# SELECT oracle_diag('ora_server')

 oracle_fdw 2.3.0, PostgreSQL 13.1, Oracle client 21.1.0.0.0, Oracle server 12.2.0.1.0
(1 row)

ds_db=# SELECT oracle_diag();

 oracle_fdw 2.3.0, PostgreSQL 13.1, Oracle client 21.1.0.0.0, ORACLE_HOME=/usr/lib/oracle/21/client64/lib
(1 row)

Please note that I tried also to_char with different formats, cast(timestamp as date), to_char, and then to_date. None of this doesn't work. Below some examples

CREATE FOREIGN TABLE integration.t_dg_merchant_javid (
    terminal_id character varying(16),
    access_device_subtype_cd character varying(100),
    agreem_access_device_start_dt timestamp,
    agreem_access_device_end_dt timestamp,
    agreement_current_status_cd character varying(50),
    address_line_2_txt character varying(1000),
    customer_no character varying(50)
)
SERVER ora_server
OPTIONS ( table '( SELECT TERMINAL_ID,
          ACCESS_DEVICE_SUBTYPE_CD,
          AGREEM_ACCESS_DEVICE_START_DT,
          AGREEM_ACCESS_DEVICE_END_DT,
          AGREEMENT_CURRENT_STATUS_CD,
          ADDRESS_LINE_2_TXT,
          CUSTOMER_NO
     FROM dwh.v_terminal)'
);

dsdb=# select * from t_dg_merchant_javid;
ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-01858: a non-numeric character was found where a numeric was expected

CREATE FOREIGN TABLE integration.t_dg_merchant_javid (
    terminal_id character varying(16),
    access_device_subtype_cd character varying(100),
    agreem_access_device_start_dt character varying(100),
    agreem_access_device_end_dt character varying(100),
    agreement_current_status_cd character varying(50),
    address_line_2_txt character varying(1000),
    customer_no character varying(50)
)
SERVER ora_server
OPTIONS ( table '( SELECT TERMINAL_ID,
          ACCESS_DEVICE_SUBTYPE_CD,
          to_char(AGREEM_ACCESS_DEVICE_START_DT,''dd/mm/yyyy''),
          to_char(AGREEM_ACCESS_DEVICE_END_DT,''dd/mm/yyyy''),
          AGREEMENT_CURRENT_STATUS_CD,
          ADDRESS_LINE_2_TXT,
          CUSTOMER_NO
     FROM dwh.v_terminal)'
);

dsdb=# select * from t_dg_merchant_javid;
ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-01858: a non-numeric character was found where a numeric was expected

CREATE FOREIGN TABLE integration.t_dg_merchant_javid (
    terminal_id character varying(16),
    access_device_subtype_cd character varying(100),
    agreem_access_device_start_dt date,
    agreem_access_device_end_dt date,
    agreement_current_status_cd character varying(50),
    address_line_2_txt character varying(1000),
    customer_no character varying(50)
)
SERVER ora_server
OPTIONS ( table '( SELECT TERMINAL_ID,
          ACCESS_DEVICE_SUBTYPE_CD,
          cast(AGREEM_ACCESS_DEVICE_START_DT as date),
          cast(AGREEM_ACCESS_DEVICE_END_DT as date),
          AGREEMENT_CURRENT_STATUS_CD,
          ADDRESS_LINE_2_TXT,
          CUSTOMER_NO
     FROM dwh.v_terminal)'
);

dsdb=# select * from t_dg_merchant_javid;
ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-01858: a non-numeric character was found where a numeric was expected

Thanks in advance.

**Comment by laurenz** [comment]
Please find the problematic value.

You can narrow it down with queries like

    SELECT * FROM foreigntab WHERE pkey BETWEEN 1 AND 100000;

Repeat queries like that until you find a single primary key where the conversion fails.

Then query the Oracle database for the problematic value.

I would also like to know the Oracle database character set and the PostgreSQL server encoding.

**Comment by jkhasanov** [comment]
Dear Laurenz, thanks for your quick response. I found the reason for problem.

The object v_terminal was a view at oracle side, not a table. There was implicit datatype conversion inside this view.

       AND TRUNC (ss.DEVICE_STATUS_DTTM) >
                                 12-aug-2019'

I replaced it with        

AND TRUNC (ss.DEVICE_STATUS_DTTM) >
                                 to_date('12/aug/2019','dd/mm/yyyy')

and problem solved.
