### ISSUE TITLE
limit clause push-down

### ISSUE THREAD

**Issue by iliasaz** [laurenz/oracle_fdw#463]
Hi,
First of all, great library - thank you!

Question: is there a way to push down the "limit" clause to Oracle? For example, when I issue this statement in Postgres, 
select * from table limit 10;

... the query I see in Oracle is "select col1, col2, ... from (select * from table) r1". On large tables, this leads to a problem because Oracle doesn't apply a stop count optimization. It would be nice to convert PGS's "limit" into Oracle's "fetch first N rows only" (12c+).
Thanks!

**Comment by laurenz** [comment]
See my comments to Gilles' pull request #464.

For the query you quote, would applying a stop count really make a difference?
Oracle operates with cursors, and PostgreSQL simply stops fetching rows from the result set when the `LIMIT` is reached.

For more complicated queries, you have a point, since the Oracle optimizer has a chance to pick a different plan if it knows that only a few rows will be fetched.

**Comment by laurenz** [comment]
Thanks to Gilles Darold who did most of the work on this!

**Comment by iliasaz** [comment]
Hi,
I've been testing this recently, and I noticed that whenever I have ORDER BY and LIMIT in my SQL, ORDER BY is not pushed down while LIMIT is pushed down.
Postgres query: select <columns> from <table> order by col1, col2, col3 limit 10
This results in Oracle query: select <columns> from <table> fetch first 10 rows only

So Oracle applies stop count optimization before it has a chance to sort the rows. This results in Postgres applying a sort on a random dataset. Could you kindly look into it, please?

Thank you!

**Comment by darold** [comment]
Please instead of adding comment to a closed pull request open a new issue. Also in the issue you will create post the data type of the columns in the order clause, I guess there is at least one non numeric column.

**Comment by laurenz** [comment]
Looking at the code, I think that I forgot this case.
I will investigate.

**Comment by darold** [comment]
@laurenz why not always pushing down the order by clause when there is no local condition even if there is string data type?

**Comment by darold** [comment]
I mean that maybe what the user want in this case is to retrieve ordered data from Oracle just like Oracle will do not like PG will do?

**Comment by laurenz** [comment]
@darold We cannot push down `ORDER BY` conditions that use operators, functions or data types that cannot be translated to Oracle.
I also will reject all attempts to push down a condition that behaves differently in Oracle and so causes different resulty depending on whether they are executed locally or not.
The way forward here is to *not* push down `LIMIT` if there is an `ORDER BY` that is not entirely pushed down.

**Comment by darold** [comment]
Ok, I understand, if you want I can fix to not the push down of LIMIT when there is an ORDER BY clause.

**Comment by laurenz** [comment]
That would be very welcome; thanks for the offer!

**Comment by laurenz** [comment]
To be more exact: only avoid pushing down `LIMIT` if there is an `ORDER BY` clause *that it not pushed down*.

**Comment by darold** [comment]
yes of course.

**Comment by laurenz** [comment]
Thanks for the report - that was an embarrassing oversight.
Thanks again to @darold for the help.

**Comment by iliasaz** [comment]
Thanks for the quick fix!
