### ISSUE TITLE
libclntsh.so.19.1 : No such file, during "Create extension oracle_fdw"

### ISSUE THREAD

**Issue by tuturgit** [laurenz/oracle_fdw#466]
Hello, 

I try to install the oracle_fdw extension on a Redhat 8.3 server with PostgresSQL 10.15.

The compilation with MAKE and MAKE INSTALL work propely, but after when i try to create the extension i have the error:

```
# CREATE EXTENSION oracle_fdw;
ERROR:  could not load library "/usr/lib64/pgsql/oracle_fdw.so": libclntsh.so.19.1: cannot open shared object file: No such file or directory
```
The client is an oracle 19.3 client  and the path of ORACLE_HOME and LD_LIBRABRY_PATH are set is postgresql service (with drop-in function)

Moreover i try to add a ldconfig file with the path of LD_LIBRARY_PATH but no change.

Do you have an idea please ?

Regards,

**Comment by laurenz** [comment]
In which directory is the Oracle client installed?
Are you using Instant Client or some other distribution?

You must have made a mistake setting `LD_LIBRARY_PATH`.
You can verify that with

    cat /proc/1104/environ | xargs -0 -n 1 echo

where you have to replace 1104 with your postmaster's PID.

Please tell me exactly what you did, what files you changed, how you restarted PostgreSQL and so on, then we should be able to identify the problem.

**Comment by laurenz** [comment]
That looks ok.

Is there a library `libclntsh.so.19.1` in `/u01/app/ora19client/product/19.0.0/client/lib`?
If yes, what do you get if you run

```bash
ldd /u01/app/ora19client/product/19.0.0/client/lib/libclntsh.so.19.1
```

Did you check that all executables and libraries involved are 64-bit?

**Comment by tuturgit** [comment]
Thank, 
Yes there is a library `libclntsh.so.19.1` in `/u01/app/ora19client/product/19.0.0/client/lib `

```
 ldd /u01/app/ora19client/product/19.0.0/client/lib/libclntsh.so.19.1
        linux-vdso.so.1 (0x00007ffdd1781000)
        libnnz19.so => /u01/app/ora19client/product/19.0.0/client/lib/libnnz19.so (0x00007fafc268e000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fafc248a000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fafc2108000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fafc1ee8000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007fafc1ccf000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fafc1ac7000)
        libaio.so.1 => /lib64/libaio.so.1 (0x00007fafc18c4000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fafc16ad000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fafc12ea000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fafc6dd7000)
        libclntshcore.so.19.1 => /u01/app/ora19client/product/19.0.0/client/lib/libclntshcore.so.19.1 (0x00007fafc0d4a000)
```
The library is in 64bits :

```
objdump -f /u01/app/ora19client/product/19.0.0/client/lib/libclntsh.so.19.1 | grep ^architecture
architecture: i386:x86-64, flags 0x00000150:
```

Oracle client was installed from the zipfile `LINUX.X64_193000_client.zip` available on [https://www.oracle.com/fr/database/technologies/oracle19c-linux-downloads.html](url)

**Comment by laurenz** [comment]
Mysterious. Everything looks right.

My last idea is to attach `strace` to the backend and monitor the system calls that occur while you get the error.
That might give us a clue about what is wrong.

**Comment by laurenz** [comment]
Anything new?

**Comment by tuturgit** [comment]
Hi Laurenz,

I fully uninstall the oracle client and reinstall properly, 

And so no error after, 

Thank's for you help,
