### ISSUE TITLE
too much time in retrieve data

### ISSUE THREAD

**Issue by fernandorb10** [laurenz/oracle_fdw#467]
Hi, 

I have a very expensive query, which performs a join on three tables, the execution time in oracle is fast, because the session is active for a few seconds, but the time to retrieve the data and display it in postgres is very long. 

Attached is the execution plan. I greatly appreciate the help,

```
GroupAggregate  (cost=93593.03..93593.12 rows=1 width=1252) (actual time=3665237.262..3665390.736 rows=44398 loops=1)
   Group Key: g.fecha_extraccion, g.contract_id, g.guid, g.node_id, g.user_id, g.rule_id, g.state, g.substate, g.estado_anterior, g.created, g.modificacion, g.fecha_fin, g.synchronous, g.email_address, g.bad_email, g.telephone, g.bad_ph
one, g.sign_methods, g.last_sign_method, g.velocidad
   Buffers: shared hit=15, temp read=1012014 written=1012014
   CTE general
     ->  HashAggregate  (cost=73590.00..73590.05 rows=1 width=2248) (actual time=1912241.688..1912360.698 rows=44398 loops=1)
           Group Key: to_char(n.created, 'YYYY-MM-DD'::text), n.contract_id, n.lang, n.guid, n.node_id, s.user_id, s.rule_id, n.address_preferred, n.procsyn_id, n.state, n.result, to_char(n.created, 'yyyy-mm-dd hh24:mi:ss'::text), to_ch
ar(n.modified, 'yyyy-mm-dd hh24:mi:ss'::text), to_char(n.result_date, 'yyyy-mm-dd hh24:mi:ss'::text), n.external_id, n.billing_info, n.synchronous, n.billing_size, s.sms_sent, (s.result_date - s.substate_date), u.email, u.telephone, s.s
ign_methods, s.last_sign_method, n.created, n.result_date
           Buffers: temp read=1012014 written=1012014
           ->  Hash Left Join  (cost=50025.00..62652.50 rows=125000 width=2572) (actual time=1862664.463..1912115.106 rows=44398 loops=1)
                 Hash Cond: (n.node_id = s.node_id)
                 Buffers: temp read=1012014 written=1012014
                 ->  Hash Left Join  (cost=30012.50..40190.00 rows=5000 width=1180) (actual time=851028.678..880324.657 rows=41479 loops=1)
                       Hash Cond: (n.contract_id = c.contract_id)
                       ->  Foreign Scan on pt_nodes n  (cost=10000.00..20000.00 rows=1000 width=1180) (actual time=851014.313..880241.163 rows=41479 loops=1)
                             Filter: ((date(created) >= to_date('01042021'::text, 'DDMMYYY'::text)) AND (date(created) < to_date('03042021'::text, 'DDMMYYYY'::text)))
                             Rows Removed by Filter: 45691557
                             Oracle query: SELECT /*f533c1b064a0d18811dbc0ae89b0fa84*/ r1."NODE_ID", r1."GUID", r1."CONTRACT_ID", r1."LANG", r1."STATE", r1."CREATED", r1."MODIFIED", r1."SYNCHRONOUS", r1."BILLING_INFO", r1."RESULT", r1."
ADDRESS_PREFERRED", r1."EXTERNAL_ID", r1."RESULT_DATE", r1."PROCSYN_ID", r1."BILLING_SIZE" FROM "LOGALTYTECA"."PT_NODES" r1 WHERE (r1."ADDRESS_PREFERRED" IN ('WEB', 'SMS'))
                       ->  Hash  (cost=20000.00..20000.00 rows=1000 width=32) (actual time=14.270..14.271 rows=1494 loops=1)
                             Buckets: 2048 (originally 1024)  Batches: 1 (originally 1)  Memory Usage: 72kB
                             ->  Foreign Scan on pt_contracts c  (cost=10000.00..20000.00 rows=1000 width=32) (actual time=4.477..13.056 rows=1494 loops=1)
                                   Oracle query: SELECT /*75e298c458d8d55e16f926f8ae89092a*/ r4."CONTRACT_ID" FROM "LOGALTYTECA"."PT_CONTRACTS" r4
                 ->  Hash  (cost=20000.00..20000.00 rows=1000 width=1296) (actual time=1011632.079..1011632.079 rows=53404219 loops=1)
                       Buckets: 4194304 (originally 1024)  Batches: 16 (originally 1)  Memory Usage: 485117kB
                       Buffers: temp written=775679
                       ->  Foreign Scan  (cost=10000.00..20000.00 rows=1000 width=1296) (actual time=107222.391..938466.500 rows=53404230 loops=1)
                             Oracle query: SELECT /*6623f51c7e1f9859105d9fcd0e33fbda*/ r2."USER_ID", r2."RULE_ID", r2."STATE", r2."RESULT", r2."SUBSTATE", r2."RESULT_DATE", r2."LAST_ACCESS_DATE", r2."SIGN_METHODS", r2."LAST_SIGN_METHOD"
, r2."SMS_SENT", r2."SUBSTATE_DATE", r2."NODE_ID", r6."EMAIL", r6."TELEPHONE" FROM ("LOGALTYTECA"."PT_SIGNATURES" r2 LEFT JOIN "LOGALTYTECA"."PT_USERS" r6 ON (r2."USER_ID" = r6."USER_ID"))
   ->  Sort  (cost=20002.98..20002.99 rows=1 width=1124) (actual time=3665237.216..3665264.128 rows=44398 loops=1)
         Sort Key: g.fecha_extraccion, g.contract_id, g.guid, g.node_id, g.user_id, g.rule_id, g.state, g.substate, g.estado_anterior, g.created, g.modificacion, g.fecha_fin, g.synchronous, g.email_address, g.bad_email, g.telephone, g.b
ad_phone, g.sign_methods, g.last_sign_method, g.velocidad
         Sort Method: quicksort  Memory: 15868kB
         Buffers: shared hit=15, temp read=1012014 written=1012014
         ->  Nested Loop Left Join  (cost=20002.90..20002.97 rows=1 width=1124) (actual time=2059634.982..3664724.375 rows=44398 loops=1)
               Join Filter: (((g.guid)::text = (fir.guid)::text) AND (g.user_id = fir.user_id))
               Rows Removed by Join Filter: 599401873
               Buffers: temp read=1012014 written=1012014
               ->  CTE Scan on general g  (cost=0.00..0.02 rows=1 width=1060) (actual time=1912241.699..1912438.790 rows=44398 loops=1)
                     Buffers: temp read=1012014 written=1012014
               ->  GroupAggregate  (cost=20002.90..20002.93 rows=1 width=214) (actual time=3.323..32.193 rows=13501 loops=44398)
                     Group Key: fir.guid, fir.user_id
                     ->  Sort  (cost=20002.90..20002.90 rows=1 width=166) (actual time=3.320..9.894 rows=13622 loops=44398)
                           Sort Key: fir.guid, fir.user_id
                           Sort Method: quicksort  Memory: 3139kB
                           ->  Subquery Scan on fir  (cost=20002.77..20002.89 rows=1 width=166) (actual time=147276.612..147328.482 rows=16855 loops=1)
                                 ->  GroupAggregate  (cost=20002.77..20002.88 rows=1 width=288) (actual time=147276.609..147312.191 rows=16855 loops=1)
                                       Group Key: pt_billing.channel, pt_billing.ntype, pt_billing.guid, pt_billing.user_id
                                       ->  Sort  (cost=20002.77..20002.78 rows=5 width=272) (actual time=147276.577..147285.476 rows=18259 loops=1)
                                             Sort Key: pt_billing.channel, pt_billing.ntype, pt_billing.guid, pt_billing.user_id
                                             Sort Method: quicksort  Memory: 2210kB
                                             ->  Hash Semi Join  (cost=10000.03..20002.71 rows=5 width=272) (actual time=137557.189..147213.043 rows=18259 loops=1)
                                                   Hash Cond: ((pt_billing.guid)::text = (general.guid)::text)
                                                   ->  Foreign Scan on pt_billing  (cost=10000.00..20000.00 rows=1000 width=272) (actual time=17.395..135218.875 rows=13996658 loops=1)
                                                         Oracle query: SELECT /*1ce46b0733dd8612d159cf954ea43784*/ r1."GUID", r1."USER_ID", r1."NTYPE", r1."CHANNEL" FROM "LOGALTYTECA"."PT_BILLING" r1 WHERE (r1."NTYPE" IN (2, 8))
                                                   ->  Hash  (cost=0.02..0.02 rows=1 width=118) (actual time=261.033..261.033 rows=44398 loops=1)
                                                         Buckets: 65536 (originally 1024)  Batches: 1 (originally 1)  Memory Usage: 3287kB
                                                         ->  CTE Scan on general  (cost=0.00..0.02 rows=1 width=118) (actual time=0.002..229.262 rows=44398 loops=1)
 Planning Time: 140.356 ms
 Execution Time: 3665424.279 ms
(55 row)
```

**Comment by fernandorb10** [comment]
I also wanted to know if there is a best practice document for oracle_fdw, about configuration parameters (postgresql.conf).

**Comment by laurenz** [comment]
You obviously never analyzed the foreign tables, since the query is using the default estimates. In PostgreSQL, run

```
ANALYZE foreign_table;
```

for all foreign tables involved.

You might also benefit from having more conditions pushed down into the foreign scan. For that, don't cast `created` to `date`, but compare it directly to a literal of the appropriate data type.

**Comment by fernandorb10** [comment]
New plan with analyze tables: 

 GroupAggregate  (cost=690053701.24..690070566.62 rows=25266 width=1252) (actual time=1996550.482..1996674.900 rows=44398 loops=1)
   Group Key: g.fecha_extraccion, g.contract_id, g.guid, g.node_id, g.user_id, g.rule_id, g.state, g.substate, g.estado_anterior, g.created, g.modificacion, g.fecha_fin, g.synchronous, g.email_address, g.bad_email, g.telephone, g.bad_pho
ne, g.sign_methods, g.last_sign_method, g.velocidad
   Buffers: shared hit=26
   CTE general
     ->  GroupAggregate  (cost=536802712.09..536838085.19 rows=252665 width=544) (actual time=1853330.522..1853520.175 rows=44398 loops=1)
           Group Key: (to_char(n.created, 'YYYY-MM-DD'::text)), n.contract_id, n.lang, n.guid, n.node_id, s.user_id, s.rule_id, n.address_preferred, n.procsyn_id, n.state, n.result, (to_char(n.created, 'yyyy-mm-dd hh24:mi:ss'::text)), (t
o_char(n.modified, 'yyyy-mm-dd hh24:mi:ss'::text)), (to_char(n.result_date, 'yyyy-mm-dd hh24:mi:ss'::text)), n.external_id, n.billing_info, n.synchronous, n.billing_size, s.sms_sent, ((s.result_date - s.substate_date)), u.email, u.teleph
one, s.sign_methods, s.last_sign_method, n.created, n.result_date
           Buffers: shared hit=11
           ->  Sort  (cost=536802712.09..536803343.75 rows=252665 width=354) (actual time=1853330.415..1853357.582 rows=44398 loops=1)
                 Sort Key: (to_char(n.created, 'YYYY-MM-DD'::text)), n.contract_id, n.lang, n.guid, n.node_id, s.user_id, s.rule_id, n.address_preferred, n.procsyn_id, n.state, n.result, (to_char(n.created, 'yyyy-mm-dd hh24:mi:ss'::text)
), (to_char(n.modified, 'yyyy-mm-dd hh24:mi:ss'::text)), (to_char(n.result_date, 'yyyy-mm-dd hh24:mi:ss'::text)), n.external_id, n.billing_info, n.synchronous, n.billing_size, s.sms_sent, ((s.result_date - s.substate_date)), u.email, u.t
elephone, s.sign_methods, s.last_sign_method, n.created, n.result_date
                 Sort Method: quicksort  Memory: 24423kB
                 Buffers: shared hit=11
                 ->  Hash Right Join  (cost=2455579.98..536780039.37 rows=252665 width=354) (actual time=993983.257..1852858.947 rows=44398 loops=1)
                       Hash Cond: (s.node_id = n.node_id)
                       ->  Foreign Scan  (cost=10000.00..534128480.00 rows=53411848 width=103) (actual time=87500.480..899496.473 rows=53428929 loops=1)
                             Oracle query: SELECT /*6623f51c7e1f9859105d9fcd0e33fbda*/ r2."USER_ID", r2."RULE_ID", r2."STATE", r2."RESULT", r2."SUBSTATE", r2."RESULT_DATE", r2."LAST_ACCESS_DATE", r2."SIGN_METHODS", r2."LAST_SIGN_METHOD",
 r2."SMS_SENT", r2."SUBSTATE_DATE", r2."NODE_ID", r6."EMAIL", r6."TELEPHONE" FROM ("LOGALTYTECA"."PT_SIGNATURES" r2 LEFT JOIN "LOGALTYTECA"."PT_USERS" r6 ON (r2."USER_ID" = r6."USER_ID"))
                       ->  Hash  (cost=2442574.60..2442574.60 rows=240430 width=129) (actual time=903453.994..903453.995 rows=41479 loops=1)
                             Buckets: 262144  Batches: 1  Memory Usage: 8966kB
                             ->  Hash Left Join  (cost=34968.69..2442574.60 rows=240430 width=129) (actual time=870718.559..903386.566 rows=41479 loops=1)
                                   Hash Cond: (n.contract_id = c.contract_id)
                                   ->  Foreign Scan on pt_nodes n  (cost=10000.00..2414300.00 rows=240430 width=129) (actual time=870701.479..903295.943 rows=41479 loops=1)
                                         Filter: ((date(created) >= to_date('01042021'::text, 'DDMMYYY'::text)) AND (date(created) < to_date('03042021'::text, 'DDMMYYYY'::text)))
                                         Rows Removed by Filter: 45713074
                                         Oracle query: SELECT /*f533c1b064a0d18811dbc0ae89b0fa84*/ r1."NODE_ID", r1."GUID", r1."CONTRACT_ID", r1."LANG", r1."STATE", r1."CREATED", r1."MODIFIED", r1."SYNCHRONOUS", r1."BILLING_INFO", r1."RE
SULT", r1."ADDRESS_PREFERRED", r1."EXTERNAL_ID", r1."RESULT_DATE", r1."PROCSYN_ID", r1."BILLING_SIZE" FROM "LOGALTYTECA"."PT_NODES" r1 WHERE (r1."ADDRESS_PREFERRED" IN ('WEB', 'SMS'))
                                   ->  Hash  (cost=24950.00..24950.00 rows=1495 width=6) (actual time=16.980..16.981 rows=1495 loops=1)
                                         Buckets: 2048  Batches: 1  Memory Usage: 72kB
                                         ->  Foreign Scan on pt_contracts c  (cost=10000.00..24950.00 rows=1495 width=6) (actual time=8.151..16.034 rows=1495 loops=1)
                                               Oracle query: SELECT /*75e298c458d8d55e16f926f8ae89092a*/ r4."CONTRACT_ID" FROM "LOGALTYTECA"."PT_CONTRACTS" r4
   ->  Sort  (cost=153215616.05..153216247.71 rows=252665 width=1124) (actual time=1996550.397..1996571.471 rows=44398 loops=1)
         Sort Key: g.fecha_extraccion, g.contract_id, g.guid, g.node_id, g.user_id, g.rule_id, g.state, g.substate, g.estado_anterior, g.created, g.modificacion, g.fecha_fin, g.synchronous, g.email_address, g.bad_email, g.telephone, g.ba
d_phone, g.sign_methods, g.last_sign_method, g.velocidad
         Sort Method: quicksort  Memory: 15868kB
         Buffers: shared hit=26
         ->  Hash Left Join  (cost=153186563.46..153192943.32 rows=252665 width=1124) (actual time=1996221.478..1996323.417 rows=44398 loops=1)
               Hash Cond: (((g.guid)::text = (fir.guid)::text) AND (g.user_id = fir.user_id))
               Buffers: shared hit=11
               ->  CTE Scan on general g  (cost=0.00..5053.30 rows=252665 width=1060) (actual time=1853330.535..1853367.600 rows=44398 loops=1)
                     Buffers: shared hit=11
               ->  Hash  (cost=153185963.46..153185963.46 rows=40000 width=101) (actual time=142890.498..142890.499 rows=16709 loops=1)
                     Buckets: 65536  Batches: 1  Memory Usage: 1802kB
                     ->  GroupAggregate  (cost=153113978.21..153185563.46 rows=40000 width=101) (actual time=142843.673..142876.397 rows=16709 loops=1)
                           Group Key: fir.guid, fir.user_id
                           ->  Sort  (cost=153113978.21..153128175.26 rows=5678820 width=53) (actual time=142843.614..142851.494 rows=16855 loops=1)
                                 Sort Key: fir.guid, fir.user_id
                                 Sort Method: quicksort  Memory: 3139kB
                                 ->  Subquery Scan on fir  (cost=152188555.80..152476895.25 rows=5678820 width=53) (actual time=142772.086..142822.130 rows=16855 loops=1)
                                       ->  GroupAggregate  (cost=152188555.80..152420107.05 rows=5678820 width=62) (actual time=142772.080..142806.619 rows=16855 loops=1)
                                             Group Key: pt_billing.channel, pt_billing.ntype, pt_billing.guid, pt_billing.user_id
                                             ->  Sort  (cost=152188555.80..152207437.50 rows=7552680 width=46) (actual time=142772.009..142781.968 rows=18259 loops=1)
                                                   Sort Key: pt_billing.channel, pt_billing.ntype, pt_billing.guid, pt_billing.user_id
                                                   Sort Method: quicksort  Memory: 2210kB
                                                   ->  Hash Join  (cost=15689.46..151192954.59 rows=7552680 width=46) (actual time=134040.607..142691.958 rows=18259 loops=1)
                                                         Hash Cond: ((pt_billing.guid)::text = (general.guid)::text)
                                                         ->  Foreign Scan on pt_billing  (cost=10000.00..151063590.00 rows=15105359 width=46) (actual time=40.188..129832.301 rows=14004352 loops=1)
                                                               Oracle query: SELECT /*1ce46b0733dd8612d159cf954ea43784*/ r1."GUID", r1."USER_ID", r1."NTYPE", r1."CHANNEL" FROM "LOGALTYTECA"."PT_BILLING" r1 WHERE (r1."NTYPE" IN (2, 8))
                                                         ->  Hash  (cost=5686.96..5686.96 rows=200 width=118) (actual time=396.167..396.168 rows=41479 loops=1)
                                                               Buckets: 65536 (originally 1024)  Batches: 1 (originally 1)  Memory Usage: 3105kB
                                                               ->  HashAggregate  (cost=5684.96..5686.96 rows=200 width=118) (actual time=338.063..367.975 rows=41479 loops=1)
                                                                     Group Key: (general.guid)::text
                                                                     ->  CTE Scan on general  (cost=0.00..5053.30 rows=252665 width=118) (actual time=0.013..293.492 rows=44398 loops=1)
 Planning Time: 202.808 ms
 JIT:
   Functions: 56
   Options: Inlining true, Optimization true, Expressions true, Deforming true
   Timing: Generation 12.599 ms, Inlining 99.523 ms, Optimization 905.159 ms, Emission 649.549 ms, Total 1666.830 ms
 Execution Time: 1996732.964 ms
(64 row)

**Comment by laurenz** [comment]
You have two expensive foreign scans there:

```
->  Foreign Scan  (cost=10000.00..534128480.00 rows=53411848 width=103) (actual time=87500.480..899496.473 rows=53428929 loops=1)
      Oracle query: SELECT /*6623f51c7e1f9859105d9fcd0e33fbda*/ r2."USER_ID", r2."RULE_ID", r2."STATE", r2."RESULT", r2."SUBSTATE", r2."RESULT_DATE", r2."LAST_ACCESS_DATE", r2."SIGN_METHODS", r2."LAST_SIGN_METHOD", r2."SMS_SENT", r2."SUBSTATE_DATE", r2."NODE_ID", r6."EMAIL", r6."TELEPHONE"
                    FROM ("LOGALTYTECA"."PT_SIGNATURES" r2
                       LEFT JOIN "LOGALTYTECA"."PT_USERS" r6 ON (r2."USER_ID" = r6."USER_ID"))
```

and

```
->  Foreign Scan on pt_nodes n  (cost=10000.00..2414300.00 rows=240430 width=129) (actual time=870701.479..903295.943 rows=41479 loops=1)
      Filter: ((date(created) >= to_date('01042021'::text, 'DDMMYYY'::text)) AND (date(created) < to_date('03042021'::text, 'DDMMYYYY'::text)))
      Rows Removed by Filter: 45713074
      Oracle query: SELECT /*f533c1b064a0d18811dbc0ae89b0fa84*/ r1."NODE_ID", r1."GUID", r1."CONTRACT_ID", r1."LANG", r1."STATE", r1."CREATED", r1."MODIFIED", r1."SYNCHRONOUS", r1."BILLING_INFO", r1."RESULT", r1."ADDRESS_PREFERRED", r1."EXTERNAL_ID", r1."RESULT_DATE", r1."PROCSYN_ID", r1."BILLING_SIZE"
                    FROM "LOGALTYTECA"."PT_NODES" r1
                    WHERE (r1."ADDRESS_PREFERRED" IN ('WEB', 'SMS'))
```

With the first query, there is not much you can do. It just reads a lot of rows (53 million).
Part of the problem may be that while oracle_fdw can push down joins (as exemplified in the second foreign scan), it cannot push down three-way joins. So if you join three foreign tables in your query, one of the joins will have to happen on the PostgreSQL side. That may cause way more data to be read from Oracle than when the join would be executed remotely.

This is a limitation of the code, and there is no better advice I can give you than not joining more than two foreign tables.

With the second foreign scan you would win a lot if you rewrote the `WHERE` conditions that are now executed in the filter so that they can be pushed down to Oracle. The way it is now, oracle_fdw reads 45 million rows, only to filter out most of them.

Improving the second foreign scan should reduce query execution time substantially.

**Comment by fernandorb10** [comment]
We have indeed created a view and the time has been reduced by a total of 13 seconds. AMAZING.

Thank you very much, you can close the post.
