### ISSUE TITLE
oracle_fdw in EDB.

### ISSUE THREAD

**Issue by somendra123** [laurenz/oracle_fdw#469]
Hi,
is this oracle_fdw setup is compatible with EDB Postgres having Postgres version 10?

**Comment by laurenz** [comment]
I cannot say, since I don't have their source code.
You can try and build oracle_fdw against EDB's fork and see if it works for you, but I cannot give any guarantees.
Perhaps you should ask EDB.

**Comment by Tharun1353** [comment]
Hi,
I am also facing the same issue which somendra has requested.
we have installed the postgres-10 and edb_version-12 on ubuntu-18.04
![Image 12](https://user-images.githubusercontent.com/59623954/121314503-092f4d80-c925-11eb-9a2b-7509e6eba4c3.png)
after exporting the following variables also we are getting this error

env variables:
---------------
export PATH=$PATH:$HOME/bin:/usr/lib/oracle/11.2/client64:/usr/lib/oracle/11.2/client64/bin:/usr/lib/edb-as/12:/usr/lib/edb-as/12/bin
export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib
export ORACLE_HOME=/usr/include/oracle/11.2/client64

Error:
postgres=# create extension oracle_fdw;
ERROR:  could not access file "$libdir/oracle_fdw": No such file or directory

**Comment by laurenz** [comment]
@Tharun1353, are you sure that is the same problem?
I don't understand the screenshot you posted, and the error looks like you didn't install oracle_fdw.

**Comment by Tharun1353** [comment]
![Image 2](https://user-images.githubusercontent.com/59623954/121566516-38d07980-ca3b-11eb-9721-1bee7d9f0eee.png)
[Downloading and installing ORACLE_FDW on ubuntu.docx](https://github.com/laurenz/oracle_fdw/files/6633153/Downloading.and.installing.ORACLE_FDW.on.ubuntu.docx)

I followed this document and i installed everything which there is in the document,but i am unable to create the Oracle_fdw.

**Comment by Tharun1353** [comment]
existing Oracle_fdw in the following link https://pgxn.org/dist/oracle_fdw/   is not working can you please confirm existing oracle_fdw is compactable with  edb-13 and lower versions.
If so please tell me the process how to configure.

**Comment by laurenz** [comment]
@somendra123, is that your problem?

@Tharun1353, your problem has nothing to do with EDB support, you just didn't configure the Oracle client right.
`libaio.so` is a dependency of the Oracle client library <code>libclntsh.so.*x*.*y*</code>, and you have to install it.
I don't have Ubuntu Linux at my fingertips, but it should be

```bash
sudo apt-get install libaio1
```

**Comment by Tharun1353** [comment]
Hi laurenz,

Thanks for your support,now the issue got resolved.

Thanks,
Tharun
![Image 7](https://user-images.githubusercontent.com/59623954/121645292-a7501e80-cab1-11eb-890c-d1aa375b6231.png)

**Comment by laurenz** [comment]
Great. So there remain two questions from my perspective:

1. @somendra123, does that fix your problem?
2. Does oracle_fdw work with EDB's fork? Just being able to install the extension is not enough.

**Comment by somendra123** [comment]
Hi Laurenz,

1. Yes, I & @Tharun1353 was working on the same issue. 
2.  For now we have only successfully installed oracle_fdw. We will update you once we will check the full-fledged functionality of oracle_fdw with EDB.
3. Yes, oracle_fdw compatible with EDB 13 on ubuntu OS.

**Comment by laurenz** [comment]
Thanks for the feedback. Shall I close the issue?
