### ISSUE TITLE
IMPORT FOREIGN SCHEMA imports nothing but does not fail

### ISSUE THREAD

**Issue by aus** [laurenz/oracle_fdw#47]
Hello.

I am trying to use the `IMPORT FOREIGN SCHEMA` feature, but I am having trouble. 

```
postgres=# SELECT oracle_diag();
                                               oracle_diag
---------------------------------------------------------------------------------------------------------
 oracle_fdw 1.3.0, PostgreSQL 9.5.0, Oracle client 12.1.0.2.0, ORACLE_HOME=/usr/lib/oracle/12.1/client64
```

I have my `CREATE SERVER` defined and I can successfully query data from my Oracle DB when my foreign table is manually setup with:

```
postgres=# create server oracle foreign data wrapper oracle_fdw options (dbserver '//hostname/test');
CREATE SERVER
postgres=# create user mapping for postgres server oracle options (user 'AUS', password 'xxxx');
CREATE USER MAPPING
postgres=# create foreign table MY_TABLE ( c_number varchar(15) not null, status varchar(60), requested_by varchar(100) ) server oracle options (schema 'AUS', table 'MY_TABLE');
CREATE FOREIGN TABLE
postgres=# select count(*) from MY_TABLE;
 count
-------
     3
(1 row)
```

Following the example and documentation, I attempt to import the foreign schema:

```
postgres=# drop foreign table MY_TABLE;
DROP FOREIGN TABLE
postgres=# create schema aus;
CREATE SCHEMA
postgres=# IMPORT FOREIGN SCHEMA "AUS" FROM SERVER oracle INTO aus OPTIONS(case 'lower');
DEBUG:  StartTransactionCommand
DEBUG:  StartTransaction
DEBUG:  name: unnamed; blockState:       DEFAULT; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children:
DEBUG:  ProcessUtility
DEBUG:  oracle_fdw: import schema "AUS" from foreign server "oracle"
DEBUG:  oracle_fdw: set NLS_LANG=AMERICAN_AMERICA.AL32UTF8
DEBUG:  oracle_fdw: begin serializable remote transaction
DEBUG:  CommitTransactionCommand
DEBUG:  CommitTransaction
DEBUG:  name: unnamed; blockState:       STARTED; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children:
DEBUG:  oracle_fdw: commit remote transaction
IMPORT FOREIGN SCHEMA
```

I don't receive any errors, but my schema is empty:

```
postgres=# \det
 List of foreign tables
 Schema | Table | Server
--------+-------+--------
(0 rows)

postgres=# \d
No relations found.
```

I went through the code a bit and found the Oracle SQL statements in `orcale_utils.c` for `oracleGetImportColumn` that are issued on `IMPORT FOREIGN SCHEMA`. My first thought was my Oracle user may not have the authority to run some of these queries. I'm no Oracle expert, but these queires seem pretty straight-forward. I ran some similar quieries with SQLPlus and didn't have a problem.

I see there are some additional debug messages from `oracle_utils.c` but I am not sure how to capture those messages.

**Comment by laurenz** [comment]
I can see no error in what you did.

Are there any tables or views defined in Schema AUS?
What do you get for the following query:

    SELECT table_name FROM all_tables WHERE owner = 'AUS';

**Comment by aus** [comment]
Well, I feel silly now. I had the owner name wrong. I corrected, and it works. Thanks for pointing me in the right direction. And thanks for your work on this project. It's exactly what I needed.
