### ISSUE TITLE
Errors in regression test

### ISSUE THREAD

**Issue by sunwei-ch** [laurenz/oracle_fdw#473]
Hi,

When I try to run regression tests in the following environments，Some tests are failing. 
Oracle server version : 11.2
Oracle client version : 11.2
postgresql version : 13.3
oracle_fdw version : 2.3.0

Some of the error messages are as follows:
```
> --- ./oracle_fdw/expected/oracle_fdw.out
+++ ./oracle_fdw/results/oracle_fdw.out
@@ -179,6 +179,8 @@
    '1 day 2 hours 30 seconds 1 microsecond',
    '-6 months'
 );
+ERROR:  error executing query: OCIStmtExecute failed to execute remote query
+DETAIL:  ORA-01843: not a valid month
 INSERT INTO shorty (id, c) VALUES (2, NULL);
 INSERT INTO typetest1 (id, c, nc, vc, nvc, lc, r, u, lb, lr, b, num, fl, db, d, ts, ids, iym) VALUES (
    3,
@@ -200,6 +202,8 @@
    '-2 days -12 hours -30 minutes',
    '-2 years -6 months'
 );
+ERROR:  error executing query: OCIStmtExecute failed to execute remote query
+DETAIL:  ORA-01847: day of month must be between 1 and last day of month
```

But when I test on Oracle server 12.2, it doesn't happen.
Is this because the oracle_fdw 2.3.0 has version requirements Oracle Server?

**Comment by laurenz** [comment]
That should not happen, and Oracle 11.2 should work.

The first think I would like to know is the actual Oracle statement issued. You can get that with

    EXPLAIN INSERT INTO typetest1 ...;

Errors like that can happen if parameters like `NLS_DATE_FORMAT`, `NLS_TIMESTAMP_FORMAT` or `NLS_TIMESTAMP_TZ_FORMAT` are set to wrong values.

oracle_fdw sets these parameters when it connects to Oracle, but I have seen cases where a silly logon trigger in Oracle changed the values and broke oracle_fdw (see #402). Could you check if that is the case here?

**Comment by sun-wei-ch** [comment]
Thank you for your reply.

I executed:
```
EXPLAIN INSERT INTO typetest1 (id, c, nc, vc, nvc, lc, r, u, lb, lr, b, num, fl, db, d, ts, ids, iym) VALUES (
   1,
   'fixed char',
   'nat''l char',
   'varlena',
   'nat''l var',
   'character large object',
   bytea('\xDEADBEEF'),
   uuid('055e26fa-f1d8-771f-e053-1645990add93'),
   bytea('\xDEADBEEF'),
   bytea('\xDEADBEEF'),
   TRUE,
   3.14159,
   3.14159,
   3.14159,
   '1968-10-20',
   '2009-01-26 15:02:54.893532 PST',
   '1 day 2 hours 30 seconds 1 microsecond',
   '-6 months'
);
```
  
The results are as follows:
(I try to use oracle_fdw 2.2.0 to test in the same environment, the query plan is the same. but INSERT sql can be executed normally)
```
Insert on typetest1  (cost=0.00..0.01 rows=1 width=391)
  Oracle statement: INSERT INTO "TYPETEST1" ("ID", "C", "NC", "VC", "NVC", "LC", "R", "U", "LB", "LR", "B", "NUM", "FL", "DB", "D", "TS", "IDS", "IYM") VALUES 
  (:p1, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10, :p11, :p12, :p13, :p14, :p15, CAST (:p16 AS DATE), CAST (:p17 AS TIMESTAMP WITH TIME ZONE), :p18, :p19)
  ->  Result  (cost=0.00..0.01 rows=1 width=391) (actual time=0.003..0.005 rows=1 loops=1)
```  

I didn't find the  silly logon trigger on my oracle server, and then i try to changed `NLS_DATE_FORMAT`,`NLS_TIMESTAMP_FORMAT ` and `NLS_TIMESTAMP_TZ_FORMAT` to the same value as the server in session, but this problem still happen.
```
SELECT oracle_execute('oracle',E'ALTER SESSION SET NLS_DATE_FORMAT = ''DD-MON-RR''');
SELECT oracle_execute('oracle',E'ALTER SESSION SET NLS_TIMESTAMP_FORMAT = ''DD-MON-RR HH.MI.SSXFF AM''');
SELECT oracle_execute('oracle',E'ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = ''DD-MON-RR HH.MI.SSXFF AM TZR''');
```

**Comment by laurenz** [comment]
But those settings are wrong. The correct ones are:

```none
NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS BC'
NLS_TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS.FF9 BC'
NLS_TIMESTAMP_TZ_FORMAT='YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC'
```

You can find logon triggers with

```
SELECT trigger_name, trigger_body
FROM dba_triggers
WHERE triggering_event = 'LOGON';
```

**Comment by sun-wei-ch** [comment]
It is not convenient to modify the parameters of the system,i try to changed NLS_DATE_FORMAT,NLS_TIMESTAMP_FORMAT and NLS_TIMESTAMP_TZ_FORMAT in session, but this problem still happen.
```
SELECT oracle_execute('oracle',E'ALTER SESSION SET NLS_DATE_FORMAT = ''YYYY-MM-DD HH24:MI:SS BC''');
SELECT oracle_execute('oracle',E'ALTER SESSION SET NLS_TIMESTAMP_FORMAT = ''YYYY-MM-DD HH24:MI:SS.FF9 BC''');
SELECT oracle_execute('oracle',E'ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = ''YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC''');
```

I executed the following SQL , but did not get any results.
```
SELECT trigger_name, trigger_body
FROM all_triggers 
WHERE triggering_event = 'LOGON';
```

Because oracle_fdw 2.2.0 uses the same Oracle server , I wonder if it is caused by the commit in oracle_fdw 2.3.0.  I tried to compare the source code in oracle_fdw 2.2.0 and oracle_fdw 2.3.0, but didn't find anything suspicious at present.

**Comment by laurenz** [comment]
If you ran these `oracle_execute` in the same PostgreSQL session as the query, I have no clue. These are the correct values, and they should work. For proper operation, you also need

```none
NLS_DATE_LANGUAGE=AMERICAN
NLS_CALENDAR=             (unset)
```

Could you create a foreign table based on `NLS_SESSION_PARAMETERS` as indicated [here](https://github.com/laurenz/oracle_fdw/issues/287#issuecomment-453453134)? Then start a new PostgreSQL session and tell me what you find there.

About the login trigger, perhaps you don't have permissions to see it. Can you ask your DBA if there are any logon triggers defined?

**Comment by sunwei-ch** [comment]
I did it and query the data from 'NLS_DATABASE_PARAMETERS', the data are as follows

NLS_SESSION_PARAMETERS
```
        parameter        |                value
-------------------------+-------------------------------------
 NLS_LANGUAGE            | AMERICAN
 NLS_TERRITORY           | AMERICA
 NLS_CURRENCY            | $
 NLS_ISO_CURRENCY        | AMERICA
 NLS_NUMERIC_CHARACTERS  | .,
 NLS_CALENDAR            | GREGORIAN
 NLS_DATE_FORMAT         | YYYY-MM-DD HH24:MI:SS BC
 NLS_DATE_LANGUAGE       | AMERICAN
 NLS_SORT                | BINARY
 NLS_TIME_FORMAT         | HH.MI.SSXFF AM
 NLS_TIMESTAMP_FORMAT    | YYYY-MM-DD HH24:MI:SS.FF9 BC
 NLS_TIME_TZ_FORMAT      | HH.MI.SSXFF AM TZR
 NLS_TIMESTAMP_TZ_FORMAT | YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC
 NLS_DUAL_CURRENCY       | $
 NLS_COMP                | BINARY
 NLS_LENGTH_SEMANTICS    | BYTE
 NLS_NCHAR_CONV_EXCP     | FALSE
```

NLS_DATABASE_PARAMETERS
```
        parameter        |            value
-------------------------+------------------------------
 NLS_LANGUAGE            | AMERICAN
 NLS_TERRITORY           | AMERICA
 NLS_CURRENCY            | $
 NLS_ISO_CURRENCY        | AMERICA
 NLS_NUMERIC_CHARACTERS  | .,
 NLS_CHARACTERSET        | AL32UTF8
 NLS_CALENDAR            | GREGORIAN
 NLS_DATE_FORMAT         | DD-MON-RR
 NLS_DATE_LANGUAGE       | AMERICAN
 NLS_SORT                | BINARY
 NLS_TIME_FORMAT         | HH.MI.SSXFF AM
 NLS_TIMESTAMP_FORMAT    | DD-MON-RR HH.MI.SSXFF AM
 NLS_TIME_TZ_FORMAT      | HH.MI.SSXFF AM TZR
 NLS_TIMESTAMP_TZ_FORMAT | DD-MON-RR HH.MI.SSXFF AM TZR
 NLS_DUAL_CURRENCY       | $
 NLS_COMP                | BINARY
 NLS_LENGTH_SEMANTICS    | BYTE
 NLS_NCHAR_CONV_EXCP     | FALSE
 NLS_NCHAR_CHARACTERSET  | AL16UTF16
 NLS_RDBMS_VERSION       | 11.2.0.1.0

```
PG_SETTINGS
```
    name     | setting
-------------+---------
 lc_collate  | C
 lc_ctype    | C
 lc_messages | C
 lc_monetary | C
 lc_numeric  | C
 lc_time     | C
```

The  `nls_database_parameters` of database is wrong,when I modify the `nls_database_parameters` of the database like the session and restart the oracle server,  `nls_database_parameters` of database  has not changed. I think this problem may be related to my oracle server settings.
```
alter system set NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS BC' scope=spfile;
alter system set NLS_TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS.FF9 BC' scope=spfile;
alter system set NLS_TIMESTAMP_TZ_FORMAT='YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC' scope=spfile;
alter system set NLS_DATE_LANGUAGE='AMERICAN' scope=spfile;
```

I try to used the sysdba user to find the logon trigger，but did not get any results.
Then I tried to create the following  logon trigger,but this problem still happen.
```
CREATE OR REPLACE TRIGGER LOGON_TRG
  before  LOGON ON DATABASE
BEGIN
  EXECUTE IMMEDIATE 'alter session set NLS_DATE_FORMAT=''YYYY-MM-DD HH24:MI:SS BC''';
  EXECUTE IMMEDIATE 'alter session set NLS_TIMESTAMP_FORMAT=''YYYY-MM-DD HH24:MI:SS.FF9 BC''';
  EXECUTE IMMEDIATE 'alter session set NLS_TIMESTAMP_TZ_FORMAT=''YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC''';
  EXECUTE IMMEDIATE 'alter session set NLS_DATE_LANGUAGE=''AMERICAN''';
exception 
   when others 
      then null; -- prevent a login failure due to an exception    
END logon_trg;
/
```

**Comment by laurenz** [comment]
You really tried to make sure. So let's assume that the settings are correct.
The database parameters shouldn't matter, it is the session parameters that do.

I have no clue what the problem could be.

You could use the procedures in [`DBMS_MONITOR`][1] to trace on the Oracle server. Set `binds => true` and `waits => false` to see the values of the parameters as they are sent to the server. Perhaps that shows something.


 [1]: https://docs.oracle.com/cd/E11882_01/appdev.112/e40758/d_monitor.htm

**Comment by sunwei-ch** [comment]
Thank you for your reply.
I don't have much Oracle experience, which is a bit difficult for me.
As a temporary solution, I use Oracle 12 as a server to avoid this problem.
If there is any subsequent discovery, I will commit a new issue to report

**Comment by laurenz** [comment]
Thanks for the feedback, and sorry that I couldn't help figure out the cause of the problem.
