### ISSUE TITLE
-I$(ORACLE_HOME) issue

### ISSUE THREAD

**Issue by fjf2002** [laurenz/oracle_fdw#475]
Your Makefile says:

... `-I$(ORACLE_HOME) -I/usr/include/oracle/21/client64` ...

... and /usr/include/oracle/21/client64 is exactly the right path for me.

On my system, ORACLE_HOME is not set. As a result, the following `-I/usr/include/oracle/21/client64` kinda gets ignored (perhaps mangled to `-I"-I/usr/include/oracle/21/client64"`?)

### Solution:
```
export ORACLE_HOME=dummy
```
solves the problem for me.
But you may want to guard your script better for that case?

**Comment by laurenz** [comment]
Thanks for the report, fixed.
