### ISSUE TITLE
Left Join is pushing down where clause wrongly 

### ISSUE THREAD

**Issue by msijmons** [laurenz/oracle_fdw#476]
Th follwoing query is issued : 

```
select pg.id as pg_id
     from public.event_0 pg
     left join ora_vc.event ora
     on ora.id = pg.id and  mod(ora.id , 10) = 0
     where mod(ora.id , 10) = 0
       and ora.id is null;
```

The ora_vc.event is the foreign table. 

The query must find any id's present in the public.event_0 but not in the ora_vc.event table

This is the explain plan: 
```
                                                                           QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 Hash Join  (cost=12255.33..22269.08 rows=1000 width=8)
   Hash Cond: (ora.id = pg.id)
   ->  Foreign Scan on event ora  (cost=10000.00..20000.00 rows=1000 width=4)
         Oracle query: SELECT /*93af4dad26c2911be0ae9e707211cffe*/ r2."ID" FROM "VC"."EVENT" r2 WHERE (r2."ID" IS NULL) AND (mod(r2."ID", 10) = 0)
   ->  Hash  (cost=1420.78..1420.78 rows=66764 width=8)
         ->  Index Only Scan using event_0_part_key_id_idx on event_0 pg  (cost=0.42..1420.78 rows=66764 width=8)
(6 rows)
```

As you can see the select in oracle will be :   Oracle query: SELECT /*93af4dad26c2911be0ae9e707211cffe*/ r2."ID" FROM "VC"."EVENT" r2 WHERE (r2."ID" IS NULL) AND (mod(r2."ID", 10) = 0)

The part  (r2."ID" IS NULL) is to find out that the right side is empty after the outer join, so the restriction before doing the outer join is too early 

Running the query gives as expected the wrong results

**Comment by laurenz** [comment]
@yamatattsu I know you are busy, but this is your join pushdown code. Could you have a look?

**Comment by laurenz** [comment]
@msijmons Can we have a complete reproducer?

**Comment by yamatattsu** [comment]
Hi Laurenz!

***@***.*** <https://github.com/yamatattsu> I know you are busy, but this
is your join pushdown code. Could you have a look?

I'll look into it this weekend. Is it okay?


>left join ora_vc.event ora
>on ora.id = pg.id and mod(ora.id , 10) = 0
>where mod(ora.id , 10) = 0

The mod(ora.id , 10) appears twice.
One of them is in the on clause and the other one is in the where clause.
In this case, I am wondering if their handling is correct in my join
pushdown code.


Regards, and Stay safe!
Tatsuro Yamada

**Comment by laurenz** [comment]
Thanks, @yamatattsu, I think you spotted the problem with the query right away (and shame on my for not seeing it).

If `mod(ora.id , 10) = 0` is part of the join condition (the `ON` clause), it is the right thing to do to push down the condition. So the problem is the original query, not the join push-down code.

Does that make sense to you, @msijmons?

**Comment by msijmons** [comment]
Yes you are correct, issue is non issue can be closed

**Comment by yamatattsu** [comment]
Hi Laurenz and msijmons,

Thanks, @yamatattsu <https://github.com/yamatattsu>, I think you spotted
> the problem with the query right away (and shame on my for not seeing it).
>
>
My pleasure.
I'm happy to have been able to help you out. :-D

Regards,
Tatsuro Yamada
