### ISSUE TITLE
how to create foreign table using oracle flashback query?

### ISSUE THREAD

**Issue by junhow** [laurenz/oracle_fdw#477]
Is there a way to create oracle foreign table using oracle flashback query (select ... as of SCN).   This would be useful for importing snapshot of oracle table at specific SCN into postgresql, and enable applying redo sql from that SCN.  Thank you

**Comment by laurenz** [comment]
The only way you could do this is by defining the foreign table on a query like

```
CREATE FOREIGN TABLE ft (...)
SERVER ... OPTIONS (table '(SELECT ... AS OF SCN ...)');
```

But I guess you wouldn't want to hard-code the SCN. I cannot think of a way to achieve that.

**Comment by junhow** [comment]
It's great that it is possible.  Hard coding SCN is fine, as I am trying to import snapshot of table at specific SCN from oracle.  After that point, I will just apply redo from oracle logminer to keep data in postgresql in sync with oracle master.   Thank you
