### ISSUE TITLE
Can't access remote schema / table (it says that it does not exist )

### ISSUE THREAD

**Issue by TimotheeWright** [laurenz/oracle_fdw#478]
Hello Laurenz Albe,

I think your work on oracle_fdw is awesome.  However it seems that I'm lacking documentation, or I'm doing something wrong because I can't get it to work.

I tried to summarize my steps, and the bold ones are the ones causing troubles.

So I have a database named chorus and a schema named chorus in postgres, then I

1. Created a user: `CREATE USER chorus WITH ENCRYPTED PASSWORD 'myPass';`
2. Gave the following privileges:
```
GRANT CONNECT, CREATE ON DATABASE chorus TO chorus; 
GRANT USAGE ON SCHEMA chorus TO chorus;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA chorus TO chorus;
```
3.	Downloaded the foreign data wrapper (at https://github.com/laurenz/oracle_fdw ).  
4.	Connected to postgres `psql -h localhost -p 5432 -U postgres`
5.	Created the extension oracle_fdw:  `create extension oracle_fdw;`
6.	Created a server with remote access:  `create server oracleChorus FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '//localhost/ORCL');`
7.	And gave the privilege USAGE to chorus on this server: `GRANT USAGE ON FOREIGN SERVER oracleChorus TO chorus;`
8.	Mapped the postgres user to the oracle user: `CREATE USER MAPPING FOR chorus SERVER oracleChorus OPTIONS (user 'c##chorus', password 'myPass');`

**9.**	At this stage, we should be able to perform operations such as `SELECT * from account;` with account being a table under oracle. 
I also tried
`CREATE FOREIGN TABLE f_oracle_account("CPT_NAME" VARCHAR NOT NULL, "CPT_MDP" VARCHAR, "CPT_LIBEL" VARCHAR) SERVER oracleChorus OPTIONS (schema 'c##chorus', table 'ACCOUNT');
`
Here I'm facing:
```
_postgres=# CREATE FOREIGN TABLE f_oracle_compte("CPT_NOM" VARCHAR NOT NULL, "CPT_MDP" VARCHAR, "CPT_LIBELLE" VARCHAR) SERVER oracleChorus OPTIONS (schema 'c##chorus', table 'COMPTE');
CREATE FOREIGN TABLE
postgres=# select * from f_oracle_compte;
ERREUR:  Oracle table "c##chorus"."COMPTE" for foreign table "f_oracle_compte" does not exist or does not allow read access
DÉTAIL : ORA-00942: Table ou vue inexistante
ASTUCE : Oracle table names are case sensitive (normally all uppercase)._
```

I also tried:

10.	Download and unzip these two deposits. 
https://github.com/cybertec-postgresql/db_migrator
https://github.com/cybertec-postgresql/ora_migrator
11.	Take the .control and .sql files in these two folders and paste them in C:\Program Files\PostgreSQL\13\share\extension
12.	Create the schema chorusOracle: `CREATE SCHEMA oracleChorus;`
**13.**	Import the schema from Oracle to postgres :` import foreign schema "c##chorus" from server oracleChorus into oracleChorus;`

The latest gives me: 
```
_postgres=# import foreign schema "c##chorus" from server oracleChorus into oracleChorus;
ERREUR:  remote schema "c##chorus" does not exist
ASTUCE : Enclose the schema name in double quotes to prevent case folding.
postgres=#_
```

And btw, this works: `sqlplus c##chorus@orcl as sysdba` .

Any help would be very appreciated. 

Thanks.

**Comment by TimotheeWright** [comment]
It seems that I did the same mistake as #395 ([Issue 395](https://github.com/laurenz/oracle_fdw/issues/395)). I wrote create table with schema name in small letter while oracle schema name should be in capital letters.

**Comment by laurenz** [comment]
Sorry for the late reply; I was on vacation.
Great  that you could figure out the problem!
