### ISSUE TITLE
Oracle timestamp(6) truncated with postgresql 9.5

### ISSUE THREAD

**Issue by dszczyt** [laurenz/oracle_fdw#48]
Mapping an oracle timestamp(6) field as timestamp(6) gives the following error:

ERREUR: error executing query: OCIStmtExecute failed to execute remote query
État SQL :HV00L
Détail :ORA-01406: la valeur de la colonne extraite a été tronquée

Follow the output of oracle_diag():

oracle_fdw 1.3.0, PostgreSQL 9.5.0, Oracle client 12.1.0.2.0

**Comment by laurenz** [comment]
Sorry for the inconvenience.

Could you tell me the timestamp value that causes the error?

**Comment by dszczyt** [comment]
Oracle SQL Dev Tool shows me values like : 28/03/14 17:56:10,863000000

First tried with import schema, giving this error. I tried to map into a character varying(255) in postgresql, same issue. It worked fine in postgresql 9.4.

**Comment by laurenz** [comment]
Hmm, it works for me.

In Oracle:

    SQL> CREATE TABLE tstest (id NUMBER(5) PRIMARY KEY, ts TIMESTAMP(6) NOT NULL);
    SQL> INSERT INTO tstest (id, ts) VALUES (1, to_timestamp('2014-03-28 17:56:10.863000000', 'YYYY-MM-DD HH24:MI:SS.FF'));
    SQL> COMMIT;

In PostgreSQL:

    test=> CREATE FOREIGN TABLE tstest (id integer NOT NULL, ts timestamp(6) NOT NULL) SERVER oracle OPTIONS (table 'TSTEST');
    test=> SELECT * FROM tstest;
    ┌────┬─────────────────────────┐
    │ id │           ts            │
    ├────┼─────────────────────────┤
    │  1 │ 2014-03-28 17:56:10.863 │
    └────┴─────────────────────────┘
    (1 row)

Could you tell me the exact hex value of the Oracle date field?
You can get it with the ``DUMP`` function, in my example like this:

    SQL> SELECT dump(ts, 16) FROM tstest WHERE id = 1;
    DUMP(TS,16)
    --------------------------------------------------------------------------------
    Typ=180 Len=11: 78,72,3,1c,12,39,b,33,70,55,c0

Alternatively, can you come up with a sequence of SQL statements to reproduce the problem?

**Comment by dszczyt** [comment]
Here is the result : 

```
Typ=180 Len=11: 78,72,3,1c,12,39,b,33,70,55,c0
```

So same value as yours. Did you run your tests with postgresql 9.5 ?

**Comment by laurenz** [comment]
Ok, I can reproduce the error now, but only with ``lc_messages = fr_FR.UTF-8``.
I'll look into it.

**Comment by laurenz** [comment]
I have pushed 3fa9d985e6a31cde4099be5636f6827a1a758db7 that should fix the problem.
Can you check?

**Comment by dszczyt** [comment]
:+1: Fixed ! Thanks !
