### ISSUE TITLE
Running oracle_execute from a procedure not working.

### ISSUE THREAD

**Issue by ksmalara** [laurenz/oracle_fdw#481]
Working from the Query Editor using Admin4 for Postgresql database access, the following command works:

```
SELECT oracle_execute(
'dw_remp_x',
'BEGIN REMPX.put_line( 0,'''' ); END;'
); 
```

where REMPX is a package name, and dw_remp_x is a foreign data wrapper using oracle_fdw

The problem:
When I call it from a procedure, I get the error "user mapping not found for xyz" 
This is the code to create the procedure.

            CREATE OR REPLACE PROCEDURE p_test(
            )
            LANGUAGE 'edbspl'
            SECURITY DEFINER VOLATILE
            COST 100
            AS $BODY$
            begin
                SELECT oracle_execute(
                'dw_remp_x',
                'BEGIN REMPX.put_line( 0,'''' ); END;'
            );
            end$BODY$;
            
            GRANT EXECUTE ON PROCEDURE p_test() TO xyz;
            GRANT EXECUTE ON PROCEDURE p_test() TO PUBLIC;

Any ideas on why this is now working.

**Comment by laurenz** [comment]
Sorry for my long silence; I was on vacation.

The owner of the function is a role different from `xyz`, and you execute the function as user `xyz`, right?
That looks like a bug; the user mapping of the function owner should be used.

Did I understand the problem correctly? I will have a look into this.

**Comment by ksmalara** [comment]
Thank you for your reply.
I have narrowed the issue down a bit more. The procedure put_line is in the package REMPX on the database referenced by wrapper dw_remp_x. The issue is with the package.

I created a procedure(p_call_putline) in this database, outside of the package, that calls REMPx.put_line . When I am logged on to the  database I can execute the procedure p_call_putline and it calls put_line successfully. 

I am using the same user to connect via oracle_connect as the one I used to log in to dw_remp_x. When this same procedure is called from the other database using the oracle_execute command, it calls the procedure p_call_putline and runs all lines except the REMPX.put_line call .There is no error message it just doesn't execute.  Since it calls the procedure, it appears that oracle_execute is working but somehow doesn't have access to the package. I have given the user and public all privileges on the package with no luck. Have you seen anything like this?

**Comment by laurenz** [comment]
I am confused &ndash; is that the same problem as the original one?
There you had a problem because it tried to use the user mapping for the wrong user, if I understood correctly.

Database A is PostgreSQL, and B is Oracle, right?
Can you describe that latter problem in more detail? What statement do you run in PostgreSQL, and what is the response?

**Comment by ksmalara** [comment]
Your suggestion for the mapping worked. Now I have a different problem where Oracle_execute runs a procedure on the foreign database but the call to a package inside that procedure doesn't work. I think it is something with my Postgresql database and not the oracle_execute command so you have answered my question. Thank you.

**Comment by laurenz** [comment]
I have fixed the bug, now oracle_fdw should use the correct user mapping.
