### ISSUE TITLE
Clob fields performance on oracle fdw

### ISSUE THREAD

**Issue by friendarora** [laurenz/oracle_fdw#483]
Hi All,

We have imported the oracle FDW on our postgres environment
We have created a foreign server and imported an oracle schema into our postgres schema with all its tables as foreign tables

We have a table order_email which has attachment in a clob datatype in oracle
We are writing a SQL to select all records from this order_email foreign table
but it is taking lot of time

Is there a way we could increase the performance of reading clob data from oracle to postgres

**Comment by jordiromera** [comment]
Hi,

This is a known problem, see #68, #326, #429 and #444.

**Comment by laurenz** [comment]
Yes, that is nothing new.
There is even an entry in the `TODO` file for that.

**Comment by laurenz** [comment]
The performance problem with Oracle LOBs has been improved with commit d679a73d02057fd674fc78fe5f25183e5c9a172b.
You are welcome to test if the current development version works better for you.
