### ISSUE TITLE
error connecting to Oracle

### ISSUE THREAD

**Issue by srivasum** [laurenz/oracle_fdw#487]
Hi Team.

I am getting below while accessing the table .

ERROR:  error connecting to Oracle: OCIAttrSet failed to set module in session handle
DETAIL:  CLI0124E  Invalid argument value.
SQL state: HV00N

Getting the same error for "SELECT oracle_diag('oracle_server');"

Could you please help on this. Thank you.

**Comment by laurenz** [comment]
Funny; that means that this call fails:

```c
OCIAttrSet(userhp, OCI_HTYPE_SESSION, "postgres", (ub4)8, OCI_ATTR_MODULE, errhp)
```

According to [the documentation](https://docs.oracle.com/en/database/oracle/oracle-database/18/lnoci/handle-and-descriptor-attributes.html#GUID-FB263210-118E-4DB3-A840-1769EF0CB977), it should be no problem to set that attribute on the session handle.

Can you tell me what Oracle versions you have installed on the PostgreSQL machine (Oracle client) and the Oracle server?
Is there anything unusual or noteworthy about your setup?

If you cannot figure this out, one simple option would be to modify `oracle_utils.c` and remove the code that sets `OCI_ATTR_MODULE` and `OCI_ATTR_ACTION`. The only disadvantage is that the respective properties would not be set on the Oracle session, but that is not necessary and is only intended to assist debugging.

**Comment by srivasum** [comment]
Hi @laurenz ,

Thanks for the Response. Please find details required:

**Oracle Client** : SQL*Plus: Release 19.0.0.0.0 - Production on Mon Aug 16 00:57:21 2021 Version 19.3.0.0.0
**Oracle Serve**r : Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production With the Partitioning, Real Application Clusters, Automatic Storage Management, OLAP,
Data Mining and Real Application Testing options

I have commented code for OCI_ATTR_MODULE and OCI_ATTR_ACTION , Now i am getting below error : 

ERROR:  connection for foreign table "test1" cannot be authenticated ( test1 is view in the Oracle server)
DETAIL:  [IBM][OCI Driver] CLI0124E  Invalid argument value. SQLSTATE=HY009
SQL state: HV00N

Commands used   : 
CREATE EXTENSION oracle_fdw;
CREATE SERVER oracle_server FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '//192.168.244.22:1972/ORARAC' );
CREATE USER MAPPING FOR postgres SERVER oracle_server  OPTIONS (user 'oraapp', password '*******');
CREATE FOREIGN TABLE test.test1 SERVER oracle_server   OPTIONS (table 'TEST1');

Note : I have got below error while compiling the code after commented code.

oracle_utils.c: In function ‘oracleGetSession’:
oracle_utils.c:104:7: warning: unused variable ‘pid’ [-Wunused-variable]
  char pid[30], *nlscopy = NULL;

Thank you very much for your help.

**Comment by laurenz** [comment]
I see `[IBM][OCI Driver]` in your error message.

That doesn't look like you are using Oracle software.
What is that driver? You seem to be using the wrong software.

**Comment by srivasum** [comment]
I am using db2_fdw in parallel , Does db2_fdw and oracle_fdw co exist for same postgreSQL instance ?
I think , i have missed something while configuring Oracle client ,

 I have tried with Oracle instant client (19.12) , getting Earlier error message :
ERROR:  error connecting to Oracle: OCIAttrSet failed to set module in session handle
DETAIL:  CLI0124E  Invalid argument value.
SQL state: HV00N

**Comment by laurenz** [comment]
I suspect that you have mixed up something, and you are using the wrong driver by mistake.
Since I don't know the DB2 driver, I cannot advise on how to use it.

If I were you, I would uninstall all IBM software from the machine and then try to get it to run.

**Comment by srivasum** [comment]
Thank you @laurenz .
There was some issue with co-existence of db2_fdw and oracle_fdw on same postgres installation .. I have tried it in separate server, everything went well. 

Could you please let me know if there is any chance to have both on same server.   
Thanks Again,

**Comment by laurenz** [comment]
Since I have no experience with the DB2 driver, I cannot tell.
My guess is that you cannot use both at the same time, but that is only a guess.
