### ISSUE TITLE
docker postgresql 13.2 install oracle_fdw

### ISSUE THREAD

**Issue by blackkeai** [laurenz/oracle_fdw#488]
i want docker postgresql 13.2 install oracle_fdw 2.3.0

step1： download instantclient-basic-linux.x64-21.3.0.0.0.zip  instantclient-sdk-linux.x64-21.3.0.0.0.zip  instantclient-sqlplus-linux.x64-21.3.0.0.0.zip
step2: unzip instantclient-basic-linux.x64-21.3.0.0.0.zip  instantclient-sdk-linux.x64-21.3.0.0.0.zip  instantclient-sqlplus-linux.x64-21.3.0.0.0.zip

step3:  
      export ORACLE_HOME=/oracle_fdw/instantclient
      export OCI_LIB_DIR=$ORACLE_HOME
      export OCI_INC_DIR=$ORACLE_HOME/sdk/include
      export LD_LIBRARY_PATH=$ORACLE_HOME:$LD_LIBRARY_PATH

step4:  download ORACLE_FDW_2_3_0.zip and  unzip  
step5:  cd   ORACLE_FDW  path  and  make

The results are as follows。

error:
oracle_fdw.c:8:10: fatal error: postgres.h: No such file or directory
 #include "postgres.h"
          ^~~~~~~~~~~~

![image](https://user-images.githubusercontent.com/7159046/130063974-8712c0fa-c228-49fd-896c-8b667d9673bc.png)

**Comment by blackkeai** [comment]
docker postgresql must install  

apt-get install postgresql-server-dev-13

**Comment by laurenz** [comment]
This is a duplicate of #399
