### ISSUE TITLE
when change target oracle server by using ALTER SERVER(question)

### ISSUE THREAD

**Issue by SeanKimMel** [laurenz/oracle_fdw#489]
Hello, I hope someone can give me some advice on this particular job I'm planning to do.

there's 2 different oracle servers in my environment(lte's call it dev and prod).

both servers have idntical schema/table structure.

I'm wondering it's safe to change target oracle server from dev to prod by using ALTER SERVER command.

execute analyze would be the next.

Versions: ORACLE 19C, PostgreSQL 12, ORACLE_FDW 2.2.0

any advice will be very welcome.

Thank you.

BTW,my alternative plan will be extract ddl and recreate every foreign server,user mapping,foreign table.

**Comment by laurenz** [comment]
You can do that, but make sure that all PostgreSQL sessions that have used the server are terminated or have executed `oracle_close_connections()` to close all open Oracle connections.

**Comment by SeanKimMel** [comment]
> You can do that, but make sure that all PostgreSQL sessions that have used the server are terminated or have executed `oracle_close_connections()` to close all open Oracle connections.

Thank you for your confirmation and tip, laurenz.

I'll update this post with result of the work.

**Comment by SeanKimMel** [comment]
it worked as you have explained. 

we didn't even need to collect new statistics because the data between those two enviornment(dev,prd) are almost identical.

queries work just like before.

Thank you so much for your guidance.

Sean kim

**Comment by laurenz** [comment]
Thanks for the confirmation!
