### ISSUE TITLE
Regress test error occurred in the Postgresql10

### ISSUE THREAD

**Issue by sunwei-ch** [laurenz/oracle_fdw#490]
Hi,

When I try to run regression tests in the postgresql10，Some tests are failing.
postgresql version : 10.18
oracle_fdw version : 2.3.0

There are three errors, two of which are caused by compatibility, and one I'm still investigating

Error 1 : Key "DEFAULT" cannot be used when create PARTITION in the postgresql10,
Because this is a new feature supported by postgresql11.
In test case oracle_fdw, the error occurred when using following SQL create partition tables
error message:
```
CREATE TABLE defpart PARTITION OF party DEFAULT;
ERROR:  syntax error at or near "DEFAULT"
LINE 1: CREATE TABLE defpart PARTITION OF party DEFAULT;
```

Error 2 : Test set compatibility issues
Original join test expected file  has been deleted in the oracle_fdw 2.3.0.
[https://github.com/laurenz/oracle_fdw/commit/3fcf3da8075ceca93a4efbe3faa816eb502e2137](url)
There is no problem after postgresql10, but in postgresql10, this file is still seems to be needed
error message:
```
expected:Oracle query: SELECT /*60c7fea5e3f46dc2acdc8ab8bb7ef8ad*/ r1."ID",……
result:  Oracle query: SELECT /*8cfad8830fdd7c0b2616a8b988b7abb5*/ r2."ID",……
```

Error 3 : Copy test of oracle_fdw failed
Copy test of oracle_fdw has been improved in the oracle_fdw 2.2.0,but the test failed on postgresql10
error message:
```
BEGIN;
COPY typetest1 FROM STDIN;
ERROR:  cannot copy to foreign table "typetest1"
ROLLBACK;
```

Error 1 and Error 2 are only caused by the version of PostgreSQL or the compatibility of the test set. 
I would like to confirm that in addition to the test set, does oracle_fdw 2.3.0 itself have requirements for postgresQL version.
For error 3, I am still investigating. if there is any new discovery, I will report on this issues.

**Comment by laurenz** [comment]
The first error is because you use an old PostgreSQL version, which does not support default partitions.

About problem two: if I remember right, that was a change in the PostgreSQL optimizer. The query changed, right?

Problem three again is because you are using PostgreSQL v10. Support for `COPY` was introduced in v11 with [commit 3d956d9562aa][copy].

 [copy]: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=3d956d9562aa4811b5eaaaf5314d361c61be2ae0

**Comment by sunwei-ch** [comment]
Thank you for your reply.

As you said, the reason for the regress test problem is that I used an old version of PostgreSQL.
The documentation or release note does not mention that PostgreSQL10 is no longer supported.
Can i think some regress test of oracle_fdw2.3.0 requires PostgreSQL11 or higher PostgreSQL, 
but oracle_fdw 2.3.0 still support PostgreSQL10?

**Comment by laurenz** [comment]
PostgreSQL v10 is supported and should work fine with oracle_fdw.

But I run the regression tests with the latest PostgreSQL development version.
Maintaining regression tests that work with all supported versions of PostgreSQL is too much effort for me.
I use the regression tests to make sure that my modifications didn't break the code.
If you are using back branches of PostgreSQL, some features won't work, and the psql output will have a slightly different format, but reading the diff carefully, you should be able to figure out if something is broken or not.

**Comment by sunwei-ch** [comment]
Thanks for your answer, I understand.
