### ISSUE TITLE
Question: When will be the release of oracle_fdw 2.4.0 version?

### ISSUE THREAD

**Issue by SeanKimMel** [laurenz/oracle_fdw#491]
Hi, laurenz

 I'm wondering about when would be the next official release of  oracle_fdw.

because I'm using oracle_fdw 2.2.0 version due to performance issue involved with BIND variables on 2.3.0.

However I might need to test different isolation level via oracle_fdw available in 2.3.0 version.

If there's 2.4.0 version release not to far from now, I'd like to wait for it because it will provide me the feature that I'd like to try

and does not have the performance issue like 2.3.0 verison.

I'm not requesting official release, if there's no plan in near future I'll just use the latest patch to test the feature.

Thank you.

**Comment by laurenz** [comment]
Sometime soon :^)

I usually release once a year, around the time when the new PostgreSQL release comes out.

Perhaps I should release more often, but I also release Windows binaries, and I that requires me to find a WIndows machine and spend a day getting it to work.

I try to keep Git HEAD in good shape, so you can always use that.

**Comment by SeanKimMel** [comment]
Thank you for your answer.

I'll try the master branch for now.

Sean Kim

**Comment by laurenz** [comment]
I just released 2.4.0.
