### ISSUE TITLE
Segmentation Fault while executing analyze on foreign table

### ISSUE THREAD

**Issue by SeanKimMel** [laurenz/oracle_fdw#494]
I'd like to share this case I'm experiencing.

at the beginning of the project, I've set the foreign table in postgresql using oracle_fdw with exact same structure with oracle table.  ​

And I scheduled analyze for the foreign table at 2:00 am everyday.

however I noticed from some point, DBMS is experiencing segmentation fault around 2:00 am everyday.

I was trying to find the origin of the problem, so I compare the ddl of both tables.(oracle and foreign table)

and I noticed there's been an alteration on the oracle table.(2 column has been added)

So I'm wondering why(I have my guesses but I want more clarification) and there's any known workaround for this problem.

In case anyone wants to reproduce the result, I post my test enviornment below.

PostgreSQL 12.5 on Centos 7
Oracle_fdw 2.2.0 version
Oracle client 19.11.0.0.0
Oracle Server 19.0.0.0.0

**Comment by laurenz** [comment]
This is probably the bug fixed in 56cb7a575cefd43d5091107536d06f655570c7e3.
Try upgrading to the current development version and see if that fixes your problem.

**Comment by SeanKimMel** [comment]
Thank you!! 

I have updated to the latest version and analyze no longer triggers segmentation fault.

**Comment by laurenz** [comment]
Thanks for the feedback.
