### ISSUE TITLE
error: ‘ModifyTableState’ {aka ‘struct ModifyTableState’} has no member named ‘mt_plans’;

### ISSUE THREAD

**Issue by ranjitmamidi1** [laurenz/oracle_fdw#497]
Error while installing oraclefdw in my docker desktop 
Versions used : 
posrgres 13
oracle_fdw : 2_3_0
instantclient:19_3 and 19_12. Same error for both versions

Step executed : `RUN cd /tmp/oracle_fdw-ORACLE_FDW_${oracle_fdw_version} && make && make install`

Error : 
```none
#9 3.927 oracle_fdw.c: In function ‘oracle_fdw_handler’:
#9 3.932 oracle_fdw.c:400:38: warning: assignment to ‘AddForeignUpdateTargets_function’ {aka ‘void (*)(struct PlannerInfo *, unsigned int,  struct RangeTblEntry *, struct RelationData *)’} from incompatible pointer type ‘void (*)(Query *, RangeTblEntry *, struct RelationData *)’ {aka ‘void (*)(struct Query *, struct RangeTblEntry *, struct RelationData *)’} [-Wincompatible-pointer-types]
#9 3.932   fdwroutine->AddForeignUpdateTargets = oracleAddForeignUpdateTargets;
#9 3.932                                       ^
#9 4.068 oracle_fdw.c: In function ‘oracleBeginForeignModify’:
#9 4.068 oracle_fdw.c:1718:27: error: ‘ModifyTableState’ {aka ‘struct ModifyTableState’} has no member named ‘mt_plans’; did you mean ‘mt_done’?
#9 4.068   Plan *subplan = mtstate->mt_plans[subplan_index]->plan;
#9 4.068                            ^~~~~~~~
#9 4.068                            mt_done
#9 6.705 make: *** [<builtin>: oracle_fdw.o] Error 1
#9 ERROR: executor failed running [/bin/sh -c cd /tmp/oracle_fdw-ORACLE_FDW_${oracle_fdw_version} && make && make install]: exit code: 2
```

**Comment by laurenz** [comment]
In your first comment you say that building fails with PostgreSQL v13 and oracle_fdw 2.3.0, while your second comment says it works.  I am confused.

The error message indicates that `PG_VERSION_NUM < 140000`, that is, the PostgreSQL version against which you build is v13 or below. But in these versions, `ModifyTableState` certainly has a member `mt_plans`.  That looks like you are building against something weird that does not seem to be normal PostgreSQL.

**Comment by ranjitmamidi1** [comment]
This is the Dockerfile I am using and error I am seeing

FROM postgres:13
ARG oracle_fdw_version=2_3_0
ARG instantclient_version=19_3

RUN apt-get update && apt-get install wget -y --no-install-recommends \
    apt-utils \
    libaio1 \
    libaio-dev \
    build-essential \
    make \	
    unzip \	
    postgresql-server-dev-all \
    postgresql-common


COPY sdk\ /tmp
RUN unzip "/tmp/*.zip" -d /tmp

ENV ORACLE_HOME /tmp/instantclient_${instantclient_version}
ENV LD_LIBRARY_PATH /tmp/instantclient_${instantclient_version}

RUN cd /tmp/oracle_fdw-ORACLE_FDW_${oracle_fdw_version} && make && make install

USER postgres

ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 5432
CMD ["postgres"]


Error : 
 #9 8.587 oracle_fdw.c: In function ‘oracle_fdw_handler’:
#9 8.588 oracle_fdw.c:400:38: warning: assignment to ‘AddForeignUpdateTargets_function’ {aka ‘void (*)(PlannerInfo *, unsigned int,  RangeTblEntry *, struct RelationData *)’} from incompatible pointer type ‘void (*)(Query *, RangeTblEntry *, struct RelationData *)’ [-Wincompatible-pointer-types]
#9 8.588   400 |  fdwroutine->AddForeignUpdateTargets = oracleAddForeignUpdateTargets;
#9 8.588       |                                      ^
#9 8.608 oracle_fdw.c: In function ‘oracleBeginForeignModify’:
#9 8.608 oracle_fdw.c:1718:25: error: ‘ModifyTableState’ has no member named ‘mt_plans’
#9 8.608  1718 |  Plan *subplan = mtstate->mt_plans[subplan_index]->plan;
#9 8.608       |                         ^~
#9 10.83 make: *** [<builtin>: oracle_fdw.o] Error 1
#9 ERROR: executor failed running [/bin/sh -c cd /tmp/oracle_fdw-ORACLE_FDW_${oracle_fdw_version} && make && make install]: exit code: 2
------
 > [5/5] RUN cd /tmp/oracle_fdw-ORACLE_FDW_2_3_0 && make && make install:
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c cd /tmp/oracle_fdw-ORACLE_FDW_${oracle_fdw_version} && make && make install]: exit code: 2

**Comment by ranjitmamidi1** [comment]
This is exactly I tried. I just started a fresh container with only postgres 13.
My new dockerfile
`FROM postgres:13`

```
Output
$ docker compose build
#1 [internal] load build definition from Dockerfile
#1 sha256:401f477834cf5134c833e43a5e679c08c7d36edf543ded41749582b5d12881fa
#1 transferring dockerfile: 53B 0.0s done
#1 DONE 0.1s

#2 [internal] load .dockerignore
#2 sha256:9391414d02b20e9f6726ef0e4a74ee41e1285e5e49994d37d018623517302214
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/postgres:13
#3 sha256:554dead64fd28f8672cb15174c743307928a1fd5e4b671ff87406985f084dcd8
#3 ...

#4 [auth] library/postgres:pull token for registry-1.docker.io
#4 sha256:1c5df7b6b03aaa66900ade9a0f3a89eda027d34bccc3fe6af700dfb35890206a
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/library/postgres:13
#3 sha256:554dead64fd28f8672cb15174c743307928a1fd5e4b671ff87406985f084dcd8
#3 DONE 3.6s

#5 [1/1] FROM docker.io/library/postgres:13@sha256:1adb50e5c24f550a9e68457a2ce60e9e4103dfc43c3b36e98310168165b443a1
#5 sha256:052e4162c00d48a7516f531d5027ec3e77020042e3713897c9883185a85f6067
#5 DONE 0.0s

#5 [1/1] FROM docker.io/library/postgres:13@sha256:1adb50e5c24f550a9e68457a2ce60e9e4103dfc43c3b36e98310168165b443a1
#5 sha256:052e4162c00d48a7516f531d5027ec3e77020042e3713897c9883185a85f6067
#5 resolve docker.io/library/postgres:13@sha256:1adb50e5c24f550a9e68457a2ce60e9e4103dfc43c3b36e98310168165b443a1 0.0s done
#5 sha256:b87d06f51711c53ac0ef42c4eb9073acd19f446a9caa91aa13435480b3595ee1 3.04kB / 3.04kB done
#5 sha256:1adb50e5c24f550a9e68457a2ce60e9e4103dfc43c3b36e98310168165b443a1 1.86kB / 1.86kB done
#5 sha256:113197da0347a82925486217beece0386a4de3b4aa3a34e53a20c988606ffa96 10.27kB / 10.27kB done
#5 sha256:4e6d0469c33225627ddfdde1174e11db7f006effe2cd8b4fd231f00ae6b6b6d8 4.71kB / 4.71kB 0.3s done
#5 extracting sha256:4e6d0469c33225627ddfdde1174e11db7f006effe2cd8b4fd231f00ae6b6b6d8 0.0s done
#5 DONE 0.9s

#6 exporting to image
#6 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#6 exporting layers done
#6 writing image sha256:59a703a13f11193bb67dc9c1052a1db6277114a50a1e06f7ca1a5a529c2c0072
#6 writing image sha256:59a703a13f11193bb67dc9c1052a1db6277114a50a1e06f7ca1a5a529c2c0072 done
#6 naming to docker.io/library/postgres13 0.0s done
#6 DONE 0.1s

$ docker image ls
REPOSITORY                                       TAG       IMAGE ID       CREATED        SIZE
postgres13                                       latest    59a703a13f11   36 hours ago   371MB

$ docker run --name test -p 5432:5432 -e POSTGRES_USER=TEST -e POSTGRES_PASSWORD=TEST -v volume:/var/lib/postgresql/data -d  postgres13
8c730328b5d4b5a2497480e7bfd69503cb7bf62729e9ef0a8102698febc10a6d

$ docker ps
CONTAINER ID   IMAGE                                                   COMMAND                  CREATED          STATUS         PORTS                    NAMES
8c730328b5d4   postgres13                                              "docker-entrypoint.s…"   12 seconds ago   Up 9 seconds   0.0.0.0:5432->5432/tcp   test

$ winpty docker exec -it test bash
root@8c730328b5d4:/# 
root@8c730328b5d4:/# `grep PG_VERSION_NUM /path/to/postgresql/include/*.h`
grep: /path/to/postgresql/include/*.h: No such file or directory
root@8c730328b5d4:/# `grep -r PG_VERSION_NUM /path/to/postgresql/include/*.h`
grep: /path/to/postgresql/include/*.h: No such file or directory
root@8c730328b5d4:/#  `grep PG_VERSION_NUM */include/*.h`
grep: */include/*.h: No such file or directory
root@8c730328b5d4:/# ` grep -r PG_VERSION_NUM */include/*.h`
grep: */include/*.h: No such file or directory

root@8c730328b5d4:/# `find . -name "execnodes.h"`
find: ‘./proc/1/map_files’: Permission denied
find: ‘./proc/63/map_files’: Permission denied
find: ‘./proc/64/map_files’: Permission denied
find: ‘./proc/65/map_files’: Permission denied
find: ‘./proc/66/map_files’: Permission denied
find: ‘./proc/67/map_files’: Permission denied
find: ‘./proc/68/map_files’: Permission denied
find: ‘./proc/88/map_files’: Permission denied
find: ‘./proc/89/map_files’: Permission denied
find: ‘./proc/91/map_files’: Permission denied


```

The files or the

**Comment by laurenz** [comment]
As I said, you have to replace `/patch/to/postgresql` with the actual installation path of PostgreSQL in your container.
You also have to use that path in the `find` command.
What do you get for `dpkg -l postgres\*`?

**Comment by laurenz** [comment]
I'll close this for inactivity. You can reopen it if you have new information.
