### ISSUE TITLE
tnsnames.ora

### ISSUE THREAD

**Issue by jottyfan** [laurenz/oracle_fdw#50]
Setting up oracle instant client may be not so easy, but using alien to convert rpm packages to deb files in Debian works quite well. Nevertheless, when one needs tnsnames.ora, there must be set an environment variable TNS_ADMIN that leads to the location of the tnsnames.ora. I didn't find it easy to configure this in oracle_fdw. But there's an easy solution: oracle instant client searches for tnsnames.ora in /etc, when there is no TNS_ADMIN set. It would be great to have this hint in your readme on setup instructions to save time for oracle_fdw users as tnsnames.ora is very common to oracle users.

**Comment by laurenz** [comment]
I often get requests to add documentation about installing and configuring Oracle, but that is such a huge topic that it would exceed the limits of a readable README.
How about writing a Wiki entry?
I know that the Wiki is empty so far, but if somebody writes something, it wouldn't be any more.
Here is the URL: [https://github.com/laurenz/oracle_fdw/wiki](https://github.com/laurenz/oracle_fdw/wiki)

**Comment by jottyfan** [comment]
Ok, I can understand that, as your readme is still huge. But I'm not so good in writing howtos or making wikis look nice, so I just put the information there. I even don't know how to publish this page, maybe you can have a look at that. Thanks!

**Comment by laurenz** [comment]
Thanks, I've tried to add some structure.
