### ISSUE TITLE
Specifying multiple dbservers or using TNS name from tnsnames.ora

### ISSUE THREAD

**Issue by askripalev** [laurenz/oracle_fdw#503]
Hi Laurenz,

For this moment I'm using "dblink" to Oracle as following:
CREATE SERVER ais_res FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '//192.168.197.88:1521/TTK00');

For a reason of reliability can I specifying multiple dbservers or use TNS name from tnsnames.ora for the statement above?

My tnsnames.ora looks like this:
TTK0 =
  (DESCRIPTION=
       (ADDRESS_LIST= (LOAD_BALANCE=on)(FAILOVER=on)
       (ADDRESS=(PROTOCOL=tcp)(HOST=192.168.197.88)(PORT=1521))
       (ADDRESS=(PROTOCOL=tcp)(HOST=192.168.197.101)(PORT=1521))
       (ADDRESS=(PROTOCOL=tcp)(HOST=192.168.197.102)(PORT=1521)))
       (CONNECT_DATA=(SERVER = DEDICATED)(SERVICE_NAME=TTK0sn)))

So, if 192.168.197.88 server fails, the other two will handle request in case of using TNS name, but statement with one dbserver won't.

It would be nice if fault tolerance could be handled as well!

--
SY, Alex

**Comment by laurenz** [comment]
oracle_fdw can use all naming methods supported by Oracle, including local naming with `tnsnames.ora`.

Just make sure that `ORACLE_HOME` or `TNS_ADMIN` are set in the environment of the PostgreSQL server, so that the Oracle client can find `tnsnames.ora`.

Then you can simply use

```none
OPTIONS (dbserver 'TTK0')
```

You don't really need local naming and specify the connect string in the server definition directly:

```none
OPTIONS (dbserver '(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=on)(FAILOVER=on)(ADDRESS=(PROTOCOL=tcp)(HOST=192.168.197.88)(PORT=1521))(ADDRESS=(PROTOCOL=tcp)(HOST=192.168.197.101)(PORT=1521))(ADDRESS=(PROTOCOL=tcp)(HOST=192.168.197.102)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=TTK0sn)))')
```

**Comment by askripalev** [comment]
Ah, okay :)

And is there a proper way to setting environment of the PostgreSQL server apart from running it with pgctl start?
It looks like .bashrc or .bash_profile won't make it.

**Comment by laurenz** [comment]
That depends on how you normally start the PostgreSQL server.
If it is systemd, you create a drop-in file in `/etc/systemd/system/` and set the environment variables there.

**Comment by askripalev** [comment]
Okay, thank you a lot :)
Have a nice day!

P.S. The issue can be closed now.
