### ISSUE TITLE
While copying data from oracle to postgreSQL using ora2pg, I am getting DETAIL:  ORA-12541: TNS:no listener at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 9352. error

### ISSUE THREAD

**Issue by chetan2211** [laurenz/oracle_fdw#507]
E:\ora2pg-23.0>ora2pg -t copy -c ora2pg_employee.dist -l employee.log
WARNING: NO_LOB_LOCATOR is deprecated, use USE_LOB_LOCATOR instead see documentation about the logic change.
WARNING: NO_BLOB_EXPORT is deprecated, use ENABLE_BLOB_EXPORT instead see documentation about the logic change.
[========================>] 1/1 tables (100.0%) end of scanning.
NOTICE:  user mapping for "employee" already exists for server "orcl", skipping
[========================>] 1/1 tables (100.0%) end of table export.
NOTICE:  drop cascades to foreign table ora2pg_fdw_import.employee_details
DBD::Pg::db do failed: ERROR:  connection for foreign table "employee_details" cannot be established
DETAIL:  ORA-12541: TNS:no listener at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 9352.
[========================>] 71/71 rows (100.0%) on total estimated data (1 sec., avg: 71 recs/sec)

I tried every solution which is available on internet but not able to resolve this issue. Please let me know if you know the solution.
Thank you in advance.

**Comment by darold** [comment]
You are mixing ora2pg and oracle_fdw, you are not posting on the right project.

**Comment by darold** [comment]
Then open an issue on the ora2pg project, this can not be discussed here.
