### ISSUE TITLE
Fatal error: can't create oracle_fdw.o: Permission denied

### ISSUE THREAD

**Issue by Charles-Arthur** [laurenz/oracle_fdw#514]
Hi 

I'm trying to configure oracle_fdw-ORACLE_FDW_2_4_0 on a OL7 (RHEL like) server and I'm getting the following error:

[postgres@server oracle_fdw-ORACLE_FDW_2_4_0]$ make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I"/sdk/include" -I"/oci/include" -I"/rdbms/public" -I"/" -I/usr/include/oracle/21/client64 -I/usr/include/oracle/19.12/client64 -I/usr/include/oracle/19.12/client -I/usr/include/oracle/19.11/client64 -I/usr/include/oracle/19.11/client -I/usr/include/oracle/19.10/client64 -I/usr/include/oracle/19.10/client -I/usr/include/oracle/19.9/client -I/usr/include/oracle/19.9/client64 -I/usr/include/oracle/19.8/client -I/usr/include/oracle/19.8/client64 -I/usr/include/oracle/19.6/client -I/usr/include/oracle/19.6/client64 -I/usr/include/oracle/19.3/client -I/usr/include/oracle/19.3/client64 -I/usr/include/oracle/18.5/client -I/usr/include/oracle/18.5/client64 -I/usr/include/oracle/18.3/client -I/usr/include/oracle/18.3/client64 -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_fdw.o oracle_fdw.c
Assembler messages:
Fatal error: can't create oracle_fdw.o: Permission denied
oracle_fdw.c:11:33: fatal error: access/htup_details.h: No such file or directory

Path is set as follows:
[postgres@server ~]$ echo $PATH
/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/home/postgres/.local/bin:/home/postgres/bin:/usr/pgsql-11/bin/pg_config

Do you have any idea what might be causing the issue?

Thanks
Charlie.

**Comment by laurenz** [comment]
It seems like your user does not have write permissions on the directory that got created when you unpacked the software. I'd recommend that you unpack the software with the same operating system user that you use to build it.

Also, your `PATH` seems wrong: It should not contain `/usr/pgsql-11/bin/pg_config`, but `/usr/pgsql-11/bin` (the directory that contains `pg_config`.

**Comment by Charles-Arthur** [comment]
So I've tried changing the path to the directory above pg_config in the path, I've also changed ownership of the unzipped file, but I'm still hitting issues:

[postgres@server ~]$ cd /u01/stage/
[postgres@server stage]$ ll
total 132
drwxrwxr-x 5 **postgres postgres**   4096 Jan 31 09:13 oracle_fdw-ORACLE_FDW_2_4_0
-rw-rw-r-- 1 postgres postgres 127620 Jan 28 14:44 oracle_fdw-ORACLE_FDW_2_4_0.tar.gz

[postgres@server stage]$ echo $PATH
/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/home/postgres/.local/bin:/home/postgres/bin:**/usr/pgsql-11/bin**

[postgres@server oracle_fdw-ORACLE_FDW_2_4_0]$ make clean
rm -f oracle_fdw.so   liboracle_fdw.a
rm -f oracle_fdw.o oracle_utils.o oracle_gis.o
rm -rf results/ regression.diffs regression.out tmp_check/ log/
[postgres@lv1038 oracle_fdw-ORACLE_FDW_2_4_0]$ make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I"/sdk/include" -I"/oci/include" -I"/rdbms/public" -I"/" -I/usr/include/oracle/21/client64 -I/usr/include/oracle/19.12/client64 -I/usr/include/oracle/19.12/client -I/usr/include/oracle/19.11/client64 -I/usr/include/oracle/19.11/client -I/usr/include/oracle/19.10/client64 -I/usr/include/oracle/19.10/client -I/usr/include/oracle/19.9/client -I/usr/include/oracle/19.9/client64 -I/usr/include/oracle/19.8/client -I/usr/include/oracle/19.8/client64 -I/usr/include/oracle/19.6/client -I/usr/include/oracle/19.6/client64 -I/usr/include/oracle/19.3/client -I/usr/include/oracle/19.3/client64 -I/usr/include/oracle/18.5/client -I/usr/include/oracle/18.5/client64 -I/usr/include/oracle/18.3/client -I/usr/include/oracle/18.3/client64 -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_fdw.o oracle_fdw.c
oracle_fdw.c:11:33: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"
                                 ^
compilation terminated.
make: *** [oracle_fdw.o] Error 1

The error appears to consistent whether run as either the Postgres or Root user. What am I missing?

**Comment by laurenz** [comment]
There could be two causes:

1. There is a different `pg_config` from a different PostgreSQL installation somewhere on the `PATH` before `/usr/pgsql-11/bin`.
   This is very likely, because I see `-I/usr/include/pgsql/server -I/usr/include/pgsql/internal` in the `gcc` invocation.

   The remedy is to put `/usr/pgsql-11/bin` at the beginning of the `PATH`.

2. You did not install the PostgreSQL header files. In RPM-based Linux distributions like you seem to be using, that package is called something like`postgresql11-devel`.

**Comment by Charles-Arthur** [comment]
Thanks Laurenz - things have moved on, although I'm still hitting some issues with the install. The 3rd section was just me not using sudo but it still failed with it. The 5ths section shows the path, with /usr/pgsql-11/bin being promoted to the start of the variable.

Any idea what further might be missing?

[postgres@server oracle_fdw-ORACLE_FDW_2_4_0]$ make clean
rm -f oracle_fdw.so   liboracle_fdw.a  liboracle_fdw.pc
rm -f oracle_fdw.o oracle_utils.o oracle_gis.o oracle_fdw.bc oracle_utils.bc oracle_gis.bc
rm -rf results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/ output_iso/

[postgres@server oracle_fdw-ORACLE_FDW_2_4_0]$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attsion=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffenclude" -I"/oci/include" -I"/rdbms/public" -I"/" -I/usr/include/oracle/21/client64 -I/usr/include/oracle/19.12/c11/client64 -I/usr/include/oracle/19.11/client -I/usr/include/oracle/19.10/client64 -I/usr/include/oracle/19.10/client64 -I/usr/include/oracle/19.8/client -I/usr/include/oracle/19.8/client64 -I/usr/include/oracle/19.6/clientnt -I/usr/include/oracle/19.3/client64 -I/usr/include/oracle/18.5/client -I/usr/include/oracle/18.5/client64 -I/I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/ininclude/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/includusr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/clientclude/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracl
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attsion=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffenclude" -I"/oci/include" -I"/rdbms/public" -I"/" -I/usr/include/oracle/21/client64 -I/usr/include/oracle/19.12/c11/client64 -I/usr/include/oracle/19.11/client -I/usr/include/oracle/19.10/client64 -I/usr/include/oracle/19.10/client64 -I/usr/include/oracle/19.8/client -I/usr/include/oracle/19.8/client64 -I/usr/include/oracle/19.6/clientnt -I/usr/include/oracle/19.3/client64 -I/usr/include/oracle/18.5/client -I/usr/include/oracle/18.5/client64 -I/I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/ininclude/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/includusr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/clientclude/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracl
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attsion=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffenclude" -I"/oci/include" -I"/rdbms/public" -I"/" -I/usr/include/oracle/21/client64 -I/usr/include/oracle/19.12/c11/client64 -I/usr/include/oracle/19.11/client -I/usr/include/oracle/19.10/client64 -I/usr/include/oracle/19.10/client64 -I/usr/include/oracle/19.8/client -I/usr/include/oracle/19.8/client64 -I/usr/include/oracle/19.6/clientnt -I/usr/include/oracle/19.3/client64 -I/usr/include/oracle/18.5/client -I/usr/include/oracle/18.5/client64 -I/I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/ininclude/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/includusr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/clientclude/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracl
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attsion=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffeo oracle_fdw.so oracle_fdw.o oracle_utils.o oracle_gis.o -L/usr/pgsql-11/lib   -L/usr/lib64/llvm5.0/lib  -L/usr/ags  -L"/" -L"/bin" -L"/lib" -L"/lib/amd64" -lclntsh -L/usr/lib/oracle/21/client64/lib -L/usr/lib/oracle/19.12/c11/client64/lib -L/usr/lib/oracle/19.11/client/lib -L/usr/lib/oracle/19.10/client64/lib -L/usr/lib/oracle/19.10/client64/lib -L/usr/lib/oracle/19.8/client/lib -L/usr/lib/oracle/19.8/client64/lib -L/usr/lib/oracle/19.6/clientnt/lib -L/usr/lib/oracle/19.3/client64/lib -L/usr/lib/oracle/18.5/client/lib -L/usr/lib/oracle/18.5/client64/libib -L/usr/lib/oracle/12.2/client/lib -L/usr/lib/oracle/12.2/client64/lib -L/usr/lib/oracle/12.1/client/lib -L/ususr/lib/oracle/11.2/client64/lib -L/usr/lib/oracle/11.1/client/lib -L/usr/lib/oracle/11.1/client64/lib -L/usr/li -L/usr/lib/oracle/10.2.0.4/client/lib -L/usr/lib/oracle/10.2.0.4/client64/lib -L/usr/lib/oracle/10.2.0.3/client

[postgres@server oracle_fdw-ORACLE_FDW_2_4_0]$ make install
/bin/mkdir -p '/usr/pgsql-11/lib'
/bin/mkdir -p '/usr/pgsql-11/share/extension'
/bin/mkdir -p '/usr/pgsql-11/share/extension'
/bin/mkdir -p '/usr/pgsql-11/doc/extension'
/bin/install -c -m 755  oracle_fdw.so '/usr/pgsql-11/lib/oracle_fdw.so'
/bin/install: cannot remove ‘/usr/pgsql-11/lib/oracle_fdw.so’: Permission denied
make: *** [install-lib-shared] Error 1

[postgres@server oracle_fdw-ORACLE_FDW_2_4_0]$ sudo make install
[sudo] password for postgres:
Makefile:23: /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk'.  Stop.
[postgres@server oracle_fdw-ORACLE_FDW_2_4_0]$

[postgres@server oracle_fdw-ORACLE_FDW_2_4_0]$ echo $PATH
:/usr/pgsql-11/bin/:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/home/postgres/.local/bin:/home/postgres/bin

**Comment by Charles-Arthur** [comment]
Hi, sorry I have done this already, from my last reply:

**[postgres@server oracle_fdw-ORACLE_FDW_2_4_0]$ sudo make install
[sudo] password for postgres:
Makefile:23: /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk'. Stop.
[postgres@server oracle_fdw-ORACLE_FDW_2_4_0]$**

**Comment by Charles-Arthur** [comment]
I've also tried as root user in the staging directory for the unzipped files:

[root: /u01/stage/oracle_fdw-ORACLE_FDW_2_4_0]
(Mon Feb 07 16:06:19) root $ **sudo make install**
Makefile:23: /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk'.  Stop.

**Comment by Charles-Arthur** [comment]
Brilliant, that's got it - the install is complete, fdw tested and working well, thanks for all your help!
