### ISSUE TITLE
oracle_fdw ==> control file issue

### ISSUE THREAD

**Issue by virendercse** [laurenz/oracle_fdw#518]
I am getting below error while creating extension:

postgres=# create extension oracle_fdw;
ERROR:  could not open extension control file "/usr/pgsql-13/share/extension/oracle_fdw.control": No such file or directory

Actual location of the control file:

 ls -lrth /usr/share/pgsql/extension/oracle_fdw.control
-rw-r--r--. 1 root root 133 Feb 25 11:29 /usr/share/pgsql/extension/oracle_fdw.control

while doing "make install" i used sudo. "sudo make install". 

Is this something with permission or need to create any symlinks

Versions:
-bash-4.2$ uname -a
Linux v13 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

oracle_fdw-0.9.10.zip

Oracle Client 21

PG13

**Comment by laurenz** [comment]
That would indicate that you found a wrong `pg_config` in the `PATH` that told oracle_fdw to install somewhere else.

Please provide the commands and the complete output you got for `make` and `sudo make install`.

Also, what do you get for `which pg_config` and `sudo which config`?

**Comment by virendercse** [comment]
-bash-4.2$ which pg_config
/usr/bin/pg_config
-bash-4.2$ sudo which pg_config
/bin/pg_config

(edited makefile to add Oracle21 lib path as earlier it was failing with oci.h file missing error).

-bash-4.2$ make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I/usr/include/oracle/21/client64 -I/usr/include/oracle/21/client64/sdk/include -I/usr/include/oracle/21/client64/oci/include -I/usr/include/oracle/21/client64/rdbms/public -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_utils.o oracle_utils.c
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -shared -o oracle_fdw.so oracle_fdw.o oracle_utils.o -L/usr/lib64 -Wl,-z,relro   -Wl,--as-needed  -L/usr/lib/oracle/21/client64/lib -L/usr/include/oracle/21/client64 -L/usr/include/oracle/21/client64/bin -L/usr/include/oracle/21/client64/lib -lclntsh -L/usr/lib/oracle/12.1/client/lib -L/usr/lib/oracle/12.1/client64/lib -L/usr/lib/oracle/11.2/client/lib -L/usr/lib/oracle/11.2/client64/lib -L/usr/lib/oracle/11.1/client/lib -L/usr/lib/oracle/11.1/client64/lib -L/usr/lib/oracle/10.2.0.5/client/lib -L/usr/lib/oracle/10.2.0.5/client64/lib -L/usr/lib/oracle/10.2.0.4/client/lib -L/usr/lib/oracle/10.2.0.4/client64/lib -L/usr/lib/oracle/10.2.0.3/client/lib -L/usr/lib/oracle/10.2.0.3/client64/lib 




-bash-4.2$ sudo make install
[sudo] password for postgres: 
/usr/bin/mkdir -p '/usr/lib64/pgsql'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/doc/pgsql/extension'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 755  oracle_fdw.so '/usr/lib64/pgsql/oracle_fdw.so'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw.control '/usr/share/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw--1.0.sql  '/usr/share/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./README.oracle_fdw '/usr/share/doc/pgsql/extension/'

postgres=# create extension oracle_fdw;
ERROR:  could not open extension control file "/usr/pgsql-13/share/extension/oracle_fdw.control": No such file or directory
postgres=# \q

**Comment by laurenz** [comment]
It looks like there is another installation of PostgreSQL on your machine. Either remove the installation in `/usr/bin`, `/usr/include/pgsql`, `/usr/share/pgsql` etc. or change your `PATH`:

```bash
> PATH=/usr/pgsql-13/bin:$PATH make clean
> PATH=/usr/pgsql-13/bin:$PATH make
> sudo -i
# PATH=/usr/pgsql-13/bin:$PATH make install
```

**Comment by virendercse** [comment]
I started with a new installation on rhel7 and getting below error in make now.

make ==>
oracle_fdw.c:11:33: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"


echo $PATH
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/postgres/.local/bin:/home/postgres/bin

which pg_config
/usr/bin/pg_config

cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"

[postgres@v2-inst oracle_fdw-2.4.0]$ psql --version
psql (PostgreSQL) 9.2.24
[postgres@v2-inst oracle_fdw-2.4.0]$ 
[postgres@v2-inst oracle_fdw-2.4.0]$ 
[postgres@v2-inst oracle_fdw-2.4.0]$ psql
psql (9.2.24, server 14.2)
WARNING: psql version 9.2, server version 14.0.
         Some psql features might not work.
Type "help" for help.

postgres=# 


I installed postgres14 and then devel like this ==>

sudo yum install -y postgresql14-server

sudo yum install -y postgresql-devel

Does postgresql-devel bringing up PG9 client and messing it up?

**Comment by virendercse** [comment]
I see another similar issue "https://github.com/laurenz/oracle_fdw/issues/459"

However i already installed devel package.

pg_config --pgxs
/usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk

**Comment by laurenz** [comment]
You have a different PostgreSQL installed, very likely the one from Redhat. Get rid of that.
The problem is that you are not building against the PostgreSQL v14 you installed, but against the 9.2 that you installed from Redhat, and the -devel package is not installed there.

Find out all your PostgreSQL packages:

```bash
rpm -qa | grep postgres
```

Then remove all those that are not from PGDG.

**Comment by virendercse** [comment]
Sorry for spoon feed asking as i spent too much time to get this work.


rpm -qa | grep postgres
postgresql14-server-14.2-1PGDG.rhel7.x86_64
postgresql14-14.2-1PGDG.rhel7.x86_64
postgresql-libs-9.2.24-7.el7_9.x86_64
postgresql-devel-9.2.24-7.el7_9.x86_64
postgresql14-libs-14.2-1PGDG.rhel7.x86_64
postgresql-9.2.24-7.el7_9.x86_64

After i removed 9.2 packages (pg_config, psql removed with this).

rpm -qa | grep postgres
postgresql14-server-14.2-1PGDG.rhel7.x86_64
postgresql14-14.2-1PGDG.rhel7.x86_64
postgresql14-libs-14.2-1PGDG.rhel7.x86_64

which pg_config
/usr/bin/which: no pg_config in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/postgres/.local/bin:/home/postgres/bin)
which psql
/usr/bin/which: no psql in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/postgres/.local/bin:/home/postgres/bin)

And now trying to devel 14 version having error

sudo yum install postgresql14-devel

Error: Package: postgresql14-devel-14.2-1PGDG.rhel7.x86_64 (pgdg14)
           Requires: llvm-toolset-7-clang >= 4.0.1

**Comment by laurenz** [comment]
A web search tells me that you should do this:

```bash
sudo yum-config-manager --enable rhel-server-rhscl-7-rpms
```

**Comment by virendercse** [comment]
I have two setup on rhel7 and centos7

RHEL7 ==>
Tried adding repo but still dont find software in repo

sudo yum-config-manager --enable rhel-server-rhscl-7-rpms

sudo yum install llvm-toolset-7.0  (tried with * as well)
No package llvm-toolset-7.0 available.
Error: Nothing to do

CENTOS ==?

installed llvm tool set:

sudo yum install centos-release-scl

then install pg13 devel

sudo yum install postgresql13-devel

Still pg_config is missing after above installation and hence oracle_fdw compilation is not working.

**Comment by laurenz** [comment]
Another web search: Have you looked at [this][1]?

 [1]: https://developers.redhat.com/HW/ClangLLVM-RHEL-7

**Comment by virendercse** [comment]
Thanks you laurenz@ for quick replies. 

I have gone through that link but for time being i thought to focus on oracle_fdw rather that going on OS side things.
I am not sure if i am missing something obvious  that extension worked for other people and not working for me. And hence i switched OS to Centos where i could install the package but still pg_config is missing.

I am looking for a way to install PG server + devel (pg_config) at same version.

Again i appreciate your quick response that could be a trivial issue.

(meantime taking a look at that rhel7 installation thing now)

**Comment by laurenz** [comment]
This starts being a moving target - you change the setup faster than I can reply...

For CentOS, you need to [activate the EPEL repository][1].

 [1]: https://www.tecmint.com/install-epel-repository-on-centos/

**Comment by virendercse** [comment]
thank you laurenz. 
I tried with PG-10 and it worked fine as it postgresql10-server and postgres10-devel satisfied all the dependencies for oracle_fdw.

**Comment by laurenz** [comment]
... but you shouldn't use such an old version.
