### ISSUE TITLE
OCIDateTimeFromText failed to convert parameter

### ISSUE THREAD

**Issue by benapi** [laurenz/oracle_fdw#52]
I'm triing to create a materialized view:

CREATE MATERIALIZED VIEW base_ext.fdw_pastel_mouvements_vmat_m AS 
 SELECT *  FROM base_ext.fdw_pastel_mouvements m
  WHERE date_part('year'::text, m.dt_fin) = date_part('year'::text, now()) AND date_part('month'::text, m.dt_fin) = date_part('month'::text, now())
WITH DATA;

 but i have this kind of error:

ERREUR:  error executing query: OCIDateTimeFromText failed to convert parameter
DETAIL:  ORA-01843: ce n'est pas un mois valide
********** Erreur **********

ERREUR: error executing query: OCIDateTimeFromText failed to convert parameter
État SQL :HV00L
Détail :ORA-01843: ce n'est pas un mois valide

After testing this:

CREATE MATERIALIZED VIEW base_ext.fdw_pastel_mouvements_vmat_m AS 
 SELECT *  FROM base_ext.fdw_pastel_mouvements m
  WHERE date_part('year'::text, m.dt_fin) = date_part('year'::text, now()) AND date_part('month'::text, m.dt_fin) = 2
WITH DATA;

i have the same issue...
On a Windows 2008R2 server (9.3) it works but not on a debian one (9.5 with instant client 12.1)

Did i forget anything in the configuration?

**Comment by laurenz** [comment]
Sorry for the late answer.

This looks like it might be the same issue as #48.
Could you try to pull the latest version from git? Commit 3fa9d985e6a31cde4099be5636f6827a1a758db7 might fix the problem.

**Comment by laurenz** [comment]
This is probably a duplicate.

**Comment by benapi** [comment]
Hi, sorry for the late answer too...

I updated today with the latest version but i have the same issue.
Last time, i created the foreign table manually. I tried to use FOREIGN SCHEMA and it worked.
I think some columns weren't properly declared.
But now, on a different table, i have the same issue

**Comment by laurenz** [comment]
I'll look into it when I get back to the office in about 10 days.

**Comment by laurenz** [comment]
Can you send me the SQL statements used to define that Oracle table and the PostgreSQL foreign server and table?

Can I get the result of

    SELECT oracle_diag('<foreign server name>');

Does a plan SELECT also fail or only a CREATE MATERIALIZED VIEW?
Can you find the row in the Oracle table that causes the problem (maybe by bisecting the result set)?

**Comment by benapi** [comment]
Hi, here is the result of oracle_diag:
"oracle_fdw 1.3.0, PostgreSQL 9.5.1, Oracle client 12.1.0.2.0, Oracle server 11.2.0.3.0"

The error occur when i make a query with a condition. the result is the same between a view and a materialized view.
When i make a view without conditions, it works

**Comment by laurenz** [comment]
Please tell me the table definitions in Oracle an PostgreSQL, the query that causes the error and the values in the Oracle table for which the error occurs.

**Comment by legrandlegrand** [comment]
I get a similar message
oracle_diag: oracle_fdw 1.4.0, PostgreSQL 9.5.1, Oracle client 10.2.0.5.0, Oracle server 11.2.0.2.0 

after  
IMPORT FOREIGN SCHEMA "SYS" LIMIT TO ("V_$SQLAREA") ...

column last_active_time 
is a date in Oracle, 
a timestamp without timezone in Postgres

following query fails with
**select ...
from fdw.v_$sqlarea sql
where 	sql.last_active_time > NOW()- '1 hour'::interval
**

org.postgresql.util.PSQLException: ERROR: error executing query: OCIDateTimeFromText failed to convert parameter
  Détail : ORA-01843: ce n'est pas un mois valide

but 
**select ...
from fdw.v_$sqlarea sql
where 	sql.last_active_time > now()::timestamp without time zone;**

works without error but without pushing down where condition to Oracle ...

Is there a way to pushdown SYSDATE equivalent fonction ?
Regards
PAscal

**Comment by laurenz** [comment]
I think I found and fixed the bug with commit 76cb66bd6a9eef9222c96ed3a0e73a35611d1166.

The problem was that when I fixed date/timestamp handling in 17c16074543992812ff55d7035904a3a5978183c I accidentally broke `now()`, `current_timestamp` and friends and parameterized queries with date or timestamp parameters.

Could you check if the [current version](https://github.com/laurenz/oracle_fdw/archive/master.zip) of oracle_fdw works for you?

**Comment by legrandlegrand** [comment]
arf, I'm a windows 7 user, and I'm not ready to compile oracle_fdw yet.
I'll wait for next release and tell you then ;o)

**Comment by laurenz** [comment]
If you tell me your PostgreSQL version, if you use 32-bit or 64-bit Windows and an e-mail address, I can send you an custom tailored binary.

**Comment by legrandlegrand** [comment]
postgres version 9.5 windows 7 x64
legrand_legrand at hotmail dot com

**Comment by legrandlegrand** [comment]
Thanks this bug seems corrected on my side

**Comment by laurenz** [comment]
I'll close this bug.
@benapi, please tell me if there are still problems.
