### ISSUE TITLE
Oracle table is having a column with User defined datatype

### ISSUE THREAD

**Issue by lord-kratos** [laurenz/oracle_fdw#523]
Hello,

So there's one table in Oracle which is having a user defined datatype column-
table abc(
   id number(20),
   name  my_name_type,
   address varchar2(100)
);

for that I've created a foreign table in postgres but when I am running select query, getting this error :- 

ERROR:  column "my_name_type" of foreign table "f_abc" cannot be converted to or from Oracle data type
SQL state: HV004

My requirement is to create a view in pg over this foreign table.
So is there any way ?

**Comment by laurenz** [comment]
Yes, that is simple. You define a view in Oracle that converts (casts) the custom type to a string, then define a foreign table on the view.

**Comment by lord-kratos** [comment]
Thank you for your suggestion, but we want to keep the column as User data type only, so is there anything else we can implement.

**Comment by laurenz** [comment]
Creating a view does not change the column, it is just a means to transport the data to PostgreSQL. You can then have a view on the foreign table in PostgreSQL that unwraps the string representation to a custom composite data type.

There is no chance to get this to "just work" without such tricks; for one, how should oracle_fdw guess the appropriate data type in PostgreSQL? I think the solution with views is a good one.

**Comment by lord-kratos** [comment]
Don't get me wrong this solution is good, but we don't want to create any new object in Oracle. That's why I wanted to know if we can do something  with the foreign tables or in  postgres only to catch the user data type. Thank you !

**Comment by laurenz** [comment]
A view is the only solution I can think of.
You are not the first person who has expressed a reluctance to create database objects in Oracle, and I don't understand it. After all, a view is nothing but an SQL statement with a name; it is not like it can cause any more problems in a database than the query itself can.

**Comment by laurenz** [comment]
To define an Oracle view that converts a user defined data type to a string, use something like

```
create or replace TYPE "TEST_NAME_ELEMENT_TYPE" AS OBJECT (
   name VARCHAR2(50),
   len NUMBER,
   used CHAR,
   part_type CHAR);
/

create or replace TYPE "TEST_NAME_TYPE" AS VARRAY(6) OF test_name_element_type;
/

CREATE TABLE test_name(id integer PRIMARY KEY, col test_name_type);

INSERT INTO test_name VALUES (
   1,
   test_name_type(
      test_name_element_type('name', 42, 'Y', 'X'),
      test_name_element_type('other', 11, 'N', 'Y')
   )
);

COMMIT;

SELECT listagg(
   '(' || t.name || ',' || t.len || ',' || t.used || ',' || t.part_type || ')',
   ','
) AS col
FROM test_name
   CROSS JOIN TABLE(test_name.col) t
GROUP BY id;
```

**Comment by lord-kratos** [comment]
Hi, this is working but how to select before and after columns to create the view,
table test_name(
 id integer,
name varchar2(40),
col test_name_type,
val varchar2(20)
 dob DATE
)

**Comment by laurenz** [comment]
Simply add the other columns:

```
SELECT t.id,
       t.name,
       listagg('(' || x.name || ',' || x.len || ',' || x.used || ',' || x.part_type || ')', ',') AS col,
       t.val,
       t.dob
FROM test_name t
   CROSS JOIN TABLE(t.col) x
GROUP BY t.id, t.name, t.val, t.dob;
```

But you are right, this is getting off topic.

**Comment by lord-kratos** [comment]
Thank you so much for your help. Really Appreciate it !
