### ISSUE TITLE
how install oracle_fdw in two verison cluster PG

### ISSUE THREAD

**Issue by nigun** [laurenz/oracle_fdw#524]
Hi Laurenz
I have Postgres 14 and work oracle_fdw  EXTENSION.
select oracle_diag() --> oracle_fdw 2.5.0devel, PostgreSQL 14.1 (Ubuntu 14.1-2.pgdg20.04+1), Oracle client 12.1.0.2.0, ORACLE_HOME=/usr/lib/oracle/12.1/client64/lib

I now install Postgres 13
copy files 
        /usr/share/postgresql/14/extension/oracle_fdw--1.0--1.1.sql -->/usr/share/postgresql/13/extension
        /usr/share/postgresql/14/extension/oracle_fdw--1.0--1.1.sq2 -->/usr/share/postgresql/13/extension
        /usr/share/postgresql/14/extension/oracle_fdw.control -->/usr/share/postgresql/13/extension
        /usr/share/postgresql/14/extension/oracle_fdw--1.2.sql -->/usr/share/postgresql/13/extension
and
        /usr/lib/postgresql/14/lib/oracle_fdw.so -->/usr/lib/postgresql/13/lib

in run CREATE EXTENSION oracle_fdw
i get error:
SQL Error [58P01]: ERROR: could not load library "/usr/lib/postgresql/13/lib/oracle_fdw.so": /usr/lib/postgresql/13/lib/oracle_fdw.so: undefined symbol: errstart_cold

How install two copy oracle_fdw ?
thx

**Comment by laurenz** [comment]
`errstart_cold` was introduced in PostgreSQL v14 with commit [913ec71d682e99](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=913ec71d682e99852cc188a7edbdccd02d42b4b3). That proves that you built oracle_fdw with PostgreSQL v14, but try to run it with an older version, as indeed your commands suggest.

That won't work. You have to build oracle_fdw with the same PostgreSQL version as you run it.

**Comment by nigun** [comment]
how build oracle_fdw for 13 version without deleting 14?

**Comment by laurenz** [comment]
Make sure that `pg_config` from PostgreSQL v13 is first on the `PATH`:

```bash
export PATH=/usr/lib/postgresql/13/bin:$PATH
make clean
make
```

**Comment by nigun** [comment]
thx
