### ISSUE TITLE
Yes, that is simple. You define a view in Oracle that converts (casts) the custom type to a string, then define a foreign table on the view.

### ISSUE THREAD

**Issue by lord-kratos** [laurenz/oracle_fdw#525]
Yes, that is simple. You define a view in Oracle that converts (casts) the custom type to a string, then define a foreign table on the view.

_Originally posted by @laurenz in https://github.com/laurenz/oracle_fdw/issues/523#issuecomment-1076334967_

Hi, I know this will be an off topic but I am unable to cast the User-Data type as string in oracle, Normal Cast() is not working, So If you have any Idea, can you please tell me how to do that, 

column name - test_name(test_name_type )

create or replace TYPE         "TEST_NAME_TYPE"   AS VARRAY(6) OF test_name_element_type

create or replace TYPE         "TEST_NAME_ELEMENT_TYPE"   AS OBJECT (
  name VARCHAR2(50),
  len  NUMBER,
  used CHAR,
  part_type CHAR)

row example - 
TEST_NAME
"TEST_NAME_TYPE(TEST_NAME_ELEMENT_TYPE('KRATOS', 7, NULL, 'S'), TEST_NAME_ELEMENT_TYPE('LORD', 5, NULL, 'F'))"

Any help will be appreciated. Thank you

**Comment by laurenz** [comment]
I have unlocked the original question, and I will answer there.
