### ISSUE TITLE
Long Query

### ISSUE THREAD

**Issue by oballi** [laurenz/oracle_fdw#526]
Hi,

I am using **PostgreSQL version 14.2.** On the Oracle side, I am using the **Oracle Database 21c Express Edition** version.

I have 6 million tables in Oracle database. I managed to import it with oracle_fdw.

My query on the Oracle side; S**ELECT COUNT(*) FROM TB1**. takes 2 seconds. It takes 15-20 seconds on the Postgresql side. 
There is a **15 second** difference. 

Is this a problem? Or is it normal? :)

**Comment by laurenz** [comment]
Usually I would expect better performance, but we need more data.
Try running the same Query with `sqlplus` from the PostgreSQL machine and see if the time is the same, that would help figuring out if the problem is in oracle_fdw or not.
Another consideration is if there are any `BLOB` or `CLOB` columns in the table. It is a known deficiency that Oracle prefetching does not work when such columns are involved, so there would be a round trip per row, which could explain the bad performance.

**Comment by oballi** [comment]
Thanks for the quick response.

My oracle table has no blob or clob fields.

I ran the Count(*) query. It brings it in 2 seconds.

**describe table1;**
![describe_table1](https://user-images.githubusercontent.com/43172199/162700356-fce7f0e6-1407-4f04-9a99-c5e87b946165.PNG)

COUNT; 
![COUNT](https://user-images.githubusercontent.com/43172199/162700657-cb7ceab2-7e80-48d5-ad67-81507b111e08.PNG)

**Comment by laurenz** [comment]
Then I don't know what causes the difference.
Can you provide the output of `EXPLAIN (ANALYZE, VERBOSE, BUFFERS)` for the query against the foreign table?

**Comment by oballi** [comment]
**1-) EXPLAIN (ANALYZE, BUFFERS)**
```
# EXPLAIN (ANALYZE, BUFFERS) select count(*) from omr.table1;

 Aggregate  (cost=20002.50..20002.51 rows=1 width=8) (actual time=16439.118..16439.120 rows=1 loops=1)
   ->  Foreign Scan on table1  (cost=10000.00..20000.00 rows=1000 width=0) (actual time=1.975..15945.829 rows=6125548 loops=1)
         Oracle query: SELECT /*126dc0cab5d688eadf3fda67cdce1117*/ '1' FROM "OMR"."table1" r1
 Planning Time: 1.691 ms
 Execution Time: 16439.243 ms
```


**2-) EXPLAIN (VERBOSE)**
```
# EXPLAIN (VERBOSE) select count(*) from omr.table1;

ERG=# EXPLAIN (VERBOSE) select count(*) from omr.table1;
ERROR:  no SELECT privilege on V$SQL in the remote database
DETAIL:  ORA-00942
```
_Not : My user on the oracle side is ready only. For this reason, it cannot run the VERBOSE command._

**Comment by laurenz** [comment]
Ah, I see. I did not pay attention. There is a `count(*)` in the query.
Then it all makes sense. oracle_fdw cannot push down aggregate functions to Oracle, so it will actually run a `SELECT '1' FROM tab` on Oracle and count the rows in PostgreSQL, which of course performs much worse.
If that query is important for you, you could create an Oracle view for it and reference that with a foreign table.
Alternatively, you could define a foreign table with `OPTIONS (table '(SELECT count(*) AS count FROM omr."table1")`.
