### ISSUE TITLE
ORA-01856 Error

### ISSUE THREAD

**Issue by oballi** [laurenz/oracle_fdw#527]
Hello,

There is a view named osso in the Oracle database. I can read only access this database. I have a column named order_date in the table. _(data type varchar - DD-MON-RR HH:MI:SSxFF AM)_

When exporting this table to postgresql, I want to export the format as '**DD/MM/YYYY HH24:MI:SSxFX**' but I get the **ORA-01856** error.

Can you help me?

Note : I looked at #287 issue but I couldn't understand it :/

_EXPLAIN select * from orders;_
```
Foreign Scan on orders  (cost=10000.00..20000.00 rows=1000 width=88)
"  Oracle query: SELECT /*af619d11ce9b671bd092042f31ec1911*/ r1.""order_date "" FROM (
"
SELECT TO_TIMESTAMP(TO_CHAR(TO_TIMESTAMP(order_date , 'DD-MON-RR HH:MI:SSxFF AM'),'DD/MM/YYYY HH24:MI:SS')) AS order_date  FROM OMR.OSSO
WHERE order_date IS NOT NULL ) r1
```
_oracle_diag_
`oracle_fdw 2.4.0, PostgreSQL 14.2, Oracle client 21.3.0.0.0, Oracle server 18.0.0.0.0`

Not2: By the way, I can run this query via sqlplus.

maybe you would like;

```
NLS_LANGUAGE	TURKISH
NLS_TERRITORY	TURKEY
NLS_CURRENCY	?
NLS_ISO_CURRENCY	TURKEY
NLS_NUMERIC_CHARACTERS	.,
NLS_CALENDAR	GREGORIAN
NLS_DATE_FORMAT	YYYY-MM-DD HH24:MI:SS BC
NLS_DATE_LANGUAGE	AMERICAN
NLS_SORT	TURKISH
NLS_TIME_FORMAT	HH24:MI:SSXFF
NLS_TIMESTAMP_FORMAT	YYYY-MM-DD HH24:MI:SS.FF9 BC
NLS_TIME_TZ_FORMAT	HH24:MI:SSXFF TZR
NLS_TIMESTAMP_TZ_FORMAT	YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC
NLS_DUAL_CURRENCY	TL
NLS_COMP	BINARY
NLS_LENGTH_SEMANTICS	BYTE
NLS_NCHAR_CONV_EXCP	FALSE
```

**Comment by laurenz** [comment]
That query uses Oracle's `to_timestamp` without a format string, which means that it relies on the current setting of `NLS_TIMESTAMP_FORMAT`. But as you observe, oracle_fdw changes that setting, so the string does not match the format and you get an error message.

The solution is to change the view or foreign table definition (not sure what you are using) to use an explicit format string with `to_timestamp`.

**Comment by oballi** [comment]
This is how I solve the problem;

`TO_TIMESTAMP(order_date ,'DD-MON-RR HH:MI:SSxFF AM'`
