### ISSUE TITLE
PostgreSQL 12.9 experience Segmentation fault and instance enter recovery  when call a store procedure (have oracle_fdw function))

### ISSUE THREAD

**Issue by xuzhiyu01** [laurenz/oracle_fdw#528]
PG 12.9 
Oracle_FDW extension 1.1 
Centos 7.5 16G Memory.  4 core CPU. 

The postgreSQL instance crash when call a store procedure which used Oracle_FDW function. 
When this error occur.  The database will enter recovery mode. This mode will impact others application access database. 
This problem never found on Pg11.5 +Oracle_FDW extension 1.1. I upragde to pg12.9 from pg11.5. Then reinstall oracle_fdw extension. Then it's happen unexpected when call store procedure. 

I attach some file for you refernece. 
1: The pg logs.    logs_pg12.oracle_fdw.tar.gz
2: store procedure ddl.   store_procedure_ddl.txt
3: show all;       logs_pg12.oracle_fdw.tar.gz
4: extension list   logs_pg12.oracle_fdw.tar.gz 

-----------------------------------------------------------------------------------------------------------
2022-04-15 13:00:01.220 CST,,,
[store_procedure_ddl.txt](https://github.com/laurenz/oracle_fdw/files/8504109/store_procedure_ddl.txt)
13254,,62484fca.33c6,161,,2022-04-02 21:29:46 CST,,0,LOG,00000,"server process (PID 28476) was terminated by signal 11: Segmentation fault","Failed process was running: call smartds.prc_data_sync($1, $2, $3)",,,,,,,,""
2022-04-15 13:00:01.220 CST,,,13254,,62484fca.33c6,162,,2022-04-02 21:29:46 CST,,0,LOG,00000,"terminating any other active server processes",,,,,,,,,""
2022-04-15 13:00:01.220 CST,"a_appconnect","aps_tst",28478,"10.122.95.32:13749",6258fbd0.6f3e,3,"CALL",2022-04-15 13:00:00 CST,14/15,54779,WARNING,57P02,"terminating connection because of crash of another server process","The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.","In a moment you should be able to reconnect to the database and repeat your command.",,,"SQL statement ""insert into ds_mo_basic (^M
                                                        so_no, so_line_no, mo_no, mo_mtm,^M
                                                        mo_mtm_desr, mo_created_time, mo_qty,^M
                                                        mo_type, mo_shipto_country, mo_shipto_subgeo,^M
                                                        mo_comment, mo_plant, mo_release_date, bg, sys_created_by,^M
                                                        sys_last_modified_by, sys_last_modified_date,^M
                                                        so_shipping_type,^M
                                                        ext_product_group, product_hierarchy, mo_shipto_geo,^M
                                                        mo_ecc_status, mo_prodfamily, ds_group, ds_workspace,^M
                                                        application_id, tenant_id, sys_status, mo_ds_status,^M
                                                        level2_ds_group, routing^M
                                        ) ^M
                                        SELECT ^M
                                                        x.vbeln, x.posnr, x.aufnr, x.matnr,^M
                                                        mpi.maktx, x.erdat, x.gamng,^M
                                   
[logs_pg12.oracle_fdw.tar.gz](https://github.com/laurenz/oracle_fdw/files/8504099/logs_pg12.oracle_fdw.tar.gz)
                     x.zmotype, x.zcountry, x.subgeo,^M
                                                        x.zcomment, x.werks, x.ftrmi, mp.bg, v_sys_created_by,^M
                                                        v_sys_last_modified_by, v_sys_last_modified_date,^M
                                                        ies.vsart, iema.extwg, iema.prodh, x.geo, ^M
                                                        iems.stat, mpi.prodfamily,mpi.ds_group, v_ds_workspace,^M
                                                        v_application_id, v_tenant_id, v_sys_status, v_mo_ds_status_open,^M
                                                        mpi.level2_ds_group, ieb.ktext^M
                                        FROM in_ecc_mo x^M
                                        INNER join mst_plant mp on mp.plant = x.werks ^M

....................................................
2022-04-15 22:00:01.278 CST,"a_appconnect","aps_tst",16506,"10.122.95.32:65049",62596c65.407a,3,"idle",2022-04-15 21:00:21 CST,4/0,0,WARNING,57P02,"terminating connection because of crash of another server process","The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.","In a moment you should be able to reconnect to the database and repeat your command.",,,,,,,"PostgreSQL JDBC Driver"
2022-04-15 22:00:01.286 CST,,,16484,,62596c52.4064,1,,2022-04-15 21:00:02 CST,1/0,0,WARNING,57P02,"terminating connection because of crash of another server process","The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.","In a moment you should be able to reconnect to the database and repeat your command.",,,,,,,""
2022-04-15 22:00:01.286 CST,,,13254,,62484fca.33c6,208,,2022-04-02 21:29:46 CST,,0,LOG,00000,"archiver process (PID 16485) exited with exit code 2",,,,,,,,,""

-----------------------------------------------------------------------------------------------------------

**Comment by laurenz** [comment]
I assume that you are running on Windows.
Please tell me the version of oracle_fdw you are using. 1.1 is only the version of the extension. You need to run `SELECT oracle_diag();` to get the actual version of oracle_fdw.

If I read your report right, it is an insert into a foreign table `ds_mo_basic` that causes the problem. Correct?
Can I get the `CREATE FOREIGN TABLE` for that foreign table in PostgreSQL and the `CREATE TABLE` for the underlying Oracle table?

Other relevant information that I'd like to have:
- How exactly did you upgrade PostgreSQL?
- How exactly did you reinstall oracle_fdw?
- Did you use the Windows binaries that I built? Which one exactly did you use?
- Which Oracle client is installed? What is its version? Did you modify the Oracle installation in any way when you upgraded PostgreSQL?

**Comment by xuzhiyu01** [comment]
Hi  Laurenz

   I use a Linux Centos 7.5 server. 
   the store procedure will query foreign table from oracle . when match the condition. 
   Then execute insert or delete local Postgres table . 
   This table is local PostgreSQL table.  I attach it for your reference. PG_Tables.ddl.txt
   and an example about foreign table and Oracle table.
[PG_Tables.ddl.txt](https://github.com/laurenz/oracle_fdw/files/8514508/PG_Tables.ddl.txt)
[Oracle_forign_table_--example.txt](https://github.com/laurenz/oracle_fdw/files/8514578/Oracle_forign_table_--example.txt)
[Oracle_table_ddl.txt](https://github.com/laurenz/oracle_fdw/files/8514579/Oracle_table_ddl.txt)


The version is :
----------------------------------------------------------------------------------------------------------------
postgres=# SELECT oracle_diag();
                                            oracle_diag
----------------------------------------------------------------------------------------------------
 oracle_fdw 2.2.0, PostgreSQL 12.9, Oracle client 21.3.0.0.0, ORACLE_HOME=/opt/oracle/instantclient
(1 row)


How exactly did you upgrade PostgreSQL?
I dump PG data by pg_dump on PG 11.5. 
I install PG 12.9 again by binary file with same directory than PG11.5.   postgresql-12.9.tar.gz. 
copy oracle_fdw-ORACLE_FDW_2_2_0.zip file to the 12.9 extension folder. 
make and make install ORACLE_FDW. successfully. The extension could work well. Oracle table could access. 
Then use pg_restore to recovery backup pg_dump file. 

How exactly did you reinstall oracle_fdw?
Just use same command .make and make install 
Did you use the Windows binaries that I built? Which one exactly did you use?

Which Oracle client is installed? What is its version? Did you modify the Oracle installation in any way when you upgraded PostgreSQL? .No I didn't change it. 

Postgres  "bin"  "share "  "lib"  "include "  path never changed . 

Oracle client never changed during my upgrade PG. 
instantclient-basic-linux.x64-21.3.0.0.0.zip
instantclient-sdk-linux.x64-21.3.0.0.0.zip
instantclient-sqlplus-linux.x64-21.3.0.0.0.zip

----------------------------------------------------------------------------------------------------------------


opt/oracle/instantclient
[postgres@slt3iyyxf2s instantclient]$ ls -la
total 248768
drwxr-xr-x 4 root root      4096 Dec 22 16:55 .
drwxr-xr-x 4 root root      4096 Dec 22 16:55 ..
-rwxr-xr-x 1 root root     42144 Jul 27  2021 adrci
-rw-r--r-- 1 root root      5780 Jul 27  2021 BASIC_LICENSE
-rw-r--r-- 1 root root      1634 Jul 27  2021 BASIC_README
-rwxr-xr-x 1 root root     59528 Jul 27  2021 genezi
-rw-r--r-- 1 root root       342 Jul 27  2021 glogin.sql
lrwxrwxrwx 1 root root        21 Dec 22 16:55 libclntshcore.so -> libclntshcore.so.21.1
lrwxrwxrwx 1 root root        21 Dec 22 16:55 libclntshcore.so.12.1 -> libclntshcore.so.21.1
lrwxrwxrwx 1 root root        21 Dec 22 16:55 libclntshcore.so.18.1 -> libclntshcore.so.21.1
lrwxrwxrwx 1 root root        21 Dec 22 16:55 libclntshcore.so.19.1 -> libclntshcore.so.21.1
lrwxrwxrwx 1 root root        21 Dec 22 16:55 libclntshcore.so.20.1 -> libclntshcore.so.21.1
-rwxr-xr-x 1 root root   8108520 Jul 27  2021 libclntshcore.so.21.1
lrwxrwxrwx 1 root root        17 Dec 22 16:55 libclntsh.so -> libclntsh.so.21.1
lrwxrwxrwx 1 root root        17 Dec 22 16:55 libclntsh.so.10.1 -> libclntsh.so.21.1
lrwxrwxrwx 1 root root        17 Dec 22 16:55 libclntsh.so.11.1 -> libclntsh.so.21.1
lrwxrwxrwx 1 root root        17 Dec 22 16:55 libclntsh.so.12.1 -> libclntsh.so.21.1
lrwxrwxrwx 1 root root        17 Dec 22 16:55 libclntsh.so.18.1 -> libclntsh.so.21.1
lrwxrwxrwx 1 root root        17 Dec 22 16:55 libclntsh.so.19.1 -> libclntsh.so.21.1
lrwxrwxrwx 1 root root        17 Dec 22 16:55 libclntsh.so.20.1 -> libclntsh.so.21.1
-rwxr-xr-x 1 root root  83460712 Jul 27  2021 libclntsh.so.21.1
-rwxr-xr-x 1 root root   7118328 Jul 27  2021 libnnz21.so
lrwxrwxrwx 1 root root        15 Dec 22 16:55 libocci.so -> libocci.so.21.1
lrwxrwxrwx 1 root root        15 Dec 22 16:55 libocci.so.10.1 -> libocci.so.21.1
lrwxrwxrwx 1 root root        15 Dec 22 16:55 libocci.so.11.1 -> libocci.so.21.1
lrwxrwxrwx 1 root root        15 Dec 22 16:55 libocci.so.12.1 -> libocci.so.21.1
lrwxrwxrwx 1 root root        15 Dec 22 16:55 libocci.so.18.1 -> libocci.so.21.1
lrwxrwxrwx 1 root root        15 Dec 22 16:55 libocci.so.19.1 -> libocci.so.21.1
lrwxrwxrwx 1 root root        15 Dec 22 16:55 libocci.so.20.1 -> libocci.so.21.1
-rwxr-xr-x 1 root root   2374192 Jul 27  2021 libocci.so.21.1
-rwxr-xr-x 1 root root 142713392 Jul 27  2021 libociei.so
-r-xr-xr-x 1 root root    153584 Jul 27  2021 libocijdbc21.so
-rwxr-xr-x 1 root root    116104 Jul 27  2021 liboramysql.so
-rwxr-xr-x 1 root root   1710024 Jul 27  2021 libsqlplusic.so
-rwxr-xr-x 1 root root   1613888 Jul 27  2021 libsqlplus.so
drwxr-xr-x 3 root root        19 Jul 27  2021 network
-rw-r--r-- 1 root root   5053911 Jul 27  2021 ojdbc8.jar
drwxr-xr-x 5 root root        79 Jul 27  2021 sdk
-rw-r--r-- 1 root root      5780 Jul 27  2021 SDK_LICENSE
-rw-rw-r-- 1 root root      1628 Jul 27  2021 SDK_README
-rwxr-xr-x 1 root root     25104 Jul 27  2021 sqlplus
-rw-r--r-- 1 root root      5780 Jul 27  2021 SQLPLUS_LICENSE
-rw-r--r-- 1 root root      1642 Jul 27  2021 SQLPLUS_README
-rw-r--r-- 1 root root   1790635 Jul 27  2021 ucp.jar
-rwxr-xr-x 1 root root    235904 Jul 27  2021 uidrvci
-rw-r--r-- 1 root root     74603 Jul 27  2021 xstreams.jar

**Comment by laurenz** [comment]
Thanks for the additional information.

First, you are running an old version of oracle_fdw. Please try with [the latest version](https://github.com/laurenz/oracle_fdw/archive/refs/heads/master.zip) and see if you get the same behavior.

Second, you'll have to debug this further. Find out which statement in the procedure causes the problem.

[Collect a stack trace from the crash](https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Linux/BSD#Getting_a_trace_from_a_reproducibly_crashing_backend), that would be valuable information.

**Comment by xuzhiyu01** [comment]
Thanks for your update. I will try latest version.

**Comment by laurenz** [comment]
Any news on this?
