### ISSUE TITLE
when add option "use_remote_estimate", got the following error. (postgreSQL 14, Oracle 11.2.0.4 client)

### ISSUE THREAD

**Issue by MasonChen-ces** [laurenz/oracle_fdw#529]
mydb=# ALTER SERVER oracle_srv OPTIONS (add use_remote_estimate 'on');
2022-05-05 22:21:24.652 CST [11727] ERROR:  invalid option "use_remote_estimate"
2022-05-05 22:21:24.652 CST [11727] HINT:  Valid options in this context are: dbserver, isolation_level, nchar
2022-05-05 22:21:24.652 CST [11727] STATEMENT:  ALTER SERVER oracle_srv OPTIONS (add use_remote_estimate 'on');
ERROR:  invalid option "use_remote_estimate"
HINT:  Valid options in this context are: dbserver, isolation_level, nchar

**Comment by laurenz** [comment]
The option `use_remote_estimate` is specific to postgres_fdw and won't work with foreign servers for other foreign data wrappers.
oracle_fdw never uses a remote estimate. There was such an option in an older version, but Oracle's estimates turn out to be pretty useless (for PostgreSQL).

Run `ANALYZE` on the foreign table, then PostgreSQL will collect statistics on the Oracle table and should be able to come up with a decent query plan, if that is possible at all.

**Comment by MasonChen-ces** [comment]
thanks a lot
