### ISSUE TITLE
Option readonly for IMPORT FOREIGN SCHEMA

### ISSUE THREAD

**Issue by jgoux** [laurenz/oracle_fdw#53]
Hi,
would it be possible to add the option "readonly" to the `IMPORT FOREIGN SCHEMA` command ?
I'd like to bulk import multiple tables, but only in "readonly" mode.

As the option is available for `CREATE FOREIGN TABLE`, does it make sense ?

**Comment by laurenz** [comment]
Interesting idea, I will consider it!

You can also handle the situation by granting only SELECT privileges on the foreign tables.

**Comment by laurenz** [comment]
I have just committed 8ddd4fde27101998c91cda665efc57203ef36690 which adds an option "readonly".
Can you give it a try?

**Comment by jgoux** [comment]
Sorry for the late answer, it works great !
Thanks again :+1:
