### ISSUE TITLE
Change configuration of server

### ISSUE THREAD

**Issue by lux7789** [laurenz/oracle_fdw#530]
Hi !

I executed this command: create server oracle foreign data wrapper oracle_fdw options (dbserver '192.168.0.16:1521/fribourg' ); Unfortunetly, I have this result when trying to do the select statement.

postgres=# select * from vm_horaire_etudiant;
ERROR:  connection for foreign table "vm_horaire_etudiant" cannot be established
DETAIL:  ORA-12514: TNS : le processus d'écoute ne connaît pas actuellement le service demandé dans le descripteur de connexion

And SELECT oracle_diag('oracle'); give this:

ERROR:  cannot connect to foreign Oracle server
DETAIL:  ORA-12514: TNS : le processus d'écoute ne connaît pas actuellement le service demandé dans le descripteur de connexion

I guess that I should change the dbserver like this *(dbserver  192.168.0.16:1521/fribourg.equinoxemis.ch). But what's the command to do this change. Something like alter server oracle ...

Thanks !

Luc CAYA

**Comment by laurenz** [comment]
That would be

    ALTER SERVER oracle OPTIONS (SET dbserver '192.168.0.16:1521/fribourg.equinoxemis.ch');

I'd test the connection string with sqlplus to make sure it is correct.

**Comment by lux7789** [comment]
That's it ! Thanks ! Work perfectly !
