### ISSUE TITLE
How to upgrade oracle_fdw extension ?

### ISSUE THREAD

**Issue by xuzhiyu01** [laurenz/oracle_fdw#531]
Hi Lausenz:

  I have a question about upgrade extension .
  Currently. My PG env running on oracle_fdw 2.2.0.
  If i want to upgrade to latest version oracle_fdw 2.5.0devel. How to upgrade extension  to latest version ?
  Need i re-create all foreign tables ? 

```
postgres=# SELECT oracle_diag();
                                            oracle_diag
----------------------------------------------------------------------------------------------------
 oracle_fdw 2.2.0, PostgreSQL 12.9, Oracle client 21.3.0.0.0, ORACLE_HOME=/opt/oracle/instantclient
(1 row)


aps_uat=# SELECT oracle_diag();
                                               oracle_diag
---------------------------------------------------------------------------------------------------------
 oracle_fdw 2.5.0devel, PostgreSQL 12.9, Oracle client 21.3.0.0.0, ORACLE_HOME=/opt/oracle/instantclient
(1 row)
```

**Comment by laurenz** [comment]
Release 2.2.0 had the same extension version as current git HEAD: 1.1
You can see that from the `default_version` in [`oracle_fdw.control`](https://github.com/laurenz/oracle_fdw/blob/ORACLE_FDW_2_2_0/oracle_fdw.control).

If the extension version stays the same, there is no need to run

    ALTER EXTENSION oracle_fdw UPDATE;

and all you have to do is to replace `oracle_fdw.so` with the new software, typically by running `make install`.
Terminate all old database sessions that use oracle_fdw before updating the shared library. New database sessions will start using the new version right away.

**Comment by laurenz** [comment]
Does that answer your question?
