### ISSUE TITLE
Deletion requires a primary key column too strictly

### ISSUE THREAD

**Issue by zhangjfg** [laurenz/oracle_fdw#535]
Can be used directly:  delete from tableName where colName='20220612'

**Comment by zhangjfg** [comment]
Or provide : truncate table tableName

**Comment by zhangjfg** [comment]
find the way: SELECT oracle_execute('server',' delete from  tableName where colName=''202205'' ');

thanks

**Comment by laurenz** [comment]
There is no support for `TRUNCATE` from oracle_fdw, but both `DELETE` run on the foreign table as well as `DELETE` or `TRUNCATE` run via `oracle_execute` will work  fine.
Note that for `DELETE` on the foreign table to work, you must identify the primary key columns with the option `key 'on'`.
