### ISSUE TITLE
Oracle FDW performance degraded after the amazon aws moved from US to europe

### ISSUE THREAD

**Issue by friendarora** [laurenz/oracle_fdw#536]
Hi Team,

We were running an application where we were communicating between oracle and Postgres using oracle FDW
both these databases were on Amazon AWS cloud (US region)

For some business reason we moved the Postgres AWS from US region to Europe region

After this change the performance of all the SQL where foreign tables were used reduced by almost 5 times

Kindly let us know what should we do for to minimize this network change

**Comment by laurenz** [comment]
Try to assess the network lag by measuring the duration of a trivial SQL statement via `oracle_execute`.
If the problem is the network latency, there is nothing you can do except run fewer statements.
