### ISSUE TITLE
Oracle 19.15 support and onwards

### ISSUE THREAD

**Issue by portnov** [laurenz/oracle_fdw#538]
1. Please add support for Oracle instant client 19.15. If you wish, I could even make a PR for this, similar to #522 :)
2. Maybe it would be better to try and figure it out which version is installed automatically, instead of hardcoding the list of supported versions? Something like `ls /usr/lib/oracle/*/client64/lib` ?

**Comment by laurenz** [comment]
I cannot think of a way to detect that automatically... do you have an idea?

**Comment by laurenz** [comment]
Thanks!
I'll have to play with that in a quiet hour, if nobody else sends a patch first (hint, hint).

**Comment by chrullrich** [comment]
As you comm^Whint hint.

**Comment by laurenz** [comment]
Thanks a lot! This should avoid the problem in the future.
