### ISSUE TITLE
Having difficulties with Oracle geometry type - can't convert 

### ISSUE THREAD

**Issue by markhooper99** [laurenz/oracle_fdw#539]
We are trying to select records from an oracle_fdw table created for an Oracle table that has an MDSYS.SDO_GEOMETRY datatype.
When we try to select from the oracle_fdw table we get an error ...

```
[local]:markh@testhou=# desc ora2pg_fdw_import.junk
                      Foreign table "ora2pg_fdw_import.junk"
 Column |           Type            | Collation | Nullable | Default | FDW options
--------+---------------------------+-----------+----------+---------+-------------
 fld1   | character varying(10)     |           |          |         |
 fld2   | character varying(20)     |           |          |         |
 fld3   | geometry(geometry,3857) |           |          |         |
Server: mark
FDW options: (schema 'MARKH', "table" 'JUNK', readonly 'true')

[local]:markh@testhou=# select * from ora2pg_fdw_import.junk;
ERROR:  column "fld3" of foreign table "junk" cannot be converted to or from Oracle data type
```

The table on the Oracle side looks like this ..
```
MARKH@HKAP> desc junk;
 Name                                                                    Null?    Type
 ----------------------------------------------------------------------- -------- ------------------------------------------------
 FLD1                                                                             VARCHAR2(10)
 FLD2                                                                             VARCHAR2(20)
 FLD3                                                                             MDSYS.SDO_GEOMETRY

```
There are 47 records in the Oracle junk table and each has the exact same VALID linestring geometry.
Note, even with the JUNK.FLD3 column empty on the Oracle side we get the same error.

Versions... 
```
[local]:markh@testhou=# select oracle_diag();
                                               oracle_diag
----------------------------------------------------------------------------------------------------------
 oracle_fdw 2.4.0, PostgreSQL 14.4.0, Oracle client 12.2.0.1.0, ORACLE_HOME=/usr/lib/oracle/12.2/client64

```

What are we doing wrong here ?

**Comment by markhooper99** [comment]
Additional information... we did the same thing in a Postgres 13 database and it appears to work fine.  
Is there a compatibility problem with Postgres 14 ?

**Comment by markhooper99** [comment]
Additional information... we did the same thing in an EDB Postgres 13 database and it does NOT work.

```
marktest=# select oracle_diag();
                                               oracle_diag
----------------------------------------------------------------------------------------------------------
 oracle_fdw 2.4.0, PostgreSQL 13.5.9, Oracle client 12.2.0.1.0, ORACLE_HOME=/usr/lib/oracle/12.2/client64
```

**Comment by laurenz** [comment]
The most likely explanation would be that you didn't install the PostGIS extension in the database where you get the error.

If that is not the case: I have just pushed a commit that adds more information to the error message. Could you upgrade oracle_fdw to the latest development version and show which error you get now?

**Comment by markhooper99** [comment]
We most definitely have PostGIS installed.
Will try the latest commit and see what additional information it provides, thanks.

**Comment by markhooper99** [comment]
I've downloaded the latest commit and successfully performed a 'make' and a 'make install'.
When I try to update the oracle_fdw extension I get this ...
```
devcal=# alter extension oracle_fdw update;
NOTICE:  version "1.2" of extension "oracle_fdw" is already installed
ALTER EXTENSION

```
I'm not sure this actually updated anything - thoughts ?

**Comment by markhooper99** [comment]
Ok, I've set up a test with an oracle_fdw table called junk3_fdw - it points to an Oracle table containing: varchar2, date, mdsys.sdo_geometry and clob data types.
Here's what happens when I query the oracle_fdw table ...

```
-- seis_line_id and seis_set_type are varchar2 data types / row_created_date is a date data type
[local]:markh@devcal=# select seis_line_id, seis_set_type, row_created_date from junk3_fdw limit 5;
 seis_line_id | seis_set_type |  row_created_date
--------------+---------------+--------------------
 1346195837   | SEIS_LINE     | 22-MAY-09 08:30:29
 1346195899   | SEIS_LINE     | 22-MAY-09 08:30:31
 1346195958   | SEIS_LINE     | 22-MAY-09 08:30:35
 1346196020   | SEIS_LINE     | 22-MAY-09 08:30:38
 1346196082   | SEIS_LINE     | 22-MAY-09 08:30:41
(5 rows)

-- k_survey_header is a clob data type in Oracle and Postgres
[local]:markh@devcal=#* select seis_line_id, seis_set_type, k_survey_header from junk3_fdw limit 5;
ERROR:  column "k_survey_header" (14709) of foreign table "junk3_fdw" cannot be converted to or from Oracle data type (15)
[local]:markh@devcal=#! rollback;
ROLLBACK

-- k_geometry_line is an mdsys.sdo_geometry data type in Oracle and geometry(geomtry,3857) in Postgres
[local]:markh@devcal=# select seis_line_id, seis_set_type, k_geometry_line from junk3_fdw limit 5;
ERROR:  column "k_geometry_line" (65658316) of foreign table "junk3_fdw" cannot be converted to or from Oracle data type (19)
[local]:markh@devcal=#! rollback;
ROLLBACK
```

**Comment by laurenz** [comment]
Thanks you for the research; you upgraded oracle_fdw correctly (a new extension version is not required if only the code changes).

The problem with `clob` is clear: there is no such data type in PostgreSQL, so it must be a data type you created yourself (that is also obvious by its high object ID). oracle_fdw only supports the PostgreSQL data types listed in the README.

The problem with `geometry` is less clear, so let's investigate that. Please set `log_min_messages` to `debug1`, start a new session and run a query that involves an oracle_fdw foreign table. You should get a log message as follows:

```none
oracle_fdw: PostGIS is installed, GEOMETRYOID = ...
```

Please tell me if you get such a message and what object ID is reported.

**Comment by markhooper99** [comment]
The CLOB data type is there because we are running EDB Postgres Advanced Server (v14).

I set log_min_messages and tried the query again - this is what got captured in the PG server log ...

```
2022-08-17 07:47:29.618 MDT [44195] markh@devcal/psql/[local] DEBUG:  oracle_fdw: plan foreign table scan
2022-08-17 07:47:29.618 MDT [44195] markh@devcal/psql/[local] DEBUG:  oracle_fdw: set NLS_LANG=AMERICAN_AMERICA.AL32UTF8
2022-08-17 07:47:29.623 MDT [44195] markh@devcal/psql/[local] DEBUG:  oracle_fdw: remote query is: SELECT /*a677854883b202a1*/ r1."SEIS_LINE_ID", r1."SEIS_SET_TYPE", r1."K_GEOMETRY_LINE" FROM "DMASS38_4"."SEIS_LINE" r1 FETCH FIRST 5 ROWS ONLY
2022-08-17 07:47:29.623 MDT [44195] markh@devcal/psql/[local] ERROR:  column "k_geometry_line" (65658316) of foreign table "junk3_fdw" cannot be converted to or from Oracle data type (19)
2022-08-17 07:47:29.623 MDT [44195] markh@devcal/psql/[local] STATEMENT:  select seis_line_id, seis_set_type, k_geometry_line from junk3_fdw limit 5;
```

**Comment by laurenz** [comment]
Additional types defined by a fork of PostgreSQL like `clob` are not supported. Use `text` instead. If you have to, you can define a view on top of the foreign table that casts the `text` column to a different type like `clob`.

**Comment by markhooper99** [comment]
Answers to your questions...

```
(S)cal-db3:markh:devcal> psql
psql (14.5.0, server 14.3.0)
Type "help" for help.

[local]:markh@devcal=# SELECT oid, typnamespace::regnamespace
devcal-# FROM pg_type
devcal-# WHERE typname = 'geometry';
   oid    | typnamespace
----------+--------------
 65658316 | public
(1 row)

[local]:markh@devcal=#* SELECT extnamespace::regnamespace
devcal-*# FROM pg_extension
devcal-*# WHERE extname = 'postgis';
 extnamespace
--------------
 public
(1 row)
```

**Comment by laurenz** [comment]
Then the explanation must be that somehow oracle_fdw cannot identify the `geometry` data type when it starts.

It does that by looking for a `geometry_recv` function with an argument of data type `internal`.

So the following should result in 65658316:

```sql
SELECT prorettype
FROM pg_proc
WHERE proname = 'geometry_recv'
  AND proargtypes = ARRAY['internal'::regtype]::oidvector;
```

Can you test that?

**Comment by markhooper99** [comment]
Test ...

```
cal-db3:enterprisedb:devcal> psql -U markh
psql (14.5.0, server 14.3.0)
Type "help" for help.

devcal=# SELECT prorettype
devcal-# FROM pg_proc
devcal-# WHERE proname = 'geometry_recv'
devcal-#   AND proargtypes = ARRAY['internal'::regtype]::oidvector;
 prorettype
------------
   65658316
(1 row)
```

**Comment by laurenz** [comment]
Then I am pretty out of ideas, because that's what [the code that initializes PostGIS](https://github.com/laurenz/oracle_fdw/blob/master/oracle_fdw.c#L7084) does. The only difference is that rather than querying the tables directly, it uses the catalog cache of the database session.

Some straws to grasp at:
- Perhaps there is something strange with the catalog cache. Try deleting the `pg_internal.init` file in the database subdirectory in the `base` subdirectory of the data directory, then start a new session and see if you get a different result.
- Perhaps there is some weirdness in EDB's fork. Could you try with normal PostgreSQL?

**Comment by laurenz** [comment]
Did you get any further insights into this?

**Comment by markhooper99** [comment]
Unfortunately, no - there's just no support for oracle_fdw from EnterpriseDB

**Comment by laurenz** [comment]
Thanks for the feedback, even if it is bad news.
Funny, though, that EDB has [a tutorial on setting up oracle_fdw][edb1] and [explicitly describes ora_migrator][edb2] (which uses oracle_fdw) as tool that can be used with their fork.
Anyway, I'll close the ticket.

 [edb1]: https://www.enterprisedb.com/postgres-tutorials/using-foreign-data-wrappers-access-remote-postgresql-and-oracle-databases
 [edb2]: https://www.enterprisedb.com/postgres-tutorials/how-convert-oracle-postgresql-online
