### ISSUE TITLE
MAKE lib linking issues

### ISSUE THREAD

**Issue by robert1029** [laurenz/oracle_fdw#54]
I suspect my issue is more about my Oracle environment than oracle_fdw but I'm posting it here in the hopes of getting a tip.  

My environment:   Mac OS X 10.10 (Yosemite), Postgres 9.4, Oracle Instantclient_64 11.2, oracle_fdw_1_3_0

Running 'make', my first issue was that oci.h couldn't be found -- solved by downloading Oracle's SDK.

Running 'make' again, my second issue was a failure to link 'lclntsh':  
  
    ld: library not found for -lclntsh
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [oracle_fdw.so] Error 1

I tried sym-linking like this:
    libclntsh.dylib -> libclntsh.dylib.11.1  

And got this... 

ld: warning: ignoring file /Applications/oracle/product/instantclient_64/11.2.0.4.0/lib/libclntsh.dylib, file was built for i386 which is not the architecture being linked (x86_64): /Applications/oracle/product/instantclient_64/11.2.0.4.0/lib/libclntsh.dylib
Undefined symbols for architecture x86_64:
  "_OCIAttrGet", referenced from:
      _oracleGetSession in oracle_utils.o
      _closeSession in oracle_utils.o
      _oracleDescribe in oracle_utils.o
      _oracleExecuteQuery in oracle_utils.o
  "_OCIAttrSet", referenced from:

... etc. etc. for all the 64 bit libraries ora_fdw is expecting.

Just to make sure I covered my bases, I also installed the Oracle 64 bit SQL Developers app for its libraries, with no luck.

Having oracle_fdw installed will make my world a better place.  I'll really appreciate any help getting there.  Thanks in advance.

Robert

**Comment by laurenz** [comment]
The README says:

> You need to install Oracle's C header files as well (SDK package for Instant
> Client).

So that would have saved you from your first problem.
I had no mention of your second problem, but it is frequent enough that I updated the documentation:

> PostgreSQL and Oracle need to have the same architecture, for example you
> cannot have 32-bit software for the one and 64-bit software for the other.

Now that you have installed 64-bit Oracle, everything should work.
What is the error message you get?
I recommend that you uninstall the 32-bit Oracle Instant Client before trying, as it is all too easy to get confused with different Oracle installations on the same maching.

**Comment by robert1029** [comment]
Thanks for the reply.  

I don't have any 32-bit Oracle Instantclient installed.  As far as I know, there's never been a 32-bit Oracle IC on this machine.

Here are my lib path variables currently (I've tried them with "/lib" appended too), followed by the complete error dump.

robert:oracle_fdw-ORACLE_FDW_1_3_0$ echo $LD_LIBRARY_PATH 
/usr/local/mysql-5.6.25-osx10.8-x86_64/lib:/Applications/oracle/product/instantclient_64/11.2.0.4.0
robert:oracle_fdw-ORACLE_FDW_1_3_0$ echo $DYLD_LIBRARY_PATH 
/Applications/oracle/product/instantclient_64/11.2.0.4.0
robert:oracle_fdw-ORACLE_FDW_1_3_0$ pwd
/Users/502441933/Work/Reporting/FDW/Wrappers/oracle_fdw-ORACLE_FDW_1_3_0
robert:oracle_fdw-ORACLE_FDW_1_3_0$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument  -mmacosx-version-min=10.7  -bundle -multiply_defined suppress -o oracle_fdw.so oracle_fdw.o oracle_utils.o oracle_gis.o -L/Applications/Postgres.app/Contents/Versions/9.4/lib -L/Applications/Postgres.app/Contents/Versions/9.4/lib  -L/Applications/Postgres.app/Contents/Versions/9.4/lib -Wl,-dead_strip_dylibs   -L/Applications/oracle/product/instantclient_64/11.2.0.4.0 -L/Applications/oracle/product/instantclient_64/11.2.0.4.0/bin -L/Applications/oracle/product/instantclient_64/11.2.0.4.0/lib -lclntsh -L/usr/lib/oracle/12.1/client/lib -L/usr/lib/oracle/12.1/client64/lib -L/usr/lib/oracle/11.2/client/lib -L/usr/lib/oracle/11.2/client64/lib -L/usr/lib/oracle/11.1/client/lib -L/usr/lib/oracle/11.1/client64/lib -L/usr/lib/oracle/10.2.0.5/client/lib -L/usr/lib/oracle/10.2.0.5/client64/lib -L/usr/lib/oracle/10.2.0.4/client/lib -L/usr/lib/oracle/10.2.0.4/client64/lib -L/usr/lib/oracle/10.2.0.3/client/lib -L/usr/lib/oracle/10.2.0.3/client64/lib -bundle_loader /Applications/Postgres.app/Contents/Versions/9.4/bin/postgres
ld: warning: directory not found for option '-L/usr/lib/oracle/12.1/client/lib'
ld: warning: directory not found for option '-L/usr/lib/oracle/12.1/client64/lib'
ld: warning: directory not found for option '-L/usr/lib/oracle/11.2/client/lib'
ld: warning: directory not found for option '-L/usr/lib/oracle/11.2/client64/lib'
ld: warning: directory not found for option '-L/usr/lib/oracle/11.1/client/lib'
ld: warning: directory not found for option '-L/usr/lib/oracle/11.1/client64/lib'
ld: warning: directory not found for option '-L/usr/lib/oracle/10.2.0.5/client/lib'
ld: warning: directory not found for option '-L/usr/lib/oracle/10.2.0.5/client64/lib'
ld: warning: directory not found for option '-L/usr/lib/oracle/10.2.0.4/client/lib'
ld: warning: directory not found for option '-L/usr/lib/oracle/10.2.0.4/client64/lib'
ld: warning: directory not found for option '-L/usr/lib/oracle/10.2.0.3/client/lib'
ld: warning: directory not found for option '-L/usr/lib/oracle/10.2.0.3/client64/lib'
ld: library not found for -lclntsh
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [oracle_fdw.so] Error 1

Thanks.
R

**Comment by laurenz** [comment]
Ok, thanks for the feedback.
