### ISSUE TITLE
Serious time zone issue

### ISSUE THREAD

**Issue by JamesInform** [laurenz/oracle_fdw#542]
Hi Laurenz.

I am using oracle_fdw with Oracle Instant Client to access an Oracle server.

In my Oracle table there is a field "date_created" of type "timestamp with local time zone".

My PostgreSQL is running on a Linux host with time zone "Europe/Berlin". The PostgreSQL client's session time zone is also "Europe/Berlin".

Now when I query the remote Oracle table I get:

`select date_created, date_created at time zone 'europe/berlin' as date_created_at_berlin from remotetable`
![image](https://user-images.githubusercontent.com/38714600/185627170-7a5df372-e1c0-4afd-aad5-5d0cd332659b.png)

Now I set my pg time zone to 'Indian/Christmas':
`set timezone = 'Indian/Christmas'`

Now when I query the remote Oracle table I get:
`select date_created, date_created at time zone 'europe/berlin' as date_created_at_berlin from remotetable`
![image](https://user-images.githubusercontent.com/38714600/185627442-308151b1-5ae9-4000-be7a-6f80ffbeec55.png)

So the time is shifted 5 hours.

I have read through your documentation but not found anything about this issue. To me is seems that the host's time zone must match pg's session time zone. Otherwise I get wrong results. 

The oracle client seem to convert the timestamp to the host's time zone, and then handle this like an oracle date to oracle_fdw which in turn just takes this timestamp and thinks, it is in pg's session time zone.

Is this a known issue that you are aware of, or is there any setting that makes the issue disappear?

Cheers,
James

**Comment by laurenz** [comment]
Yes, that seems buggy.

**Comment by laurenz** [comment]
I have pushed a tentative fix.
Could you download [the code](https://github.com/laurenz/oracle_fdw/archive/refs/heads/local-time-zone.zip) and see if that fixes the problem for you?

If yes, I'll add regression tests and merge it.

**Comment by JamesInform** [comment]
Hi Laurenz

Thanks for your "ultra-fast" solution.

It works fine! Now the timestamptz is delivered correctly as expected.

Great work!

James
