### ISSUE TITLE
Current master Makefile likely incorrect

### ISSUE THREAD

**Issue by raqua** [laurenz/oracle_fdw#543]
I have Saltstack automation to install PG and Oracle FDW automatically in VM for me cloning current master branch. This worked fine about 2 weeks ago and fails for me now. I have not changed anything in the meantime. 

When I run "make", I get:
Makefile:9: *** missing separator.  Stop. 

I have googled for solution and it seems like there is some issue with Makefile. Unfortunately I have no skills to find what is the issue. 

Tag ORACLE_FDW_2_4_0 builds without any issue there.

**Comment by laurenz** [comment]
This must be caused by commit f81e8ea5ffc90471ffde79ecdfbbdf87c50f4dbe or 9b80bc7c713508035277fb2fde55d419bde2a502.

Apparently, the error message is not very specific. Can you give me some more information?

- Which `make` you are using (perhaps `make -v` or `make --version`)?
- Can you give me the result of `/usr/lib/oracle` and `/usr/include/oracle`?
- Which operating system are you using?

@chrullrich, do you have a clue?

**Comment by chrullrich** [comment]
Not immediately. @raqua, what is your make version (`make -v`)?

`!=` was added to GNU make in 2011, so that's probably not the reason.

**Comment by raqua** [comment]
It's CentOS 7 machine, so Linux. 

```
[vagrant@test-postgres ~]$ make -v 
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
root@test-postgres-134:/home/vagrant 
# ls /usr/lib/oracle
19.15

root@test-postgres-134:/home/vagrant 
# ls /usr/include/oracle
19.15
```

**Comment by chrullrich** [comment]
From: Paul Smith
    Subject: GNU make 3.82 is now available
    Date: Wed, 28 Jul 2010 02:50:41 -0400
                      ^^^^

Ummmm ... do you think there might be a more recent make version/package for your system?

**Comment by raqua** [comment]
Unfortunately not. At least not in the standard repos:

``` 
root@test-postgres-134:/home/vagrant 
# yum update make 
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.cvut.cz
 * centos-sclo-rh: ftp.cvut.cz
 * epel: epel.uni-sofia.bg
 * extras: ftp.cvut.cz
 * updates: ftp.cvut.cz
No packages marked for update
```

**Comment by chrullrich** [comment]
Try replacing these two lines in the Makefile

    FIND_INCLUDE != ls -d /usr/include/oracle/*/client64 /usr/include/oracle/*/client 2>/dev/null | tr -d \$
    FIND_LIBDIRS != ls -d /usr/lib/oracle/*/client64/lib /usr/lib/oracle/*/client/lib 2>/dev/null | tr -d \$

with these two, please:

    FIND_INCLUDE := $(wildcard /usr/include/oracle/*/client64 /usr/include/oracle/*/client)
    FIND_LIBDIRS := $(wildcard /usr/lib/oracle/*/client64/lib /usr/lib/oracle/*/client/lib)

If that does not work either, try these:

    FIND_INCLUDE := $(shell ls -d /usr/include/oracle/*/client64 /usr/include/oracle/*/client 2>/dev/null | tr -d \$)
    FIND_LIBDIRS := $(shell ls -d /usr/lib/oracle/*/client64/lib /usr/lib/oracle/*/client/lib 2>/dev/null | tr -d \$)

**Comment by raqua** [comment]
@chrullrich The first replacement did the trick and it worked.

**Comment by laurenz** [comment]
Thanks for the report, and thanks @chrullrich for the patch.
