### ISSUE TITLE
Exception handling when executing an ORACLE PL/SQL Procedure

### ISSUE THREAD

**Issue by NasNasingud** [laurenz/oracle_fdw#547]
Hi,

we use the oracle_execute function to call a stored PL/SQL procedure in a remote ORACLE database.

The ORACLE procedure does not return any values. If something goes wrong within the ORACLE DB, a custom error is raised (ORA-20999).

The oracle_execute function is called within a PL/pgSQL function. It works quite well and is fast. 

When I run the PL/pgSQL-Function without any exception handling and an error is raised on the ORACLE side, I get the expected result on the command line:

> ERROR:  error executing statement: OCIStmtExecute failed to execute query
> DETAIL:  ORA-20999: Custom error message
> ORA-06512: in Function Name, Row 1234
> ORA-06512: in Row 1
> CONTEXT:  SQL statement "SELECT oracle_execute(server, stmt)"

Now, I wanted to catch and handle this exception. But when I change my PL/pgSQL code to:

```
BEGIN
  PERFORM oracle_execute(server, stmt);  
EXCEPTION  
  WHEN OTHERS THEN  
    RAISE NOTICE 'Exception';  
END;
```

...I get the following error when executing the function:

> WARNING:  AbortSubTransaction while in ABORT state
> WARNING:  did not find subXID 5630 in MyProc
> ERROR:  error rolling back to savepoint: OCIStmtExecute failed on ROLLBACK TO SAVEPOINT
> DETAIL:  ORA-01086: Savepoint 'S2' Never Established In Session Or Session Invalid
> CONTEXT:  PL/pgSQL function functionname line 144 during exception cleanup

It seems as if the EXCEPTION-Block disturbes the transaction management of oracle_fdw. Is this something that I can avoid? Or does anyone has an idea how I can nevertheless implement an exception handling?
Thank you!

**Comment by laurenz** [comment]
This looks like a bug, but I cannot reproduce it:

```
DO $$BEGIN
   -- this causes a primary key violation
   PERFORM oracle_execute('oracle', 'INSERT INTO emp VALUES (7839)');
EXCEPTION WHEN OTHERS THEN
   RAISE NOTICE 'Exception';
END;$$;

NOTICE:  Exception
DO
```

Can you provide a complete reproducible test case for me?

**Comment by NasNasingud** [comment]
Yes. I have figured out how to build a reproducible test case. However, it seems that there is more involved in this issue than only a simple oracle_execute call.

On the ORACLE side:
```
CREATE TABLE TEST_TAB (COL1 NUMBER NOT NULL);
```
and
```
PROCEDURE postgresql_fdw_test(input IN NUMBER) IS              
  BEGIN
     INSERT INTO TEST_TAB (COL1) VALUES (input);
     COMMIT;
  END;
```

Then, on the PostgreSQL side, create a foreign table:
```
CREATE FOREIGN TABLE ft_test_tab (
    col1 integer NOT NULL
)
SERVER oracle
OPTIONS (schema 'SYSADM', table 'TEST_TAB');
```

Now execute the following statement:
```
DO $$
DECLARE
    testval INT;
BEGIN
    -- Database query (seems to be important for producing the error)
    SELECT t.col1
    INTO   testval
    FROM   ft_test_tab t
    LIMIT  1;

    -- PLSQL procedure call
    PERFORM oracle_execute('oracle', 'CALL postgresql_fdw_test(234)');

    -- Throw some error
    SELECT 1 / 0 INTO testval;

EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Error noticed: % %', SQLERRM, SQLSTATE;
END; $$;
```

This produces the error. If I change something (e.g. remove the COMMIT statement on the ORACLE side, remove the SELECT statement on the PostgreSQL side or remove the exception block) then everything works fine.

**Comment by laurenz** [comment]
Thanks for the reproducer, that really helps. However, this is no bug, this is pilot error.

oracle_fdw does its own transaction management. For example, if you start a transaction in PostgreSQL, oracle_fdw will also start a transaction in Oracle.
Now the way that PL/pgSQL implements exception handlers is by starting a subtransaction when you enter that block. This also starts a subtransaction in Oracle, by setting a savepoint. If you enter the exception handler, the subtransaction is rolled back. That is the `ROLLBACK TO SAVEPOINT` that you see in the error message.

The problem is that you break this by calling a procedure that executes `COMMIT`. This ends the current transaction and all subtransactions in it, which causes the error you get. This is actually described in the README:

> Be careful when using this function, since it might disturb the transaction
> management of oracle_fdw.  Remember that running a DDL statement in Oracle
> will issue an implicit COMMIT.
> You are best advised to use this function outside of multi-statement
> transactions.

`oracle_execute()` is sort of a dangerous function, as it operates outside the normal FDW API. Take care when using it.

**Comment by NasNasingud** [comment]
OK, thanks for the detailed explanation, it really helps understanding the underlying problem! I was aware of the part in the README, however I could not figure out how that interacted with the PL/pgSQL exception handler.

So, I will try to remove all COMMIT-Statements from all ORACLE procedures and try again.

Thank you!
