### ISSUE TITLE
ERROR:  cannot connect to foreign Oracle server. Getting this while copying data from oracle to postgres by using ors2pg tool.

### ISSUE THREAD

**Issue by chetan2211** [laurenz/oracle_fdw#548]
Hi @laurenz 
with respective below error which is in link 
https://github.com/laurenz/oracle_fdw/issues/321#issue-447183453

I get the following error in postgresql database

student=# SELECT oracle_diag('orcl');
ERROR:  cannot connect to foreign Oracle server
DETAIL:  ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

Please let me know if you know any solution.
Thank you in advance.

**Comment by laurenz** [comment]
That is an Oracle connection problem. You reached the Listener and requested a certain service, but that service does not exist.
Run

```bash
lsnrctl status
```

on the Oracle database server to get a list of known services.

**Comment by laurenz** [comment]
Is there anything more I can help you with?
The problem really is outside of oracle_fdw.

**Comment by chetan2211** [comment]
Hello @laurenz ,
Thanks for reply and sorry for my late reply.
I had done new fresh setup so the issue is resolved .
And once again thank you so much for helping me.
