### ISSUE TITLE
Support for ExecForeignBatchInsert

### ISSUE THREAD

**Issue by njesp** [laurenz/oracle_fdw#549]
Hello 

We love the oracle_fdw data wrapper. However, it works best for reading data, inserts of large amounts are a bit slow. 

Is there support for the new ExecForeignBatchInsert feature i Postgres 14, or is it planned for a future release of oracle_fdw?

Regards Niels Jespersen

**Comment by laurenz** [comment]
I have no plans to add support for batch insert, but I am not opposed to the idea.
If someone feels inspired to write a patch for it, great!
