### ISSUE TITLE
ORA-0600 error 

### ISSUE THREAD

**Issue by bastetmickey** [laurenz/oracle_fdw#552]
Hello,
We encounter difficulties with ORACLE_FDW, when we make queries with a LIMIT 1 constraint;
We get an ORA-0600 error, when we run the query
Owner user of the selected views.
Have you encountered this type of error and if so do you have a solution to avoid this type of incident

Thanks

**Comment by laurenz** [comment]
An ORA-00600 error is a crash of the Oracle database server, so it is a bug in Oracle (unless there is data corruption in the Oracle database). There is nothing I can do about that, except try to help you figure out what triggers the bug and how to avoid the crash.

What is the result of `EXPLAIN SELECT ...` for the query to the foreign table? That will give you the statement that is executed on Oracle. Try to run that and see if you can reproduce the crash that way. Try to modify the query, and see if you can detect a pattern when the database crashes.

I don't have a support contract with Oracle, but you should open sa service request and search the knowledge base for related bug reports.

**Comment by bastetmickey** [comment]
thank you 
I contact support ORACLE

**Comment by laurenz** [comment]
I'll close the ticket for inactivity. Feel free to reopen it if you have new information.
