### ISSUE TITLE
oracle_fdw does not work in version 15

### ISSUE THREAD

**Issue by koppaline** [laurenz/oracle_fdw#553]
13th October 2022: PostgreSQL 15 Released! oracle_fdw does not work in version 15 :-(

**Comment by laurenz** [comment]
Sure it does. You have to use the latest development version for that.
I should build a release soon.

**Comment by lucius-the** [comment]
A short update: tried compiling from current master -> it works on PostgreSQL 15.
Didn't do much with it so far, but getting data with a few simple queries from Oracle - works, thank you ;)

**Comment by coleman-rik** [comment]
@laurenz Thanks, I look forward to the code for pg15 under Linux.  

@lucius-the In the meanwhile, I'll try compiling the current code against 15 for Linux and see how far that gets me.

**Comment by laurenz** [comment]
I have released version 2.5.0. Thanks for pushing me.
