### ISSUE TITLE
Installation issue on pg 10.3

### ISSUE THREAD

**Issue by a-nikishova** [laurenz/oracle_fdw#554]
Hello Laurenz,

I'm not going to report an issue. I do know that i'm duplicating [https://github.com/laurenz/oracle_fdw/issues/272](Issue 272). That's my problem. I'm not able to execute make. Also I'm not able to upgrade posrgresql db. So I just want to ask you an advice. Are there another ways to connect Postgres to Oracle db?

**Comment by laurenz** [comment]
No, there are not. If you cannot upgrade software, you cannot get rid of bugs. Sorry.
Note that all that is required is a *minor* update, basically just applying a bug fix. That is never a technical problem.
