### ISSUE TITLE
Performance too slow when joining 3-4 tables from system monitoring views

### ISSUE THREAD

**Issue by AlexandreHGuerra** [laurenz/oracle_fdw#556]
Hi   
Im running the following queries with joins, and they are really slow when joining. I would like to ask for advice whats should i do to improve performance

I was trying to set up views for them, but its not everytime ill be able to build views. Im looking towards the links below, but any advice would be great

https://www.ongres.com/blog/boost-query-performance-using-fdw-with-minimal-changes/
https://www.cybertec-postgresql.com/en/foreign-data-wrapper-for-postgresql-performance-tuning/

```
select
	s.sid as sid,
	s."serial#",
	s.username,
	s.STATUS,
	s.STATE,
	tr.XIDSQN,
	tr.START_SCN,
	tr.PHY_IO,
	tr.LOG_IO,
	tr.START_TIME,
	(
	select
		"sequence#"
	from
		ora_sys_prod.v_$archived_log alog
	where
		tr.start_scn between alog."first_change#" and alog."next_change#") archiloginicio,
       (
	select
		"sequence#"
	from
		ora_sys_prod.v_$log loga
	where
		tr.start_scn between loga."first_change#" and loga."next_change#" ) loginicio,
	round( l.ctime / 60, 2 ) lock_time_in_minutes,
	ob.owner object_owner,
	ob.object_name,
	ob.object_type object_type
       , l.lmode
       , l.type from
	ora_sys_prod.v_$transaction tr
left join ora_sys_prod.v_$session s on
	upper(encode(tr.ADDR, 'hex')) = s.TADDR
inner join ora_sys_prod.v_$lock l on
	l.sid = s.sid
left join ora_sys_prod.dba_objects ob on
	ob.object_id = l.id1
order by
	s.STATUS ,
	SID desc;
```

**Comment by AlexandreHGuerra** [comment]
is there a way to push the filtering in a orderly way beginning from the smaller/filtered tables to speed up this at least?  the better would be to process on server side, like a compiled query.....

**Comment by AlexandreHGuerra** [comment]
allright... going this way

table (required)

The Oracle table name. This name must be written exactly as it occurs in Oracle's system catalog, so normally consist of uppercase letters only.

To define a foreign table based on an arbitrary Oracle query, set this option to the query enclosed in parentheses, e.g.

OPTIONS (table '(SELECT col FROM tab WHERE val = ''string'')')

**Comment by laurenz** [comment]
I cannot help with the original query with the little information I have. I don't even know which tables are foreign tables, nor do I know the data types involved. `EXPLAIN (ANALYZE, BUFFERS)` output would be most helpful. Even more helpful would be if you could reduce the query to the minimal required to demonstrate the problem, rather than throwing a wad of SQL at me.

There is a simple way to get `IMPORT FOREIGN SCHEMA` to import a query: define a view based on that query in Oracle.

**Comment by AlexandreHGuerra** [comment]
Pardon me. i've discarded one of the queries and made the main one maore simple
will collect the data and post it, but right now using the table query option mentioned above , wich is working reasonably well. Thanks laurenz about providing this functionality into oracle_fdw

**Comment by laurenz** [comment]
Thank you, I'll wait for updates.

**Comment by laurenz** [comment]
Still waiting...

**Comment by AlexandreHGuerra** [comment]
Please close. I was able to create views at the source database, and it went fine enough
