### ISSUE TITLE
how to specify a a pgpass file or public key file instead of creating a user mapping with password 

### ISSUE THREAD

**Issue by AlexandreHGuerra** [laurenz/oracle_fdw#557]
Hi, im looking towards creating a private/public key pair to use when oracle_fdw is looking to access Oracle
Create user mapping with plain password is not the best way to do this for us. Is there any guidance we could look for regarding this?

Thanks!

**Comment by AlexandreHGuerra** [comment]
Just found this link, but how does this apply for oracle_fdw, as the final connectity is done to Oracle, and not Postgres?
https://stackoverflow.com/questions/69099907/postgresql-foreign-data-wrapper-user-mapping-password

**Comment by laurenz** [comment]
Yes, that is possible, and the README describes it (withoit giving much detail):

> User mapping options
> --------------------
>
> - **user** (required)
>
>   The Oracle user name for the session.  
>   Set this to an empty string for *external authentication* if you don't
>   want to store Oracle credentials in the PostgreSQL database (one simple way
>   is to use an *external password store*).

`.pgpass` is a file specific to the PostgreSQL client; here we need something similar for the Oracle client. The Stackoverflow link also points to a question about postgres_fdw and does not apply here. Oracle is more <strike>advanced</strike>complicated in this respect.

[Here][oradoc] is a link to the Oracle documentation on creating a password store, and you'll have to configure Oracle client to use it. You can test it with a connection like this (using the appropriate connection string):

```bash
sqlplus /@connectionstring
```

There are two issues, #94 and #162 (unresolved), about people that had problems with that, they may help you if you run into trouble.

 [oradoc]: https://docs.oracle.com/en/database/oracle/oracle-database/21/dbseg/configuring-authentication.html#GUID-803496D2-19C7-4F02-94EC-C13EDD8FB17B

**Comment by AlexandreHGuerra** [comment]
Found an iteresting link where to find the necessary oracle tools
https://ogobrecht.com/posts/2020-07-29-how-to-use-mkstore-and-orapki-with-oracle-instant-client/
https://andriydmytrenko.wordpress.com/2013/07/01/using-the-secure-external-password-store-with-instant-client/

**Comment by AlexandreHGuerra** [comment]
https://asktom.oracle.com/pls/apex/asktom.search?tag=which-current-client-package-does-formally-deliver-the-tools-mkstore-and-orapki&p_session=103064047229711

**Comment by laurenz** [comment]
Thanks for all the links. Did you get it to work? Can we close the issue?

**Comment by AlexandreHGuerra** [comment]
Please close. Thanks so much for the assistance :)  Apprecited

Em qui., 24 de nov. de 2022 às 05:29, Laurenz Albe ***@***.***>
escreveu:
