### ISSUE TITLE
How to write query - select * from table where trunc(created_timestamp) = '16-DEC-2022' for foreign table

### ISSUE THREAD

**Issue by syedmujtaba88** [laurenz/oracle_fdw#562]

**Comment by syedmujtaba88** [comment]
Thank you for your swift response. yes, the column is of data type timestamp. the query is mentioned works perfectly fine on oracle side, so i was wondering if any such provision is available while working with oracle_fdw. since there is no such function i guess i can work with to_char function to work with my requirement.

**Comment by laurenz** [comment]
You cannot run an Oracle query in PostgreSQL. When you run a query against a PostgreSQL foreign table, you have to use PostgreSQL SQL syntax and PostgreSQL functions.

**Comment by syedmujtaba88** [comment]
Thank you, Appreciated

**Comment by syedmujtaba88** [comment]
Hello @laurenz,

updated query: select * from table_name where date_trunc('day', transaction_date)::date = '2022-12-14' and status = 'Failed';

i tried with postgres functions as mentioned and query returned with error below. Oracle table has a CLOB column which i created in Postgres as text data type.
SQL Error [HV00L]: ERROR: error fetching result: OCILobOpen failed to open LOB
  Detail: ORA-22293: LOB already opened in the same transaction

data is returned if i select columns other than CLOB data type using the mentioned query.

Also note if i use simple query without the mentioned date functions all columns are properly returned.

**Comment by laurenz** [comment]
Now that is more interesting.
Can you send me the result of `EXPLAIN (VERBOSE) SELECT ...` for that query?
Also, I would like to know the `CREATE TABLE` statement in Oracle and the `CREATE FOREIGN TABLE` statement in PostgreSQL.
I'll have to be able to reproduce that in order to understand what is going on.
Also, can you send me the result of `SELECT oracle_diag('server_name');`, where `server_name` is the name of the foreign server?

**Comment by syedmujtaba88** [comment]
Hello @laurenz,

my user does not have access on v$sql on oracle side so getting details for explain verbose will be challenging. if it is really necessary, please let me know i will have to work with my DBA for necessary privileges.

below are the remaining requested details,

oracle table:

`CREATE TABLE CSSPRD.CRM_DEACTIVATION_TRANSACTIONS (
    REQUEST_ID NUMBER,
    SIM VARCHAR2(100),
    MSISDN VARCHAR2(20),
    TRANS_DATE TIMESTAMP,
    PROCESSOR_ID VARCHAR2(50) DEFAULT null,
    STATUS NUMBER,
    SERIAL2 VARCHAR2(100),
    MSISDN2 VARCHAR2(20),
    SERIAL3 VARCHAR2(100),
    MSISDN3 VARCHAR2(20),
    CREATED DATE DEFAULT (sysdate),
    UPDATED DATE,
    RETRY_COUNT NUMBER DEFAULT (0),
    STATUS_REASON CLOB,
    REQUEST_TYPE VARCHAR2(50),
    LAST_ACTIVITY_DATE TIMESTAMP,
    SYSTEM_NAME VARCHAR2(200),
    APPLICATION_NAME VARCHAR2(200)
);`

Foreign table on postgres:
`
CREATE FOREIGN TABLE drsdev.CSSPRD_CRM_DEACTIVATION_TRANSACTIONS(
    REQUEST_ID int8 options (key 'true'),
    SIM VARCHAR(100),  
    MSISDN VARCHAR(20),
    TRANS_DATE TIMESTAMP,  
    PROCESSOR_ID VARCHAR(50),
    STATUS numeric,
    SERIAL2 VARCHAR(100),
    MSISDN2 VARCHAR(20),
    SERIAL3 VARCHAR(100),
    MSISDN3 VARCHAR(20),
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,  
    RETRY_COUNT numeric,
    STATUS_REASON text,
    REQUEST_TYPE VARCHAR(50),
    LAST_ACTIVITY_DATE timestamp,
    SYSTEM_NAME VARCHAR(200),
    APPLICATION_NAME VARCHAR(200)
) SERVER CSSPRD OPTIONS (SCHEMA 'CSS' , TABLE 'CRM_DEACTIVATION_TRANSACTIONS');`

oracle diag output: `oracle_fdw 2.5.0, PostgreSQL 15.1, Oracle client 19.17.0.0.0, Oracle server 19.0.0.0.0`

**Comment by laurenz** [comment]
Thanks. I created such an Oracle table, inserted a row (making sure that `status_reason` was not NULL) and ran

    SELECT *
    FROM CSSPRD_CRM_DEACTIVATION_TRANSACTIONS
    WHERE date_trunc('day', trans_date)::date = '2022-12-14'
      AND status = 42;

It worked just fine.

Best would be if you could provide a series of SQL statements that I can execute one after the other to reproduce the problem. The `EXPLAIN` output is not necessarily required for that. But perhaps it shows something strange that could explain the problem.

**Comment by syedmujtaba88** [comment]
can you try these different values in status reason column, each line represents separate row.
`Completed
CSS-005: You are not allowed to perform this operation
CSS-002: Database technical error, please contact system administrator.
CSS-107: MSISDN is invalid! 
SIM and MSISDN IS NULL
CSS-052: The data entered is too large`

**Comment by laurenz** [comment]
I will try after Jan 9, when I am back from vacation.

**Comment by laurenz** [comment]
I tried with those values, and it worked fine.

Perhaps this has a connection to #565:

- Could you try [the latest development version](https://github.com/laurenz/oracle_fdw/archive/refs/heads/master.zip)?

- Does the error vanish if you change the remote server like this:

      ALTER SERVER cssprd OPTIONS (DROP nchar);
