### ISSUE TITLE
LOB form mismatch

### ISSUE THREAD

**Issue by jopoly** [laurenz/oracle_fdw#565]
Hi,

I detect a bug related to LOB data type and I would like to share the solution.
Are you interested?

**Procedure steps:**
Step 1: Create a table in remote server
```
CREATE TABLE test."T 1" (
  c1 NUMBER(5) PRIMARY KEY,
  c2 NUMBER(5),
  c3 CLOB
)
```
Step 2: Create a foreign table
```
CREATE FOREIGN TABLE ft1 (
  c1 int OPTIONS (key 'yes') NOT NULL ,
  c2 int NOT NULL,
  c3 text
) SERVER oracle_srv OPTIONS (table 'T 1');
```
Step 3: Execute command
`INSERT INTO ft1 (c1, c2, c3) VALUES (1101, 201, 'aaa'), (1102, 202, 'bbb'), (1103, 203, 'ccc') RETURNING c1, c2, c3;`

Result:
```
ERROR:  error fetching result: OCILobRead failed to read LOB chunk
DETAIL:  ORA-24806: LOB form mismatch
```

**Root cause:**
When binding TEXT value (column c3), FDW does not convert TEXT to LOB form, FDW also does not bind value as type of SQLT_CLOB. So, after executing and getting result, FDW cannot convert it to LOB form.

**Solution:**
In the function oracleExecuteQuery, after OCIBindByName is called the value_type of column c3 (IN/OUT value) will be output to SQLT_CLOB.
We add the condition not to set national character set like this (file: oracle_utils).
```
if (session->have_nchar
    && (value_type != SQLT_CLOB)        <--- add condition
    && checkerr(
        OCIAttrSet((void *)param->bindh, OCI_HTYPE_BIND, (void *)&nchar, 0,
            OCI_ATTR_CHARSET_FORM, session->envp->errhp),
        (dvoid *)session->envp->errhp, OCI_HTYPE_ERROR) != OCI_SUCCESS)
{
    oracleError_d(FDW_UNABLE_TO_CREATE_EXECUTION,
        "error executing query: OCIAttrSet failed to set charset form on bind parameter",
        oraMessage);
}
```

**Comment by laurenz** [comment]
I will have a look at your issues when I return from vacation after Jan 9 2023.

**Comment by laurenz** [comment]
Thanks for the report and the fix!
