### ISSUE TITLE
Support trigger before updating data

### ISSUE THREAD

**Issue by jopoly** [laurenz/oracle_fdw#566]
Hi Laurenz,

Currently, oracle_fdw does not have source to handle trigger before updating data.
I refer to source code of postgres_fdw like below:
```
if (operation == CMD_INSERT ||
    (operation == CMD_UPDATE &&
     rel->trigdesc &&
     rel->trigdesc->trig_update_before_row))
{
    TupleDesc	tupdesc = RelationGetDescr(rel);
    int			attnum;

    for (attnum = 1; attnum <= tupdesc->natts; attnum++)
    {
        Form_pg_attribute attr = TupleDescAttr(tupdesc, attnum - 1);

        if (!attr->attisdropped)
            targetAttrs = lappend_int(targetAttrs, attnum);
    }
}
```

I would like to share the implementation of oracle_fdw like this.
Are you interested?

**Comment by laurenz** [comment]
oracle_fdw already supports `BEFORE UPDATE` triggers on foreign tables.
Can you describe your proposed enhancement in some more detail?

**Comment by jopoly** [comment]
Thanks for reply.
I add some test case in oracle_fdw.sql like this:

**Procedure steps**:

1. Prepare:
```
--
-- Test that trigger on remote table works as expected
--
INSERT INTO typetest1 (id, vc) VALUES (22222, 'bb');
SELECT * FROM typetest1 WHERE id = 22222;
  id   | c | nc | vc | nvc | lc | r | u | lb | lr | b | num | fl | db | d | ts | ids | iym 
-------+---+----+----+-----+----+---+---+----+----+---+-----+----+----+---+----+-----+-----
 22222 |   |    | bb |     |    |   |   |    |    |   |     |    |    |   |    |     | 
(1 row)

CREATE OR REPLACE FUNCTION F_BRTRIG() RETURNS trigger AS $$
BEGIN
    NEW.vc = NEW.vc || '_brtrig';
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER typetest1_br_insert BEFORE INSERT OR UPDATE
    ON typetest1 FOR EACH ROW EXECUTE PROCEDURE F_BRTRIG();
UPDATE typetest1 SET c = 'aa' WHERE id = 22222;
```

2. Select after update:
2.1. Actual result:
```
SELECT * FROM typetest1 WHERE id = 22222;

-- Actual result: value in vc is not updated.
  id   |     c      | nc | vc | nvc | lc | r | u | lb | lr | b | num | fl | db | d | ts | ids | iym 
-------+------------+----+----+-----+----+---+---+----+----+---+-----+----+----+---+----+-----+-----
 22222 | aa         |    | bb |     |    |   |   |    |    |   |     |    |    |   |    |     | 
(1 row)
```

2.2. Expected result:
```
SELECT * FROM typetest1 WHERE id = 22222;

-- Expected result: value in vc is updated.
  id   |     c      | nc | vc | nvc | lc | r | u | lb | lr | b | num | fl | db | d | ts | ids | iym 
-------+------------+----+----+-----+----+---+---+----+----+---+-----+----+----+---+----+-----+-----
 22222 | aa         |    | bb_brtrig |     |    |   |   |    |    |   |     |    |    |   |    |     | 
(1 row)
```

**Comment by laurenz** [comment]
Strange, it works for me.

On Oracle:

```
CREATE TABLE trig (
   id number(5) CONSTRAINT trigger_pkey PRIMARY KEY,
   val varchar2(20 char)
) SEGMENT CREATION IMMEDIATE;
```

On PostgreSQL:

```
CREATE FOREIGN TABLE trig (
   id integer OPTIONS (key 'on') NOT NULL,
   val varchar(20)
) SERVER oracle OPTIONS (table 'TRIG');

CREATE FUNCTION trig() RETURNS trigger LANGUAGE plpgsql AS
$$BEGIN
   NEW.val := NEW.val || '!';
   RETURN NEW;
END;$$;

CREATE TRIGGER trig BEFORE INSERT OR UPDATE ON trig
   FOR EACH ROW EXECUTE FUNCTION trig();

INSERT INTO trig VALUES (1, 'mama');

TABLE trig;

 id │  val  
════╪═══════
  1 │ mama!
(1 row)

UPDATE trig SET val = 'wuwu' WHERE id = 1;

TABLE trig;

 id │  val  
════╪═══════
  1 │ wuwu!
(1 row)

UPDATE trig SET val = 'super' WHERE id = 1 RETURNING val;

  val   
════════
 super!
(1 row)
```

I am using git HEAD for PostgreSQL and oracle_fdw.
Since you say you have an implementation, can me tell me what is wrong?

**Comment by jopoly** [comment]
I use Postgresql 15.0 and the newest oracle_fdw.

I tried to follow your procedure steps, and it works.
But with my procedure steps, it still not works.
I think our procedure is not the same.
I used **PROCEDURE** and you use **FUNCTION**

I use make check to reproduce this bug.
I create folders like below
![image](https://user-images.githubusercontent.com/33323090/212299009-a145ac2c-d242-4959-bac3-d6a47bdffce0.png)

I send you .sql file and .out when I execute test. I already added the test cases to reproduce this bug.
[oracle_fdw_testcode.zip](https://github.com/laurenz/oracle_fdw/files/10410601/oracle_fdw_testcode.zip)

You can compare these files with the original version to see the test case that I added.

**Comment by laurenz** [comment]
No, `FUNCTION` or `PROCEDURE` in `CREATE TRIGGER` is the same.
The difference is that your `UPDATE` statement does _not_ modify the column that is changed by the trigger.
Then the trigger runs correctly locally, but the remote `UPDATE` statement does not include the column that was modified by the trigger, so that value is not modified in Oracle.

This is indeed a bug.
Do you already have a fix?

**Comment by laurenz** [comment]
Thanks again for the report and the pointer to the cause.
I gave up waiting for a patch from you, but I'm still happy to accept fixes for the other bugs you reported.
