### ISSUE TITLE
Support generate column when UPDATE

### ISSUE THREAD

**Issue by jopoly** [laurenz/oracle_fdw#567]
Hi Laurenz,

Currently, generating column is not supported in oracle_fdw.
Example:

```
create foreign table grem1 (
    a int OPTIONS (key 'yes'),
    b int generated always as (a * 2) stored
) server oracle_srv options(table 'GLOC1');

insert into grem1 (a) values (1), (2);

select * from grem1;
 a | b 
---+---
 1 | 2
 2 | 4
(2 rows)

update grem1 set a = 22 where a = 2;
 a  | b 
----+---
  1 | 2
 22 | 4
(2 rows)
```
I think the result after executing UPDATE command should be like below:
```
 a  | b 
----+----
  1 |  2
 22 | 44
(2 rows)
```

I would like to share the source code to handle this.
Are you interested?

**Comment by laurenz** [comment]
That is actually a bug, and I would definitely welcome a fix.

**Comment by jopoly** [comment]
Thanks for your feedback, I will fix it and create a Pull Request as soon as possible.
