### ISSUE TITLE
Support RETURNING whole row

### ISSUE THREAD

**Issue by jopoly** [laurenz/oracle_fdw#568]
Hi Laurenz,

I would like to share the source code to support RETURNING the whole row.
Are you interested?

Example:

```
CREATE FOREIGN TABLE tbl1 (
  c1 int,
  c2 character(10),
  c3 character(10)
) SERVER oracle_srv (table 'TBL1');

INSERT INTO tbl1 (c1, c2) VALUES (1, 'aaa') RETURNING c1, c2;
 c1 |  c2 
----+-----
  1 | aaa 
(1 row)

-- RETURNING the whole row
INSERT INTO tbl1 (c1, c2) VALUES (1, 'aaa') RETURNING tb1;
   tb1
---------
(1, aaa,)
(1 row)
```

**Comment by laurenz** [comment]
That is also a bug, and a fix is welcome.

**Comment by jopoly** [comment]
Thanks for your feedback, I will fix it and create a Pull Request as soon as possible.

**Comment by mkgrgis** [comment]
Ping, @jopoly 
This look like interesting fix for one of my cases. Have you got any news?
