### ISSUE TITLE
Import schema and timestamp(-78)

### ISSUE THREAD

**Issue by decibel** [laurenz/oracle_fdw#57]
Related to  #56 , sys.xds_ace also fails:

```
LINE 1: ... "xds_ace" ("aclid" bytea, "start_date" timestamp(-78) witho...
                                                             ^
QUERY:  CREATE FOREIGN TABLE "xds_ace" ("aclid" bytea, "start_date" timestamp(-78) without time zone, "end_date" timestamp(-78) without time zone, "is_grant" character varying(5), "invert" character varying(5), "principal" character varying(4000), "privilege" text) SERVER "oracle" OPTIONS (schema 'SYS', table 'XDS_ACE', readonly 'true')
```

Looking in ALL_TAB_COLUMNS, DATA_TYPE indeed shows 'TIMESTAMP(-78)' and DATA_SCALE is -78.

I also can't exclude this table. I've tried XDS_ACE, xds_ace and "xds_ace":

```
IMPORT FOREIGN SCHEMA "SYS"
  EXCEPT( EXU8COL, EXU8COLU, EXU8COL_TTS_UNUSED_COL, KU$_TABCLUSTER_COL_VIEW, "xds_ace" )
  FROM SERVER oracle
  INTO sys
  OPTIONS( readonly 'true' )
;
```

And LIMIT TO is apparently being ignored as well (I tried both upper and lowercase):
```SQL
IMPORT FOREIGN SCHEMA "SYS"
  --EXCEPT( EXU8COL, EXU8COLU, EXU8COL_TTS_UNUSED_COL, KU$_TABCLUSTER_COL_VIEW, "xds_ace" )
  LIMIT TO( all_source )
  FROM SERVER oracle
  INTO sys
  OPTIONS( readonly 'true' )
;
```

**Comment by laurenz** [comment]
Now that is strange.

The (internal) table ``SYS.XDS_ACE`` is defined differently in different Oracle versions, but it does not look like what you see in the ones I have at hand.

In Oracle 10.2:

    SQL> SELECT data_length, data_precision, data_scale
      2  FROM all_tab_columns
      3  WHERE owner='SYS' and table_name='XDS_ACE' AND column_name='START_DATE';
    
    no rows selected

In Oracle 11.2:

    SQL> SELECT data_length, data_precision, data_scale
      2  FROM all_tab_columns
      3  WHERE owner='SYS' and table_name='XDS_ACE' AND column_name='START_DATE';
    
    DATA_LENGTH DATA_PRECISION DATA_SCALE
    ----------- -------------- ----------
             13                         9

In Oracle 12.1:

    SQL> SELECT data_length, data_precision, data_scale
      2  FROM all_tab_columns
      3  WHERE owner='SYS' and table_name='XDS_ACE' AND column_name='START_DATE';
    
    DATA_LENGTH DATA_PRECISION DATA_SCALE
    ----------- -------------- ----------
           4000                         0

What is your Oracle server version?

And ``LIMIT TO`` and ``EXCEPT`` work fine here.
I wonder what is going on in your installation.

Can you tell me the result of ``SELECT oracle_diag('oracle')``?

**Comment by decibel** [comment]
```SELECT oracle_diag('oracle');
                                       oracle_diag 

----------------------------------------------------------------------------------------
  oracle_fdw 1.3.0, PostgreSQL 9.5.0, Oracle client 11.2.0.4.0, Oracle 
server 11.2.0.1.0
(1 row)
```

**Comment by decibel** [comment]
```
SELECT` oracle_diag('oracle');
                                       oracle_diag 
----------------------------------------------------------------------------------------
  oracle_fdw 1.3.0, PostgreSQL 9.5.0, Oracle client 11.2.0.4.0, Oracle 
server 11.2.0.1.0
(1 row)
```

**Comment by laurenz** [comment]
Could it be that there is a bug or data corruption in your Oracle database?
I tested on 11.2.0.4, but that shouldn't make much of a difference.

Can you try

    ALTER VIEW SYS.XDS_ACE COMPILE;

and see if that makes a difference?

How did you test that ``LIMIT TO`` and ``EXCEPT`` does not work?
I tried with schema ``SYS`` like you did and didn't notice anything odd.

Can you maybe attach a debugger and see what happens in ``IsImportableForeignTable()`` in ``src/backend/foreign/foreign.c``?

**Comment by decibel** [comment]
On 2/17/16 4:26 AM, Laurenz Albe wrote:
> Can you try
>
> |ALTER VIEW SYS.XDS_ACE COMPILE; |
>
> and see if that makes a difference?

Unfortunately I don't have the required perms. I've asked my client to 
try this.

> How did you test that |LIMIT TO| and |EXCEPT| does not work?
> I tried with schema |SYS| like you did and didn't notice anything odd.
>
> Can you maybe attach a debugger and see what happens in
> |IsImportableForeignTable()| in |src/backend/foreign/foreign.c|?

Turns out the problem here is with how things are coded. The FDW creates 
a monster set of CREATE FOREIGN TABLE commands, which get *parsed* 
inside ImportForeignSchema(), before even attempting to see whether we 
should be importing the table or not. Since we're getting bogus data for 
xds_ace, the parsing fails. That could maybe be fixed, but I suspect 
it's not worth it.
-- 
Jim Nasby, Data Architect, Blue Treble Consulting, Austin TX
Experts in Analytics, Data Architecture and PostgreSQL
Data in Trouble? Get it in Treble! http://BlueTreble.com

**Comment by laurenz** [comment]
oracle_fdw uses the default of not pushing down ``LIMIT TO`` and ``EXCEPT``.
I have considered it, but it would be a challenge because I'd have to take case translation into account.

So what remains to be seen to is ``SYS.XDS_ACE``.
I'll wait for what your client says.

**Comment by decibel** [comment]
They recompiled all_tab_columns and the odd negative scales went away.

**Comment by laurenz** [comment]
Strange, but good that it is solved!
