### ISSUE TITLE
Postgresql 15 support

### ISSUE THREAD

**Issue by raulk89** [laurenz/oracle_fdw#572]
Hi

Will there be postgresql 15 support as well for linux (RHEL 8)..?

Regards
Raul

**Comment by laurenz** [comment]
Version 15 is supported and should work with the latest release of oracle_fdw.

**Comment by laurenz** [comment]
I never provided binaries for Linux. There are so many distributions and packaging systems.
Besides, it is so simple to build oracle_fdw from source.
i used to provide Windows binaries, but since I don't have access to a Windows machine at the moment, I didn't provide Windows binaries for the latest release either.

**Comment by philflorent** [comment]
Hi,
Yes it's a trivial task. I package oracle_fdw for Debian. Debian 10/pg 11, Debian 11/pg13 and I will do that for Debian 12/pg15 as well (it's already ready for dev & test of course but I wait for Debian 12 to be released to put the links on a public address).  
Purpose is always to maintain for my customers a complete Postgres-ready iso derived from Debian that can be 99% updated from an official repository  but I can also provide the individual non-native Debian binaries if it can be useful for some people .

https://pgphil.ovh/oracle-instantclient-21.9_amd64.deb (Oracle Instant Client 19.17 tested with Debian 10/11/12)
https://pgphil.ovh/postgresql-11-oracle-fdw-19.2_amd64.deb (oracle_fdw 2.2 Debian 10 / PostgreSQL 11)
https://pgphil.ovh/postgresql-13-oracle-fdw-21.5_amd64.deb (oracle_fdw 2.5devel Debian 11 /PostgreSQL 13)

I also used to package tds_fdw in the past but it's now native.
oracle_fdw itself could be in core Debian distribution but it depends on a non-free component, Oracle Instant Client, unlike tds-fdw. 
Not difficult to package this Oracle client but I would have to change quite a few things to pass lintian validation (I currently put it in /opt for example). Instant Client is normally "freely" redistributable and perhaps it could be put in non-free according to its license but, for example, current version is 19.3 on Debian/Power and 19.18 on Debian/am64. Oracle has no predictable roadmap on this aspect.
Best is to package oracle_fdw for your Linux distribution according to your needs or to deploy it via ansible or to create a docker image etc. So many ways to distribute it efficiently.  
Best regards,
Phil

**Comment by laurenz** [comment]
@philflorent  Thanks for the information.
You say that you "would have to change quite a few things to pass lintian validation". I don't know what that is, but if there is anything that should be changed around oracle_fdw to make packaging easier, I am happy to consider it.

**Comment by laurenz** [comment]
@philflorent  Thanks for the clarification.

**Comment by laurenz** [comment]
@michi-zuri  Thanks for your initiative, but you should start a new issue for that. I cannot verify your binaries, but I can take them on faith and provide them to the public.
