### ISSUE TITLE
Upgrade Postgresql 14.2 to Postgresql 15.2

### ISSUE THREAD

**Issue by lux7789** [laurenz/oracle_fdw#574]
Hi,

I'm trying to upgrade with pg_upgrade and I'm using this command,

 pg_upgrade -b /u01/app/postgres/product/14/db_2/bin -B /u01/app/postgres/product/15/db_3/bin -d /u02/pgdata/14/db_1 -D /u02/pgdata/15/db_3/PG1 --check

I got this message,
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for system-defined composite types in user tables  ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for presence of required libraries                 fatal

Your installation references loadable libraries that are missing from the
new installation.  You can add these libraries to the new installation,
or remove the functions using them from the old installation.  A list of
problem libraries is in the file:
    /u02/pgdata/15/db_3/PG1/pg_upgrade_output.d/20230216T133231.378/loadable_libraries.txt

Failure, exiting

And we find this in loadable_libraries.txt,

could not load library "$libdir/pg_cron": ERROR:  could not access file "$libdir/pg_cron": Aucun fichier ou dossier de ce type
In database: postgres
could not load library "$libdir/oracle_fdw": ERROR:  could not access file "$libdir/oracle_fdw": Aucun fichier ou dossier de ce type
In database: postgres

Should I reinstall both extensions and where ?  /u01/app/postgres/product/15/db_3/bin ?

**Comment by laurenz** [comment]
Yes, you have to install the same version of oracle_fdw with the v15 binaries. Just follow the normal installation procedure.

If you are using a version of oracle_fdw that is too old to build on v15, upgrade to a more recent version of oracle_fdw in the v14 database first.

**Comment by lux7789** [comment]
Perfect !
