### ISSUE TITLE
Windows dll v2.5.0 for pg11-pg15

### ISSUE THREAD

**Issue by michi-zuri** [laurenz/oracle_fdw#578]
Hi again, 

I noticed that I compiled the master branch (2.6.0devel) in #572, so here a zip file of the compiled 2.5.0 release for pg11 to pg15. As you said, not possible to verify the builds, but maybe it's of help to someone out there anyway. At least `select oracle_diag()` seems to return the correct values. I haven't tested anything else. 

[pg11-pg15_x64.zip](https://github.com/laurenz/oracle_fdw/files/10984874/pg11-pg15_x64.zip)

all the best 
Michi

**Comment by laurenz** [comment]
Thanks for your help; I have added your binaries to the release.

**Comment by laurenz** [comment]
@Schtailian Thanks for the generous offer. I would welcome that!
