### ISSUE TITLE
IMPORT FOREIGN TABLE 

### ISSUE THREAD

**Issue by colibri11** [laurenz/oracle_fdw#58]
Hi, be possible to add the IMPORT FOREIGN TABLE  command ?

**Comment by laurenz** [comment]
``IMPORT FOREIGN SCHEMA`` is standard SQL, while I believe that ``IMPORT FOREIGN TABLE`` is not.
So I don't think PostgreSQL is going to add that command.

You can easily do the same thing by using the ``LIMIT TO`` clause of ``IMPORT FOREIGN SCHEMA``:

    IMPORT FOREIGN SCHEMA "ORASCHEMA" LIMIT TO (mytable) FROM SERVER oradb INTO local_schema
