### ISSUE TITLE
postgresql15-devel installation failed 

### ISSUE THREAD

**Issue by lux7789** [laurenz/oracle_fdw#580]
Hi,

I'm following your doc but since I installed postgresql15.2 with packages I understand that I need postgresql15-devel. And when I'm trying to install the dev packages I'm receiving an error saying that I need to install package perl-ipc-run. This package is not available in my distribution. My distribution is Oracle Linux 7.9. I tried to install rh-perl530-perl-IPC-Run.noarch that is included in the distribution but without success. Can I trust what I find on metacpan (https://metacpan.org/pod/IPC::Run) ? The maintainer is also looking for some else to take over !  Are you aware of this ? The main question is, can I trust that package ?

Thanks !

Regards,

Luc

**Comment by lux7789** [comment]
Hi  !

I installed perl-ipc-run from metacpan with cpanm and I still have the error when installing postgresql15-devel.

Erreur : Paquet : postgresql15-devel-15.2-1PGDG.rhel7.x86_64 (pgdg15)
             Requiert : perl(IPC::Run)

**Comment by laurenz** [comment]
Sorry for the late reply.

You can [download the package][dl] from Oracle, but the best solution is probably to enable the repository:

```bash
sudo yum install oracle-linux-manager-server-release-el7
sudo yum-config-manager --enable ol7_optional_latest
```

If you install the software without a package like you did, RPM won't know it is installed, so you'd have to install the "devel" package ignoring dependencies, which is possible with`rpm`, but (as far as I know) not with `yum`. I think that it is better to install the packages.

 [dl]: https://yum.oracle.com/repo/OracleLinux/OL7/optional/latest/x86_64/getPackage/perl-IPC-Run-0.92-2.el7.noarch.rpm

**Comment by laurenz** [comment]
Does this solve your problem?

**Comment by lux7789** [comment]
Yes !
