### ISSUE TITLE
table or view in SYS cannot be imported

### ISSUE THREAD

**Issue by huey97** [laurenz/oracle_fdw#584]
After CREATE SERVER and CREATE USER MAPPING, we cannot import table/view from SYS in ORACLE. This following statements will get stuck, rather than raising an error or something else.

IMPORT FOREIGN SCHEMA "SYS" LIMIT TO ("all_db_links") FROM SERVER oracle INTO import OPTIONS (case 'lower');

**Comment by laurenz** [comment]
Are there any updates on this?
