### ISSUE TITLE
Problem with getting a connection.

### ISSUE THREAD

**Issue by Barsu4ello** [laurenz/oracle_fdw#586]
Hi, i try to use oracle_fdw in my production environment.

Server with Postgres settings:
PostgresProEnterprise 11.5
instantclient oracle 21_6

Server with Oracle have  instant client 11.2.0.4.0

I did next steps:
CREATE EXTENSION oracle_fdw;

CREATE SERVER oradb
FOREIGN DATA WRAPPER oracle_fdw
 OPTIONS (dbserver '//host:port/sid');
			  
GRANT USAGE ON FOREIGN SERVER oradb TO postgres;
			  
 CREATE USER MAPPING FOR postgres SERVER oradb
 OPTIONS (user 'myUserName', password 'myPas');
			  
CREATE FOREIGN TABLE oratab (
...
   ) SERVER oradb OPTIONS (schema 'TEST', table 'TEST_TABLE');
  

When i tried to execute:
Select * from oratab 
I have next error:
server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.

If i try to execute comand: sqlplus myUserName/myPas@//host:port/sid 	
It works well.

if i execute:
 select orac_diag();
 I get:
oracle_fdw 2.5.0, PostgreSQL 11.5, Oracle client 21.6.0.0.0, ORACLE_HOME=E:\SOFT\instantclient_21_6, TNS_ADMIN=E:\SOFT\instantclient_21_6\network\admin

but if i execute:
select orac_diag('oradb');
i get the same error:
server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.

Maybe, you can give me adviсe about this problem..

I tried to do same steps on my home computer and oracle_fdw works well. But in production it doesn't work((

**Comment by laurenz** [comment]
I know from #261 that PostgresPro's fork is not binary compatible with PostgreSQL, but #217 suggests that oracle_fdw works with it (at least to some extent). So my suspicion is that you built oracle_fdw with a different PostgreSQL installation than the one where you installed it (see #583 for an example of possible effects of that).

So my suggestion is:
- uninstall every PostgreSQL software from the machine except the PostgresProEnterprise 11.5 you are using
- build oracle_fdw on that machine

See if that fixes your problem. Be aware that I cannot guarantee that oracle_fdw will work with any fork of PostgreSQL. It reaches deep into the innards of PostgreSQL, so if these have been modified in the fork, anything could happen.

**Comment by Barsu4ello** [comment]
...uninstall every PostgreSQL software from the machine except the PostgresProEnterprise 11.5 you are using

On that machine only PostgresProEnterprise 11.5 without other Postgresql software.

...build oracle_fdw on that machine.

You mean that write code for building oracle_fdw against PostgresPro?

**Comment by laurenz** [comment]
No, just that you should perform the `make` &ndash; `make install` routine on that very machine.

If that is what you did, try and [get a stack trace][1] from the core dump created during the server crash.

 [1]: https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Linux/BSD

**Comment by Barsu4ello** [comment]
Is there similar method on Windows? Production on Windows machine.

**Comment by chrullrich** [comment]
According to https://postgrespro.com/products/download/postgrespro/latest (select 11, then Windows) PostgresPro (Standard) 11 (currently at 11.19, perhaps try the latest release?) includes oracle_fdw 2.3.0.

From version 12 on they include oracle_fdw 2.5.0. Yours is 2.5.0, so it may not be the included version. Where did you get it?

You can easily compile oracle_fdw on Windows if you have the tools, i.e. Visual Studio 2013 or later.

**Comment by Barsu4ello** [comment]
- From version 12 on they include oracle_fdw 2.5.0. Yours is 2.5.0, so it may not be the included version. Where did you get it?

I get it here https://github.com/laurenz/oracle_fdw/releases. And use it on my home machine with postgresql 14. It worked well. And I decided did the same steps on my production.

Now i understand what i need to do. I downloaded https://pgxn.org/dist/oracle_fdw/2.3.0/ this zip file. 
But when i use comand:
msbuild oracle_fdw-2.3.0\msvc\oracle_fdw.sln /p:Configuration=Debug /p:Platform=x64  /p:OracleClient="C:\instantclient_21_6\sdk" /p:PostrgeSQL="C:\Program Files\PostgresProEnterprise\11"

I get error:
C:\...\Microsoft.Cpp.WindowsSDK.target
s(46,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or chang
e the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [E
:\TMP\oracle_fdw-2.3.0\oracle_fdw-2.3.0\msvc\oracle_fdw.vcxproj]

I quess that i need download Windows SDK version 8.1? Beacause with Windows SDK version 10 i can't execute msbuild. Is it true? Or I can do it with 10 vers SDK some other method?

**Comment by chrullrich** [comment]
Add `/p:WindowsTargetPlatformVersion=10.0` to your msbuild command line. That should give you the latest 10 SDK you have. If you want an earlier one, you can use the full version from the directory names in `Windows Kits\10\include`.

**Comment by Barsu4ello** [comment]
Thank you very mush.
But i had next proplem:

ClCompile target) ->
  e:\tmp\oracle_fdw-2.3.0\oracle_fdw-2.3.0\oracle_fdw.c(8): fatal error C1083: Cannot open include file: 'postgres.h': No such file or directory [E:\TMP\oracle_fdw-2.3.0\oracle_fdw-2.3.0\msvc\oracle_fdw.vcxproj]
  e:\tmp\oracle_fdw-2.3.0\oracle_fdw-2.3.0\oracle_gis.c(15): fatal error C1083: Cannot open include file: 'oci.h': No such file or directory [E:\TMP\oracle_fdw-2.3.0\oracle_fdw-2.3.0\msvc\oracle_fdw.vcxproj]
  e:\tmp\oracle_fdw-2.3.0\oracle_fdw-2.3.0\oracle_utils.c(12): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [E:\TMP\oracle_fdw-2.3.0\oracle_fdw-2.3.0\msvc\oracle_fdw.vcxproj]
  e:\tmp\oracle_fdw-2.3.0\oracle_fdw-2.3.0\msvc\oracle_msvc.c(1): fatal error C1083: Cannot open include file: 'postgres.h': No such file or drectory [E:\TMP\oracle_fdw-2.3.0\oracle_fdw-2.3.0\msvc\oracle_fdw.vcxproj]

**Comment by Barsu4ello** [comment]
laurenz, chrullrich, Thank you very mush. I have done it!!! All your recommendations were very usefull!
All the best to you!

**Comment by laurenz** [comment]
Are you sure you want to use an old version like 2.3.0?
Anyway, glad that you could get it to build.
Can we close the issue?

**Comment by Barsu4ello** [comment]
I have tested my bd. Version 2.3.0 is good for me. You can close the issue. Thank you very much.
