### ISSUE TITLE
Cannot cancel an insert from oracle foreign table

### ISSUE THREAD

**Issue by SebastienCaunes** [laurenz/oracle_fdw#588]
When I do an insert `INSERT INTO my_pg_table (SELECT * FROM my_foreign_table);`

If I cancel the insert from dbeaver, or just end the connection from a client (NPGsql) the query keeps running indefinetly in postgres and there is no way to kill it with pg_terminate_backend().

I will try to get more information for you. Please let me know what you want.

**Comment by SebastienCaunes** [comment]
Thanks for your answer Laurenz.
The table transferred is 100GB large, with one CLOB column (yes, I know you hate them :) ). 99,6% of these CLOBS are less than 12ko and 0,0001% more than 1MB. And it's dam slow at 0.5MB /s (I set 1000 for prefetch, and the default 1MB for lob_prefetch)

**Comment by SebastienCaunes** [comment]
I did the test again making sure last HEAD version is installed.
It is really slow. like 0.5MB/s
I'm using crazy workarounds to make the transfer faster : I create several views on Oracle side depending on the CLOB length. I slice the CLOB in varchar(4000). Then import in Postgres and concatenate them when inserting. I reach 18 times faster this way (around 10MB/s).

**Comment by laurenz** [comment]
Well, it was fast for me and others.

Anyway, that's not the problem at hand.
Try to figure out if oracle_fdw is stuck inside a single, long running Oracle request.
You may have to look at the Oracle side to see that, or use a debugger like I suggested.

**Comment by laurenz** [comment]
Could you make any progress with this problem?
