### ISSUE TITLE
OCIStmtExecute failed to execute remote query‎ strikes again

### ISSUE THREAD

**Issue by Reznik070** [laurenz/oracle_fdw#590]
Hi,

And thank you for your contribution. This OCIStmtExecute failed to execute remote query‎ has been giving me a headache recently. Oracle_fdw worked so well last year until I checked recently. Did you change anything recently? Is this some serialization issue? First I got this error. Then it worked but I noticed no ID (Primary key) serial was saved. Then I tried again with a new create and all I get is this error.

Thanks.

**Comment by Reznik070** [comment]
Sorry for the late response. I was trying to find out additional information as per test case.

PostgresSQL version 11 / oracle_fdw 1.1 / Oracle 11g / Oracle client 12c

**Comment by laurenz** [comment]
Thanks. 1.1 is the version of the extension.
You can run `SELECT oracle_diag();` to get the oracle_fdw version.

Now please copy and paste the error message and show me the exact sequence of statements that lead to this.

**Comment by laurenz** [comment]
> Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.

Please make it display the interesting information.

You are using a very old version of oracle_fdw. Please try with [Git HEAD](https://github.com/laurenz/oracle_fdw/archive/refs/heads/master.zip).

If the error persists, and the secret detail information is not enough for me to understand what's going on, I will ask for the following:

- the exact `CREATE TABLE` statement in Oracle
- the exact `CREATE FOREIGN TABLE` statement in PostgreSQL
- the exact query you are running

**Comment by laurenz** [comment]
You are welcome! Could you solve the problem? How?

**Comment by Reznik070** [comment]
Hi, not yet. Oracle admin is on holiday. I'll post when we try your suggestions. Sorry for the late response

**Comment by laurenz** [comment]
I'll close this for inactivity. Feel free to reopen it if you have new information.
