### ISSUE TITLE
insert double precison report errorOCI-22061: invalid format text [9D9EEEEE]

### ISSUE THREAD

**Issue by liubeck** [laurenz/oracle_fdw#591]
Now I am using oracle_fdw to insert a foreigin table which with double precison column.
When insert a record '1.7e+99', I can insert successfully.
But inset a record '1.7e+100', it report error as below.
It shows formate '9D9EEEEE' is invalid. 
So how should we support the number '1.7e+100' to insert foreign table?

oracle table desc
```
SQL>  create table precision_test(value double precision);

Table created.
```

```
postgres=# create foreign table precision_test(value double precision) server oracle  options (table 'PRECISION_TEST');
CREATE FOREIGN TABLE
postgres=# select * from precision_test;
 value
-------
(0 rows)

postgres=# insert into precision_test values (1.7e+99);
INSERT 0 1
postgres=# insert into precision_test values (1.7e+100);
2023-06-08 17:09:51.214 CST [2851377] ERROR:  error executing query: OCINumberFromText failed to convert parameter
2023-06-08 17:09:51.214 CST [2851377] DETAIL:  OCI-22061: invalid format text [9D9EEEEE]
2023-06-08 17:09:51.214 CST [2851377] STATEMENT:  insert into precision_test values (1.7e+100);
ERROR:  error executing query: OCINumberFromText failed to convert parameter
DETAIL:  OCI-22061: invalid format text [9D9EEEEE]
```
I use pg15. And oracle_fdw is 
commit c357af36270abd807773f26b9c876543e3784629 (HEAD -> master, origin/master, origin/HEAD)
Author: Laurenz Albe <laurenz.albe@cybertec.at>
Date:   Mon Jun 5 10:30:20 2023 +0200

    Fix license wording

After I change the  num_format to '9D9EEEE' from '9D9EEEEE', I can insert '1.7e+100' successfully.

**Comment by laurenz** [comment]
Thanks for the report!
Could you check if that commit fixed the problem?

**Comment by liubeck** [comment]
> Thanks for the report! Could you check if that commit fixed the problem?

Thanks for you fix.
With this commit, now I can insert successfully.
```
postgres=# insert into precision_test values (1.7e+99);
INSERT 0 1
postgres=# insert into precision_test values (1.7e+100);
INSERT 0 1
postgres=# select * from precision_test;
  value
----------
  1.7e+99
 1.7e+100
(2 rows)
```

I don't konw whether this is a bug.
Now I insert with value '1.7e+127', it will report successfully. And I query, it will return "Infinity".
```
postgres=# insert into precision_test values (1.7e+126);
INSERT 0 1
postgres=# select * from precision_test;
  value
----------
 Infinity
  1.7e+99
 1.7e+100
(3 rows)

postgres=# insert into precision_test values (1.7e+125);
INSERT 0 1
postgres=# select * from precision_test;
  value
----------
 Infinity
 1.7e+125
  1.7e+99
 1.7e+100
(4 rows)

postgres=# insert into precision_test values (1.7e+127);
INSERT 0 1
postgres=# select * from precision_test;
  value
----------
 Infinity
 1.7e+125
  1.7e+99
 1.7e+100
 Infinity
(5 rows)
```

Actually, In oracle, I cannot insert value '1.7e+127'. It will report overflow.
```
SQL> select * from precision_test;

     VALUE
----------
	 ~
1.700E+125
1.7000E+99
1.700E+100
	 ~

SQL>
SQL> insert into precision_test values (1.7e+126);
insert into precision_test values (1.7e+126)
                                   *
ERROR at line 1:
ORA-01426: numeric overflow


SQL>
```

**Comment by laurenz** [comment]
The reason for that is that I convert the value to an Oracle NUMBER, and that is limited from 10<sup>-130</sup> to 10<sup>126</sup> (exclusive the upper bound).

This is not quite proper, since BINARY_DOUBLE would support a wider range of numbers, but unless that is a real problem for you, I'd be too lazy to change that.

**Comment by liubeck** [comment]
Thank you very much for your patience. This is a real problem for me.
Can you explain how it should be fixed？

**Comment by laurenz** [comment]
I'd have to disambiguate between NUMBER and BINARY_FLOAT in `oracleExecuteQuery` in `oracle_utils.c`.
Currently, all numeric parameters are labeled as `BIND_NUMBER`.

**Comment by laurenz** [comment]
I think I fixed the problem; it was simpler than I thought.
Can you test again?

**Comment by liubeck** [comment]
Hi laurenz, thank you very much.
With this fix, I can get the same behavie with oracle when I insert '1.7e+126'.
