### ISSUE TITLE
ORA-01861 when try get data from view in Oracle

### ISSUE THREAD

**Issue by paulohmoraes** [laurenz/oracle_fdw#593]
Oracle variables  : 

NLS_LANGUAGE	BRAZILIAN PORTUGUESE

```
desc VW_TEST
Nome       Nulo? Tipo         
---------- ----- ------------ 
INS        VARCHAR2(8)  
STA            VARCHAR2(3)  
KEEP        VARCHAR2(29) 
HT             VARCHAR2(9) 
```

Postgres variables : 

```
CREATE FOREIGN TABLE IF NOT EXISTS f_test (
INS        VARCHAR(10),
STA            VARCHAR(4),
KEEP        varchar(35),
HT             varchar(10) 
)
SERVER mkwork
OPTIONS (schema 'DB', table 'VW_TEST');
```

Test :

```
SELECT * FROM f_test

ERROR:  error executing query: OCIStmtExecute failed to execute remote query
SQL state: HV00L
Detail: ORA-01861: literal does not match format strin
```

The same does not happen when I get the data from the Oracle table:

``` 
create table test_table as  select * from VW_TEST;
Table TEST_TABLE criado.
```

Postgres : 

```
CREATE FOREIGN TABLE IF NOT EXISTS f_test (
INS        VARCHAR(10),
STA            VARCHAR(4),
KEEP        varchar(35),
HT             varchar(10) 
)
SERVER catalogo
OPTIONS (schema 'DB', table 'TEST_TABLE');

SELECT * FROM f_test
 INST                      STA           KEEP                                                               HT             
"DBLINKTEST" 	"OK"	"USING WINDOW "	  "BOB"
```

I thank anyone who can help

**Comment by paulohmoraes** [comment]
adicional information : 
Postgtres
SELECT oracle_diag('catalogo');
oracle_fdw 2.5.0, PostgreSQL 14.8, Oracle client 21.8.0.0.0, Oracle server 19.0.0.0.0

SHOW server_encoding;
UTF8
Oracle :
 SELECT parameter, value
FROM nls_database_parameters
WHERE parameter IN ('NLS_CHARACTERSET', 'NLS_NCHAR_CHARACTERSET');

NLS_NCHAR_CHARACTERSET AL16UTF16
NLS_CHARACTERSET AL32UTF8

**Comment by laurenz** [comment]
Strange.

Try to get the execution plan with the query that is executed in Oracle:

```
EXPLAIN SELECT * FROM f_test;
```

Do you get the same error if you execute that query in sqlplus or another Oracle client?

**Comment by paulohmoraes** [comment]
Thanks's for help.

Postgres :
EXPLAIN SELECT * FROM f_test;

Foreign Scan on f_test  (cost=10000.00..20000.00 rows=1000 width=872) 
Oracle query: SELECT /*b6bc85b5b0e924d6*/ r1.  INS  , r1.  STA  , r1.  KEEP  , r1.  HT   FROM   DBRCAT  .  VW_TEST   r1 

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.17.0.0.0

SQL> SELECT * FROM VW_TEST;

INS   STA      KEEP                                HT
-------- --- ----------------------------- ---------
DBLINKTEST OK  USING WINDOW    BOB

**Comment by laurenz** [comment]
You didn't run the same query in Oracle.

Did you copy and paste that? There are strange spaces in the query that `EXPLAIN` provides, were they there in the original?

The only chance I can help you is if I understand exactly what's going on or can reproduce the problem. You already gave me the `CREATE FOREIGN TABLE` statement in PostgreSQL. Can I have the `CREATE TABLE` statement from Oracle too?

**Comment by laurenz** [comment]
Anything new?
