### ISSUE TITLE
Postgres 16 support

### ISSUE THREAD

**Issue by Deltaus** [laurenz/oracle_fdw#594]
Hi there, so postgres 16 beta 1 is out and beta 2 has been stamped, I saw some errors when building current version with pg 16. May I know when we can expect a pg 16 compatible version to be available? Thanks!

**Comment by laurenz** [comment]
[Git HEAD](https://github.com/laurenz/oracle_fdw/archive/refs/heads/master.zip) should build well with the latest PostgreSQL software. If not, please open an issue.
I normally release a new version around the time when a new PostgreSQL version is released.

**Comment by Deltaus** [comment]
Confirmed master branch can build with beta 2. Thank you!!
