### ISSUE TITLE
Problem with ArchGIS software

### ISSUE THREAD

**Issue by dtoller** [laurenz/oracle_fdw#60]
Hi,
I encountered a problem while trying to read spatial data from a database in which there is the SDE scheme of ArchGIS software; the database has oracle_fdw, postgis and postgis_topology extensions installed.
I found that in the SDE schema are replicated some Postgis function, particularly the ST_GeomFromWKB function.
In your code (oracle_fdw.c) is a check on this function, if found duplicated in schemas other the "public", it generates an error preventing the conversion of spatial data.

_Extracto from postgres log:_
_ERROR: column "xxx" of foreign table "yyy" can not be converted to or from Oracle data types_

From another database of the same postgres instance, without SDE schema, I could read spacial data successfuly without errors.

**Comment by laurenz** [comment]
So you are saying that there are two functions called <tt>st_geomfromwkb</tt> in the database, one of them from PostGIS, the other from ArcGIS?

**Comment by dtoller** [comment]
exactly,
I found this situation in my database:

select nspname as schema, proname as procedure
from pg_proc pp join pg_namespace pns on pp.pronamespace = pns.oid
where pp.proname = 'st_geomfromwkb';

 schema |   procedure
--------+----------------
 sde    | st_geomfromwkb
 sde    | st_geomfromwkb
 public | st_geomfromwkb
 public | st_geomfromwkb

**Comment by laurenz** [comment]
Could you check if this commit fixes the problem for you?

**Comment by dtoller** [comment]
Hi
I tried the patch and now I can read spatial data without problems.
But when I set up the extension on the database I got the following warning message:

_CREATE EXTENSION oracle_fdw;
WARNING: reference leak cache: pg_proc cache (41), list 0x442bef0 has count 1_

**Comment by laurenz** [comment]
Ugh, sloppy coding; thanks for the report.

Should be fixed now.
