### ISSUE TITLE
RAW column length check for UUID case

### ISSUE THREAD

**Issue by mkgrgis** [laurenz/oracle_fdw#600]
Hello, @laurenz ! Thanks for your stable FDW.

Could you implement preventive RAW length check for UUID case like https://github.com/mkgrgis/sqlite_fdw/blob/939b6bc79033b74f7c24fd50ac22590e33bed9b0/sqlite_query.c#L378 In case of `RAW(15)` or `RAW(17)` there is expected PostgreSQL error, but I think more ISO:SQL is to prevent this problems before first sample error, in FDW. How do you think?

**Comment by laurenz** [comment]
I don't think that this is related to the SQL standard.

Do you mean that oracle_fdw should throw an error if the Oracle column is defiled as &ndash; say &ndash; `RAW(25)`?
I'm not sure if that is a good idea. The column could still contain a perfectly valid UUID value.

Or did I misunderstand? Then please describe the change and its benefits in more detail.

**Comment by mkgrgis** [comment]
> Do you mean that oracle_fdw should throw an error if the Oracle column is defiled as – say – `RAW(25)`?

Yes.

>  I'm not sure if that is a good idea. The column could still contain a perfectly valid UUID value.

We have only `unsigned char data [UUID_LEN]` in [pg_uuid_t](https://doxygen.postgresql.org/structpg__uuid__t.html) and `UUID_LEN = 16`. What about `RAW(25)`? 25 bytes is not 16 bytes, hence what about cutting? First 25-16 or last? What if `RAW(14)`? Add `/0` before data or after data? Why not to add some other default byte, not `/0`? All of this questions about possible implementation is outside of UUID (RFC4122) semantics at all. Transformations outside normal datatype semantics should not implemented according ISO:SQL to prevent non-obvious errors. Have you got any reason `RAW(25)`⇔`unsigned char data [UUID_LEN]` is normal 1 to 1 semantics?

> Or did I misunderstand? Then please describe the change and its benefits in more detail.

Yes, please refer https://datatracker.ietf.org/doc/html/rfc4122 implemented in PostgreSQL with such storage as https://doxygen.postgresql.org/structpg__uuid__t.html in https://doxygen.postgresql.org/uuid_8c.html#nested-classes

**Comment by laurenz** [comment]
I think you got me wrong. I am aware that a UUID is exactly 16 bytes long.

What I mean is that a column defined as `RAW(25)` can contain a valid UUID:

```
CREATE TABLE x (i RAW(25));

Table created.

SQL> INSERT INTO x VALUES ('00010203040506070809000102030405');

1 row created.

SQL> COMMIT;

Commit complete.

SQL> SELECT * FROM x;

I
--------------------------------------------------
00010203040506070809000102030405
```

So why should oracle_fdw throw an error in this case?

**Comment by mkgrgis** [comment]
> I think you got me wrong. 

Yes. I was wrong about values longer than formally `RAW(16)`. Thanks for clarification @laurenz !

> What I mean is that a column defined as `RAW(25)` can contain a valid UUID:

I am sorry, I have forgot Oracle RAW can have this `varbit`-like behavior. I haven't meet this use case or similar data transformation rules in other FDWs for PostgreSQL.

> ```
> CREATE TABLE x (i RAW(25));
> SQL> INSERT INTO x VALUES ('00010203040506070809000102030405');
> ```
![изображение](https://github.com/laurenz/oracle_fdw/assets/41448637/f83808f6-c8d0-4986-b4b6-d7268b945bbf)

> So why should oracle_fdw throw an error in this case?

Yes, this case is not an error and this is normal 1⇔1 ISO:SQL `RAW(25)`⇔`unsigned char data [UUID_LEN]` semantics.

Oh ... What about
```
CREATE TABLE x1 (i RAW(15));
INSERT INTO x1 VALUES ('4990673643343740511841223171');
```
![изображение](https://github.com/laurenz/oracle_fdw/assets/41448637/10512c89-a0ac-4c5b-b021-dcb88cae917c)
? I think in this case oracle_fdw can throw an error, isn't it?

**Comment by laurenz** [comment]
But that already throws an error:

```none
ERROR:  invalid input syntax for type uuid: "000102030405060708090001020304"
CONTEXT:  converting column "u" for foreign table scan of "raws", row 1
```

I think there is nothing to improve.

**Comment by laurenz** [comment]
I don't think that's worth the effort.

**Comment by mkgrgis** [comment]
Thanks for your FDW, @laurenz !
I am sorry for bad research.

**Comment by laurenz** [comment]
Don't be sorry. I am grateful for this discussion!
Somebody cares about my code!
