### ISSUE TITLE
Can you provide download link for oracle_fdw which has compatibility with psql (PostgreSQL) 9.4.24? Thanks!

### ISSUE THREAD

**Issue by J3throSanidad** [laurenz/oracle_fdw#601]

**Comment by mkgrgis** [comment]
Hello @J3throSanidad , what about https://github.com/laurenz/oracle_fdw/tags ? This is common github tradition to save history of repositories as releases.

**Comment by J3throSanidad** [comment]
> Hello @J3throSanidad , what about https://github.com/laurenz/oracle_fdw/tags ? This is common github tradition to save history of repositories as releases.

Hello, I checked with chatgpt the correct version of oracle_fdw for postgresql 9.4.24 and it is saying that the version shoud be 1.8.1. In laurenz's repositories, there is only ORACLE_FDW_2_0_0 and ORACLE_FDW_1_5_0. Both are encountering errors in 'make' command.

make
gcc -m64 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99   -Werror=uninitialized -Werror=implicit-function-declaration -fPIC -I"/sdk/include" -I"/oci/include" -I"/rdbms/public" -I"/"  -I. -I./ -I/usr/local/greenplum-db-6.7.1/include/postgresql/server -I/usr/local/greenplum-db-6.7.1/include/postgresql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/include  -c -o oracle_fdw.o oracle_fdw.c
oracle_fdw.c: In function ‘oracleGetForeignRelSize’:
oracle_fdw.c:881:3: error: too few arguments to function ‘clauselist_selectivity’
   ntuples = ntuples * clauselist_selectivity(root, baserel->baserestrictinfo, 0, JOIN_INNER, NULL);
   ^
In file included from oracle_fdw.c:53:0:
/usr/local/greenplum-db-6.7.1/include/postgresql/server/optimizer/cost.h:225:20: note: declared here
 extern Selectivity clauselist_selectivity(PlannerInfo *root,
                    ^
oracle_fdw.c: In function ‘oracleIterateForeignScan’:
oracle_fdw.c:1393:38: error: ‘TupleTableSlot’ has no member named ‘tts_values’
   convertTuple(fdw_state, index, slot->tts_values, slot->tts_isnull, false);
                                      ^
oracle_fdw.c:1393:56: error: ‘TupleTableSlot’ has no member named ‘tts_isnull’
   convertTuple(fdw_state, index, slot->tts_values, slot->tts_isnull, false);
                                                        ^
oracle_fdw.c: In function ‘oracleExecForeignInsert’:
oracle_fdw.c:2094:34: error: ‘TupleTableSlot’ has no member named ‘tts_values’
   convertTuple(fdw_state, 1, slot->tts_values, slot->tts_isnull, false);
                                  ^
oracle_fdw.c:2094:52: error: ‘TupleTableSlot’ has no member named ‘tts_isnull’
   convertTuple(fdw_state, 1, slot->tts_values, slot->tts_isnull, false);
                                                    ^
oracle_fdw.c: In function ‘oracleExecForeignUpdate’:
oracle_fdw.c:2144:34: error: ‘TupleTableSlot’ has no member named ‘tts_values’
   convertTuple(fdw_state, 1, slot->tts_values, slot->tts_isnull, false);
                                  ^
oracle_fdw.c:2144:52: error: ‘TupleTableSlot’ has no member named ‘tts_isnull’
   convertTuple(fdw_state, 1, slot->tts_values, slot->tts_isnull, false);
                                                    ^
oracle_fdw.c: In function ‘oracleExecForeignDelete’:
oracle_fdw.c:2194:34: error: ‘TupleTableSlot’ has no member named ‘tts_values’
   convertTuple(fdw_state, 1, slot->tts_values, slot->tts_isnull, false);
                                  ^
oracle_fdw.c:2194:52: error: ‘TupleTableSlot’ has no member named ‘tts_isnull’
   convertTuple(fdw_state, 1, slot->tts_values, slot->tts_isnull, false);
                                                    ^
make: *** [oracle_fdw.o] Error 1

**Comment by philflorent** [comment]
Hi,

I don't know how ChatGPT concluded you need oracle_fdw 1.8 but I read at the main page chapter 5. Installation requirements that "PostgreSQL 9.3 or better is required." 

It should apply to the latest released version (2.5) if the sentence is up-to-date. Imo don't waste your time looking for oracle_fdw 1.8 (I am pretty sure ChatGPT was wrong in this case) and investigate another issue. 

For example I read "Greenplum" , I suppose it's some commercial database based on PostgreSQL but are you sure it's really 100% PostgreSQL compatible ?
I read
"You will need PostgreSQL headers and PGXS installed (if your PostgreSQL was installed with packages, install the development package)."
and also
"oracle_fdw is written for standard open source PostgreSQL. Forks of PostgreSQL, such as "PostgresPro" and "Postgres-XL", are likely to be incompatible. If you want to try it nonetheless, you'll have to build oracle_fdw from source. If you encounter problems while using such a PostgreSQL-derived server, please try with the original version before reporting an issue."

Perhaps Greenplum can provide you what is missing if you are a customer ?

Best regards,
Phil
