### ISSUE TITLE
Unhandled Oracle Datatype

### ISSUE THREAD

**Issue by abap64** [laurenz/oracle_fdw#602]
I am facing an unhandled Oracle datatype, "NCLOB".
Is there any way to ask "oracle_fdw" to act as if it were a CLOB ?

DETAIL : column "output" (25) of foreign table "short" cannot be converted to or from Oracle data type (22):

**Comment by laurenz** [comment]
I cannot handle an `NCLOB` as if it were a `CLOB`, because Oracle handles encoding differently for this data type.
I figured that out when I first wrote oracle_fdw, so I don't have a reference to the Oracle documentation handy.

I am not fundamentally opposed to supporting `NCLOB`, but it is low on my priority list, and it might be difficult.
Is it possible to write a statement like this in Oracle:

     SELECT CAST (nclob_col AS CLOB) FROM tab;

If yes, I could suggest a workaround to you.

**Comment by abap64** [comment]
Thanks for your answer
I was not sure that would be a very relevant to add this problem into issues list.
I am working with ora_migrator, and i was on the way to use to_clob to modify columns datatype into oracle database before calling "db_migrate".
"CAST(col as CLOB)" doesn't seem to handle NCLOB either.

**Comment by laurenz** [comment]
It's certainly fine for you to request that enhancement, and I admin that this lack can be annoying.
If somebody can figure out how to do it and wants to implement NCLOB support, and it is not too complicated, great. But I myself don't feel motivated.

How about using `to_clob()` to convert the NCLOB to a CLOB in Oracle?
I have never been able to understand the point of NCLOB. As far as I know, CLOBs always use a Unicode encoding internally, so they should be good for all characters.

**Comment by abap64** [comment]
I don't understand either, in database i am working on, Oracle tables has been made by a java ORM and NCLOB columns were dedicated to store json objects.
It look like that some ORM use oracle datatypes likes NVARCHAR, NCLOB (I heard the same about django). 
Maybe it's way to avoid depending on Oracle database characterset.

**Comment by laurenz** [comment]
How about using `to_clob()` to convert the NCLOB to a CLOB in Oracle?

**Comment by abap64** [comment]
That's what i am going to use, i just wanted to avoid one more step in my migration process.

**Comment by laurenz** [comment]
Sorry. But at least you have a workaround.
