### ISSUE TITLE
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle

### ISSUE THREAD

**Issue by J3throSanidad** [laurenz/oracle_fdw#606]
I recently installed the oracle_fdw. We're able to create the foreign tables to access the oracle tables. However, we encountered the error in the subject line. Hopefully you can help us with this issue. Below is the sequence of my steps. Thanks!

```
[gpadmin@gbpi-fmstr-uat-danalytics-01 ~]$ psql postgres
psql (9.4.24)
Type "help" for help.

postgres=# \dx
                        List of installed extensions
    Name    | Version |   Schema   |              Description
------------+---------+------------+----------------------------------------
 oracle_fdw | 1.2     | public     | foreign data wrapper for Oracle access
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)
```

Below is the oracle foreign server that I created:

```
postgres=# \desc+
                                                             List of foreign servers
 Name |  Owner  | Foreign-data wrapper | Access privileges | Type | Version |                     F
DW Options                      | Description
------+---------+----------------------+-------------------+------+---------+----------------------
--------------------------------+-------------
 uat  | gpadmin | oracle_fdw           |                   |      |         | (dbserver 'oraosi-uat
[trgt.gardenia.com.ph:1521/UAT](http://trgt.gardenia.com.ph:1521/UAT)') |
(1 row)
```

Below is the created user mapping:

```
postgres=# \deu+
                  List of user mappings
 Server | User name |             FDW Options
--------+-----------+-------------------------------------
 uat    | gpadmin   | ("user" 'apps', password 'apps')
(1 row)

postgres=#
```

Below is the creation of the foreign table:

```
CREATE FOREIGN TABLE xle_entity_profiles_test1 (
    name character varying (240)
)
SERVER uat
OPTIONS (
    schema 'apps',
    table 'xle_entity_profiles'
);
```

When I'm trying to query the foreign table, I'm having the issue below:

```
postgres=# select count(*) from xle_entity_profiles_test1;
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
```

**Comment by laurenz** [comment]
This is a generic error that means that something is wrong with how you set up Oracle.

Please look at [#307](https://github.com/laurenz/oracle_fdw/issues/307#issuecomment-482670284) and the many issues linked from there. See if one of these issues solves your problem.

In particular, see if you can connect using `sqlplus` from the command line of the `postgres` operating system user.

**Comment by J3throSanidad** [comment]
Hello,

Per checking, I encountered below when running sqlplus:

[gpadmin@gbpi-fmstr-uat-danalytics-01 lib]$ sqlplus
Error 6 initializing SQL*Plus
SP2-0667: Message file sp1<lang>.msb not found
SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory
[gpadmin@gbpi-fmstr-uat-danalytics-01 lib]$

My last action is copy the .so files below from /data/instantclient/instantclient_19_20 to /usr/local/greenplum-db-6.7.1/lib. 

libclntsh.so.19.1,  libnnz19.so, libclntshcore.so.19.1


After copying the said files, I was able to install the oracle_fdw extension. But it seems it disabled my sqlplus. I tried to remove the .so files from /data/instantclient/instantclient_19_20  and sqlplus worked again.

[gpadmin@gbpi-fmstr-uat-danalytics-01 lib]$ mv libclntsh.so.19.1 backup_so/
[gpadmin@gbpi-fmstr-uat-danalytics-01 lib]$ mv libnnz19.so backup_so/
[gpadmin@gbpi-fmstr-uat-danalytics-01 lib]$ mv libclntshcore.so.19.1 backup_so/

[gpadmin@gbpi-fmstr-uat-danalytics-01 lib]$ sqlplus apps/appss@UAT

SQL*Plus: Release 19.0.0.0.0 - Production on Mon Sep 11 11:32:12 2023
Version 19.20.0.0.0

Copyright (c) 1982, 2022, Oracle.  All rights reserved.

Last Successful login time: Mon Sep 11 2023 09:41:36 +08:00

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.15.0.0.0

SQL>

**Comment by J3throSanidad** [comment]
By the way, I also set up the following variables:

[gpadmin@gbpi-fmstr-uat-danalytics-01 instantclient]$ export PATH=$PATH:/data/instantclient/instantclient_19_20/
[gpadmin@gbpi-fmstr-uat-danalytics-01 instantclient]$ export ORACLE_HOME=/data/instantclient/instantclient_19_20/
[gpadmin@gbpi-fmstr-uat-danalytics-01 instantclient]$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME:$ORACLE_HOME/sdk/include
[gpadmin@gbpi-fmstr-uat-danalytics-01 instantclient]$ export TNS_ADMIN=$ORACLE_HOME/network/admin

**Comment by laurenz** [comment]
So, does `sqlplus` work with these environment variables?

Then make sure you also have the variables set in the environment of your PostgreSQL server process. How to look at the environment of the PostgreSQL server and how to set an environment variable there is amply covered in the issues linked from #307.

**Comment by laurenz** [comment]
If you are using https://github.com/adam8157/oracle_fdw_greenplum rather than oracle_fdw, why do you bother opening an issue here? I'll close it as off-topic.

Anyway, you shouldn't copy libraries around. The fact that PostgreSQL couldn't find `libclntsh.so.19.1` or one of its dependent libraries proves that you didn't manage to set `LD_LIBRARY_PATH` correctly in the environment of the database server.

**Comment by chrullrich** [comment]
(@laurenz I was literally writing this reply when you closed the issue. I'd rather not throw it away.)

> We are using greenplum database. As far as my understanding, is it also based in postgre sql. Please see below the steps that we performed until we reached the issue.

It is, but using `oracle_fdw` with forks of PostgreSQL is always a bit prone to trouble.

> Install the https://github.com/adam8157/oracle_fdw_greenplum

Are you aware that this fork of `oracle_fdw` is more than three years old?

I also note that the "maintainer" of the fork has disabled creating bugs against his fork so people come here.

> postgres=# create extension oracle_fdw;
> ERROR: could not load library "/usr/local/greenplum-db-6.7.1/lib/postgresql/oracle_fdw.so": libclntsh.so.19.1: cannot open shared object file: No such file or directory (dfmgr.c:240)
> postgres=#
> 
> Per Adam Lee, the command is looking for the .so libclntsh.so.19.1. I copied the libclntsh.so.19.1 from /data/instantclient/instantclient_19_20/
[...]

Copying libraries does not work. As Laurenz mentioned above, you must put the original Instant Client installation on the server's `$LD_LIBRARY_PATH`.

**Comment by laurenz** [comment]
@chrullrich You are free to reopen the issue.

> I also note that the "maintainer" of the fork has disabled creating bugs against his fork so people come here.

That is convenient for the author, but I won't support his code. I have enough on my hands with the spaghetti that is oracle_fdw...

**Comment by chrullrich** [comment]
> @chrullrich You are free to reopen the issue.

Heck no :-).

**Comment by J3throSanidad** [comment]
Hi @chrullrich , do you have an idea where to get this libraries?

libclntsh.so.19.1
libnnz19.so
libclntshcore.so.19.1

The files above that I copied came from this zip files:

instantclient-basic-linux.x64-19.20.0.0.0dbru.zip
instantclient-sdk-linux.x64-19.20.0.0.0dbru.zip
instantclient-sqlplus-linux.x64-19.20.0.0.0dbru.zip

@laurenz , I checked Adam Lee's github but unfortuately, there is no issue tab in his greenplum_oracle_fdw. I already have a conversation with him via email but he asked me to check the issue with github.

**Comment by chrullrich** [comment]
The libraries are fine where they ended up when you extracted the zip archive. You need to tell the PostgreSQL server where that is. Please google `LD_LIBRARY_PATH linux` for more information on what it is and how to modify it.

Also remove the copies you made; it will not work as long as they are in the databases `lib` directory.

**Comment by laurenz** [comment]
Some literature for you about setting `LD_LIBRARY_PATH` or configuring the library path in other ways on the PostgreSQL server: https://github.com/laurenz/oracle_fdw/issues/358#issuecomment-544901981, https://github.com/laurenz/oracle_fdw/issues/394#issuecomment-625246827, #161 and #322.

**Comment by J3throSanidad** [comment]
Hello,

@laurenz @chrullrich . Showing to you the current setup of our bash_profile and bashrc

bash_profile

# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

source /usr/local/greenplum-db/greenplum_path.sh
export MASTER_DATA_DIRECTORY=/data/master/gpseg-1
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-1.el7_9.x86_64/jre/


bashrc

# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# Shorthand / Shortcuts
alias c='clear'
alias pxf=/usr/local/greenplum-db/pxf/bin/pxf

# Greenplum
export MASTER_DATA_DIRECTORY=/data/master/gpseg-1
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-1.el7_9.x86_64/jre/

# Use vs-code as crontab editor
export VISUAL=~/code-wait.sh
export EDITOR=~/code-wait.sh

As an additional information, this postgresql / greenplum database is already extracting data from MS SQL. This has been setup by our vendor years ago (unfortunately, we don't have support contract with them). I also check the /usr/local/greenplum-db/greenplum_path.sh contents and I found out that there is an LD_LIBRARY setup there. I'm not sure if I should modify it since it might effect the already working connection with MS SQL.

Also showing to you the /usr/local/greenplum-db/greenplum_path.sh contents:

GPHOME=/usr/local/greenplum-db-6.7.1

# Replace with symlink path if it is present and correct
if [ -h ${GPHOME}/../greenplum-db ]; then
    GPHOME_BY_SYMLINK=`(cd ${GPHOME}/../greenplum-db/ && pwd -P)`
    if [ x"${GPHOME_BY_SYMLINK}" = x"${GPHOME}" ]; then
        GPHOME=`(cd ${GPHOME}/../greenplum-db/ && pwd -L)`/.
    fi
    unset GPHOME_BY_SYMLINK
fi
#setup PYTHONHOME
if [ -x $GPHOME/ext/python/bin/python ]; then
    PYTHONHOME="$GPHOME/ext/python"
    export PYTHONHOME
fi
PYTHONPATH=$GPHOME/lib/python
PATH=$GPHOME/bin:$PYTHONHOME/bin:$PATH
LD_LIBRARY_PATH=$GPHOME/lib:$PYTHONHOME/lib:${LD_LIBRARY_PATH-}
export LD_LIBRARY_PATH
if [ -e $GPHOME/etc/openssl.cnf ]; then
OPENSSL_CONF=$GPHOME/etc/openssl.cnf
export OPENSSL_CONF
fi
export GPHOME
export PATH
export PYTHONPATH


Your help will be greatly appreciated. Thank you!

**Comment by J3throSanidad** [comment]
Kindly ignore the bold letters. Not sure why it was there. My comment didn't include the bold letters. Thanks.

**Comment by laurenz** [comment]
Please check if `ld_library_path` and other environment variables you need to make Oracle work are set in the environment of the database server:

```bash
cat /proc/32288/environ | xargs -n 1 -0
```

(Replace 32288 with the database server process number).

If they are not set, as we suspect, please tell us exactly how the Greenplum server is started.

**Comment by J3throSanidad** [comment]
Hello,

Can you check if I get the correct process id?

[root@gbpi-fmstr-uat-danalytics-01 3374]# ps -ef |grep postgres
gpadmin    3374      1  0 Sep11 ?        00:00:39 /usr/local/greenplum-db-6.7.1/bin/postgres -D /data/master/gpseg-1 -p 5432 -E

[root@gbpi-fmstr-uat-danalytics-01 3374]# cat /proc/3374/environ | xargs -n 1 -0
XDG_SESSION_ID=14
HOSTNAME=gbpi-fmstr-uat-danalytics-01
GPERA=902ce8fe102d8b4e_230911151528
MASTER_DATA_DIRECTORY=/data/master/gpseg-1
TERM=xterm
SHELL=/bin/bash
HISTSIZE=1000
SSH_CLIENT=192.168.13.216 56690 22
PG_GRANDPARENT_PID=3273
GPHOME=/usr/local/greenplum-db/.
SSH_TTY=/dev/pts/0
USER=gpadmin
LD_LIBRARY_PATH=/usr/local/greenplum-db/./lib:/usr/local/greenplum-db/./ext/python/lib:
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
MAIL=/var/spool/mail/gpadmin
PATH=/usr/local/greenplum-db/./bin:/usr/local/greenplum-db/./ext/python/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/gpadmin/.local/bin:/home/gpadmin/bin
_=/usr/bin/env
PWD=/home/gpadmin
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-1.el7_9.x86_64/jre/
EDITOR=/home/gpadmin/code-wait.sh
LANG=en_US.UTF-8
PYTHONHOME=/usr/local/greenplum-db/./ext/python
PGSYSCONFDIR=/usr/local/greenplum-db-6.7.1/etc/postgresql
HISTCONTROL=ignoredups
SHLVL=2
HOME=/home/gpadmin
PYTHONPATH=/usr/local/greenplum-db/./lib/python
LOGNAME=gpadmin
GPSESSID=0000000000
VISUAL=/home/gpadmin/code-wait.sh
SSH_CONNECTION=192.168.13.216 56690 10.16.24.150 22
PGDATA=/data/master/gpseg-1
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/1001
[root@gbpi-fmstr-uat-danalytics-01 3374]#

**Comment by laurenz** [comment]
Looks good. You see that `LD_LIBRARY_PATH` does not include the Oracle client libraries, and no Oracle environment variables are set.

Now you'll have to figure out how Greenplum is started and change that startup process so that the correct environment is set.

**Comment by J3throSanidad** [comment]
I see. Just to confirm, currently the LD_LIBRARY_PATH is currently set to /usr/local/greenplum-db/./lib:/usr/local/greenplum-db/./ext/python/lib:....  If we changed this, it might affect the connection to MS SQL? Also do you have an idea if oracle_fdw can be setup along with MS SQL (pxf)?

**Comment by laurenz** [comment]
I have no information about that. You'll have to try and see what happens.

**Comment by J3throSanidad** [comment]
Hi Laurenz,

I'm able to extract 1 column specifically in xle_entity_profiles table from Oracle. Do you have an idea on how I can extract data from all columns of a specific table? So far I'm able to research is importing all tables from a specific schema.

postgres=# IMPORT FOREIGN SCHEMA "ORA_USER" FROM SERVER ora_sv INTO imp_schema;
IMPORT FOREIGN SCHEMA

**Comment by J3throSanidad** [comment]
Hello,

I setup the LD_LIBRARY_PATH as suggested by adding the /data/instantclient/instantclient_19_20/ directory. So far it didn't affect the extraction of data from ms sql database. Also, I realized that I should be creating the oracle_fdw extension to another database (not postgre). Below are my other steps:

export PATH=$PATH:/data/instantclient/instantclient_19_20/
export ORACLE_HOME=/data/instantclient/instantclient_19_20/
export TNS_ADMIN=$ORACLE_HOME/network/admin

psql omdfs_dw

omdfs_dw=# create extension oracle_fdw;
CREATE EXTENSION

Check if the oracle_fdw extension has been installed:

omdfs_dw=# \dx
                            List of installed extensions
    Name    | Version |   Schema   |                   Description

------------+---------+------------+--------------------------------------------
-----
 oracle_fdw | 1.2     | public     | foreign data wrapper for Oracle access
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
 pxf        | 1.0     | public     | Extension which allows to access unmanaged
data
(3 rows)

Create server:

omdfs_dw=# create server uat foreign data wrapper oracle_fdw options (dbserver 'oraosi-uattrgt.gardania.com.ph:1521/UAT');
CREATE SERVER

omdfs_dw=# create user mapping for gpadmin server uat options (user 'apps', password 'apps');
CREATE USER MAPPING

omdfs_dw=# CREATE FOREIGN TABLE xle_entity_profiles_test1 (
omdfs_dw(#     name character varying (240)
omdfs_dw(# )
omdfs_dw-# SERVER uat
omdfs_dw-# OPTIONS (
omdfs_dw(#     schema 'apps',
omdfs_dw(#     table 'xle_entity_profiles'
omdfs_dw(# );
CREATE FOREIGN TABLE
omdfs_dw=# select count(*) from xle_entity_profiles_test1;
ERROR:  Oracle table "apps"."xle_entity_profiles" for foreign table "xle_entity_profiles_test1" does not exist or does not allow read access
DETAIL:  ORA-00942: table or view does not exist
HINT:  Oracle table names are case sensitive (normally all uppercase).
omdfs_dw=#

According to below, change the schema and table to all caps (CAPITAL LETTERS).

https://www.postgresql.fastware.com/postgresql-insider-fdw-ora-bas

CREATE FOREIGN TABLE xle_entity_profiles_test1 (
name character varying (240)
)
SERVER uat
OPTIONS (
schema 'APPS',
table 'XLE_ENTITY_PROFILES'
);

Above I tried to get only 1 column and it works. On my next table creations, I included all the columns though I include them in my  code one by one including their corresponding datatypes. I think for now, I'm ok with this approach. Thank you very much for the assistance. Should I need help again, I will just log another issue log :)

**Comment by laurenz** [comment]
Thanks.
Setting the environment variables with `export` in the shell normally only works if you start the PostgreSQL server manually with `pg_ctl start` or `postgres` in the shell where you set the environment variables.

But thanks for the feedback, and I am glad you could make progress.
