### ISSUE TITLE
‘Value’ undeclared

### ISSUE THREAD

**Issue by LucRobberechts** [laurenz/oracle_fdw#607]
Hello,

when trying to install oracle_fdw 2.4.0 On an Oracle Linux 8.8 I receive following error messages when I run the "make" command

oracle_fdw.c: In function ‘oracle_fdw_validator’:
oracle_fdw.c:499:30: error: ‘Value’ undeclared (first use in this function); did you mean ‘false’?
    (void)getIsolationLevel(((Value *)(def->arg))->val.str);
                              ^~~~~
                              false

Any idea what is going wrong or what I should do to fix this?
I tried with Oracle instant client 12.2 and 19.20

Regards,
Luc Robberechts

**Comment by laurenz** [comment]
The oracle_fdw version you are using is too old for the (unspecified) PostgreSQL version on that system.
You will need an oracle_fdw version that includes commit 32df3c082f6adf4851166cc0e2f9fc6c625cc9cb, so at least 2.5.0.
I recommend using the latest version (2.6.0).

**Comment by laurenz** [comment]
Did that resolve the problem?

**Comment by LucRobberechts** [comment]
Hello,

yes, this has been solved now.  I was just working with an older version, I was not aware of the fact that there was already a new version.

Met vriendelijke groeten,
Cordialement,
Kind regards,

***@***.***
Luc Robberechts
Co-Founder

M
+32 472 900 684
E
***@***.*** ***@***.***>
W
hieda.be <https://www.hieda.be/?utm_source=signature&utm_medium=mail&utm_campaign=personal_signature>

**Comment by laurenz** [comment]
Thanks for the feedback!
