### ISSUE TITLE
IMPORT FOREIGN SCHEMA "SYS" 

### ISSUE THREAD

**Issue by prensgold** [laurenz/oracle_fdw#608]
Hi ,

When I want to show the following views from Oracle in Postgres, it creates some 11 of them.
However, I could not create it even though I tried constantly in other views.
I don't get any errors either. I couldn't find where the problem was.

IMPORT FOREIGN SCHEMA "SYS" LIMIT TO (DBA_SEGMENTS, DBA_OBJECTS,  DBA_INDEXES, DBA_IND_COLUMNS, DBA_CONSTRAINTS, DBA_CONS_COLUMNS, GLOBAL_NAME, DBA_TABLES, DBA_IND_EXPRESSIONS, DBA_IND_PARTITIONS, DBA_TAB_COLUMNS, DBA_SEQUENCES, DBA_TAB_PARTITIONS, DBA_PART_KEY_COLUMNS, DBA_MVIEWS, V_$NLS_PARAMETERS,  DBA_STAT_EXTENSIONS, V_$VERSION, ALL_PROCEDURES, ALL_ARGUMENTS) 
FROM SERVER oradb INTO oracle_schema_compare;

Tables that can be created
<img width="189" alt="image" src="https://github.com/laurenz/oracle_fdw/assets/118886124/c0910106-b587-4294-9693-d8525f221749">

When I try to recreate a created foreign table, I get an error. However, even though I try to create a foreign table that is not created, I do not get an error either. I could not find where the problem is.

[postgres@lprdgovtb01 scripts_pg]$ psql
psql (15.2)

bkmgo=# IMPORT FOREIGN SCHEMA "SYS" LIMIT TO (all_arguments) FROM SERVER oradb INTO oracle_schema_compare;
ERROR:  relation "all_arguments" already exists
CONTEXT:  importing foreign table "all_arguments"
bkmgo=# IMPORT FOREIGN SCHEMA "SYS" LIMIT TO ( v_$version) FROM SERVER oradb INTO oracle_schema_compare;
IMPORT FOREIGN SCHEMA
bkmgo=# IMPORT FOREIGN SCHEMA "SYS" LIMIT TO ( v_$version) FROM SERVER oradb INTO oracle_schema_compare;
IMPORT FOREIGN SCHEMA
bkmgo=# IMPORT FOREIGN SCHEMA "SYS" LIMIT TO ( v_$version) FROM SERVER oradb INTO oracle_schema_compare;
IMPORT FOREIGN SCHEMA
bkmgo=#

**Comment by prensgold** [comment]
SELECT oracle_diag('oradb');
                                      oracle_diag                                       
----------------------------------------------------------------------------------------
 oracle_fdw 2.5.0, PostgreSQL 15.2, Oracle client 19.20.0.0.0, Oracle server 19.0.0.0.0
(1 row)

SELECT oracle_diag();
                                                 oracle_diag                                                  
--------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.5.0, PostgreSQL 15.2, Oracle client 19.20.0.0.0, ORACLE_HOME=/usr/lib/oracle/19.20/client64/lib
(1 row)

**Comment by laurenz** [comment]
What oracle_fdw does when it executes `IMPORT FOREIGN SCHEMA` is to look for the tables in `ALL_TAB_COLUMNS`. Whether you can see a table or view there depends on your permissions. It seems that you are using an Oracle user who has permissions to see `DBA_OBJECTS`, but not `DBA_INDEXES` in that view.

You can try yourself by running the following on Oracle:

```
SELECT col.table_name, col.column_name, col.data_type, col.data_type_owner,
       col.char_length, col.data_precision, col.data_scale, col.nullable,
       CASE WHEN primkey_col.position IS NOT NULL THEN 1 ELSE 0 END AS primary_key
FROM all_tab_columns col,
     (SELECT con.table_name, cons_col.column_name, cons_col.position
      FROM all_constraints con, all_cons_columns cons_col
      WHERE con.owner = cons_col.owner AND con.table_name = cons_col.table_name
        AND con.constraint_name = cons_col.constraint_name
        AND con.constraint_type = 'P' AND con.owner = 'SYS') primkey_col
WHERE col.table_name = primkey_col.table_name(+) AND col.column_name = primkey_col.column_name(+)
  AND col.owner = 'SYS'
  AND col.table_name = 'DBA_INDEXES'
ORDER BY col.table_name, col.column_id;
```

You need to use an Oracle user who has sufficient permissions to get a result for this query.

**Comment by prensgold** [comment]
What confuses me here is that the user I am running has dba permission.
It can also run the above query in Oracle.
I'm not too far from the current version.
I couldn't figure it out.

**Comment by laurenz** [comment]
I am testing on Oracle 18, but I would be surprised if the permission system changed.

I cannot debug your system, so I am trying to tell you how it works, to help you figure out what is going on. The FDW just runs the query I quoted above (without the last but one line with the condition on `table_name`) to figure out all tables and views and their columns that can potentially be imported. The PostgreSQL end then filters away those tables that don't appear in the `LIMIT TO` clause. So if a table or view is not imported, that can either be because it does not match the `LIMIT TO` clause or because it is not returned by the query.

I would double check the user used in the user mapping. Since you mention "dba permission", what exactly do you mean by that? oracle_fdw does not connect `AS SYSDBA`.

**Comment by prensgold** [comment]
DBA role is one of the most authorized user rights in Oracle.
It cannot only close and open the database. DBA user can easily perform other DML DDL operations on the database.

I could not import v_$version to Postgres.
I ran the query you sent for this table as well, with the ora2pg user (having the dba role).
It returns results in Oracle database.

<img width="482" alt="image" src="https://github.com/laurenz/oracle_fdw/assets/118886124/1ba9475e-64c3-4fb2-83bb-e7d38df283b3">


<img width="636" alt="image" src="https://github.com/laurenz/oracle_fdw/assets/118886124/d6cfeed2-30df-46d2-a6b4-65ffaffc2254">

<img width="211" alt="image" src="https://github.com/laurenz/oracle_fdw/assets/118886124/7afa7028-e80c-4263-8b3a-93b4041a49b0">

**Comment by laurenz** [comment]
I assume you are talking about membership in the role `DBA`, right?

I tried with a user that is just member of role `DBA`, but the metadata query for `IMPORT FOREIGN SCHEMA` never finishes, so I cannot tell you if it would work for me or not.

I don't know why you are getting different results if you are using the same Oracle user with oracle_fdw and with your interactive Oracle client. A possible workaround would be to define the foreign tables manually with `CREATE FOREIGN TABLE`.

**Comment by prensgold** [comment]
I was able to create it manually.
As the number of tables and columns that I have to create manually increases, the possibility of making mistakes in manual editing may be high.
Is there a script that I can generate create foreing table scripts in Oracle?

**Comment by prensgold** [comment]
I created a function with your query as follows.
But it just wrote the following line.
I think I'm making a mistake while returning column information in the function.

CREATE FOREIGN TABLE dba_indexes ();

```
CREATE OR REPLACE FUNCTION generate_foreign_table_script (
    p_table_name   IN VARCHAR2)
    RETURN VARCHAR2
IS
    v_script   VARCHAR2 (32767)
        :=    'CREATE FOREIGN TABLE '
           || LOWER (p_table_name)
           || ' ('
           || CHR (10);
BEGIN
    FOR col
        IN (SELECT LOWER (col.column_name)    AS column_name,
                   col.data_type,
                   col.data_type_owner,
                   col.char_length,
                   col.data_precision,
                   col.data_scale,
                   col.nullable,
                   CASE
                       WHEN primkey_col.position IS NOT NULL THEN 1
                       ELSE 0
                   END                        AS primary_key
              FROM all_tab_columns  col,
                   (SELECT con.table_name,
                           cons_col.column_name,
                           cons_col.position
                      FROM all_constraints con, all_cons_columns cons_col
                     WHERE     con.owner = cons_col.owner
                           AND con.table_name = cons_col.table_name
                           AND con.constraint_name = cons_col.constraint_name
                           AND con.constraint_type = 'P'
                           AND con.owner = 'SYS') primkey_col
             WHERE     col.table_name = primkey_col.table_name(+)
                   AND col.column_name = primkey_col.column_name(+)
                   AND col.owner = 'SYS'
                   AND col.table_name = p_table_name)
    LOOP
        v_script := v_script || ' ' || col.column_name || ' ';

        CASE col.data_type
            WHEN 'CHAR'
            THEN
                v_script :=
                       v_script
                    || 'character('
                    || NVL (col.char_length, 1)
                    || ')';
            WHEN 'NCHAR'
            THEN
                v_script :=
                       v_script
                    || 'character('
                    || NVL (col.char_length, 1)
                    || ')';
            WHEN 'VARCHAR2'
            THEN
                v_script :=
                       v_script
                    || 'character varying('
                    || NVL (col.char_length, 1)
                    || ')';
            WHEN 'NVARCHAR2'
            THEN
                v_script :=
                       v_script
                    || 'character varying('
                    || NVL (col.char_length, 1)
                    || ')';
            WHEN 'CLOB'
            THEN
                v_script := v_script || 'text';
            WHEN 'LONG'
            THEN
                v_script := v_script || 'text';
            WHEN 'NUMBER'
            THEN
                IF col.data_precision = 0
                THEN
                    IF col.data_scale = 0
                    THEN
                        v_script := v_script || 'numeric';
                    ELSIF col.data_precision < 5
                    THEN
                        v_script := v_script || 'smallint';
                    ELSIF col.data_precision < 10
                    THEN
                        v_script := v_script || 'integer';
                    ELSIF col.data_precision < 19
                    THEN
                        v_script := v_script || 'bigint';
                    ELSE
                        v_script :=
                               v_script
                            || 'numeric('
                            || col.data_precision
                            || ')';
                    END IF;
                ELSE
                    v_script :=
                           v_script
                        || 'numeric('
                        || GREATEST (col.data_precision, col.data_scale)
                        || ','
                        || col.data_scale
                        || ')';
                END IF;
            WHEN 'FLOAT'
            THEN
                IF col.data_precision < 54
                THEN
                    v_script :=
                        v_script || 'float(' || col.data_precision || ')';
                ELSE
                    v_script := v_script || 'numeric';
                END IF;
            WHEN 'BINARY_FLOAT'
            THEN
                v_script := v_script || 'real';
            WHEN 'BINARY_DOUBLE'
            THEN
                v_script := v_script || 'double precision';
            WHEN 'RAW'
            THEN
                v_script := v_script || 'bytea';
            WHEN 'BLOB'
            THEN
                v_script := v_script || 'bytea';
            WHEN 'BFILE'
            THEN
                v_script := v_script || 'bytea';
            WHEN 'LONG RAW'
            THEN
                v_script := v_script || 'bytea';
            WHEN 'DATE'
            THEN
                v_script := v_script || 'timestamp(0) without time zone';
            WHEN 'TIMESTAMP'
            THEN
                v_script :=
                       v_script
                    || 'timestamp('
                    || LEAST (col.data_scale, 6)
                    || ') without time zone';
            WHEN 'TIMESTAMP WITH TIME ZONE'
            THEN
                v_script :=
                       v_script
                    || 'timestamp('
                    || LEAST (col.data_scale, 6)
                    || ') with time zone';
            WHEN 'TIMESTAMP WITH LOCAL TIME ZONE'
            THEN
                v_script :=
                       v_script
                    || 'timestamp('
                    || LEAST (col.data_scale, 6)
                    || ') with time zone';
            WHEN 'INTERVAL DAY TO SECOND'
            THEN
                v_script :=
                       v_script
                    || 'interval('
                    || LEAST (col.data_scale, 6)
                    || ')';
            WHEN 'INTERVAL YEAR TO MONTH'
            THEN
                v_script := v_script || 'interval(0)';
            WHEN 'XMLTYPE'
            THEN
                v_script := v_script || 'xml';
            ELSE
                v_script := v_script || 'text';
        END CASE;

        IF col.nullable = 'Y'
        THEN
            v_script := v_script || ' NULL,' || CHR (10);
        ELSE
            v_script := v_script || ' NOT NULL,' || CHR (10);
        END IF;
    END LOOP;

    v_script := RTRIM (v_script, ',' || CHR (10)) || ');';

    RETURN v_script;
EXCEPTION
    WHEN OTHERS
    THEN
        RETURN NULL;
END;
/

DECLARE
v_foreign_table_script VARCHAR2(32767);
BEGIN
v_foreign_table_script := generate_foreign_table_script('DBA_INDEXES');
DBMS_OUTPUT.PUT_LINE(v_foreign_table_script);
END;
/
```

**Comment by laurenz** [comment]
I don't know why your Oracle function does not show you output. Perhaps you didn't configure your client to show output from `DBMS_OUTPUT.PUT:LINE()`? I'd simply run

    SELECT generate_foreign_table_script('DBA_INDEXES') FROM dual;

Yes, piecing together a `CREATE FOREIGN TABLE` statement manually if the table has many columns can be a pain. But you only have to do it once for each table.

**Comment by laurenz** [comment]
Shall we close the issue?
