### ISSUE TITLE
Option to disable adding MD5 to Oracle query to benefit from Oracle soft parse stage

### ISSUE THREAD

**Issue by rdnkrkmz** [laurenz/oracle_fdw#611]
From docs of "**Internal**" section.
"Therefore, **oracle_fdw adds a comment to the query that contains an MD5 hash of the query text.** This is used to search in V$SQL. The actual execution plan or cost information is retrieved from V$SQL_PLAN."

In our case, adding MD5 to every query causes in Oracle to hard parse very same statement sent by fdw.

Is there any option to disable adding MD5 to Oracle query to benefit from Oracle soft parse stage?

Thanks in advance.

**Comment by laurenz** [comment]
I need the hash to identify queries in the library cache.

If the query is the same, the hash will also be the same, so I am not sure where the problem is. Or are you using `CURSOR_SHARING = FORCE` in Oracle?

**Comment by rdnkrkmz** [comment]
Yes, `CURSOR_SHARING = FORCE`
Despite being set `cursor_sharing `to force, there are 70k+ unique queries in our OLTP db and causes pressure on `Shared Pool`.
On the other side, if Pg side do not use bind variable (we face this with .NET Core ORM) situation is worst.

**Comment by laurenz** [comment]
You could use this patch: [no_hash_patch.txt](https://github.com/laurenz/oracle_fdw/files/12780134/no_hash_patch.txt)

I am reluctant to make this an option, because it would break `EXPLAIN`, but you can run a patched version of oracle_fdw.

**Comment by rdnkrkmz** [comment]
Thank you.
But after applying patch and recompilig the extension, **yet we have again MD5 hashes in SQL Query.**
Here what our **oracle_fdw.c** file (patched one)
[oracle_fdw.txt](https://github.com/laurenz/oracle_fdw/files/12783327/oracle_fdw.txt)

New file is installed successfully as :

```
[root@pg ~]# ls -l /usr/pgsql-14/lib/oracle_fdw.so
-rwxr-xr-x. 1 root root 740920 Oct  2 16:39 /usr/pgsql-14/lib/oracle_fdw.so
```

**Comment by laurenz** [comment]
Well, it works for me:

```
EXPLAIN SELECT * FROM json;

                              QUERY PLAN                              
══════════════════════════════════════════════════════════════════════
 Foreign Scan on "json"  (cost=10000.00..20000.00 rows=1000 width=36)
   Oracle query: SELECT r1."ID", r1."J" FROM "JSON" r1
(2 rows)
```

Perhaps you didn't overwrite the correct `oracle_fdw.so`, or you didn't start a new PostgreSQL session after overwriting the library. If you have `oracle_fdw` in `shared_preload_libraries`, you need a PostgreSQL restart.

**Comment by rdnkrkmz** [comment]
After starting new connections, yes MD5 hash gone.
Thank you much.
