### ISSUE TITLE
oracle_fdw installation issue on postgres 15.2 on rhel 7.9

### ISSUE THREAD

**Issue by bindalsa** [laurenz/oracle_fdw#615]
We are installing oracle_fdw(2.6.0) on Postgres 15.3 on rhel 7.9 .  We need this to create dblink from postgres DB to Oracle DB .

We are getting below error :

```none
[root@atdsfxiseedodn2 oracle_fdw-ORACLE_FDW_2_6_0]# PATH=/usr/pgsql-15/bin:$PATH make
Makefile:30: /usr/pgsql-15/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/usr/pgsql-15/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.
```

Thanks
Saurabh

**Comment by bindalsa** [comment]
cd /opt/oracle/software/postgres/client19c/oracle_fdw/oracle_fdw-ORACLE_FDW_2_6_0/
export ORACLE_HOME=/opt/oracle/product/19.3/client_1
export LD_LIBRARY_PATH=$ORACLE_HOME/lib
export PATH=$ORACLE_HOME/bin:$ORACLE_HOME/perl/bin:$PATH
export PG_CONFIG=/usr/pgsql-15/bin
export PATH=/usr/pgsql-15/bin:$PATH
pg_config
=====================
-bash-4.2$ pg_config
BINDIR = /usr/pgsql-15/bin
DOCDIR = /usr/pgsql-15/doc
HTMLDIR = /usr/pgsql-15/doc/html
INCLUDEDIR = /usr/pgsql-15/include
PKGINCLUDEDIR = /usr/pgsql-15/include
INCLUDEDIR-SERVER = /usr/pgsql-15/include/server
LIBDIR = /usr/pgsql-15/lib
PKGLIBDIR = /usr/pgsql-15/lib
LOCALEDIR = /usr/pgsql-15/share/locale
MANDIR = /usr/pgsql-15/share/man
SHAREDIR = /usr/pgsql-15/share
SYSCONFDIR = /etc/sysconfig/pgsql
PGXS = /usr/pgsql-15/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE =  '--enable-rpath' '--prefix=/usr/pgsql-15' '--includedir=/usr/pgsql-15/include' '--mandir=/usr/pgsql-15/share/man' '--datadir=/usr/pgsql-15/share' '--libdir=/usr/pgsql-15/lib' '--with-lz4' '--with-zstd' '--enable-tap-tests' '--with-icu' '--with-llvm' '--with-perl' '--with-python' '--with-tcl' '--with-tclconfig=/usr/lib64' '--with-openssl' '--with-pam' '--with-gssapi' '--with-includes=/usr/include' '--with-libraries=/usr/lib64' '--enable-nls' '--enable-dtrace' '--with-uuid=e2fs' '--with-libxml' '--with-libxslt' '--with-ldap' '--with-selinux' '--with-systemd' '--with-system-tzdata=/usr/share/zoneinfo' '--sysconfdir=/etc/sysconfig/pgsql' '--docdir=/usr/pgsql-15/doc' '--htmldir=/usr/pgsql-15/doc/html' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' 'LDFLAGS=-Wl,--as-needed' 'LLVM_CONFIG=/usr/lib64/llvm5.0/bin/llvm-config' 'CLANG=/opt/rh/llvm-toolset-7/root/usr/bin/clang' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig' 'PYTHON=/usr/bin/python3'
CC = gcc -std=gnu99
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -L/usr/lib64/llvm5.0/lib -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-15/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lselinux -lzstd -llz4 -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lpthread -lrt -ldl -lm
VERSION = PostgreSQL 15.2
===========================================================

**Comment by laurenz** [comment]
You forgot to install `postgresql13-devel`.

**Comment by laurenz** [comment]
If you can tell me how exactly you installed PostgreSQL, I can tell you in more detail.

**Comment by bindalsa** [comment]
Hi Laurenz,

We have installed Postgres using RPMs , but now I am able to resolve this issue by install additional RPMs.
We can close this thread.

Thanks
Saurabh

**Comment by laurenz** [comment]
Thanks for the feedback.

**Comment by laurenz** [comment]
This is a duplicate of #390.
