### ISSUE TITLE
Change in maximum prefetch option between 2.5.0 and 2.6.0

### ISSUE THREAD

**Issue by olssojoe** [laurenz/oracle_fdw#617]
Hello, I'm wondering about the change in maximum prefetch option between 2.5.0 and 2.6.0, which goes from 10240 to 1000. Why has it changed, is it memory considerations involved? I've made some tests and it seem to have some performance effects for us. We currently use oracle_fdw 2.5.0 and Postgres 15.4 and all foreign tables have prefetch option set to 10240. I've tested a Postgres procedure that selects data from 24 tables in Oracle (pretty small and no long or lob columns) and inserts data in postgres tables. With the current configuration this takes around 10 seconds. When I tested with oracle_fdw 2.6.0 it increased to around 17 seconds. I've also made hacked version of oracle_fdw where I replaced the limit 1000 with the old 10240 and that got me back to around 10 seconds. We are a bit concerned about this change since we are about copy larger tables from Oracle in near future and we of course want to be able to upgrade oracle_fdw. Is it possible to increase the maximum prefetch value in future releases? Or should we consider something else when it comes to performance?

**Comment by laurenz** [comment]
Does this answer your question? Shall we close the issue?

**Comment by olssojoe** [comment]
Sorry for late reply, been on vacation. Yes you can close the issue.

Regards
Joel

Från: Laurenz Albe ***@***.***>
Skickat: den 25 oktober 2023 09:21
Till: laurenz/oracle_fdw ***@***.***>
Kopia: Joel Olsson ***@***.***>; Author ***@***.***>
Ämne: Re: [laurenz/oracle_fdw] Change in maximum prefetch option between 2.5.0 and 2.6.0 (Issue #617)


Does this answer your question? Shall we close the issue?
