### ISSUE TITLE
warning: implicit declaration of function 'bms_first_member'; did you mean 'bms_is_member'? [-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by LarsDohn** [laurenz/oracle_fdw#618]
Hi Laurenz and thanks for oracle_fdw; We use it a lot.
I'm on Oracle Linux 9.2 and installed postgres-16 + devel + oracle instant client 19.19.
Make install gives  
oracle_fdw.c:1611:39: warning: implicit declaration of function 'bms_first_member'; did you mean 'bms_is_member'? [-Wimplicit-function-declaration]
 1611 |                         while ((col = bms_first_member(updated_cols)) >= 0)
      |                                       ^~~~~~~~~~~~~~~~
      |                                       bms_is_member

Can you help ?
Regards
Lars Dohn

**Comment by laurenz** [comment]
Looks like you are using a version of oracle_fdw that doesn't have commit 2ad79b0df7f808af724cc57a123c21402ba83d4a. Upgrade to version 2.6.0 or use Git HEAD.

oracle_fdw uses a lot of internal APIs of PostgreSQL, which change (slightly) from version to version. You have to use a recent oracle_fdw with a recent PostgreSQL version.

**Comment by LarsDohn** [comment]
Downloaded new 260 source code; Works; Thanks ! Keep up the good work :-)
