### ISSUE TITLE
Filtering stops being pushed into WHERE clause 

### ISSUE THREAD

**Issue by SteveDirschelTR** [laurenz/oracle_fdw#619]
We have a procedure to copy data from an Oracle table to a Postgres table.  The Oracle table is daily range partitioned on CREATED_TIME.  The procedure will loop through and copy over I day of data and commit, then copy the next day and commit, and so on until it has copied all data it needs to.  This was initially tested going from Postgres to Postgres so postgres_fdw extension was used.  When I was initially testing this against the postgres_fdw extension a problem happened where when in the loop for the first few days of data to copy the query pushed to the remote postgres database would include WHERE CREATED_TIME >= value and CREATED_TIME < value but then suddenly it stopped pushing that CREATED_TIME filtering into the WHERE clause which caused the entire table to be full scanned rather than just the appropriate partition.  I was able to work-around that issue by doing an ALTER SERVER using OPTIONS ADD use_remote_estimate=true.  When that was done then every time it ran the query to pull 1 day of data it would always include CREATED_TIME in the WHERE clause.

Now I am trying to run the same procedure except this time the remote database is Oracle and I'm running into the same problem.  I can see the first 5 days in the loop it will include WHERE CREATED_TIME in the query but then on the 6th iteration it stops adding it (below shows the 6 queries it executed from the Oracle side- you will see the bottom one which is the last one it was executing has no WHERE clause).  I tried setting the use_remote_estimate = true option but it says that is not a valid option with oracle_fdw.  When it stops including CREATED_TIME in the WHERE clause performance is horrible because it's full scanning 300+ partitions on the Oracle side vs just scanning 1 partition.  What do I need to do to get the query to always push the CREATED_TIME into the WHERE clause?

Thanks

SELECT /*ce9b014b42e543d7*/ r3."SESSION_ID", r3."ONE_PASS_USER_NAME", r3."FIRST_NAME", r3."LAST_NAME", r3."EMAIL_ADDRESS", r3."EXPIRES_TIME", r3."SITE", r3."CREATED_TIME", r3."SESSION_EXPIRES_TIME", r3."PRISM_GUID", r3."SATOKEN", r3."SESSION_ENDED_DATE", r3."SESSION_STATUS", r3."LAST_UPDATED_TIME", r3."USER_CLASSIFICATION", r3."ORPHAN_EXPIRES_TIME", r3."EXPIRES_TIME_REASON", r3."SESSION_ENDED_REASON", r3."PRODUCT_NAME", r3."EMULATEE_PRISM_GUID", r3."EMULATEE_PRISM_REN_AUTH_TOKEN", r3."PRISM_RENEWED_AUTH_TOKEN", r3."TIER", r3."SESSION_BASED_PREFS", r3."SESSION_SOURCE", r3."SERVICE_TYPE", r3."PMD_DATA_VERSION", r3."CREATED_TIME_AND_TZ", r3."PAYMENT_TYPE", r3."PRISM_REGISTRATION_KEY", r3."CREATED_TIME_LONG", r3."ONE_PASS_PRODUCT", r3."SESSION_STORAGE_PROFILE", r3."PRODUCT_VIEW", r3."IP_ADDRESS", r3."USER_CATEGORY", r3."BILLING_METHOD", r3."ROAMING_STATUS", r3."ONE_PASS_USER_ID" FROM "UDS_LONG"."CO_SESSION" r3 WHERE (r3."CREATED_TIME" >= (CAST (:"SYS_B_0" AS TIMESTAMP))) AND (r3."CREATED_TIME" < (CAST (:"SYS_B_1" AS TIMESTAMP)))

SELECT /*b543de8ba8ea0fd3*/ r3."SESSION_ID", r3."ONE_PASS_USER_NAME", r3."FIRST_NAME", r3."LAST_NAME", r3."EMAIL_ADDRESS", r3."EXPIRES_TIME", r3."SITE", r3."CREATED_TIME", r3."SESSION_EXPIRES_TIME", r3."PRISM_GUID", r3."SATOKEN", r3."SESSION_ENDED_DATE", r3."SESSION_STATUS", r3."LAST_UPDATED_TIME", r3."USER_CLASSIFICATION", r3."ORPHAN_EXPIRES_TIME", r3."EXPIRES_TIME_REASON", r3."SESSION_ENDED_REASON", r3."PRODUCT_NAME", r3."EMULATEE_PRISM_GUID", r3."EMULATEE_PRISM_REN_AUTH_TOKEN", r3."PRISM_RENEWED_AUTH_TOKEN", r3."TIER", r3."SESSION_BASED_PREFS", r3."SESSION_SOURCE", r3."SERVICE_TYPE", r3."PMD_DATA_VERSION", r3."CREATED_TIME_AND_TZ", r3."PAYMENT_TYPE", r3."PRISM_REGISTRATION_KEY", r3."CREATED_TIME_LONG", r3."ONE_PASS_PRODUCT", r3."SESSION_STORAGE_PROFILE", r3."PRODUCT_VIEW", r3."IP_ADDRESS", r3."USER_CATEGORY", r3."BILLING_METHOD", r3."ROAMING_STATUS", r3."ONE_PASS_USER_ID" FROM "UDS_LONG"."CO_SESSION" r3 WHERE (r3."CREATED_TIME" >= (CAST (:"SYS_B_0" AS TIMESTAMP))) AND (r3."CREATED_TIME" < (CAST (:"SYS_B_1" AS TIMESTAMP)))

SELECT /*c878e3badba646e5*/ r3."SESSION_ID", r3."ONE_PASS_USER_NAME", r3."FIRST_NAME", r3."LAST_NAME", r3."EMAIL_ADDRESS", r3."EXPIRES_TIME", r3."SITE", r3."CREATED_TIME", r3."SESSION_EXPIRES_TIME", r3."PRISM_GUID", r3."SATOKEN", r3."SESSION_ENDED_DATE", r3."SESSION_STATUS", r3."LAST_UPDATED_TIME", r3."USER_CLASSIFICATION", r3."ORPHAN_EXPIRES_TIME", r3."EXPIRES_TIME_REASON", r3."SESSION_ENDED_REASON", r3."PRODUCT_NAME", r3."EMULATEE_PRISM_GUID", r3."EMULATEE_PRISM_REN_AUTH_TOKEN", r3."PRISM_RENEWED_AUTH_TOKEN", r3."TIER", r3."SESSION_BASED_PREFS", r3."SESSION_SOURCE", r3."SERVICE_TYPE", r3."PMD_DATA_VERSION", r3."CREATED_TIME_AND_TZ", r3."PAYMENT_TYPE", r3."PRISM_REGISTRATION_KEY", r3."CREATED_TIME_LONG", r3."ONE_PASS_PRODUCT", r3."SESSION_STORAGE_PROFILE", r3."PRODUCT_VIEW", r3."IP_ADDRESS", r3."USER_CATEGORY", r3."BILLING_METHOD", r3."ROAMING_STATUS", r3."ONE_PASS_USER_ID" FROM "UDS_LONG"."CO_SESSION" r3 WHERE (r3."CREATED_TIME" >= (CAST (:"SYS_B_0" AS TIMESTAMP))) AND (r3."CREATED_TIME" < (CAST (:"SYS_B_1" AS TIMESTAMP)))

SELECT /*68a7dab2a49d7bbf*/ r3."SESSION_ID", r3."ONE_PASS_USER_NAME", r3."FIRST_NAME", r3."LAST_NAME", r3."EMAIL_ADDRESS", r3."EXPIRES_TIME", r3."SITE", r3."CREATED_TIME", r3."SESSION_EXPIRES_TIME", r3."PRISM_GUID", r3."SATOKEN", r3."SESSION_ENDED_DATE", r3."SESSION_STATUS", r3."LAST_UPDATED_TIME", r3."USER_CLASSIFICATION", r3."ORPHAN_EXPIRES_TIME", r3."EXPIRES_TIME_REASON", r3."SESSION_ENDED_REASON", r3."PRODUCT_NAME", r3."EMULATEE_PRISM_GUID", r3."EMULATEE_PRISM_REN_AUTH_TOKEN", r3."PRISM_RENEWED_AUTH_TOKEN", r3."TIER", r3."SESSION_BASED_PREFS", r3."SESSION_SOURCE", r3."SERVICE_TYPE", r3."PMD_DATA_VERSION", r3."CREATED_TIME_AND_TZ", r3."PAYMENT_TYPE", r3."PRISM_REGISTRATION_KEY", r3."CREATED_TIME_LONG", r3."ONE_PASS_PRODUCT", r3."SESSION_STORAGE_PROFILE", r3."PRODUCT_VIEW", r3."IP_ADDRESS", r3."USER_CATEGORY", r3."BILLING_METHOD", r3."ROAMING_STATUS", r3."ONE_PASS_USER_ID" FROM "UDS_LONG"."CO_SESSION" r3 WHERE (r3."CREATED_TIME" >= (CAST (:"SYS_B_0" AS TIMESTAMP))) AND (r3."CREATED_TIME" < (CAST (:"SYS_B_1" AS TIMESTAMP)))

SELECT /*3e1c73297ac38549*/ r3."SESSION_ID", r3."ONE_PASS_USER_NAME", r3."FIRST_NAME", r3."LAST_NAME", r3."EMAIL_ADDRESS", r3."EXPIRES_TIME", r3."SITE", r3."CREATED_TIME", r3."SESSION_EXPIRES_TIME", r3."PRISM_GUID", r3."SATOKEN", r3."SESSION_ENDED_DATE", r3."SESSION_STATUS", r3."LAST_UPDATED_TIME", r3."USER_CLASSIFICATION", r3."ORPHAN_EXPIRES_TIME", r3."EXPIRES_TIME_REASON", r3."SESSION_ENDED_REASON", r3."PRODUCT_NAME", r3."EMULATEE_PRISM_GUID", r3."EMULATEE_PRISM_REN_AUTH_TOKEN", r3."PRISM_RENEWED_AUTH_TOKEN", r3."TIER", r3."SESSION_BASED_PREFS", r3."SESSION_SOURCE", r3."SERVICE_TYPE", r3."PMD_DATA_VERSION", r3."CREATED_TIME_AND_TZ", r3."PAYMENT_TYPE", r3."PRISM_REGISTRATION_KEY", r3."CREATED_TIME_LONG", r3."ONE_PASS_PRODUCT", r3."SESSION_STORAGE_PROFILE", r3."PRODUCT_VIEW", r3."IP_ADDRESS", r3."USER_CATEGORY", r3."BILLING_METHOD", r3."ROAMING_STATUS", r3."ONE_PASS_USER_ID" FROM "UDS_LONG"."CO_SESSION" r3 WHERE (r3."CREATED_TIME" >= (CAST (:"SYS_B_0" AS TIMESTAMP))) AND (r3."CREATED_TIME" < (CAST (:"SYS_B_1" AS TIMESTAMP)))

SELECT /*6ef478b3ccac8e30*/ r3."SESSION_ID", r3."ONE_PASS_USER_NAME", r3."FIRST_NAME", r3."LAST_NAME", r3."EMAIL_ADDRESS", r3."EXPIRES_TIME", r3."SITE", r3."CREATED_TIME", r3."SESSION_EXPIRES_TIME", r3."PRISM_GUID", r3."SATOKEN", r3."SESSION_ENDED_DATE", r3."SESSION_STATUS", r3."LAST_UPDATED_TIME", r3."USER_CLASSIFICATION", r3."ORPHAN_EXPIRES_TIME", r3."EXPIRES_TIME_REASON", r3."SESSION_ENDED_REASON", r3."PRODUCT_NAME", r3."EMULATEE_PRISM_GUID", r3."EMULATEE_PRISM_REN_AUTH_TOKEN", r3."PRISM_RENEWED_AUTH_TOKEN", r3."TIER", r3."SESSION_BASED_PREFS", r3."SESSION_SOURCE", r3."SERVICE_TYPE", r3."PMD_DATA_VERSION", r3."CREATED_TIME_AND_TZ", r3."PAYMENT_TYPE", r3."PRISM_REGISTRATION_KEY", r3."CREATED_TIME_LONG", r3."ONE_PASS_PRODUCT", r3."SESSION_STORAGE_PROFILE", r3."PRODUCT_VIEW", r3."IP_ADDRESS", r3."USER_CATEGORY", r3."BILLING_METHOD", r3."ROAMING_STATUS", r3."ONE_PASS_USER_ID" FROM "UDS_LONG"."CO_SESSION" r3

**Comment by laurenz** [comment]
Since you say that you are using a procedure, and the problem happened at the sixth execution of the query, I strongly suspect that the problem is that PostgreSQL starts using a generic plan. If that is the cause of the problem, you can fix the procedure by setting

```
ALTER PROCEDURE name_of_procedure() SET plan_cache_mode = force_custom_plan;
```

Then start a new database session and try again.

If that does not fix the problem, please show me the definition of the procedure.

**Comment by SteveDirschelTR** [comment]
Hi.  I altered the procedure but now when I execute it an error is thrown after trying to process one day:

shudslong01a=> alter procedure uds_long.copy_co_session() set plan_cache_mode = force_custom_plan;
ALTER PROCEDURE
shudslong01a=>  call uds_long.copy_co_session();
ERROR:  invalid transaction termination
CONTEXT:  PL/pgSQL function uds_long.copy_co_session() line 91 at COMMIT


Here is that procedure:

create or replace procedure uds_long.copy_co_session()
 LANGUAGE plpgsql
 AS $$
 DECLARE

   v_run_date		TIMESTAMP;
   v_exit		BOOLEAN := FALSE;
   v_start_time		TIMESTAMP;
   v_end_time		TIMESTAMP;
   v_rows_processed	INTEGER;

   v_state                     TEXT;
   v_msg                       TEXT;
   v_detail                    TEXT;
   v_hint                      TEXT;
   v_context                   TEXT;

BEGIN


  WHILE v_exit = FALSE
  LOOP

     SELECT last_run_date
       INTO v_run_date
       FROM uds_long.copy_tracker
      WHERE table_name = 'co_session';

     /* Stop copying when caught up to current day - 2 */

     IF date_trunc('day', v_run_date) = date_trunc('day', now()) OR date_trunc('day', v_run_date) = date_trunc('day', now() - interval '1 day') THEN

        v_exit = TRUE;

     ELSE

        /* copy 1 day of data.  Putting inside a BEGIN/END block to allow committing between days if there are multiple days to copy */
        /* if there are multiple days to copy and 1 day fails the procedure will stop processing. */

        BEGIN
           v_start_time := clock_timestamp();


            INSERT into uds_long.co_session
   		   (SESSION_ID, ONE_PASS_USER_NAME, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, EXPIRES_TIME,SITE,
		   CREATED_TIME, SESSION_EXPIRES_TIME, PRISM_GUID, SATOKEN, SESSION_ENDED_DATE, SESSION_STATUS,
		   LAST_UPDATED_TIME, USER_CLASSIFICATION, ORPHAN_EXPIRES_TIME, EXPIRES_TIME_REASON,
		   SESSION_ENDED_REASON, PRODUCT_NAME, EMULATEE_PRISM_GUID, EMULATEE_PRISM_REN_AUTH_TOKEN,
		   PRISM_RENEWED_AUTH_TOKEN, TIER, SESSION_BASED_PREFS, SESSION_SOURCE,SERVICE_TYPE,
		   PMD_DATA_VERSION, CREATED_TIME_AND_TZ, PAYMENT_TYPE, PRISM_REGISTRATION_KEY, CREATED_TIME_LONG,
		   ONE_PASS_PRODUCT, SESSION_STORAGE_PROFILE, PRODUCT_VIEW, IP_ADDRESS,USER_CATEGORY,
		   BILLING_METHOD, ROAMING_STATUS, ONE_PASS_USER_ID)
            SELECT SESSION_ID, ONE_PASS_USER_NAME, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, EXPIRES_TIME,SITE,
		   CREATED_TIME, SESSION_EXPIRES_TIME, PRISM_GUID, SATOKEN, SESSION_ENDED_DATE, SESSION_STATUS,
		   LAST_UPDATED_TIME, USER_CLASSIFICATION, ORPHAN_EXPIRES_TIME, EXPIRES_TIME_REASON,
		   SESSION_ENDED_REASON, PRODUCT_NAME, EMULATEE_PRISM_GUID, EMULATEE_PRISM_REN_AUTH_TOKEN,
		   PRISM_RENEWED_AUTH_TOKEN, TIER, SESSION_BASED_PREFS, SESSION_SOURCE,SERVICE_TYPE,
		   PMD_DATA_VERSION, CREATED_TIME_AND_TZ, PAYMENT_TYPE, PRISM_REGISTRATION_KEY, CREATED_TIME_LONG,
		   ONE_PASS_PRODUCT, SESSION_STORAGE_PROFILE, PRODUCT_VIEW, IP_ADDRESS,USER_CATEGORY,
		   BILLING_METHOD, ROAMING_STATUS, ONE_PASS_USER_ID
              FROM uds_long_link.co_session
             WHERE created_time >= date_trunc('day', v_run_date)
               AND created_time < date_trunc('day', v_run_date + interval '1 day');


            GET DIAGNOSTICS v_rows_processed  = row_count;

            v_end_time := clock_timestamp();

            UPDATE uds_long.copy_tracker
               SET last_run_date = v_run_date + interval '1 day'
             WHERE table_name = 'co_session';

            INSERT into uds_long.copy_tracker_log
            VALUES ('co_session','SUCCESS',v_start_time, v_end_time, v_run_date, v_rows_processed);

            

        EXCEPTION WHEN OTHERS THEN

           v_exit = TRUE;

           get stacked diagnostics
             v_state   = returned_sqlstate,
             v_msg     = message_text,
             v_detail  = pg_exception_detail,
             v_hint    = pg_exception_hint,
             v_context = pg_exception_context;

           raise exception 'state: %, message: %, detail: %, hint: %, context: %', v_state, v_msg, v_detail, v_hint, v_context;
        END;

        COMMIT;

     END IF;

  END LOOP;

END $$;

**Comment by laurenz** [comment]
I wasn't aware that setting a parameter on a procedure would be a problem with transaction control statements...

You will have to undo the change:

```sql
ALTER PROCEDURE uds_long.copy_co_session() RESET plan_cache_mode;
```

Then you have two alternatives:

1. Run the following before you execute the `INSERT` statement:

   ```sql
   SET plan_cache_mode = force_custom_plan;
   ```

   You can do that directly in the procedure. Don't forget to `RESET` the parameter after the `INSERT`. or you won't get any generic plans at all.

2. Run your `INSERT` as a dynamic statement:

   ```sql
   EXECUTE format(
              'INSERT into uds_long.co_session ...
               SELECT ...
               FROM uds_long_link.co_session
               WHERE created_time >= %L  AND created_time < %L',
              date_trunc('day', v_run_date),
              date_trunc('day', v_run_date + interval '1 day')
           );
   ```

**Comment by SteveDirschelTR** [comment]
I did the SET plan_cache_mode = force_custom_plan in the procedure before the insert and then did a reset on it after the commit and now the query is always pushing the CREATED_TIME filter into the query on the Oracle side.  So that fixed the issue.

Thanks for your help on this!
