### ISSUE TITLE
PostgreSQL 9.5.1 Cannot CREATE extension oracle_fdw; could not load library "/oracle_fdw.so": /oracle_fdw.so: undefined symbol: errcontext

### ISSUE THREAD

**Issue by luisifern** [laurenz/oracle_fdw#62]
Hi,

I'm having trouble when using oracle_fdw (1.3.0) with 2 PostgreSQL (one with 9.1.13 and the other with 9.5.1) instances/clusters on the same server.

**The first installation/configuration** and usage went smoothly with oracle_fdw 1.3.0 & PostgreSQL 9.1.13 port 2345:

##@ POSTGRESQL SERVER:
-bash-4.1$ psql -p 2345 postgres
psql (9.1.13)

postgres=# CREATE EXTENSION oracle_fdw;
CREATE EXTENSION

postgres=# CREATE SERVER svr_oracle FOREIGN DATA WRAPPER oracle_fdw OPTIONS(dbserver 'ol7orcl12c:21912/BDTEST');
CREATE SERVER

postgres=# GRANT USAGE ON FOREIGN SERVER svr_oracle TO postgres;
GRANT

postgres=# CREATE USER MAPPING FOR postgres SERVER svr_oracle OPTIONS (user 'SYSTEM', password '********');
CREATE USER MAPPING

postgres=# select oracle_diag();
                          oracle_diag
_____________________________________________________
 oracle_fdw 1.3.0, PostgreSQL 9.1.13, Oracle client 12.1.0.2.0
(1 fila)

postgres=# CREATE FOREIGN TABLE ft_dual (
postgres(#            dummy character varying(1) NOT NULL
postgres(#            ) SERVER svr_oracle OPTIONS (schema 'SYS', table 'DUAL');
CREATE FOREIGN TABLE

postgres=# SELECT * FROM ft_dual;
dummy
_______
 X
(1 fila)

##END OF USAGE WITH POSTGRESQL 9.1.13

On the same server, **the second installation/configuration** with oracle_fdw 1.3.0 & PostgreSQL 9.5.1 port 5432. I had issues after the Installation:

##@ POSTGRESQL SERVER:
##LETS CHECK THE PARAMETERS & LIBRARIES:

##STEP 1
[root@svr-lb-prcat2 ~]# yum list 'postgres*'
Installed Packages
postgresql91.x86_64                                             9.1.13-1PGDG.rhel6                                      @/postgresql91-9.1.13-1PGDG.rhel6.x86_64
postgresql91-contrib.x86_64                                     9.1.13-1PGDG.rhel6                                      @/postgresql91-contrib-9.1.13-1PGDG.rhel6.x86_64
postgresql91-devel.x86_64                                       9.1.13-1PGDG.rhel6                                      installed
postgresql91-libs.x86_64                                        9.1.13-1PGDG.rhel6                                      @/postgresql91-libs-9.1.13-1PGDG.rhel6.x86_64
postgresql91-server.x86_64                                      9.1.13-1PGDG.rhel6                                      @/postgresql91-server-9.1.13-1PGDG.rhel6.x86_64
postgresql95.x86_64                                             9.5.1-1PGDG.rhel6                                       installed
postgresql95-contrib.x86_64                                     9.5.1-1PGDG.rhel6                                       installed
postgresql95-devel.x86_64                                       9.5.1-1PGDG.rhel6                                       installed
postgresql95-libs.x86_64                                        9.5.1-1PGDG.rhel6                                       installed
postgresql95-server.x86_64                                      9.5.1-1PGDG.rhel6                                       installed

##STEP 2
[root@svr-lb-prcat2 ~]# vim ~/.bash_profile
ORACLE_HOME=/oracle/instantclient_12_1
LD_LIBRARY_PATH=/oracle/instantclient_12_1
#PG_CONFIG=/usr/pgsql-9.1/bin
PG_CONFIG=/usr/pgsql-9.5/bin
PATH=$PATH:$HOME/bin:$ORACLE_HOME:$PG_CONFIG
#PATH=$PATH:$HOME/bin
export PATH
export ORACLE_HOME
export LD_LIBRARY_PATH

##STEP 3
[root@svr-lb-prcat2 ~]# logout
##LOGIN:
##STEP 4
[root@svr-lb-prcat2 ~]# find / -name pg_config
/usr/pgsql-9.1/bin/pg_config
/usr/pgsql-9.5/bin/pg_config

##STEP 5
[root@svr-lb-prcat2 ~]# yum list installed 'postgres*' | grep 'postgresql' | grep 'devel'
postgresql91-devel.x86_64   9.1.13-1PGDG.rhel6 installed
postgresql95-devel.x86_64   9.5.1-1PGDG.rhel6  installed

##STEP 6
[root@svr-lb-prcat2 ~]# pg_config | head -n 1
BINDIR = /usr/pgsql-9.5/bin

##STEP 7
[root@svr-lb-prcat2 ~]# pg_config --pgxs
/usr/pgsql-9.5/lib/pgxs/src/makefiles/pgxs.mk

##STEP 8
[root@svr-lb-prcat2 ~]# echo $ORACLE_HOME
/oracle/instantclient_12_1

##STEP 9
[root@svr-lb-prcat2 ~]# echo $LD_LIBRARY_PATH
/oracle/instantclient_12_1

##STEP 10
[root@svr-lb-prcat2 ~]# cd /oracle/oracle_fdw-1.3.0/

##STEP 11
[root@svr-lb-prcat2 oracle_fdw-1.3.0]# pg_config --pgxs
/usr/pgsql-9.5/lib/pgxs/src/makefiles/pgxs.mk

##STEP 12
[root@svr-lb-prcat2 oracle_fdw-1.3.0]# make
make: Does not do anything for `all'.

##STEP 13
[root@svr-lb-prcat2 oracle_fdw-1.3.0]# make install
/bin/mkdir -p '/usr/pgsql-9.5/lib'
/bin/mkdir -p '/usr/pgsql-9.5/share/extension'
/bin/mkdir -p '/usr/pgsql-9.5/share/extension'
/bin/mkdir -p '/usr/pgsql-9.5/doc/extension'
/usr/bin/install -c -m 755  oracle_fdw.so '/usr/pgsql-9.5/lib/oracle_fdw.so'
/usr/bin/install -c -m 644 .//oracle_fdw.control '/usr/pgsql-9.5/share/extension/'
/usr/bin/install -c -m 644 .//oracle_fdw--1.1.sql .//oracle_fdw--1.0--1.1.sql  '/usr/pgsql-9.5/share/extension/'
/usr/bin/install -c -m 644 .//README.oracle_fdw '/usr/pgsql-9.5/doc/extension/'

##STEP 14
[root@svr-lb-prcat2 oracle_fdw-1.3.0]# pg_config | grep PKGLIBDIR
PKGLIBDIR = /usr/pgsql-9.5/lib

##STEP 15
[root@svr-lb-prcat2 oracle_fdw-1.3.0]# ls -l /usr/pgsql-9.5/lib/oracle_fdw*
-rwxr-xr-x. 1 root root 323418 mar  2 10:11 /usr/pgsql-9.5/lib/oracle_fdw.so

##STEP 16
[root@svr-lb-prcat2 oracle_fdw-1.3.0]# ldd /usr/pgsql-9.5/lib/oracle_fdw.so
        linux-vdso.so.1 =>  (0x00007fffd7acc000)
        libclntsh.so.12.1 => /oracle/instantclient_12_1/libclntsh.so.12.1 (0x00007fe66d325000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe66cf87000)
        libmql1.so => /oracle/instantclient_12_1/libmql1.so (0x00007fe66cd11000)
        libipc1.so => /oracle/instantclient_12_1/libipc1.so (0x00007fe66c993000)
        libnnz12.so => /oracle/instantclient_12_1/libnnz12.so (0x00007fe66c288000)
        libons.so => /oracle/instantclient_12_1/libons.so (0x00007fe66c043000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fe66be3f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fe66bbba000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe66b99d000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007fe66b784000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fe66b57b000)
        /lib64/ld-linux-x86-64.so.2 (0x000000389a200000)
        libaio.so.1 => /lib64/libaio.so.1 (0x00007fe66b37a000)
        libclntshcore.so.12.1 => /oracle/instantclient_12_1/libclntshcore.so.12.1 (0x00007fe66ae08000)

##STEP 17
[root@svr-lb-prcat2 oracle_fdw-1.3.0]# service postgresql-9.5 restart
Stoping service  postgresql-9.5:                       [  OK  ]
Starting services postgresql-9.5:                        [  OK  ]

##STEP 18
[root@svr-lb-prcat2 oracle_fdw-1.3.0]# su - postgres

##STEP 19
-bash-4.1$ psql -p 5432 postgres

psql (9.5.1)

##STEP 20
postgres=# CREATE EXTENSION oracle_fdw;
ERROR:  could not load library "/usr/pgsql-9.5/lib/oracle_fdw.so": /usr/pgsql-9.5/lib/oracle_fdw.so: undefined symbol: errcontext

##END OF INSTALLATION/CONFIGURATION

I assume the root of the error is on STEP 12 something is amiss compared with the installation with postgresql 9.1.13.

My FOREIGN SERVER to oracle is still working with Postgresql 9.1.13 but I Cannot CREATE EXTENSION oracle_fdw; with Postgresql 9.5.1.
**ERROR:  could not load library "/usr/pgsql-9.5/lib/oracle_fdw.so": /usr/pgsql-9.5/lib/oracle_fdw.so: undefined symbol: errcontext
**

**Why Am I Using another PG9.5 Instance/Cluster on the same server?**
Our production data is in PG 9.1 and oracle_fdw cannot INSERT, UPDATE, DELETE from PG 9.1 to an ORACLE scenario. So as PG 9.5 with oracle_fdw CAN do it, I'm going to dblink locally PG9.5 to 9.1 then INSERT, UPDATE, DELETE to ORACLE from 9.5. Also, is so much easier to import a whole schema to 9.5 than creating Foreign by Foreign table on 9.1

So as i said both Postgresql 9.1.13 and 9.5.1 are on the same Server RHEL 6.4 (Santiago). Is there anything I've missed? Thanks in advanced!

**Comment by laurenz** [comment]
You did not rebuild oracle_fdw for PostgreSQL 9.5, so you installed the binary built for 9.1 into 9.5, which won't work.

Between step 11 and 12, do the following:

    make clean

to clean the directory.

**Comment by luisifern** [comment]
Thanks laurenz I'll try it right now!

**Comment by luisifern** [comment]
It's Working Thanks a Lot!
