### ISSUE TITLE
How to use TCPS to connect to Oracle via the FDW

### ISSUE THREAD

**Issue by gwlester** [laurenz/oracle_fdw#622]
I could not find documentation of how to use the FDW to make a secure (TCPS protocol) connection to Oracle.

Is this possible?

Where is it documented?

**Comment by laurenz** [comment]
This is a duplicate of #343, perhaps the little information provided there can help you.

This should be documented in the Oracle documentation. As I have never used it myself, I cannot give you assistance.
oracle_fdw supports all Oracle connection methods that Oracle supports, you just have to set the connection string correctly and perhaps configure something in the client's `sqlnet.ora`.

If you can show me how you connect with sqlplus, we can figure out how to connect with oracle_fdw.

**Comment by philflorent** [comment]
Hi,

I really suggest to follow oracle-base tutorial : https://oracle-base.com/articles/misc/native-network-encryption-for-database-connections
Tim Hall is also an OCM and he knows his stuff. His documentation is more concise and clearer than Oracle official docs. 

Key parts :


_"From 10g Release 2 onward, Native Network Encryption and [TCP/IP with SSL/TLS](https://oracle-base.com/articles/misc/configure-tcpip-with-ssl-and-tls-for-database-connections) are no longer part of the [Advanced Security Option](https://docs.oracle.com/cd/B19306_01/license.102/b14199/options.htm#DBLIC138). Native network encryption gives you the ability to encrypt database connections, without the configuration overhead of [TCP/IP and SSL/TLS](https://oracle-base.com/articles/misc/configure-tcpip-with-ssl-and-tls-for-database-connections) and without the need to open and listen on different ports."_ 

Oracle 11g or later uses can use this feature without an expensive option.  

_"If we require AES256 encryption on all connections to the server, we would add the following to the server side "sqlnet.ora" file. The client does not need to be altered as the default settings (ACCEPTED and no named encryption algorithm) will allow it to successfully negotiate a connection.

SQLNET.ENCRYPTION_SERVER=REQUIRED
SQLNET.ENCRYPTION_TYPES_SERVER=(AES256)"_

Just one file to edit server side and that's all.

Best regards,
Phil

**Comment by philflorent** [comment]
I just (re)checked it is OK :

Sqlnet.ora server side :

NAMES.DIRECTORY_PATH= (TNSNAMES, EZCONNECT)
DIAG_ADR_ENABLED=OFF
DIAG_SIGHANDLER_ENABLED=FALSE
DIAG_DDE_ENABLED=FALSE
**SQLNET.ENCRYPTION_SERVER=REQUIRED
SQLNET.ENCRYPTION_TYPES_SERVER=(AES256)**

 
 Some query from oracle_fdw, session id 3025


SQL> select network_service_banner from v$session_connect_info where sid = 3025;
 

NETWORK_SERVICE_BANNER

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

TCP/IP NT Protocol Adapter for Linux: Version 11.2.0.4.0 - Production
Oracle Advanced Security: encryption service for Linux: Version 11.2.0.4.0 - Production
Oracle Advanced Security: AES256 encryption service adapter for Linux: Version 11.2.0.4.0 - Product
Oracle Advanced Security: crypto-checksumming service for Linux: Version 11.2.0.4.0 – Production

Here you can see I obtain the line "Oracle Advanced Security: AES256 encryption service adapter for Linux: Version 11.2.0.4.0 - Product". I also obtain a line "Oracle Advanced Security: encryption service for Linux: Version 11.2.0.4.0 - Production" but it will always be present. It just means the feature us available but here the line with "AES256" means it is really in use with the algo information. 
Notice I have a line about checksumming but it is just available, it's not in use. I would have another line with SHAXX or something similiar if it was in use. 

You can be puzzled but the "Oracle Advanced Security" part but this mention was removed in 12c even if Advanced Security option was not needed even in 11.2.  

Best regards,
Phil

**Comment by laurenz** [comment]
Did you manage to connect using TCPS?
