### ISSUE TITLE
oracle_fdw on AlmaLinux 8 installation failed

### ISSUE THREAD

**Issue by brunre01** [laurenz/oracle_fdw#625]
Getting error when trying to build oracle_fdw from source on AlmaLinux 8 for a postgres 16.1 cluster.
Is oracle_fdw included in the postgresql16-devel or postgresql16-contrib packages?
What are my options here?

[BRUSSELS][08:41:04 EST] # make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -fvisibility=hidden -I"/sdk/include" -I"/oci/include" -I"/rdbms/public" -I"/"  -I. -I./ -I/usr/pgsql-16/include/server -I/usr/pgsql-16/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_fdw.o oracle_fdw.c
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
make: *** [<builtin>: oracle_fdw.o] Error 1

**Comment by laurenz** [comment]
Install the missing package that contains that file:

```bash
sudo dnf install redhat-rpm-config
```

**Comment by brunre01** [comment]
Thank you. That seemed to work. Is it possible to include the minimum
package requirements in the installation document ?

**Comment by laurenz** [comment]
That package is not required by oracle_fdw, but by the way your PostgreSQL was configured when it was built.
You would have the same problem building any other extension.

It would be difficult to keep track of all binary PostgreSQL distributions and their requirements. I don't think this should go in the README. But you are welcome to create a page on the [Wiki](/laurenz/oracle_fdw/wiki) that deals with building oracle_fdw on your specific Linux distribution.

**Comment by laurenz** [comment]
Duplicate of #203.
