### ISSUE TITLE
Support for Postgres v16?

### ISSUE THREAD

**Issue by AmebaBrain** [laurenz/oracle_fdw#629]
Any plans to release a Postgres v16 compatible version?

**Comment by AmebaBrain** [comment]
Ok, I see!

In other FDWs authors usually explicitly specify that specific release is latest major version compatible. For example, 
https://github.com/EnterpriseDB/mysql_fdw/releases/tag/REL-2_9_1
https://github.com/pgspider/sqlite_fdw/releases/tag/v2.4.0

For some reason, I was expecting to see the same in your FDW :)

I'll try it out. Closing the ticket and many thanks

**Comment by laurenz** [comment]
Hm, not a bad idea. I could add it to the release notes from now on.
