### ISSUE TITLE
Not able to create extension oracle_fdw

### ISSUE THREAD

**Issue by bimalkoirala** [laurenz/oracle_fdw#630]
Getting this error:
secure_data=# CREATE EXTENSION oracle_fdw;
ERROR:  could not load library "/usr/lib/postgresql/15/lib/oracle_fdw.so": /usr/lib/postgresql/15/lib/oracle_fdw.so: undefined symbol: getRTEPermissionInfo

postgres@dev-pg-stats01:~$ ls -lhtr /usr/lib/postgresql/15/lib/oracle_fdw.so
-rwxr-xr-x 1 root root 606K Dec 13 16:38 /usr/lib/postgresql/15/lib/oracle_fdw.so

postgres@dev-pg-stats01:/usr/share/postgresql/15/extension$ ls -alhtr oracle_fdw*
-rw-r--r-- 1 root root  133 Dec 13 16:55 oracle_fdw.control
-rw-r--r-- 1 root root 1.3K Dec 13 16:55 oracle_fdw--1.2.sql
-rw-r--r-- 1 root root  240 Dec 13 16:55 oracle_fdw--1.1--1.2.sql
-rw-r--r-- 1 root root  231 Dec 13 16:55 oracle_fdw--1.0--1.1.sql

postgres@dev-pg-stats01:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/oracle/19.21/client64/lib/:/usr/lib/postgresql/15/bin

postgres=# select version();
                                                              version
-----------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 15.5 (Ubuntu 15.5-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit

Thank you for your help.

**Comment by laurenz** [comment]
That looks very much like you built oracle_fdw with PostgreSQL v16 (which introduced `getRTEPermissionInfo`) and now are trying to use the library with v15.
That won't work. You have to build oracle_fdw with the same PostgreSQL version as you are running it.

**Comment by bimalkoirala** [comment]
Thank you laurenz. I didn't realize that postgresql-client-16 postgresql-server-dev-16 postgresql-server-dev-all were automatically installed during my initial PostgreSQL 15 installation. I removed the V16 and now it's working file. You are awesome.

Thank you once again !
