### ISSUE TITLE
A questions about the development of Postgres Extension Development. (No related to this project.)

### ISSUE THREAD

**Issue by Zrealshadow** [laurenz/oracle_fdw#635]
Hi Sir,

I noticed you were active in Postgres Extension Development and contributed many good solutions, no matter in stackoverflow or stackExchange. Seems you are an expert in Postgres C Extension.

I didn't find email in your profile webpage, only your github.
So I just go there to reach your asisstance.

I'm a student which interested in Postgres Extension Development.
I proposed it in stackexchange, link: https://dba.stackexchange.com/questions/334279/in-postgres-c-extension-development-the-argument-of-function-is-a-tuple-how-to.

Would you mind giving me some advice ? 

Appreciate, many thx.

**Comment by Zrealshadow** [comment]
I‘m sorry, maybe a little rude.

**Comment by laurenz** [comment]
It is not rude, just off-topic here.
