### ISSUE TITLE
Does oracle_fdw support LOAD_BALANCE or FAILOVER 

### ISSUE THREAD

**Issue by mellerbeck** [laurenz/oracle_fdw#640]
MYDB=(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=YES)(FAILOVER=YES)(ADDRESS=(PROTOCOL=tcp)(HOST=hostname1-vip.domain.com)(PORT=1571))(ADDRESS=(PROTOCOL=tcp)(HOST=hostname2-vip.domain.com)(PORT=1571))(ADDRESS=(PROTOCOL=tcp)(HOST=hostname3-vip.domain.com)(PORT=1571)))(CONNECT_DATA=(SERVICE_NAME=ServiceName)))

**Comment by laurenz** [comment]
Is there any special support needed? If the Oracle client can understand that connection string, you can use it with oracle_fdw.

I am under the impression that the only thing client code needs to do in the case of a failover is to reconnect when it loses the database connection. oracle_fdw does that:
- At the beginning of a statement, it tests the [`OCI_ATTR_SERVER_STATUS`][oradoc] of the connection (which, according to the documentation, performs "a light weight connection health check"). If that fails, it will silently try to reconnect.
- Then, oracle_fdw starts a database transaction, and if there are certain error messages that indicate connection loss (ORA-01012, ORA-00028, ORA-03113 or ORA-03135), it will also silently try to reconnect.

That list of error messages may not be exhaustive; if you know any other error messages that mean that oracle_fdw should try to reconnect, please let me know.


 [oradoc]: https://docs.oracle.com/en/database/oracle/oracle-database/18/lnoci/handle-and-descriptor-attributes.html#GUID-2B6D06A7-8EDF-46FF-BDEF-320D293DCA65__GUID-36E3EEA5-E38F-4A5E-A73B-0CD50152A922

**Comment by philflorent** [comment]
Hi,
Testing OCI_ATTR_SERVER_STATUS and ORA- network related issues is enough to achieve reconnection, no matter which Oracle (or not) server-side mechanisms and network redundancy is used.
If you want to know if RAC related features e.g TAF (Transparent Application Failover) or FCF (fast connection failover) are specifically implemented client-side in oracle_fdw it's NO afaik but Laurenz can tell more about that.
If RAC is in use this tnsnames.ora entry seems problematic. You won't achieve any real high availability with that. You need SCAN and I see 3 VIPs instead. It's much easier to define the foreign server via "create server" with a SCAN.  
That said anyway RAC is not reliable for various reasons and the main one is that Oracle Clusterware itself is a SPOF but it's another debate.
Hopefully oracle_fdw will remain simple. If connection is KO, it tries to reconnect and if the service is up it works. 
Best regards,
Phil

**Comment by laurenz** [comment]
Thanks, @philflorent . Yes, there is no TAF or FCF in oracle_fdw.

**Comment by mellerbeck** [comment]
Thanks, @philflorent it sounds like we are using tnsnames with 3 virtual IP's. It looks like SCAN would be the ideal way, then oracle_fdw would just connects to what looks like a single server to it.

**Comment by laurenz** [comment]
Can we close this issue? Are your questions answered?

**Comment by mellerbeck** [comment]
Yes! Thank you very much
