### ISSUE TITLE
Cannot connect to foreign Oracle server

### ISSUE THREAD

**Issue by AbdelrahmanMaher1** [laurenz/oracle_fdw#642]
I built oracle_fdw and did all the steps but when I run this query:
 **"select * from oracle_execute('oracle_server', 'select 1') ;"** 
it give me this error:
**"SQL Error [HV00N]: ERROR: cannot connect to foreign Oracle server
  Detail: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor"**

note :
oracle_diag                                                                                               |
----------------------------------------------------------------------------------------------------------+
oracle_fdw 2.6.0, PostgreSQL 15.5, Oracle client 12.2.0.1.0, ORACLE_HOME=/usr/lib/oracle/12.2/client64/lib|

It seems i need to add my service name to listener but I don't know where is the file in my machine ?! 
OS: CentOS 7.

Advise me to solve that please .

**Comment by AbdelrahmanMaher1** [comment]
@laurenz, I hope you give me your advice.

**Comment by laurenz** [comment]
The connect string you specified in the `dbserver` option of the `CREATE SERVER` statement must be wrong, or the database is not registered with the Oracle listener.

Try to connect to Oracle using `sqlplus` as user `postgres` on the PostgreSQL machine. You have to figure out what connection string is correct for you. Once you can connect with

```bash
sqlplus someuser/password@connstring
```

use that very same `connstring` in your `CREATE SERVER` statement.

**Comment by AbdelrahmanMaher1** [comment]
it gives me that :

SQL*Plus: Release 12.2.0.1.0 Production on Thu Feb 1 01:03:15 2024

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

ERROR:
ORA-12514: TNS:listener does not currently know of service requested in connect
descriptor
 
I tried to create file that named tnsnames.ora and write that into it :
serviceName=
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = serverIP)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = serviceName)
    )
  )

then I setup TNS_ADMIN environment variable to the directory of the tnsnames.ora file.
but also it is the same result :'(

**Comment by laurenz** [comment]
I would gladly help you with this, but I cannot.
I cannot tell you the correct connect string for your database. Perhaps you should ask your Oracle DBAs for help.

**Comment by laurenz** [comment]
Great, thanks.
