### ISSUE TITLE
cannot make oracle_fdw 

### ISSUE THREAD

**Issue by MobeenNaser** [laurenz/oracle_fdw#645]
hi i'm facing this error while making oracle_fdw 

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -shared -o oracle_fdw.so oracle_fdw.o oracle_utils.o oracle_gis.o -L/usr/lib64  -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,--as-needed  -L"/var/lib/pgsql/instantclient_11_2/" -L"/var/lib/pgsql/instantclient_11_2/bin" -L"/var/lib/pgsql/instantclient_11_2/lib" -L"/var/lib/pgsql/instantclient_11_2/lib/amd64" -L/usr/lib/oracle/11.2/client64/lib -lclntsh
/usr/bin/ld: cannot find -lclntsh
collect2: error: ld returned 1 exit status
make: *** [/usr/lib64/pgsql/pgxs/src/makefiles/../../src/Makefile.shlib:322: oracle_fdw.so] Error 1

![image](https://github.com/laurenz/oracle_fdw/assets/158822776/1b05bd5e-4225-445c-8ee2-309c75b97868)

**Comment by laurenz** [comment]
The linker didn't find the Oracle client shared library. Do what the documentation recommends:

> Set the environment variable ORACLE_HOME to the location of the Oracle installation.

**Comment by MobeenNaser** [comment]
its installed now but when i write create extension command this error raised : 

ERROR:  extension "oracle_fdw" has no installation script nor update path for version "1.2"

**Comment by laurenz** [comment]
Then you didn't properly install the extension with `make install`.
The file `oracle_fdw--1.2.sql` is missing in the `extension` subdirectory of the PostgreSQL share directory, which you can find with `pg_config --sharedir`.

**Comment by MobeenNaser** [comment]
i tried the process again 

this is the output of make install : 
![image](https://github.com/laurenz/oracle_fdw/assets/158822776/e7141dc7-39dc-47ff-9d22-3cb49a18dc89)

and this is the content of extinsion directory : 
![image](https://github.com/laurenz/oracle_fdw/assets/158822776/a4ef23fd-b03d-4a6c-843e-873d253c753f)

when i run create extension oracle_fdw 

this error is raised : 

![image](https://github.com/laurenz/oracle_fdw/assets/158822776/36d6b782-b497-4604-94f9-67cde8d7ad20)

**Comment by MobeenNaser** [comment]
i changed the installation Pathe to the Path in the eoor and i get a new error : 

![image](https://github.com/laurenz/oracle_fdw/assets/158822776/1d58db2b-261e-4ecb-8c2c-f22fd728d51f)

the .so file is exist 

lld_library_PATH=/usr/lib/oracle/21/client64/lib

**Comment by laurenz** [comment]
Please, _please_, **please** use formatted text, not images.
I have a hard time dong copy and paste from that...

You built oracle_fdw against a different version of PostgreSQL than the one where you installed it. From the error message, the version you used to build must have been older than v12, but the version where you installed it must be newer than that. That won't work: you have to build oracle_fdw against the same version of PostgreSQL as the one where you are using it.

This diagnosis fits your earlier trouble: you probably have a different `pg_config` on your `PATH` when you run `make` than when you run `make install`.

The easiest way to resolve the problem would be to uninstall the decrepit old version of PostgreSQL that is installed in `/usr/share/pgsql`. Very likely, the old packages are from the Ubuntu/Debian distribution, while the new ones are from the PGDG. That is always a very bad idea.

**Comment by MobeenNaser** [comment]
should i run make and make install using root user

**Comment by laurenz** [comment]
No, you should uninstall the bad software.

**Comment by laurenz** [comment]
Did you succeed? Do you need any more help?

**Comment by laurenz** [comment]
Closing as inactive; feel free to reopen if you still need help.
