### ISSUE TITLE
Could not open extension control file

### ISSUE THREAD

**Issue by taneraruk** [laurenz/oracle_fdw#646]
Hi,

I get this error message when try to create oracle_fdw extension. I would appreciate if you help.

`could not open extension control file "/usr/share/postgresql/14/extension/oracle_fdw.control": No such file or directory`

control file is located under share folder,

> pg_config --sharedir
> /usr/share/postgresql/14

> ls -al /usr/share/postgresql/14/extension/
> drwxrwxrwx 1 root root 4096 Feb  7 10:28 .
> drwxrwxrwx 1 root root 4096 Feb  7 10:28 ..
> -rwxrwxrwx 1 root root  231 Feb  7 10:28 oracle_fdw--1.0--1.1.sql
> -rwxrwxrwx 1 root root  240 Feb  7 10:28 oracle_fdw--1.1--1.2.sql
> -rwxrwxrwx 1 root root 1244 Feb  7 10:28 oracle_fdw--1.2.sql
> -rwxrwxrwx 1 root root  133 Feb  7 10:28 oracle_fdw.control

ORACLE_HOME set,

> $ORACLE_HOME
> bash: /usr/lib/oracle/12.2/client64: Is a directory

There is no error during make install.

> $LD_LIBRARY_PATH
> bash: /usr/lib/oracle/12.2/client64/lib: Is a directory

**Comment by laurenz** [comment]
That is indeed mysterious:

> ```none
> could not open extension control file "/usr/share/postgresql/14/extension/oracle_fdw.control": No such file or directory
> ```

but

> ```none
> pg_config --sharedir
> /usr/share/postgresql/14
>
> ls -al /usr/share/postgresql/14/extension/
> drwxrwxrwx 1 root root 4096 Feb 7 10:28 .
> drwxrwxrwx 1 root root 4096 Feb 7 10:28 ..
> -rwxrwxrwx 1 root root 231 Feb 7 10:28 oracle_fdw--1.0--1.1.sql
> -rwxrwxrwx 1 root root 240 Feb 7 10:28 oracle_fdw--1.1--1.2.sql
> -rwxrwxrwx 1 root root 1244 Feb 7 10:28 oracle_fdw--1.2.sql
> -rwxrwxrwx 1 root root 133 Feb 7 10:28 oracle_fdw.control
> ```

The only explanation that I have is that the first message is from a connection to a machine that is different from the one where you listed the files...

**Comment by taneraruk** [comment]
Sorry, maybe I am doing something completely wrong, I should give more details. 

I have an Oracle database and I want to migrate it to Postgresql database. For migration I am using [ora2pg ](https://ora2pg.darold.net/documentation.html) application. We have a big amount of blob data thus migration takes too long. [In this article](https://www.migops.com/blog/ora2pg-now-supports-oracle_fdw-to-increase-the-data-migration-speed/) it is advised to use oracle_fdw to fasten blob migration.

![image](https://github.com/laurenz/oracle_fdw/assets/11517050/6fa9f50e-2ccd-4e0b-8a17-81315f4b6856)

**Comment by laurenz** [comment]
How is that comment or that image related to this issue?

Did you read my comment?

**Comment by taneraruk** [comment]
Yes, that image shows what I try to do. I try to extract and read data from oracle and write it to postgresql db. I have installed oracle_fdw on ora2pg server.

**Comment by laurenz** [comment]
Let me repeat:

Did you make sure that the machine where you ran `ls -al /usr/share/postgresql/14/extension/` is the PostgreSQL **server** (not the client) where you got the error message for `CREATE EXTENSION`?

In your picture, that would be the machine on the right side.

**Comment by taneraruk** [comment]
Sorry for late response, yes you are right, it is my bad, trying to run it on client. It works now. Thanks for your help.

**Comment by laurenz** [comment]
Thanks for the feedback, and good that it works for you.
