### ISSUE TITLE
Encountered make issue related to missing oci.h file

### ISSUE THREAD

**Issue by andersmd7** [laurenz/oracle_fdw#647]
I am encountering an issue during the `make` step that is slightly different from the other reported issues related to  the `make` step. 
I am running PostgreSQL 12 on an Oracle Linux 8 server (I know... Gross). I installed Oracle Instant Client following [these instructions](https://docs.oracle.com/en/database/oracle/oracle-database/21/lacli/install-instant-client-using-rpm.html#GUID-2E81E2AE-E94C-413F-99B2-AE9A3949F05D), and set $ORACLE_HOME to /usr/lib/oracle/21/client64, which seems to be the proper location.

After issuing ```make```, I received the following:

```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I"/sdk/include" -I"/oci/include" -I"/rdbms/public" -I"/"  -I. -I./ -I/usr/pgsql-12/include/server -I/usr/pgsql-12/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_fdw.o oracle_fdw.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I"/sdk/include" -I"/oci/include" -I"/rdbms/public" -I"/"  -I. -I./ -I/usr/pgsql-12/include/server -I/usr/pgsql-12/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_utils.o oracle_utils.c
oracle_utils.c:22:10: fatal error: oci.h: No such file or directory
 #include <oci.h>
          ^~~~~~~
compilation terminated.
make: *** [<builtin>: oracle_utils.o] Error 1
```

I'm sorry of this is a dumb/obvious issue, but appreciate any help you can provide, and thank you for your contribution with this package!

**Comment by andersmd7** [comment]
Actually, I see now this is an apparent duplicate of #447 . I'd previously installed oracle-instantclient-basic instead of oracle-instantclient-devel

**Comment by laurenz** [comment]
The same problem was also reported in #286, #403 and #405.
Yes, you need to install the package with the C headers and the "basic" or "basiclite" package.

**Comment by andersmd7** [comment]
Yes, I realized that the original search I performed in the issue tracker had been limited to open issues.

Thank you! I've made it through the whole process to where I should be able to do ```CREATE EXTENSION oracle_fdw```, and I'm receiving:

```
ERROR:  could not open extension control file "/usr/pgsql-12/share/extension/oracle_fdw.control": No such file or directory
SQL state: 58P01
```

Ownership of that file is the same as all other .control files in the directory. I restarted the database server. I'm puzzled...

**Comment by andersmd7** [comment]
Arggh. Please disregard the comment above! In my case, the explanation was the dumbest one possible (I connected to the wrong server).

**Comment by laurenz** [comment]
Thanks for the feedback that the problem is resolved. I am glad I could help.
