### ISSUE TITLE
Makefile:18: ../../src/Makefile.global: No such file or directory Makefile:19: /contrib/contrib-global.mk: No such file or directory make: *** No rule to make target `/contrib/contrib-global.mk'.  Stop.

### ISSUE THREAD

**Issue by MARCELVIS** [laurenz/oracle_fdw#65]
Hey Larenz,

I'm trying to upgrade from oracle_fdw 1.1 to 1.3; my operating system is Ubuntu and using Postgres 9.5.

After executing the make NO_PGXS=1 command I get the errors:

**Makefile:18: ../../src/Makefile.global: No such file or directory
Makefile:19: /contrib/contrib-global.mk: No such file or directory
make: *** No rule to make target `/contrib/contrib-global.mk'.  Stop.**

Any idea what can cause this?  Thanks Marcel

**Comment by laurenz** [comment]
If you want to build oracle_fdw in a PostgreSQL source tree, you'll have to copy it to <tt>contrib/oracle_fdw</tt> and run <tt>make NO_PGXS=1</tt> from there.

Unless you have a good reason to do this, I'd recommend that you run plain <tt>make</tt> and make sure that <tt>pg_config</tt> is on the <tt>PATH</tt>.

**Comment by farukerdm** [comment]
Hello,

Where is the contrib directory that you have mentioned?

**Comment by laurenz** [comment]
In the PostgreSQL source tree.
