### ISSUE TITLE
create extension 

### ISSUE THREAD

**Issue by MajdRamadan** [laurenz/oracle_fdw#651]
after finish install for oracle_fdw this error raised 

create extension oracle_fdw;
ERROR:  could not load library "/usr/pgsql-15/lib/oracle_fdw.so": /usr/pgsql-15/lib/oracle_fdw.so: undefined symbol: get_rel_all_updated_cols

**Comment by chrullrich** [comment]
You are using a version of oracle_fdw that was built with PostgreSQL 16. You have to find and install a package that supports PostgreSQL 15 instead. oracle_fdw is always compiled for one specific (major) version of PostgreSQL and the result only works with that one version.

You can also build it yourself from source. Please see the README file; it explains in detail how to do this.

**Comment by laurenz** [comment]
Another possibility is that your PostgreSQL version is 15.0 or 15.1.
That won't work, and you have to update to a later minor release.

See #596 and the commit message for 57279082a83f4519244211c35d384e471b39ba9e.

**Comment by laurenz** [comment]
No. Update your PostgreSQL v15 server to 15.6 and try again.

**Comment by MajdRamadan** [comment]
i'm new on postgres and i dont have any idea about upgrading so i tried using postgresql 12 and face this error : 

create extension oracle_fdw;
ERROR:  could not load library "/usr/pgsql-12/lib/oracle_fdw.so": /usr/pgsql-12/lib/oracle_fdw.so: undefined symbol: errstart_cold

**Comment by laurenz** [comment]
See the documentation:

> Since the Oracle client shared library is probably not in the standard library path, you have to make sure that the PostgreSQL server will be able to find it. How this is done varies from operating system to operating system; on Linux you can set LD_LIBRARY_PATH or use `/etc/ld.so.conf`.

But you definitely should not use PostgreSQL v12. Updating is trivial: install 15.6 over your existing 15.0 installation and restart the server. If that is too much for you, perhaps you shouldn't use oracle_fdw, which involves compiling from source...

**Comment by devrimgunduz** [comment]
@MajdRamadan how are you installing  oracle_Fdw, and what is the OS?

**Comment by laurenz** [comment]
Could you resolve the problem?

**Comment by renatabsb** [comment]
Hi, Laurenz !
I can help me?!


postgres=# CREATE EXTENSION oracle_fdw;
ERROR:  could not load library "/usr/pgsql-15/lib/oracle_fdw.so": /usr/pgsql-15/lib/oracle_fdw.so: undefined symbol: get_rel_all_updated_cols
postgres=# select version();

                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 15.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-15), 64-bit
(1 row)

**Comment by devrimgunduz** [comment]
dnf update postgresql15*

**Comment by laurenz** [comment]
There is a [section in the documentation][doc] that describes which minor releases cannot be used with oracle_fdw.


 [doc]: https://github.com/laurenz/oracle_fdw#5-installation-requirements
