### ISSUE TITLE
 Oracle client library (oci.dll) not found - Oracle Fdw

### ISSUE THREAD

**Issue by SGopishan** [laurenz/oracle_fdw#652]
I have Created Oracle_fdw Extension in postgres. and i have set oracle inveironment path as below
/u01/oracle/db/19.0.0/bin.
During the foreign table select query i am getting below issue.

**ERROR: Oracle client library (oci.dll) not found
DETAIL: No Oracle client is installed, or your system is configured incorrectly.
HINT: Verify that the PATH variable includes the Oracle client.
SQL state: 58000**
Note that, Oracle client installed on Linux and postgres version PostgreSQL 11.8, compiled by Visual C++ build 1914, 64-bit installed in windows server 2016 standard.

Could pls advise how to resolve this issue

**Comment by laurenz** [comment]
What version of oracle_fdw are you using?
How exactly do you start the PostgreSQL server?

Since you are speaking of `oci.dll`, I assume that your PostgreSQL server is running on Windows. But then you need to install Oracle client on that Windows machine too, not on some Linux machine.

**Comment by SGopishan** [comment]
Oracle and PostgreSQL  server should be install on same server?

**Comment by laurenz** [comment]
The Oracle *client* needs to be installed on the machine where the PostgreSQL *server* is.
The Oracle *server* can be anywhere, as long as you can get a network connection.

1.2 is the extension version, but what is the version of oracle_fdw?

**Comment by SGopishan** [comment]
How to check version of oracle_fdw?

**Comment by SGopishan** [comment]
I want to install freshly for all configuration. Could pls share the steps by steps manual  for postgresql 11 to oracle 19.0?

**Comment by laurenz** [comment]
If you can't get oracle_fdw to run yet, the easiest way to find the version (if you don't remember what you downloaded) is to look at `orscle_fdw.h`. The version is in the macro `ORACLE_FDW_VERSION`.

The installation steps are in the documentation.

**Comment by SGopishan** [comment]
I want to remove all the files which i copied from downloaded files. after that, i will install newly all files. could you please share the download link which version suitable for Oracle 19 c and postgresql 11

**Comment by laurenz** [comment]
You can use [the latest development version][devel] or [the latest released version][released].


 [devel]: https://github.com/laurenz/oracle_fdw/archive/refs/heads/master.zip
 [released]: https://github.com/laurenz/oracle_fdw/archive/refs/tags/ORACLE_FDW_2_6_0.zip

**Comment by SGopishan** [comment]
Building oracle_fdw on Windows:
 **below comment was not working.** 
msbuild oracle_fdw.sln /p:Configuration=(Debug or Release) ^
            /p:Platform=(Win32 or x64) ^
            /p:OracleClient=(path to Oracle Client/SDK) ^
            /p:PostgreSQL=(path to PostgreSQL installation)

Could pls provide parameter with details?

**Comment by SGopishan** [comment]
In downloaded file i found msvc folder. what is that and where to copy those files?

**Comment by laurenz** [comment]
Do you have Microsoft's Visual Studio C compiler installed? Otherwise, it won't work.

**Comment by SGopishan** [comment]
i have installed Program Files\Microsoft Visual Studio\2022\Community edition.
![image](https://github.com/laurenz/oracle_fdw/assets/66984760/fa51b989-563d-4ab9-be94-83fcfed79e36)

Could you tell me what configuration need in the Microsoft Visual Studio\2022\Community edition.

**Comment by philflorent** [comment]
Hi,
@SGopishan It seems your databases run on Linux for Oracle and it's a good practice.
Even if you manage to make things work in this particular case, on a long term perspective, I suggest you to also install PostgreSQL on Linux. 
The disclaimer "I don't have any Windows system within reach." is very common among PostgreSQL hackers and experts and the best support, community or commercial, will be with Linux. 
Windows is somehow an exotic platform for PostgreSQL, as it is for Oracle.
Best regards,
Phil

**Comment by SGopishan** [comment]
PostgreSQL on Linux  installation  : i cannot install same oracle running server. can i create new linux server and install postgres? 
I have two server Windows for development  and linux for production. (postgres)

**Comment by SGopishan** [comment]
If i have Linux separate server for postgres. Shall i need to install oracle client on the same postgres server?

**Comment by philflorent** [comment]
Yes and you don't need a full client for oracle-fdw. You need an Oracle Instant Client which is freely available and easy to install : https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html
It's documented on the main page of this git repo.

**Comment by SGopishan** [comment]
Could please support on this oracle_fdw integration remotely?

**Comment by laurenz** [comment]
I can do that, but that would be commercial support - you can contact my company [Cybertec](mailto:sales@cybertec.at).

**Comment by philflorent** [comment]
@laurenz Yes I agree it's not that complicated perhaps I should not have given this advice... That said I really think it's a better idea to run PostgreSQL on Linux in terms of support. At some point tools like Barman had no Windows port for example. You often have a specific Windows section etc.

**Comment by laurenz** [comment]
I do agree that the PostgreSQL experience is better on Linux.

**Comment by SGopishan** [comment]
Dear Laurenz

Could pls share contact email orsend me proposal for configuration windows
server and Linux server
We will check and revert you

Regards
Gopishanmugam

**Comment by SGopishan** [comment]
I have requested could pls check with your team and let me know.

**Comment by laurenz** [comment]
We haven't heard back from you. Shall I close this issue?

**Comment by SGopishan** [comment]
I have discussing with management regarding proposals I will get back to
you coming Tuesday

**Comment by laurenz** [comment]
We could install the extension in an interactive session. These were the steps we had to perform:

- install Oracle Instantclient 19.22
- reinstall VisualStudio, as the installation was messed up somehow
- update PostgreSQL v11 to 11.22, because an API break in PostgreSQL 11.11 made earlier minor releases unusable

Then we could open the "development command prompt" of VisualStudio, change to the `msvc` subdirectory of oracle_fdw and build with `msbuild` according to the documentation.
