### ISSUE TITLE
Thanks for the feedback.

### ISSUE THREAD

**Issue by crruiz0411** [laurenz/oracle_fdw#653]
Thanks for the feedback.
I am still a little worried about the problem you reported with smaller `lob_prefetch`, but I guess I'll wait until somebody else reports a similar problem.

_Originally posted by @laurenz in https://github.com/laurenz/oracle_fdw/issues/621#issuecomment-1792654416_

**Comment by laurenz** [comment]
What are you trying to tell me?

**Comment by crruiz0411** [comment]
[MAIN LOG PARTS - DEBUG2_LEVEL.txt](https://github.com/laurenz/oracle_fdw/files/14603694/MAIN.LOG.PARTS.-.DEBUG2_LEVEL.txt)
[TABLE_DATA_INFORMATION.txt](https://github.com/laurenz/oracle_fdw/files/14603696/TABLE_DATA_INFORMATION.txt)
[HARDWARE_INFORMATION.txt](https://github.com/laurenz/oracle_fdw/files/14603697/HARDWARE_INFORMATION.txt)
[ORACLE_FDW_DIAG.txt](https://github.com/laurenz/oracle_fdw/files/14603698/ORACLE_FDW_DIAG.txt)
[TABLE_DESCRIPTION.txt](https://github.com/laurenz/oracle_fdw/files/14603699/TABLE_DESCRIPTION.txt)

**Comment by crruiz0411** [comment]
Excuse me Laurenz.

I'm using oracle_fdw to migrate an Oracle XE 21c database to Postgreql 16.2.
When I select the first or the last 100 records of a table with CLOB column it is functioning perfectly. But, when I select all records Postgres does an unexpected shutdown.
This occurs with other tables that contain CLOB columns, but I think better to focuse at that one.
The table has 233831 and the longest CLOB record length is 155747.

All the details are at the attached files.

I'm ready If you need more information about the case.

Thank you for your prompted attention.

Best Regrds,

Cláudio Ruiz.

**Comment by crruiz0411** [comment]
The database was renamed to DATABASE_NAME because a NDA.

**Comment by laurenz** [comment]
I see no crash in the log.

Does the oracle_fdw snapshot you are using have commit d62b87614935fdef22ae79661b9b39b7491471dd in it?

There is pretty little I can do about that without a reproducible test case, or at least a stack trace from the crash (if there is a crash).

**Comment by crruiz0411** [comment]
I'll try to grab a crash dump.

**Comment by crruiz0411** [comment]
Hi Laurenz,

I read in one of our colleagues' post that the problem could be in version 21 of the Oracle client. I followed the instructions in the post, removed version 21, installed version 19 and the problem was resolved.

Thank you!

Best Regards,

Cláudio Ruiz

**Comment by laurenz** [comment]
Thanks for letting me know.
The current README has a warning not to use Oracle client 21.

**Comment by laurenz** [comment]
Duplicate of #643 and #614.
