### ISSUE TITLE
Import Schema invalid memory alloc

### ISSUE THREAD

**Issue by NCxZ** [laurenz/oracle_fdw#655]
Hi,

I'm trying to update a schema by dropping it and re-importing to get new tables. The schema has over 10k tables and this import is now giving me an alert.
I am running this block to update the schema often.
```
BEGIN;
DROP SCHEMA SCH CASCADE;
CREATE SCHEMA SCH;
IMPORT FOREIGN SCHEMA "SCHTOIMPORT" FROM SERVER SERV INTO SCH OPTIONS (CASE 'lower' , READONLY 'true');
COMMIT;
```

ERROR: invalid memory alloc request size 1073741824
CONTEXT: import foreign table "batchotupr677777"

Is there a smarter way to update the schema by getting only newly created tables (import schema with a condition)?
I tried tweaking postgre configurations to increare memory, can you suggest a way to resolve this?

Thanks

**Comment by laurenz** [comment]
The limit of 1GB is a hard limit that is not subject to configuration.
Could it be that the total length of all `CREATE FOREIGN TABLE` statements generated exceeds that size?

The best idea that I have is that you create a foreign table that points to Oracle's `USER_TABLES` or `ALL_TABLES`.
Then you can get a list of all tables on the Oracle side and compare that to your foreign tables.
The new tables can be imported with `IMPORT FOREIGN SCHEMA ... LIMIT TO (...)`.
That SQL statement has become more efficient with commit 8d8e80fab7268b1b2980fe07aaaf2c5c13eaf3e7, so you may want to use the latest development version.

**Comment by NCxZ** [comment]
> Could it be that the total length of all `CREATE FOREIGN TABLE` statements generated exceeds that size?

I suppose this is the reason.

I didn't know the usage of LIMIT TO, this solves my problem.
Having an option for "getting tables with name startswith" would be event better in my case.
Thanks
