### ISSUE TITLE
`IMPORT FOREIFN SCHEMA` new `import_views` option

### ISSUE THREAD

**Issue by mkgrgis** [laurenz/oracle_fdw#656]
Hello, @laurenz !
Thanks for great FDW and interesting C code!

This is a feature request.
During data migrations sometimes we need import only really stored relations, not views.
Could you please implement a new option about views import (`import_views`?, default `true`) like in [firebird_fdw](https://github.com/ibarwick/firebird_fdw/blob/0567f72f6d02fa3400d397a3c841db00ffbe12e5/src/firebird_fdw.c#L3563) ? Look like this can touch [this place](https://github.com/laurenz/oracle_fdw/blob/158c03b6eca465f352f20e3e0516d95adc6cb163/oracle_fdw.c#L2304), [this signature](https://github.com/laurenz/oracle_fdw/blob/158c03b6eca465f352f20e3e0516d95adc6cb163/oracle_utils.c#L2514) and [the query](https://github.com/laurenz/oracle_fdw/blob/158c03b6eca465f352f20e3e0516d95adc6cb163/oracle_utils.c#L2521) from `oracleGetImportColumn`.

**Comment by laurenz** [comment]
That's a useful enhancement request.
I'll leave it open; it shouldn't bee hard to implement.
Perhaps I should create a TODO item...

**Comment by mkgrgis** [comment]
@laurenz , also there is materialized views. Users thinks this class of DB objects can have separate flag for export with default `true`. Generally will be useful a comment for foreign table about original object in Oracle like "This is IMPORT FOREIGN SCHEMA foreign table for table|view|materialized view".
I'll try to make a draft for you.
