### ISSUE TITLE
What operational system are supported by Oracle FDW ? Error when compiling in Oracle Linux 9.3

### ISSUE THREAD

**Issue by carlossalheb** [laurenz/oracle_fdw#657]
What operational system are supported by Oracle FDW ?

I have been trying to compile it in Oracle Linux 9.3, and it has been returned the error bellow:

[postgres@vm-oralinux-93 oracle_fdw-master]$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I"/sdk/include" -I"/oci/include" -I"/rdbms/public" -I"/" -I/usr/include/oracle/21/client64 -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_fdw.o oracle_fdw.c
gcc: fatal error: cannot read spec file ‘/usr/lib/rpm/redhat/redhat-hardened-cc1’: No such file or directory
compilation terminated.
make: *** [<builtin>: oracle_fdw.o] Error 1

[postgres@vm-oralinux-93 oracle_fdw-master]$ cat /etc/oracle-release
Oracle Linux Server release 9.3

**Comment by laurenz** [comment]
oracle_fdw should work on all platforms that

- PostgreSQL runs on
- Oracle client runs on

In your case, the problem is a missing package:

```bash
sudo dnf install redhat-rpm-config
```

**Comment by carlossalheb** [comment]
> oracle_fdw should work on all platforms that
> 
> * PostgreSQL runs on
> * Oracle client runs on
> 
> In your case, the problem is a missing package:
> 
> ```shell
> sudo dnf install redhat-rpm-config
> ```

Hi Laurenz,

Thank you for your response.

After the installation of that package, the compilation has been successfully and i've got create extension.

**Comment by laurenz** [comment]
Duplicate of #203.
