### ISSUE TITLE
system user mapping example

### ISSUE THREAD

**Issue by zorroMasked** [laurenz/oracle_fdw#666]
From your documentation: (You can use external authentication to avoid storing Oracle passwords; see below.)

Should I use the same type kind of examples as the extension postgres_fdw with different auth types like system users?

I am able to connect using clear text stored in database but can't seem to get the mappings options right for system users.
The error I get is null password since I used... options (user orauser, password '');   The password set on the linux system is the same.

Hopefully I came to the correct place to ask this question.

Thank you for any help.

**Comment by zorroMasked** [comment]
I downloaded a dev ova from oracle to practice on it is oracle webcenter portal 12c R2(12.2.1) and has all the defaults..

**Comment by laurenz** [comment]
It won't work to set the `password empty`, you need to set the `user` empty:

> User mapping options
> --------------------
>
> - **user** (required)
>
>   The Oracle user name for the session.  
>   Set this to an empty string for *external authentication* if you don't  want to store Oracle credentials in the PostgreSQL database (one simple way  is to use an *external password store*).

How to set up external authentication is Oracle is its own science; you should read the Oracle documentation and look at issues #94 and #162, and perhaps #557 as well. Essentially, any external authentication method you can use with Oracle client can be used with oracle_fdw as well.

**Comment by laurenz** [comment]
Oh, and looking at postgresql_fdw won't help you there, because PostgreSQL authentication is different from Oracle authentication.

**Comment by zorroMasked** [comment]
I should probably use my glasses when reading documentation, thank you for taking the time to answer my question and help me out.  lol

**Comment by laurenz** [comment]
No problem, I am happy that I could help.
