### ISSUE TITLE
oracle_fdw make command fails with : *** [<builtin>: oracle_utils.o] Error 1

### ISSUE THREAD

**Issue by vasu4dba** [laurenz/oracle_fdw#667]
Hi Team,

Can you please help me to figure out the solution for the problem ?  I went through previous solutions and i ensured to set the path correctly.
like ORACLE_HOME, LD_LIBRARY_PATH, PG_GOME..etc.

 echo $ORACLE_HOME
/usr/pgsql-15/instantclient
echo $LD_LIBRARY_PATH
/usr/pgsql-15/instantclient/sdk/include:/usr/pgsql-15/instantclient/sdk/include
 echo $PGHOME
/usr/pgsql-15/bin
 
I used latest oracle_fdw from your github [https://github.com/laurenz/oracle_fdw.git]. kindly help

$make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I"/sdk/include" -I"/oci/include" -I"/rdbms/public" -I"/"  -I. -I./ -I/usr/pgsql-15/include/server -I/usr/pgsql-15/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_utils.o oracle_utils.c
oracle_utils.c:22:10: fatal error: oci.h: No such file or directory
 #include <oci.h>
          ^~~~~~~
compilation terminated.
make: *** [<builtin>: oracle_utils.o] Error 1

Thanks
-Vasu

**Comment by mkgrgis** [comment]
Hello, @vasu4dba ! What about accessible by your include search path `<oci.h>`? Until you can not compile some simple C `main` with `#include <oci.h>` this FDW also will not compile. 
Your include paths like` /usr/pgsql-15/include/server -I/usr/pgsql-15/include/internal` `/usr/include/libxml2`  `/usr/include`  looks normal, but `"/sdk/include"` `"/oci/include"` and `"/rdbms/public"` looks very bad. Does your system really have this directories?
 -I"/sdk/include" -I"/oci/include

**Comment by vasu4dba** [comment]
Hi Mkgrgis,

Yes, those /oci/include or /rdbms/public were came as part of Oracle Instant client pre-requisite.

**Comment by mkgrgis** [comment]
@vasu4dba what about results of `find /usr -type f -name "oci.h"`? In my case there is `/usr/include/oracle/oci.h` and no problems.

**Comment by vasu4dba** [comment]
$ find /usr -type f -name "oci.h"
/usr/pgsql-15/bin/instantclient_21_7/sdk/include/oci.h
/usr/pgsql-15/instantclient/sdk/include/oci.h
$

I don't see issue with actual dependents, I am trying different options from my end, I will update soon.

**Comment by vasu4dba** [comment]
Finally, figured the problem and I was able to run with out any issue.
Issue with the user with sudo priveleges and ran with root no issues.

**Comment by mkgrgis** [comment]
@vasu4dba, for security reasons it's strongly not recommended to use any database servers or clients with root privileges if this is not primitive embedded system. Any compilation works with FDW _except installation_ should be successfully for normal user without root privileges.

**Comment by laurenz** [comment]
@vasu4dba It would be nice if you could tell us what was the cause of the problem; it might help future readers.
Looking at your question, the only reason I can think of is that you set `ORACLE_HOME`, but didn't `export` it, so that it wasn't in the environment of the commands you ran.
