### ISSUE TITLE
ORA-01406 with oracle DATE fields

### ISSUE THREAD

**Issue by legrandlegrand** [laurenz/oracle_fdw#67]
Hello,
Here is my problem / context: 

oracle_diag
--> oracle_fdw 1.3.0, PostgreSQL 9.4.5, Oracle client 10.2.0.5.0, Oracle server 11.2.0.2.0 

When runing queries on my Foreign table containing
varchar, text, and timestamp(0) or date datatypes
(the attached Oracle table is containing Varchar2, Clob and Date datatypes)
It works with varchar or text but fails with timestamp(0) / date :

ERREUR:  error executing query: OCIStmtExecute failed to execute remote query
DÉTAIL : ORA-01406: la valeur de la colonne extraite a été tronquée

Any Idea to fix this ?

Note: I'm using ORAFCE and have set NLS_LANG=american_america.WE8MSWIN1252

Thanks in advance
Regards
PAscal

**Comment by laurenz** [comment]
This is the same bug as #48.

Could you try with the latest version from git?

Note to self: I should release a new version soon.

**Comment by legrandlegrand** [comment]
I'm not able to build from source,
but I changed my LC_MESSSAGES from French_France.1252 to en_US.1252
an error ORA-01406 is gone !
Thank you
