### ISSUE TITLE
 The working principle of oracle_fdw？

### ISSUE THREAD

**Issue by ruralqiu** [laurenz/oracle_fdw#670]
Hello, may I ask if the principle of oracle_fdw is that PG accesses Oracle through an oracle_fdw connection, queries data from Oracle, and then returns the result set to PG for display?

**Comment by mkgrgis** [comment]
@ruralqiu , this is very common description. Full list of PostgreSQL functions implemented by `oracle_fdw`  and executed for OracleDB or inside of OracleDB is [here](https://github.com/laurenz/oracle_fdw/blob/33c4086ac346f2afc6153a4ce59a4cf8c63c505a/oracle_fdw.c#L442).

**Comment by laurenz** [comment]
Yes, your description is pretty accurate. Another way to think of it is that a foreign table is somewhat like a view: it does not store any data, and whenever you read or write, it is actually the underlying Oracle table that is accessed.

**Comment by ruralqiu** [comment]
> Yes, your description is pretty accurate. Another way to think of it is that a foreign table is somewhat like a view: it does not store any data, and whenever you read or write, it is actually the underlying Oracle table that is accessed.

OK，So I can understand it as follows: there is no relationship between oracle_fdw and the performance of the postgreSQL environment, is it？

**Comment by laurenz** [comment]
As long as you don't access foreign tables, oracle_fdw should have no impact on the performance of PostgreSQL.
If you read from a foreign table, and the query on the Oracle side takes a long time, or if the data transfer rate is slow, that will also affect the performance on the PostgreSQL side.

**Comment by ruralqiu** [comment]
> As long as you don't access foreign tables, oracle_fdw should have no impact on the performance of PostgreSQL. If you read from a foreign table, and the query on the Oracle side takes a long time, or if the data transfer rate is slow, that will also affect the performance on the PostgreSQL side.

Okay,thanks, I understand now. Will I use indexes to improve query speed when I create indexes in Oracle tables that are mapped externally?

**Comment by laurenz** [comment]
Indexes on the Oracle side will get used at the discretion of Oracle. PostgreSQL knows nothing about them. All it does is send a query (look at the `EXPLAIN` output), and Oracle decides if it wants to use an index or not (look at the `EXPLAIN (VERBOSE)` output).

**Comment by ruralqiu** [comment]
Okay, thank you very much
