### ISSUE TITLE
Unable to get the header files for windows environment

### ISSUE THREAD

**Issue by Itv1529** [laurenz/oracle_fdw#677]
i am trying to setup both the oracle19.3 and postgresql12.19 in windows. 
while setting up the environment it is lacking of these header files "postgres.h", "oci.h" ,"unistd.h". 

help for this.

**Comment by laurenz** [comment]
- if `postgres.h` is missing, you didn't install the PostgreSQL C headers, or you didn't supply the correct path to the build process
- if `oci.h` is missing, you didn't install the Oracle software development kit, or you didn't supply the correct path to the build process
- if `unistd.h` is missing, you don't have a C development environment installed on the machine

Make sure to follow the [installation instructions][build] and have all the [requirements][req] installed.

Please show me the exact steps you followed from the beginning and provide a literal copy of the error messages you get.


 [build]: https://github.com/laurenz/oracle_fdw#building-oracle_fdw-on-windows
 [req]: https://github.com/laurenz/oracle_fdw#5-installation-requirements

**Comment by Itv1529** [comment]
installing and running the oracle_fdw.sln from the visual studio getting this error. 

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C1083	Cannot open include file: 'postgres.h': No such file or directory	oracle_fdw	C:\oracle_fdw-master\oracle_fdw.c	8		

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C1083	Cannot open include file: 'oci.h': No such file or directory	oracle_fdw	C:\oracle_fdw-master\oracle_gis.c	15		

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C1083	Cannot open include file: 'unistd.h': No such file or directory	oracle_fdw	C:\oracle_fdw-master\oracle_utils.c	12		



Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C1083	Cannot open include file: 'postgres.h': No such file or directory	oracle_fdw	C:\oracle_fdw-master\msvc\oracle_msvc.c	1

**Comment by laurenz** [comment]
Ok, so we have the error messages and we know that you are using Visual Studio.

So what exactly did you do *before* you started the build?

**Comment by laurenz** [comment]
Any update here, or shall I close the issue?
