### ISSUE TITLE
performances : is there a way to change FETCH SIZE ?

### ISSUE THREAD

**Issue by legrandlegrand** [laurenz/oracle_fdw#68]
Hello,

when monitoring SQL on the ORACLE side ( looking at executions, fetches, rows_processed in V$SQL view) it seems that FETCH SIZE is set to 1.
Is there a way to change that setting to reduce data transfert time ?

regards
PAscal

**Comment by laurenz** [comment]
oracle_fdw uses prefetching with OCI_ATTR_PREFETCH_ROWS set to 200 and OCI_ATTR_PREFETCH_MEMORY set to 24576 (see the [OCI Programmer's Guide](http://docs.oracle.com/cd/E11882_01/appdev.112/e10646/oci04sql.htm#LNOCI16355)).

See [here](https://github.com/laurenz/oracle_fdw/blob/master/oracle_utils.c#L26) and [here](https://github.com/laurenz/oracle_fdw/blob/master/oracle_utils.c#L1782) in the source.

This works fine here.

First, let's check the current values in Oracle:

    SQL> SET LINE 130
    SQL> COL SQL_TEXT FORMAT A70
    SQL> SELECT sql_id, FETCHES, executions, ROWS_PROCESSED, sql_text FROM v$sql WHERE sql_id = 'funhwbzwb57wv';
    
    SQL_ID           FETCHES EXECUTIONS ROWS_PROCESSED SQL_TEXT
    ------------- ---------- ---------- -------------- ----------------------------------------------------------------------
    funhwbzwb57wv          2          2              5 SELECT /*0dc94d5400fd952cc37dfb2974a17de8*/ "ID", "VAL" FROM "GUID"

Then perform a query with oracle_fdw:

    test=> SELECT id, val FROM guid;
    ┌────┬──────────────────────────────────────┐
    │ id │                 val                  │
    ├────┼──────────────────────────────────────┤
    │  1 │ 21e8acbf-7794-0c6d-e053-1645990a14fa │
    │  2 │ 2e2af02b-0779-1aa6-e053-1645990a5505 │
    │  3 │ 2e2af02b-077a-1aa6-e053-1645990a5505 │
    │  4 │ 2e2af02b-077b-1aa6-e053-1645990a5505 │
    └────┴──────────────────────────────────────┘
    (4 rows)

Then check again with Oracle:

    SQL> SELECT sql_id, FETCHES, executions, ROWS_PROCESSED, sql_text FROM v$sql WHERE sql_id = 'funhwbzwb57wv';
    
    SQL_ID           FETCHES EXECUTIONS ROWS_PROCESSED SQL_TEXT
    ------------- ---------- ---------- -------------- ----------------------------------------------------------------------
    funhwbzwb57wv          3          3              9 SELECT /*0dc94d5400fd952cc37dfb2974a17de8*/ "ID", "VAL" FROM "GUID"

Four more rows, but only one additional fetch.
So all rows were fetched together.

There is a note in the Oracle documentation saying:

> Prefetching is not in effect if LONG, LOB or Opaque Type columns (such as XMLType) are part of the query.

Maybe that is the problem for you.
What is the Oracle query and the data types involved (use EXPLAIN in PostgreSQL)?

**Comment by legrandlegrand** [comment]
That's it !
I had tested with 2 tables, the first contains a LONG, the second contains 2 CLOB.
--> 1 row per fetch
Removing thoses fields from the selects has corrected the problem,
--> ~200 rows per fetch

Thanks for your detailled and pertinent answer !

**Comment by tevariou** [comment]
@laurenz can we have a small note in the README regarding the issue with the BLOB data type ?

**Comment by laurenz** [comment]
@tevariou Good idea; done.
