### ISSUE TITLE
"oracle_fdw" extension - does not support secure connection (Wallet/SSL/TLS).

### ISSUE THREAD

**Issue by shay-salomon-db** [laurenz/oracle_fdw#680]
For "oracle_fdw" extension; it seems currently the secure connection (Wallet/SSL/TLS) feature is not available.

**Comment by shay-salomon-db** [comment]
For "oracle_fdw" extension; it seems currently the secure connection (Wallet/SSL/TLS) feature is not available in GCP.

**Comment by laurenz** [comment]
That is quite possible. After all, you'd have to install the wallet on the database server, and Google won't give you file system access.

You'd have to take that up with Google.

**Comment by laurenz** [comment]
Can we close the issue?
