### ISSUE TITLE
issue with oracle_fdw on Postgres 16.3 

### ISSUE THREAD

**Issue by anujneo** [laurenz/oracle_fdw#683]
I have installed oracle_fdw-2.5.0 on Rocky Linux 9.4 with Postgres 16.3.

While creating extension, I am receiving following error.

enq=# create extension oracle_fdw;
ERROR:  could not load library "/usr/pgsql-16/lib/oracle_fdw.so": /usr/pgsql-16/lib/oracle_fdw.so: undefined symbol: bms_first_member

What am I missing ?

**Comment by laurenz** [comment]
This is a duplicate of #612, #618, #639 and #681.

You have to use a more recent version of oracle_fdw, and you have to build it with the PostgreSQL version that you are using.

**Comment by anujneo** [comment]
Thanks.

I used the RPM installation instead and that worked successfully.

Thanks for the support.
