### ISSUE TITLE
Slowly operation of data overload.

### ISSUE THREAD

**Issue by Barsu4ello** [laurenz/oracle_fdw#686]
Hello again, dear developers!

I have operation of data overload like this:
INSERT INTO target_table (column1, column2, column3)
SELECT column1, column2, column3
FROM source_table
WHERE condition;

And if i need overload 200 000 row this spent 4-5 min. Each row contains 7 field (character varying(256)).
This situation is normally or mayby i can do it faster?
Thank you very much!

**Comment by laurenz** [comment]
If `target_table` is an oracle_fdw foreign table, that is pretty normal.
Each inserted row is a round trip between PostgreSQL and Oracle, so with a network latency of 0.5 milliseconds, that's the duration I would expect.

**Comment by Barsu4ello** [comment]
Thnak you very much for this information!
Good day!
