### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by Chonghaolong** [laurenz/oracle_fdw#687]
CREATE EXTENSION oracle_fdw;

ERROR:  could not load library "/usr/local/gpdb-main/lib/postgresql/oracle_fdw.so": /usr/local/gpdb-main/lib/postgresql/oracle_fdw.so: undefined symbol: MemoryContextDelete

**Comment by Chonghaolong** [comment]
The version is 2.6.0

**Comment by laurenz** [comment]
Strange.
Perhaps you could start by telling me

- the operating system you are using
- the PostgreSQL version you are using
- how you did install PostgreSQL
- how you built and installed oracle_fdw

**Comment by Chonghaolong** [comment]
the operating system is  Rocky9.4    the PostgreSQL version is 12.12  I use postgresql from greenplum7.2-beta  I used both oracle_fdw-ORACLE_FDW_2_6_0.tar.gz and  oracle_fdw-ORACLE_FDW_2_3_0.tar.gz   to have this problem and used oracle-instantclient19.19 development packages

**Comment by laurenz** [comment]
I guess "Greenplum" is the problem here.

Can you check if it works with regular PostgreSQL on your system?

**Comment by Chonghaolong** [comment]
we need use greenplum wo we not have regular PostgreSQL in any system   the greenplum uesd postgresql12.12  I try install the s postgresql12-devel package in /usr/pgsql-12  and edit the MakeFile to make (Added parameter PG_CPPFLAGS   -I/usr/pgsql-12/include/server -I/usr/include/oracle/19.19/client64)

**Comment by Chonghaolong** [comment]
![1720057917015](https://github.com/laurenz/oracle_fdw/assets/107032891/84478c25-98ad-4ac1-94bd-fbc8bdb7b1d4)

**Comment by laurenz** [comment]
I don't understand your last two comments.

Anyway, if you need to use Greenplum, I guess you cannot use oracle_fdw.
oracle_fdw is an extension for PostgreSQL.

**Comment by Chonghaolong** [comment]
I  finished about that

**Comment by laurenz** [comment]
So you mean you got oracle_fdw to build with Greenplum?
If yes, that would be interesting to know.
What did you have to do to make it work?
