### ISSUE TITLE
can't upgrade to version 1.3.0

### ISSUE THREAD

**Issue by MARCELVIS** [laurenz/oracle_fdw#69]
Hey Laurenz:

My co-workers and I are still unable to upgrade to version 1.3.0 from 1.1.

Just wanted to check in to see if there are any known issues with the versions of Postgres, Ubuntu or the Oracle client we are using:

- Postgres: version 9.5.0
- Ubuntu 14.04.3
-Oracle client 12

Thanks.

-- marcel

**Comment by laurenz** [comment]
I have no experience with Ububtu Linux, but that should be pretty straightforward.

Could you tell me what exactly you did and what happened, with copy-and-paste error messages, ideally a session transcript.
Then I'll probably be able to help you.

**Comment by MARCELVIS** [comment]
I executed the make, make install commands as per the install instructions - no errors.

Speaking with my co-workers looks like the functionality works fine though the version being displayed is till 1.1.

Is it possible there is a minor bug that isn't updating the version number?

**Comment by laurenz** [comment]
Oh, I see.
No, everything is perfect.

The 1.1 you see with <tt>\dx</tt> is not the version of oracle_fdw, but the version of the extension.
The extension version is only upgraded if the definition of the objects in the extension changes, which fortunately doesn't happen with every release of oracle_fdw.

To see the version of oracle_fdw, run

    SELECT oracle_diag();
