### ISSUE TITLE
ERROR:  could not load library "/usr/lib/postgresql/16/lib/oracle_fdw.so": libaio.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by iomatters** [laurenz/oracle_fdw#691]
# CREATE EXTENSION oracle_fdw;
ERROR:  could not load library "/usr/lib/postgresql/16/lib/oracle_fdw.so": libaio.so.1: cannot open shared object file: No such file or directory

Version: psql (16.3 (Ubuntu 16.3-1.pgdg24.04+1)), instantclient_23_4

# apt search libaio
Sorting... Done
Full Text Search... Done
libaio-dev/noble,now 0.3.113-6build1 amd64 [installed]
  Linux kernel AIO access library - development files

libaio1t64/noble,now 0.3.113-6build1 amd64 [installed]
  Linux kernel AIO access library - shared library

libaio-dev and libaio1t64 are both installed.

Am I missing anything ?

**Comment by iomatters** [comment]
Fixed, for those who're ionterested:
ln -s /usr/lib/x86_64-linux-gnu/libaio.so /usr/lib/x86_64-linux-gnu/libaio.so.1

**Comment by laurenz** [comment]
I cannot recommend that. You shouldn't create links like that.

On my Ubuntu 22.04 system, all you need to do is install the library:

```bash
sudo apt install libaio1
```

That provides `/usr/lib/x86_64-linux-gnu/libaio.so.1.0.1`.

**Comment by iomatters** [comment]
~# cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

**Comment by iomatters** [comment]
# apt install libaio1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libaio1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libaio1' has no installation candidate

**Comment by laurenz** [comment]
I found [this](https://askubuntu.com/questions/1512196/libaio1-on-noble/1512197#1512197).
Anyway it seems to be a problem of configuring Oracle and the operating system rather than a problem of oracle_fdw.

**Comment by iomatters** [comment]
Well I understand that's a problem of configuring Oracle, still would be nice to mention that unless you don't officially support 24.04 LTS.

**Comment by laurenz** [comment]
Any operating system that supports PostgreSQL server and Oracle client should work.

Perhaps this issue will be interesting for others with a similar problem.
I just had to add that your solution is not correct and may cause trouble in the future.
