### ISSUE TITLE
ORA-12545: Connect failed because target host or object does not exist

### ISSUE THREAD

**Issue by marcodsivo** [laurenz/oracle_fdw#698]
I have two connections created to an Oracle 11g server and I am accepting the following error below.

Connections below

CREATE SERVER ora_1
	FOREIGN DATA WRAPPER oracle_fdw
	OPTIONS (servidordb '//HOSTNAME:1523/APEX');
	
CREATE SERVER ora_2
	FOREIGN DATA WRAPPER oracle_fdw
	OPTIONS (serverdb '//IP:1523/APEX');
	
However, in both connections I receive the following error 

2024-08-02 07:29:59.218 -04 [1835397] ERROR: connection to external table "test" cannot be established
2024-08-02 07:29:59.218 -04 [1835397] DETAIL: ORA-12545: Connection failed because target host or object does not exist

I can telnet connect to both IP and HOSTNAME on port 1523 and I still receive the error above.

The "test" table is a simple "SELECT 1 FROM dual" for oracle.

My server's listener in oracle looks like this:

APEX =
  (ADDRESS_LIST =
        (ADDRESS= (PROTOCOL=TCP)(Host= IP )(Port=1523))
  )

APEX =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(Host = IP )(Port = 1523))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = APEX)
    )
  )

  
  What I noticed is that when I restart the listener, the postgres connection via dblink starts working again for a few seconds, but then the above error returns. The same happens when I try to make a connection through sqlplus on the postgres server.

**Comment by laurenz** [comment]
Sorry, that looks like an Oracle or, more likely, a network problem, particularly since you get the same behavior with `sqlplus`.
I cannot help you with network problems.

**Comment by marcodsivo** [comment]
Resolvido. Precisei colocar dentro do arquivo  /etc/hosts do servidor postgres o IP do oracle junto com 3 hostnames e no servidor oracle o IP e hostname do servidor postgres

**Comment by laurenz** [comment]
To translate: it was a DNS problem.
