### ISSUE TITLE
Regression tests failing on PostgreSQL 16 and Oracle 23ai Free (23.4.0.0)

### ISSUE THREAD

**Issue by alperkocatas** [laurenz/oracle_fdw#700]
I tried to run the oracle_fdw regression tests using PostgreSQL 16 and the [docker container for Oracle database 23ai ](https://container-registry.oracle.com/ords/f?p=113:4:9851618742311:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:1863,1863,Oracle%20Database%20Free,Oracle%20Database%20Free,1,0&cs=3gnaGt0XrVFaNdDiWwPhScks7A63u3gUhOKgYSTai96Z--XLSOoluwRt3gMumhhCp3_pfozqJFLe5Y-9BfOpbqQ) (23.4.0.0). 

I am getting a few seemingly minor differences in the expected values, causing `oracle_fdw` tests to fail. I feel like the error messages emitted by Oracle database might have been changed since the tests were developed. 

I am not sure about the `+   InitPlan 1 (returns $0)` message, though. Can you please comment if these changes are as expected and minor? If the expected values of the tests should be updated with the observed results, I would be happy to update the tests and create a pull request. 

Thanks. 

Note: The readme indicates any oracle server with version 10.2 or better would be ok. 

Here is my overall output: 

```
not ok 1     - oracle_fdw                               2976 ms
ok 2         - oracle_gis                                598 ms
ok 3         - oracle_import                            1171 ms
ok 4         - oracle_join                               620 ms
1..4
# 1 of 4 tests failed.
```

When I look at regression.diffs, I see:

```
diff -U3 /home/azuredb/orcasql-postgresql/contrib_3rd_party/oracle_fdw/expected/oracle_fdw.out /home/azuredb/orcasql-postgresql/contrib_3rd_party/oracle_fd
w/results/oracle_fdw.out
--- /home/azuredb/orcasql-postgresql/contrib_3rd_party/oracle_fdw/expected/oracle_fdw.out       2024-08-06 18:38:26.730667400 +0000
+++ /home/azuredb/orcasql-postgresql/contrib_3rd_party/oracle_fdw/results/oracle_fdw.out        2024-08-20 11:51:35.673340162 +0000
@@ -238,7 +238,8 @@

 DELETE FROM typetest1;
 ERROR:  error executing query: OCIStmtExecute failed to execute remote query
-DETAIL:  ORA-01456: may not perform insert/delete/update operation inside a READ ONLY transaction
+DETAIL:  ORA-01456: may not perform insert, delete, update operation inside a READ ONLY transaction
+Help: https://docs.oracle.com/error-help/db/ora-01456/
 -- use the default SERIALIZABLE isolation level from now on
 ALTER SERVER oracle OPTIONS (DROP isolation_level);
 SELECT oracle_close_connections();
@@ -362,7 +363,9 @@
 -- will cause an error
 INSERT INTO shorty (id, c) VALUES (1, 'c');
 ERROR:  error executing query: OCIStmtExecute failed to execute remote query
-DETAIL:  ORA-00001: unique constraint (SCOTT.TYPETEST1_PKEY) violated
+DETAIL:  ORA-00001: unique constraint (SCOTT.TYPETEST1_PKEY) violated on table SCOTT.TYPETEST1 columns (ID)
+ORA-03301: (ORA-00001 details) row with column values (ID:1) already exists
+Help: https://docs.oracle.com/error-help/db/ora-00001/
 ROLLBACK TO one;
 INSERT INTO shorty (id, c) VALUES (2, 'c');
 ROLLBACK TO one;
@@ -403,7 +406,7 @@
 ----------------------------------------------------------------------------------------------------------------------------------------------------
  Foreign Scan on typetest1
    Oracle query: SELECT /*fdfac5fa5afb2dc8*/ r1."ID", r1."VC" FROM "TYPETEST1" r1 WHERE (r1."VC" IN ('short', :p1)) ORDER BY r1."ID" ASC NULLS LAST
-   InitPlan 1
+   InitPlan 1 (returns $0)
      ->  Result
 (4 rows)

@@ -928,7 +931,7 @@
 SET SESSION AUTHORIZATION duff;
 -- this should fail
 SELECT id FROM typetest1 ORDER BY id;
-ERROR:  user mapping not found for user "duff", server "oracle"
+ERROR:  user mapping not found for "duff"
 -- these should succeed
 SELECT id FROM v_typetest1 ORDER BY id;
  id
```

**Comment by laurenz** [comment]
Thank you for the report.
You probably get these differences because your are using a different version of Oracle and PostgreSQL.
I developed the regression tests with the latest PostgreSQL development version (Git HEAD) and Oracle 18 XE.
You are probably using an older PostgreSQL version and a newer Oracle server version.

Ideally, I should maintain alternative regression test response files that cover all versions, but that would be hell to maintain, so I just leave it as it is.
It is certainly annoying for you to get these differences, but as you see, there is no serious discrepancy.

Can you live with that?
