### ISSUE TITLE
Installation Bug

### ISSUE THREAD

**Issue by leopoldev404** [laurenz/oracle_fdw#708]
![image](https://github.com/user-attachments/assets/c15c5e29-b189-4cc6-a825-d25b39889864)

When trying to run the make script I get the error shown in the image

**Comment by laurenz** [comment]
This has been reported before, see #286, #403, #405 or #447 (among others).

You need to install the Oracle SDK as documented.

**Comment by leopoldev404** [comment]
Thanks for replying!
I did not see anything about oracle sdk in the documentation, are there any useful link to the oracle sdk installation on linux?

**Comment by laurenz** [comment]
It's right there in the documentation:

> You need to install Oracle's C header files as well (SDK package for Instant
> Client).  If you use the Instant Client ZIP files provided by Oracle,
> you may have to create a symbolic link from `libclntsh.so` to the actual shared
> library file yourself (normally, the SDK package does that).

How exactly you have to install it depends a lot on what Oracle client you installed and how. Just do the same moves for the SDK.

**Comment by leopoldev404** [comment]
so I followed the recommended approach for oracle sdk installation, but seems it's not working.

OS: linux ubuntu 22.04 (on a docker container)
Postgres 9.6
downloaded oracle sdk instaclient: https://download.oracle.com/otn_software/linux/instantclient/2350000/instantclient-basic-linux.x64-23.5.0.24.07.zip

any instructions on which could be the cause?

**Comment by laurenz** [comment]
Thanks for your cooperation.

Please tell me details:
- How exactly did you install instant client? Ideally, show me the exact commands you ran.
- How exactly did you install the SDK? I guess you didn't only download it, right?
- Did you set any environment variables before you ran `make`? Did you follow the documentation:
  > Set the environment variable ORACLE_HOME to the location of the Oracle
  > installation.

**Comment by leopoldev404** [comment]
# Download and install Oracle Instant Client
# Oracle Instant Client variables - updated for 23.5
ENV ORACLE_HOME=/usr/lib/oracle/instantclient_23_5
ENV LD_LIBRARY_PATH=/usr/lib/oracle/instantclient_23_5
ENV TNS_ADMIN=/usr/lib/oracle/instantclient_23_5/network/admin

WORKDIR /tmp
RUN wget https://download.oracle.com/otn_software/linux/instantclient/2350000/instantclient-basic-linux.x64-23.5.0.24.07.zip
RUN wget https://download.oracle.com/otn_software/linux/instantclient/2350000/instantclient-sdk-linux.x64-23.5.0.24.07.zip
RUN mkdir -p /usr/lib/oracle
RUN unzip instantclient-basic-linux.x64-23.5.0.24.07.zip -d /usr/lib/oracle
RUN unzip instantclient-sdk-linux.x64-23.5.0.24.07.zip -d /usr/lib/oracle
RUN rm instantclient-basic-linux.x64-23.5.0.24.07.zip
RUN rm instantclient-sdk-linux.x64-23.5.0.24.07.zip

# Create symbolic links for Oracle Instant Client 23.5
RUN cd /usr/lib/oracle/instantclient_23_5 && ln -s libclntsh.so.23.1 libclntsh.so && ln -s libocci.so.23.1 libocci.so

# Create a symbolic link for the OCI library
RUN ln -s /usr/lib/oracle/instantclient_23_5/libclntsh.so.23.1 /usr/lib/libclntsh.so

# Update the dynamic linker cache
RUN echo "/usr/lib/oracle/instantclient_23_5" >/etc/ld.so.conf.d/oracle.conf && ldconfig

# Download and compile oracle_fdw
RUN git clone https://github.com/laurenz/oracle_fdw.git && cd oracle_fdw && make && make install

**Comment by laurenz** [comment]
That looks fine (except I don't see where you installed PostgreSQL).
But the image you showed in the beginning shows that `ORACLE_HOME` was **not** set when you ran `make`.
That's where you have to investigate.

**Comment by leopoldev404** [comment]
I have updated it

**Comment by leopoldev404** [comment]
do I need both oracle client and sdks?

**Comment by leopoldev404** [comment]
am I missing something?

**Comment by laurenz** [comment]
9.6? Are you kidding?

Anyway, the image at the very beginning of this thread still proves that `ORACLE_HOME` was **not set**.

**Comment by leopoldev404** [comment]
yeah, for business requirement I need to use 9.6, I need to replicate locally an old prod db.
Anyway, I have updated the steps

**Comment by laurenz** [comment]
Yes, you forgot to read my last two comments. I'm not going to repeat it.

**Comment by leopoldev404** [comment]
I got your point but I don't understand why it should not be initialized.
Should I use ENV instead of export? I am populating the ORACLE_HOME variable

**Comment by laurenz** [comment]
Well, the variable is not populated.
I'm not dealing with Docker, so I cannot tell you where you made a mistake.
But it is not a problem of oracle_fdw, it is a problem of your dockerfile.

**Comment by chrullrich** [comment]
Just in case:

- The Oracle client and SDK are two different things. You need both.
- Nowhere in this thread does a download URL for the SDK package appear, but at one point the client package is extracted into a directory named "sdk". This is wrong.
- There are multiple different download URLs for the client package mentioned. The one in the quoted Dockerfile is for Linux on zSeries, but a bit above a URL for an x64 package appears. (While z is definitely the platform it would surprise me the least to find a 9.6 production installation, are you really developing for an IBM mainframe?)
- Using `RUN export ...` appears to be wrong; there is documentation that says each `RUN` starts a new shell. A variable set this way in one line would not exist anymore in the next. `ENV` seems to be the correct way to add environment variables for subsequent commands.

**Comment by laurenz** [comment]
@chrullrich Thanks for the help.

**Comment by laurenz** [comment]
Is this case resolved, can I close the issue?
