### ISSUE TITLE
CREATE EXTENSION oracle_fdw failed with ERROR could not load oracle_fdw.so

### ISSUE THREAD

**Issue by denissun** [laurenz/oracle_fdw#710]
postgres=# CREATE EXTENSION oracle_fdw;
ERROR:  could not load library "/usr/pgsql-16/lib/oracle_fdw.so": libclntsh.so.19.1: cannot open shared object file: No such file or directory
postgres=

postgres=# select version();
                                                 version
----------------------------------------------------------------------------------------------------------
 PostgreSQL 16.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3), 64-bit
(1 row)

ORACLE_HOME is  oracle server 19.3

oracle_fdw is 2.8

root@tpalpf9ivd003:/u01/stage/oracle_fdw # head CHANGELOG
Version 2.8.0

  Bugfixes:
  - Throw an error if "ctid" or other system columns are used in the WHERE
    clause.  Since these columns have no meaning in Oracle, they are assigned

---  the file exist:
/u01/stage/oracle_fdw [] $ ls -lh /usr/pgsql-16/lib/oracle_fdw.so
-rwxr-xr-x 1 root root 619K Oct 10 12:09 /usr/pgsql-16/lib/oracle_fdw.so

**Comment by laurenz** [comment]
This is a duplicate; see #22 and #440.

It is also covered in the documentation:
> Since the Oracle client shared library is probably not in the standard
> library path, you have to make sure that the PostgreSQL server will be able
> to find it.  How this is done varies from operating system to operating
> system; on Linux you can set LD_LIBRARY_PATH or use `/etc/ld.so.conf`.
