### ISSUE TITLE
Oracle_FDW 2.6.0 zip file PostgreSQL15 for Windows

### ISSUE THREAD

**Issue by takashiyf15** [laurenz/oracle_fdw#713]
Hi Laurenz,

I would like to use the win64 version of oracle_fdw2.6.0 to use with PostgreSQL15. 
I don't have compilation environment, could you please provide me build files like a oracle_fdw-2.5.0-pg15-win64.zip.

Best regards.

**Comment by laurenz** [comment]
I don't have access to a Windows system, sorry.
