### ISSUE TITLE
Issue with oracle_fdw file when upgrading between postgres16 and 17 - MemoryContextAllocZeroAligned

### ISSUE THREAD

**Issue by adam-shenker** [laurenz/oracle_fdw#716]
Hi,

I have both Postgresql16 and 17 installed on a single redhat 9.4 server

On Postgresql16 I have oracle_fdw version 2.6.0 fully installed
On postgresql17 I have oracle_fdw version 2.7.0 installed (make and make install completed successfully plus conf file changes - nothing else)

Postgresql17 has had initdb run with a different port (5433) and the config files have had the same changes added as the postgresql16 server.

When running pg_upgrade I get an fdw based error that I do not know how to solve:

[postgres@server ~]$ time /usr/pgsql-17/bin/pg_upgrade --old-bindir /usr/pgsql-16/bin --new-bindir /usr/pgsql-17/bin --old-datadir /var/lib/pgsql/16/data --new-datadir /var/lib/pgsql/17/data  --check
Performing Consistency Checks on Old Live Server
------------------------------------------------
Checking cluster versions                                     ok
Checking database user is the install user                    ok
Checking database connection settings                         ok
Checking for prepared transactions                            ok
Checking for contrib/isn with bigint-passing mismatch         ok
Checking data type usage                                      ok
Checking for presence of required libraries                   fatal

Your installation references loadable libraries that are missing from the
new installation.  You can add these libraries to the new installation,
or remove the functions using them from the old installation.  A list of
problem libraries is in the file:
    /var/lib/pgsql/17/data/pg_upgrade_output.d/20241113T073832.829/loadable_libraries.txt
Failure, exiting

real    0m0.623s
user    0m0.059s
sys     0m0.074s
[postgres@server ~]$ cat /var/lib/pgsql/17/data/pg_upgrade_output.d/20241113T073832.829/loadable_libraries.txt
could not load library "$libdir/oracle_fdw": ERROR:  could not load library "/usr/pgsql-17/lib/oracle_fdw.so": /usr/pgsql-17/lib/oracle_fdw.so: undefined symbol: MemoryContextAllocZeroAligned
In database: ora_tasks

The database ora_tasks exists in postgresql16 and not in postgres17 as of yet.

Can you please give me a direction in where to look to try and solve this issue?
This is on a dev environment (prior to prod upgrade)

With thanks,

Adam.

**Comment by mkgrgis** [comment]
@adam-shenker , please refer `pg_config` usage for pointing to non-default PostgreSQL version. This names _compiling for any existed PostgreSQL version on a system_.

**Comment by adam-shenker** [comment]
Hi,

The output is below

$ pg_config
BINDIR = /usr/pgsql-17/bin
DOCDIR = /usr/pgsql-17/doc
HTMLDIR = /usr/pgsql-17/doc/html
INCLUDEDIR = /usr/pgsql-17/include
PKGINCLUDEDIR = /usr/pgsql-17/include
INCLUDEDIR-SERVER = /usr/pgsql-17/include/server
LIBDIR = /usr/pgsql-17/lib
PKGLIBDIR = /usr/pgsql-17/lib
LOCALEDIR = /usr/pgsql-17/share/locale
MANDIR = /usr/pgsql-17/share/man
SHAREDIR = /usr/pgsql-17/share
SYSCONFDIR = /etc/sysconfig/pgsql
PGXS = /usr/pgsql-17/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE =  '--enable-rpath' '--prefix=/usr/pgsql-17' '--includedir=/usr/pgsql-17/include' '--mandir=/usr/pgsql-17/share/man' '--datadir=/usr/pgsql-17/share' '--libdir=/usr/pgsql-17/lib' '--with-lz4' '--with-zstd' '--enable-tap-tests' '--with-icu' '--with-llvm' '--with-perl' '--with-python' '--with-tcl' '--with-tclconfig=/usr/lib64' '--with-openssl' '--with-pam' '--with-gssapi' '--with-includes=/usr/include' '--with-libraries=/usr/lib64' '--enable-nls' '--enable-dtrace' '--with-uuid=e2fs' '--with-libxml' '--with-libxslt' '--with-ldap' '--with-selinux' '--with-systemd' '--with-system-tzdata=/usr/share/zoneinfo' '--sysconfdir=/etc/sysconfig/pgsql' '--docdir=/usr/pgsql-17/doc' '--htmldir=/usr/pgsql-17/doc/html' 'CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-Wl,--as-needed' 'LLVM_CONFIG=/usr/bin/llvm-config-64' 'CLANG=/usr/bin/clang' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -L/usr/lib64 -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-17/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lselinux -lzstd -llz4 -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lm
VERSION = PostgreSQL 17.0
[postgres@postgres-dev ~]$


It is only showing the new installation.

With thanks for your help.

Adam.

**Comment by mkgrgis** [comment]
@adam-shenker , this is normal output for PostgreSQL 17. That is default version on your system. What about 

> Also please check if include headers of your Oracle client are accessible form usual C language context.

?

**Comment by adam-shenker** [comment]
Hi,

Thank you.
I did not run make clean.

The output now is 👍 
$ make clean
rm -f oracle_fdw.so   liboracle_fdw.a  liboracle_fdw.pc
rm -f oracle_fdw.o oracle_utils.o oracle_gis.o oracle_fdw.bc oracle_utils.bc oracle_gis.bc
rm -rf results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/ output_iso/
postgres$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -fvisibility=hidden -I"/u01/app/oracle/product/21.0.0/client_1//sdk/include" -I"/u01/app/oracle/product/21.0.0/client_1//oci/include" -I"/u01/app/oracle/product/21.0.0/client_1//rdbms/public" -I"/u01/app/oracle/product/21.0.0/client_1//"  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_fdw.o oracle_fdw.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -fvisibility=hidden -I"/u01/app/oracle/product/21.0.0/client_1//sdk/include" -I"/u01/app/oracle/product/21.0.0/client_1//oci/include" -I"/u01/app/oracle/product/21.0.0/client_1//rdbms/public" -I"/u01/app/oracle/product/21.0.0/client_1//"  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_utils.o oracle_utils.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -fvisibility=hidden -I"/u01/app/oracle/product/21.0.0/client_1//sdk/include" -I"/u01/app/oracle/product/21.0.0/client_1//oci/include" -I"/u01/app/oracle/product/21.0.0/client_1//rdbms/public" -I"/u01/app/oracle/product/21.0.0/client_1//"  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_gis.o oracle_gis.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -fvisibility=hidden -shared -o oracle_fdw.so oracle_fdw.o oracle_utils.o oracle_gis.o -L/usr/pgsql-17/lib  -Wl,--as-needed -L/usr/lib64  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-17/lib',--enable-new-dtags -fvisibility=hidden -L"/u01/app/oracle/product/21.0.0/client_1//" -L"/u01/app/oracle/product/21.0.0/client_1//bin" -L"/u01/app/oracle/product/21.0.0/client_1//lib" -L"/u01/app/oracle/product/21.0.0/client_1//lib/amd64"  -lclntsh
postgres$ make install
/usr/bin/mkdir -p '/usr/pgsql-17/lib'
/usr/bin/mkdir -p '/usr/pgsql-17/share/extension'
/usr/bin/mkdir -p '/usr/pgsql-17/share/extension'
/usr/bin/mkdir -p '/usr/pgsql-17/doc/extension'
/usr/bin/install -c -m 755  oracle_fdw.so '/usr/pgsql-17/lib/oracle_fdw.so'
/usr/bin/install -c -m 644 .//oracle_fdw.control '/usr/pgsql-17/share/extension/'
/usr/bin/install -c -m 644 .//oracle_fdw--1.2.sql .//oracle_fdw--1.0--1.1.sql .//oracle_fdw--1.1--1.2.sql  '/usr/pgsql-17/share/extension/'
/usr/bin/install -c -m 644 .//README.oracle_fdw '/usr/pgsql-17/doc/extension/'
postgres$

The pg_upgrade command now works :-)
Thank you for your help. It is very much appreciation.

 time /usr/pgsql-17/bin/pg_upgrade --old-bindir /usr/pgsql-16/bin --new-bindir /usr/pgsql-17/bin --old-datadir /var/lib/pgsql/16/data --new-datadir /var/lib/pgsql/17/data  --check
Performing Consistency Checks on Old Live Server
------------------------------------------------
Checking cluster versions                                     ok
Checking database user is the install user                    ok
Checking database connection settings                         ok
Checking for prepared transactions                            ok
Checking for contrib/isn with bigint-passing mismatch         ok
Checking data type usage                                      ok
Checking for presence of required libraries                   ok
Checking database user is the install user                    ok
Checking for prepared transactions                            ok
Checking for new cluster tablespace directories               ok

*Clusters are compatible*

real    0m0.677s
user    0m0.060s
sys     0m0.079s
[postgres@postgres-dev oracle_fdw-ORACLE_FDW_2_7_0]$

With thanks again,

Adam.
