### ISSUE TITLE
Support mapping to postgresql boolean

### ISSUE THREAD

**Issue by nmoreaud** [laurenz/oracle_fdw#719]
Hello
I would like to map "NUMBER(1,0)" with postgresql boolean type.
I know I can create a view that handles the conversion, but it would be more practical if it was an option of the foreign table declaration.
Would it be possible to handle it as an option of the foreign tables?

**Comment by laurenz** [comment]
That should work out of the box. Just define the foreign table column with type `boolean`.

**Comment by nmoreaud** [comment]
This seems to work well with an alter table, thanks :-)
```sql
alter table "user_account" alter column "active" type boolean;
```

For now, I import tables with `IMPORT FOREIGN SCHEMA`.
If I use `IMPORT FOREIGN TABLE` instead, can I declare only the columns for which I want to adapt the type?

**Comment by laurenz** [comment]
No, there is no way to influence the data type `IMPORT FOREIGN SCHEMA` chooses on the PostgreSQL side.

**Comment by nmoreaud** [comment]
Okay, thanks
