### ISSUE TITLE
Timestamp problem

### ISSUE THREAD

**Issue by cachique** [laurenz/oracle_fdw#72]
I have a database created with all locales _es_PY-UTF8_.
I've done all the setting process without any problem. Setting a server, user mapping and importing a table.

But, when I try to select a timestamp field it gives me the following error...
oratest=# select * from oracle_ft ;
ERROR:  la sintaxis de entrada no es válida para tipo timestamp: «2012-12-18 08:14:21.752000000 DC»
CONTEXT:  converting column "fecha_alta" for foreign table scan of "oracle_ft", row 1
(something like Invalid input syntax for type timestamp.)

The **DC** part at the end is the spanish representation for **AD**.
If I change _lc_messages_ to en_US-UTF8 the error is gone. But I can do this only in the _postgresql.conf_ and restart the server.If I change with psql using SET the error persists.
Is this normal behavior?

Regards,
Walter

**Comment by laurenz** [comment]
It is a known bug, see #48.
I'll release a new version soon, in the meantime, either change lc_messages like you did or use the latest version from git.

Apologies for the inconvenience.
