### ISSUE TITLE
estimated release date and availability for max prefetch limit increase

### ISSUE THREAD

**Issue by PavanMedarametlaTR** [laurenz/oracle_fdw#722]
We have a use case for testing the performance of the max prefetch limit increase to 10,000.   Can you please provide estimated release date for this:    https://github.com/laurenz/oracle_fdw/commit/13ac9fb4e5ca5a515062b2c441d53079b0ec814d

**Comment by laurenz** [comment]
Probably fall of 2025, when PostgreSQL v18 comes out.
But don't hesitate to work with the latest development version. I'm trying to keep that in good shape, and no extra quality assurance takes place before a release.

**Comment by laurenz** [comment]
Is that fine with you? Can I close the issue?
