### ISSUE TITLE
Postgresql 17

### ISSUE THREAD

**Issue by crruiz0411** [laurenz/oracle_fdw#723]
![Oracle_FDW_extension](https://github.com/user-attachments/assets/34cef230-6cbd-4bca-a581-c9ae9de44622)
![Oracle_FDW_lib](https://github.com/user-attachments/assets/08b275ea-098f-41a1-b77b-2ab363684097)
![Oracle_FDW](https://github.com/user-attachments/assets/cd283e3e-00d6-4e7f-a88a-499f104040f3)
![Oracle_FDW_set](https://github.com/user-attachments/assets/1d3eba83-7525-44f2-89f3-fc0bd2daf054)

When I try to install Oracle_fdw on Postgresql 17 (Windows 2019) I receive this message:

ERROR:  cannot load library "D:/Program Files/PostgreSQL/17/lib/oracle_fdw.dll": The specified procedure could not be found.
 
 Does Oracle_fdw support Postgresql 17?
 
 Best Regards!

Cláudio Ruiz

**Comment by laurenz** [comment]
Yes, oracle_fdw supports PostgreSQL v17, if you use the latest version.

This seems to be a cryptic Windows error; perhaps there was some mistake during the build process.
- Do you have any other PostgreSQL versions installed?
- What is the exact Oracle software you are using? Instant client? Which version?
- Please describe how you built and installed oracle_fdw as detailed as possible.

**Comment by crruiz0411** [comment]
Hi Lourenz,

I'll get all informativo you ask and return as soon as possible.

Best Regards,

Cláudio Ruiz

Em qua., 11 de dez. de 2024 04:41, Laurenz Albe ***@***.***>
escreveu:

**Comment by laurenz** [comment]
Thanks for the feedback.
