### ISSUE TITLE
could not load library "C:/Program Files/PostgreSQL/9.5/lib/oracle_fdw.dll": The specified module could not be found.

### ISSUE THREAD

**Issue by joysu01** [laurenz/oracle_fdw#73]
When I execute the command: CREATE EXTENSION oracle_fdw WITH SCHEMA myschema;
I got this "could not load library "C:/Program Files/PostgreSQL/9.5/lib/oracle_fdw.dll": The specified module could not be found." error.

I have the oracle_fdw.dll in the C:/Program Files/PostgreSQL/9.5/lib/ directory and the C:/Program Files/PostgreSQL/9.5/lib is in my system path.

Could you kindly help why this error is thrown? Thanks.

**Comment by chrullrich** [comment]
Your Oracle client installation is not on the path used by the PostgreSQL service. This error can be misleading, here it indicates that a DLL required by oracle_fdw.dll is not found.

**Comment by joysu01** [comment]
My oracle client is installed on a remote linux machine. I am trying to query it from a postgresql database installed on my desktop with Windows 7. How do I put the Oracle client installation on my Path?

**Comment by chrullrich** [comment]
No, that is your Oracle server. The client is the Oracle package you put on your Windows machine to access the Oracle database directly, such as Instant Client.

**Comment by joysu01** [comment]
I installed the Oracle Instant Client and the problem is gone. Thank you
very much.
