### ISSUE TITLE
How to used ROWID in oracle_fdw?

### ISSUE THREAD

**Issue by sangli00** [laurenz/oracle_fdw#74]
hi @laurenz 
I create oracle_fdw table 

create foreign table test(
col1 text,
...
rowid text
);
why not used rowid?

**Comment by laurenz** [comment]
I'll think about supporting ROWID.
If it is easy, why not.

But what do you want to do with an Oracle ROWID in PostgreSQL?

**Comment by sangli00** [comment]
oracle table A is very big, I think used ROWID select data.
select * from oralce_fdw_table where rowid > '......';  
if table is not index,no partition, I think used rowid check data is good .

**Comment by sangli00** [comment]
I try to modify oracle_fdw.
used rowid 

 /* execute the query and get the first result row */
        result = checkerr(
                OCIStmtExecute(session->connp->svchp, session->stmthp, session->envp->errhp, (ub4)1, (ub4)0,
                        (CONST OCISnapshot *)NULL, (OCISnapshot *)NULL, OCI_DEFAULT),
                (dvoid *)session->envp->errhp, OCI_HTYPE_ERROR);

        if (result != OCI_SUCCESS && result != OCI_NO_DATA)
        {
                /* use the correct SQLSTATE for serialization failures */
                oracleError_d(err_code == 8177 ? FDW_SERIALIZATION_FAILURE : FDW_UNABLE_TO_CREATE_EXECUTION,
                        "error executing query: OCIStmtExecute failed to execute remote query",
                        oraMessage);
        }
running this is error.   
how to fixed it ?

**Comment by laurenz** [comment]
You didn't tell me *how* you modified oracle_fdw &hellip;

oracle_fdw will never push down a predicate like <tt>ROWID &gt; '&hellip;'</tt> because it does not push down string comparisons except <tt>=</tt> and <tt>&lt;&gt;</tt> because of character collation problems.
I recommend that you use the primary key instead.

**Comment by sangli00** [comment]
void
checkDataType(oraType oratype, int scale, Oid pgtype, const char *tablename, const char *colname)
{
        if(oratype == 20)
                return;
...
}
oratype this is others.  maybe this check is error .
ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-01406: fetched column value was truncated

**Comment by sangli00** [comment]
/* construct a "SELECT * FROM ..." query to describe columns */
        length += 14;
        query = oracleAlloc(length + 1);
        strcpy(query, "SELECT a.*,rowid FROM ");
        strcat(query, tablename);
        strcat(query, " a");
printf("%s\n",query);

**Comment by laurenz** [comment]
Can you point me to a commit in a repository rather than sending me code snippets without context?

You'd have to modify [<tt>oracleDescribe</tt>](https://github.com/laurenz/oracle_fdw/blob/master/oracle_utils.c#L994) in <tt>oracle_utils.c</tt> and handle <tt>SQLT_RDD</tt>.
It would be good to introduce a <tt>ORA_TYPE_ROWID</tt> in [<tt>oracle_fdw.h</tt>](https://github.com/laurenz/oracle_fdw/blob/master/oracle_fdw.h#L92).
Then handle the mapping between <tt>ORA_TYPE_ROWID</tt> and <tt>TEXTOID</tt> in [<tt>checkDataType</tt>](https://github.com/laurenz/oracle_fdw/blob/master/oracle_fdw.c#L3769).

But, as I said, that will not push down &gt; and &lt; comparisons.
Moreover, you could not map the ROWID of an Oracle row to a column in the foreign table, as the ROWID does not show up in DESCRIBE output.  That would require more complicated changes &hellip;
Why not use primary keys?

**Comment by sangli00** [comment]
PK is better,but i connect oracle database is not own,is third party,I need increment synchronization data in my postgres  DB. this table is 100 column no index no PK ,is very slowly .... i think used ROWID is quick

**Comment by laurenz** [comment]
Well, if the third party wants you to use the Oracle table, they should make it usable (which a table without a primary key is not).

Anyway, if you succeed in mapping ROWID with PostgreSQL strings, you could define a table as<br>
<tt>CREATE FOREIGN TABLE &hellip; OPTIONS (table '(SELECT ROWID, * FROM tab &hellip;)');</tt><br>
and use that.

One difficulty in mapping ROWID with strings is that the length of a ROWID can be large for Index Organized Tables; I don't know if it is possible to find a reasonable maximum. Also (I have to look that up) I think I remember that Oracle doesn't promise that a ROWID converted to a string will always work reliably.

**Comment by sangli00** [comment]
pipeline-# create foreign table fdw_xx(........)
pipeline-# Server oradb
pipeline-# Options (schema 'SAPSR3DB', table '(select ROWID,t.* from DU_GLTX_SHJH t)')
pipeline-# ;
CREATE FOREIGN TABLE
Time: 2.160 ms
pipeline=# select * from fdw_xx limit 1;
ERROR:  error describing remote table: OCIStmtExecute failed to describe table
DETAIL:  ORA-00903: invalid table name
Time: 70.665 ms
pipeline=#

**Comment by laurenz** [comment]
That only works with the latest version from git (which I assumed you were using since you started modifying he code).

**Comment by yecarrillo** [comment]
OPTIONS (table '(SELECT ... didn´t work on latest master zip from today

**Comment by yecarrillo** [comment]
My fault. To use a SELECT statement, do not include schema option.

**Comment by sangli00** [comment]
hi @laurenz 
I have a problem
pipeline=# select * from du_ccc_zsxx_zsxx_test;
ERROR:  column "zersda" of foreign table "du_ccc_zsxx_zsxx_test" cannot be converted to or from Oracle data type
pipeline=# 

column zersda is timestamp,

CREATE  foreign TABLE du_ccc_zsxx_zsxx_test
(
  cert_apply_no text,
  cert_no text,
  app_name text,
  certi_status text,
  rzjg_bm text,
  auth_proj_code text,
  cert_award_date date,
  cert_ori_no text,
  zersda timestamp
)
server oradb 
OPTIONS (schema 'SAPSR3DB', table 'DU_CCC_ZSXX_ZSXX');

in oracle
desc du_ccc_zsxx_zsxx
ZERSDA 					    TIMESTAMP(6)

**Comment by sangli00** [comment]
if i test this  is OK.
create table test_sl(x timestamp,y varchar2(100),z date);

insert into test_sl
select sysdate,'aaa',sysdate from dual;
commit;

create foreign table fdw_test_sl
	(
x timestamp,
Y text,
z timestamp
		)server oradb 
OPTIONS (schema 'SAPSR3DB', table 'TEST_SL');


pipeline=# select * from fdw_test_sl;
          x          |  y  |          z          
---------------------+-----+---------------------
 2016-04-07 15:25:25 | aaa | 2016-04-07 15:25:25
(1 row)

**Comment by sangli00** [comment]
@laurenz  my god ,  TIMESTAMP(6) is diff  TIMESTAMP .. my fault.

**Comment by laurenz** [comment]
Probably a table definition mismatch.

What do you get for <tt>DESC du_ccc_zsxx_zsxx</tt> in Oracle?
Compare these columns one by one with the foreign table columns.

**Comment by sangli00** [comment]
maybe,but if i used oracle table all columns ,like this;
create foreign table test(
all columns
..
..
..
)server oradb 
OPTIONS (schema 'SAPSR3DB', table 'DU_CCC_ZSXX_ZSXX');

select ZERSDA from test; is OK

----------------------------------------------
create foreign table test(
ZERSDA,
col1,
col2
)server oradb 
OPTIONS (schema 'SAPSR3DB', table 'DU_CCC_ZSXX_ZSXX');

select ZERSDA from test; is bad...

I don't what happen . oracle_fdw code is latest version from git.

**Comment by laurenz** [comment]
Yes, that cannot work.
oracle_fdw does not match columns by name, but by position.
So the first column in the foreign table always corresponds to the first Oracle table column.

**Comment by sangli00** [comment]
OK,I know thinks .
 .. I link you Facebook is ok?

**Comment by laurenz** [comment]
I don't do Facebook, so I don't mind.

**Comment by sangli00** [comment]
OK  ,it doesn't matter .
we will conversation in this .

**Comment by sangli00** [comment]
@laurenz  
pg function is push down in oracle?
in PG:select max(timestamp) from oracle_fdw;
function max is running PG not running   oracle?

**Comment by laurenz** [comment]
Right, there is no aggregate pushdown.

**Comment by sangli00** [comment]
OK
