### ISSUE TITLE
make errors

### ISSUE THREAD

**Issue by joysu01** [laurenz/oracle_fdw#75]
After I downloaded the oracle_fdw-ORACLE_FDW_1_3_0.zip source code and unzipped it. The make command generated a big list of errors. Following are the errors on the top of the list.

oracle_utils.c:22:17: error: oci.h: No such file or directory
oracle_utils.c:39: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'err_code'
oracle_utils.c:52: error: expected specifier-qualifier-list before 'dvoid'
oracle_utils.c:73: error: expected declaration specifiers or '...' before 'dvoid'
oracle_utils.c:73: error: expected declaration specifiers or '...' before 'sb4'
oracle_utils.c:73: error: expected declaration specifiers or '...' before 'ub2'
oracle_utils.c:73: error: expected declaration specifiers or '...' before 'ub2'
oracle_utils.c:73: error: expected declaration specifiers or '...' before 'sb2'
oracle_utils.c:74: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'checkerr'
oracle_utils.c:76: error: expected ')' before '*' token
oracle_utils.c:77: error: expected ')' before '*' token
oracle_utils.c:78: error: expected ')' before '*' token
oracle_utils.c:79: error: expected ')' before '*' token
oracle_utils.c:80: error: expected ')' before '*' token
oracle_utils.c:81: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'getOraType'
oracle_utils.c:82: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'bind_out_callback'
oracle_utils.c:83: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'bind_in_callback'
oracle_utils.c: In function 'oracleGetSession':
oracle_utils.c:95: error: 'OCIEnv' undeclared (first use in this function)

The last line is: make: *** [oracle_utils.o] Error 1.

**Comment by laurenz** [comment]
This is your problem:

> oracle_utils.c:22:17: error: oci.h: No such file or directory

You must install the C header files for Oracle and make sure that the environment variable ORACLE_HOME points to the Oracle installation while you build oracle_fdw.

**Comment by joysu01** [comment]
Yes, the problem is resolve after I installed the basic, sqlplus, and sdk packages of the oracle instant client. Thank you for your advice.

**Comment by joysu01** [comment]
However, when I am trying to create the oracle_fdw extension, I got the error below.

could not load library "/usr/pgsql-9.5/lib/oracle_fdw.so": libclntsh.so.12.1: cannot open shared object file: No such file or directory
