### ISSUE TITLE
Allow PostGIS geometries stored as RAW or BLOB

### ISSUE THREAD

**Issue by yecarrillo** [laurenz/oracle_fdw#76]
I have no oracle spatial license, so allowing store of postgis geometry type as RAW or BLOB on Oracle would be apreciated.

Oracle:
CREATE TABLE ORAUSER.ORATAB
(
  GID NUMBER(10,0) NOT NULL,
  GEOM1 LONG RAW
);

PostgreSQL:
CREATE FOREIGN TABLE oratab  (
	gid INTEGER,
        geom geometry

) SERVER oradb OPTIONS (table '(SELECT GID,GEOM FROM ORAUSER.ORATAB)');

**Comment by laurenz** [comment]
LONG RAW is out of the question, as it has long been deprecated by Oracle.

You don't need a license for Oracle Spatial, you only need [Oracle Locator](http://docs.oracle.com/cd/E11882_01/appdev.112/e11830/sdo_locator.htm#SPATL340) which is a subset of Spatial that requires no additional licensing.

The only use case for PostGIS support that I can see is to be able to access Oracle geometries from PostgreSQL. What is your use case?
