### ISSUE TITLE
ESRI ArcSDE support

### ISSUE THREAD

**Issue by yecarrillo** [laurenz/oracle_fdw#77]
Please add support for ESRI ArcSDE

http://www.gdal.org/drv_sde.html
https://github.com/OSGeo/gdal/tree/trunk/gdal/ogr/ogrsf_frmts/sde

**Comment by laurenz** [comment]
What is that Github project about? I cannot find any documentation.

I feel reluctant to support another third party product.
PostGIS is challenge enough, and that is at least open source.

There are other problems with an implementation:
- My knowledge of GIS is limited, and I have no experience with ESRI software.
- I don't think I can get access to ESRI software.

Perhaps if you can find someone who implements this for money, but even then it would be a problem that I cannot test, review and support the resulting code.

**Comment by vmora** [comment]
@yecarrillo ArcSDE is a different RDBMS altogether, not oracle related.

So this would be another FDW, i.e. another project.

**Comment by vpicavet** [comment]
True, nothing to do with Oracle FDW
You may be able to use this project though : https://github.com/pramsey/pgsql-ogr-fdw
