### ISSUE TITLE
Access to tables with other schemas and dblinks

### ISSUE THREAD

**Issue by lorenati** [laurenz/oracle_fdw#78]
In oracle with the user myuser and the schema myschema I can select this view:

select * from anotherschema.a_view@adblink

Can I do the same thing in oracle_fdw?  so far I have this:

CREATE SERVER oradb FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver 'MyServer');

CREATE USER MAPPING FOR postgres SERVER oradb OPTIONS (user 'myuser', password 'mypassword');

SET search_path = ds_oracle;

CREATE FOREIGN TABLE a_view (
		aid bigint,
		acolumn double precision
       ) SERVER oradb OPTIONS ( schema 'anotherschema', table 'a_view@adblink');

But I get this error when I perform a select of that table:

ERROR:  Oracle table "anotherschema"."a_view@adblink" for foreign table "a_view" does not exist or does not allow read access
DETAIL:  ORA-00942: table or view does not exist
HINT:  Oracle table names are case sensitive (normally all uppercase).
********** Error **********

ERROR:  Oracle table "anotherschema"."a_view@adblink" for foreign table "a_view" does not exist or does not allow read access
SQL state: HV00R
Detail: ORA-00942: table or view does not exist
Hint: Oracle table names are case sensitive (normally all uppercase).

Am I missing something? I've tried the names with uppercase also

**Comment by laurenz** [comment]
You won't be able to access a table via database link directly because oracle_fdw double quotes the schema and table name.

Create a synonym in Oracle and use that.

**Comment by lorenati** [comment]
I made a view (a_view_test) containing a select * from a_view@adblink; I get this error:

ERROR:  error describing remote table: OCIStmtExecute failed to describe table
DETAIL:  ORA-02070: database ADATABASE does not support set transaction in this context
ORA-02063: line preceding adblink
********** Error **********

**Comment by laurenz** [comment]
I could not find that specific restriction in the [Database Gateway for SQL Server User's Guide](http://docs.oracle.com/database/121/GMSWN/toc.htm), but it looks like you cannot have a serializable transaction involving this SQL server database.

Can you try the following with sqlplus to see if I am on the right track:

    SQL> SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    SQL> SELECT * FROM a_view@adblink;

and see if you get the same error message.
If yes, that is a limitation of Oracle Gateway for Microsoft SQL Server.

oracle_fdw needs serializable transactions to guarantee that DML operations work properly.

Why are you trying to access an SQL server database from with oracle_fdw via a Database Gateway link? That seems like a rather fragile architecture.
Have you considered using [tds_fdw](https://github.com/GeoffMontee/tds_fdw) for this table?

**Comment by lorenati** [comment]
> Why are you trying to access an SQL server database from with oracle_fdw via a Database Gateway link? That seems like a rather fragile architecture.

It is, by fortune, this will not continue, but I did found this scenario very interesting. Unfortunately I can't change the isolation level, but the level in sql server is read commited, if that's helpful

**Comment by laurenz** [comment]
First, did you try with sqlplus as I suggested?

I don't understand what you say about the isolation level, but then I don't know Microsoft SQL Server.
You normally set the isolation level with [SET TRANSACTION ISOLATION LEVEL](https://technet.microsoft.com/en-us/library/ms173763%28v=sql.105%29.aspx) in a database session, so you can change it.

**Comment by lorenati** [comment]
Hello, my bad, I didn't read your query properly and I thought you were talking about the sql server environment, this is the output of 

> SQL> SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
> SQL> SELECT * FROM a_view@adblink;

> ORA-02070: database ADATABASE does not support set transaction in this context
> ORA-02063: line preceding adblink
> 02070. 00000 -  "database %s%s does not support %s in this context"
> *Cause:    The remote database does not support the named capability in
>            the context in which it is used.
> *Action:   Simplify the SQL statement.

**Comment by laurenz** [comment]
Ok, so it is a limitation of Oracle.

You could ask Oracle why this is not documented and if there are any solutions (if you have a support contract).

**Comment by nboullis** [comment]
I’m not sure if I should open a new issue or re-use this one.

I’ve been given access to an Oracle server where some tables are available through a dblink. I’d like to access those tables from my PostgreSQL server.

I know very little about Oracle but, as far as I can tell, I have no permission to create a synonym, as suggested. Anyway, even if I could, I am using a (read-only) account that is shared with other users; I guess it would be terribly messy if each user created their own synonyms (or views or tables or whatever)…

Would it be possible to add an option for oracle_fdw’s foreign tables to access a table through a dblink?

**Comment by laurenz** [comment]
Please open a new issue for that.
You can refer to this one.
