### ISSUE TITLE
Any way that IMPORT FOREIGN SCHEMA set the key option automatically for the PK columns?

### ISSUE THREAD

**Issue by JMLessard** [laurenz/oracle_fdw#83]
I imported the foreign schema successfully, but I cannot perform any update, insert on the foreign tables.
It seems that the key option is only available with CREATE FOREIGN TABLE
Any plan to add this to the import?

**Comment by laurenz** [comment]
It should work just fine, but only for tables, not for views.

Can you provide a test case where it does not work for an Oracle table?
What do you get for `SELECT oracle_diag(<servername>)` ?

**Comment by JMLessard** [comment]
\prompt 'Foreing data warper name: ' fdw_name
\prompt 'Foreing DB connection string: ' fdb_cng_str
\prompt 'Foreing DB connection user: ' fdb_cng_usr
\prompt 'Foreing DB connection password: ' fdb_cng_pwd
\prompt 'Foreing schema: ' fdb_schema

DROP SERVER IF EXISTS :fdw_name CASCADE;
CREATE SERVER :fdw_name FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver :'fdb_cng_str');
CREATE USER MAPPING FOR CURRENT_USER SERVER :fdw_name OPTIONS (user :'fdb_cng_usr', password :'fdb_cng_pwd');

--Creating a schema for holding the foreign table definitions
DROP SCHEMA IF EXISTS ftab_def CASCADE;
CREATE SCHEMA ftab_def AUTHORIZATION CURRENT_USER;

IMPORT FOREIGN SCHEMA :"fdb_schema" FROM SERVER :fdw_name INTO ftab_def;

\echo Loading the sites table
INSERT INTO sites (SELECT * FROM ftab_def.sites);
INSERT 0 36

UPDATE ftab_def.sites SET cor_sit_cod=cod WHERE cod='TT191';
ERROR:  no primary key column specified for foreign Oracle table
DETAIL:  For UPDATE or DELETE, at least one foreign table column must be marked as primary key column.
HINT:  Set the option "key" on the columns that belong to the primary key.

**Comment by JMLessard** [comment]
SELECT oracle_diag(<servername>);
 oracle_fdw 1.3.0, PostgreSQL 9.5.1, Oracle client 10.2.0.5.0, Oracle server 11.2.0.3.0

**Comment by laurenz** [comment]
Ok, what do you get if you type

    SELECT constraint_name
    FROM all_constraints
    WHERE table_name = 'SITES' AND owner = 'FDB_SCHEMA' AND constraint_type = 'P';

in sqlplus (assuming that the Oracle schema is `FDB_SCHEMA`)?

**Comment by JMLessard** [comment]
CONSTRAINT_NAME
------------------------------
SIT_PK

**Comment by laurenz** [comment]
Mysterious.

What do you get for this query:

    SELECT col.table_name, col.column_name, col.data_type,
           CASE WHEN primkey_col.column_position IS NOT NULL THEN 1 ELSE 0 END AS primary_key
    FROM all_tab_columns col,
         (SELECT con.table_name, ind.column_name, ind.column_position
          FROM all_constraints con, all_ind_columns ind
          WHERE con.owner = ind.table_owner AND con.table_name = ind.table_name
            AND con.index_owner = ind.index_owner AND con.index_name = ind.index_name
            AND con.constraint_type = 'P' AND con.owner = 'IBISTST51') primkey_col
    WHERE col.table_name = primkey_col.table_name(+) AND col.column_name = primkey_col.column_name(+)
      AND col.owner = 'IBISTST51' AND col.table_name = 'SITES'
    ORDER BY col.table_name, col.column_id;

This is roughly the query that oracle_fdw runs to find the columns names and types and if they are primary keys or not. Can you run that for me?

Could there be an error in my query?

**Comment by laurenz** [comment]
I just committed 0ce95ab6c238b55fe5060a31ddac7f8ce6ac5f9f which might fix this problem; I followed the idea by @legrandlegrand even though I couldn't reproduce the problem.

Can you try if `IMPORT FOREIGN SCHEMA` works now?

**Comment by JMLessard** [comment]
I will try you fix latter today,

But, just to let you know, I found the issue with the original query. The inner view of your query returns no rows, the index_owner column is NULL.
Hum! strange, I ckecked on several db running on 11.1.0.7 and 11.2.0.3, and the column is always empty.

SELECT owner, constraint_name, table_name, index_owner, index_name FROM all_constraints con
WHERE con.owner='IBISTST51' AND con.table_name='SITES' AND con.constraint_type = 'P';
OWNER     CONSTRAINT_NAME TABLE_NAME INDEX_OWNER INDEX_NAME
--------- --------------- ---------- ----------- ----------
IBISTST51 SIT_PK          SITES                  SIT_PK

You can safely drop the where cause on the index_owner as there can be only one PK on a table; so the owner, table_name and index_name would be enough.
SELECT col.table_name, col.column_name, col.data_type,
       CASE WHEN primkey_col.column_position IS NOT NULL THEN 1 ELSE 0 END AS primary_key
FROM all_tab_columns col,
     (SELECT con.table_name, ind.column_name, ind.column_position
        FROM all_constraints con, all_ind_columns ind
       WHERE con.owner = ind.table_owner AND con.table_name = ind.table_name AND con.index_name = ind.index_name
         AND con.constraint_type = 'P' AND con.owner = 'IBISTST51' AND con.table_name = 'SITES') primkey_col
WHERE col.table_name = primkey_col.table_name(+) AND col.column_name = primkey_col.column_name(+)
  AND col.owner = 'IBISTST51' AND col.table_name = 'SITES'
ORDER BY col.table_name, col.column_id;

**Comment by laurenz** [comment]
Thanks for looking into this!

I used `ALL_CONS_COLUMNS` instead of `ALL_IND_COLUMNS` as @legrandlegrand suggested in #84, so the column `INDEX_OWNER` isn't checked any more.

**Comment by JMLessard** [comment]
Hi Laurenz,

Could you please send me the new dll file please

Thank you


Jean-Marc Lessard
Administrateur de base de données / Database Administrator
Ultra Electronics Forensic Technology Inc.
T +1 514 489 4247 x4164
www.ultra-forensictechnology.com<http://www.ultra-forensictechnology.com>

**Comment by laurenz** [comment]
Please send your e-mail adress to laurenz (dot) albe (at) wien (dot) gv (ot) at

**Comment by JMLessard** [comment]
It works just fine,
Thank you very much
