### ISSUE TITLE
ERROR:  could not load library:undefined symbol: OCICollGetElem

### ISSUE THREAD

**Issue by Iznakurnog** [laurenz/oracle_fdw#85]
After building ORACLE_FDW_1_4_0 without any errors I got library oracle_fdw.so without any necessary dependencies to oracle instant client libraries and expectedly extention was not operable.
CentOS 6.6
PostgreSQL 9.5.2
Oracle Instant Client 12.1

Steps to reproduce:
1) download from oracle  following packages:
instantclient-basic-linux.x64-12.1.0.2.0.zip 
instantclient-sdk-linux.x64-12.1.0.2.0.zip
instantclient-sqlplus-linux.x64-12.1.0.2.0.zip

2) unpack instantclient-basic-linux.x64-12.1.0.2.0.zip and instantclient-sqlplus-linux.x64-12.1.0.2.0.zip
to ~/distr/oracle/ora_instantclient_12_1/lib
and unpack instantclient-sdk-linux.x64-12.1.0.2.0.zip
to ~/distr/oracle/ora_instantclient_12_1/sdk

3) successfully test instant client. sqlplus is able to connect to oracle database

4) unpack   oracle_fdw-ORACLE_FDW_1_4_0.tar.gz to /export/home/postgres/distr/oracle_fdw_src
 
5) tune makefile to point to my oracle libraries as following:
PG_CPPFLAGS = -I/export/home/postgres/distr/oracle/ora_instantclient_12_1/sdk/include -I/export/home/postgres/distr/oracle/ora_instantclient_12_1/lib

SHLIB_LINK = -L/export/home/postgres/distr/oracle/ora_instantclient_12_1/lib

6) Now make
$ make clean install DESTDIR=/export/home/postgres/distr/oracle_fdw CC="gcc -Wl,-rpath,'\$\$ORIGIN/lib_instantclient'"

7) It is compiled and installed to DESTDIR without any errors... but ldd shows only few dependencies and no dependencies to oracle libraries
-bash-4.1$ ldd ~/distr/oracle_fdw/u01/pg5432/9.5/plugins/oracle_fdw/oracle_fdw.so
        linux-vdso.so.1 =>  (0x00007fff87ba4000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe14c7ff000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003fb2800000)

strange !!!

8) Copy compiled oracle_fdw to my postgres folder . fix oracle_fdw.control file to point to library location 
9) CREATE EXTENSION oracle_fdw;
ERROR:  could not load library "/u01/pg5446/9.5/app/lib/postgresql/../../../plugins/oracle_fdw/oracle_fdw.so": /u01/pg5446/9.5/app/lib/postgresql/../../../plugins/oracle_fdw/oracle_fdw.so: undefined symbol: OCICollGetElem
********** Error **********

ERROR: could not load library "/u01/pg5446/9.5/app/lib/postgresql/../../../plugins/oracle_fdw/oracle_fdw.so": /u01/pg5446/9.5/app/lib/postgresql/../../../plugins/oracle_fdw/oracle_fdw.so: undefined symbol: OCICollGetElem
SQL state: XX000

10) Finally I managed to guess which library it lacks. and add necessary dependency by patchelf utility

cd /u01/pg5432/9.5/plugins/oracle_fdw/
$ patchelf --add-needed libclntsh.so.12.1 oracle_fdw.so

11) This fixed an issue. Extention was successfully created and worked smoothly according to my tests

So though I find workaround it is probably an issue with building process...

**Comment by laurenz** [comment]
It seems like you forgot the `-l` option when you changed `SHLIB_LINK`.
If you don't tell the linker to link with the Oracle client library, it won't. The dependencies will then be unresolved, and loading will fail as you observed.

The recommended way is not to tinker with `Makefile`, but to set the environment variable `ORACLE_HOME` to where your Instant client is installed. Then everything should work fine.

**Comment by Iznakurnog** [comment]
Thanks for explanation **laurenz** So that was actually my fault. I occasionally removed
-l$(ORACLE_SHLIB) from SHLIB_LINK in Makefile so got the problem. That's due to my small experience with compiling. Now I read about -L and -l flags and know their meaning.
 I'm trying not to use extra env variables like ORACLE_HOME or LD_LIBRARY_PATH to get more easy deployment and portability - just unpack and use.  And this approach seems work fine up to now.
So cause that's not bug I will close an issue

**Comment by laurenz** [comment]
Good that your problem is solved.

I don't quite buy into the argument that it is easier to deploy and port that way; all you need is

    ORACLE_HOME=/export/home/postgres/distr/oracle/ora_instantclient_12_1 make ...
