### ISSUE TITLE
Improvement request - "WARNING:  remote schema ".." does not exist" should be an error, instead of a warning, like with the postgres_fdw.

### ISSUE THREAD

**Issue by JMLessard** [laurenz/oracle_fdw#86]
Minor improvement in order to be consitent with the postgres_fwd.
Here are test cases for postgres_fdw and oracle_fdw that show the different behavior between postgres_fdw and oracle_fdw.
Find attached the PLsql that create the server, user mapping and import the schema.

Testcase #1: postgres_fdw
============
SELECT credblink('dcx1.001.pg', 'user', 'pwd', 'data', 'postgres');
...
ERROR:  schema "data" is not present on foreign server "dcx1.001.pg"
CONTEXT:  SQL statement "IMPORT FOREIGN SCHEMA data FROM SERVER "dcx1.001.pg" INTO "dcx1.001.pg""

Testcase #2: oracle_fdw
============
SELECT credblink('svr1.tst.fti', 'ftsupport', 'expos', 'data', 'oracle');
...
WARNING:  remote schema "DATA" does not exist
HINT:  Enclose the schema name in double quotes to prevent case folding.
CONTEXT:  SQL statement "IMPORT FOREIGN SCHEMA "DATA" FROM SERVER "svr1.tst.fti" INTO "svr1.tst.fti""
```
credblink
------------------------------------------------------
 "svr1.tst.fti" foreign server created.
 "svr1.tst.fti" schema created.
DATA foreign schema imported into "svr1.tst.fti"
(3 rows)
-->It looks like it succeed, but it failed.

**Comment by laurenz** [comment]
Thanks for the report, this is actually a bugfix rather than an enhancement.

The SQL standard says:

> 12.7 <import foreign schema statement>
> [&hellip;]
> General Rules
> [&hellip;]
> 2) If *FSVR* does not maintain information about a schema *FS* whose name is equivalent to *FSN*, then an exception condition is raised: *FDW-specific condition — schema not found.*
