### ISSUE TITLE
psql session crashes when importing foreign schema and using os authentication in the user mapping.

### ISSUE THREAD

**Issue by JMLessard** [laurenz/oracle_fdw#94]
Instant client 10.2 is installed and I can connect / via sqlplus without problem to the foreign database as follow:
sqlplus /@dcx1.004.trig

An empty string for the user and password is provided to the user mapping as follow:
CREATE SERVER "dcx1.004.trig" FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver 'dcx1.004.trig');
CREATE USER MAPPING FOR CURRENT_USER SERVER "dcx1.004.trig" OPTIONS (user '', password '');
CREATE SCHEMA "dcx1.004.trig";
IMPORT FOREIGN SCHEMA "IBISL0" FROM SERVER "dcx1.004.trig" INTO "dcx1.004.trig";
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

**Comment by laurenz** [comment]
Can you tell me your operating system and the output from `SELECT oracle_diag()`?

This *could* be related to #89, which was fixed with d3882a2724d4106af9a92f7ac91a92b9a196e6f8.

Do you get the same crash when you run `SELECT oracle_diag('dcx1.004.trig')`?
Can you try and create a foreign table with CREATE FOREIGN TABLE and see what happens when you try to SELECT from that?

If my suspicion is correct, that would mean that external authentication somehow fails, and an error message would be displayed when you SELECT from a foreign table. Due to the bug fixed in the commit above, failed authentication causes a crash with oracle_diag with a server argument and in IMPORT FOREIGN SCHEMA.

**Comment by JMLessard** [comment]
Operating system (Postgres server) : 2012 R2

C:\Users\jmlessard>psql
jmlessard@dcx1-006-jml(ibis)=> SELECT oracle_diag();
oracle_fdw 1.3.0, PostgreSQL 9.5.1, Oracle client 10.2.0.5.0

1. Do you get the same crash when you run SELECT oracle_diag('dcx1.004.trig')?
jmlessard@dcx1-006-jml(ibis)=> SELECT oracle_diag('dcx1.004.trig');
server closed the connection unexpectedly

2. Can you try and create a foreign table with CREATE FOREIGN TABLE and see what happens when you try to SELECT from that?
jmlessard@dcx1-006-jml(ibis)=> CREATE FOREIGN TABLE "dcx1.004.trig".cases2(
...
) SERVER "dcx1.004.trig" OPTIONS (schema 'IBISL0', table 'CASES');

jmlessard@dcx1-006-jml(ibis)=> select * from "dcx1.004.trig".cases2;
ERROR:  session for foreign table "cases2" cannot be authenticated
DETAIL:  ORA-01005: null password given; logon denied

External authentication (OS authentication in our case) fails asking for a password,
but sqlplus connection with OS authentication successed as follow.
C:\Users\jmlessard>sqlplus /@dcx1.004.trig
SQL*Plus: Release 10.2.0.5.0 - Production on Mon Jun 6 11:35:25 2016
Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
IBISDOM4\JMLESSARD dcx1.004.trig>

**Comment by legrandlegrand** [comment]
maybe you could try using
 ... OPTIONS (user '/', password '');

**Comment by JMLessard** [comment]
Dropped and re-created user mapping 
CREATE USER MAPPING FOR CURRENT_USER SERVER "dcx1.004.trig" OPTIONS (user '/', password '');
but still have ORA-01005: null password given; logon denied

I enabled session auditing on the Oracle DB, and audit record are generated when connecting / with sqlplus from the PGserver, but the fdw connection does not generate a failed connection attempt?
It look that the Oracle DB does not received connection any from the fdw, but how if it is the case WHERE how come a oar connection attempt dioes not reach the server

**Comment by laurenz** [comment]
At least we know that the crash is the same problem as in issue #89 and is triggered by an authentication failure.

Setting the `user`option to '/' won't work: as the README states, you must set `user` to the empty string for external authentication (see [the relevant code](https://github.com/laurenz/oracle_fdw/blob/master/oracle_utils.c#L412)).

To help you with the underlying authentication problem, I'd need more information.

What is the name that Oracle uses for the authentication method you employ? Are you using a *Secure External Password Store* or are you using `OS_AUTHENT_PREFIX`?
Might it depend on environment variables that are not set correctly (e.g., `ORACLE_SID`)?
Perhaps a [trace](http://docs.oracle.com/cd/E11882_01/network.112/e41945/trouble.htm#NETAG429) can show where things go wrong.

**Comment by JMLessard** [comment]
I am using OS Authentication as defined in the client sqlnet.ora by
SQLNET.AUTHENTICATION_SERVICES = (NTS)
The OS_AUTHENT_PREFIX is explicitly set to an empty string (OS_AUTHENT_PREFIX='')
The db username is the DOMAIN\OSUSER

I enabled session auditing on the Oracle DB and the connection from the fwd does not generate any audit failed record.
It look like that the credential type of the OCISessionBegin() is not set to OCI_CRED_EXT and the oci call fails before it try connecting to the DB. See the legrandlegrand comment above.

**Comment by laurenz** [comment]
oracle_fdw uses `OCI_CRED_EXT` if the username is an empty string, see [here](https://github.com/laurenz/oracle_fdw/blob/master/oracle_utils.c#L412) in the code.
It worked in my tests with an external password store.
I will try using `OS_AUTHENT_PREFIX` and see if it works on my Linux system.

Please double check that the `user` option in the user mapping is set to an empty string.

**Comment by laurenz** [comment]
I just tested it on Linux (with `OS_AUTHENT_PREFIX = ops$` and `REMOTE_OS_AUTHENT = TRUE`) and it worked just fine&hellip;

Must be some setup problem on the Oracle side.

**Comment by laurenz** [comment]
When you tried sqlplus, did you use the same operating system user that runs the PostgreSQL server?
Is PostgreSQL started as a service on your computer?
Is the service run by a local user or a domain user?

I cannor really help with Windows native authentication, but maybe that gets you on the right track.

**Comment by JMLessard** [comment]
The pg_hba.conf is configured as follow to stripped off the realm from the user (include_realm=0) and no user mapping is defined.
host	all		all		0.0.0.0/0       sspi include_realm=0 krb_realm=ibisdom4

PostgreSQL runs as a service.
The service runs as Network Service.
I will modify the service to run as a domain user and see what happen.
Thanks for your help

**Comment by JMLessard** [comment]
I created a domain user named psotgres and modified the service to run PostgreSQL as the postgres domain user. The behaviour is different; now I receive an ora-1017.
```
jmlessard@dcx1-006-jml(ibis)=>  SELECT * FROM "dcx1.004.trig".cases;
ERROR:  session for foreign table "cases" cannot be authenticated
DETAIL:  ORA-01017: invalid username/password; logon denied
```
That time a failed connection is recorded in the audit trail.
`select DB_USER,OS_USER,OS_HOST,RETURNCODE from V$XML_AUDIT_TRAIL;`
DB_USER....................... OS_USER.................. OS_HOST.........................RETURNCODE
"-------------------------------- -------------------------- --------------------------------- ----------"
IBISDOM4\JMLESSARD..IBISDOM4\jmlessard..IBISDOM4\DCX1-006-JML ..........0.. <--sqlplus /
_(null)_.................................**postgres**...................IBISDOM4\DCX1-006-JML .....1017.. <--oracle_fdw

The fdw connect as the OS user of backend process which runs under the service credential (the postgres domain user in bold above, but curiously without the domain name. I would have expected ibisdom4\postgres).
Moreover, creating an Oracle DBuser named postgres does not either work. Note that the DB_USER field above in italic that is empty, strange? 

Conclusion: The backend process unpersonify the real OSuser running the psql client which we expect in OSAuthentication. The front end does not forward the osuser to the backend.

**Comment by laurenz** [comment]
The only user that counts is the operating system user under which the PostgreSQL server process runs, the User who starts `psql` or the contents of `pg_hba.conf` do not influence this problem.

Do you mean that in the original configuration you did not get an audit log entry?

If you login as PostgreSQL operating system user, can you connect with `sqlplus /@dcx1.004.trig`?
If yes, try to start the PostgreSQL server manually with `pg_ctl start`.
Does that make the problem go away? If yes, the problem might be connected with the fact that PostgreSQL is running as a service.

I am quite out of my depth here, maybe a Windows system administrator can give some insight.

**Comment by legrandlegrand** [comment]
as a workarround,
wouldn't it be possible to
 **create user postgres identified externally;**
in that oracle database ?
1. 

 in thisostgres identi

**Comment by legrandlegrand** [comment]
did you try testing with
create user "postgresql" identified externally;

in case authentication is case sensitive.

for the domain, I remember about osauth_prefix_domain ... that oracle_fdw / oracle instant client would maybe not using the same way

**Comment by JMLessard** [comment]
Laurenz wrote: Do you mean that in the original configuration you did not get an audit log entry?
JMlessard: Yes, when the PostgreSQL service is running as NETWORK SERVICES, I receive an ORA-1005 and there is no audit log entry.

When the PostgreSQL service is running as the domain user IBIDOM4\postgres, I receive an ORA-1017, there is an audit log entry, but the DBUSER is empty as follow.
DB_USER....................... OS_USER.................. OS_HOST.........................RETURNCODE
"-------------------------------- -------------------------- --------------------------------- ----------"
`(null)`.............................**postgres**...................IBISDOM4\DCX1-006-JML .....1017 

When I start manually the PostgreSQL with pg_ctl_start the fwd connect successfully
DB_USER....................... OS_USER.................. OS_HOST.........................RETURNCODE
"-------------------------------- -------------------------- --------------------------------- ----------"
IBISDOM4\POSTGRES....I**BISDOM4\postgres**..IBISDOM4\DCX1-006-JML ..........0

You may close the issue, I do not think it worth digging more on this. It may be considered as a know issue.
Thanks

**Comment by laurenz** [comment]
You already closed the issue :^)

I think the problem is with setting up and using Windows Native Authentication.
Did you try to start PostgreSQL with `pg_ctl start` and see if it works then?

**Comment by JMLessard** [comment]
Yes it does work when PostgreSQL is started with pg_ctl start

**Comment by laurenz** [comment]
Seems like Windows handles users differently when the process is run as a service.
Or it is an Oracle problem &ndash; you could ask Oracle.

**Comment by chrullrich** [comment]
I don't have the first idea about how Oracle's external auth works, but if it is just plain Kerberos, you can try to configure the (PostgreSQL) service account, or the computer account of the PostgreSQL server, to be "trusted for delegation". Not sure which of the two, but I think it's the service account when used, and the computer account with PostgreSQL running as NETWORK SERVICE.

Also, read up on Kerberos "double hop" authentication, when you have a spare week or two.

(Forwarding the PostgreSQL user identity may work with that option on, it cannot work without.)

**Comment by JMLessard** [comment]
nice, 
thanks chrullrich
