### ISSUE TITLE
How to fix "oracle_utils.c:22:17: fatal error: oci.h"?

### ISSUE THREAD

**Issue by diddlybop** [laurenz/oracle_fdw#95]
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/DBMS/pgsql/include/server -I/DBMS/pgsql/include/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_utils.o oracle_utils.c
oracle_utils.c:22:17: fatal error: oci.h: No such file or directory
 #include <oci.h>
                 ^
compilation terminated.
make: *** [oracle_utils.o] error 1

when I compile oracle_fdw folder I got a this message...

plz help me

**Comment by laurenz** [comment]
As the REAME says, set the environment variable ORACLE_HOME so that it points to the directory where Oracle client is installed.
Also, make sure that you have the Oracle SDK files installed there (they include header files like `oci.h`).

**Comment by diddlybop** [comment]
I installed Oracle instant client and SDK  in directory /root/instantclient_12_1.
and then I changed bash_profile in pgdba user like that.
![aa](https://cloud.githubusercontent.com/assets/19543285/15889037/67d3cb9e-2da4-11e6-8ab7-6a3fd3202612.png)

**Comment by laurenz** [comment]
Several comments:

- The environment variable `ORACLE_HOME` must be in uppercase.  
  That's probably your problem.
- `/etc/ld.so.conf` and `lconfig` is better than `LD_LIBRARY_PATH`, although both should work.  
  They are only needed in the environment of the PostgreSQL server process, not during build.
- Are you building software and/or running PostgreSQL as user `root`? If yes, think again.

**Comment by diddlybop** [comment]
I built PostgreSQL as user pgdba.
I changed the environment variable ORACLE_HOME in uppercase and changed Path /etc/ld.so.conf...
but it doesn't work ... I get another error. haha... I will try again!!

**Comment by laurenz** [comment]
So `make` can find `oci.h` now? Good.
Tell me if you get stuck.

**Comment by diddlybop** [comment]
It's working!!!! Thank you bro.
I love you

**Comment by laurenz** [comment]
You are welcome.

**Comment by keating178** [comment]
@laurenz
I am running into the same issue as the one stated above, ( I have included screenshots).
I am getting an error when tryin to run "make" of a certain wrapper.
I am getting the error message stating "oci.h no such file or directory" but the file clearly exists.

Can you shed some light on what might be happening or what I might be doing wrong?

Thanks,

![wrapper 1](https://user-images.githubusercontent.com/45406216/56397997-57d87580-61fb-11e9-8bbb-a61565f3d3e3.JPG)
![wrapper 2](https://user-images.githubusercontent.com/45406216/56397998-57d87580-61fb-11e9-81dc-3a5cbcf9cb81.JPG)

**Comment by laurenz** [comment]
The path to Oracle 18.3 was added by commit b2fc87691ee6f35ebe24c6faa1148837f0995101.

Either get the [latest development version](../archive/master.zip) or edit `Makefile` manually.

**Comment by keating178** [comment]
@laurenz 
(screenshot attached)
I have updated my instantclient to 18.5 due to an ask from my team, as well as downloaded the above "fdw_master" package you supplied but I am getting new errors, is this because I updated to 18.5? Should I have stayed at 18.3?
Where would I find an updated "fdw_master" file that is suitable for the updated "oracle instantclient" for when I have to upgrade or rebuild these servers in the future?
![Yay More Errors](https://user-images.githubusercontent.com/45406216/56436007-3e810900-628f-11e9-954f-39af18af03a7.JPG)

**Comment by laurenz** [comment]
This has nothing to do with `oci.h`.

Please open a new issue for this.

And do *not* add screen shots, rather copy and paste the messages.
This is easier to read for me, and helps other who may have a similar problem to find it with a web search.
