### ISSUE TITLE
Server closed Unexpectedly   - remote Oracle DB connection

### ISSUE THREAD

**Issue by jjgallow** [laurenz/oracle_fdw#96]
Hi there,  I believe I've set up my connection paramaters correctly, and I'm able to successfully connect to a LOCAL oracle DB using oracle_fdw.

However, when I try to connect to a Remote Oracle DB (tried many of them, many combinations etc), I get the following error:

pgdb=# select * from remote_oracle_table;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!>

The Same connection using SQLPLUS is successful.

This is a virtual machine in a considerably secure IT environment.  However, the equivalent SQLPLUS connection does work.   

Any suggestions?

**Comment by jjgallow** [comment]
From postgresql logs:

DETAIL:  Failed process was running: select * from remote_oracle_table;
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally an\
d possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
FATAL:  the database system is in recovery mode
LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted; last known up at 2016-06-16 23:44:50 MDT
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  record with zero length at 1DD6/150CBB80
LOG:  redo is not required
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
LOG:  server process (PID 23307) was terminated by signal 11: Segmentation fault

**Comment by laurenz** [comment]
What is your operating system?

Can you run `SELECT oracle_diag()` and tell me what you get?

Do you have problems with all foreign tables or just with a certain one?
If only a certain table causes the problem, it would be good to know the Oracle and PostgreSQL table definitions.

Can you get a stack trace from the crash? That would help immensely. See [here](https://wiki.postgresql.org/wiki/Generating_a_stack_trace_of_a_PostgreSQL_backend) for instructions.

**Comment by jjgallow** [comment]
Thank you laurenz,

"oracle_fdw 1.2.0, PostgreSQL 9.2.10, Oracle client 12.1.0.1.0, ORACLE_HOME=/wrrnddbprd/san/bin/oracle/oracle0/12.1.0, ORACLE_SID=local_database"

I will work on the stack trace.  It appears to be all foreign tables.

Is possible that I Shouldn't have the ORACLE_SID set as an environment variable?   It's set to the local database, which is the only one that works.     

SELECT oracle_diag('foreign_database')

returns:

ERROR:  server "foreign_database" does not exist
********** Error **********
ERROR: server "foreign_database" does not exist
SQL state: 42704

**Comment by jjgallow** [comment]
Solved!

Ah, Bad connection string.

Sometimes, easy connect isn't so easy.  (although it works for SQLPLUS)

For my setup, I needed the full connection string:

CREATE SERVER pdspawn FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=myhost.com)(Port=1521))(CONNECT_DATA=(SID=FOREIGN_DATABASE)))');

**Comment by laurenz** [comment]
Good.

Still, a `SELECT` statement should not crash if the credentials are wrong.
Could you try the `SELECT` with oracle_fdw 1.4.0 and bad credentials?
