### ISSUE TITLE
Query SDE layer through Oracle Spatial

### ISSUE THREAD

**Issue by jjgallow** [laurenz/oracle_fdw#97]
Hi there,

One other quick issue I ran into:

CREATE FOREIGN TABLE WATER_PRESSURE_ZONE (geom text) SERVER pdspawn OPTIONS (table '(SELECT **sde.st_astext(shape)** a FROM FOREIGN_TABLE)');

When I run the above query, I get the following error:

ERROR: error describing remote table: OCIStmtExecute failed to describe table
SQL state: HV00M
Detail: ORA-00972: identifier is too long

When I run the same query through SQLPLUS, it runs fine.    Is it possible to call an SDE function through oracle spatial, using oracle_FDW?  

ps....In my case, I am unable to create a view in the Oracle Spatial schema (or I would go that route)

**Comment by laurenz** [comment]
Strange &ndash; I wonder where that identifier is generated.

What are the Oracle versions involved? Try

    SELECT oracle_diag('<foreign server>');

Could you run the following query in sqlplus:

    SELECT * FROM (SELECT sde.st_astext(shape) a FROM FOREIGN_TABLE) WHERE rownum = 1;

Then please tell me the exact output you get (I am only interested in the column name).

**Comment by jjgallow** [comment]
Thank you laurenz,

"oracle_fdw 1.2.0, PostgreSQL 9.2.10, Oracle client 12.1.0.1.0, ORACLE_HOME=/wrrnddbprd/san/bin/oracle/oracle0/12.1.0"

It returns the column name "A".   Is it possible that oracle_FDW doesn't handle extproc well?
https://desktop.arcgis.com/en/arcmap/latest/manage-data/using-sql-with-gdbs/configure-oracle-extproc.htm

The listeners are all set up on the server, SQLPLUS and other apps can utilize it.  But for some reason not in oracle_fdw.   It would be a Really good feature to have, the ability to access ST_GEOMETRY functions.

Thanks laurenz!

**Comment by laurenz** [comment]
All that oracle_fdw does in the call that fails is execute the above query with the `OCI_DESCRIBE_ONLY` flag set to get the Oracle column names, types etc.; see [here](https://github.com/laurenz/oracle_fdw/blob/master/oracle_utils.c#L826).

I don't know what to do with this &ndash; is there a chance that you can get an Oracle server trace for this and look for the cause of the error and send it to me?
It might well be an Oracle bug; any chance you can open a service request and ask them?

**Comment by laurenz** [comment]
I have created a little C program contained in [ocidesc.zip](https://github.com/laurenz/oracle_fdw/files/328117/ocidesc.zip) that should trigger the same error.

Unzip and edit it, setting the correct values for `DB_USER`, `DB_PASSWD` and `DB_CONNSTR`.
Then compile it on Linux using

    gcc -o ocidesc -I <includedir> -L <libdir>  -Wl,-rpath,<libdir> -l clntsh ocidesc.c

or on Windows using

    cl /I <includedir> ocidesc.c <libdir>\oci.lib

where `<includedir>` is the directory containing `oci.h` and `<libdir>` the directory containing `libclntsh.do` or `oci.lib`.

Then run it and enter the SQL statement that causes the problem, e.g.

    SELECT * FROM (SELECT sde.st_astext(shape) a FROM FOREIGN_TABLE)

See if the same error is thrown.

If yes, that could help greatly when you open a Service Request with Oracle; then they can hopefully reproduce your problem.

**Comment by laurenz** [comment]
I'll close the issue; please reopen it if you have more information.
