### ISSUE TITLE
Error with Primary Key

### ISSUE THREAD

**Issue by DFuster** [laurenz/oracle_fdw#98]
Good morning.
I am using ORACLE_FDW to create FOREIGN tables for read  only and also  writing, writing tables using the primary key using OPTIONS (key 'true') in the respective columns.
With version 1.3 had a problem with dates so we had to return to version 1.2.
Currently installed version postgreSQL 9.5 with Oracle_fdw 1.4 and that problem does not happen being OK, but when performing DELETE or UPDATE get the message:

org.postgresql.util.PSQLException: ERROR: DELETE on Oracle table 0 rows removed in one iteration INSTEAD OF 1
   Hint: This Means That You probably did not set the "key" option on all primary key columns

We review the definition of the foreign table with OPTIONS (key 'true') and follows the problem, return to  OracleFDW 1.2 and PostgreSQL 9.4 and everythings is OK, is a bug in version 1.4? It has been corrected?
Thank you for your attention

**Comment by laurenz** [comment]
There was a bug with the way `date`s and `timestamp`s were handled in DML operations, see commit 76cb66bd6a9eef9222c96ed3a0e73a35611d1166.
It may well be that this is the problem you experience, but it is hard to be certain because you don't show much detail.

- Could you try with the [latest version from git](https://github.com/laurenz/oracle_fdw/archive/master.zip) and see if the problem persists?
- If that does not fix the problem, could you send me the Oracle and PostgreSQL table definitions as well as the data in the row that you cannot delete?

**Comment by DFuster** [comment]
the table definition in Oracle is : 

create table GISMAP.PROG_RT
(
 cod_1            NUMBER(3) not null,
  cod_r             VARCHAR2(30) not null,
  vehiculo             VARCHAR2(30),
  secuencia            NUMBER,
  cod_si NUMBER not null,
  cod_pi    NUMBER,
  cod_sf   NUMBER not null,
  cod_pfl      NUMBER,
  hora_arribo_ini      DATE,
  hora_partida         DATE,
  fecha                DATE not null,
)
alter table GISMAP.PROG_RT
 add constraint PK_PROG_RT primary key (COD_1, FECHA, COD_R, COD_SI, COD_SF)


and the table definition in PostgreSQL is : 

CREATE FOREIGN TABLE ruteo.solution
   (cod_1 integer OPTIONS (key 'true'),
    cod_r character varying OPTIONS (key 'true'),
    vehiculo character varying ,
    secuencia integer ,
    cod_si integer OPTIONS (key 'true') NOT NULL,
    cod_pi integer ,
    cod_sf integer OPTIONS (key 'true') NOT NULL,
    cod_pf integer ,
    hora_ini_s timestamp without time zone ,
    hora_fin_s timestamp without time zone ,
    fecha timestamp without time zone OPTIONS (key 'true'),)
   SERVER ora_db
   OPTIONS (schema 'GISMAP', table 'PROG_RT');
ALTER FOREIGN TABLE ruteo.solution
  OWNER TO postgres

Using  PostgreSQL 9.4 and Oracle_fdw 1,2 works correctly, but  with PostgrSQL 9.5 and Oracle_FDW 1.4 error occurs.

**Comment by laurenz** [comment]
I get an error with the current development version too.
Working on it.

**Comment by laurenz** [comment]
This problem was introduced in 1.3.0.
The fix in 76cb66bd6a9eef9222c96ed3a0e73a35611d1166 had an oversight, and I just made a commit that should fix that.

Could you try with the latest version from git and see if it works for you?

**Comment by laurenz** [comment]
I'll close this because I think it is fixed.
Don't hesitate to reopen it if the problem persists.
